In [2]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re
import numpy as np

In [4]:
#target1,2,3 : Q2, Q3 우세
path = '/content/gdrive/My Drive/2025_dacon_etri/data/'

train_file_name3 = "submission_0.6350958281670923_lightgbm.csv"
submission_df3 = pd.read_csv(path+train_file_name3, encoding='utf8')

In [5]:
submission_df3.head(10)

  subject_id  sleep_date lifelog_date  Q1  Q2  Q3  S1  S2  S3
0       id01  2024-07-31   2024-07-30   0   1   0   1   1   1
1       id01  2024-08-01   2024-07-31   0   1   0   0   1   1
2       id01  2024-08-02   2024-08-01   0   0   1   0   0   1
3       id01  2024-08-03   2024-08-02   1   0   0   1   1   1
4       id01  2024-08-04   2024-08-03   1   1   1   1   1   1
5       id01  2024-08-06   2024-08-05   0   0   0   0   1   1
6       id01  2024-08-07   2024-08-06   1   0   0   0   0   1
7       id01  2024-08-09   2024-08-08   1   0   0   0   1   1
8       id01  2024-08-10   2024-08-09   1   0   0   1   1   1
9       id01  2024-08-12   2024-08-11   0   1   1   1   1   1

In [7]:
#target1,2,3 : S1, S3 우세
path = '/content/gdrive/My Drive/2025_dacon_etri/data/'

train_file_name2 = "submission_0.6359383853269983_xgboost.csv"
submission_df2 = pd.read_csv(path+train_file_name2, encoding='utf8')

In [8]:
submission_df2.head(10)

  subject_id  sleep_date lifelog_date  Q1  Q2  Q3  S1  S2  S3
0       id01  2024-07-31   2024-07-30   0   1   0   1   1   1
1       id01  2024-08-01   2024-07-31   0   0   0   0   1   1
2       id01  2024-08-02   2024-08-01   0   0   1   0   1   1
3       id01  2024-08-03   2024-08-02   1   0   0   1   1   1
4       id01  2024-08-04   2024-08-03   1   1   1   1   1   1
5       id01  2024-08-06   2024-08-05   0   0   0   0   1   1
6       id01  2024-08-07   2024-08-06   0   0   0   0   0   1
7       id01  2024-08-09   2024-08-08   0   0   0   0   1   1
8       id01  2024-08-10   2024-08-09   1   0   0   0   1   1
9       id01  2024-08-12   2024-08-11   0   1   1   1   1   1

In [10]:
#target1,2,3 : Q1, S2 우세
path = '/content/gdrive/My Drive/2025_dacon_etri/data/'

train_file_name1 = "submission_0.6383372929850419_catboost.csv"
submission_df = pd.read_csv(path+train_file_name1, encoding='utf8')

In [11]:
submission_df.head(10)

  subject_id  sleep_date lifelog_date  Q1  Q2  Q3  S1  S2  S3
0       id01  2024-07-31   2024-07-30   0   1   1   1   1   1
1       id01  2024-08-01   2024-07-31   0   0   0   0   1   1
2       id01  2024-08-02   2024-08-01   0   0   1   0   1   1
3       id01  2024-08-03   2024-08-02   1   0   0   1   1   1
4       id01  2024-08-04   2024-08-03   1   1   1   1   1   1
5       id01  2024-08-06   2024-08-05   0   0   0   0   1   1
6       id01  2024-08-07   2024-08-06   1   0   0   0   0   1
7       id01  2024-08-09   2024-08-08   1   0   0   0   1   1
8       id01  2024-08-10   2024-08-09   1   0   0   1   1   1
9       id01  2024-08-12   2024-08-11   0   1   1   1   1   1

In [12]:
submission_df["S1"] = submission_df2["S1"]
submission_df["S3"] = submission_df2["S3"]

In [13]:
submission_df["Q2"] = submission_df3["Q2"]
submission_df["Q3"] = submission_df3["Q3"]

In [14]:
submission_df.head(10)

  subject_id  sleep_date lifelog_date  Q1  Q2  Q3  S1  S2  S3
0       id01  2024-07-31   2024-07-30   0   1   0   1   1   1
1       id01  2024-08-01   2024-07-31   0   1   0   0   1   1
2       id01  2024-08-02   2024-08-01   0   0   1   0   1   1
3       id01  2024-08-03   2024-08-02   1   0   0   1   1   1
4       id01  2024-08-04   2024-08-03   1   1   1   1   1   1
5       id01  2024-08-06   2024-08-05   0   0   0   0   1   1
6       id01  2024-08-07   2024-08-06   1   0   0   0   0   1
7       id01  2024-08-09   2024-08-08   1   0   0   0   1   1
8       id01  2024-08-10   2024-08-09   1   0   0   0   1   1
9       id01  2024-08-12   2024-08-11   0   1   1   1   1   1

In [15]:
submission_file_name = "submission_3_ensemble.csv"
submission_df.to_csv(path+submission_file_name, index=False)
print(f"Saved 'finished")

Saved 'finished

In [16]:
submission_df.head()

  subject_id  sleep_date lifelog_date  Q1  Q2  Q3  S1  S2  S3
0       id01  2024-07-31   2024-07-30   0   1   0   1   1   1
1       id01  2024-08-01   2024-07-31   0   1   0   0   1   1
2       id01  2024-08-02   2024-08-01   0   0   1   0   1   1
3       id01  2024-08-03   2024-08-02   1   0   0   1   1   1
4       id01  2024-08-04   2024-08-03   1   1   1   1   1   1