In [1]:
from transformers import LlamaTokenizer, LlamaForSequenceClassification,TrainingArguments, Trainer
import pandas as pd
import torch
from torch import nn
from huggingface_hub import login
import os
from torch.utils.data import Dataset
import numpy as np

2025-05-28 12:21:57.228743: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1748434917.416825      35 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1748434917.475569      35 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered

In [2]:
import pandas as pd
import torch
from torch import nn
import numpy as np
import re
from transformers import LlamaTokenizer, LlamaForCausalLM
from transformers import AutoTokenizer
from transformers import AutoModelForSequenceClassification, LlamaForSequenceClassification
from peft import (
    LoraConfig,
    get_peft_model,
    get_peft_model_state_dict,
)
from tqdm import tqdm

from torch.utils.data import Dataset
from torch.utils.data import DataLoader
from torchmetrics import Accuracy

In [3]:
# set random seed
def seed_everything(seed: int):
    import random, os
    import numpy as np
    import torch
    
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = True
    
    
seed_everything(seed=42)

In [4]:
import wandb
wandb.login(key="5fa8dfb2c5be3c888bfe0101437a8fa22fbdf0e0")
wandb.init(project="etri_lifelog", entity="byc3230")

wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: No netrc file found, creating one.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: byc3230 to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

In [5]:
import pandas as pd
train = pd.read_csv('/kaggle/input/dacon-etri-lifelog-best-score-baseline-xgboost/train_0512.csv')

In [6]:
test = pd.read_csv('/kaggle/input/dacon-etri-lifelog-best-score-baseline-xgboost/test_0512.csv')

In [7]:
# 숫자형 컬럼만 선택해서 결측값 -1로 채우기
train[train.select_dtypes(include='number').columns] = train.select_dtypes(include='number').fillna(-1)

In [8]:
test[test.select_dtypes(include='number').columns] = test.select_dtypes(include='number').fillna(-1)

In [9]:
train.head()

,subject_id,sleep_date,lifelog_date,Q1,Q2,Q3,S1,S2,S3,charging_ratio,...,m_light_awake_blocks,w_light_awake_minutes,w_light_awake_blocks,awake_minutes,awake_blocks,pred_exe_flag,act_exe_flag,gps_exe_flag,hr_exe_flag,pedo_exe_flag
0,id01,2024-06-27,2024-06-26,0,0,0,0,0,1,0.215859,...,1.0,17.0,3.0,17.0,3.0,0,0,0,0,0
1,id01,2024-06-28,2024-06-27,0,0,0,0,1,1,0.158571,...,1.0,14.0,3.0,14.0,3.0,0,0,0,0,0
2,id01,2024-06-29,2024-06-28,1,0,0,1,1,1,0.180282,...,1.0,0.0,0.0,4.0,1.0,0,0,0,0,0
3,id01,2024-06-30,2024-06-29,1,0,1,2,0,0,0.286567,...,1.0,0.0,0.0,1.0,1.0,0,0,0,0,0
4,id01,2024-07-01,2024-06-30,0,1,1,1,1,1,0.144286,...,1.0,0.0,0.0,2.0,1.0,0,0,0,0,0

In [10]:
test.head()

,subject_id,sleep_date,lifelog_date,Q1,Q2,Q3,S1,S2,S3,charging_ratio,...,m_light_awake_blocks,w_light_awake_minutes,w_light_awake_blocks,awake_minutes,awake_blocks,pred_exe_flag,act_exe_flag,gps_exe_flag,hr_exe_flag,pedo_exe_flag
0,id01,2024-07-31,2024-07-30,0,0,0,0,0,0,0.245324,...,-1.0,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
1,id01,2024-08-01,2024-07-31,0,0,0,0,0,0,0.428676,...,-1.0,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
2,id01,2024-08-02,2024-08-01,0,0,0,0,0,0,0.172611,...,-1.0,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
3,id01,2024-08-03,2024-08-02,0,0,0,0,0,0,0.270290,...,-1.0,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0
4,id01,2024-08-04,2024-08-03,0,0,0,0,0,0,0.163830,...,-1.0,-1.0,-1.0,-1.0,-1.0,0,0,0,0,0

In [11]:
# 함수 밖에서 한 번만 정의
target_cols = ['Q1', 'Q2', 'Q3', 'S1', 'S2', 'S3']
feature_cols = [col for col in train.columns if col not in target_cols]

In [12]:
#feature_cols = ["total_screen_time", "wake_up_early_minutes", "speed_le5_max", "rolling_wake_time_3d", "rolling_sleep_time_3d", "sleep_time_diff", "wlight_evening_mean", "hr_evening_std"]
feature_cols = ['subject_id', 'sleep_date', 'lifelog_date',"light_max", "light_night_ratio","hr_evening_max", "lat_change", "vehicle_minutes", "hr_afternoon_std"]

In [13]:
def prepare_input_text(row):
    target_cols = ['Q1', 'Q2', 'Q3', 'S1', 'S2', 'S3']
    #feature_cols = [col for col in train.columns if col not in target_cols]

    instruct_txt = "Classify the self-reported stress level just before sleep. Use 0 if High stress level, and 1 if Low stress level.###DATA### "
    for clm in feature_cols:
        instruct_txt += f"{clm} : {row[clm]}, "

    return instruct_txt.strip()[:-1]+'.'

In [14]:
print(feature_cols)

['subject_id', 'sleep_date', 'lifelog_date', 'light_max', 'light_night_ratio', 'hr_evening_max', 'lat_change', 'vehicle_minutes', 'hr_afternoon_std']

In [15]:
train.head(1)

,subject_id,sleep_date,lifelog_date,Q1,Q2,Q3,S1,S2,S3,charging_ratio,...,m_light_awake_blocks,w_light_awake_minutes,w_light_awake_blocks,awake_minutes,awake_blocks,pred_exe_flag,act_exe_flag,gps_exe_flag,hr_exe_flag,pedo_exe_flag
0,id01,2024-06-27,2024-06-26,0,0,0,0,0,1,0.215859,...,1.0,17.0,3.0,17.0,3.0,0,0,0,0,0

In [16]:
train['input'] = train.apply(lambda x: prepare_input_text(x),axis=1)

/tmp/ipykernel_35/1472349885.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  train['input'] = train.apply(lambda x: prepare_input_text(x),axis=1)

In [17]:
test['input'] = test.apply(lambda x: prepare_input_text(x),axis=1)

/tmp/ipykernel_35/2802783739.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test['input'] = test.apply(lambda x: prepare_input_text(x),axis=1)

In [18]:
len(train['input'][0])

378

In [19]:
len(test['input'][0])

388

In [20]:
train['input'][0]

'Classify the self-reported stress level just before sleep. Use 0 if High stress level, and 1 if Low stress level.###DATA### subject_id : id01, sleep_date : 2024-06-27, lifelog_date : 2024-06-26, light_max : 1886.0, light_night_ratio : 0.1780821917808219, hr_evening_max : 124.0, lat_change : 0.0229018, vehicle_minutes : 3.8666666666666663, hr_afternoon_std : 12.63656557013988.'

In [21]:
len(train['input'][0])

378

In [22]:
test['input'][0]

'Classify the self-reported stress level just before sleep. Use 0 if High stress level, and 1 if Low stress level.###DATA### subject_id : id01, sleep_date : 2024-07-31, lifelog_date : 2024-07-30, light_max : 11581.0, light_night_ratio : 0.3333333333333333, hr_evening_max : -1.0, lat_change : -0.0001174999999999, vehicle_minutes : 8.766666666666667, hr_afternoon_std : 13.130036952925778.'

In [23]:
def calculate_model_parameters(target_model):
    model_parameters = filter(lambda p: p.requires_grad, target_model.parameters())
    params = sum([np.prod(p.size()) for p in model_parameters])
    return "{:,}".format(params)

In [24]:
train["label"] = train["Q3"]
train["text"] = train["input"]

/tmp/ipykernel_35/729822868.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  train["label"] = train["Q3"]
/tmp/ipykernel_35/729822868.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  train["text"] = train["input"]

In [25]:
import pandas as pd
from io import StringIO

string = """
subject_id	sleep_date
id01	2024-07-24
id01	2024-07-27
id01	2024-08-18
id01	2024-08-19
id01	2024-08-20
id01	2024-08-21
id01	2024-08-22
id01	2024-08-24
id01	2024-08-25
id01	2024-08-26
id01	2024-08-27
id01	2024-08-28
id01	2024-08-29
id01	2024-08-30
id02	2024-08-23
id02	2024-08-24
id02	2024-09-16
id02	2024-09-17
id02	2024-09-19
id02	2024-09-20
id02	2024-09-21
id02	2024-09-22
id02	2024-09-23
id02	2024-09-24
id02	2024-09-25
id02	2024-09-26
id02	2024-09-27
id02	2024-09-28
id03	2024-08-30
id03	2024-09-01
id03	2024-09-02
id03	2024-09-03
id03	2024-09-05
id03	2024-09-06
id03	2024-09-07
id04	2024-09-03
id04	2024-09-04
id04	2024-09-05
id04	2024-09-06
id04	2024-09-07
id04	2024-09-08
id04	2024-09-09
id04	2024-10-08
id04	2024-10-09
id04	2024-10-10
id04	2024-10-11
id04	2024-10-12
id04	2024-10-13
id04	2024-10-14
id05	2024-10-19
id05	2024-10-23
id05	2024-10-24
id05	2024-10-25
id05	2024-10-26
id05	2024-10-27
id05	2024-10-28
id06	2024-07-25
id06	2024-07-26
id06	2024-07-27
id06	2024-07-28
id06	2024-07-29
id06	2024-07-30
id06	2024-07-31
id07	2024-07-07
id07	2024-07-08
id07	2024-07-09
id07	2024-07-10
id07	2024-07-11
id07	2024-07-12
id07	2024-07-13
id07	2024-07-30
id07	2024-08-01
id07	2024-08-02
id07	2024-08-03
id07	2024-08-04
id07	2024-08-05
id07	2024-08-06
id08	2024-08-28
id08	2024-08-29
id08	2024-08-30
id08	2024-08-31
id08	2024-09-01
id08	2024-09-02
id08	2024-09-04
id09	2024-08-02
id09	2024-08-22
id09	2024-08-23
id09	2024-08-24
id09	2024-08-25
id09	2024-08-27
id09	2024-08-28
id09	2024-08-29
id09	2024-08-30
id09	2024-08-31
id09	2024-09-01
id09	2024-09-02
id09	2024-09-03
id09	2024-09-04
id10	2024-08-28
id10	2024-08-30
id10	2024-08-31
id10	2024-09-01
id10	2024-09-02
id10	2024-09-03
id10	2024-09-06
"""

# DataFrame 생성
valid_ids = pd.read_csv(StringIO(string), sep='\t')
valid_ids['pk'] = valid_ids['subject_id']+valid_ids['sleep_date']

In [26]:
valid_ids['pk'] = valid_ids['subject_id']+valid_ids['sleep_date']
train['pk'] = train['subject_id']+train['sleep_date']

all_valid = train.loc[train['pk'].isin(valid_ids['pk'])].reset_index(drop=True).copy()
all_train = train.loc[~train['pk'].isin(valid_ids['pk'])].reset_index(drop=True).copy()

/tmp/ipykernel_35/373063627.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  train['pk'] = train['subject_id']+train['sleep_date']

In [27]:
all_train.head()

,subject_id,sleep_date,lifelog_date,Q1,Q2,Q3,S1,S2,S3,charging_ratio,...,awake_blocks,pred_exe_flag,act_exe_flag,gps_exe_flag,hr_exe_flag,pedo_exe_flag,input,label,text,pk
0,id01,2024-06-27,2024-06-26,0,0,0,0,0,1,0.215859,...,3.0,0,0,0,0,0,Classify the self-reported stress level just b...,0,Classify the self-reported stress level just b...,id012024-06-27
1,id01,2024-06-28,2024-06-27,0,0,0,0,1,1,0.158571,...,3.0,0,0,0,0,0,Classify the self-reported stress level just b...,0,Classify the self-reported stress level just b...,id012024-06-28
2,id01,2024-06-29,2024-06-28,1,0,0,1,1,1,0.180282,...,1.0,0,0,0,0,0,Classify the self-reported stress level just b...,0,Classify the self-reported stress level just b...,id012024-06-29
3,id01,2024-06-30,2024-06-29,1,0,1,2,0,0,0.286567,...,1.0,0,0,0,0,0,Classify the self-reported stress level just b...,1,Classify the self-reported stress level just b...,id012024-06-30
4,id01,2024-07-01,2024-06-30,0,1,1,1,1,1,0.144286,...,1.0,0,0,0,0,0,Classify the self-reported stress level just b...,1,Classify the self-reported stress level just b...,id012024-07-01

In [28]:
all_train.info

<bound method DataFrame.info of     subject_id  sleep_date lifelog_date  Q1  Q2  Q3  S1  S2  S3  \
0         id01  2024-06-27   2024-06-26   0   0   0   0   0   1
1         id01  2024-06-28   2024-06-27   0   0   0   0   1   1
2         id01  2024-06-29   2024-06-28   1   0   0   1   1   1
3         id01  2024-06-30   2024-06-29   1   0   1   2   0   0
4         id01  2024-07-01   2024-06-30   0   1   1   1   1   1
..         ...         ...          ...  ..  ..  ..  ..  ..  ..
340       id10  2024-08-03   2024-08-02   0   0   0   0   0   0
341       id10  2024-09-08   2024-09-07   1   1   0   2   1   1
342       id10  2024-09-09   2024-09-08   1   1   1   0   1   1
343       id10  2024-09-12   2024-09-11   0   0   0   0   0   0
344       id10  2024-09-15   2024-09-14   1   0   0   1   0   0

     charging_ratio  ...  awake_blocks  pred_exe_flag  act_exe_flag  \
0          0.215859  ...           3.0              0             0
1          0.158571  ...           3.0              0             0
2          0.180282  ...           1.0              0             0
3          0.286567  ...           1.0              0             0
4          0.144286  ...           1.0              0             0
..              ...  ...           ...            ...           ...
340        0.267442  ...          -1.0              0             0
341        0.593678  ...           7.0              0             0
342        0.397810  ...          -1.0              0             0
343        0.336620  ...          -1.0              0             0
344        0.386014  ...           5.0              0             0

     gps_exe_flag  hr_exe_flag  pedo_exe_flag  \
0               0            0              0
1               0            0              0
2               0            0              0
3               0            0              0
4               0            0              0
..            ...          ...            ...
340             0            0              0
341             0            0              0
342             0            0              0
343             0            0              0
344             0            0              0

                                                 input  label  \
0    Classify the self-reported stress level just b...      0
1    Classify the self-reported stress level just b...      0
2    Classify the self-reported stress level just b...      0
3    Classify the self-reported stress level just b...      1
4    Classify the self-reported stress level just b...      1
..                                                 ...    ...
340  Classify the self-reported stress level just b...      0
341  Classify the self-reported stress level just b...      0
342  Classify the self-reported stress level just b...      1
343  Classify the self-reported stress level just b...      0
344  Classify the self-reported stress level just b...      0

                                                  text              pk
0    Classify the self-reported stress level just b...  id012024-06-27
1    Classify the self-reported stress level just b...  id012024-06-28
2    Classify the self-reported stress level just b...  id012024-06-29
3    Classify the self-reported stress level just b...  id012024-06-30
4    Classify the self-reported stress level just b...  id012024-07-01
..                                                 ...             ...
340  Classify the self-reported stress level just b...  id102024-08-03
341  Classify the self-reported stress level just b...  id102024-09-08
342  Classify the self-reported stress level just b...  id102024-09-09
343  Classify the self-reported stress level just b...  id102024-09-12
344  Classify the self-reported stress level just b...  id102024-09-15

[345 rows x 177 columns]>

In [29]:
all_valid.info

<bound method DataFrame.info of     subject_id  sleep_date lifelog_date  Q1  Q2  Q3  S1  S2  S3  \
0         id01  2024-07-24   2024-07-23   0   1   1   0   0   1
1         id01  2024-07-27   2024-07-26   0   0   1   1   1   1
2         id01  2024-08-18   2024-08-17   0   1   1   1   0   1
3         id01  2024-08-19   2024-08-18   0   0   0   0   1   1
4         id01  2024-08-20   2024-08-19   0   1   1   0   1   1
..         ...         ...          ...  ..  ..  ..  ..  ..  ..
100       id10  2024-08-31   2024-08-30   0   1   1   0   0   0
101       id10  2024-09-01   2024-08-31   1   1   1   1   1   1
102       id10  2024-09-02   2024-09-01   0   0   0   0   0   0
103       id10  2024-09-03   2024-09-02   0   0   0   0   0   0
104       id10  2024-09-06   2024-09-05   1   0   0   1   0   1

     charging_ratio  ...  awake_blocks  pred_exe_flag  act_exe_flag  \
0          0.262238  ...          -1.0              0             0
1          0.169075  ...           1.0              0             0
2          0.031387  ...           0.0              0             0
3          0.260741  ...           2.0              0             0
4          0.133094  ...           1.0              0             0
..              ...  ...           ...            ...           ...
100        0.328169  ...           3.0              0             0
101        0.188542  ...           7.0              0             0
102        0.502534  ...           4.0              0             0
103        0.414421  ...          -1.0              0             0
104        0.280435  ...          -1.0              0             0

     gps_exe_flag  hr_exe_flag  pedo_exe_flag  \
0               0            0              0
1               0            0              0
2               0            0              0
3               0            0              0
4               0            0              0
..            ...          ...            ...
100             0            0              0
101             0            0              0
102             0            0              0
103             0            0              0
104             0            0              0

                                                 input  label  \
0    Classify the self-reported stress level just b...      1
1    Classify the self-reported stress level just b...      1
2    Classify the self-reported stress level just b...      1
3    Classify the self-reported stress level just b...      0
4    Classify the self-reported stress level just b...      1
..                                                 ...    ...
100  Classify the self-reported stress level just b...      1
101  Classify the self-reported stress level just b...      1
102  Classify the self-reported stress level just b...      0
103  Classify the self-reported stress level just b...      0
104  Classify the self-reported stress level just b...      0

                                                  text              pk
0    Classify the self-reported stress level just b...  id012024-07-24
1    Classify the self-reported stress level just b...  id012024-07-27
2    Classify the self-reported stress level just b...  id012024-08-18
3    Classify the self-reported stress level just b...  id012024-08-19
4    Classify the self-reported stress level just b...  id012024-08-20
..                                                 ...             ...
100  Classify the self-reported stress level just b...  id102024-08-31
101  Classify the self-reported stress level just b...  id102024-09-01
102  Classify the self-reported stress level just b...  id102024-09-02
103  Classify the self-reported stress level just b...  id102024-09-03
104  Classify the self-reported stress level just b...  id102024-09-06

[105 rows x 177 columns]>

In [30]:
all_valid.head()

,subject_id,sleep_date,lifelog_date,Q1,Q2,Q3,S1,S2,S3,charging_ratio,...,awake_blocks,pred_exe_flag,act_exe_flag,gps_exe_flag,hr_exe_flag,pedo_exe_flag,input,label,text,pk
0,id01,2024-07-24,2024-07-23,0,1,1,0,0,1,0.262238,...,-1.0,0,0,0,0,0,Classify the self-reported stress level just b...,1,Classify the self-reported stress level just b...,id012024-07-24
1,id01,2024-07-27,2024-07-26,0,0,1,1,1,1,0.169075,...,1.0,0,0,0,0,0,Classify the self-reported stress level just b...,1,Classify the self-reported stress level just b...,id012024-07-27
2,id01,2024-08-18,2024-08-17,0,1,1,1,0,1,0.031387,...,0.0,0,0,0,0,0,Classify the self-reported stress level just b...,1,Classify the self-reported stress level just b...,id012024-08-18
3,id01,2024-08-19,2024-08-18,0,0,0,0,1,1,0.260741,...,2.0,0,0,0,0,0,Classify the self-reported stress level just b...,0,Classify the self-reported stress level just b...,id012024-08-19
4,id01,2024-08-20,2024-08-19,0,1,1,0,1,1,0.133094,...,1.0,0,0,0,0,0,Classify the self-reported stress level just b...,1,Classify the self-reported stress level just b...,id012024-08-20

In [31]:
val_df = all_valid[['text','label']]
train_df = all_train[['text','label']]

In [32]:
test["text"] = test["input"]

/tmp/ipykernel_35/3863687931.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test["text"] = test["input"]

In [33]:
val_df.label.value_counts()

label
1    67
0    38
Name: count, dtype: int64

In [34]:
train_df.label.value_counts()

label
1    203
0    142
Name: count, dtype: int64

In [35]:
token = "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"
login(token)

In [36]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
os.environ["TOKENIZERS_PARALLELISM"] = "false"

In [37]:
import warnings
warnings.filterwarnings("ignore")

In [38]:
#model_path = 'openlm-research/open_llama_3b'
#model_path = 'google/flan-t5-large' #loss 측정 불가
model_path = 'tiiuae/falcon-rw-1b' #초반에 로스 터짐..
#model_path = 'distilbert-base-uncased' #학습 진행 안됨
num_labels = 2 

#model = LlamaForSequenceClassification.from_pretrained(model_path, num_labels=num_labels, torch_dtype=torch.float16, device_map='cuda:0')
model = AutoModelForSequenceClassification.from_pretrained(model_path, num_labels=num_labels, torch_dtype=torch.float16, device_map='auto')

config.json:   0%|          | 0.00/1.05k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/2.62G [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.62G [00:00<?, ?B/s]

Some weights of FalconForSequenceClassification were not initialized from the model checkpoint at tiiuae/falcon-rw-1b and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [39]:
from transformers import LlamaTokenizer, LlamaForCausalLM
from transformers import AutoTokenizer
from transformers import AutoModelForSequenceClassification, LlamaForSequenceClassification

In [40]:
tokenizer = AutoTokenizer.from_pretrained(model_path, 
                                          trust_remote_code=True,
                                         )
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

tokenizer_config.json:   0%|          | 0.00/234 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/798k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.11M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/99.0 [00:00<?, ?B/s]

In [41]:
tokenizer

GPT2TokenizerFast(name_or_path='tiiuae/falcon-rw-1b', vocab_size=50257, model_max_length=1024, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'bos_token': '<|endoftext|>', 'eos_token': '<|endoftext|>', 'unk_token': '<|endoftext|>', 'pad_token': '<|endoftext|>'}, clean_up_tokenization_spaces=True, added_tokens_decoder={
	50256: AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}
)

In [42]:
config = LoraConfig(
    r=16,
    lora_alpha=16,
    #target_modules=["q_proj", "v_proj"], # https://github.com/huggingface/peft/blob/632997d1fb776c3cf05d8c2537ac9a98a7ce9435/src/peft/utils/other.py#L202
    lora_dropout=0.1,
    bias="none",
    modules_to_save=["classifier"],
)
lora_model = get_peft_model(model, config)

In [43]:
model

FalconForSequenceClassification(
  (transformer): FalconModel(
    (word_embeddings): Embedding(50304, 2048)
    (h): ModuleList(
      (0-23): 24 x FalconDecoderLayer(
        (self_attention): FalconAttention(
          (query_key_value): lora.Linear(
            (base_layer): FalconLinear(in_features=2048, out_features=6144, bias=True)
            (lora_dropout): ModuleDict(
              (default): Dropout(p=0.1, inplace=False)
            )
            (lora_A): ModuleDict(
              (default): Linear(in_features=2048, out_features=16, bias=False)
            )
            (lora_B): ModuleDict(
              (default): Linear(in_features=16, out_features=6144, bias=False)
            )
            (lora_embedding_A): ParameterDict()
            (lora_embedding_B): ParameterDict()
            (lora_magnitude_vector): ModuleDict()
          )
          (dense): FalconLinear(in_features=2048, out_features=2048, bias=True)
          (attention_dropout): Dropout(p=0.0, inplace=False)
        )
        (mlp): FalconMLP(
          (dense_h_to_4h): FalconLinear(in_features=2048, out_features=8192, bias=True)
          (act): GELUActivation()
          (dense_4h_to_h): FalconLinear(in_features=8192, out_features=2048, bias=True)
        )
        (post_attention_layernorm): LayerNorm((2048,), eps=1e-05, elementwise_affine=True)
        (input_layernorm): LayerNorm((2048,), eps=1e-05, elementwise_affine=True)
      )
    )
    (ln_f): LayerNorm((2048,), eps=1e-05, elementwise_affine=True)
    (rotary_emb): FalconRotaryEmbedding()
  )
  (score): Linear(in_features=2048, out_features=2, bias=False)
)

In [44]:
class CustomDataset(Dataset):
    def __init__(self, twitterDF):
        self.twitterDF = twitterDF

    def __len__(self):
        return len(self.twitterDF.index)

    def __getitem__(self, idx):
        return np.array([idx])

In [45]:
training_data = CustomDataset(train_df)
validation_data = CustomDataset(val_df)

train_dataloader = DataLoader(training_data, batch_size=1, shuffle=True)
val_dataloader = DataLoader(validation_data, batch_size=1, shuffle=False)

In [46]:
test_df = test[["text"]]

In [47]:
test_data = CustomDataset(test)
test_dataloader = DataLoader(test_data, batch_size=1, shuffle=False)

In [48]:
from sklearn import metrics

In [49]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

Using device: cuda

In [50]:
def train(model, loader, optimizer, criterion, twitterDFTrain_clean):
    model.train()
    
    total_loss = 0
    correct = 0
    pred = []
    label = []
    for batchIdx, sampledIdx in enumerate(tqdm(loader, position=0, leave=True)):
        #print(data)
        
        optimizer.zero_grad()
        
        #text
        sampledIdx = sampledIdx.cpu().data.numpy()
        sampledRowText = list(twitterDFTrain_clean["text"].iloc[list(sampledIdx.flatten())])
        #label
        sampledRowLabels = torch.tensor(list(twitterDFTrain_clean["label"].iloc[list(sampledIdx.flatten())])).to(device)
        
        #encoded
        encoded_input = tokenizer(sampledRowText, truncation=True, padding=True, return_tensors='pt').to(device) # Output shape: [bs, num_Labels]
        encoded_inputIds = encoded_input["input_ids"].to(device)
        encoded_attnMask = encoded_input["attention_mask"].to(device)

        #model
        outputs = model(input_ids=encoded_inputIds, attention_mask=encoded_attnMask)

        # label type change
        sampledRowLabels = sampledRowLabels.to(outputs.logits.device).long()  # shape: [1]
        
        # loss
        loss = criterion(outputs.logits, sampledRowLabels) 
        total_loss += loss.item()
        
        #acurracy
        probs = torch.nn.functional.softmax(outputs.logits, dim=-1)
        predicted_class = torch.argmax(outputs.logits, dim=-1)
        pred.extend(predicted_class.flatten().cpu().data.numpy())
        label.extend(sampledRowLabels.cpu().data.numpy())     

        #back propagation
        loss.backward()
        optimizer.step()

    train_accuracy_score = metrics.f1_score(label,pred, average='macro')
    return total_loss / len(loader), train_accuracy_score

In [51]:
def valid(model, valid_loader, criterion, twitterDFVal_clean):
    model.eval()
    with torch.no_grad():
        
        total_loss = 0
        correct = 0

        pred = []
        label = []

        for batchIdx, sampledIdx in enumerate(tqdm(valid_loader, position=0, leave=True)):
            
            sampledRowText = list(twitterDFVal_clean["text"].iloc[list(sampledIdx.flatten())])
            sampledRowLabels = torch.tensor(list(twitterDFVal_clean["label"].iloc[list(sampledIdx.flatten())]))

            encoded_input = tokenizer(sampledRowText, truncation=True, padding=True, return_tensors='pt').to(device) # Output shape: [bs, num_Labels]
            encoded_inputIds = encoded_input["input_ids"].to(device)
            encoded_attnMask = encoded_input["attention_mask"].to(device)
            
            #model
            outputs = model(input_ids=encoded_inputIds, attention_mask=encoded_attnMask)
    
            # label type change
            sampledRowLabels = sampledRowLabels.to(outputs.logits.device).long()  # shape: [1]
            
            # loss
            loss = criterion(outputs.logits, sampledRowLabels) 
            total_loss += loss.item()
            
            #acurracy
            probs = torch.nn.functional.softmax(outputs.logits, dim=-1)
            predicted_class = torch.argmax(outputs.logits, dim=-1)
            pred.extend(predicted_class.flatten().cpu().data.numpy())
            label.extend(sampledRowLabels.cpu().data.numpy())     

        valid_accuracy_score = metrics.f1_score(label,pred, average='macro')
    return total_loss/len(valid_loader), valid_accuracy_score

In [52]:
twitterDFTrain_clean = train_df
twitterDFVal_clean = val_df

In [53]:
model

FalconForSequenceClassification(
  (transformer): FalconModel(
    (word_embeddings): Embedding(50304, 2048)
    (h): ModuleList(
      (0-23): 24 x FalconDecoderLayer(
        (self_attention): FalconAttention(
          (query_key_value): lora.Linear(
            (base_layer): FalconLinear(in_features=2048, out_features=6144, bias=True)
            (lora_dropout): ModuleDict(
              (default): Dropout(p=0.1, inplace=False)
            )
            (lora_A): ModuleDict(
              (default): Linear(in_features=2048, out_features=16, bias=False)
            )
            (lora_B): ModuleDict(
              (default): Linear(in_features=16, out_features=6144, bias=False)
            )
            (lora_embedding_A): ParameterDict()
            (lora_embedding_B): ParameterDict()
            (lora_magnitude_vector): ModuleDict()
          )
          (dense): FalconLinear(in_features=2048, out_features=2048, bias=True)
          (attention_dropout): Dropout(p=0.0, inplace=False)
        )
        (mlp): FalconMLP(
          (dense_h_to_4h): FalconLinear(in_features=2048, out_features=8192, bias=True)
          (act): GELUActivation()
          (dense_4h_to_h): FalconLinear(in_features=8192, out_features=2048, bias=True)
        )
        (post_attention_layernorm): LayerNorm((2048,), eps=1e-05, elementwise_affine=True)
        (input_layernorm): LayerNorm((2048,), eps=1e-05, elementwise_affine=True)
      )
    )
    (ln_f): LayerNorm((2048,), eps=1e-05, elementwise_affine=True)
    (rotary_emb): FalconRotaryEmbedding()
  )
  (score): Linear(in_features=2048, out_features=2, bias=False)
)

In [54]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class FocalLoss(nn.Module):
    def __init__(self, gamma=2.0, alpha=None, reduction='mean'):
        super(FocalLoss, self).__init__()
        self.gamma = gamma
        self.alpha = alpha  # optional: list or tensor of class weights
        self.reduction = reduction

    def forward(self, inputs, targets):
        ce_loss = F.cross_entropy(inputs, targets, reduction='none', weight=self.alpha)
        pt = torch.exp(-ce_loss)  # prevents nans when probability is 0
        focal_loss = ((1 - pt) ** self.gamma) * ce_loss

        if self.reduction == 'mean':
            return focal_loss.mean()
        elif self.reduction == 'sum':
            return focal_loss.sum()
        else:
            return focal_loss

In [55]:
import os

# Define your training loop
#epochs = 5
epochs = 16
optimizer = torch.optim.AdamW(model.parameters(), lr=1e-5)
criterion = FocalLoss(gamma=2.0)
#criterion = nn.BCEWithLogitsLoss()

total_loss = 0
correct = 0

#best model 를 찾기 위한
best = np.inf

#3번까지 validation loss 터지면 stop 시킴
patience = 3

#best model save
result_path = "/kaggle/working/"
best_model_path = os.path.join(result_path, 'best_model.pt')
bad_counter = 0

for epoch in range(epochs):
    
    avg_train_loss, avg_train_acc  = train(model, train_dataloader, optimizer, criterion, twitterDFTrain_clean)
    
    avg_vaild_loss, avg_vaild_acc = valid(model, val_dataloader, criterion, twitterDFVal_clean)
    
    if avg_vaild_loss < best:
        best = avg_vaild_loss
        torch.save(model.state_dict(), best_model_path)
        bad_counter = 0
    else:
        bad_counter += 1

    if bad_counter == patience:
        break
    
    print(f'Epoch: {str(epoch+1)}: t_loss:{avg_train_loss:.3f} t_acc:{avg_train_acc:.3f} v_loss:{avg_vaild_loss:.3f} v_acc:{avg_vaild_acc:.3f}')
    
    wandb.log({"train": {'epoch': epoch, "acc": avg_train_acc, "loss": avg_train_loss}, "val": {'epoch': epoch, "acc": avg_vaild_acc, "loss": avg_vaild_loss}})

100%|██████████| 345/345 [00:50<00:00,  6.89it/s]
100%|██████████| 105/105 [00:06<00:00, 15.12it/s]

Epoch: 1: t_loss:0.247 t_acc:0.489 v_loss:0.202 v_acc:0.417

100%|██████████| 345/345 [00:49<00:00,  7.00it/s]
100%|██████████| 105/105 [00:06<00:00, 15.11it/s]

Epoch: 2: t_loss:0.177 t_acc:0.532 v_loss:0.177 v_acc:0.454

100%|██████████| 345/345 [00:49<00:00,  7.00it/s]
100%|██████████| 105/105 [00:06<00:00, 15.03it/s]

Epoch: 3: t_loss:0.172 t_acc:0.523 v_loss:0.184 v_acc:0.475

100%|██████████| 345/345 [00:49<00:00,  7.00it/s]
100%|██████████| 105/105 [00:06<00:00, 15.12it/s]

Epoch: 4: t_loss:0.166 t_acc:0.546 v_loss:0.168 v_acc:0.469

100%|██████████| 345/345 [00:49<00:00,  7.01it/s]
100%|██████████| 105/105 [00:06<00:00, 15.14it/s]

Epoch: 5: t_loss:0.166 t_acc:0.600 v_loss:0.178 v_acc:0.382

100%|██████████| 345/345 [00:49<00:00,  7.02it/s]
100%|██████████| 105/105 [00:06<00:00, 15.12it/s]

Epoch: 6: t_loss:0.163 t_acc:0.583 v_loss:0.168 v_acc:0.475

100%|██████████| 345/345 [00:49<00:00,  7.01it/s]
100%|██████████| 105/105 [00:06<00:00, 15.11it/s]

Epoch: 7: t_loss:0.159 t_acc:0.607 v_loss:0.178 v_acc:0.522

100%|██████████| 345/345 [00:49<00:00,  7.02it/s]
100%|██████████| 105/105 [00:06<00:00, 15.16it/s]

Epoch: 8: t_loss:0.156 t_acc:0.601 v_loss:0.173 v_acc:0.409

100%|██████████| 345/345 [00:49<00:00,  7.02it/s]
100%|██████████| 105/105 [00:06<00:00, 15.11it/s]

In [56]:
#best model save
result_path = "/kaggle/working/"
best_model_path = os.path.join(result_path, 'best_model.pt')

In [57]:
def inference(model, loader, test_data):
    #best model 불러와서 call 하기
    model.load_state_dict(torch.load(best_model_path))
    model.eval()
    
    preds = []
    preds_prob = []
    with torch.no_grad():
        total_loss = 0
        correct = 0

        pred = []
        label = []
        
        for batchIdx, sampledIdx in enumerate(tqdm(loader, position=0, leave=True)):
            
            sampledRowText = list(test_data["text"].iloc[list(sampledIdx.flatten())])

            encoded_input = tokenizer(sampledRowText, truncation=True, padding=True, return_tensors='pt').to("cuda") # Output shape: [bs, num_Labels]
            encoded_inputIds = encoded_input["input_ids"].to("cuda")
            encoded_attnMask = encoded_input["attention_mask"].to("cuda")
            
            outputs = model(input_ids=encoded_inputIds, attention_mask=encoded_attnMask)
            logits = outputs.logits


            #acurracy
            probs = torch.nn.functional.softmax(outputs.logits.cpu(), dim=-1)
            
            #확률구하기
            preds_prob.extend(probs.cpu().data.numpy())

            #acurracy
            pred.extend(torch.argmax(logits, dim=1).flatten().cpu().data.numpy())
            
    return pred, preds_prob

In [58]:
# inference
preds, preds_prob = inference(model, val_dataloader, val_df)

100%|██████████| 105/105 [00:06<00:00, 15.22it/s]

In [59]:
preds_prob

[array([0.4844, 0.5156], dtype=float16),
 array([0.3994, 0.6006], dtype=float16),
 array([0.4373, 0.5625], dtype=float16),
 array([0.447, 0.553], dtype=float16),
 array([0.3933, 0.607 ], dtype=float16),
 array([0.396, 0.604], dtype=float16),
 array([0.4834, 0.5166], dtype=float16),
 array([0.4858, 0.514 ], dtype=float16),
 array([0.4248, 0.575 ], dtype=float16),
 array([0.4116, 0.5884], dtype=float16),
 array([0.4575, 0.5425], dtype=float16),
 array([0.4658, 0.534 ], dtype=float16),
 array([0.396, 0.604], dtype=float16),
 array([0.524, 0.476], dtype=float16),
 array([0.4407, 0.559 ], dtype=float16),
 array([0.3948, 0.6055], dtype=float16),
 array([0.4663, 0.5337], dtype=float16),
 array([0.423, 0.577], dtype=float16),
 array([0.368, 0.632], dtype=float16),
 array([0.3975, 0.6025], dtype=float16),
 array([0.4644, 0.5356], dtype=float16),
 array([0.3674, 0.6323], dtype=float16),
 array([0.3647, 0.6353], dtype=float16),
 array([0.4722, 0.528 ], dtype=float16),
 array([0.3757, 0.6245], dtype=float16),
 array([0.4226, 0.5776], dtype=float16),
 array([0.4126, 0.5874], dtype=float16),
 array([0.434, 0.566], dtype=float16),
 array([0.423, 0.577], dtype=float16),
 array([0.4565, 0.5435], dtype=float16),
 array([0.4614, 0.5386], dtype=float16),
 array([0.4102, 0.59  ], dtype=float16),
 array([0.4707, 0.5293], dtype=float16),
 array([0.519, 0.481], dtype=float16),
 array([0.4312, 0.569 ], dtype=float16),
 array([0.3853, 0.6147], dtype=float16),
 array([0.4648, 0.535 ], dtype=float16),
 array([0.4082, 0.592 ], dtype=float16),
 array([0.4941, 0.506 ], dtype=float16),
 array([0.3315, 0.6685], dtype=float16),
 array([0.3762, 0.624 ], dtype=float16),
 array([0.4485, 0.552 ], dtype=float16),
 array([0.3762, 0.624 ], dtype=float16),
 array([0.4524, 0.548 ], dtype=float16),
 array([0.4678, 0.532 ], dtype=float16),
 array([0.448 , 0.5522], dtype=float16),
 array([0.3965, 0.6035], dtype=float16),
 array([0.3918, 0.608 ], dtype=float16),
 array([0.4177, 0.582 ], dtype=float16),
 array([0.4805, 0.5195], dtype=float16),
 array([0.4844, 0.5156], dtype=float16),
 array([0.4006, 0.599 ], dtype=float16),
 array([0.4192, 0.581 ], dtype=float16),
 array([0.3867, 0.6133], dtype=float16),
 array([0.3474, 0.653 ], dtype=float16),
 array([0.3933, 0.607 ], dtype=float16),
 array([0.4465, 0.5537], dtype=float16),
 array([0.3948, 0.6055], dtype=float16),
 array([0.4055, 0.5947], dtype=float16),
 array([0.435, 0.565], dtype=float16),
 array([0.422, 0.578], dtype=float16),
 array([0.5293, 0.4707], dtype=float16),
 array([0.4163, 0.5835], dtype=float16),
 array([0.46, 0.54], dtype=float16),
 array([0.4485, 0.552 ], dtype=float16),
 array([0.4106, 0.5894], dtype=float16),
 array([0.4373, 0.5625], dtype=float16),
 array([0.4746, 0.5254], dtype=float16),
 array([0.5205, 0.4795], dtype=float16),
 array([0.4197, 0.5806], dtype=float16),
 array([0.413, 0.587], dtype=float16),
 array([0.4902, 0.51  ], dtype=float16),
 array([0.5366, 0.4634], dtype=float16),
 array([0.5073, 0.4927], dtype=float16),
 array([0.4397, 0.56  ], dtype=float16),
 array([0.457, 0.543], dtype=float16),
 array([0.4736, 0.5264], dtype=float16),
 array([0.5063, 0.4937], dtype=float16),
 array([0.462, 0.538], dtype=float16),
 array([0.4456, 0.5547], dtype=float16),
 array([0.4946, 0.5054], dtype=float16),
 array([0.5034, 0.4966], dtype=float16),
 array([0.4795, 0.5205], dtype=float16),
 array([0.4878, 0.512 ], dtype=float16),
 array([0.4556, 0.5444], dtype=float16),
 array([0.4363, 0.5635], dtype=float16),
 array([0.4421, 0.5576], dtype=float16),
 array([0.5024, 0.4976], dtype=float16),
 array([0.4102, 0.59  ], dtype=float16),
 array([0.5044, 0.4956], dtype=float16),
 array([0.4436, 0.5566], dtype=float16),
 array([0.4883, 0.5117], dtype=float16),
 array([0.4216, 0.5786], dtype=float16),
 array([0.4648, 0.535 ], dtype=float16),
 array([0.4316, 0.5684], dtype=float16),
 array([0.519, 0.481], dtype=float16),
 array([0.397, 0.603], dtype=float16),
 array([0.61, 0.39], dtype=float16),
 array([0.4082, 0.592 ], dtype=float16),
 array([0.4417, 0.558 ], dtype=float16),
 array([0.382 , 0.6177], dtype=float16),
 array([0.4644, 0.5356], dtype=float16),
 array([0.383 , 0.6167], dtype=float16),
 array([0.4092, 0.591 ], dtype=float16),
 array([0.435, 0.565], dtype=float16)]

In [60]:
val_df["label"]

0      1
1      1
2      1
3      0
4      1
      ..
100    1
101    1
102    0
103    0
104    0
Name: label, Length: 105, dtype: int64

In [61]:
preds

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1]

In [62]:
metrics.f1_score(val_df["label"],preds, average='macro')

0.475

In [63]:
preds, preds_prob = inference(model, test_dataloader, test_df)

100%|██████████| 250/250 [00:16<00:00, 15.26it/s]

In [64]:
preds_prob

[array([0.4238, 0.576 ], dtype=float16),
 array([0.4854, 0.5146], dtype=float16),
 array([0.412, 0.588], dtype=float16),
 array([0.4834, 0.5166], dtype=float16),
 array([0.4153, 0.5845], dtype=float16),
 array([0.475, 0.525], dtype=float16),
 array([0.4326, 0.5674], dtype=float16),
 array([0.458, 0.542], dtype=float16),
 array([0.4316, 0.5684], dtype=float16),
 array([0.4624, 0.5376], dtype=float16),
 array([0.4282, 0.572 ], dtype=float16),
 array([0.444, 0.556], dtype=float16),
 array([0.458, 0.542], dtype=float16),
 array([0.4624, 0.5376], dtype=float16),
 array([0.4575, 0.5425], dtype=float16),
 array([0.3757, 0.6245], dtype=float16),
 array([0.4377, 0.562 ], dtype=float16),
 array([0.4966, 0.5034], dtype=float16),
 array([0.4663, 0.5337], dtype=float16),
 array([0.4373, 0.5625], dtype=float16),
 array([0.4565, 0.5435], dtype=float16),
 array([0.433, 0.567], dtype=float16),
 array([0.403 , 0.5967], dtype=float16),
 array([0.3984, 0.6016], dtype=float16),
 array([0.3928, 0.6074], dtype=float16),
 array([0.455, 0.545], dtype=float16),
 array([0.3674, 0.6323], dtype=float16),
 array([0.3784, 0.6216], dtype=float16),
 array([0.3447, 0.6553], dtype=float16),
 array([0.3306, 0.6694], dtype=float16),
 array([0.3862, 0.614 ], dtype=float16),
 array([0.4539, 0.5464], dtype=float16),
 array([0.347 , 0.6533], dtype=float16),
 array([0.39, 0.61], dtype=float16),
 array([0.343, 0.657], dtype=float16),
 array([0.4326, 0.5674], dtype=float16),
 array([0.3896, 0.6104], dtype=float16),
 array([0.3438, 0.6562], dtype=float16),
 array([0.3552, 0.6445], dtype=float16),
 array([0.4026, 0.597 ], dtype=float16),
 array([0.3455, 0.6543], dtype=float16),
 array([0.3748, 0.625 ], dtype=float16),
 array([0.4465, 0.5537], dtype=float16),
 array([0.398, 0.602], dtype=float16),
 array([0.3994, 0.6006], dtype=float16),
 array([0.3938, 0.6064], dtype=float16),
 array([0.3684, 0.632 ], dtype=float16),
 array([0.448 , 0.5522], dtype=float16),
 array([0.435, 0.565], dtype=float16),
 array([0.4055, 0.5947], dtype=float16),
 array([0.414, 0.586], dtype=float16),
 array([0.3867, 0.6133], dtype=float16),
 array([0.53  , 0.4702], dtype=float16),
 array([0.373, 0.627], dtype=float16),
 array([0.4102, 0.59  ], dtype=float16),
 array([0.3584, 0.6416], dtype=float16),
 array([0.3784, 0.6216], dtype=float16),
 array([0.3774, 0.6226], dtype=float16),
 array([0.4277, 0.5723], dtype=float16),
 array([0.4253, 0.5747], dtype=float16),
 array([0.5264, 0.4736], dtype=float16),
 array([0.4495, 0.551 ], dtype=float16),
 array([0.506 , 0.4941], dtype=float16),
 array([0.3923, 0.6074], dtype=float16),
 array([0.4995, 0.5005], dtype=float16),
 array([0.4377, 0.562 ], dtype=float16),
 array([0.517, 0.483], dtype=float16),
 array([0.4495, 0.551 ], dtype=float16),
 array([0.456, 0.544], dtype=float16),
 array([0.4272, 0.5728], dtype=float16),
 array([0.4775, 0.5225], dtype=float16),
 array([0.4226, 0.5776], dtype=float16),
 array([0.4312, 0.569 ], dtype=float16),
 array([0.4922, 0.508 ], dtype=float16),
 array([0.502, 0.498], dtype=float16),
 array([0.48, 0.52], dtype=float16),
 array([0.462, 0.538], dtype=float16),
 array([0.4543, 0.546 ], dtype=float16),
 array([0.504, 0.496], dtype=float16),
 array([0.4736, 0.5264], dtype=float16),
 array([0.404, 0.596], dtype=float16),
 array([0.405, 0.595], dtype=float16),
 array([0.384, 0.616], dtype=float16),
 array([0.3726, 0.6274], dtype=float16),
 array([0.3975, 0.6025], dtype=float16),
 array([0.4111, 0.589 ], dtype=float16),
 array([0.3955, 0.6045], dtype=float16),
 array([0.462, 0.538], dtype=float16),
 array([0.3887, 0.6113], dtype=float16),
 array([0.4727, 0.5273], dtype=float16),
 array([0.4678, 0.532 ], dtype=float16),
 array([0.4253, 0.5747], dtype=float16),
 array([0.3816, 0.618 ], dtype=float16),
 array([0.434, 0.566], dtype=float16),
 array([0.4312, 0.569 ], dtype=float16),
 array([0.3943, 0.606 ], dtype=float16),
 array([0.481, 0.519], dtype=float16),
 array([0.4163, 0.5835], dtype=float16),
 array([0.3625, 0.6377], dtype=float16),
 array([0.4707, 0.5293], dtype=float16),
 array([0.3667, 0.6333], dtype=float16),
 array([0.347 , 0.6533], dtype=float16),
 array([0.4, 0.6], dtype=float16),
 array([0.3726, 0.6274], dtype=float16),
 array([0.4087, 0.5913], dtype=float16),
 array([0.395, 0.605], dtype=float16),
 array([0.3975, 0.6025], dtype=float16),
 array([0.3955, 0.6045], dtype=float16),
 array([0.402 , 0.5977], dtype=float16),
 array([0.3643, 0.6357], dtype=float16),
 array([0.448 , 0.5522], dtype=float16),
 array([0.4148, 0.585 ], dtype=float16),
 array([0.3877, 0.6123], dtype=float16),
 array([0.453 , 0.5474], dtype=float16),
 array([0.4858, 0.514 ], dtype=float16),
 array([0.403 , 0.5967], dtype=float16),
 array([0.3965, 0.6035], dtype=float16),
 array([0.447, 0.553], dtype=float16),
 array([0.4197, 0.5806], dtype=float16),
 array([0.4277, 0.5723], dtype=float16),
 array([0.3594, 0.6406], dtype=float16),
 array([0.4055, 0.5947], dtype=float16),
 array([0.3662, 0.634 ], dtype=float16),
 array([0.4402, 0.5596], dtype=float16),
 array([0.4336, 0.5664], dtype=float16),
 array([0.4087, 0.5913], dtype=float16),
 array([0.4148, 0.585 ], dtype=float16),
 array([0.3872, 0.613 ], dtype=float16),
 array([0.4233, 0.5767], dtype=float16),
 array([0.4475, 0.5527], dtype=float16),
 array([0.4465, 0.5537], dtype=float16),
 array([0.3594, 0.6406], dtype=float16),
 array([0.514 , 0.4858], dtype=float16),
 array([0.433, 0.567], dtype=float16),
 array([0.5024, 0.4976], dtype=float16),
 array([0.3914, 0.6084], dtype=float16),
 array([0.5977, 0.402 ], dtype=float16),
 array([0.4297, 0.5703], dtype=float16),
 array([0.561 , 0.4387], dtype=float16),
 array([0.413, 0.587], dtype=float16),
 array([0.4824, 0.5176], dtype=float16),
 array([0.4692, 0.531 ], dtype=float16),
 array([0.4097, 0.5903], dtype=float16),
 array([0.3984, 0.6016], dtype=float16),
 array([0.518, 0.482], dtype=float16),
 array([0.496, 0.504], dtype=float16),
 array([0.4556, 0.5444], dtype=float16),
 array([0.4844, 0.5156], dtype=float16),
 array([0.5425, 0.4575], dtype=float16),
 array([0.4072, 0.593 ], dtype=float16),
 array([0.4192, 0.581 ], dtype=float16),
 array([0.4272, 0.5728], dtype=float16),
 array([0.4016, 0.598 ], dtype=float16),
 array([0.4277, 0.5723], dtype=float16),
 array([0.4436, 0.5566], dtype=float16),
 array([0.433, 0.567], dtype=float16),
 array([0.458, 0.542], dtype=float16),
 array([0.4238, 0.576 ], dtype=float16),
 array([0.4363, 0.5635], dtype=float16),
 array([0.4956, 0.5044], dtype=float16),
 array([0.4202, 0.58  ], dtype=float16),
 array([0.4712, 0.529 ], dtype=float16),
 array([0.4722, 0.528 ], dtype=float16),
 array([0.4377, 0.562 ], dtype=float16),
 array([0.5024, 0.4976], dtype=float16),
 array([0.5107, 0.4893], dtype=float16),
 array([0.4363, 0.5635], dtype=float16),
 array([0.3857, 0.6143], dtype=float16),
 array([0.4692, 0.531 ], dtype=float16),
 array([0.4514, 0.549 ], dtype=float16),
 array([0.4016, 0.598 ], dtype=float16),
 array([0.4233, 0.5767], dtype=float16),
 array([0.4016, 0.598 ], dtype=float16),
 array([0.4353, 0.5645], dtype=float16),
 array([0.434, 0.566], dtype=float16),
 array([0.4824, 0.5176], dtype=float16),
 array([0.46, 0.54], dtype=float16),
 array([0.548 , 0.4524], dtype=float16),
 array([0.4312, 0.569 ], dtype=float16),
 array([0.3757, 0.6245], dtype=float16),
 array([0.5156, 0.4844], dtype=float16),
 array([0.4336, 0.5664], dtype=float16),
 array([0.545, 0.455], dtype=float16),
 array([0.4814, 0.5186], dtype=float16),
 array([0.4995, 0.5005], dtype=float16),
 array([0.461, 0.539], dtype=float16),
 array([0.5215, 0.4785], dtype=float16),
 array([0.519, 0.481], dtype=float16),
 array([0.618 , 0.3816], dtype=float16),
 array([0.4614, 0.5386], dtype=float16),
 array([0.661 , 0.3386], dtype=float16),
 array([0.539, 0.461], dtype=float16),
 array([0.461, 0.539], dtype=float16),
 array([0.529 , 0.4712], dtype=float16),
 array([0.4624, 0.5376], dtype=float16),
 array([0.508 , 0.4922], dtype=float16),
 array([0.5005, 0.4995], dtype=float16),
 array([0.4055, 0.5947], dtype=float16),
 array([0.4697, 0.5303], dtype=float16),
 array([0.5796, 0.4207], dtype=float16),
 array([0.5366, 0.4634], dtype=float16),
 array([0.4268, 0.573 ], dtype=float16),
 array([0.4692, 0.531 ], dtype=float16),
 array([0.4932, 0.507 ], dtype=float16),
 array([0.496, 0.504], dtype=float16),
 array([0.433, 0.567], dtype=float16),
 array([0.5146, 0.4854], dtype=float16),
 array([0.4363, 0.5635], dtype=float16),
 array([0.4678, 0.532 ], dtype=float16),
 array([0.4382, 0.5615], dtype=float16),
 array([0.4775, 0.5225], dtype=float16),
 array([0.448 , 0.5522], dtype=float16),
 array([0.478, 0.522], dtype=float16),
 array([0.4604, 0.5396], dtype=float16),
 array([0.4543, 0.546 ], dtype=float16),
 array([0.444, 0.556], dtype=float16),
 array([0.499, 0.501], dtype=float16),
 array([0.4465, 0.5537], dtype=float16),
 array([0.4702, 0.53  ], dtype=float16),
 array([0.422, 0.578], dtype=float16),
 array([0.4702, 0.53  ], dtype=float16),
 array([0.499, 0.501], dtype=float16),
 array([0.639 , 0.3606], dtype=float16),
 array([0.521, 0.479], dtype=float16),
 array([0.3877, 0.6123], dtype=float16),
 array([0.474, 0.526], dtype=float16),
 array([0.4548, 0.5454], dtype=float16),
 array([0.404, 0.596], dtype=float16),
 array([0.363, 0.637], dtype=float16),
 array([0.4126, 0.5874], dtype=float16),
 array([0.378, 0.622], dtype=float16),
 array([0.3975, 0.6025], dtype=float16),
 array([0.4226, 0.5776], dtype=float16),
 array([0.3904, 0.6094], dtype=float16),
 array([0.4556, 0.5444], dtype=float16),
 array([0.402 , 0.5977], dtype=float16),
 array([0.48, 0.52], dtype=float16),
 array([0.3784, 0.6216], dtype=float16),
 array([0.4126, 0.5874], dtype=float16),
 array([0.447, 0.553], dtype=float16),
 array([0.447, 0.553], dtype=float16),
 array([0.4243, 0.5757], dtype=float16),
 array([0.4446, 0.5557], dtype=float16),
 array([0.407 , 0.5933], dtype=float16),
 array([0.3918, 0.608 ], dtype=float16),
 array([0.385, 0.615], dtype=float16),
 array([0.3398, 0.66  ], dtype=float16),
 array([0.4387, 0.561 ], dtype=float16),
 array([0.4102, 0.59  ], dtype=float16),
 array([0.423, 0.577], dtype=float16)]

In [65]:
preds

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1]

In [66]:
df = pd.DataFrame({
    "text": test["text"],
    "predicted_label": preds,
    "prob_0": [p[0] for p in preds_prob],
    "prob_1": [p[1] for p in preds_prob],
})

In [67]:
df.head()

,text,predicted_label,prob_0,prob_1
0,Classify the self-reported stress level just b...,1,0.423828,0.576172
1,Classify the self-reported stress level just b...,1,0.485352,0.514648
2,Classify the self-reported stress level just b...,1,0.412109,0.587891
3,Classify the self-reported stress level just b...,1,0.483398,0.516602
4,Classify the self-reported stress level just b...,1,0.415283,0.584473

In [68]:
# ✅ CSV 저장
df.to_csv("model_predictions_Q3.csv", index=False)
print("Saved to model_predictions Q3.csv")

Saved to model_predictions Q3.csv