<a href="https://colab.research.google.com/github/jacobgreen4477/The-4th-ETRI-AI-Human-Understanding-Competition/blob/main/etri_baseline_v5_0_4(%EC%A6%9D%EA%B0%95).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 📦 전처리 파일 불러오기
파일 from etri_baseline_v6_1_1.ipynb

In [1]:
# Core Libraries
import os
import sys
import json
import re
import ast
import glob
import random
from functools import reduce
from io import StringIO
from collections import Counter
from datetime import datetime, timedelta, time

# Numerical Operations
import numpy as np
import pandas as pd

# Math & Geospatial
from math import radians, cos, sin, asin, sqrt
from scipy.stats import entropy
from haversine import haversine

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Machine Learning
from sklearn.model_selection import (
    train_test_split, KFold, StratifiedKFold, cross_val_score
)
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import f1_score, roc_auc_score, roc_curve, log_loss
from lightgbm import LGBMClassifier, log_evaluation, early_stopping
from xgboost import XGBClassifier
import lightgbm as lgb

# Deep Learning (PyTorch)
import torch
from torch import nn, optim
from torch.utils.data import DataLoader, Dataset
from torch.nn import functional as F

# Progress Tracking
from tqdm import tqdm
from tqdm.auto import tqdm
from category_encoders import TargetEncoder

# Warnings
import warnings
warnings.filterwarnings('ignore')

# seed 고정
SD = 42
random.seed(SD)
np.random.seed(SD)
os.environ['PYTHONHASHSEED'] = str(SD)

# pandas 옵션
pd.set_option('display.max_columns', 999)
pd.set_option('display.max_rows', 999)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.float_format', lambda x: '%0.4f' % x)

c:\Users\lhj56\ws\etri\lhj\.venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
train2 = pd.read_parquet(f"../data/train_0524_v1.parquet")
test2 = pd.read_parquet(f"../data/test_0524_v1.parquet")

In [3]:
train = train2.copy()
test = test2.copy()

In [4]:
train.shape, test.shape

((450, 252), (250, 252))

In [5]:
train.dtypes

subject_id                               object
sleep_date                               object
lifelog_date                             object
Q1                                        int64
Q2                                        int64
Q3                                        int64
S1                                        int64
S2                                        int64
S3                                        int64
charging_ratio                          float64
charging_sum                            float64
charging_transitions                    float64
avg_charging_duration                   float64
max_charging_duration                   float64
sleep_charging_ratio                    float64
sleep_charging_sum                      float64
sleep_charging_transitions              float64
sleep_avg_charging_duration             float64
sleep_max_charging_duration             float64
walking_minutes                         float64
vehicle_minutes                         float64
activity_minutes                        float64
sleep_walking_minutes                   float64
sleep_vehicle_minutes                   float64
sleep_activity_minutes                  float64
m_activity@240min@std@00h00m            float64
m_activity@240min@std@04h00m            float64
m_activity@240min@std@08h00m            float64
m_activity@240min@std@12h00m            float64
m_activity@240min@std@16h00m            float64
m_activity@240min@std@20h00m            float64
m_activity_met@240min@std@00h00m        float64
m_activity_met@240min@std@04h00m        float64
m_activity_met@240min@std@08h00m        float64
m_activity_met@240min@std@12h00m        float64
m_activity_met@240min@std@16h00m        float64
m_activity_met@240min@std@20h00m        float64
m_activity_met@240min@sum@00h00m        float64
m_activity_met@240min@sum@04h00m        float64
m_activity_met@240min@sum@08h00m        float64
m_activity_met@240min@sum@12h00m        float64
m_activity_met@240min@sum@16h00m        float64
m_activity_met@240min@sum@20h00m        float64
m_activity_0@240min@std@00h00m          float64
m_activity_0@240min@std@04h00m          float64
m_activity_0@240min@std@08h00m          float64
m_activity_0@240min@std@12h00m          float64
m_activity_0@240min@std@16h00m          float64
m_activity_0@240min@std@20h00m          float64
m_activity_0@240min@sum@00h00m          float64
m_activity_0@240min@sum@04h00m          float64
m_activity_0@240min@sum@08h00m          float64
m_activity_0@240min@sum@12h00m          float64
m_activity_0@240min@sum@16h00m          float64
m_activity_0@240min@sum@20h00m          float64
active_hour_unique_label_count          float64
active_hour_snor_count                  float64
sleep_hour_unique_label_count           float64
sleep_hour_snor_count                   float64
work_hour_rssi_mean                     float64
work_hour_rssi_min                      float64
work_hour_rssi_max                      float64
work_hour_others_ratio                  float64
work_hour_unknown_ratio                 float64
free_hour_rssi_mean                     float64
free_hour_rssi_min                      float64
free_hour_rssi_max                      float64
free_hour_others_ratio                  float64
free_hour_unknown_ratio                 float64
sleep_hour_rssi_mean                    float64
sleep_hour_rssi_min                     float64
sleep_hour_rssi_max                     float64
sleep_hour_others_ratio                 float64
sleep_hour_unknown_ratio                float64
active_hour_walk_minutes                float64
active_hour_jog_minutes                 float64
active_hour_vehicle_minutes             float64
active_hour_mean_speed                  float64
active_hour_max_speed                   float64
active_hour_min_speed                   float64
active_hour_distance_x                  float64
exercise_flag                           float64
sleep_hour_walk_minutes                 float64
sleep_hour_jog_minutes                  float64
sleep_hour_vehicle_minutes              float64
sleep_hour_mean_speed                   float64
sleep_hour_max_speed                    float64
sleep_hour_min_speed                    float64
sleep_hour_distance_x                   float64
mgps_first_wakeup_minutes               float64
light_mean                              float64
light_std                               float64
light_max                               float64
light_min                               float64
light_night_mean                        float64
light_day_mean                          float64
light_night_ratio                       float64
sleep_duration_min_mLight               float64
sleep_time_min_mLight                   float64
wake_time_min_mLight                    float64
hour_slept_mLight                       float64
hour_woke_up_mLight                     float64
sleep_duration_interp_mLight            float64
sleep_duration_hour_mLight              float64
sleep_duration_interp_hour_mLight       float64
light_sleep_time                        float64
light_wake_time                         float64
light_sleep_duration_min                float64
light_weekday                           float64
light_month                             float64
light_avg_sleep_time                    float64
light_avg_wake_time                     float64
light_avg_sleep_duration                float64
light_sleep_time_diff                   float64
light_wake_time_diff                    float64
light_sleep_duration_diff               float64
light_sleep_time_ratio                  float64
light_wake_time_ratio                   float64
light_sleep_duration_ratio              float64
light_sleep_time_lag1                   float64
light_sleep_duration_lag1               float64
light_sleep_time_diff_lag1              float64
light_wake_time_diff_lag1               float64
light_sleep_duration_diff_lag1          float64
light_sleep_time_lag2                   float64
light_wake_time_lag2                    float64
light_sleep_duration_lag2               float64
light_sleep_time_diff_lag2              float64
light_wake_time_diff_lag2               float64
light_sleep_duration_diff_lag2          float64
light_week_type_lag1                     object
light_rolling_sleep_time_2d             float64
light_rolling_wake_time_2d              float64
light_rolling_sleep_duration_2d         float64
light_rolling_sleep_time_3d             float64
light_rolling_wake_time_3d              float64
light_rolling_sleep_duration_3d         float64
light_weekday_avg_sleep                 float64
light_sleep_duration_vs_weekday_avg     float64
light_is_sleep_duration_change_large    float64
lights_off_time                         float64
sleep_time                              float64
wake_time                               float64
sleep_duration_min                      float64
weekday                                 float64
week_type                                object
month                                   float64
avg_sleep_time                          float64
avg_wake_time                           float64
avg_sleep_duration                      float64
sleep_time_diff                         float64
wake_time_diff                          float64
sleep_duration_diff                     float64
sleep_time_ratio                        float64
wake_time_ratio                         float64
sleep_duration_ratio                    float64
sleep_time_lag1                         float64
wake_time_lag1                          float64
sleep_duration_lag1                     float64
sleep_time_diff_lag1                    float64
wake_time_diff_lag1                     float64
sleep_duration_diff_lag1                float64
sleep_time_lag2                         float64
wake_time_lag2                          float64
sleep_duration_lag2                     float64
sleep_time_diff_lag2                    float64
wake_time_diff_lag2                     float64
sleep_duration_diff_lag2                float64
week_type_lag1                           object
rolling_sleep_time_2d                   float64
rolling_wake_time_2d                    float64
rolling_sleep_duration_2d               float64
rolling_sleep_time_3d                   float64
rolling_wake_time_3d                    float64
rolling_sleep_duration_3d               float64
weekday_avg_sleep                       float64
sleep_duration_vs_weekday_avg           float64
is_sleep_duration_change_large          float64
activehour_통화_time                      float64
beforebed_통화_time                       float64
activehour_전화_time                      float64
beforebed_전화_time                       float64
activehour_YouTube_time                 float64
beforebed_YouTube_time                  float64
activehour_메신저_time                     float64
beforebed_메신저_time                      float64
activehour_NAVER_time                   float64
beforebed_NAVER_time                    float64
activehour_캐시워크_time                    float64
beforebed_캐시워크_time                     float64
activehour_성경일독Q_time                   float64
beforebed_성경일독Q_time                    float64
activehour_OneUI홈_time                  float64
beforebed_OneUI홈_time                   float64
activehour_unique_app_count             float64
beforebed_unique_app_count              float64
activehour_total_screen_time            float64
beforebed_total_screen_time             float64
activehour_screen_time_vs_avg_pct       float64
beforebed_screen_time_vs_avg_pct        float64
activehour_scan_count                   float64
beforebed_scan_count                    float64
activehour_unique_bssid_count           float64
beforebed_unique_bssid_count            float64
activehour_avg_rssi                     float64
beforebed_avg_rssi                      float64
activehour_max_rssi                     float64
beforebed_max_rssi                      float64
activehour_min_rssi                     float64
beforebed_min_rssi                      float64
activehour_strong_signal_ratio          float64
beforebed_strong_signal_ratio           float64
activehour_empty_scan_count             float64
beforebed_empty_scan_count              float64
activehour_top_bssid                     object
beforebed_top_bssid                      object
activehour_top_bssid_count              float64
beforebed_top_bssid_count               float64
activehour_hour_span_minutes            float64
beforebed_hour_span_minutes             float64
active_hour_mean_hr                     float64
active_hour_min_hr                      float64
active_hour_max_hr                      float64
active_hour_std_hr                      float64
active_hour_high_hr                     float64
sleep_hour_mean_hr                      float64
sleep_hour_min_hr                       float64
sleep_hour_max_hr                       float64
sleep_hour_std_hr                       float64
sleep_hour_high_hr                      float64
active_hour_mean_light                  float64
active_hour_min_light                   float64
active_hour_max_light                   float64
active_hour_std_light                   float64
sleep_hour_mean_light                   float64
sleep_hour_min_light                    float64
sleep_hour_max_light                    float64
sleep_hour_std_light                    float64
mlight_first_sleep_minutes              float64
mlight_first_wakeup_minutes             float64
active_hour_steps                       float64
active_hour_distance_y                  float64
active_hour_burned_calories             float64
sleep_hour_steps                        float64
sleep_hour_distance_y                   float64
sleep_hour_burned_calories              float64
m_light_awake_minutes                   float64
m_light_awake_blocks                    float64
w_light_awake_minutes                   float64
w_light_awake_blocks                    float64
light_awake_minutes                     float64
light_awake_blocks                      float64
dtype: object

In [6]:
!python download_dataset.py --dataname adult
!python process_dataset.py --dataname adult

Start processing dataset adult from UCI.
Aready downloaded.
Start processing dataset default from UCI.
Aready downloaded.
Start processing dataset magic from UCI.
Aready downloaded.
Start processing dataset shoppers from UCI.
Aready downloaded.
Start processing dataset beijing from UCI.
Aready downloaded.
Start processing dataset news from UCI.
Aready downloaded.
adult (32561, 15) (16281, 15) (32561, 15)
Numerical (32561, 6)
Categorical (32561, 8)
Processing and Saving adult Successfully!
adult
Total 48842
Train 32561
Test 16281
Num 6
Cat 9

## 🥸 sample data 확인

In [7]:
x_cat_train = np.load("./data/adult/X_cat_train.npy", allow_pickle=True)
x_num_train = np.load("./data/adult/X_num_train.npy", allow_pickle=True)
y_train = np.load("./data/adult/y_train.npy", allow_pickle=True)

with open("./data/adult/info.json") as f:
    info = json.load(f)

In [8]:
x_cat_train.shape, x_cat_train[:2]

((32561, 8),
 array([[' State-gov', ' Bachelors', ' Never-married', ' Adm-clerical',
         ' Not-in-family', ' White', ' Male', ' United-States'],
        [' Self-emp-not-inc', ' Bachelors', ' Married-civ-spouse',
         ' Exec-managerial', ' Husband', ' White', ' Male',
         ' United-States']], dtype=object))

In [9]:
x_num_train.shape, x_num_train[:2]

((32561, 6),
 array([[3.9000e+01, 7.7516e+04, 1.3000e+01, 2.1740e+03, 0.0000e+00,
         4.0000e+01],
        [5.0000e+01, 8.3311e+04, 1.3000e+01, 0.0000e+00, 0.0000e+00,
         1.3000e+01]], dtype=float32))

In [10]:
y_train.shape, y_train[:2]

((32561, 1),
 array([[' <=50K'],
        [' <=50K']], dtype=object))

In [11]:
info.keys()
# 'name', 'task_type', 'header', 'column_names', 'num_col_idx', 'cat_col_idx', 'target_col_idx', 'file_type', 'data_path', 'test_path', 'column_info', 'train_num', 'test_num', 'idx_mapping', 'inverse_idx_mapping', 'idx_name_mapping', 'metadata'

# 필수 키
# task_type: binclass, multiclass 중 하나
# num_col_idx: 수치형 컬럼 인덱스 리스트
# cat_col_idx: 범주형 컬럼 인덱스 리스트

# target_col_idx: 생성할 타겟 컬럼 인덱스
# idx_mapping: 컬럼 인덱스와 컬럼 이름 매핑 딕셔너리
# n_classes: 클래스 개수

dict_keys(['name', 'task_type', 'header', 'column_names', 'num_col_idx', 'cat_col_idx', 'target_col_idx', 'file_type', 'data_path', 'test_path', 'column_info', 'train_num', 'test_num', 'idx_mapping', 'inverse_idx_mapping', 'idx_name_mapping', 'metadata'])

## 📦 우리 데이터 전처리

In [12]:
def make_tabsyn_data(df, result_dir="./data"):
    targets_binary = ['Q1', 'Q2', 'Q3', 'S1', 'S2', 'S3']

    df: pd.DataFrame = df.copy()
    x_data = df
    x_data = x_data.astype({
        'Q1': 'object', 'Q2': 'object', 'Q3': 'object',
        'S1': 'object', 'S2': 'object', 'S3': 'object'
    })

    # feature 분리
    column_names = x_data.columns.tolist()
    categorical_feature_cols = x_data.select_dtypes(include=['object']).columns.tolist()
    num_feature_cols = x_data.select_dtypes(exclude=['object']).columns.tolist()

    x_cat = x_data[categorical_feature_cols].values
    x_num = x_data[num_feature_cols].values

    train_ratio = 0.6

    # 1. 먼저 비율대로 split
    idx = np.arange(df.shape[0])
    train_size = int(train_ratio * df.shape[0])
    np.random.shuffle(idx)
    train_idx = idx[:train_size]
    test_idx = idx[train_size:]
    train_idx_set = set(train_idx)

    # 2. 카테고리별 최소 1개 보장
    cat_uniques = {col: set(x_data[col].unique()) for col in categorical_feature_cols}
    for col in categorical_feature_cols:
        for val in cat_uniques[col]:
            idxs = set(x_data.index[x_data[col] == val])
            if len(idxs) == 0:
                continue  # 값이 실제로 없음
            if not idxs & train_idx_set:
                train_idx_set.add(next(iter(idxs)))

    # 3. train/test 재계산
    train_idx = np.array(sorted(train_idx_set))
    test_idx = np.array([i for i in range(len(x_data)) if i not in train_idx_set])

    print(f"train 개수: {len(train_idx)}, test 개수: {len(test_idx)}")

    x_cat_train = x_cat[train_idx]
    x_cat_test = x_cat[test_idx]
    x_num_train = x_num[train_idx]
    x_num_test = x_num[test_idx]

    num_col_idx = [column_names.index(col) for col in num_feature_cols]
    cat_col_idx = [column_names.index(col) for col in categorical_feature_cols]

    dataset_name = "etri_syn"
    data_dir = os.path.join(result_dir, dataset_name)
    os.makedirs(data_dir, exist_ok=True)

    idx_mapping = {}

    curr_num_idx = 0
    curr_cat_idx = len(num_col_idx)
    curr_target_idx = curr_cat_idx + len(cat_col_idx)

    for idx in range(len(column_names + [dataset_name])):

        if idx in num_col_idx:
            idx_mapping[int(idx)] = curr_num_idx
            curr_num_idx += 1
        elif idx in cat_col_idx:
            idx_mapping[int(idx)] = curr_cat_idx
            curr_cat_idx += 1
        else:
            idx_mapping[int(idx)] = curr_target_idx
            curr_target_idx += 1

    np.save(os.path.join(data_dir, "X_cat_train.npy"), x_cat_train)
    np.save(os.path.join(data_dir, "X_cat_test.npy"), x_cat_test)
    np.save(os.path.join(data_dir, "X_num_train.npy"), x_num_train)
    np.save(os.path.join(data_dir, "X_num_test.npy"), x_num_test)
    # np.save(os.path.join(data_dir, "y_train.npy"), y_data.iloc[train_idx][target_col].values)
    # np.save(os.path.join(data_dir, "y_test.npy"), y_data.iloc[test_idx][target_col].values)
    np.save(os.path.join(data_dir, "y_train.npy"), np.zeros(len(train_idx), dtype=int))
    np.save(os.path.join(data_dir, "y_test.npy"), np.zeros(len(test_idx), dtype=int))
    with open(os.path.join(data_dir, "info.json"), "w") as f:
        json.dump({
            "name": dataset_name,
            "task_type": "multiclass",
            "n_classes": 2,
            "header": None,
            "column_names": column_names + [dataset_name],
            "num_col_idx": [column_names.index(col) for col in num_feature_cols],
            "cat_col_idx": [column_names.index(col) for col in categorical_feature_cols],
            "target_col_idx": [len(column_names)],
            "file_type": "npy",
            "data_path": os.path.join(data_dir, "X_cat_train.npy"),
            "test_path": os.path.join(data_dir, "X_cat_test.npy"),
            "column_info": {col: str(x_data[col].dtype) for col in column_names},
            "train_num": len(train_idx),
            "test_num": len(test_idx),
            "idx_mapping": idx_mapping,
            "inverse_idx_mapping": {v: k for k, v in idx_mapping.items()},
            "idx_name_mapping": {str(i): name for i, name in enumerate(column_names + [dataset_name])},
            "metadata": {
                "columns": {
                    str(i): {
                        "sdtype": "numerical" if col in num_feature_cols else "categorical"
                    } for i, col in enumerate(column_names)
                }
            }
        }, f, indent=4)

In [13]:
make_tabsyn_data(train)

train 개수: 322, test 개수: 128

### 📦 Tabsyn 학습
- 비고
  - vae epoch 4000 -> 4000 (`tabsyn/vae/main.py` 118 번 줄)
  - tabsyn epoch 10001 -> 10001 (`tabsyn/tabsyn/main.py` 44 번 줄)
  - 생성 갯수 조정 파라미터 추가 (`tabsyn/utils.py` 120 번 줄)

In [14]:
import torch
torch.cuda.is_available()

True

In [ ]:
%run main.py --method vae  --dataname etri_syn

Using device: cuda:0
self.category_embeddings.weight.shape=torch.Size([500, 4])
self.category_embeddings.weight.shape=torch.Size([500, 4])

Epoch 1/4000: 100%|██████████| 1/1 [00:00<00:00,  3.25it/s]

epoch: 0, beta = 0.010000, Train MSE: 6.710555, Train CE:1.975018, Train KL:0.498826, Val MSE:6.782426, Val CE:1.960522, Train ACC:0.387992, Val ACC:0.385938

Epoch 2/4000: 100%|██████████| 1/1 [00:00<00:00, 22.15it/s]

epoch: 1, beta = 0.010000, Train MSE: 6.684830, Train CE:1.945441, Train KL:0.499625, Val MSE:6.750818, Val CE:1.932777, Train ACC:0.398344, Val ACC:0.395313

Epoch 3/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 2, beta = 0.010000, Train MSE: 6.671066, Train CE:1.935616, Train KL:0.508518, Val MSE:6.726808, Val CE:1.918905, Train ACC:0.391304, Val ACC:0.404167

Epoch 4/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 3, beta = 0.010000, Train MSE: 6.635061, Train CE:1.926077, Train KL:0.523803, Val MSE:6.700577, Val CE:1.918817, Train ACC:0.393375, Val ACC:0.405729

Epoch 5/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 4, beta = 0.010000, Train MSE: 6.620110, Train CE:1.910304, Train KL:0.543332, Val MSE:6.687001, Val CE:1.886838, Train ACC:0.398137, Val ACC:0.425521

Epoch 6/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 5, beta = 0.010000, Train MSE: 6.592277, Train CE:1.909758, Train KL:0.566052, Val MSE:6.663714, Val CE:1.895652, Train ACC:0.408489, Val ACC:0.419271

Epoch 7/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 6, beta = 0.010000, Train MSE: 6.567233, Train CE:1.896315, Train KL:0.590475, Val MSE:6.632494, Val CE:1.887094, Train ACC:0.411180, Val ACC:0.418750

Epoch 8/4000: 100%|██████████| 1/1 [00:00<00:00, 23.81it/s]

epoch: 7, beta = 0.010000, Train MSE: 6.546767, Train CE:1.889347, Train KL:0.616551, Val MSE:6.610821, Val CE:1.876974, Train ACC:0.418427, Val ACC:0.431250

Epoch 9/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 8, beta = 0.010000, Train MSE: 6.520447, Train CE:1.878420, Train KL:0.644296, Val MSE:6.587301, Val CE:1.869207, Train ACC:0.430849, Val ACC:0.435417

Epoch 10/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 9, beta = 0.010000, Train MSE: 6.496683, Train CE:1.871121, Train KL:0.672851, Val MSE:6.562541, Val CE:1.866330, Train ACC:0.436439, Val ACC:0.436979

Epoch 11/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 10, beta = 0.010000, Train MSE: 6.472991, Train CE:1.873496, Train KL:0.702449, Val MSE:6.540105, Val CE:1.867466, Train ACC:0.440580, Val ACC:0.431771

Epoch 12/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 11, beta = 0.010000, Train MSE: 6.445946, Train CE:1.865957, Train KL:0.732969, Val MSE:6.514713, Val CE:1.847270, Train ACC:0.441408, Val ACC:0.452604

Epoch 13/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 12, beta = 0.010000, Train MSE: 6.417260, Train CE:1.859119, Train KL:0.765121, Val MSE:6.471438, Val CE:1.840928, Train ACC:0.450311, Val ACC:0.472396

Epoch 14/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 13, beta = 0.010000, Train MSE: 6.387621, Train CE:1.849208, Train KL:0.799083, Val MSE:6.442646, Val CE:1.834996, Train ACC:0.459834, Val ACC:0.469271

Epoch 15/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 14, beta = 0.010000, Train MSE: 6.354889, Train CE:1.839244, Train KL:0.835231, Val MSE:6.416467, Val CE:1.830104, Train ACC:0.474948, Val ACC:0.473438

Epoch 16/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 15, beta = 0.010000, Train MSE: 6.325044, Train CE:1.835570, Train KL:0.873264, Val MSE:6.375501, Val CE:1.818791, Train ACC:0.476605, Val ACC:0.486979

Epoch 17/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 16, beta = 0.010000, Train MSE: 6.289958, Train CE:1.824082, Train KL:0.913742, Val MSE:6.342475, Val CE:1.817631, Train ACC:0.485507, Val ACC:0.492188

Epoch 18/4000: 100%|██████████| 1/1 [00:00<00:00, 23.17it/s]

epoch: 17, beta = 0.010000, Train MSE: 6.255317, Train CE:1.812142, Train KL:0.956855, Val MSE:6.301080, Val CE:1.801556, Train ACC:0.498344, Val ACC:0.505729

Epoch 19/4000: 100%|██████████| 1/1 [00:00<00:00, 18.01it/s]

epoch: 18, beta = 0.010000, Train MSE: 6.213054, Train CE:1.803106, Train KL:1.002474, Val MSE:6.258651, Val CE:1.787081, Train ACC:0.505797, Val ACC:0.513021

Epoch 20/4000: 100%|██████████| 1/1 [00:00<00:00, 23.51it/s]

epoch: 19, beta = 0.010000, Train MSE: 6.173359, Train CE:1.789919, Train KL:1.050397, Val MSE:6.218817, Val CE:1.774274, Train ACC:0.512629, Val ACC:0.527083

Epoch 21/4000: 100%|██████████| 1/1 [00:00<00:00, 23.27it/s]

epoch: 20, beta = 0.010000, Train MSE: 6.133367, Train CE:1.777252, Train KL:1.099969, Val MSE:6.172748, Val CE:1.763881, Train ACC:0.523810, Val ACC:0.531250

Epoch 22/4000: 100%|██████████| 1/1 [00:00<00:00, 22.70it/s]

epoch: 21, beta = 0.010000, Train MSE: 6.087145, Train CE:1.767111, Train KL:1.150769, Val MSE:6.119174, Val CE:1.745556, Train ACC:0.531884, Val ACC:0.554167

Epoch 23/4000: 100%|██████████| 1/1 [00:00<00:00, 22.95it/s]

epoch: 22, beta = 0.010000, Train MSE: 6.038489, Train CE:1.749819, Train KL:1.202529, Val MSE:6.073490, Val CE:1.731159, Train ACC:0.545342, Val ACC:0.558333

Epoch 24/4000: 100%|██████████| 1/1 [00:00<00:00, 23.30it/s]

epoch: 23, beta = 0.010000, Train MSE: 5.990829, Train CE:1.739096, Train KL:1.255950, Val MSE:6.017686, Val CE:1.724638, Train ACC:0.549482, Val ACC:0.557292

Epoch 25/4000: 100%|██████████| 1/1 [00:00<00:00, 23.55it/s]

epoch: 24, beta = 0.010000, Train MSE: 5.936417, Train CE:1.726770, Train KL:1.311167, Val MSE:5.960363, Val CE:1.710341, Train ACC:0.558799, Val ACC:0.566667

Epoch 26/4000: 100%|██████████| 1/1 [00:00<00:00, 23.03it/s]

epoch: 25, beta = 0.010000, Train MSE: 5.882001, Train CE:1.714355, Train KL:1.368182, Val MSE:5.895859, Val CE:1.697959, Train ACC:0.561698, Val ACC:0.564063

Epoch 27/4000: 100%|██████████| 1/1 [00:00<00:00, 18.00it/s]

epoch: 26, beta = 0.010000, Train MSE: 5.822513, Train CE:1.703771, Train KL:1.427290, Val MSE:5.836372, Val CE:1.681501, Train ACC:0.568530, Val ACC:0.573958

Epoch 28/4000: 100%|██████████| 1/1 [00:00<00:00, 23.81it/s]

epoch: 27, beta = 0.010000, Train MSE: 5.763415, Train CE:1.683212, Train KL:1.488338, Val MSE:5.772143, Val CE:1.672435, Train ACC:0.577019, Val ACC:0.575000

Epoch 29/4000: 100%|██████████| 1/1 [00:00<00:00, 27.07it/s]

epoch: 28, beta = 0.010000, Train MSE: 5.699052, Train CE:1.674250, Train KL:1.551170, Val MSE:5.704320, Val CE:1.657683, Train ACC:0.578675, Val ACC:0.579688

Epoch 30/4000: 100%|██████████| 1/1 [00:00<00:00, 20.55it/s]

epoch: 29, beta = 0.010000, Train MSE: 5.632370, Train CE:1.664890, Train KL:1.616656, Val MSE:5.630279, Val CE:1.641809, Train ACC:0.589027, Val ACC:0.584896

Epoch 31/4000: 100%|██████████| 1/1 [00:00<00:00, 22.45it/s]

epoch: 30, beta = 0.010000, Train MSE: 5.559395, Train CE:1.650671, Train KL:1.684639, Val MSE:5.552879, Val CE:1.630682, Train ACC:0.586749, Val ACC:0.593229

Epoch 32/4000: 100%|██████████| 1/1 [00:00<00:00, 23.50it/s]

epoch: 31, beta = 0.010000, Train MSE: 5.486364, Train CE:1.642763, Train KL:1.754362, Val MSE:5.476357, Val CE:1.620375, Train ACC:0.589648, Val ACC:0.592708

Epoch 33/4000: 100%|██████████| 1/1 [00:00<00:00, 18.42it/s]

epoch: 32, beta = 0.010000, Train MSE: 5.408944, Train CE:1.624991, Train KL:1.826361, Val MSE:5.401236, Val CE:1.613142, Train ACC:0.595238, Val ACC:0.596354

Epoch 34/4000: 100%|██████████| 1/1 [00:00<00:00, 23.03it/s]

epoch: 33, beta = 0.010000, Train MSE: 5.327820, Train CE:1.616788, Train KL:1.900134, Val MSE:5.310361, Val CE:1.599741, Train ACC:0.597930, Val ACC:0.595833

Epoch 35/4000: 100%|██████████| 1/1 [00:00<00:00, 23.75it/s]

epoch: 34, beta = 0.010000, Train MSE: 5.243468, Train CE:1.605983, Train KL:1.975603, Val MSE:5.221382, Val CE:1.585971, Train ACC:0.601863, Val ACC:0.600521

Epoch 36/4000: 100%|██████████| 1/1 [00:00<00:00, 25.14it/s]

epoch: 35, beta = 0.010000, Train MSE: 5.160705, Train CE:1.598515, Train KL:2.052977, Val MSE:5.128271, Val CE:1.575602, Train ACC:0.604348, Val ACC:0.610417

Epoch 37/4000: 100%|██████████| 1/1 [00:00<00:00, 25.65it/s]

epoch: 36, beta = 0.010000, Train MSE: 5.069479, Train CE:1.589212, Train KL:2.132602, Val MSE:5.038040, Val CE:1.570066, Train ACC:0.606418, Val ACC:0.610938

Epoch 38/4000: 100%|██████████| 1/1 [00:00<00:00, 21.08it/s]

epoch: 37, beta = 0.010000, Train MSE: 4.975631, Train CE:1.577910, Train KL:2.214295, Val MSE:4.936438, Val CE:1.549457, Train ACC:0.612008, Val ACC:0.614063

Epoch 39/4000: 100%|██████████| 1/1 [00:00<00:00, 21.61it/s]

epoch: 38, beta = 0.010000, Train MSE: 4.879516, Train CE:1.566615, Train KL:2.298013, Val MSE:4.837427, Val CE:1.547845, Train ACC:0.615321, Val ACC:0.613021

Epoch 40/4000: 100%|██████████| 1/1 [00:00<00:00, 21.46it/s]

epoch: 39, beta = 0.010000, Train MSE: 4.781137, Train CE:1.559027, Train KL:2.384178, Val MSE:4.734703, Val CE:1.539482, Train ACC:0.615735, Val ACC:0.618750

Epoch 41/4000: 100%|██████████| 1/1 [00:00<00:00, 23.47it/s]

epoch: 40, beta = 0.010000, Train MSE: 4.673353, Train CE:1.550792, Train KL:2.473177, Val MSE:4.618338, Val CE:1.532049, Train ACC:0.617598, Val ACC:0.619271

Epoch 42/4000: 100%|██████████| 1/1 [00:00<00:00, 22.15it/s]

epoch: 41, beta = 0.010000, Train MSE: 4.570507, Train CE:1.544455, Train KL:2.564672, Val MSE:4.517416, Val CE:1.521119, Train ACC:0.616977, Val ACC:0.618229

Epoch 43/4000: 100%|██████████| 1/1 [00:00<00:00, 23.73it/s]

epoch: 42, beta = 0.010000, Train MSE: 4.467639, Train CE:1.537221, Train KL:2.658628, Val MSE:4.410159, Val CE:1.514087, Train ACC:0.619255, Val ACC:0.620313

Epoch 44/4000: 100%|██████████| 1/1 [00:00<00:00, 17.40it/s]

epoch: 43, beta = 0.010000, Train MSE: 4.357271, Train CE:1.528563, Train KL:2.753729, Val MSE:4.300288, Val CE:1.505390, Train ACC:0.620911, Val ACC:0.620833

Epoch 45/4000: 100%|██████████| 1/1 [00:00<00:00, 21.49it/s]

epoch: 44, beta = 0.010000, Train MSE: 4.250598, Train CE:1.522569, Train KL:2.849554, Val MSE:4.185826, Val CE:1.500703, Train ACC:0.621532, Val ACC:0.623958

Epoch 46/4000: 100%|██████████| 1/1 [00:00<00:00, 20.12it/s]

epoch: 45, beta = 0.010000, Train MSE: 4.138168, Train CE:1.513622, Train KL:2.946723, Val MSE:4.077350, Val CE:1.489959, Train ACC:0.623603, Val ACC:0.623438

Epoch 47/4000: 100%|██████████| 1/1 [00:00<00:00, 22.49it/s]

epoch: 46, beta = 0.010000, Train MSE: 4.029734, Train CE:1.504499, Train KL:3.044997, Val MSE:3.962412, Val CE:1.480325, Train ACC:0.624431, Val ACC:0.628646

Epoch 48/4000: 100%|██████████| 1/1 [00:00<00:00, 21.57it/s]

epoch: 47, beta = 0.010000, Train MSE: 3.922002, Train CE:1.495839, Train KL:3.144525, Val MSE:3.851507, Val CE:1.471009, Train ACC:0.627536, Val ACC:0.631250

Epoch 49/4000: 100%|██████████| 1/1 [00:00<00:00, 21.97it/s]

epoch: 48, beta = 0.010000, Train MSE: 3.808830, Train CE:1.482505, Train KL:3.246744, Val MSE:3.740385, Val CE:1.462235, Train ACC:0.633747, Val ACC:0.637500

Epoch 50/4000: 100%|██████████| 1/1 [00:00<00:00, 21.19it/s]

epoch: 49, beta = 0.010000, Train MSE: 3.702906, Train CE:1.474168, Train KL:3.350587, Val MSE:3.628918, Val CE:1.452875, Train ACC:0.633954, Val ACC:0.636458

Epoch 51/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 50, beta = 0.010000, Train MSE: 3.589463, Train CE:1.464028, Train KL:3.456511, Val MSE:3.510418, Val CE:1.444528, Train ACC:0.638923, Val ACC:0.644792

Epoch 52/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 51, beta = 0.010000, Train MSE: 3.475247, Train CE:1.454129, Train KL:3.563702, Val MSE:3.406821, Val CE:1.433073, Train ACC:0.642443, Val ACC:0.642188

Epoch 53/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 52, beta = 0.010000, Train MSE: 3.372172, Train CE:1.444360, Train KL:3.671969, Val MSE:3.292619, Val CE:1.423673, Train ACC:0.646998, Val ACC:0.646354

Epoch 54/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 53, beta = 0.010000, Train MSE: 3.262360, Train CE:1.431314, Train KL:3.781458, Val MSE:3.188324, Val CE:1.412565, Train ACC:0.647205, Val ACC:0.651563

Epoch 55/4000: 100%|██████████| 1/1 [00:00<00:00, 23.81it/s]

epoch: 54, beta = 0.010000, Train MSE: 3.156929, Train CE:1.419001, Train KL:3.891404, Val MSE:3.079197, Val CE:1.400789, Train ACC:0.647619, Val ACC:0.653646

Epoch 56/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 55, beta = 0.010000, Train MSE: 3.050287, Train CE:1.406214, Train KL:4.001646, Val MSE:2.974205, Val CE:1.390682, Train ACC:0.650725, Val ACC:0.653125

Epoch 57/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 56, beta = 0.010000, Train MSE: 2.947143, Train CE:1.397781, Train KL:4.111771, Val MSE:2.871042, Val CE:1.382033, Train ACC:0.650932, Val ACC:0.654167

Epoch 58/4000: 100%|██████████| 1/1 [00:00<00:00, 23.81it/s]

epoch: 57, beta = 0.010000, Train MSE: 2.840674, Train CE:1.388705, Train KL:4.221719, Val MSE:2.771869, Val CE:1.370902, Train ACC:0.654037, Val ACC:0.652083

Epoch 59/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 58, beta = 0.010000, Train MSE: 2.742687, Train CE:1.379974, Train KL:4.330827, Val MSE:2.673440, Val CE:1.361840, Train ACC:0.656729, Val ACC:0.656250

Epoch 60/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 59, beta = 0.010000, Train MSE: 2.643978, Train CE:1.369142, Train KL:4.439220, Val MSE:2.578699, Val CE:1.351343, Train ACC:0.659006, Val ACC:0.657813

Epoch 61/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 60, beta = 0.010000, Train MSE: 2.549274, Train CE:1.357833, Train KL:4.545940, Val MSE:2.482221, Val CE:1.340748, Train ACC:0.660248, Val ACC:0.664063

Epoch 62/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 61, beta = 0.010000, Train MSE: 2.458597, Train CE:1.344225, Train KL:4.649344, Val MSE:2.395083, Val CE:1.326954, Train ACC:0.666253, Val ACC:0.666146

Epoch 63/4000: 100%|██████████| 1/1 [00:00<00:00, 22.69it/s]

epoch: 62, beta = 0.010000, Train MSE: 2.365416, Train CE:1.329456, Train KL:4.750798, Val MSE:2.304725, Val CE:1.313566, Train ACC:0.670807, Val ACC:0.675000

Epoch 64/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 63, beta = 0.010000, Train MSE: 2.282616, Train CE:1.319415, Train KL:4.850520, Val MSE:2.228471, Val CE:1.298466, Train ACC:0.674327, Val ACC:0.680208

Epoch 65/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 64, beta = 0.010000, Train MSE: 2.198850, Train CE:1.306483, Train KL:4.951149, Val MSE:2.142157, Val CE:1.289814, Train ACC:0.676605, Val ACC:0.676042

Epoch 66/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 65, beta = 0.010000, Train MSE: 2.120284, Train CE:1.294907, Train KL:5.052422, Val MSE:2.062371, Val CE:1.275922, Train ACC:0.678468, Val ACC:0.679167

Epoch 67/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 66, beta = 0.010000, Train MSE: 2.038964, Train CE:1.282018, Train KL:5.154521, Val MSE:1.982944, Val CE:1.266653, Train ACC:0.678468, Val ACC:0.676042

Epoch 68/4000: 100%|██████████| 1/1 [00:00<00:00, 20.00it/s]

epoch: 67, beta = 0.010000, Train MSE: 1.962474, Train CE:1.273206, Train KL:5.254527, Val MSE:1.909240, Val CE:1.251262, Train ACC:0.678468, Val ACC:0.679688

Epoch 69/4000: 100%|██████████| 1/1 [00:00<00:00, 21.74it/s]

epoch: 68, beta = 0.010000, Train MSE: 1.886301, Train CE:1.259021, Train KL:5.351458, Val MSE:1.836234, Val CE:1.241620, Train ACC:0.678882, Val ACC:0.684375

Epoch 70/4000: 100%|██████████| 1/1 [00:00<00:00, 23.02it/s]

epoch: 69, beta = 0.010000, Train MSE: 1.813340, Train CE:1.247394, Train KL:5.446463, Val MSE:1.769693, Val CE:1.225206, Train ACC:0.684058, Val ACC:0.686458

Epoch 71/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 70, beta = 0.010000, Train MSE: 1.745754, Train CE:1.234784, Train KL:5.540226, Val MSE:1.700100, Val CE:1.214209, Train ACC:0.683851, Val ACC:0.680729

Epoch 72/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 71, beta = 0.010000, Train MSE: 1.678549, Train CE:1.223379, Train KL:5.635419, Val MSE:1.633597, Val CE:1.200803, Train ACC:0.686128, Val ACC:0.685417

Epoch 73/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 72, beta = 0.010000, Train MSE: 1.615280, Train CE:1.209441, Train KL:5.733593, Val MSE:1.576375, Val CE:1.188192, Train ACC:0.685093, Val ACC:0.684896

Epoch 74/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 73, beta = 0.010000, Train MSE: 1.553670, Train CE:1.199258, Train KL:5.831624, Val MSE:1.513746, Val CE:1.174633, Train ACC:0.686957, Val ACC:0.686458

Epoch 75/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 74, beta = 0.010000, Train MSE: 1.492824, Train CE:1.186514, Train KL:5.923774, Val MSE:1.458042, Val CE:1.163058, Train ACC:0.686957, Val ACC:0.693229

Epoch 76/4000: 100%|██████████| 1/1 [00:00<00:00, 23.81it/s]

epoch: 75, beta = 0.010000, Train MSE: 1.437733, Train CE:1.174673, Train KL:6.008387, Val MSE:1.405727, Val CE:1.150447, Train ACC:0.690890, Val ACC:0.700000

Epoch 77/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 76, beta = 0.010000, Train MSE: 1.379762, Train CE:1.162502, Train KL:6.088494, Val MSE:1.350126, Val CE:1.141909, Train ACC:0.696273, Val ACC:0.700521

Epoch 78/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 77, beta = 0.010000, Train MSE: 1.329149, Train CE:1.151512, Train KL:6.164918, Val MSE:1.300139, Val CE:1.126742, Train ACC:0.698758, Val ACC:0.703125

Epoch 79/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 78, beta = 0.010000, Train MSE: 1.280537, Train CE:1.140391, Train KL:6.241006, Val MSE:1.252080, Val CE:1.117778, Train ACC:0.700414, Val ACC:0.705208

Epoch 80/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 79, beta = 0.010000, Train MSE: 1.230811, Train CE:1.130017, Train KL:6.318451, Val MSE:1.203634, Val CE:1.108878, Train ACC:0.703106, Val ACC:0.715625

Epoch 81/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 80, beta = 0.010000, Train MSE: 1.183479, Train CE:1.121668, Train KL:6.401510, Val MSE:1.159697, Val CE:1.099695, Train ACC:0.706832, Val ACC:0.715104

Epoch 82/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 81, beta = 0.010000, Train MSE: 1.136954, Train CE:1.113000, Train KL:6.485563, Val MSE:1.115525, Val CE:1.089950, Train ACC:0.712008, Val ACC:0.725000

Epoch 83/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 82, beta = 0.010000, Train MSE: 1.094069, Train CE:1.103348, Train KL:6.563013, Val MSE:1.072652, Val CE:1.078355, Train ACC:0.714493, Val ACC:0.728125

Epoch 84/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 83, beta = 0.010000, Train MSE: 1.051927, Train CE:1.093608, Train KL:6.634611, Val MSE:1.032105, Val CE:1.072268, Train ACC:0.721739, Val ACC:0.726563

Epoch 85/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 84, beta = 0.010000, Train MSE: 1.012430, Train CE:1.085773, Train KL:6.707269, Val MSE:0.991100, Val CE:1.062003, Train ACC:0.720911, Val ACC:0.728125

Epoch 86/4000: 100%|██████████| 1/1 [00:00<00:00, 21.74it/s]

epoch: 85, beta = 0.010000, Train MSE: 0.973322, Train CE:1.077021, Train KL:6.780654, Val MSE:0.955046, Val CE:1.051861, Train ACC:0.722360, Val ACC:0.728646

Epoch 87/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 86, beta = 0.010000, Train MSE: 0.935749, Train CE:1.067685, Train KL:6.850552, Val MSE:0.921934, Val CE:1.044174, Train ACC:0.724638, Val ACC:0.728125

Epoch 88/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 87, beta = 0.010000, Train MSE: 0.901049, Train CE:1.058487, Train KL:6.915486, Val MSE:0.888853, Val CE:1.035270, Train ACC:0.726294, Val ACC:0.730729

Epoch 89/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 88, beta = 0.010000, Train MSE: 0.867880, Train CE:1.050437, Train KL:6.977361, Val MSE:0.857075, Val CE:1.028963, Train ACC:0.725466, Val ACC:0.728646

Epoch 90/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 89, beta = 0.010000, Train MSE: 0.836798, Train CE:1.042340, Train KL:7.033766, Val MSE:0.824513, Val CE:1.020681, Train ACC:0.726087, Val ACC:0.730208

Epoch 91/4000: 100%|██████████| 1/1 [00:00<00:00, 23.81it/s]

epoch: 90, beta = 0.010000, Train MSE: 0.804533, Train CE:1.036642, Train KL:7.082145, Val MSE:0.798358, Val CE:1.011704, Train ACC:0.725880, Val ACC:0.730208

Epoch 92/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 91, beta = 0.010000, Train MSE: 0.776083, Train CE:1.027598, Train KL:7.126672, Val MSE:0.774163, Val CE:1.006220, Train ACC:0.727329, Val ACC:0.728646

Epoch 93/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 92, beta = 0.010000, Train MSE: 0.749217, Train CE:1.019483, Train KL:7.172698, Val MSE:0.746604, Val CE:0.999053, Train ACC:0.729193, Val ACC:0.729688

Epoch 94/4000: 100%|██████████| 1/1 [00:00<00:00, 23.81it/s]

epoch: 93, beta = 0.010000, Train MSE: 0.723009, Train CE:1.011777, Train KL:7.221498, Val MSE:0.719933, Val CE:0.991395, Train ACC:0.729814, Val ACC:0.732292

Epoch 95/4000: 100%|██████████| 1/1 [00:00<00:00, 23.53it/s]

epoch: 94, beta = 0.010000, Train MSE: 0.699143, Train CE:1.004172, Train KL:7.268475, Val MSE:0.697068, Val CE:0.984698, Train ACC:0.730642, Val ACC:0.730729

Epoch 96/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 95, beta = 0.010000, Train MSE: 0.676147, Train CE:0.997230, Train KL:7.312768, Val MSE:0.674445, Val CE:0.976768, Train ACC:0.730849, Val ACC:0.732813

Epoch 97/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 96, beta = 0.010000, Train MSE: 0.654465, Train CE:0.990014, Train KL:7.355199, Val MSE:0.655495, Val CE:0.970683, Train ACC:0.729814, Val ACC:0.732813

Epoch 98/4000: 100%|██████████| 1/1 [00:00<00:00, 22.88it/s]

epoch: 97, beta = 0.010000, Train MSE: 0.633358, Train CE:0.982607, Train KL:7.396907, Val MSE:0.635071, Val CE:0.962630, Train ACC:0.733333, Val ACC:0.736979

Epoch 99/4000: 100%|██████████| 1/1 [00:00<00:00, 23.81it/s]

epoch: 98, beta = 0.010000, Train MSE: 0.612673, Train CE:0.975159, Train KL:7.433122, Val MSE:0.615967, Val CE:0.956185, Train ACC:0.734369, Val ACC:0.736979

Epoch 100/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 99, beta = 0.010000, Train MSE: 0.592766, Train CE:0.968726, Train KL:7.464994, Val MSE:0.595528, Val CE:0.951257, Train ACC:0.736853, Val ACC:0.737500

Epoch 101/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 100, beta = 0.010000, Train MSE: 0.574974, Train CE:0.962344, Train KL:7.495489, Val MSE:0.579915, Val CE:0.943518, Train ACC:0.736853, Val ACC:0.741146

Epoch 102/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 101, beta = 0.010000, Train MSE: 0.557876, Train CE:0.956105, Train KL:7.525626, Val MSE:0.562742, Val CE:0.939440, Train ACC:0.737681, Val ACC:0.740625

Epoch 103/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 102, beta = 0.010000, Train MSE: 0.541475, Train CE:0.947875, Train KL:7.551517, Val MSE:0.546275, Val CE:0.931554, Train ACC:0.741615, Val ACC:0.742708

Epoch 104/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 103, beta = 0.010000, Train MSE: 0.526110, Train CE:0.942259, Train KL:7.577345, Val MSE:0.532394, Val CE:0.926661, Train ACC:0.742029, Val ACC:0.743750

Epoch 105/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 104, beta = 0.010000, Train MSE: 0.510712, Train CE:0.935879, Train KL:7.601808, Val MSE:0.518452, Val CE:0.919722, Train ACC:0.745342, Val ACC:0.746354

Epoch 106/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 105, beta = 0.010000, Train MSE: 0.496694, Train CE:0.928573, Train KL:7.620351, Val MSE:0.503745, Val CE:0.913676, Train ACC:0.746791, Val ACC:0.746875

Epoch 107/4000: 100%|██████████| 1/1 [00:00<00:00, 22.99it/s]

epoch: 106, beta = 0.010000, Train MSE: 0.483463, Train CE:0.922953, Train KL:7.636953, Val MSE:0.491616, Val CE:0.906823, Train ACC:0.747412, Val ACC:0.747396

Epoch 108/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 107, beta = 0.010000, Train MSE: 0.469888, Train CE:0.917823, Train KL:7.652283, Val MSE:0.479533, Val CE:0.901754, Train ACC:0.749896, Val ACC:0.748438

Epoch 109/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 108, beta = 0.010000, Train MSE: 0.457610, Train CE:0.912119, Train KL:7.662921, Val MSE:0.466983, Val CE:0.898838, Train ACC:0.749068, Val ACC:0.747917

Epoch 110/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 109, beta = 0.010000, Train MSE: 0.445955, Train CE:0.905075, Train KL:7.676861, Val MSE:0.455986, Val CE:0.890963, Train ACC:0.751967, Val ACC:0.751042

Epoch 111/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 110, beta = 0.010000, Train MSE: 0.434806, Train CE:0.899996, Train KL:7.688620, Val MSE:0.445392, Val CE:0.885578, Train ACC:0.753209, Val ACC:0.752604

Epoch 112/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 111, beta = 0.010000, Train MSE: 0.423847, Train CE:0.893423, Train KL:7.699591, Val MSE:0.435514, Val CE:0.881094, Train ACC:0.754037, Val ACC:0.754167

Epoch 113/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 112, beta = 0.010000, Train MSE: 0.414779, Train CE:0.888922, Train KL:7.709611, Val MSE:0.424160, Val CE:0.876827, Train ACC:0.754658, Val ACC:0.756771

Epoch 114/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 113, beta = 0.010000, Train MSE: 0.404693, Train CE:0.883651, Train KL:7.716996, Val MSE:0.415201, Val CE:0.871207, Train ACC:0.756315, Val ACC:0.757813

Epoch 115/4000: 100%|██████████| 1/1 [00:00<00:00, 23.56it/s]

epoch: 114, beta = 0.010000, Train MSE: 0.395959, Train CE:0.877730, Train KL:7.724174, Val MSE:0.407170, Val CE:0.866346, Train ACC:0.756936, Val ACC:0.759896

Epoch 116/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 115, beta = 0.010000, Train MSE: 0.386607, Train CE:0.872961, Train KL:7.731805, Val MSE:0.398836, Val CE:0.860996, Train ACC:0.760041, Val ACC:0.761979

Epoch 117/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 116, beta = 0.010000, Train MSE: 0.377885, Train CE:0.866526, Train KL:7.738425, Val MSE:0.391730, Val CE:0.856235, Train ACC:0.762319, Val ACC:0.764063

Epoch 118/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 117, beta = 0.010000, Train MSE: 0.370218, Train CE:0.862663, Train KL:7.746702, Val MSE:0.383102, Val CE:0.850075, Train ACC:0.763561, Val ACC:0.768750

Epoch 119/4000: 100%|██████████| 1/1 [00:00<00:00, 18.87it/s]

epoch: 118, beta = 0.010000, Train MSE: 0.362398, Train CE:0.857036, Train KL:7.759385, Val MSE:0.375817, Val CE:0.845030, Train ACC:0.765839, Val ACC:0.768229

Epoch 120/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 119, beta = 0.010000, Train MSE: 0.354953, Train CE:0.852161, Train KL:7.768289, Val MSE:0.368473, Val CE:0.841107, Train ACC:0.766253, Val ACC:0.769792

Epoch 121/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 120, beta = 0.010000, Train MSE: 0.348665, Train CE:0.846416, Train KL:7.772034, Val MSE:0.361388, Val CE:0.835651, Train ACC:0.768116, Val ACC:0.769271

Epoch 122/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 121, beta = 0.010000, Train MSE: 0.341382, Train CE:0.841978, Train KL:7.774004, Val MSE:0.355257, Val CE:0.831386, Train ACC:0.772671, Val ACC:0.768750

Epoch 123/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 122, beta = 0.010000, Train MSE: 0.335482, Train CE:0.836385, Train KL:7.774532, Val MSE:0.348982, Val CE:0.826017, Train ACC:0.774327, Val ACC:0.773958

Epoch 124/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 123, beta = 0.010000, Train MSE: 0.328956, Train CE:0.832728, Train KL:7.772784, Val MSE:0.342672, Val CE:0.822333, Train ACC:0.775362, Val ACC:0.771875

Epoch 125/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 124, beta = 0.010000, Train MSE: 0.323099, Train CE:0.827406, Train KL:7.772994, Val MSE:0.337529, Val CE:0.816555, Train ACC:0.776190, Val ACC:0.773958

Epoch 126/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 125, beta = 0.010000, Train MSE: 0.317285, Train CE:0.822843, Train KL:7.777431, Val MSE:0.331532, Val CE:0.811703, Train ACC:0.778675, Val ACC:0.772396

Epoch 127/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 126, beta = 0.010000, Train MSE: 0.312130, Train CE:0.817850, Train KL:7.783197, Val MSE:0.326662, Val CE:0.807367, Train ACC:0.779089, Val ACC:0.777083

Epoch 128/4000: 100%|██████████| 1/1 [00:00<00:00, 21.01it/s]

epoch: 127, beta = 0.010000, Train MSE: 0.307045, Train CE:0.813342, Train KL:7.784931, Val MSE:0.321515, Val CE:0.802648, Train ACC:0.780331, Val ACC:0.775000

Epoch 129/4000: 100%|██████████| 1/1 [00:00<00:00, 21.28it/s]

epoch: 128, beta = 0.010000, Train MSE: 0.301829, Train CE:0.808816, Train KL:7.782267, Val MSE:0.316876, Val CE:0.798469, Train ACC:0.781573, Val ACC:0.779167

Epoch 130/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 129, beta = 0.010000, Train MSE: 0.297049, Train CE:0.804374, Train KL:7.779931, Val MSE:0.312051, Val CE:0.792292, Train ACC:0.781781, Val ACC:0.780729

Epoch 131/4000: 100%|██████████| 1/1 [00:00<00:00, 21.84it/s]

epoch: 130, beta = 0.010000, Train MSE: 0.291883, Train CE:0.799320, Train KL:7.778956, Val MSE:0.307383, Val CE:0.787092, Train ACC:0.783437, Val ACC:0.780729

Epoch 132/4000: 100%|██████████| 1/1 [00:00<00:00, 21.28it/s]

epoch: 131, beta = 0.010000, Train MSE: 0.287718, Train CE:0.795485, Train KL:7.776186, Val MSE:0.302100, Val CE:0.783994, Train ACC:0.784472, Val ACC:0.782292

Epoch 133/4000: 100%|██████████| 1/1 [00:00<00:00, 22.74it/s]

epoch: 132, beta = 0.010000, Train MSE: 0.283696, Train CE:0.790305, Train KL:7.774226, Val MSE:0.298937, Val CE:0.779791, Train ACC:0.784265, Val ACC:0.782813

Epoch 134/4000: 100%|██████████| 1/1 [00:00<00:00, 21.59it/s]

epoch: 133, beta = 0.010000, Train MSE: 0.279012, Train CE:0.785934, Train KL:7.771351, Val MSE:0.294125, Val CE:0.776411, Train ACC:0.785714, Val ACC:0.785938

Epoch 135/4000: 100%|██████████| 1/1 [00:00<00:00, 18.77it/s]

epoch: 134, beta = 0.010000, Train MSE: 0.275281, Train CE:0.781977, Train KL:7.769423, Val MSE:0.290969, Val CE:0.772583, Train ACC:0.786957, Val ACC:0.790625

Epoch 136/4000: 100%|██████████| 1/1 [00:00<00:00, 20.91it/s]

epoch: 135, beta = 0.010000, Train MSE: 0.271407, Train CE:0.777983, Train KL:7.765387, Val MSE:0.287429, Val CE:0.769066, Train ACC:0.787992, Val ACC:0.792188

Epoch 137/4000: 100%|██████████| 1/1 [00:00<00:00, 19.11it/s]

epoch: 136, beta = 0.010000, Train MSE: 0.267454, Train CE:0.773258, Train KL:7.759704, Val MSE:0.283870, Val CE:0.763568, Train ACC:0.795031, Val ACC:0.801563

Epoch 138/4000: 100%|██████████| 1/1 [00:00<00:00, 19.35it/s]

epoch: 137, beta = 0.010000, Train MSE: 0.263734, Train CE:0.769240, Train KL:7.752782, Val MSE:0.280282, Val CE:0.759592, Train ACC:0.800621, Val ACC:0.808333

Epoch 139/4000: 100%|██████████| 1/1 [00:00<00:00, 22.37it/s]

epoch: 138, beta = 0.010000, Train MSE: 0.260545, Train CE:0.765637, Train KL:7.747272, Val MSE:0.276675, Val CE:0.756743, Train ACC:0.809524, Val ACC:0.811979

Epoch 140/4000: 100%|██████████| 1/1 [00:00<00:00, 20.97it/s]

epoch: 139, beta = 0.010000, Train MSE: 0.257003, Train CE:0.761630, Train KL:7.741181, Val MSE:0.273030, Val CE:0.752209, Train ACC:0.810766, Val ACC:0.811458

Epoch 141/4000: 100%|██████████| 1/1 [00:00<00:00, 21.16it/s]

epoch: 140, beta = 0.010000, Train MSE: 0.253515, Train CE:0.757007, Train KL:7.737495, Val MSE:0.269700, Val CE:0.748161, Train ACC:0.813458, Val ACC:0.812500

Epoch 142/4000: 100%|██████████| 1/1 [00:00<00:00, 22.15it/s]

epoch: 141, beta = 0.010000, Train MSE: 0.250321, Train CE:0.753305, Train KL:7.735862, Val MSE:0.267089, Val CE:0.743519, Train ACC:0.814079, Val ACC:0.816667

Epoch 143/4000: 100%|██████████| 1/1 [00:00<00:00, 23.25it/s]

epoch: 142, beta = 0.010000, Train MSE: 0.246906, Train CE:0.749602, Train KL:7.732149, Val MSE:0.263409, Val CE:0.739636, Train ACC:0.815735, Val ACC:0.817708

Epoch 144/4000: 100%|██████████| 1/1 [00:00<00:00, 18.47it/s]

epoch: 143, beta = 0.010000, Train MSE: 0.243445, Train CE:0.745058, Train KL:7.724020, Val MSE:0.260273, Val CE:0.734802, Train ACC:0.817391, Val ACC:0.819271

Epoch 145/4000: 100%|██████████| 1/1 [00:00<00:00, 21.68it/s]

epoch: 144, beta = 0.010000, Train MSE: 0.240667, Train CE:0.740973, Train KL:7.714633, Val MSE:0.257226, Val CE:0.732037, Train ACC:0.816977, Val ACC:0.818229

Epoch 146/4000: 100%|██████████| 1/1 [00:00<00:00, 21.33it/s]

epoch: 145, beta = 0.010000, Train MSE: 0.238030, Train CE:0.737097, Train KL:7.705823, Val MSE:0.253511, Val CE:0.728925, Train ACC:0.818841, Val ACC:0.819271

Epoch 147/4000: 100%|██████████| 1/1 [00:00<00:00, 21.65it/s]

epoch: 146, beta = 0.010000, Train MSE: 0.234643, Train CE:0.733562, Train KL:7.697094, Val MSE:0.252222, Val CE:0.725898, Train ACC:0.817598, Val ACC:0.818750

Epoch 148/4000: 100%|██████████| 1/1 [00:00<00:00, 22.29it/s]

epoch: 147, beta = 0.010000, Train MSE: 0.232179, Train CE:0.729482, Train KL:7.688131, Val MSE:0.248770, Val CE:0.721860, Train ACC:0.820497, Val ACC:0.822917

Epoch 149/4000: 100%|██████████| 1/1 [00:00<00:00, 22.02it/s]

epoch: 148, beta = 0.010000, Train MSE: 0.228978, Train CE:0.726282, Train KL:7.682827, Val MSE:0.246371, Val CE:0.718210, Train ACC:0.818841, Val ACC:0.825000

Epoch 150/4000: 100%|██████████| 1/1 [00:00<00:00, 21.90it/s]

epoch: 149, beta = 0.010000, Train MSE: 0.226377, Train CE:0.722251, Train KL:7.676063, Val MSE:0.243363, Val CE:0.715300, Train ACC:0.820911, Val ACC:0.823958

Epoch 151/4000: 100%|██████████| 1/1 [00:00<00:00, 17.01it/s]

epoch: 150, beta = 0.010000, Train MSE: 0.223685, Train CE:0.718958, Train KL:7.666287, Val MSE:0.241302, Val CE:0.711569, Train ACC:0.822774, Val ACC:0.825000

Epoch 152/4000: 100%|██████████| 1/1 [00:00<00:00, 19.55it/s]

epoch: 151, beta = 0.010000, Train MSE: 0.221077, Train CE:0.715235, Train KL:7.653564, Val MSE:0.238600, Val CE:0.708032, Train ACC:0.822153, Val ACC:0.825521

Epoch 153/4000: 100%|██████████| 1/1 [00:00<00:00, 18.51it/s]

epoch: 152, beta = 0.010000, Train MSE: 0.219347, Train CE:0.711191, Train KL:7.643344, Val MSE:0.235237, Val CE:0.704118, Train ACC:0.822774, Val ACC:0.827083

Epoch 154/4000: 100%|██████████| 1/1 [00:00<00:00, 15.74it/s]

epoch: 153, beta = 0.010000, Train MSE: 0.216358, Train CE:0.707663, Train KL:7.637875, Val MSE:0.234115, Val CE:0.700185, Train ACC:0.824017, Val ACC:0.827604

Epoch 155/4000: 100%|██████████| 1/1 [00:00<00:00, 20.43it/s]

epoch: 154, beta = 0.010000, Train MSE: 0.214257, Train CE:0.704053, Train KL:7.632722, Val MSE:0.231212, Val CE:0.696839, Train ACC:0.824224, Val ACC:0.825000

Epoch 156/4000: 100%|██████████| 1/1 [00:00<00:00, 21.41it/s]

epoch: 155, beta = 0.010000, Train MSE: 0.211797, Train CE:0.700313, Train KL:7.627325, Val MSE:0.229191, Val CE:0.693807, Train ACC:0.826294, Val ACC:0.828125

Epoch 157/4000: 100%|██████████| 1/1 [00:00<00:00, 20.25it/s]

epoch: 156, beta = 0.010000, Train MSE: 0.209406, Train CE:0.697771, Train KL:7.622057, Val MSE:0.225790, Val CE:0.690419, Train ACC:0.825880, Val ACC:0.829688

Epoch 158/4000: 100%|██████████| 1/1 [00:00<00:00, 21.06it/s]

epoch: 157, beta = 0.010000, Train MSE: 0.206561, Train CE:0.694137, Train KL:7.614082, Val MSE:0.223861, Val CE:0.690814, Train ACC:0.827122, Val ACC:0.829167

Epoch 159/4000: 100%|██████████| 1/1 [00:00<00:00, 21.75it/s]

epoch: 158, beta = 0.010000, Train MSE: 0.204471, Train CE:0.691360, Train KL:7.601128, Val MSE:0.220872, Val CE:0.688801, Train ACC:0.828364, Val ACC:0.830729

Epoch 160/4000: 100%|██████████| 1/1 [00:00<00:00, 20.70it/s]

epoch: 159, beta = 0.010000, Train MSE: 0.202234, Train CE:0.687738, Train KL:7.592045, Val MSE:0.218446, Val CE:0.684312, Train ACC:0.830021, Val ACC:0.833854

Epoch 161/4000: 100%|██████████| 1/1 [00:00<00:00, 19.74it/s]

epoch: 160, beta = 0.010000, Train MSE: 0.199768, Train CE:0.685013, Train KL:7.587633, Val MSE:0.217470, Val CE:0.679267, Train ACC:0.830021, Val ACC:0.830208

Epoch 162/4000: 100%|██████████| 1/1 [00:00<00:00, 20.29it/s]

epoch: 161, beta = 0.010000, Train MSE: 0.197983, Train CE:0.681424, Train KL:7.580883, Val MSE:0.214568, Val CE:0.675588, Train ACC:0.831470, Val ACC:0.834375

Epoch 163/4000: 100%|██████████| 1/1 [00:00<00:00, 21.28it/s]

epoch: 162, beta = 0.010000, Train MSE: 0.196282, Train CE:0.678015, Train KL:7.573695, Val MSE:0.212534, Val CE:0.672936, Train ACC:0.832298, Val ACC:0.833333

Epoch 164/4000: 100%|██████████| 1/1 [00:00<00:00, 19.23it/s]

epoch: 163, beta = 0.010000, Train MSE: 0.194349, Train CE:0.674982, Train KL:7.565453, Val MSE:0.210930, Val CE:0.669926, Train ACC:0.832505, Val ACC:0.834896

Epoch 165/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 164, beta = 0.010000, Train MSE: 0.192021, Train CE:0.671948, Train KL:7.554929, Val MSE:0.209007, Val CE:0.666365, Train ACC:0.833126, Val ACC:0.835938

Epoch 166/4000: 100%|██████████| 1/1 [00:00<00:00, 21.74it/s]

epoch: 165, beta = 0.010000, Train MSE: 0.190221, Train CE:0.669240, Train KL:7.546107, Val MSE:0.206732, Val CE:0.664485, Train ACC:0.833333, Val ACC:0.835417

Epoch 167/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 166, beta = 0.010000, Train MSE: 0.188003, Train CE:0.665960, Train KL:7.541265, Val MSE:0.204770, Val CE:0.660337, Train ACC:0.834369, Val ACC:0.834896

Epoch 168/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 167, beta = 0.010000, Train MSE: 0.186074, Train CE:0.663190, Train KL:7.535223, Val MSE:0.202559, Val CE:0.658275, Train ACC:0.832712, Val ACC:0.836979

Epoch 169/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 168, beta = 0.010000, Train MSE: 0.184421, Train CE:0.660766, Train KL:7.527431, Val MSE:0.200934, Val CE:0.654985, Train ACC:0.834162, Val ACC:0.834896

Epoch 170/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 169, beta = 0.010000, Train MSE: 0.182826, Train CE:0.657564, Train KL:7.518583, Val MSE:0.199396, Val CE:0.653050, Train ACC:0.834783, Val ACC:0.836458

Epoch 171/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 170, beta = 0.010000, Train MSE: 0.181082, Train CE:0.654140, Train KL:7.512103, Val MSE:0.196667, Val CE:0.652529, Train ACC:0.836853, Val ACC:0.837500

Epoch 172/4000: 100%|██████████| 1/1 [00:00<00:00, 17.54it/s]

epoch: 171, beta = 0.010000, Train MSE: 0.178686, Train CE:0.651996, Train KL:7.506839, Val MSE:0.195587, Val CE:0.650759, Train ACC:0.835404, Val ACC:0.838021

Epoch 173/4000: 100%|██████████| 1/1 [00:00<00:00, 19.61it/s]

epoch: 172, beta = 0.010000, Train MSE: 0.177546, Train CE:0.648689, Train KL:7.499981, Val MSE:0.193336, Val CE:0.646904, Train ACC:0.838302, Val ACC:0.838542

Epoch 174/4000: 100%|██████████| 1/1 [00:00<00:00, 21.00it/s]

epoch: 173, beta = 0.010000, Train MSE: 0.176066, Train CE:0.646327, Train KL:7.495970, Val MSE:0.191097, Val CE:0.644740, Train ACC:0.838095, Val ACC:0.836979

Epoch 175/4000: 100%|██████████| 1/1 [00:00<00:00, 21.74it/s]

epoch: 174, beta = 0.010000, Train MSE: 0.174097, Train CE:0.643173, Train KL:7.490346, Val MSE:0.189591, Val CE:0.641967, Train ACC:0.839545, Val ACC:0.838542

Epoch 176/4000: 100%|██████████| 1/1 [00:00<00:00, 21.74it/s]

epoch: 175, beta = 0.010000, Train MSE: 0.172563, Train CE:0.641027, Train KL:7.480369, Val MSE:0.188718, Val CE:0.637560, Train ACC:0.839959, Val ACC:0.840104

Epoch 177/4000: 100%|██████████| 1/1 [00:00<00:00, 20.83it/s]

epoch: 176, beta = 0.010000, Train MSE: 0.170912, Train CE:0.637989, Train KL:7.475012, Val MSE:0.186762, Val CE:0.639208, Train ACC:0.841201, Val ACC:0.839583

Epoch 178/4000: 100%|██████████| 1/1 [00:00<00:00, 20.83it/s]

epoch: 177, beta = 0.010000, Train MSE: 0.169162, Train CE:0.635242, Train KL:7.467891, Val MSE:0.184276, Val CE:0.636362, Train ACC:0.842236, Val ACC:0.839583

Epoch 179/4000: 100%|██████████| 1/1 [00:00<00:00, 21.28it/s]

epoch: 178, beta = 0.010000, Train MSE: 0.167544, Train CE:0.632872, Train KL:7.462125, Val MSE:0.183344, Val CE:0.633894, Train ACC:0.842443, Val ACC:0.840625

Epoch 180/4000: 100%|██████████| 1/1 [00:00<00:00, 21.74it/s]

epoch: 179, beta = 0.010000, Train MSE: 0.166034, Train CE:0.630477, Train KL:7.452432, Val MSE:0.181072, Val CE:0.631539, Train ACC:0.843478, Val ACC:0.843229

Epoch 181/4000: 100%|██████████| 1/1 [00:00<00:00, 21.74it/s]

epoch: 180, beta = 0.010000, Train MSE: 0.164940, Train CE:0.627895, Train KL:7.447493, Val MSE:0.179892, Val CE:0.628521, Train ACC:0.845963, Val ACC:0.842188

Epoch 182/4000: 100%|██████████| 1/1 [00:00<00:00, 21.06it/s]

epoch: 181, beta = 0.010000, Train MSE: 0.163366, Train CE:0.625340, Train KL:7.446524, Val MSE:0.177893, Val CE:0.626414, Train ACC:0.848654, Val ACC:0.842708

Epoch 183/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 182, beta = 0.010000, Train MSE: 0.161322, Train CE:0.623143, Train KL:7.440881, Val MSE:0.176649, Val CE:0.623775, Train ACC:0.846170, Val ACC:0.842188

Epoch 184/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 183, beta = 0.010000, Train MSE: 0.160395, Train CE:0.620210, Train KL:7.439910, Val MSE:0.175011, Val CE:0.617778, Train ACC:0.849068, Val ACC:0.844792

Epoch 185/4000: 100%|██████████| 1/1 [00:00<00:00, 21.74it/s]

epoch: 184, beta = 0.010000, Train MSE: 0.158500, Train CE:0.618130, Train KL:7.438725, Val MSE:0.173053, Val CE:0.620987, Train ACC:0.848861, Val ACC:0.845313

Epoch 186/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 185, beta = 0.010000, Train MSE: 0.156678, Train CE:0.615627, Train KL:7.426466, Val MSE:0.171369, Val CE:0.617225, Train ACC:0.850311, Val ACC:0.845313

Epoch 187/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 186, beta = 0.010000, Train MSE: 0.155575, Train CE:0.613105, Train KL:7.415466, Val MSE:0.170153, Val CE:0.613538, Train ACC:0.849275, Val ACC:0.846875

Epoch 188/4000: 100%|██████████| 1/1 [00:00<00:00, 20.83it/s]

epoch: 187, beta = 0.010000, Train MSE: 0.154005, Train CE:0.610525, Train KL:7.409923, Val MSE:0.169306, Val CE:0.611001, Train ACC:0.850311, Val ACC:0.849479

Epoch 189/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 188, beta = 0.010000, Train MSE: 0.153037, Train CE:0.608233, Train KL:7.402718, Val MSE:0.168078, Val CE:0.608769, Train ACC:0.851967, Val ACC:0.850521

Epoch 190/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 189, beta = 0.010000, Train MSE: 0.151817, Train CE:0.605636, Train KL:7.396576, Val MSE:0.165977, Val CE:0.608056, Train ACC:0.853209, Val ACC:0.852083

Epoch 191/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 190, beta = 0.010000, Train MSE: 0.149926, Train CE:0.603589, Train KL:7.388758, Val MSE:0.163939, Val CE:0.605996, Train ACC:0.853830, Val ACC:0.853125

Epoch 192/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 191, beta = 0.010000, Train MSE: 0.148699, Train CE:0.601534, Train KL:7.381861, Val MSE:0.162826, Val CE:0.603273, Train ACC:0.855280, Val ACC:0.855208

Epoch 193/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 192, beta = 0.010000, Train MSE: 0.147036, Train CE:0.598884, Train KL:7.381969, Val MSE:0.161944, Val CE:0.601617, Train ACC:0.856108, Val ACC:0.853646

Epoch 194/4000: 100%|██████████| 1/1 [00:00<00:00, 18.18it/s]

epoch: 193, beta = 0.010000, Train MSE: 0.146094, Train CE:0.596689, Train KL:7.377112, Val MSE:0.160228, Val CE:0.598424, Train ACC:0.856729, Val ACC:0.855208

Epoch 195/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 194, beta = 0.010000, Train MSE: 0.144479, Train CE:0.594290, Train KL:7.366357, Val MSE:0.158737, Val CE:0.593648, Train ACC:0.858385, Val ACC:0.858333

Epoch 196/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 195, beta = 0.010000, Train MSE: 0.142762, Train CE:0.592350, Train KL:7.354014, Val MSE:0.157932, Val CE:0.590969, Train ACC:0.856108, Val ACC:0.858854

Epoch 197/4000: 100%|██████████| 1/1 [00:00<00:00, 22.04it/s]

epoch: 196, beta = 0.010000, Train MSE: 0.142005, Train CE:0.589463, Train KL:7.341481, Val MSE:0.156502, Val CE:0.589998, Train ACC:0.860663, Val ACC:0.856771

Epoch 198/4000: 100%|██████████| 1/1 [00:00<00:00, 20.84it/s]

epoch: 197, beta = 0.010000, Train MSE: 0.140751, Train CE:0.587280, Train KL:7.331044, Val MSE:0.155310, Val CE:0.587034, Train ACC:0.859006, Val ACC:0.860417

Epoch 199/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 198, beta = 0.010000, Train MSE: 0.139780, Train CE:0.585308, Train KL:7.323936, Val MSE:0.154003, Val CE:0.584979, Train ACC:0.859420, Val ACC:0.856250

Epoch 200/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 199, beta = 0.010000, Train MSE: 0.138291, Train CE:0.582830, Train KL:7.317417, Val MSE:0.152492, Val CE:0.584498, Train ACC:0.860041, Val ACC:0.860417

Epoch 201/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 200, beta = 0.010000, Train MSE: 0.137294, Train CE:0.581050, Train KL:7.308222, Val MSE:0.150692, Val CE:0.583156, Train ACC:0.860870, Val ACC:0.860938

Epoch 202/4000: 100%|██████████| 1/1 [00:00<00:00, 20.20it/s]

epoch: 201, beta = 0.010000, Train MSE: 0.136129, Train CE:0.578862, Train KL:7.298139, Val MSE:0.150184, Val CE:0.580166, Train ACC:0.861698, Val ACC:0.860417

Epoch 203/4000: 100%|██████████| 1/1 [00:00<00:00, 21.28it/s]

epoch: 202, beta = 0.010000, Train MSE: 0.134740, Train CE:0.576144, Train KL:7.287620, Val MSE:0.149026, Val CE:0.578593, Train ACC:0.861905, Val ACC:0.858333

Epoch 204/4000: 100%|██████████| 1/1 [00:00<00:00, 21.28it/s]

epoch: 203, beta = 0.010000, Train MSE: 0.133878, Train CE:0.574514, Train KL:7.276926, Val MSE:0.147442, Val CE:0.575478, Train ACC:0.863147, Val ACC:0.861979

Epoch 205/4000: 100%|██████████| 1/1 [00:00<00:00, 21.28it/s]

epoch: 204, beta = 0.010000, Train MSE: 0.132742, Train CE:0.572161, Train KL:7.266722, Val MSE:0.146533, Val CE:0.573710, Train ACC:0.861491, Val ACC:0.861458

Epoch 206/4000: 100%|██████████| 1/1 [00:00<00:00, 21.74it/s]

epoch: 205, beta = 0.010000, Train MSE: 0.131527, Train CE:0.570023, Train KL:7.257115, Val MSE:0.145177, Val CE:0.571171, Train ACC:0.863768, Val ACC:0.865104

Epoch 207/4000: 100%|██████████| 1/1 [00:00<00:00, 21.74it/s]

epoch: 206, beta = 0.010000, Train MSE: 0.130538, Train CE:0.567864, Train KL:7.249310, Val MSE:0.144021, Val CE:0.568823, Train ACC:0.863768, Val ACC:0.863021

Epoch 208/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 207, beta = 0.010000, Train MSE: 0.129315, Train CE:0.565691, Train KL:7.241030, Val MSE:0.142974, Val CE:0.566007, Train ACC:0.864803, Val ACC:0.865104

Epoch 209/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 208, beta = 0.010000, Train MSE: 0.127897, Train CE:0.563664, Train KL:7.233866, Val MSE:0.141500, Val CE:0.564547, Train ACC:0.864182, Val ACC:0.864583

Epoch 210/4000: 100%|██████████| 1/1 [00:00<00:00, 21.74it/s]

epoch: 209, beta = 0.010000, Train MSE: 0.127396, Train CE:0.561321, Train KL:7.226305, Val MSE:0.140304, Val CE:0.562002, Train ACC:0.863354, Val ACC:0.862500

Epoch 211/4000: 100%|██████████| 1/1 [00:00<00:00, 21.74it/s]

epoch: 210, beta = 0.010000, Train MSE: 0.125894, Train CE:0.559536, Train KL:7.220062, Val MSE:0.139778, Val CE:0.560460, Train ACC:0.865424, Val ACC:0.863021

Epoch 212/4000: 100%|██████████| 1/1 [00:00<00:00, 20.00it/s]

epoch: 211, beta = 0.010000, Train MSE: 0.125100, Train CE:0.557303, Train KL:7.210271, Val MSE:0.138844, Val CE:0.559992, Train ACC:0.865839, Val ACC:0.864583

Epoch 213/4000: 100%|██████████| 1/1 [00:00<00:00, 21.74it/s]

epoch: 212, beta = 0.010000, Train MSE: 0.124250, Train CE:0.555607, Train KL:7.196899, Val MSE:0.136489, Val CE:0.557816, Train ACC:0.864803, Val ACC:0.864063

Epoch 214/4000: 100%|██████████| 1/1 [00:00<00:00, 20.00it/s]

epoch: 213, beta = 0.010000, Train MSE: 0.123094, Train CE:0.553610, Train KL:7.190730, Val MSE:0.135922, Val CE:0.554790, Train ACC:0.867495, Val ACC:0.868750

Epoch 215/4000: 100%|██████████| 1/1 [00:00<00:00, 20.41it/s]

epoch: 214, beta = 0.010000, Train MSE: 0.121753, Train CE:0.551683, Train KL:7.182223, Val MSE:0.135174, Val CE:0.554140, Train ACC:0.868116, Val ACC:0.867188

Epoch 216/4000: 100%|██████████| 1/1 [00:00<00:00, 21.74it/s]

epoch: 215, beta = 0.010000, Train MSE: 0.121127, Train CE:0.549706, Train KL:7.171598, Val MSE:0.133808, Val CE:0.551430, Train ACC:0.868530, Val ACC:0.867188

Epoch 217/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 216, beta = 0.010000, Train MSE: 0.120028, Train CE:0.547153, Train KL:7.168993, Val MSE:0.132890, Val CE:0.548897, Train ACC:0.867288, Val ACC:0.867188

Epoch 218/4000: 100%|██████████| 1/1 [00:00<00:00, 22.70it/s]

epoch: 217, beta = 0.010000, Train MSE: 0.119220, Train CE:0.545349, Train KL:7.160036, Val MSE:0.132106, Val CE:0.548221, Train ACC:0.869565, Val ACC:0.869271

Epoch 219/4000: 100%|██████████| 1/1 [00:00<00:00, 23.81it/s]

epoch: 218, beta = 0.010000, Train MSE: 0.118256, Train CE:0.543532, Train KL:7.150030, Val MSE:0.131420, Val CE:0.546358, Train ACC:0.869979, Val ACC:0.868750

Epoch 220/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 219, beta = 0.010000, Train MSE: 0.117056, Train CE:0.541388, Train KL:7.147757, Val MSE:0.130032, Val CE:0.545220, Train ACC:0.871222, Val ACC:0.869792

Epoch 221/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 220, beta = 0.010000, Train MSE: 0.116112, Train CE:0.539781, Train KL:7.138243, Val MSE:0.129203, Val CE:0.543102, Train ACC:0.868530, Val ACC:0.868229

Epoch 222/4000: 100%|██████████| 1/1 [00:00<00:00, 23.81it/s]

epoch: 221, beta = 0.010000, Train MSE: 0.115237, Train CE:0.537791, Train KL:7.129818, Val MSE:0.128543, Val CE:0.541010, Train ACC:0.869979, Val ACC:0.869271

Epoch 223/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 222, beta = 0.010000, Train MSE: 0.114111, Train CE:0.535655, Train KL:7.124614, Val MSE:0.126894, Val CE:0.539865, Train ACC:0.869979, Val ACC:0.871875

Epoch 224/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 223, beta = 0.010000, Train MSE: 0.113413, Train CE:0.534056, Train KL:7.114482, Val MSE:0.125649, Val CE:0.538140, Train ACC:0.870186, Val ACC:0.870833

Epoch 225/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 224, beta = 0.010000, Train MSE: 0.112319, Train CE:0.531753, Train KL:7.107806, Val MSE:0.125154, Val CE:0.535663, Train ACC:0.872671, Val ACC:0.870313

Epoch 226/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 225, beta = 0.010000, Train MSE: 0.111514, Train CE:0.530114, Train KL:7.102425, Val MSE:0.124120, Val CE:0.533722, Train ACC:0.873913, Val ACC:0.871354

Epoch 227/4000: 100%|██████████| 1/1 [00:00<00:00, 20.83it/s]

epoch: 226, beta = 0.010000, Train MSE: 0.110428, Train CE:0.527998, Train KL:7.096377, Val MSE:0.122789, Val CE:0.531505, Train ACC:0.872257, Val ACC:0.871875

Epoch 228/4000: 100%|██████████| 1/1 [00:00<00:00, 20.41it/s]

epoch: 227, beta = 0.010000, Train MSE: 0.109831, Train CE:0.526347, Train KL:7.088343, Val MSE:0.122011, Val CE:0.529734, Train ACC:0.874120, Val ACC:0.871354

Epoch 229/4000: 100%|██████████| 1/1 [00:00<00:00, 21.89it/s]

epoch: 228, beta = 0.010000, Train MSE: 0.108729, Train CE:0.524193, Train KL:7.082868, Val MSE:0.120786, Val CE:0.528420, Train ACC:0.873706, Val ACC:0.873438

Epoch 230/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 229, beta = 0.010000, Train MSE: 0.108186, Train CE:0.522371, Train KL:7.076558, Val MSE:0.120318, Val CE:0.526543, Train ACC:0.875362, Val ACC:0.873958

Epoch 231/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 230, beta = 0.010000, Train MSE: 0.107080, Train CE:0.520549, Train KL:7.072569, Val MSE:0.118699, Val CE:0.525541, Train ACC:0.875569, Val ACC:0.875521

Epoch 232/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 231, beta = 0.010000, Train MSE: 0.106150, Train CE:0.518973, Train KL:7.063597, Val MSE:0.118360, Val CE:0.523325, Train ACC:0.877433, Val ACC:0.873438

Epoch 233/4000: 100%|██████████| 1/1 [00:00<00:00, 23.55it/s]

epoch: 232, beta = 0.010000, Train MSE: 0.105517, Train CE:0.516713, Train KL:7.052157, Val MSE:0.117889, Val CE:0.522096, Train ACC:0.877226, Val ACC:0.874479

Epoch 234/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 233, beta = 0.010000, Train MSE: 0.104471, Train CE:0.515611, Train KL:7.047014, Val MSE:0.117003, Val CE:0.520162, Train ACC:0.877640, Val ACC:0.876042

Epoch 235/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 234, beta = 0.010000, Train MSE: 0.104020, Train CE:0.512951, Train KL:7.038302, Val MSE:0.116153, Val CE:0.518615, Train ACC:0.876812, Val ACC:0.875000

Epoch 236/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 235, beta = 0.010000, Train MSE: 0.103110, Train CE:0.511563, Train KL:7.030232, Val MSE:0.115172, Val CE:0.517349, Train ACC:0.877640, Val ACC:0.878646

Epoch 237/4000: 100%|██████████| 1/1 [00:00<00:00, 22.95it/s]

epoch: 236, beta = 0.010000, Train MSE: 0.102176, Train CE:0.509843, Train KL:7.025014, Val MSE:0.114828, Val CE:0.515233, Train ACC:0.879710, Val ACC:0.876042

Epoch 238/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 237, beta = 0.010000, Train MSE: 0.101387, Train CE:0.508072, Train KL:7.018894, Val MSE:0.113486, Val CE:0.514269, Train ACC:0.880538, Val ACC:0.876563

Epoch 239/4000: 100%|██████████| 1/1 [00:00<00:00, 23.81it/s]

epoch: 238, beta = 0.010000, Train MSE: 0.100772, Train CE:0.506294, Train KL:7.012145, Val MSE:0.112428, Val CE:0.512858, Train ACC:0.879296, Val ACC:0.876042

Epoch 240/4000: 100%|██████████| 1/1 [00:00<00:00, 22.89it/s]

epoch: 239, beta = 0.010000, Train MSE: 0.100079, Train CE:0.504662, Train KL:7.002728, Val MSE:0.112154, Val CE:0.510512, Train ACC:0.881366, Val ACC:0.878646

Epoch 241/4000: 100%|██████████| 1/1 [00:00<00:00, 24.63it/s]

epoch: 240, beta = 0.010000, Train MSE: 0.099380, Train CE:0.502600, Train KL:6.993210, Val MSE:0.111421, Val CE:0.509574, Train ACC:0.879089, Val ACC:0.876042

Epoch 242/4000: 100%|██████████| 1/1 [00:00<00:00, 23.43it/s]

epoch: 241, beta = 0.010000, Train MSE: 0.098446, Train CE:0.500823, Train KL:6.986143, Val MSE:0.110521, Val CE:0.507563, Train ACC:0.880952, Val ACC:0.880729

Epoch 243/4000: 100%|██████████| 1/1 [00:00<00:00, 23.03it/s]

epoch: 242, beta = 0.010000, Train MSE: 0.097831, Train CE:0.499440, Train KL:6.979605, Val MSE:0.109256, Val CE:0.506637, Train ACC:0.881988, Val ACC:0.879688

Epoch 244/4000: 100%|██████████| 1/1 [00:00<00:00, 19.69it/s]

epoch: 243, beta = 0.010000, Train MSE: 0.097064, Train CE:0.497239, Train KL:6.973743, Val MSE:0.109519, Val CE:0.504636, Train ACC:0.882816, Val ACC:0.876563

Epoch 245/4000: 100%|██████████| 1/1 [00:00<00:00, 21.53it/s]

epoch: 244, beta = 0.010000, Train MSE: 0.096217, Train CE:0.495852, Train KL:6.966866, Val MSE:0.108925, Val CE:0.502551, Train ACC:0.883230, Val ACC:0.878646

Epoch 246/4000: 100%|██████████| 1/1 [00:00<00:00, 23.38it/s]

epoch: 245, beta = 0.010000, Train MSE: 0.095668, Train CE:0.494220, Train KL:6.959517, Val MSE:0.107762, Val CE:0.500711, Train ACC:0.882402, Val ACC:0.880729

Epoch 247/4000: 100%|██████████| 1/1 [00:00<00:00, 21.02it/s]

epoch: 246, beta = 0.010000, Train MSE: 0.095000, Train CE:0.492605, Train KL:6.951916, Val MSE:0.107356, Val CE:0.499344, Train ACC:0.883437, Val ACC:0.879167

Epoch 248/4000: 100%|██████████| 1/1 [00:00<00:00, 25.44it/s]

epoch: 247, beta = 0.010000, Train MSE: 0.094579, Train CE:0.490535, Train KL:6.941644, Val MSE:0.106539, Val CE:0.498087, Train ACC:0.883437, Val ACC:0.880208

Epoch 249/4000: 100%|██████████| 1/1 [00:00<00:00, 19.31it/s]

epoch: 248, beta = 0.010000, Train MSE: 0.093553, Train CE:0.488960, Train KL:6.935923, Val MSE:0.106115, Val CE:0.496391, Train ACC:0.882402, Val ACC:0.879688

Epoch 250/4000: 100%|██████████| 1/1 [00:00<00:00, 22.01it/s]

epoch: 249, beta = 0.010000, Train MSE: 0.093240, Train CE:0.487241, Train KL:6.924073, Val MSE:0.105448, Val CE:0.494593, Train ACC:0.883851, Val ACC:0.879167

Epoch 251/4000: 100%|██████████| 1/1 [00:00<00:00, 18.05it/s]

epoch: 250, beta = 0.010000, Train MSE: 0.092977, Train CE:0.485447, Train KL:6.913701, Val MSE:0.104805, Val CE:0.493244, Train ACC:0.883644, Val ACC:0.882292

Epoch 252/4000: 100%|██████████| 1/1 [00:00<00:00, 20.77it/s]

epoch: 251, beta = 0.010000, Train MSE: 0.091917, Train CE:0.484083, Train KL:6.908172, Val MSE:0.104677, Val CE:0.492177, Train ACC:0.885714, Val ACC:0.882292

Epoch 253/4000: 100%|██████████| 1/1 [00:00<00:00, 23.79it/s]

epoch: 252, beta = 0.010000, Train MSE: 0.091425, Train CE:0.481971, Train KL:6.902058, Val MSE:0.102995, Val CE:0.491003, Train ACC:0.885507, Val ACC:0.880729

Epoch 254/4000: 100%|██████████| 1/1 [00:00<00:00, 22.19it/s]

epoch: 253, beta = 0.010000, Train MSE: 0.090327, Train CE:0.481363, Train KL:6.898534, Val MSE:0.103081, Val CE:0.488360, Train ACC:0.885507, Val ACC:0.883333

Epoch 255/4000: 100%|██████████| 1/1 [00:00<00:00, 22.68it/s]

epoch: 254, beta = 0.010000, Train MSE: 0.089920, Train CE:0.479518, Train KL:6.887591, Val MSE:0.102330, Val CE:0.487023, Train ACC:0.888199, Val ACC:0.882813

Epoch 256/4000: 100%|██████████| 1/1 [00:00<00:00, 25.43it/s]

epoch: 255, beta = 0.010000, Train MSE: 0.089669, Train CE:0.477645, Train KL:6.882790, Val MSE:0.101505, Val CE:0.486505, Train ACC:0.888406, Val ACC:0.883854

Epoch 257/4000: 100%|██████████| 1/1 [00:00<00:00, 22.86it/s]

epoch: 256, beta = 0.010000, Train MSE: 0.088920, Train CE:0.476085, Train KL:6.880706, Val MSE:0.100778, Val CE:0.482932, Train ACC:0.887992, Val ACC:0.885417

Epoch 258/4000: 100%|██████████| 1/1 [00:00<00:00, 23.35it/s]

epoch: 257, beta = 0.010000, Train MSE: 0.088830, Train CE:0.474186, Train KL:6.868434, Val MSE:0.100722, Val CE:0.482470, Train ACC:0.888613, Val ACC:0.883854

Epoch 259/4000: 100%|██████████| 1/1 [00:00<00:00, 25.03it/s]

epoch: 258, beta = 0.010000, Train MSE: 0.087888, Train CE:0.472837, Train KL:6.865813, Val MSE:0.100437, Val CE:0.480701, Train ACC:0.890062, Val ACC:0.883854

Epoch 260/4000: 100%|██████████| 1/1 [00:00<00:00, 26.55it/s]

epoch: 259, beta = 0.010000, Train MSE: 0.087400, Train CE:0.470751, Train KL:6.863454, Val MSE:0.099278, Val CE:0.478453, Train ACC:0.890062, Val ACC:0.884896

Epoch 261/4000: 100%|██████████| 1/1 [00:00<00:00, 26.75it/s]

epoch: 260, beta = 0.010000, Train MSE: 0.086708, Train CE:0.469408, Train KL:6.855353, Val MSE:0.098372, Val CE:0.477834, Train ACC:0.890269, Val ACC:0.884896

Epoch 262/4000: 100%|██████████| 1/1 [00:00<00:00, 19.29it/s]

epoch: 261, beta = 0.010000, Train MSE: 0.086215, Train CE:0.467702, Train KL:6.850797, Val MSE:0.097959, Val CE:0.475832, Train ACC:0.890476, Val ACC:0.885417

Epoch 263/4000: 100%|██████████| 1/1 [00:00<00:00, 21.93it/s]

epoch: 262, beta = 0.010000, Train MSE: 0.085500, Train CE:0.466534, Train KL:6.845318, Val MSE:0.097556, Val CE:0.473982, Train ACC:0.891097, Val ACC:0.886979

Epoch 264/4000: 100%|██████████| 1/1 [00:00<00:00, 27.07it/s]

epoch: 263, beta = 0.010000, Train MSE: 0.085094, Train CE:0.464964, Train KL:6.837085, Val MSE:0.096836, Val CE:0.472248, Train ACC:0.893375, Val ACC:0.886458

Epoch 265/4000: 100%|██████████| 1/1 [00:00<00:00, 23.29it/s]

epoch: 264, beta = 0.010000, Train MSE: 0.084100, Train CE:0.463537, Train KL:6.833738, Val MSE:0.095945, Val CE:0.470795, Train ACC:0.891925, Val ACC:0.884375

Epoch 266/4000: 100%|██████████| 1/1 [00:00<00:00, 20.66it/s]

epoch: 265, beta = 0.010000, Train MSE: 0.083931, Train CE:0.461887, Train KL:6.824339, Val MSE:0.095163, Val CE:0.469182, Train ACC:0.892340, Val ACC:0.887500

Epoch 267/4000: 100%|██████████| 1/1 [00:00<00:00, 21.51it/s]

epoch: 266, beta = 0.010000, Train MSE: 0.083419, Train CE:0.460036, Train KL:6.813721, Val MSE:0.095252, Val CE:0.467468, Train ACC:0.893168, Val ACC:0.884896

Epoch 268/4000: 100%|██████████| 1/1 [00:00<00:00, 27.48it/s]

epoch: 267, beta = 0.010000, Train MSE: 0.082668, Train CE:0.458677, Train KL:6.807943, Val MSE:0.094582, Val CE:0.466356, Train ACC:0.893375, Val ACC:0.886458

Epoch 269/4000: 100%|██████████| 1/1 [00:00<00:00, 21.85it/s]

epoch: 268, beta = 0.010000, Train MSE: 0.082121, Train CE:0.456815, Train KL:6.802082, Val MSE:0.093742, Val CE:0.464350, Train ACC:0.893582, Val ACC:0.885938

Epoch 270/4000: 100%|██████████| 1/1 [00:00<00:00, 20.60it/s]

epoch: 269, beta = 0.010000, Train MSE: 0.081842, Train CE:0.455339, Train KL:6.800142, Val MSE:0.093421, Val CE:0.463337, Train ACC:0.893996, Val ACC:0.886458

Epoch 271/4000: 100%|██████████| 1/1 [00:00<00:00, 19.92it/s]

epoch: 270, beta = 0.010000, Train MSE: 0.081151, Train CE:0.454025, Train KL:6.793132, Val MSE:0.092493, Val CE:0.461398, Train ACC:0.894824, Val ACC:0.886979

Epoch 272/4000: 100%|██████████| 1/1 [00:00<00:00, 18.54it/s]

epoch: 271, beta = 0.010000, Train MSE: 0.080963, Train CE:0.452368, Train KL:6.781507, Val MSE:0.092146, Val CE:0.461254, Train ACC:0.894824, Val ACC:0.886458

Epoch 273/4000: 100%|██████████| 1/1 [00:00<00:00, 20.76it/s]

epoch: 272, beta = 0.010000, Train MSE: 0.080387, Train CE:0.451015, Train KL:6.774943, Val MSE:0.091685, Val CE:0.459619, Train ACC:0.895031, Val ACC:0.884896

Epoch 274/4000: 100%|██████████| 1/1 [00:00<00:00, 24.60it/s]

epoch: 273, beta = 0.010000, Train MSE: 0.079588, Train CE:0.449174, Train KL:6.768786, Val MSE:0.091179, Val CE:0.457454, Train ACC:0.896480, Val ACC:0.886979

Epoch 275/4000: 100%|██████████| 1/1 [00:00<00:00, 20.32it/s]

epoch: 274, beta = 0.010000, Train MSE: 0.079650, Train CE:0.447744, Train KL:6.761711, Val MSE:0.090633, Val CE:0.456667, Train ACC:0.895031, Val ACC:0.885417

Epoch 276/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 275, beta = 0.010000, Train MSE: 0.078437, Train CE:0.446422, Train KL:6.758877, Val MSE:0.090171, Val CE:0.454505, Train ACC:0.895859, Val ACC:0.887500

Epoch 277/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 276, beta = 0.010000, Train MSE: 0.078267, Train CE:0.444601, Train KL:6.750936, Val MSE:0.089654, Val CE:0.453183, Train ACC:0.897308, Val ACC:0.887500

Epoch 278/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 277, beta = 0.010000, Train MSE: 0.077583, Train CE:0.443371, Train KL:6.743671, Val MSE:0.088874, Val CE:0.451896, Train ACC:0.897101, Val ACC:0.885938

Epoch 279/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 278, beta = 0.010000, Train MSE: 0.077005, Train CE:0.441948, Train KL:6.737027, Val MSE:0.088888, Val CE:0.449684, Train ACC:0.897930, Val ACC:0.888021

Epoch 280/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 279, beta = 0.010000, Train MSE: 0.077147, Train CE:0.440551, Train KL:6.726469, Val MSE:0.088500, Val CE:0.449344, Train ACC:0.898551, Val ACC:0.889063

Epoch 281/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 280, beta = 0.010000, Train MSE: 0.076266, Train CE:0.439058, Train KL:6.720902, Val MSE:0.087745, Val CE:0.446949, Train ACC:0.898758, Val ACC:0.891667

Epoch 282/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 281, beta = 0.010000, Train MSE: 0.075445, Train CE:0.437345, Train KL:6.712943, Val MSE:0.086975, Val CE:0.446382, Train ACC:0.898965, Val ACC:0.890104

Epoch 283/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 282, beta = 0.010000, Train MSE: 0.075384, Train CE:0.435940, Train KL:6.710299, Val MSE:0.086360, Val CE:0.444388, Train ACC:0.899379, Val ACC:0.889063

Epoch 284/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 283, beta = 0.010000, Train MSE: 0.074690, Train CE:0.434977, Train KL:6.705986, Val MSE:0.085853, Val CE:0.442750, Train ACC:0.899586, Val ACC:0.891667

Epoch 285/4000: 100%|██████████| 1/1 [00:00<00:00, 23.06it/s]

epoch: 284, beta = 0.010000, Train MSE: 0.074363, Train CE:0.432961, Train KL:6.698795, Val MSE:0.085628, Val CE:0.442445, Train ACC:0.900621, Val ACC:0.890104

Epoch 286/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 285, beta = 0.010000, Train MSE: 0.073790, Train CE:0.432137, Train KL:6.693604, Val MSE:0.085075, Val CE:0.440948, Train ACC:0.901242, Val ACC:0.893229

Epoch 287/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 286, beta = 0.010000, Train MSE: 0.073273, Train CE:0.430091, Train KL:6.687106, Val MSE:0.084848, Val CE:0.440059, Train ACC:0.901863, Val ACC:0.890625

Epoch 288/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 287, beta = 0.010000, Train MSE: 0.073058, Train CE:0.428951, Train KL:6.681387, Val MSE:0.084349, Val CE:0.438949, Train ACC:0.899379, Val ACC:0.891667

Epoch 289/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 288, beta = 0.010000, Train MSE: 0.072628, Train CE:0.427543, Train KL:6.676635, Val MSE:0.084090, Val CE:0.437355, Train ACC:0.902484, Val ACC:0.891146

Epoch 290/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 289, beta = 0.010000, Train MSE: 0.072232, Train CE:0.425938, Train KL:6.670606, Val MSE:0.082902, Val CE:0.435965, Train ACC:0.902899, Val ACC:0.892708

Epoch 291/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 290, beta = 0.010000, Train MSE: 0.071579, Train CE:0.424655, Train KL:6.671011, Val MSE:0.082575, Val CE:0.434901, Train ACC:0.903313, Val ACC:0.892188

Epoch 292/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 291, beta = 0.010000, Train MSE: 0.071308, Train CE:0.423222, Train KL:6.666693, Val MSE:0.082256, Val CE:0.434475, Train ACC:0.903313, Val ACC:0.893750

Epoch 293/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 292, beta = 0.010000, Train MSE: 0.070865, Train CE:0.421474, Train KL:6.660684, Val MSE:0.081774, Val CE:0.432072, Train ACC:0.904348, Val ACC:0.895833

Epoch 294/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 293, beta = 0.010000, Train MSE: 0.070696, Train CE:0.420315, Train KL:6.654789, Val MSE:0.081519, Val CE:0.429647, Train ACC:0.904141, Val ACC:0.895313

Epoch 295/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 294, beta = 0.010000, Train MSE: 0.070138, Train CE:0.418923, Train KL:6.651070, Val MSE:0.080832, Val CE:0.429245, Train ACC:0.906211, Val ACC:0.897917

Epoch 296/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 295, beta = 0.010000, Train MSE: 0.069395, Train CE:0.417509, Train KL:6.651680, Val MSE:0.080619, Val CE:0.426563, Train ACC:0.906211, Val ACC:0.897396

Epoch 297/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 296, beta = 0.010000, Train MSE: 0.068961, Train CE:0.416266, Train KL:6.646101, Val MSE:0.079928, Val CE:0.426227, Train ACC:0.906418, Val ACC:0.896875

Epoch 298/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 297, beta = 0.010000, Train MSE: 0.068842, Train CE:0.415130, Train KL:6.638945, Val MSE:0.079957, Val CE:0.425125, Train ACC:0.906832, Val ACC:0.898438

Epoch 299/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 298, beta = 0.010000, Train MSE: 0.068586, Train CE:0.413358, Train KL:6.630855, Val MSE:0.079248, Val CE:0.424425, Train ACC:0.907453, Val ACC:0.901563

Epoch 300/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 299, beta = 0.010000, Train MSE: 0.068033, Train CE:0.412252, Train KL:6.627346, Val MSE:0.079298, Val CE:0.423007, Train ACC:0.908075, Val ACC:0.898958

Epoch 301/4000: 100%|██████████| 1/1 [00:00<00:00, 23.81it/s]

epoch: 300, beta = 0.010000, Train MSE: 0.067768, Train CE:0.410678, Train KL:6.626269, Val MSE:0.078461, Val CE:0.422170, Train ACC:0.908075, Val ACC:0.897917

Epoch 302/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 301, beta = 0.010000, Train MSE: 0.067279, Train CE:0.409426, Train KL:6.627442, Val MSE:0.078215, Val CE:0.419644, Train ACC:0.907039, Val ACC:0.901563

Epoch 303/4000: 100%|██████████| 1/1 [00:00<00:00, 23.81it/s]

epoch: 302, beta = 0.010000, Train MSE: 0.066704, Train CE:0.408173, Train KL:6.621345, Val MSE:0.077362, Val CE:0.419560, Train ACC:0.908282, Val ACC:0.903125

Epoch 304/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 303, beta = 0.010000, Train MSE: 0.066461, Train CE:0.406520, Train KL:6.618497, Val MSE:0.077488, Val CE:0.416820, Train ACC:0.909110, Val ACC:0.903646

Epoch 305/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 304, beta = 0.010000, Train MSE: 0.066480, Train CE:0.405158, Train KL:6.611570, Val MSE:0.076468, Val CE:0.416276, Train ACC:0.910145, Val ACC:0.904688

Epoch 306/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 305, beta = 0.010000, Train MSE: 0.065670, Train CE:0.403669, Train KL:6.610964, Val MSE:0.075860, Val CE:0.415653, Train ACC:0.910352, Val ACC:0.904167

Epoch 307/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 306, beta = 0.010000, Train MSE: 0.065547, Train CE:0.402518, Train KL:6.606862, Val MSE:0.076361, Val CE:0.414304, Train ACC:0.911594, Val ACC:0.903646

Epoch 308/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 307, beta = 0.010000, Train MSE: 0.065000, Train CE:0.401083, Train KL:6.598471, Val MSE:0.075255, Val CE:0.413361, Train ACC:0.911387, Val ACC:0.905729

Epoch 309/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 308, beta = 0.010000, Train MSE: 0.064575, Train CE:0.399992, Train KL:6.595246, Val MSE:0.074793, Val CE:0.412032, Train ACC:0.910766, Val ACC:0.906250

Epoch 310/4000: 100%|██████████| 1/1 [00:00<00:00, 20.41it/s]

epoch: 309, beta = 0.010000, Train MSE: 0.064323, Train CE:0.398747, Train KL:6.588014, Val MSE:0.074509, Val CE:0.410394, Train ACC:0.910766, Val ACC:0.908333

Epoch 311/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 310, beta = 0.010000, Train MSE: 0.063941, Train CE:0.397412, Train KL:6.581286, Val MSE:0.074099, Val CE:0.410306, Train ACC:0.913458, Val ACC:0.907292

Epoch 312/4000: 100%|██████████| 1/1 [00:00<00:00, 21.74it/s]

epoch: 311, beta = 0.010000, Train MSE: 0.063601, Train CE:0.396237, Train KL:6.580629, Val MSE:0.074401, Val CE:0.406850, Train ACC:0.913251, Val ACC:0.907813

Epoch 313/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 312, beta = 0.010000, Train MSE: 0.063984, Train CE:0.394827, Train KL:6.573509, Val MSE:0.073703, Val CE:0.408104, Train ACC:0.913043, Val ACC:0.906771

Epoch 314/4000: 100%|██████████| 1/1 [00:00<00:00, 21.88it/s]

epoch: 313, beta = 0.010000, Train MSE: 0.063369, Train CE:0.393667, Train KL:6.571641, Val MSE:0.073273, Val CE:0.405011, Train ACC:0.913665, Val ACC:0.906771

Epoch 315/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 314, beta = 0.010000, Train MSE: 0.063056, Train CE:0.392309, Train KL:6.564332, Val MSE:0.072675, Val CE:0.404125, Train ACC:0.914907, Val ACC:0.907813

Epoch 316/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 315, beta = 0.010000, Train MSE: 0.062194, Train CE:0.390953, Train KL:6.561032, Val MSE:0.072443, Val CE:0.404099, Train ACC:0.914493, Val ACC:0.907292

Epoch 317/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 316, beta = 0.010000, Train MSE: 0.061979, Train CE:0.389516, Train KL:6.554113, Val MSE:0.072088, Val CE:0.402078, Train ACC:0.914079, Val ACC:0.909896

Epoch 318/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 317, beta = 0.010000, Train MSE: 0.061940, Train CE:0.388412, Train KL:6.548173, Val MSE:0.071285, Val CE:0.402387, Train ACC:0.914700, Val ACC:0.910938

Epoch 319/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 318, beta = 0.010000, Train MSE: 0.061276, Train CE:0.387411, Train KL:6.548901, Val MSE:0.071106, Val CE:0.399033, Train ACC:0.914286, Val ACC:0.908854

Epoch 320/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 319, beta = 0.010000, Train MSE: 0.061058, Train CE:0.385774, Train KL:6.542903, Val MSE:0.070375, Val CE:0.398993, Train ACC:0.914079, Val ACC:0.910417

Epoch 321/4000: 100%|██████████| 1/1 [00:00<00:00, 23.27it/s]

epoch: 320, beta = 0.010000, Train MSE: 0.060433, Train CE:0.385030, Train KL:6.541830, Val MSE:0.070076, Val CE:0.398358, Train ACC:0.916356, Val ACC:0.909896

Epoch 322/4000: 100%|██████████| 1/1 [00:00<00:00, 23.81it/s]

epoch: 321, beta = 0.010000, Train MSE: 0.060119, Train CE:0.383270, Train KL:6.538770, Val MSE:0.069764, Val CE:0.396236, Train ACC:0.914700, Val ACC:0.911458

Epoch 323/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 322, beta = 0.010000, Train MSE: 0.060163, Train CE:0.381912, Train KL:6.530612, Val MSE:0.069712, Val CE:0.397162, Train ACC:0.915528, Val ACC:0.910417

Epoch 324/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 323, beta = 0.010000, Train MSE: 0.059675, Train CE:0.381104, Train KL:6.527451, Val MSE:0.070380, Val CE:0.394594, Train ACC:0.916563, Val ACC:0.912500

Epoch 325/4000: 100%|██████████| 1/1 [00:00<00:00, 22.31it/s]

epoch: 324, beta = 0.010000, Train MSE: 0.059583, Train CE:0.379565, Train KL:6.523066, Val MSE:0.068625, Val CE:0.395253, Train ACC:0.915528, Val ACC:0.910417

Epoch 326/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 325, beta = 0.010000, Train MSE: 0.059196, Train CE:0.379266, Train KL:6.527421, Val MSE:0.069215, Val CE:0.391905, Train ACC:0.915321, Val ACC:0.906771

Epoch 327/4000: 100%|██████████| 1/1 [00:00<00:00, 21.74it/s]

epoch: 326, beta = 0.010000, Train MSE: 0.059080, Train CE:0.377250, Train KL:6.513275, Val MSE:0.068328, Val CE:0.390688, Train ACC:0.916356, Val ACC:0.912500

Epoch 328/4000: 100%|██████████| 1/1 [00:00<00:00, 21.74it/s]

epoch: 327, beta = 0.010000, Train MSE: 0.058252, Train CE:0.376076, Train KL:6.506836, Val MSE:0.068120, Val CE:0.390503, Train ACC:0.915942, Val ACC:0.911979

Epoch 329/4000: 100%|██████████| 1/1 [00:00<00:00, 17.54it/s]

epoch: 328, beta = 0.010000, Train MSE: 0.058362, Train CE:0.374868, Train KL:6.506792, Val MSE:0.068786, Val CE:0.387929, Train ACC:0.916563, Val ACC:0.913021

Epoch 330/4000: 100%|██████████| 1/1 [00:00<00:00, 18.52it/s]

epoch: 329, beta = 0.010000, Train MSE: 0.058652, Train CE:0.373405, Train KL:6.500865, Val MSE:0.067507, Val CE:0.389255, Train ACC:0.916563, Val ACC:0.912500

Epoch 331/4000: 100%|██████████| 1/1 [00:00<00:00, 21.28it/s]

epoch: 330, beta = 0.010000, Train MSE: 0.057647, Train CE:0.372619, Train KL:6.497996, Val MSE:0.066912, Val CE:0.386515, Train ACC:0.917391, Val ACC:0.911458

Epoch 332/4000: 100%|██████████| 1/1 [00:00<00:00, 21.74it/s]

epoch: 331, beta = 0.010000, Train MSE: 0.057154, Train CE:0.371137, Train KL:6.488719, Val MSE:0.066723, Val CE:0.384736, Train ACC:0.917391, Val ACC:0.912500

Epoch 333/4000: 100%|██████████| 1/1 [00:00<00:00, 21.74it/s]

epoch: 332, beta = 0.010000, Train MSE: 0.057512, Train CE:0.370005, Train KL:6.486000, Val MSE:0.065759, Val CE:0.387000, Train ACC:0.916149, Val ACC:0.910938

Epoch 334/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 333, beta = 0.010000, Train MSE: 0.056361, Train CE:0.369371, Train KL:6.487204, Val MSE:0.066174, Val CE:0.383714, Train ACC:0.917184, Val ACC:0.915104

Epoch 335/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 334, beta = 0.010000, Train MSE: 0.056338, Train CE:0.367190, Train KL:6.477103, Val MSE:0.066285, Val CE:0.383069, Train ACC:0.918841, Val ACC:0.913021

Epoch 336/4000: 100%|██████████| 1/1 [00:00<00:00, 22.09it/s]

epoch: 335, beta = 0.010000, Train MSE: 0.056351, Train CE:0.366103, Train KL:6.471920, Val MSE:0.065702, Val CE:0.382190, Train ACC:0.917598, Val ACC:0.914583

Epoch 337/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 336, beta = 0.010000, Train MSE: 0.055994, Train CE:0.365512, Train KL:6.472413, Val MSE:0.065697, Val CE:0.380545, Train ACC:0.918219, Val ACC:0.915625

Epoch 338/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 337, beta = 0.010000, Train MSE: 0.056185, Train CE:0.363672, Train KL:6.465289, Val MSE:0.064792, Val CE:0.379970, Train ACC:0.919669, Val ACC:0.917188

Epoch 339/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 338, beta = 0.010000, Train MSE: 0.055238, Train CE:0.362631, Train KL:6.462415, Val MSE:0.064419, Val CE:0.377764, Train ACC:0.919255, Val ACC:0.916667

Epoch 340/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 339, beta = 0.010000, Train MSE: 0.054752, Train CE:0.361420, Train KL:6.456568, Val MSE:0.064014, Val CE:0.376673, Train ACC:0.919255, Val ACC:0.915104

Epoch 341/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 340, beta = 0.010000, Train MSE: 0.054756, Train CE:0.360343, Train KL:6.450407, Val MSE:0.063740, Val CE:0.376931, Train ACC:0.919876, Val ACC:0.917188

Epoch 342/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 341, beta = 0.010000, Train MSE: 0.054476, Train CE:0.359072, Train KL:6.453175, Val MSE:0.063202, Val CE:0.375614, Train ACC:0.919876, Val ACC:0.916146

Epoch 343/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 342, beta = 0.010000, Train MSE: 0.053975, Train CE:0.358015, Train KL:6.448762, Val MSE:0.063265, Val CE:0.374360, Train ACC:0.920290, Val ACC:0.918229

Epoch 344/4000: 100%|██████████| 1/1 [00:00<00:00, 23.81it/s]

epoch: 343, beta = 0.010000, Train MSE: 0.053957, Train CE:0.356728, Train KL:6.443422, Val MSE:0.062316, Val CE:0.375031, Train ACC:0.921532, Val ACC:0.916667

Epoch 345/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 344, beta = 0.010000, Train MSE: 0.053690, Train CE:0.355993, Train KL:6.447787, Val MSE:0.062161, Val CE:0.372428, Train ACC:0.920911, Val ACC:0.918750

Epoch 346/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 345, beta = 0.010000, Train MSE: 0.053548, Train CE:0.354355, Train KL:6.441928, Val MSE:0.062080, Val CE:0.371718, Train ACC:0.919669, Val ACC:0.917708

Epoch 347/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 346, beta = 0.010000, Train MSE: 0.053019, Train CE:0.353278, Train KL:6.435217, Val MSE:0.062155, Val CE:0.370762, Train ACC:0.920083, Val ACC:0.919792

Epoch 348/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 347, beta = 0.010000, Train MSE: 0.052752, Train CE:0.352900, Train KL:6.433132, Val MSE:0.062305, Val CE:0.369321, Train ACC:0.920911, Val ACC:0.917708

Epoch 349/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 348, beta = 0.010000, Train MSE: 0.053033, Train CE:0.350986, Train KL:6.431346, Val MSE:0.061301, Val CE:0.369486, Train ACC:0.921739, Val ACC:0.917188

Epoch 350/4000: 100%|██████████| 1/1 [00:00<00:00, 20.41it/s]

epoch: 349, beta = 0.010000, Train MSE: 0.052410, Train CE:0.350403, Train KL:6.428648, Val MSE:0.061394, Val CE:0.367085, Train ACC:0.921118, Val ACC:0.916146

Epoch 351/4000: 100%|██████████| 1/1 [00:00<00:00, 20.00it/s]

epoch: 350, beta = 0.010000, Train MSE: 0.052044, Train CE:0.348689, Train KL:6.420567, Val MSE:0.060934, Val CE:0.367067, Train ACC:0.922774, Val ACC:0.916667

Epoch 352/4000: 100%|██████████| 1/1 [00:00<00:00, 21.89it/s]

epoch: 351, beta = 0.010000, Train MSE: 0.051969, Train CE:0.348008, Train KL:6.416570, Val MSE:0.060345, Val CE:0.367527, Train ACC:0.923810, Val ACC:0.917188

Epoch 353/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 352, beta = 0.010000, Train MSE: 0.051482, Train CE:0.346944, Train KL:6.420505, Val MSE:0.060574, Val CE:0.365604, Train ACC:0.923188, Val ACC:0.920313

Epoch 354/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 353, beta = 0.010000, Train MSE: 0.051695, Train CE:0.345345, Train KL:6.418758, Val MSE:0.059824, Val CE:0.365745, Train ACC:0.924017, Val ACC:0.917708

Epoch 355/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 354, beta = 0.010000, Train MSE: 0.051192, Train CE:0.344259, Train KL:6.413435, Val MSE:0.059712, Val CE:0.364363, Train ACC:0.924017, Val ACC:0.919792

Epoch 356/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 355, beta = 0.010000, Train MSE: 0.050876, Train CE:0.343090, Train KL:6.411431, Val MSE:0.059178, Val CE:0.363341, Train ACC:0.924017, Val ACC:0.919792

Epoch 357/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 356, beta = 0.010000, Train MSE: 0.050838, Train CE:0.341943, Train KL:6.412095, Val MSE:0.058813, Val CE:0.363605, Train ACC:0.926087, Val ACC:0.919271

Epoch 358/4000: 100%|██████████| 1/1 [00:00<00:00, 31.60it/s]

epoch: 357, beta = 0.010000, Train MSE: 0.050469, Train CE:0.341014, Train KL:6.412873, Val MSE:0.058691, Val CE:0.360654, Train ACC:0.924638, Val ACC:0.920833

Epoch 359/4000: 100%|██████████| 1/1 [00:00<00:00, 23.03it/s]

epoch: 358, beta = 0.010000, Train MSE: 0.050286, Train CE:0.339575, Train KL:6.405963, Val MSE:0.058734, Val CE:0.359215, Train ACC:0.924638, Val ACC:0.920833

Epoch 360/4000: 100%|██████████| 1/1 [00:00<00:00, 20.41it/s]

epoch: 359, beta = 0.010000, Train MSE: 0.049913, Train CE:0.338545, Train KL:6.401588, Val MSE:0.058623, Val CE:0.360679, Train ACC:0.925466, Val ACC:0.921875

Epoch 361/4000: 100%|██████████| 1/1 [00:00<00:00, 21.63it/s]

epoch: 360, beta = 0.010000, Train MSE: 0.049815, Train CE:0.337810, Train KL:6.400264, Val MSE:0.057972, Val CE:0.357052, Train ACC:0.925466, Val ACC:0.922917

Epoch 362/4000: 100%|██████████| 1/1 [00:00<00:00, 21.71it/s]

epoch: 361, beta = 0.010000, Train MSE: 0.049608, Train CE:0.336335, Train KL:6.394511, Val MSE:0.057908, Val CE:0.356883, Train ACC:0.925673, Val ACC:0.921354

Epoch 363/4000: 100%|██████████| 1/1 [00:00<00:00, 21.48it/s]

epoch: 362, beta = 0.010000, Train MSE: 0.049154, Train CE:0.335226, Train KL:6.392274, Val MSE:0.057693, Val CE:0.355815, Train ACC:0.926294, Val ACC:0.922917

Epoch 364/4000: 100%|██████████| 1/1 [00:00<00:00, 20.49it/s]

epoch: 363, beta = 0.010000, Train MSE: 0.048774, Train CE:0.333935, Train KL:6.388340, Val MSE:0.057486, Val CE:0.354705, Train ACC:0.925880, Val ACC:0.921875

Epoch 365/4000: 100%|██████████| 1/1 [00:00<00:00, 22.15it/s]

epoch: 364, beta = 0.010000, Train MSE: 0.049055, Train CE:0.332933, Train KL:6.383245, Val MSE:0.056920, Val CE:0.353922, Train ACC:0.926708, Val ACC:0.920833

Epoch 366/4000: 100%|██████████| 1/1 [00:00<00:00, 21.99it/s]

epoch: 365, beta = 0.010000, Train MSE: 0.048456, Train CE:0.332251, Train KL:6.382690, Val MSE:0.057195, Val CE:0.351957, Train ACC:0.927329, Val ACC:0.922396

Epoch 367/4000: 100%|██████████| 1/1 [00:00<00:00, 22.85it/s]

epoch: 366, beta = 0.010000, Train MSE: 0.048462, Train CE:0.330823, Train KL:6.372819, Val MSE:0.056551, Val CE:0.351351, Train ACC:0.929607, Val ACC:0.924479

Epoch 368/4000: 100%|██████████| 1/1 [00:00<00:00, 22.41it/s]

epoch: 367, beta = 0.010000, Train MSE: 0.048104, Train CE:0.330002, Train KL:6.364039, Val MSE:0.056402, Val CE:0.351661, Train ACC:0.927950, Val ACC:0.922917

Epoch 369/4000: 100%|██████████| 1/1 [00:00<00:00, 20.65it/s]

epoch: 368, beta = 0.010000, Train MSE: 0.048188, Train CE:0.328721, Train KL:6.358977, Val MSE:0.056538, Val CE:0.349880, Train ACC:0.927536, Val ACC:0.923438

Epoch 370/4000: 100%|██████████| 1/1 [00:00<00:00, 20.00it/s]

epoch: 369, beta = 0.010000, Train MSE: 0.048034, Train CE:0.327361, Train KL:6.356047, Val MSE:0.056402, Val CE:0.350273, Train ACC:0.929607, Val ACC:0.922917

Epoch 371/4000: 100%|██████████| 1/1 [00:00<00:00, 24.87it/s]

epoch: 370, beta = 0.010000, Train MSE: 0.047466, Train CE:0.326896, Train KL:6.350235, Val MSE:0.056091, Val CE:0.348342, Train ACC:0.928986, Val ACC:0.925000

Epoch 372/4000: 100%|██████████| 1/1 [00:00<00:00, 22.88it/s]

epoch: 371, beta = 0.010000, Train MSE: 0.047335, Train CE:0.325576, Train KL:6.345260, Val MSE:0.055861, Val CE:0.347461, Train ACC:0.929400, Val ACC:0.925521

Epoch 373/4000: 100%|██████████| 1/1 [00:00<00:00, 19.14it/s]

epoch: 372, beta = 0.010000, Train MSE: 0.047215, Train CE:0.324453, Train KL:6.340673, Val MSE:0.055448, Val CE:0.345608, Train ACC:0.930849, Val ACC:0.924479

Epoch 374/4000: 100%|██████████| 1/1 [00:00<00:00, 24.27it/s]

epoch: 373, beta = 0.010000, Train MSE: 0.047237, Train CE:0.323442, Train KL:6.336562, Val MSE:0.055525, Val CE:0.345678, Train ACC:0.928986, Val ACC:0.923958

Epoch 375/4000: 100%|██████████| 1/1 [00:00<00:00, 21.62it/s]

epoch: 374, beta = 0.010000, Train MSE: 0.046908, Train CE:0.322573, Train KL:6.334399, Val MSE:0.055252, Val CE:0.344921, Train ACC:0.932091, Val ACC:0.927604

Epoch 376/4000: 100%|██████████| 1/1 [00:00<00:00, 24.98it/s]

epoch: 375, beta = 0.010000, Train MSE: 0.046601, Train CE:0.321533, Train KL:6.332467, Val MSE:0.054936, Val CE:0.344040, Train ACC:0.933954, Val ACC:0.928125

Epoch 377/4000: 100%|██████████| 1/1 [00:00<00:00, 25.22it/s]

epoch: 376, beta = 0.010000, Train MSE: 0.046483, Train CE:0.320328, Train KL:6.332593, Val MSE:0.054551, Val CE:0.342028, Train ACC:0.931677, Val ACC:0.927604

Epoch 378/4000: 100%|██████████| 1/1 [00:00<00:00, 24.95it/s]

epoch: 377, beta = 0.010000, Train MSE: 0.046289, Train CE:0.319183, Train KL:6.327462, Val MSE:0.054439, Val CE:0.341705, Train ACC:0.932919, Val ACC:0.927604

Epoch 379/4000: 100%|██████████| 1/1 [00:00<00:00, 22.39it/s]

epoch: 378, beta = 0.010000, Train MSE: 0.045911, Train CE:0.318390, Train KL:6.325303, Val MSE:0.054502, Val CE:0.340632, Train ACC:0.932919, Val ACC:0.925521

Epoch 380/4000: 100%|██████████| 1/1 [00:00<00:00, 22.95it/s]

epoch: 379, beta = 0.010000, Train MSE: 0.045988, Train CE:0.317248, Train KL:6.323708, Val MSE:0.054132, Val CE:0.341145, Train ACC:0.934369, Val ACC:0.927083

Epoch 381/4000: 100%|██████████| 1/1 [00:00<00:00, 25.10it/s]

epoch: 380, beta = 0.010000, Train MSE: 0.045563, Train CE:0.316432, Train KL:6.324950, Val MSE:0.054296, Val CE:0.338030, Train ACC:0.932919, Val ACC:0.927604

Epoch 382/4000: 100%|██████████| 1/1 [00:00<00:00, 22.16it/s]

epoch: 381, beta = 0.010000, Train MSE: 0.045856, Train CE:0.315507, Train KL:6.317756, Val MSE:0.054076, Val CE:0.341973, Train ACC:0.934161, Val ACC:0.926042

Epoch 383/4000: 100%|██████████| 1/1 [00:00<00:00, 22.48it/s]

epoch: 382, beta = 0.010000, Train MSE: 0.045845, Train CE:0.315807, Train KL:6.323298, Val MSE:0.054564, Val CE:0.335394, Train ACC:0.932298, Val ACC:0.926563

Epoch 384/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 383, beta = 0.010000, Train MSE: 0.046808, Train CE:0.313470, Train KL:6.316403, Val MSE:0.052692, Val CE:0.336162, Train ACC:0.934990, Val ACC:0.927604

Epoch 385/4000: 100%|██████████| 1/1 [00:00<00:00, 23.40it/s]

epoch: 384, beta = 0.010000, Train MSE: 0.044953, Train CE:0.312579, Train KL:6.316266, Val MSE:0.052804, Val CE:0.334216, Train ACC:0.935611, Val ACC:0.928646

Epoch 386/4000: 100%|██████████| 1/1 [00:00<00:00, 22.98it/s]

epoch: 385, beta = 0.010000, Train MSE: 0.044670, Train CE:0.311098, Train KL:6.312829, Val MSE:0.053460, Val CE:0.331328, Train ACC:0.936025, Val ACC:0.927604

Epoch 387/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 386, beta = 0.010000, Train MSE: 0.045057, Train CE:0.310502, Train KL:6.306475, Val MSE:0.053129, Val CE:0.333591, Train ACC:0.935197, Val ACC:0.928646

Epoch 388/4000: 100%|██████████| 1/1 [00:00<00:00, 24.27it/s]

epoch: 387, beta = 0.010000, Train MSE: 0.044997, Train CE:0.310049, Train KL:6.303526, Val MSE:0.052704, Val CE:0.329313, Train ACC:0.935818, Val ACC:0.928125

Epoch 389/4000: 100%|██████████| 1/1 [00:00<00:00, 20.55it/s]

epoch: 388, beta = 0.010000, Train MSE: 0.044247, Train CE:0.308420, Train KL:6.295540, Val MSE:0.052168, Val CE:0.328447, Train ACC:0.936853, Val ACC:0.930208

Epoch 390/4000: 100%|██████████| 1/1 [00:00<00:00, 22.26it/s]

epoch: 389, beta = 0.010000, Train MSE: 0.043928, Train CE:0.307244, Train KL:6.290464, Val MSE:0.051665, Val CE:0.328674, Train ACC:0.938923, Val ACC:0.930208

Epoch 391/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 390, beta = 0.010000, Train MSE: 0.043808, Train CE:0.306329, Train KL:6.287990, Val MSE:0.052139, Val CE:0.327603, Train ACC:0.937681, Val ACC:0.930208

Epoch 392/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 391, beta = 0.010000, Train MSE: 0.044013, Train CE:0.305089, Train KL:6.279980, Val MSE:0.051164, Val CE:0.327990, Train ACC:0.937060, Val ACC:0.929688

Epoch 393/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 392, beta = 0.010000, Train MSE: 0.043324, Train CE:0.304083, Train KL:6.275822, Val MSE:0.051028, Val CE:0.327024, Train ACC:0.937888, Val ACC:0.929688

Epoch 394/4000: 100%|██████████| 1/1 [00:00<00:00, 21.74it/s]

epoch: 393, beta = 0.010000, Train MSE: 0.043285, Train CE:0.303383, Train KL:6.268238, Val MSE:0.051172, Val CE:0.325262, Train ACC:0.937888, Val ACC:0.931250

Epoch 395/4000: 100%|██████████| 1/1 [00:00<00:00, 18.87it/s]

epoch: 394, beta = 0.010000, Train MSE: 0.043390, Train CE:0.302556, Train KL:6.262921, Val MSE:0.050960, Val CE:0.328389, Train ACC:0.938716, Val ACC:0.931250

Epoch 396/4000: 100%|██████████| 1/1 [00:00<00:00, 19.10it/s]

epoch: 395, beta = 0.010000, Train MSE: 0.043191, Train CE:0.302657, Train KL:6.265736, Val MSE:0.050764, Val CE:0.324421, Train ACC:0.937681, Val ACC:0.931250

Epoch 397/4000: 100%|██████████| 1/1 [00:00<00:00, 20.83it/s]

epoch: 396, beta = 0.010000, Train MSE: 0.043078, Train CE:0.300178, Train KL:6.253669, Val MSE:0.050167, Val CE:0.322113, Train ACC:0.940373, Val ACC:0.930208

Epoch 398/4000: 100%|██████████| 1/1 [00:00<00:00, 20.22it/s]

epoch: 397, beta = 0.010000, Train MSE: 0.042659, Train CE:0.299445, Train KL:6.249306, Val MSE:0.050537, Val CE:0.324677, Train ACC:0.938923, Val ACC:0.930729

Epoch 399/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 398, beta = 0.010000, Train MSE: 0.042835, Train CE:0.299183, Train KL:6.252413, Val MSE:0.050795, Val CE:0.321396, Train ACC:0.938923, Val ACC:0.932813

Epoch 400/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 399, beta = 0.010000, Train MSE: 0.043413, Train CE:0.297501, Train KL:6.245936, Val MSE:0.049915, Val CE:0.321001, Train ACC:0.937888, Val ACC:0.932292

Epoch 401/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 400, beta = 0.010000, Train MSE: 0.042147, Train CE:0.296482, Train KL:6.237819, Val MSE:0.050382, Val CE:0.319230, Train ACC:0.939752, Val ACC:0.932292

Epoch 402/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 401, beta = 0.010000, Train MSE: 0.042358, Train CE:0.295569, Train KL:6.230314, Val MSE:0.049922, Val CE:0.317869, Train ACC:0.939337, Val ACC:0.933333

Epoch 403/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 402, beta = 0.010000, Train MSE: 0.042122, Train CE:0.294876, Train KL:6.227903, Val MSE:0.049264, Val CE:0.320041, Train ACC:0.940994, Val ACC:0.932813

Epoch 404/4000: 100%|██████████| 1/1 [00:00<00:00, 23.81it/s]

epoch: 403, beta = 0.010000, Train MSE: 0.041786, Train CE:0.293935, Train KL:6.230532, Val MSE:0.049045, Val CE:0.318812, Train ACC:0.939959, Val ACC:0.932813

Epoch 405/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 404, beta = 0.010000, Train MSE: 0.041571, Train CE:0.292463, Train KL:6.224968, Val MSE:0.049493, Val CE:0.315616, Train ACC:0.940787, Val ACC:0.933854

Epoch 406/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 405, beta = 0.010000, Train MSE: 0.041510, Train CE:0.291784, Train KL:6.214545, Val MSE:0.049018, Val CE:0.317182, Train ACC:0.941615, Val ACC:0.932813

Epoch 407/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 406, beta = 0.010000, Train MSE: 0.041208, Train CE:0.290990, Train KL:6.214493, Val MSE:0.048735, Val CE:0.314993, Train ACC:0.940787, Val ACC:0.935938

Epoch 408/4000: 100%|██████████| 1/1 [00:00<00:00, 22.34it/s]

epoch: 407, beta = 0.010000, Train MSE: 0.041234, Train CE:0.289811, Train KL:6.213959, Val MSE:0.048237, Val CE:0.314985, Train ACC:0.941615, Val ACC:0.935417

Epoch 409/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 408, beta = 0.010000, Train MSE: 0.040760, Train CE:0.288722, Train KL:6.209270, Val MSE:0.048353, Val CE:0.314814, Train ACC:0.941822, Val ACC:0.935417

Epoch 410/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 409, beta = 0.010000, Train MSE: 0.040629, Train CE:0.288079, Train KL:6.205472, Val MSE:0.047982, Val CE:0.313516, Train ACC:0.942029, Val ACC:0.934375

Epoch 411/4000: 100%|██████████| 1/1 [00:00<00:00, 21.28it/s]

epoch: 410, beta = 0.010000, Train MSE: 0.040589, Train CE:0.287014, Train KL:6.203883, Val MSE:0.047459, Val CE:0.313649, Train ACC:0.941822, Val ACC:0.935417

Epoch 412/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 411, beta = 0.010000, Train MSE: 0.040415, Train CE:0.286373, Train KL:6.205026, Val MSE:0.047437, Val CE:0.312075, Train ACC:0.942650, Val ACC:0.935938

Epoch 413/4000: 100%|██████████| 1/1 [00:00<00:00, 22.23it/s]

epoch: 412, beta = 0.010000, Train MSE: 0.040150, Train CE:0.284987, Train KL:6.199556, Val MSE:0.047445, Val CE:0.311057, Train ACC:0.942236, Val ACC:0.934896

Epoch 414/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 413, beta = 0.010000, Train MSE: 0.039967, Train CE:0.284214, Train KL:6.195549, Val MSE:0.047398, Val CE:0.311211, Train ACC:0.941822, Val ACC:0.938021

Epoch 415/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 414, beta = 0.010000, Train MSE: 0.039587, Train CE:0.283388, Train KL:6.195995, Val MSE:0.047261, Val CE:0.309506, Train ACC:0.942857, Val ACC:0.936458

Epoch 416/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 415, beta = 0.010000, Train MSE: 0.039606, Train CE:0.282387, Train KL:6.193247, Val MSE:0.046983, Val CE:0.309581, Train ACC:0.942443, Val ACC:0.937500

Epoch 417/4000: 100%|██████████| 1/1 [00:00<00:00, 22.72it/s]

epoch: 416, beta = 0.010000, Train MSE: 0.039588, Train CE:0.281424, Train KL:6.190547, Val MSE:0.047022, Val CE:0.307457, Train ACC:0.943685, Val ACC:0.937500

Epoch 418/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 417, beta = 0.010000, Train MSE: 0.039287, Train CE:0.280384, Train KL:6.186513, Val MSE:0.046279, Val CE:0.307605, Train ACC:0.944928, Val ACC:0.936979

Epoch 419/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 418, beta = 0.010000, Train MSE: 0.039024, Train CE:0.279524, Train KL:6.186398, Val MSE:0.046235, Val CE:0.306273, Train ACC:0.943892, Val ACC:0.936979

Epoch 420/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 419, beta = 0.010000, Train MSE: 0.039173, Train CE:0.278648, Train KL:6.182115, Val MSE:0.046102, Val CE:0.305914, Train ACC:0.943892, Val ACC:0.937500

Epoch 421/4000: 100%|██████████| 1/1 [00:00<00:00, 21.74it/s]

epoch: 420, beta = 0.010000, Train MSE: 0.038836, Train CE:0.277804, Train KL:6.177865, Val MSE:0.045797, Val CE:0.306384, Train ACC:0.944928, Val ACC:0.937500

Epoch 422/4000: 100%|██████████| 1/1 [00:00<00:00, 23.81it/s]

epoch: 421, beta = 0.010000, Train MSE: 0.038842, Train CE:0.277104, Train KL:6.175857, Val MSE:0.045955, Val CE:0.304793, Train ACC:0.945135, Val ACC:0.937500

Epoch 423/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 422, beta = 0.010000, Train MSE: 0.038786, Train CE:0.275964, Train KL:6.171637, Val MSE:0.045483, Val CE:0.304988, Train ACC:0.945756, Val ACC:0.937500

Epoch 424/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 423, beta = 0.010000, Train MSE: 0.038466, Train CE:0.275381, Train KL:6.169231, Val MSE:0.045619, Val CE:0.304456, Train ACC:0.945549, Val ACC:0.937500

Epoch 425/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 424, beta = 0.010000, Train MSE: 0.038444, Train CE:0.274260, Train KL:6.166096, Val MSE:0.045437, Val CE:0.303051, Train ACC:0.945963, Val ACC:0.939063

Epoch 426/4000: 100%|██████████| 1/1 [00:00<00:00, 23.81it/s]

epoch: 425, beta = 0.010000, Train MSE: 0.038168, Train CE:0.273313, Train KL:6.164220, Val MSE:0.045012, Val CE:0.301332, Train ACC:0.946170, Val ACC:0.937500

Epoch 427/4000: 100%|██████████| 1/1 [00:00<00:00, 24.39it/s]

epoch: 426, beta = 0.010000, Train MSE: 0.037880, Train CE:0.272509, Train KL:6.164004, Val MSE:0.044866, Val CE:0.301768, Train ACC:0.946377, Val ACC:0.938542

Epoch 428/4000: 100%|██████████| 1/1 [00:00<00:00, 23.81it/s]

epoch: 427, beta = 0.010000, Train MSE: 0.037634, Train CE:0.271817, Train KL:6.159874, Val MSE:0.044909, Val CE:0.299490, Train ACC:0.946584, Val ACC:0.937500

Epoch 429/4000: 100%|██████████| 1/1 [00:00<00:00, 23.96it/s]

epoch: 428, beta = 0.010000, Train MSE: 0.037822, Train CE:0.270966, Train KL:6.155246, Val MSE:0.045001, Val CE:0.302995, Train ACC:0.946791, Val ACC:0.940625

Epoch 430/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 429, beta = 0.010000, Train MSE: 0.037853, Train CE:0.270359, Train KL:6.154131, Val MSE:0.045022, Val CE:0.296661, Train ACC:0.946584, Val ACC:0.940625

Epoch 431/4000: 100%|██████████| 1/1 [00:00<00:00, 20.41it/s]

epoch: 430, beta = 0.010000, Train MSE: 0.038231, Train CE:0.269490, Train KL:6.146514, Val MSE:0.044825, Val CE:0.298439, Train ACC:0.946998, Val ACC:0.941146

Epoch 432/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 431, beta = 0.010000, Train MSE: 0.037773, Train CE:0.268953, Train KL:6.147707, Val MSE:0.044472, Val CE:0.295122, Train ACC:0.947205, Val ACC:0.941146

Epoch 433/4000: 100%|██████████| 1/1 [00:00<00:00, 23.81it/s]

epoch: 432, beta = 0.010000, Train MSE: 0.037334, Train CE:0.267696, Train KL:6.141737, Val MSE:0.044300, Val CE:0.295208, Train ACC:0.948240, Val ACC:0.940625

Epoch 434/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 433, beta = 0.010000, Train MSE: 0.037078, Train CE:0.266506, Train KL:6.140551, Val MSE:0.043934, Val CE:0.294021, Train ACC:0.946998, Val ACC:0.941146

Epoch 435/4000: 100%|██████████| 1/1 [00:00<00:00, 19.61it/s]

epoch: 434, beta = 0.010000, Train MSE: 0.037084, Train CE:0.265889, Train KL:6.136718, Val MSE:0.044445, Val CE:0.292197, Train ACC:0.948240, Val ACC:0.941146

Epoch 436/4000: 100%|██████████| 1/1 [00:00<00:00, 21.28it/s]

epoch: 435, beta = 0.010000, Train MSE: 0.037300, Train CE:0.264998, Train KL:6.130436, Val MSE:0.043674, Val CE:0.293831, Train ACC:0.948447, Val ACC:0.941146

Epoch 437/4000: 100%|██████████| 1/1 [00:00<00:00, 24.09it/s]

epoch: 436, beta = 0.010000, Train MSE: 0.036834, Train CE:0.264239, Train KL:6.130869, Val MSE:0.043460, Val CE:0.292625, Train ACC:0.948240, Val ACC:0.939583

Epoch 438/4000: 100%|██████████| 1/1 [00:00<00:00, 24.19it/s]

epoch: 437, beta = 0.010000, Train MSE: 0.036508, Train CE:0.263116, Train KL:6.125346, Val MSE:0.043609, Val CE:0.292343, Train ACC:0.947619, Val ACC:0.941667

Epoch 439/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 438, beta = 0.010000, Train MSE: 0.036512, Train CE:0.262228, Train KL:6.119261, Val MSE:0.043443, Val CE:0.293820, Train ACC:0.948654, Val ACC:0.942708

Epoch 440/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 439, beta = 0.010000, Train MSE: 0.036565, Train CE:0.261632, Train KL:6.118668, Val MSE:0.043162, Val CE:0.290947, Train ACC:0.948654, Val ACC:0.941146

Epoch 441/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 440, beta = 0.010000, Train MSE: 0.036513, Train CE:0.260628, Train KL:6.111309, Val MSE:0.042708, Val CE:0.291467, Train ACC:0.948447, Val ACC:0.940104

Epoch 442/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 441, beta = 0.010000, Train MSE: 0.035867, Train CE:0.259824, Train KL:6.106983, Val MSE:0.042691, Val CE:0.290615, Train ACC:0.950104, Val ACC:0.942188

Epoch 443/4000: 100%|██████████| 1/1 [00:00<00:00, 23.81it/s]

epoch: 442, beta = 0.010000, Train MSE: 0.035881, Train CE:0.259060, Train KL:6.103297, Val MSE:0.043071, Val CE:0.287237, Train ACC:0.949482, Val ACC:0.942188

Epoch 444/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 443, beta = 0.010000, Train MSE: 0.036129, Train CE:0.258286, Train KL:6.099441, Val MSE:0.042910, Val CE:0.291358, Train ACC:0.949897, Val ACC:0.942708

Epoch 445/4000: 100%|██████████| 1/1 [00:00<00:00, 23.25it/s]

epoch: 444, beta = 0.010000, Train MSE: 0.036188, Train CE:0.257964, Train KL:6.098129, Val MSE:0.043335, Val CE:0.286543, Train ACC:0.950932, Val ACC:0.943229

Epoch 446/4000: 100%|██████████| 1/1 [00:00<00:00, 23.81it/s]

epoch: 445, beta = 0.010000, Train MSE: 0.036414, Train CE:0.256937, Train KL:6.093792, Val MSE:0.042483, Val CE:0.288359, Train ACC:0.949068, Val ACC:0.943750

Epoch 447/4000: 100%|██████████| 1/1 [00:00<00:00, 23.81it/s]

epoch: 446, beta = 0.010000, Train MSE: 0.035328, Train CE:0.256045, Train KL:6.092958, Val MSE:0.042276, Val CE:0.286438, Train ACC:0.951760, Val ACC:0.944271

Epoch 448/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 447, beta = 0.010000, Train MSE: 0.035381, Train CE:0.254815, Train KL:6.086757, Val MSE:0.042416, Val CE:0.284897, Train ACC:0.950104, Val ACC:0.943750

Epoch 449/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 448, beta = 0.010000, Train MSE: 0.035546, Train CE:0.253838, Train KL:6.084451, Val MSE:0.042195, Val CE:0.286555, Train ACC:0.950932, Val ACC:0.942708

Epoch 450/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 449, beta = 0.010000, Train MSE: 0.035148, Train CE:0.253271, Train KL:6.082655, Val MSE:0.041727, Val CE:0.283282, Train ACC:0.951553, Val ACC:0.943750

Epoch 451/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 450, beta = 0.010000, Train MSE: 0.035048, Train CE:0.252524, Train KL:6.078352, Val MSE:0.041396, Val CE:0.283891, Train ACC:0.950104, Val ACC:0.943229

Epoch 452/4000: 100%|██████████| 1/1 [00:00<00:00, 21.28it/s]

epoch: 451, beta = 0.010000, Train MSE: 0.034665, Train CE:0.252148, Train KL:6.081758, Val MSE:0.041286, Val CE:0.280997, Train ACC:0.952174, Val ACC:0.944792

Epoch 453/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 452, beta = 0.010000, Train MSE: 0.034526, Train CE:0.250590, Train KL:6.074650, Val MSE:0.041514, Val CE:0.279700, Train ACC:0.951967, Val ACC:0.943229

Epoch 454/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 453, beta = 0.010000, Train MSE: 0.034534, Train CE:0.250047, Train KL:6.068190, Val MSE:0.041401, Val CE:0.280736, Train ACC:0.952381, Val ACC:0.944792

Epoch 455/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 454, beta = 0.010000, Train MSE: 0.034449, Train CE:0.249053, Train KL:6.070499, Val MSE:0.040623, Val CE:0.278539, Train ACC:0.951553, Val ACC:0.945313

Epoch 456/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 455, beta = 0.010000, Train MSE: 0.034272, Train CE:0.248198, Train KL:6.064252, Val MSE:0.040865, Val CE:0.277960, Train ACC:0.952588, Val ACC:0.946354

Epoch 457/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 456, beta = 0.010000, Train MSE: 0.034067, Train CE:0.247660, Train KL:6.055939, Val MSE:0.041102, Val CE:0.276684, Train ACC:0.953209, Val ACC:0.945313

Epoch 458/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 457, beta = 0.010000, Train MSE: 0.034040, Train CE:0.246554, Train KL:6.055332, Val MSE:0.040497, Val CE:0.276936, Train ACC:0.952588, Val ACC:0.945833

Epoch 459/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 458, beta = 0.010000, Train MSE: 0.033974, Train CE:0.246031, Train KL:6.052569, Val MSE:0.040845, Val CE:0.276173, Train ACC:0.951760, Val ACC:0.946354

Epoch 460/4000: 100%|██████████| 1/1 [00:00<00:00, 22.49it/s]

epoch: 459, beta = 0.010000, Train MSE: 0.033847, Train CE:0.245176, Train KL:6.049307, Val MSE:0.040410, Val CE:0.276072, Train ACC:0.952795, Val ACC:0.947396

Epoch 461/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 460, beta = 0.010000, Train MSE: 0.033934, Train CE:0.244569, Train KL:6.044675, Val MSE:0.040570, Val CE:0.279047, Train ACC:0.953002, Val ACC:0.946354

Epoch 462/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 461, beta = 0.010000, Train MSE: 0.033625, Train CE:0.244154, Train KL:6.047751, Val MSE:0.040629, Val CE:0.274242, Train ACC:0.952795, Val ACC:0.945833

Epoch 463/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 462, beta = 0.010000, Train MSE: 0.034048, Train CE:0.243014, Train KL:6.039858, Val MSE:0.040358, Val CE:0.274828, Train ACC:0.954658, Val ACC:0.945313

Epoch 464/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 463, beta = 0.010000, Train MSE: 0.033563, Train CE:0.242117, Train KL:6.038042, Val MSE:0.040064, Val CE:0.271799, Train ACC:0.953623, Val ACC:0.946354

Epoch 465/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 464, beta = 0.010000, Train MSE: 0.033570, Train CE:0.241106, Train KL:6.039359, Val MSE:0.039844, Val CE:0.269672, Train ACC:0.954037, Val ACC:0.946354

Epoch 466/4000: 100%|██████████| 1/1 [00:00<00:00, 23.25it/s]

epoch: 465, beta = 0.010000, Train MSE: 0.033595, Train CE:0.240409, Train KL:6.034540, Val MSE:0.039444, Val CE:0.271453, Train ACC:0.954037, Val ACC:0.946354

Epoch 467/4000: 100%|██████████| 1/1 [00:00<00:00, 23.54it/s]

epoch: 466, beta = 0.010000, Train MSE: 0.033177, Train CE:0.239786, Train KL:6.030657, Val MSE:0.039905, Val CE:0.269959, Train ACC:0.954451, Val ACC:0.947917

Epoch 468/4000: 100%|██████████| 1/1 [00:00<00:00, 23.81it/s]

epoch: 467, beta = 0.010000, Train MSE: 0.033222, Train CE:0.238896, Train KL:6.025756, Val MSE:0.039560, Val CE:0.271064, Train ACC:0.955072, Val ACC:0.947396

Epoch 469/4000: 100%|██████████| 1/1 [00:00<00:00, 22.98it/s]

epoch: 468, beta = 0.010000, Train MSE: 0.032847, Train CE:0.238036, Train KL:6.019479, Val MSE:0.039567, Val CE:0.269440, Train ACC:0.953830, Val ACC:0.948438

Epoch 470/4000: 100%|██████████| 1/1 [00:00<00:00, 21.74it/s]

epoch: 469, beta = 0.010000, Train MSE: 0.033009, Train CE:0.237326, Train KL:6.013855, Val MSE:0.039518, Val CE:0.269037, Train ACC:0.954658, Val ACC:0.947917

Epoch 471/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 470, beta = 0.010000, Train MSE: 0.032917, Train CE:0.236333, Train KL:6.013098, Val MSE:0.039075, Val CE:0.270360, Train ACC:0.955280, Val ACC:0.946875

Epoch 472/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 471, beta = 0.010000, Train MSE: 0.032411, Train CE:0.235995, Train KL:6.011937, Val MSE:0.039176, Val CE:0.265983, Train ACC:0.955072, Val ACC:0.948958

Epoch 473/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 472, beta = 0.010000, Train MSE: 0.032709, Train CE:0.235013, Train KL:6.007099, Val MSE:0.039062, Val CE:0.267679, Train ACC:0.956108, Val ACC:0.945313

Epoch 474/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 473, beta = 0.010000, Train MSE: 0.032480, Train CE:0.234711, Train KL:6.006303, Val MSE:0.039702, Val CE:0.262541, Train ACC:0.956315, Val ACC:0.944792

Epoch 475/4000: 100%|██████████| 1/1 [00:00<00:00, 20.41it/s]

epoch: 474, beta = 0.010000, Train MSE: 0.032747, Train CE:0.234035, Train KL:5.997323, Val MSE:0.039065, Val CE:0.263450, Train ACC:0.956522, Val ACC:0.946875

Epoch 476/4000: 100%|██████████| 1/1 [00:00<00:00, 22.19it/s]

epoch: 475, beta = 0.010000, Train MSE: 0.032453, Train CE:0.233081, Train KL:6.002381, Val MSE:0.038790, Val CE:0.262089, Train ACC:0.956522, Val ACC:0.945313

Epoch 477/4000: 100%|██████████| 1/1 [00:00<00:00, 24.25it/s]

epoch: 476, beta = 0.010000, Train MSE: 0.032161, Train CE:0.231924, Train KL:6.000727, Val MSE:0.038686, Val CE:0.261184, Train ACC:0.955694, Val ACC:0.948958

Epoch 478/4000: 100%|██████████| 1/1 [00:00<00:00, 20.53it/s]

epoch: 477, beta = 0.010000, Train MSE: 0.031956, Train CE:0.231017, Train KL:5.992087, Val MSE:0.038858, Val CE:0.261311, Train ACC:0.956522, Val ACC:0.948438

Epoch 479/4000: 100%|██████████| 1/1 [00:00<00:00, 24.25it/s]

epoch: 478, beta = 0.010000, Train MSE: 0.031969, Train CE:0.230813, Train KL:5.987764, Val MSE:0.038580, Val CE:0.260531, Train ACC:0.956522, Val ACC:0.947917

Epoch 480/4000: 100%|██████████| 1/1 [00:00<00:00, 23.46it/s]

epoch: 479, beta = 0.010000, Train MSE: 0.032162, Train CE:0.229700, Train KL:5.985837, Val MSE:0.037932, Val CE:0.265050, Train ACC:0.957350, Val ACC:0.947917

Epoch 481/4000: 100%|██████████| 1/1 [00:00<00:00, 23.39it/s]

epoch: 480, beta = 0.010000, Train MSE: 0.031638, Train CE:0.229561, Train KL:5.985499, Val MSE:0.038116, Val CE:0.261719, Train ACC:0.956315, Val ACC:0.948438

Epoch 482/4000: 100%|██████████| 1/1 [00:00<00:00, 20.81it/s]

epoch: 481, beta = 0.010000, Train MSE: 0.031704, Train CE:0.228471, Train KL:5.975745, Val MSE:0.037969, Val CE:0.260783, Train ACC:0.957557, Val ACC:0.948958

Epoch 483/4000: 100%|██████████| 1/1 [00:00<00:00, 20.66it/s]

epoch: 482, beta = 0.010000, Train MSE: 0.031424, Train CE:0.227264, Train KL:5.969452, Val MSE:0.037908, Val CE:0.261151, Train ACC:0.957557, Val ACC:0.948958

Epoch 484/4000: 100%|██████████| 1/1 [00:00<00:00, 21.19it/s]

epoch: 483, beta = 0.010000, Train MSE: 0.031543, Train CE:0.226550, Train KL:5.969145, Val MSE:0.037845, Val CE:0.258769, Train ACC:0.958592, Val ACC:0.948958

Epoch 485/4000: 100%|██████████| 1/1 [00:00<00:00, 23.94it/s]

epoch: 484, beta = 0.010000, Train MSE: 0.031307, Train CE:0.225543, Train KL:5.968508, Val MSE:0.037788, Val CE:0.258277, Train ACC:0.957971, Val ACC:0.947396

Epoch 486/4000: 100%|██████████| 1/1 [00:00<00:00, 24.20it/s]

epoch: 485, beta = 0.010000, Train MSE: 0.031036, Train CE:0.225127, Train KL:5.965550, Val MSE:0.037341, Val CE:0.258059, Train ACC:0.957557, Val ACC:0.950521

Epoch 487/4000: 100%|██████████| 1/1 [00:00<00:00, 22.88it/s]

epoch: 486, beta = 0.010000, Train MSE: 0.030974, Train CE:0.224624, Train KL:5.963652, Val MSE:0.037347, Val CE:0.257798, Train ACC:0.957350, Val ACC:0.949479

Epoch 488/4000: 100%|██████████| 1/1 [00:00<00:00, 24.05it/s]

epoch: 487, beta = 0.010000, Train MSE: 0.031070, Train CE:0.223945, Train KL:5.965193, Val MSE:0.037649, Val CE:0.257166, Train ACC:0.958178, Val ACC:0.950000

Epoch 489/4000: 100%|██████████| 1/1 [00:00<00:00, 23.82it/s]

epoch: 488, beta = 0.010000, Train MSE: 0.030988, Train CE:0.223072, Train KL:5.961154, Val MSE:0.037677, Val CE:0.255359, Train ACC:0.958178, Val ACC:0.951042

Epoch 490/4000: 100%|██████████| 1/1 [00:00<00:00, 24.12it/s]

epoch: 489, beta = 0.010000, Train MSE: 0.031006, Train CE:0.222082, Train KL:5.958910, Val MSE:0.037672, Val CE:0.256327, Train ACC:0.958385, Val ACC:0.950521

Epoch 491/4000: 100%|██████████| 1/1 [00:00<00:00, 23.47it/s]

epoch: 490, beta = 0.010000, Train MSE: 0.030737, Train CE:0.221654, Train KL:5.958484, Val MSE:0.037200, Val CE:0.250861, Train ACC:0.958592, Val ACC:0.951042

Epoch 492/4000: 100%|██████████| 1/1 [00:00<00:00, 20.37it/s]

epoch: 491, beta = 0.010000, Train MSE: 0.030797, Train CE:0.220850, Train KL:5.949225, Val MSE:0.037180, Val CE:0.251354, Train ACC:0.959834, Val ACC:0.950521

Epoch 493/4000: 100%|██████████| 1/1 [00:00<00:00, 24.43it/s]

epoch: 492, beta = 0.010000, Train MSE: 0.030496, Train CE:0.219754, Train KL:5.948717, Val MSE:0.036870, Val CE:0.252177, Train ACC:0.959006, Val ACC:0.950521

Epoch 494/4000: 100%|██████████| 1/1 [00:00<00:00, 24.37it/s]

epoch: 493, beta = 0.010000, Train MSE: 0.030343, Train CE:0.219415, Train KL:5.949908, Val MSE:0.036736, Val CE:0.251076, Train ACC:0.958385, Val ACC:0.950521

Epoch 495/4000: 100%|██████████| 1/1 [00:00<00:00, 23.44it/s]

epoch: 494, beta = 0.010000, Train MSE: 0.030559, Train CE:0.218917, Train KL:5.943386, Val MSE:0.037595, Val CE:0.253685, Train ACC:0.959006, Val ACC:0.950521

Epoch 496/4000: 100%|██████████| 1/1 [00:00<00:00, 23.56it/s]

epoch: 495, beta = 0.010000, Train MSE: 0.030638, Train CE:0.218439, Train KL:5.938605, Val MSE:0.037652, Val CE:0.247950, Train ACC:0.958385, Val ACC:0.951563

Epoch 497/4000: 100%|██████████| 1/1 [00:00<00:00, 22.89it/s]

epoch: 496, beta = 0.010000, Train MSE: 0.031360, Train CE:0.217747, Train KL:5.934658, Val MSE:0.036908, Val CE:0.253476, Train ACC:0.960248, Val ACC:0.950000

Epoch 498/4000: 100%|██████████| 1/1 [00:00<00:00, 23.04it/s]

epoch: 497, beta = 0.010000, Train MSE: 0.030486, Train CE:0.217344, Train KL:5.937545, Val MSE:0.036602, Val CE:0.246039, Train ACC:0.958385, Val ACC:0.954688

Epoch 499/4000: 100%|██████████| 1/1 [00:00<00:00, 23.71it/s]

epoch: 498, beta = 0.010000, Train MSE: 0.030642, Train CE:0.215940, Train KL:5.932597, Val MSE:0.036308, Val CE:0.246696, Train ACC:0.960041, Val ACC:0.952083

Epoch 500/4000: 100%|██████████| 1/1 [00:00<00:00, 24.29it/s]

epoch: 499, beta = 0.010000, Train MSE: 0.030019, Train CE:0.214715, Train KL:5.931295, Val MSE:0.036598, Val CE:0.246968, Train ACC:0.961284, Val ACC:0.950521

Epoch 501/4000: 100%|██████████| 1/1 [00:00<00:00, 23.77it/s]

epoch: 500, beta = 0.010000, Train MSE: 0.029863, Train CE:0.214260, Train KL:5.925643, Val MSE:0.036403, Val CE:0.243575, Train ACC:0.959834, Val ACC:0.952083

Epoch 502/4000: 100%|██████████| 1/1 [00:00<00:00, 23.46it/s]

epoch: 501, beta = 0.010000, Train MSE: 0.030218, Train CE:0.213916, Train KL:5.921596, Val MSE:0.036603, Val CE:0.247302, Train ACC:0.960663, Val ACC:0.951563

Epoch 503/4000: 100%|██████████| 1/1 [00:00<00:00, 20.63it/s]

epoch: 502, beta = 0.010000, Train MSE: 0.030378, Train CE:0.213452, Train KL:5.923869, Val MSE:0.036441, Val CE:0.243208, Train ACC:0.959627, Val ACC:0.953646

Epoch 504/4000: 100%|██████████| 1/1 [00:00<00:00, 26.49it/s]

epoch: 503, beta = 0.010000, Train MSE: 0.030079, Train CE:0.212234, Train KL:5.915393, Val MSE:0.035857, Val CE:0.243390, Train ACC:0.960663, Val ACC:0.952083

Epoch 505/4000: 100%|██████████| 1/1 [00:00<00:00, 23.01it/s]

epoch: 504, beta = 0.010000, Train MSE: 0.029503, Train CE:0.211438, Train KL:5.916714, Val MSE:0.035814, Val CE:0.242932, Train ACC:0.961077, Val ACC:0.952604

Epoch 506/4000: 100%|██████████| 1/1 [00:00<00:00, 23.61it/s]

epoch: 505, beta = 0.010000, Train MSE: 0.029302, Train CE:0.210546, Train KL:5.917792, Val MSE:0.035469, Val CE:0.241808, Train ACC:0.961491, Val ACC:0.952083

Epoch 507/4000: 100%|██████████| 1/1 [00:00<00:00, 23.24it/s]

epoch: 506, beta = 0.010000, Train MSE: 0.029286, Train CE:0.209818, Train KL:5.911684, Val MSE:0.035674, Val CE:0.242173, Train ACC:0.960041, Val ACC:0.953125

Epoch 508/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 507, beta = 0.010000, Train MSE: 0.029281, Train CE:0.209427, Train KL:5.909793, Val MSE:0.035683, Val CE:0.238304, Train ACC:0.960663, Val ACC:0.952604

Epoch 509/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 508, beta = 0.010000, Train MSE: 0.029199, Train CE:0.208413, Train KL:5.905941, Val MSE:0.035945, Val CE:0.240374, Train ACC:0.961905, Val ACC:0.952083

Epoch 510/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 509, beta = 0.010000, Train MSE: 0.029270, Train CE:0.207810, Train KL:5.902499, Val MSE:0.035299, Val CE:0.238726, Train ACC:0.962733, Val ACC:0.953125

Epoch 511/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 510, beta = 0.010000, Train MSE: 0.028819, Train CE:0.207153, Train KL:5.902362, Val MSE:0.035968, Val CE:0.238508, Train ACC:0.963147, Val ACC:0.952604

Epoch 512/4000: 100%|██████████| 1/1 [00:00<00:00, 23.81it/s]

epoch: 511, beta = 0.010000, Train MSE: 0.029117, Train CE:0.206253, Train KL:5.900126, Val MSE:0.035091, Val CE:0.239973, Train ACC:0.962940, Val ACC:0.952083

Epoch 513/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 512, beta = 0.010000, Train MSE: 0.028735, Train CE:0.205808, Train KL:5.899442, Val MSE:0.035448, Val CE:0.236425, Train ACC:0.962526, Val ACC:0.955208

Epoch 514/4000: 100%|██████████| 1/1 [00:00<00:00, 23.53it/s]

epoch: 513, beta = 0.010000, Train MSE: 0.028829, Train CE:0.205246, Train KL:5.893790, Val MSE:0.035315, Val CE:0.238691, Train ACC:0.963768, Val ACC:0.954167

Epoch 515/4000: 100%|██████████| 1/1 [00:00<00:00, 23.81it/s]

epoch: 514, beta = 0.010000, Train MSE: 0.028617, Train CE:0.204761, Train KL:5.890439, Val MSE:0.035103, Val CE:0.234799, Train ACC:0.961698, Val ACC:0.953125

Epoch 516/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 515, beta = 0.010000, Train MSE: 0.028574, Train CE:0.203619, Train KL:5.889247, Val MSE:0.034845, Val CE:0.233324, Train ACC:0.964389, Val ACC:0.954688

Epoch 517/4000: 100%|██████████| 1/1 [00:00<00:00, 23.50it/s]

epoch: 516, beta = 0.010000, Train MSE: 0.028407, Train CE:0.202937, Train KL:5.888098, Val MSE:0.035026, Val CE:0.233466, Train ACC:0.963561, Val ACC:0.955208

Epoch 518/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 517, beta = 0.010000, Train MSE: 0.028382, Train CE:0.202100, Train KL:5.884118, Val MSE:0.035273, Val CE:0.232474, Train ACC:0.964182, Val ACC:0.956771

Epoch 519/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 518, beta = 0.010000, Train MSE: 0.028693, Train CE:0.201786, Train KL:5.880502, Val MSE:0.034860, Val CE:0.233956, Train ACC:0.963561, Val ACC:0.955208

Epoch 520/4000: 100%|██████████| 1/1 [00:00<00:00, 18.52it/s]

epoch: 519, beta = 0.010000, Train MSE: 0.028207, Train CE:0.200946, Train KL:5.880627, Val MSE:0.035224, Val CE:0.231031, Train ACC:0.963975, Val ACC:0.955208

Epoch 521/4000: 100%|██████████| 1/1 [00:00<00:00, 19.61it/s]

epoch: 520, beta = 0.010000, Train MSE: 0.028576, Train CE:0.200355, Train KL:5.877932, Val MSE:0.035090, Val CE:0.231464, Train ACC:0.964596, Val ACC:0.957292

Epoch 522/4000: 100%|██████████| 1/1 [00:00<00:00, 21.74it/s]

epoch: 521, beta = 0.010000, Train MSE: 0.028061, Train CE:0.199295, Train KL:5.872152, Val MSE:0.034590, Val CE:0.229173, Train ACC:0.964803, Val ACC:0.955729

Epoch 523/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 522, beta = 0.010000, Train MSE: 0.028284, Train CE:0.198825, Train KL:5.865607, Val MSE:0.034571, Val CE:0.230586, Train ACC:0.965424, Val ACC:0.957292

Epoch 524/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 523, beta = 0.010000, Train MSE: 0.028031, Train CE:0.197998, Train KL:5.865366, Val MSE:0.034604, Val CE:0.230819, Train ACC:0.965631, Val ACC:0.956771

Epoch 525/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 524, beta = 0.010000, Train MSE: 0.028161, Train CE:0.197197, Train KL:5.863635, Val MSE:0.034116, Val CE:0.228902, Train ACC:0.965217, Val ACC:0.957813

Epoch 526/4000: 100%|██████████| 1/1 [00:00<00:00, 23.81it/s]

epoch: 525, beta = 0.010000, Train MSE: 0.027903, Train CE:0.196358, Train KL:5.858010, Val MSE:0.034324, Val CE:0.230280, Train ACC:0.966253, Val ACC:0.954167

Epoch 527/4000: 100%|██████████| 1/1 [00:00<00:00, 23.81it/s]

epoch: 526, beta = 0.010000, Train MSE: 0.027831, Train CE:0.196089, Train KL:5.855631, Val MSE:0.033848, Val CE:0.227436, Train ACC:0.965838, Val ACC:0.955729

Epoch 528/4000: 100%|██████████| 1/1 [00:00<00:00, 23.51it/s]

epoch: 527, beta = 0.010000, Train MSE: 0.027718, Train CE:0.195331, Train KL:5.856435, Val MSE:0.033854, Val CE:0.229567, Train ACC:0.966667, Val ACC:0.957292

Epoch 529/4000: 100%|██████████| 1/1 [00:00<00:00, 23.81it/s]

epoch: 528, beta = 0.010000, Train MSE: 0.027520, Train CE:0.194785, Train KL:5.855560, Val MSE:0.033920, Val CE:0.224710, Train ACC:0.966253, Val ACC:0.957813

Epoch 530/4000: 100%|██████████| 1/1 [00:00<00:00, 23.81it/s]

epoch: 529, beta = 0.010000, Train MSE: 0.027693, Train CE:0.193839, Train KL:5.851288, Val MSE:0.034418, Val CE:0.224638, Train ACC:0.966253, Val ACC:0.960417

Epoch 531/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 530, beta = 0.010000, Train MSE: 0.027770, Train CE:0.193353, Train KL:5.847055, Val MSE:0.033797, Val CE:0.221623, Train ACC:0.965838, Val ACC:0.958333

Epoch 532/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 531, beta = 0.010000, Train MSE: 0.027527, Train CE:0.192447, Train KL:5.844851, Val MSE:0.033531, Val CE:0.224133, Train ACC:0.967081, Val ACC:0.958854

Epoch 533/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 532, beta = 0.010000, Train MSE: 0.027315, Train CE:0.191751, Train KL:5.845546, Val MSE:0.033660, Val CE:0.221709, Train ACC:0.966460, Val ACC:0.959375

Epoch 534/4000: 100%|██████████| 1/1 [00:00<00:00, 23.53it/s]

epoch: 533, beta = 0.010000, Train MSE: 0.027116, Train CE:0.191008, Train KL:5.839019, Val MSE:0.033439, Val CE:0.220756, Train ACC:0.967081, Val ACC:0.956250

Epoch 535/4000: 100%|██████████| 1/1 [00:00<00:00, 23.53it/s]

epoch: 534, beta = 0.010000, Train MSE: 0.027150, Train CE:0.190365, Train KL:5.836468, Val MSE:0.033388, Val CE:0.223514, Train ACC:0.966874, Val ACC:0.961458

Epoch 536/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 535, beta = 0.010000, Train MSE: 0.027080, Train CE:0.189826, Train KL:5.837773, Val MSE:0.033715, Val CE:0.218629, Train ACC:0.967288, Val ACC:0.958854

Epoch 537/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 536, beta = 0.010000, Train MSE: 0.027365, Train CE:0.189201, Train KL:5.832469, Val MSE:0.033964, Val CE:0.221013, Train ACC:0.967081, Val ACC:0.959896

Epoch 538/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 537, beta = 0.010000, Train MSE: 0.027102, Train CE:0.188367, Train KL:5.829938, Val MSE:0.033574, Val CE:0.218821, Train ACC:0.967081, Val ACC:0.958854

Epoch 539/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 538, beta = 0.010000, Train MSE: 0.027033, Train CE:0.187808, Train KL:5.826781, Val MSE:0.033442, Val CE:0.219876, Train ACC:0.967702, Val ACC:0.958854

Epoch 540/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 539, beta = 0.010000, Train MSE: 0.026955, Train CE:0.186893, Train KL:5.823691, Val MSE:0.033264, Val CE:0.218780, Train ACC:0.968323, Val ACC:0.958333

Epoch 541/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 540, beta = 0.010000, Train MSE: 0.026718, Train CE:0.186320, Train KL:5.819951, Val MSE:0.033502, Val CE:0.218543, Train ACC:0.968944, Val ACC:0.958333

Epoch 542/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 541, beta = 0.010000, Train MSE: 0.026701, Train CE:0.185853, Train KL:5.818276, Val MSE:0.033109, Val CE:0.219342, Train ACC:0.968116, Val ACC:0.959896

Epoch 543/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 542, beta = 0.010000, Train MSE: 0.026738, Train CE:0.185141, Train KL:5.816436, Val MSE:0.032665, Val CE:0.217059, Train ACC:0.967702, Val ACC:0.958854

Epoch 544/4000: 100%|██████████| 1/1 [00:00<00:00, 21.74it/s]

epoch: 543, beta = 0.010000, Train MSE: 0.026579, Train CE:0.184575, Train KL:5.814291, Val MSE:0.033309, Val CE:0.219395, Train ACC:0.968116, Val ACC:0.961458

Epoch 545/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 544, beta = 0.010000, Train MSE: 0.026540, Train CE:0.184339, Train KL:5.813642, Val MSE:0.033231, Val CE:0.214092, Train ACC:0.968323, Val ACC:0.958854

Epoch 546/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 545, beta = 0.010000, Train MSE: 0.026978, Train CE:0.183657, Train KL:5.810630, Val MSE:0.033735, Val CE:0.221427, Train ACC:0.968323, Val ACC:0.960417

Epoch 547/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 546, beta = 0.010000, Train MSE: 0.027302, Train CE:0.183496, Train KL:5.810765, Val MSE:0.034259, Val CE:0.212592, Train ACC:0.969358, Val ACC:0.961979

Epoch 548/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 547, beta = 0.010000, Train MSE: 0.028175, Train CE:0.182766, Train KL:5.807058, Val MSE:0.033948, Val CE:0.220764, Train ACC:0.966874, Val ACC:0.958854

Epoch 549/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 548, beta = 0.010000, Train MSE: 0.027324, Train CE:0.182838, Train KL:5.811305, Val MSE:0.033015, Val CE:0.209282, Train ACC:0.967909, Val ACC:0.961458

Epoch 550/4000: 100%|██████████| 1/1 [00:00<00:00, 21.79it/s]

epoch: 549, beta = 0.010000, Train MSE: 0.026794, Train CE:0.181079, Train KL:5.804221, Val MSE:0.032404, Val CE:0.210909, Train ACC:0.968737, Val ACC:0.959375

Epoch 551/4000: 100%|██████████| 1/1 [00:00<00:00, 20.41it/s]

epoch: 550, beta = 0.010000, Train MSE: 0.026027, Train CE:0.179832, Train KL:5.801611, Val MSE:0.032539, Val CE:0.212129, Train ACC:0.970186, Val ACC:0.959375

Epoch 552/4000: 100%|██████████| 1/1 [00:00<00:00, 20.20it/s]

epoch: 551, beta = 0.010000, Train MSE: 0.026258, Train CE:0.179406, Train KL:5.801209, Val MSE:0.033148, Val CE:0.207260, Train ACC:0.969565, Val ACC:0.960417

Epoch 553/4000: 100%|██████████| 1/1 [00:00<00:00, 20.41it/s]

epoch: 552, beta = 0.010000, Train MSE: 0.026812, Train CE:0.178911, Train KL:5.794879, Val MSE:0.033225, Val CE:0.212810, Train ACC:0.969358, Val ACC:0.960938

Epoch 554/4000: 100%|██████████| 1/1 [00:00<00:00, 21.05it/s]

epoch: 553, beta = 0.010000, Train MSE: 0.026407, Train CE:0.178499, Train KL:5.792384, Val MSE:0.032510, Val CE:0.206906, Train ACC:0.970393, Val ACC:0.959896

Epoch 555/4000: 100%|██████████| 1/1 [00:00<00:00, 20.83it/s]

epoch: 554, beta = 0.010000, Train MSE: 0.026272, Train CE:0.177622, Train KL:5.789851, Val MSE:0.032242, Val CE:0.211056, Train ACC:0.970393, Val ACC:0.963021

Epoch 556/4000: 100%|██████████| 1/1 [00:00<00:00, 21.28it/s]

epoch: 555, beta = 0.010000, Train MSE: 0.026033, Train CE:0.177056, Train KL:5.789055, Val MSE:0.031862, Val CE:0.207415, Train ACC:0.970393, Val ACC:0.962500

Epoch 557/4000: 100%|██████████| 1/1 [00:00<00:00, 21.28it/s]

epoch: 556, beta = 0.010000, Train MSE: 0.025901, Train CE:0.176103, Train KL:5.789303, Val MSE:0.031570, Val CE:0.205349, Train ACC:0.969565, Val ACC:0.962500

Epoch 558/4000: 100%|██████████| 1/1 [00:00<00:00, 21.27it/s]

epoch: 557, beta = 0.010000, Train MSE: 0.025676, Train CE:0.175659, Train KL:5.782701, Val MSE:0.031428, Val CE:0.208943, Train ACC:0.970393, Val ACC:0.962500

Epoch 559/4000: 100%|██████████| 1/1 [00:00<00:00, 20.83it/s]

epoch: 558, beta = 0.010000, Train MSE: 0.025512, Train CE:0.174683, Train KL:5.781310, Val MSE:0.032253, Val CE:0.205674, Train ACC:0.970600, Val ACC:0.961458

Epoch 560/4000: 100%|██████████| 1/1 [00:00<00:00, 19.23it/s]

epoch: 559, beta = 0.010000, Train MSE: 0.025969, Train CE:0.174122, Train KL:5.780358, Val MSE:0.032301, Val CE:0.205837, Train ACC:0.970600, Val ACC:0.961979

Epoch 561/4000: 100%|██████████| 1/1 [00:00<00:00, 18.52it/s]

epoch: 560, beta = 0.010000, Train MSE: 0.025565, Train CE:0.173550, Train KL:5.776711, Val MSE:0.032280, Val CE:0.201603, Train ACC:0.971636, Val ACC:0.959375

Epoch 562/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 561, beta = 0.010000, Train MSE: 0.025589, Train CE:0.173165, Train KL:5.771328, Val MSE:0.031685, Val CE:0.204587, Train ACC:0.971429, Val ACC:0.960417

Epoch 563/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 562, beta = 0.010000, Train MSE: 0.025596, Train CE:0.172250, Train KL:5.764946, Val MSE:0.032279, Val CE:0.203969, Train ACC:0.972671, Val ACC:0.960417

Epoch 564/4000: 100%|██████████| 1/1 [00:00<00:00, 23.81it/s]

epoch: 563, beta = 0.010000, Train MSE: 0.025776, Train CE:0.171677, Train KL:5.761974, Val MSE:0.031519, Val CE:0.202441, Train ACC:0.971636, Val ACC:0.964583

Epoch 565/4000: 100%|██████████| 1/1 [00:00<00:00, 23.81it/s]

epoch: 564, beta = 0.010000, Train MSE: 0.025614, Train CE:0.170798, Train KL:5.755337, Val MSE:0.031903, Val CE:0.202832, Train ACC:0.973292, Val ACC:0.964583

Epoch 566/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 565, beta = 0.010000, Train MSE: 0.025308, Train CE:0.170267, Train KL:5.749519, Val MSE:0.031789, Val CE:0.203820, Train ACC:0.972671, Val ACC:0.965625

Epoch 567/4000: 100%|██████████| 1/1 [00:00<00:00, 23.81it/s]

epoch: 566, beta = 0.010000, Train MSE: 0.025306, Train CE:0.169674, Train KL:5.747564, Val MSE:0.032027, Val CE:0.202653, Train ACC:0.973706, Val ACC:0.965625

Epoch 568/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 567, beta = 0.010000, Train MSE: 0.025542, Train CE:0.169129, Train KL:5.744463, Val MSE:0.031892, Val CE:0.203903, Train ACC:0.971636, Val ACC:0.965625

Epoch 569/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 568, beta = 0.010000, Train MSE: 0.025226, Train CE:0.168607, Train KL:5.744586, Val MSE:0.031313, Val CE:0.201006, Train ACC:0.972464, Val ACC:0.966667

Epoch 570/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 569, beta = 0.010000, Train MSE: 0.025189, Train CE:0.167826, Train KL:5.738780, Val MSE:0.031419, Val CE:0.199858, Train ACC:0.973706, Val ACC:0.965625

Epoch 571/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 570, beta = 0.010000, Train MSE: 0.025107, Train CE:0.167266, Train KL:5.735837, Val MSE:0.031547, Val CE:0.200613, Train ACC:0.974120, Val ACC:0.966667

Epoch 572/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 571, beta = 0.010000, Train MSE: 0.025192, Train CE:0.166466, Train KL:5.736489, Val MSE:0.031277, Val CE:0.198514, Train ACC:0.974741, Val ACC:0.967708

Epoch 573/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 572, beta = 0.010000, Train MSE: 0.025159, Train CE:0.165830, Train KL:5.731719, Val MSE:0.031140, Val CE:0.198670, Train ACC:0.974120, Val ACC:0.965104

Epoch 574/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 573, beta = 0.010000, Train MSE: 0.025097, Train CE:0.165197, Train KL:5.733356, Val MSE:0.031080, Val CE:0.197875, Train ACC:0.973706, Val ACC:0.965625

Epoch 575/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 574, beta = 0.010000, Train MSE: 0.024946, Train CE:0.164636, Train KL:5.729643, Val MSE:0.030978, Val CE:0.196849, Train ACC:0.974327, Val ACC:0.963542

Epoch 576/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 575, beta = 0.010000, Train MSE: 0.024767, Train CE:0.164011, Train KL:5.727436, Val MSE:0.031028, Val CE:0.195722, Train ACC:0.974948, Val ACC:0.963542

Epoch 577/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 576, beta = 0.010000, Train MSE: 0.024775, Train CE:0.163393, Train KL:5.726441, Val MSE:0.031348, Val CE:0.196436, Train ACC:0.975569, Val ACC:0.964583

Epoch 578/4000: 100%|██████████| 1/1 [00:00<00:00, 19.23it/s]

epoch: 577, beta = 0.010000, Train MSE: 0.024854, Train CE:0.162964, Train KL:5.721719, Val MSE:0.031028, Val CE:0.194940, Train ACC:0.975983, Val ACC:0.964063

Epoch 579/4000: 100%|██████████| 1/1 [00:00<00:00, 18.51it/s]

epoch: 578, beta = 0.010000, Train MSE: 0.024972, Train CE:0.162529, Train KL:5.721367, Val MSE:0.031029, Val CE:0.197847, Train ACC:0.975776, Val ACC:0.963542

Epoch 580/4000: 100%|██████████| 1/1 [00:00<00:00, 21.28it/s]

epoch: 579, beta = 0.010000, Train MSE: 0.024884, Train CE:0.162113, Train KL:5.718434, Val MSE:0.031401, Val CE:0.192099, Train ACC:0.975983, Val ACC:0.964063

Epoch 581/4000: 100%|██████████| 1/1 [00:00<00:00, 21.50it/s]

epoch: 580, beta = 0.010000, Train MSE: 0.025204, Train CE:0.161592, Train KL:5.717211, Val MSE:0.031644, Val CE:0.200084, Train ACC:0.974534, Val ACC:0.964063

Epoch 582/4000: 100%|██████████| 1/1 [00:00<00:00, 23.87it/s]

epoch: 581, beta = 0.010000, Train MSE: 0.025469, Train CE:0.161534, Train KL:5.718616, Val MSE:0.031601, Val CE:0.190123, Train ACC:0.975155, Val ACC:0.966146

Epoch 583/4000: 100%|██████████| 1/1 [00:00<00:00, 21.50it/s]

epoch: 582, beta = 0.010000, Train MSE: 0.025862, Train CE:0.161428, Train KL:5.712491, Val MSE:0.031630, Val CE:0.197133, Train ACC:0.974120, Val ACC:0.964583

Epoch 584/4000: 100%|██████████| 1/1 [00:00<00:00, 23.15it/s]

epoch: 583, beta = 0.010000, Train MSE: 0.025669, Train CE:0.160546, Train KL:5.712364, Val MSE:0.030359, Val CE:0.189388, Train ACC:0.973913, Val ACC:0.968750

Epoch 585/4000: 100%|██████████| 1/1 [00:00<00:00, 24.11it/s]

epoch: 584, beta = 0.010000, Train MSE: 0.025343, Train CE:0.158940, Train KL:5.710799, Val MSE:0.029648, Val CE:0.189909, Train ACC:0.974741, Val ACC:0.967708

Epoch 586/4000: 100%|██████████| 1/1 [00:00<00:00, 20.63it/s]

epoch: 585, beta = 0.010000, Train MSE: 0.024217, Train CE:0.158143, Train KL:5.707417, Val MSE:0.030018, Val CE:0.190998, Train ACC:0.977019, Val ACC:0.968229

Epoch 587/4000: 100%|██████████| 1/1 [00:00<00:00, 24.58it/s]

epoch: 586, beta = 0.010000, Train MSE: 0.024243, Train CE:0.157769, Train KL:5.703413, Val MSE:0.031344, Val CE:0.185984, Train ACC:0.975569, Val ACC:0.967188

Epoch 588/4000: 100%|██████████| 1/1 [00:00<00:00, 21.95it/s]

epoch: 587, beta = 0.010000, Train MSE: 0.025648, Train CE:0.157804, Train KL:5.699905, Val MSE:0.032341, Val CE:0.193904, Train ACC:0.976605, Val ACC:0.969792

Epoch 589/4000: 100%|██████████| 1/1 [00:00<00:00, 24.04it/s]

epoch: 588, beta = 0.010000, Train MSE: 0.025778, Train CE:0.157854, Train KL:5.697799, Val MSE:0.030707, Val CE:0.183434, Train ACC:0.975776, Val ACC:0.966667

Epoch 590/4000: 100%|██████████| 1/1 [00:00<00:00, 24.96it/s]

epoch: 589, beta = 0.010000, Train MSE: 0.024945, Train CE:0.157105, Train KL:5.693216, Val MSE:0.030152, Val CE:0.187928, Train ACC:0.977640, Val ACC:0.967708

Epoch 591/4000: 100%|██████████| 1/1 [00:00<00:00, 25.35it/s]

epoch: 590, beta = 0.010000, Train MSE: 0.024038, Train CE:0.155563, Train KL:5.691038, Val MSE:0.029794, Val CE:0.185009, Train ACC:0.977433, Val ACC:0.968750

Epoch 592/4000: 100%|██████████| 1/1 [00:00<00:00, 23.96it/s]

epoch: 591, beta = 0.010000, Train MSE: 0.023893, Train CE:0.154798, Train KL:5.690235, Val MSE:0.030211, Val CE:0.181877, Train ACC:0.976605, Val ACC:0.966146

Epoch 593/4000: 100%|██████████| 1/1 [00:00<00:00, 20.73it/s]

epoch: 592, beta = 0.010000, Train MSE: 0.024586, Train CE:0.154529, Train KL:5.687554, Val MSE:0.030357, Val CE:0.190138, Train ACC:0.976812, Val ACC:0.966667

Epoch 594/4000: 100%|██████████| 1/1 [00:00<00:00, 20.61it/s]

epoch: 593, beta = 0.010000, Train MSE: 0.024759, Train CE:0.153941, Train KL:5.683779, Val MSE:0.030039, Val CE:0.183450, Train ACC:0.978261, Val ACC:0.968229

Epoch 595/4000: 100%|██████████| 1/1 [00:00<00:00, 24.24it/s]

epoch: 594, beta = 0.010000, Train MSE: 0.024340, Train CE:0.152908, Train KL:5.679556, Val MSE:0.029526, Val CE:0.185784, Train ACC:0.978882, Val ACC:0.969792

Epoch 596/4000: 100%|██████████| 1/1 [00:00<00:00, 21.42it/s]

epoch: 595, beta = 0.010000, Train MSE: 0.023702, Train CE:0.152241, Train KL:5.678609, Val MSE:0.029520, Val CE:0.185319, Train ACC:0.978882, Val ACC:0.968750

Epoch 597/4000: 100%|██████████| 1/1 [00:00<00:00, 21.09it/s]

epoch: 596, beta = 0.010000, Train MSE: 0.023866, Train CE:0.151761, Train KL:5.676869, Val MSE:0.029815, Val CE:0.179565, Train ACC:0.979710, Val ACC:0.969792

Epoch 598/4000: 100%|██████████| 1/1 [00:00<00:00, 21.30it/s]

epoch: 597, beta = 0.010000, Train MSE: 0.024025, Train CE:0.151461, Train KL:5.675462, Val MSE:0.030514, Val CE:0.184667, Train ACC:0.980538, Val ACC:0.970313

Epoch 599/4000: 100%|██████████| 1/1 [00:00<00:00, 21.49it/s]

epoch: 598, beta = 0.010000, Train MSE: 0.023928, Train CE:0.150790, Train KL:5.672740, Val MSE:0.029841, Val CE:0.180579, Train ACC:0.980124, Val ACC:0.970833

Epoch 600/4000: 100%|██████████| 1/1 [00:00<00:00, 22.93it/s]

epoch: 599, beta = 0.010000, Train MSE: 0.023669, Train CE:0.150111, Train KL:5.670806, Val MSE:0.029730, Val CE:0.182531, Train ACC:0.979710, Val ACC:0.971875

Epoch 601/4000: 100%|██████████| 1/1 [00:00<00:00, 21.35it/s]

epoch: 600, beta = 0.010000, Train MSE: 0.023551, Train CE:0.149407, Train KL:5.666348, Val MSE:0.029746, Val CE:0.180181, Train ACC:0.980745, Val ACC:0.969792

Epoch 602/4000: 100%|██████████| 1/1 [00:00<00:00, 23.47it/s]

epoch: 601, beta = 0.010000, Train MSE: 0.023433, Train CE:0.148928, Train KL:5.666447, Val MSE:0.029870, Val CE:0.181158, Train ACC:0.980124, Val ACC:0.970313

Epoch 603/4000: 100%|██████████| 1/1 [00:00<00:00, 21.45it/s]

epoch: 602, beta = 0.010000, Train MSE: 0.023506, Train CE:0.148326, Train KL:5.665517, Val MSE:0.029941, Val CE:0.182797, Train ACC:0.980952, Val ACC:0.969271

Epoch 604/4000: 100%|██████████| 1/1 [00:00<00:00, 22.59it/s]

epoch: 603, beta = 0.010000, Train MSE: 0.023836, Train CE:0.148013, Train KL:5.662156, Val MSE:0.029646, Val CE:0.178025, Train ACC:0.980124, Val ACC:0.971354

Epoch 605/4000: 100%|██████████| 1/1 [00:00<00:00, 21.77it/s]

epoch: 604, beta = 0.010000, Train MSE: 0.023628, Train CE:0.147694, Train KL:5.661965, Val MSE:0.029326, Val CE:0.179218, Train ACC:0.980745, Val ACC:0.970833

Epoch 606/4000: 100%|██████████| 1/1 [00:00<00:00, 20.58it/s]

epoch: 605, beta = 0.010000, Train MSE: 0.023221, Train CE:0.146768, Train KL:5.658657, Val MSE:0.029098, Val CE:0.181129, Train ACC:0.981159, Val ACC:0.972396

Epoch 607/4000: 100%|██████████| 1/1 [00:00<00:00, 24.95it/s]

epoch: 606, beta = 0.010000, Train MSE: 0.023160, Train CE:0.146223, Train KL:5.658921, Val MSE:0.029312, Val CE:0.177353, Train ACC:0.981159, Val ACC:0.972917

Epoch 608/4000: 100%|██████████| 1/1 [00:00<00:00, 23.51it/s]

epoch: 607, beta = 0.010000, Train MSE: 0.023243, Train CE:0.145620, Train KL:5.654981, Val MSE:0.029449, Val CE:0.178643, Train ACC:0.981781, Val ACC:0.971875

Epoch 609/4000: 100%|██████████| 1/1 [00:00<00:00, 24.03it/s]

epoch: 608, beta = 0.010000, Train MSE: 0.023454, Train CE:0.145189, Train KL:5.652256, Val MSE:0.029114, Val CE:0.178564, Train ACC:0.981159, Val ACC:0.971354

Epoch 610/4000: 100%|██████████| 1/1 [00:00<00:00, 25.11it/s]

epoch: 609, beta = 0.010000, Train MSE: 0.023544, Train CE:0.144648, Train KL:5.654928, Val MSE:0.029360, Val CE:0.182030, Train ACC:0.981988, Val ACC:0.971875

Epoch 611/4000: 100%|██████████| 1/1 [00:00<00:00, 23.44it/s]

epoch: 610, beta = 0.010000, Train MSE: 0.023174, Train CE:0.144045, Train KL:5.650208, Val MSE:0.029230, Val CE:0.176034, Train ACC:0.983851, Val ACC:0.972396

Epoch 612/4000: 100%|██████████| 1/1 [00:00<00:00, 20.93it/s]

epoch: 611, beta = 0.010000, Train MSE: 0.023261, Train CE:0.143261, Train KL:5.647403, Val MSE:0.028883, Val CE:0.180060, Train ACC:0.983230, Val ACC:0.971875

Epoch 613/4000: 100%|██████████| 1/1 [00:00<00:00, 23.93it/s]

epoch: 612, beta = 0.010000, Train MSE: 0.022770, Train CE:0.142748, Train KL:5.647061, Val MSE:0.029045, Val CE:0.177835, Train ACC:0.983644, Val ACC:0.972917

Epoch 614/4000: 100%|██████████| 1/1 [00:00<00:00, 22.26it/s]

epoch: 613, beta = 0.010000, Train MSE: 0.023043, Train CE:0.142178, Train KL:5.644017, Val MSE:0.029252, Val CE:0.179944, Train ACC:0.982195, Val ACC:0.973438

Epoch 615/4000: 100%|██████████| 1/1 [00:00<00:00, 24.19it/s]

epoch: 614, beta = 0.010000, Train MSE: 0.022942, Train CE:0.141855, Train KL:5.644220, Val MSE:0.029122, Val CE:0.175105, Train ACC:0.984886, Val ACC:0.975000

Epoch 616/4000: 100%|██████████| 1/1 [00:00<00:00, 23.63it/s]

epoch: 615, beta = 0.010000, Train MSE: 0.022843, Train CE:0.141071, Train KL:5.638499, Val MSE:0.028320, Val CE:0.177000, Train ACC:0.983437, Val ACC:0.973958

Epoch 617/4000: 100%|██████████| 1/1 [00:00<00:00, 24.11it/s]

epoch: 616, beta = 0.010000, Train MSE: 0.022723, Train CE:0.140592, Train KL:5.639903, Val MSE:0.028463, Val CE:0.174950, Train ACC:0.983023, Val ACC:0.975521

Epoch 618/4000: 100%|██████████| 1/1 [00:00<00:00, 25.09it/s]

epoch: 617, beta = 0.010000, Train MSE: 0.022621, Train CE:0.139977, Train KL:5.635847, Val MSE:0.028443, Val CE:0.169182, Train ACC:0.984058, Val ACC:0.975521

Epoch 619/4000: 100%|██████████| 1/1 [00:00<00:00, 23.48it/s]

epoch: 618, beta = 0.010000, Train MSE: 0.022694, Train CE:0.139867, Train KL:5.631057, Val MSE:0.028557, Val CE:0.172341, Train ACC:0.983023, Val ACC:0.972917

Epoch 620/4000: 100%|██████████| 1/1 [00:00<00:00, 23.34it/s]

epoch: 619, beta = 0.010000, Train MSE: 0.022530, Train CE:0.139701, Train KL:5.627361, Val MSE:0.028545, Val CE:0.175137, Train ACC:0.982609, Val ACC:0.971354

Epoch 621/4000: 100%|██████████| 1/1 [00:00<00:00, 23.69it/s]

epoch: 620, beta = 0.010000, Train MSE: 0.022778, Train CE:0.139460, Train KL:5.621967, Val MSE:0.029171, Val CE:0.167085, Train ACC:0.983230, Val ACC:0.974479

Epoch 622/4000: 100%|██████████| 1/1 [00:00<00:00, 22.37it/s]

epoch: 621, beta = 0.010000, Train MSE: 0.023268, Train CE:0.138465, Train KL:5.617010, Val MSE:0.028936, Val CE:0.169650, Train ACC:0.983437, Val ACC:0.975521

Epoch 623/4000: 100%|██████████| 1/1 [00:00<00:00, 24.10it/s]

epoch: 622, beta = 0.010000, Train MSE: 0.023299, Train CE:0.138179, Train KL:5.614358, Val MSE:0.029176, Val CE:0.169000, Train ACC:0.983230, Val ACC:0.975000

Epoch 624/4000: 100%|██████████| 1/1 [00:00<00:00, 22.65it/s]

epoch: 623, beta = 0.010000, Train MSE: 0.023434, Train CE:0.137598, Train KL:5.614308, Val MSE:0.029224, Val CE:0.175410, Train ACC:0.983023, Val ACC:0.976042

Epoch 625/4000: 100%|██████████| 1/1 [00:00<00:00, 23.59it/s]

epoch: 624, beta = 0.010000, Train MSE: 0.023149, Train CE:0.136880, Train KL:5.612696, Val MSE:0.028796, Val CE:0.171667, Train ACC:0.984058, Val ACC:0.976563

Epoch 626/4000: 100%|██████████| 1/1 [00:00<00:00, 25.55it/s]

epoch: 625, beta = 0.010000, Train MSE: 0.023187, Train CE:0.135705, Train KL:5.607979, Val MSE:0.028218, Val CE:0.174501, Train ACC:0.985300, Val ACC:0.974479

Epoch 627/4000: 100%|██████████| 1/1 [00:00<00:00, 23.50it/s]

epoch: 626, beta = 0.010000, Train MSE: 0.022507, Train CE:0.135308, Train KL:5.609762, Val MSE:0.028334, Val CE:0.172876, Train ACC:0.985714, Val ACC:0.974479

Epoch 628/4000: 100%|██████████| 1/1 [00:00<00:00, 24.10it/s]

epoch: 627, beta = 0.010000, Train MSE: 0.022664, Train CE:0.134891, Train KL:5.608432, Val MSE:0.028328, Val CE:0.171816, Train ACC:0.986128, Val ACC:0.976042

Epoch 629/4000: 100%|██████████| 1/1 [00:00<00:00, 21.13it/s]

epoch: 628, beta = 0.010000, Train MSE: 0.022756, Train CE:0.134266, Train KL:5.602662, Val MSE:0.028829, Val CE:0.176983, Train ACC:0.986128, Val ACC:0.973438

Epoch 630/4000: 100%|██████████| 1/1 [00:00<00:00, 22.28it/s]

epoch: 629, beta = 0.010000, Train MSE: 0.022836, Train CE:0.133899, Train KL:5.604047, Val MSE:0.028295, Val CE:0.172054, Train ACC:0.985093, Val ACC:0.975000

Epoch 631/4000: 100%|██████████| 1/1 [00:00<00:00, 20.67it/s]

epoch: 630, beta = 0.007000, Train MSE: 0.022625, Train CE:0.133624, Train KL:5.601587, Val MSE:0.028524, Val CE:0.171873, Train ACC:0.987371, Val ACC:0.976042

Epoch 632/4000: 100%|██████████| 1/1 [00:00<00:00, 21.86it/s]

Learning rate updated: 0.00095
epoch: 631, beta = 0.007000, Train MSE: 0.022570, Train CE:0.133598, Train KL:5.600327, Val MSE:0.028313, Val CE:0.169171, Train ACC:0.984472, Val ACC:0.977083

Epoch 633/4000: 100%|██████████| 1/1 [00:00<00:00, 20.99it/s]

epoch: 632, beta = 0.007000, Train MSE: 0.022762, Train CE:0.132274, Train KL:5.608560, Val MSE:0.027801, Val CE:0.169925, Train ACC:0.986749, Val ACC:0.975521

Epoch 634/4000: 100%|██████████| 1/1 [00:00<00:00, 21.09it/s]

epoch: 633, beta = 0.007000, Train MSE: 0.022149, Train CE:0.132070, Train KL:5.618167, Val MSE:0.027673, Val CE:0.167391, Train ACC:0.986128, Val ACC:0.978125

Epoch 635/4000: 100%|██████████| 1/1 [00:00<00:00, 20.67it/s]

epoch: 634, beta = 0.007000, Train MSE: 0.021929, Train CE:0.131048, Train KL:5.633182, Val MSE:0.027975, Val CE:0.165163, Train ACC:0.986335, Val ACC:0.977083

Epoch 636/4000: 100%|██████████| 1/1 [00:00<00:00, 19.03it/s]

epoch: 635, beta = 0.007000, Train MSE: 0.021606, Train CE:0.130493, Train KL:5.652820, Val MSE:0.028234, Val CE:0.165478, Train ACC:0.987578, Val ACC:0.976042

Epoch 637/4000: 100%|██████████| 1/1 [00:00<00:00, 20.17it/s]

epoch: 636, beta = 0.007000, Train MSE: 0.021576, Train CE:0.130096, Train KL:5.673967, Val MSE:0.027942, Val CE:0.167694, Train ACC:0.986128, Val ACC:0.975521

Epoch 638/4000: 100%|██████████| 1/1 [00:00<00:00, 18.49it/s]

epoch: 637, beta = 0.007000, Train MSE: 0.021375, Train CE:0.129958, Train KL:5.701262, Val MSE:0.027639, Val CE:0.168970, Train ACC:0.986749, Val ACC:0.975521

Epoch 639/4000: 100%|██████████| 1/1 [00:00<00:00, 21.84it/s]

epoch: 638, beta = 0.007000, Train MSE: 0.021083, Train CE:0.129297, Train KL:5.724440, Val MSE:0.027470, Val CE:0.159932, Train ACC:0.986957, Val ACC:0.976563

Epoch 640/4000: 100%|██████████| 1/1 [00:00<00:00, 22.28it/s]

epoch: 639, beta = 0.007000, Train MSE: 0.021100, Train CE:0.128352, Train KL:5.744414, Val MSE:0.026919, Val CE:0.161865, Train ACC:0.987164, Val ACC:0.976563

Epoch 641/4000: 100%|██████████| 1/1 [00:00<00:00, 21.57it/s]

epoch: 640, beta = 0.007000, Train MSE: 0.020761, Train CE:0.128105, Train KL:5.766740, Val MSE:0.026910, Val CE:0.160366, Train ACC:0.986957, Val ACC:0.978646

Epoch 642/4000: 100%|██████████| 1/1 [00:00<00:00, 23.83it/s]

epoch: 641, beta = 0.007000, Train MSE: 0.020785, Train CE:0.127386, Train KL:5.783015, Val MSE:0.026317, Val CE:0.164451, Train ACC:0.988199, Val ACC:0.975000

Epoch 643/4000: 100%|██████████| 1/1 [00:00<00:00, 23.10it/s]

epoch: 642, beta = 0.007000, Train MSE: 0.020350, Train CE:0.126746, Train KL:5.802625, Val MSE:0.026498, Val CE:0.163500, Train ACC:0.987992, Val ACC:0.976042

Epoch 644/4000: 100%|██████████| 1/1 [00:00<00:00, 23.90it/s]

epoch: 643, beta = 0.007000, Train MSE: 0.020398, Train CE:0.126184, Train KL:5.814354, Val MSE:0.026466, Val CE:0.161212, Train ACC:0.989441, Val ACC:0.977083

Epoch 645/4000: 100%|██████████| 1/1 [00:00<00:00, 24.21it/s]

epoch: 644, beta = 0.007000, Train MSE: 0.020298, Train CE:0.125768, Train KL:5.822460, Val MSE:0.026473, Val CE:0.162739, Train ACC:0.989441, Val ACC:0.977604

Epoch 646/4000: 100%|██████████| 1/1 [00:00<00:00, 22.93it/s]

epoch: 645, beta = 0.007000, Train MSE: 0.020582, Train CE:0.125318, Train KL:5.834275, Val MSE:0.026355, Val CE:0.159721, Train ACC:0.988613, Val ACC:0.976042

Epoch 647/4000: 100%|██████████| 1/1 [00:00<00:00, 25.70it/s]

epoch: 646, beta = 0.007000, Train MSE: 0.020065, Train CE:0.124648, Train KL:5.836878, Val MSE:0.026027, Val CE:0.161230, Train ACC:0.988820, Val ACC:0.976042

Epoch 648/4000: 100%|██████████| 1/1 [00:00<00:00, 20.56it/s]

epoch: 647, beta = 0.007000, Train MSE: 0.019972, Train CE:0.124317, Train KL:5.841204, Val MSE:0.026397, Val CE:0.162629, Train ACC:0.989234, Val ACC:0.979167

Epoch 649/4000: 100%|██████████| 1/1 [00:00<00:00, 24.64it/s]

epoch: 648, beta = 0.007000, Train MSE: 0.019892, Train CE:0.123673, Train KL:5.844535, Val MSE:0.026727, Val CE:0.159101, Train ACC:0.989027, Val ACC:0.977604

Epoch 650/4000: 100%|██████████| 1/1 [00:00<00:00, 23.29it/s]

epoch: 649, beta = 0.007000, Train MSE: 0.019983, Train CE:0.123276, Train KL:5.840513, Val MSE:0.026831, Val CE:0.157517, Train ACC:0.988613, Val ACC:0.978125

Epoch 651/4000: 100%|██████████| 1/1 [00:00<00:00, 20.70it/s]

epoch: 650, beta = 0.007000, Train MSE: 0.019862, Train CE:0.122849, Train KL:5.838820, Val MSE:0.026604, Val CE:0.159445, Train ACC:0.989027, Val ACC:0.978646

Epoch 652/4000: 100%|██████████| 1/1 [00:00<00:00, 20.94it/s]

epoch: 651, beta = 0.007000, Train MSE: 0.019892, Train CE:0.122258, Train KL:5.833053, Val MSE:0.026493, Val CE:0.162681, Train ACC:0.989027, Val ACC:0.978646

Epoch 653/4000: 100%|██████████| 1/1 [00:00<00:00, 20.21it/s]

epoch: 652, beta = 0.007000, Train MSE: 0.019978, Train CE:0.122002, Train KL:5.825641, Val MSE:0.026424, Val CE:0.155665, Train ACC:0.988613, Val ACC:0.978125

Epoch 654/4000: 100%|██████████| 1/1 [00:00<00:00, 23.05it/s]

epoch: 653, beta = 0.007000, Train MSE: 0.019824, Train CE:0.121315, Train KL:5.816534, Val MSE:0.026316, Val CE:0.157423, Train ACC:0.990062, Val ACC:0.978646

Epoch 655/4000: 100%|██████████| 1/1 [00:00<00:00, 19.91it/s]

epoch: 654, beta = 0.007000, Train MSE: 0.019834, Train CE:0.120971, Train KL:5.809587, Val MSE:0.026474, Val CE:0.157570, Train ACC:0.989855, Val ACC:0.978646

Epoch 656/4000: 100%|██████████| 1/1 [00:00<00:00, 22.61it/s]

epoch: 655, beta = 0.007000, Train MSE: 0.019893, Train CE:0.120196, Train KL:5.802275, Val MSE:0.026553, Val CE:0.159668, Train ACC:0.991097, Val ACC:0.979688

Epoch 657/4000: 100%|██████████| 1/1 [00:00<00:00, 21.35it/s]

epoch: 656, beta = 0.007000, Train MSE: 0.019902, Train CE:0.119760, Train KL:5.793396, Val MSE:0.026601, Val CE:0.156748, Train ACC:0.990683, Val ACC:0.978125

Epoch 658/4000: 100%|██████████| 1/1 [00:00<00:00, 20.39it/s]

epoch: 657, beta = 0.007000, Train MSE: 0.019951, Train CE:0.119404, Train KL:5.783785, Val MSE:0.026480, Val CE:0.160129, Train ACC:0.989648, Val ACC:0.978646

Epoch 659/4000: 100%|██████████| 1/1 [00:00<00:00, 23.39it/s]

epoch: 658, beta = 0.007000, Train MSE: 0.019975, Train CE:0.119061, Train KL:5.780719, Val MSE:0.026129, Val CE:0.157700, Train ACC:0.990890, Val ACC:0.978646

Epoch 660/4000: 100%|██████████| 1/1 [00:00<00:00, 22.00it/s]

epoch: 659, beta = 0.007000, Train MSE: 0.020193, Train CE:0.118636, Train KL:5.771241, Val MSE:0.026262, Val CE:0.158581, Train ACC:0.991511, Val ACC:0.980208

Epoch 661/4000: 100%|██████████| 1/1 [00:00<00:00, 26.02it/s]

epoch: 660, beta = 0.007000, Train MSE: 0.019977, Train CE:0.118062, Train KL:5.768209, Val MSE:0.026766, Val CE:0.159311, Train ACC:0.991097, Val ACC:0.978646

Epoch 662/4000: 100%|██████████| 1/1 [00:00<00:00, 23.11it/s]

epoch: 661, beta = 0.007000, Train MSE: 0.019942, Train CE:0.117521, Train KL:5.767816, Val MSE:0.026874, Val CE:0.152874, Train ACC:0.990476, Val ACC:0.978125

Epoch 663/4000: 100%|██████████| 1/1 [00:00<00:00, 23.99it/s]

epoch: 662, beta = 0.007000, Train MSE: 0.020024, Train CE:0.116949, Train KL:5.766704, Val MSE:0.027103, Val CE:0.158064, Train ACC:0.990890, Val ACC:0.979167

Epoch 664/4000: 100%|██████████| 1/1 [00:00<00:00, 21.11it/s]

epoch: 663, beta = 0.007000, Train MSE: 0.020422, Train CE:0.116911, Train KL:5.767806, Val MSE:0.026523, Val CE:0.151550, Train ACC:0.991718, Val ACC:0.979167

Epoch 665/4000: 100%|██████████| 1/1 [00:00<00:00, 25.63it/s]

epoch: 664, beta = 0.007000, Train MSE: 0.020642, Train CE:0.116808, Train KL:5.767181, Val MSE:0.026717, Val CE:0.160642, Train ACC:0.990476, Val ACC:0.979688

Epoch 666/4000: 100%|██████████| 1/1 [00:00<00:00, 23.52it/s]

epoch: 665, beta = 0.007000, Train MSE: 0.020378, Train CE:0.116937, Train KL:5.772137, Val MSE:0.027275, Val CE:0.143669, Train ACC:0.989234, Val ACC:0.981250

Epoch 667/4000: 100%|██████████| 1/1 [00:00<00:00, 24.77it/s]

epoch: 666, beta = 0.007000, Train MSE: 0.020775, Train CE:0.117147, Train KL:5.769281, Val MSE:0.027883, Val CE:0.162729, Train ACC:0.989027, Val ACC:0.977083

Epoch 668/4000: 100%|██████████| 1/1 [00:00<00:00, 24.89it/s]

epoch: 667, beta = 0.007000, Train MSE: 0.021267, Train CE:0.116947, Train KL:5.775761, Val MSE:0.027363, Val CE:0.148465, Train ACC:0.989441, Val ACC:0.980208

Epoch 669/4000: 100%|██████████| 1/1 [00:00<00:00, 24.01it/s]

epoch: 668, beta = 0.007000, Train MSE: 0.021367, Train CE:0.115986, Train KL:5.777852, Val MSE:0.026915, Val CE:0.150418, Train ACC:0.990890, Val ACC:0.978646

Epoch 670/4000: 100%|██████████| 1/1 [00:00<00:00, 20.56it/s]

epoch: 669, beta = 0.007000, Train MSE: 0.020306, Train CE:0.115228, Train KL:5.778082, Val MSE:0.025484, Val CE:0.146740, Train ACC:0.989648, Val ACC:0.979167

Epoch 671/4000: 100%|██████████| 1/1 [00:00<00:00, 23.01it/s]

epoch: 670, beta = 0.007000, Train MSE: 0.019690, Train CE:0.113870, Train KL:5.785317, Val MSE:0.025945, Val CE:0.145126, Train ACC:0.990476, Val ACC:0.980208

Epoch 672/4000: 100%|██████████| 1/1 [00:00<00:00, 22.85it/s]

epoch: 671, beta = 0.007000, Train MSE: 0.020252, Train CE:0.113841, Train KL:5.787083, Val MSE:0.026854, Val CE:0.152070, Train ACC:0.990890, Val ACC:0.979167

Epoch 673/4000: 100%|██████████| 1/1 [00:00<00:00, 20.44it/s]

epoch: 672, beta = 0.007000, Train MSE: 0.020358, Train CE:0.113710, Train KL:5.787286, Val MSE:0.026255, Val CE:0.142770, Train ACC:0.991511, Val ACC:0.982292

Epoch 674/4000: 100%|██████████| 1/1 [00:00<00:00, 22.16it/s]

epoch: 673, beta = 0.007000, Train MSE: 0.020168, Train CE:0.112874, Train KL:5.787285, Val MSE:0.026079, Val CE:0.149359, Train ACC:0.991097, Val ACC:0.980729

Epoch 675/4000: 100%|██████████| 1/1 [00:00<00:00, 18.71it/s]

epoch: 674, beta = 0.007000, Train MSE: 0.019625, Train CE:0.112053, Train KL:5.787126, Val MSE:0.026440, Val CE:0.149502, Train ACC:0.992547, Val ACC:0.981771

Epoch 676/4000: 100%|██████████| 1/1 [00:00<00:00, 21.06it/s]

epoch: 675, beta = 0.007000, Train MSE: 0.019565, Train CE:0.111135, Train KL:5.790739, Val MSE:0.026125, Val CE:0.145822, Train ACC:0.992547, Val ACC:0.982813

Epoch 677/4000: 100%|██████████| 1/1 [00:00<00:00, 23.91it/s]

epoch: 676, beta = 0.007000, Train MSE: 0.019369, Train CE:0.110824, Train KL:5.788893, Val MSE:0.025881, Val CE:0.148491, Train ACC:0.992547, Val ACC:0.979688

Epoch 678/4000: 100%|██████████| 1/1 [00:00<00:00, 20.88it/s]

epoch: 677, beta = 0.007000, Train MSE: 0.019459, Train CE:0.110577, Train KL:5.786550, Val MSE:0.025369, Val CE:0.149708, Train ACC:0.993375, Val ACC:0.981250

Epoch 679/4000: 100%|██████████| 1/1 [00:00<00:00, 23.83it/s]

epoch: 678, beta = 0.007000, Train MSE: 0.019464, Train CE:0.110131, Train KL:5.788367, Val MSE:0.025575, Val CE:0.146930, Train ACC:0.992961, Val ACC:0.980729

Epoch 680/4000: 100%|██████████| 1/1 [00:00<00:00, 20.61it/s]

epoch: 679, beta = 0.007000, Train MSE: 0.019218, Train CE:0.109546, Train KL:5.784348, Val MSE:0.025837, Val CE:0.146358, Train ACC:0.993582, Val ACC:0.982813

Epoch 681/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 680, beta = 0.007000, Train MSE: 0.019056, Train CE:0.108859, Train KL:5.783792, Val MSE:0.025714, Val CE:0.147605, Train ACC:0.992754, Val ACC:0.980729

Epoch 682/4000: 100%|██████████| 1/1 [00:00<00:00, 22.44it/s]

epoch: 681, beta = 0.007000, Train MSE: 0.019035, Train CE:0.108651, Train KL:5.782509, Val MSE:0.025563, Val CE:0.146443, Train ACC:0.993582, Val ACC:0.982292

Epoch 683/4000: 100%|██████████| 1/1 [00:00<00:00, 23.51it/s]

epoch: 682, beta = 0.004900, Train MSE: 0.019243, Train CE:0.108039, Train KL:5.778428, Val MSE:0.025857, Val CE:0.145342, Train ACC:0.992754, Val ACC:0.981250

Epoch 684/4000: 100%|██████████| 1/1 [00:00<00:00, 24.01it/s]

Learning rate updated: 0.0009025
epoch: 683, beta = 0.004900, Train MSE: 0.019167, Train CE:0.107598, Train KL:5.778971, Val MSE:0.025292, Val CE:0.144585, Train ACC:0.993789, Val ACC:0.982813

Epoch 685/4000: 100%|██████████| 1/1 [00:00<00:00, 21.55it/s]

epoch: 684, beta = 0.004900, Train MSE: 0.018897, Train CE:0.107088, Train KL:5.779439, Val MSE:0.024941, Val CE:0.145460, Train ACC:0.993996, Val ACC:0.982292

Epoch 686/4000: 100%|██████████| 1/1 [00:00<00:00, 23.78it/s]

epoch: 685, beta = 0.004900, Train MSE: 0.018841, Train CE:0.106839, Train KL:5.787990, Val MSE:0.025219, Val CE:0.147270, Train ACC:0.993789, Val ACC:0.979688

Epoch 687/4000: 100%|██████████| 1/1 [00:00<00:00, 23.42it/s]

epoch: 686, beta = 0.004900, Train MSE: 0.018771, Train CE:0.106232, Train KL:5.803259, Val MSE:0.025056, Val CE:0.143600, Train ACC:0.993168, Val ACC:0.981250

Epoch 688/4000: 100%|██████████| 1/1 [00:00<00:00, 23.34it/s]

epoch: 687, beta = 0.004900, Train MSE: 0.018690, Train CE:0.105966, Train KL:5.814840, Val MSE:0.024752, Val CE:0.148596, Train ACC:0.993582, Val ACC:0.982292

Epoch 689/4000: 100%|██████████| 1/1 [00:00<00:00, 24.02it/s]

epoch: 688, beta = 0.004900, Train MSE: 0.018517, Train CE:0.105623, Train KL:5.832385, Val MSE:0.024470, Val CE:0.145641, Train ACC:0.993168, Val ACC:0.981771

Epoch 690/4000: 100%|██████████| 1/1 [00:00<00:00, 23.73it/s]

epoch: 689, beta = 0.004900, Train MSE: 0.018268, Train CE:0.105146, Train KL:5.850993, Val MSE:0.024698, Val CE:0.142646, Train ACC:0.993996, Val ACC:0.981250

Epoch 691/4000: 100%|██████████| 1/1 [00:00<00:00, 22.31it/s]

epoch: 690, beta = 0.004900, Train MSE: 0.018557, Train CE:0.104922, Train KL:5.869256, Val MSE:0.024566, Val CE:0.143427, Train ACC:0.993996, Val ACC:0.981771

Epoch 692/4000: 100%|██████████| 1/1 [00:00<00:00, 23.55it/s]

epoch: 691, beta = 0.004900, Train MSE: 0.018410, Train CE:0.104397, Train KL:5.892424, Val MSE:0.024759, Val CE:0.144839, Train ACC:0.994617, Val ACC:0.981250

Epoch 693/4000: 100%|██████████| 1/1 [00:00<00:00, 26.04it/s]

epoch: 692, beta = 0.004900, Train MSE: 0.018333, Train CE:0.103823, Train KL:5.909978, Val MSE:0.024111, Val CE:0.140210, Train ACC:0.995445, Val ACC:0.982813

Epoch 694/4000: 100%|██████████| 1/1 [00:00<00:00, 25.73it/s]

epoch: 693, beta = 0.004900, Train MSE: 0.018086, Train CE:0.103215, Train KL:5.931318, Val MSE:0.023815, Val CE:0.142229, Train ACC:0.994824, Val ACC:0.983333

Epoch 695/4000: 100%|██████████| 1/1 [00:00<00:00, 24.59it/s]

epoch: 694, beta = 0.004900, Train MSE: 0.018008, Train CE:0.102888, Train KL:5.949850, Val MSE:0.023721, Val CE:0.137465, Train ACC:0.995238, Val ACC:0.983333

Epoch 696/4000: 100%|██████████| 1/1 [00:00<00:00, 25.49it/s]

epoch: 695, beta = 0.004900, Train MSE: 0.017980, Train CE:0.102387, Train KL:5.962894, Val MSE:0.023463, Val CE:0.142049, Train ACC:0.996066, Val ACC:0.983854

Epoch 697/4000: 100%|██████████| 1/1 [00:00<00:00, 22.41it/s]

epoch: 696, beta = 0.004900, Train MSE: 0.017674, Train CE:0.101911, Train KL:5.979390, Val MSE:0.023524, Val CE:0.143481, Train ACC:0.995652, Val ACC:0.982813

Epoch 698/4000: 100%|██████████| 1/1 [00:00<00:00, 24.02it/s]

epoch: 697, beta = 0.004900, Train MSE: 0.017681, Train CE:0.101719, Train KL:5.993668, Val MSE:0.023835, Val CE:0.136721, Train ACC:0.995445, Val ACC:0.983333

Epoch 699/4000: 100%|██████████| 1/1 [00:00<00:00, 23.48it/s]

epoch: 698, beta = 0.004900, Train MSE: 0.017537, Train CE:0.101147, Train KL:6.003209, Val MSE:0.023429, Val CE:0.139881, Train ACC:0.996066, Val ACC:0.983333

Epoch 700/4000: 100%|██████████| 1/1 [00:00<00:00, 23.41it/s]

epoch: 699, beta = 0.004900, Train MSE: 0.017567, Train CE:0.100731, Train KL:6.016384, Val MSE:0.023147, Val CE:0.138125, Train ACC:0.994824, Val ACC:0.983854

Epoch 701/4000: 100%|██████████| 1/1 [00:00<00:00, 24.03it/s]

epoch: 700, beta = 0.004900, Train MSE: 0.017541, Train CE:0.100164, Train KL:6.025141, Val MSE:0.023174, Val CE:0.139262, Train ACC:0.996480, Val ACC:0.982813

Epoch 702/4000: 100%|██████████| 1/1 [00:00<00:00, 23.47it/s]

epoch: 701, beta = 0.004900, Train MSE: 0.017444, Train CE:0.099815, Train KL:6.030531, Val MSE:0.023149, Val CE:0.138364, Train ACC:0.997308, Val ACC:0.983333

Epoch 703/4000: 100%|██████████| 1/1 [00:00<00:00, 24.34it/s]

epoch: 702, beta = 0.004900, Train MSE: 0.017305, Train CE:0.099490, Train KL:6.035422, Val MSE:0.022930, Val CE:0.136850, Train ACC:0.995652, Val ACC:0.983854

Epoch 704/4000: 100%|██████████| 1/1 [00:00<00:00, 23.64it/s]

epoch: 703, beta = 0.004900, Train MSE: 0.017343, Train CE:0.099016, Train KL:6.037477, Val MSE:0.022932, Val CE:0.138218, Train ACC:0.996687, Val ACC:0.983333

Epoch 705/4000: 100%|██████████| 1/1 [00:00<00:00, 21.91it/s]

epoch: 704, beta = 0.004900, Train MSE: 0.017183, Train CE:0.098551, Train KL:6.040143, Val MSE:0.023058, Val CE:0.137989, Train ACC:0.997516, Val ACC:0.983333

Epoch 706/4000: 100%|██████████| 1/1 [00:00<00:00, 24.44it/s]

epoch: 705, beta = 0.004900, Train MSE: 0.017140, Train CE:0.098148, Train KL:6.041584, Val MSE:0.023095, Val CE:0.136062, Train ACC:0.996894, Val ACC:0.984375

Epoch 707/4000: 100%|██████████| 1/1 [00:00<00:00, 22.56it/s]

epoch: 706, beta = 0.004900, Train MSE: 0.017183, Train CE:0.097829, Train KL:6.038948, Val MSE:0.023097, Val CE:0.139585, Train ACC:0.997308, Val ACC:0.982813

Epoch 708/4000: 100%|██████████| 1/1 [00:00<00:00, 20.50it/s]

epoch: 707, beta = 0.004900, Train MSE: 0.017018, Train CE:0.097347, Train KL:6.038198, Val MSE:0.023131, Val CE:0.137458, Train ACC:0.996894, Val ACC:0.984896

Epoch 709/4000: 100%|██████████| 1/1 [00:00<00:00, 23.89it/s]

epoch: 708, beta = 0.004900, Train MSE: 0.017080, Train CE:0.096993, Train KL:6.035205, Val MSE:0.023850, Val CE:0.139668, Train ACC:0.997101, Val ACC:0.981771

Epoch 710/4000: 100%|██████████| 1/1 [00:00<00:00, 22.99it/s]

epoch: 709, beta = 0.004900, Train MSE: 0.017437, Train CE:0.097036, Train KL:6.028318, Val MSE:0.023888, Val CE:0.134976, Train ACC:0.996273, Val ACC:0.981250

Epoch 711/4000: 100%|██████████| 1/1 [00:00<00:00, 18.25it/s]

epoch: 710, beta = 0.004900, Train MSE: 0.017910, Train CE:0.097253, Train KL:6.026223, Val MSE:0.024186, Val CE:0.140509, Train ACC:0.996066, Val ACC:0.982292

Epoch 712/4000: 100%|██████████| 1/1 [00:00<00:00, 19.35it/s]

epoch: 711, beta = 0.004900, Train MSE: 0.018157, Train CE:0.097228, Train KL:6.018823, Val MSE:0.024234, Val CE:0.131494, Train ACC:0.996066, Val ACC:0.985938

Epoch 713/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 712, beta = 0.004900, Train MSE: 0.018213, Train CE:0.096340, Train KL:6.017087, Val MSE:0.023544, Val CE:0.140604, Train ACC:0.996480, Val ACC:0.982292

Epoch 714/4000: 100%|██████████| 1/1 [00:00<00:00, 24.01it/s]

epoch: 713, beta = 0.004900, Train MSE: 0.017629, Train CE:0.095867, Train KL:6.015798, Val MSE:0.023129, Val CE:0.130885, Train ACC:0.996480, Val ACC:0.985938

Epoch 715/4000: 100%|██████████| 1/1 [00:00<00:00, 22.27it/s]

epoch: 714, beta = 0.004900, Train MSE: 0.017424, Train CE:0.094751, Train KL:6.009927, Val MSE:0.023026, Val CE:0.131077, Train ACC:0.997308, Val ACC:0.985417

Epoch 716/4000: 100%|██████████| 1/1 [00:00<00:00, 22.26it/s]

epoch: 715, beta = 0.004900, Train MSE: 0.017224, Train CE:0.094466, Train KL:6.009540, Val MSE:0.023458, Val CE:0.135049, Train ACC:0.997308, Val ACC:0.983854

Epoch 717/4000: 100%|██████████| 1/1 [00:00<00:00, 23.28it/s]

epoch: 716, beta = 0.004900, Train MSE: 0.017426, Train CE:0.094265, Train KL:6.006573, Val MSE:0.023278, Val CE:0.127465, Train ACC:0.996894, Val ACC:0.984896

Epoch 718/4000: 100%|██████████| 1/1 [00:00<00:00, 21.90it/s]

epoch: 717, beta = 0.004900, Train MSE: 0.017680, Train CE:0.094265, Train KL:6.003946, Val MSE:0.023381, Val CE:0.133151, Train ACC:0.996894, Val ACC:0.983854

Epoch 719/4000: 100%|██████████| 1/1 [00:00<00:00, 20.00it/s]

epoch: 718, beta = 0.004900, Train MSE: 0.017494, Train CE:0.093774, Train KL:6.004827, Val MSE:0.022751, Val CE:0.131032, Train ACC:0.996480, Val ACC:0.985417

Epoch 720/4000: 100%|██████████| 1/1 [00:00<00:00, 21.38it/s]

epoch: 719, beta = 0.004900, Train MSE: 0.017133, Train CE:0.092875, Train KL:6.005343, Val MSE:0.022849, Val CE:0.129377, Train ACC:0.997516, Val ACC:0.983333

Epoch 721/4000: 100%|██████████| 1/1 [00:00<00:00, 20.52it/s]

epoch: 720, beta = 0.004900, Train MSE: 0.017056, Train CE:0.092455, Train KL:6.003371, Val MSE:0.023031, Val CE:0.131258, Train ACC:0.997930, Val ACC:0.985417

Epoch 722/4000: 100%|██████████| 1/1 [00:00<00:00, 23.98it/s]

epoch: 721, beta = 0.004900, Train MSE: 0.017379, Train CE:0.092379, Train KL:6.003554, Val MSE:0.022964, Val CE:0.127683, Train ACC:0.997308, Val ACC:0.987500

Epoch 723/4000: 100%|██████████| 1/1 [00:00<00:00, 22.14it/s]

epoch: 722, beta = 0.004900, Train MSE: 0.017321, Train CE:0.092029, Train KL:6.001146, Val MSE:0.022746, Val CE:0.129979, Train ACC:0.997516, Val ACC:0.984896

Epoch 724/4000: 100%|██████████| 1/1 [00:00<00:00, 19.45it/s]

epoch: 723, beta = 0.004900, Train MSE: 0.017108, Train CE:0.091629, Train KL:6.000628, Val MSE:0.022844, Val CE:0.127107, Train ACC:0.997930, Val ACC:0.983854

Epoch 725/4000: 100%|██████████| 1/1 [00:00<00:00, 22.56it/s]

epoch: 724, beta = 0.004900, Train MSE: 0.017137, Train CE:0.091070, Train KL:6.005803, Val MSE:0.022599, Val CE:0.126936, Train ACC:0.997930, Val ACC:0.985417

Epoch 726/4000: 100%|██████████| 1/1 [00:00<00:00, 25.34it/s]

epoch: 725, beta = 0.004900, Train MSE: 0.016952, Train CE:0.090611, Train KL:6.006314, Val MSE:0.022650, Val CE:0.132214, Train ACC:0.997723, Val ACC:0.985417

Epoch 727/4000: 100%|██████████| 1/1 [00:00<00:00, 22.56it/s]

epoch: 726, beta = 0.004900, Train MSE: 0.016830, Train CE:0.090355, Train KL:6.009793, Val MSE:0.022433, Val CE:0.128693, Train ACC:0.997723, Val ACC:0.984896

Epoch 728/4000: 100%|██████████| 1/1 [00:00<00:00, 20.87it/s]

epoch: 727, beta = 0.004900, Train MSE: 0.016813, Train CE:0.089948, Train KL:6.010895, Val MSE:0.022822, Val CE:0.126693, Train ACC:0.998137, Val ACC:0.985417

Epoch 729/4000: 100%|██████████| 1/1 [00:00<00:00, 25.79it/s]

epoch: 728, beta = 0.004900, Train MSE: 0.017058, Train CE:0.089744, Train KL:6.010128, Val MSE:0.022660, Val CE:0.131831, Train ACC:0.997930, Val ACC:0.984896

Epoch 730/4000: 100%|██████████| 1/1 [00:00<00:00, 20.38it/s]

epoch: 729, beta = 0.004900, Train MSE: 0.016977, Train CE:0.089710, Train KL:6.016972, Val MSE:0.022913, Val CE:0.128564, Train ACC:0.997930, Val ACC:0.985938

Epoch 731/4000: 100%|██████████| 1/1 [00:00<00:00, 21.46it/s]

epoch: 730, beta = 0.004900, Train MSE: 0.017016, Train CE:0.088915, Train KL:6.015496, Val MSE:0.022645, Val CE:0.123907, Train ACC:0.998137, Val ACC:0.987500

Epoch 732/4000: 100%|██████████| 1/1 [00:00<00:00, 21.97it/s]

epoch: 731, beta = 0.004900, Train MSE: 0.016705, Train CE:0.088472, Train KL:6.019853, Val MSE:0.022254, Val CE:0.127960, Train ACC:0.998137, Val ACC:0.985938

Epoch 733/4000: 100%|██████████| 1/1 [00:00<00:00, 21.17it/s]

epoch: 732, beta = 0.004900, Train MSE: 0.016830, Train CE:0.088113, Train KL:6.024765, Val MSE:0.022565, Val CE:0.128437, Train ACC:0.998344, Val ACC:0.987500

Epoch 734/4000: 100%|██████████| 1/1 [00:00<00:00, 22.90it/s]

epoch: 733, beta = 0.004900, Train MSE: 0.017010, Train CE:0.087850, Train KL:6.023672, Val MSE:0.022518, Val CE:0.126668, Train ACC:0.998344, Val ACC:0.986458

Epoch 735/4000: 100%|██████████| 1/1 [00:00<00:00, 21.48it/s]

epoch: 734, beta = 0.004900, Train MSE: 0.016977, Train CE:0.087515, Train KL:6.027944, Val MSE:0.022682, Val CE:0.128760, Train ACC:0.997723, Val ACC:0.985938

Epoch 736/4000: 100%|██████████| 1/1 [00:00<00:00, 24.17it/s]

epoch: 735, beta = 0.004900, Train MSE: 0.016758, Train CE:0.087055, Train KL:6.027544, Val MSE:0.022567, Val CE:0.125277, Train ACC:0.998344, Val ACC:0.986458

Epoch 737/4000: 100%|██████████| 1/1 [00:00<00:00, 22.81it/s]

epoch: 736, beta = 0.004900, Train MSE: 0.016744, Train CE:0.086785, Train KL:6.029965, Val MSE:0.022323, Val CE:0.131462, Train ACC:0.997930, Val ACC:0.986979

Epoch 738/4000: 100%|██████████| 1/1 [00:00<00:00, 22.34it/s]

epoch: 737, beta = 0.004900, Train MSE: 0.016755, Train CE:0.086763, Train KL:6.032926, Val MSE:0.022532, Val CE:0.125555, Train ACC:0.997516, Val ACC:0.988021

Epoch 739/4000: 100%|██████████| 1/1 [00:00<00:00, 21.32it/s]

epoch: 738, beta = 0.004900, Train MSE: 0.016903, Train CE:0.086172, Train KL:6.030812, Val MSE:0.022190, Val CE:0.129632, Train ACC:0.998137, Val ACC:0.986458

Epoch 740/4000: 100%|██████████| 1/1 [00:00<00:00, 20.49it/s]

epoch: 739, beta = 0.004900, Train MSE: 0.016601, Train CE:0.085610, Train KL:6.035095, Val MSE:0.022163, Val CE:0.122733, Train ACC:0.997930, Val ACC:0.988021

Epoch 741/4000: 100%|██████████| 1/1 [00:00<00:00, 19.23it/s]

epoch: 740, beta = 0.004900, Train MSE: 0.016505, Train CE:0.085296, Train KL:6.034157, Val MSE:0.022251, Val CE:0.122912, Train ACC:0.997723, Val ACC:0.986979

Epoch 742/4000: 100%|██████████| 1/1 [00:00<00:00, 22.15it/s]

epoch: 741, beta = 0.004900, Train MSE: 0.016571, Train CE:0.084910, Train KL:6.033690, Val MSE:0.021808, Val CE:0.130005, Train ACC:0.998137, Val ACC:0.986979

Epoch 743/4000: 100%|██████████| 1/1 [00:00<00:00, 23.43it/s]

epoch: 742, beta = 0.004900, Train MSE: 0.016573, Train CE:0.085009, Train KL:6.037343, Val MSE:0.022571, Val CE:0.116415, Train ACC:0.997516, Val ACC:0.988021

Epoch 744/4000: 100%|██████████| 1/1 [00:00<00:00, 23.47it/s]

epoch: 743, beta = 0.004900, Train MSE: 0.016899, Train CE:0.085319, Train KL:6.035573, Val MSE:0.022978, Val CE:0.128400, Train ACC:0.997930, Val ACC:0.983854

Epoch 745/4000: 100%|██████████| 1/1 [00:00<00:00, 23.36it/s]

epoch: 744, beta = 0.004900, Train MSE: 0.017296, Train CE:0.085340, Train KL:6.037684, Val MSE:0.023000, Val CE:0.124298, Train ACC:0.997516, Val ACC:0.986458

Epoch 746/4000: 100%|██████████| 1/1 [00:00<00:00, 21.63it/s]

epoch: 745, beta = 0.004900, Train MSE: 0.017892, Train CE:0.084834, Train KL:6.039977, Val MSE:0.023374, Val CE:0.125288, Train ACC:0.997308, Val ACC:0.986979

Epoch 747/4000: 100%|██████████| 1/1 [00:00<00:00, 19.34it/s]

epoch: 746, beta = 0.004900, Train MSE: 0.017411, Train CE:0.083899, Train KL:6.034755, Val MSE:0.022262, Val CE:0.117474, Train ACC:0.998137, Val ACC:0.987500

Epoch 748/4000: 100%|██████████| 1/1 [00:00<00:00, 23.84it/s]

epoch: 747, beta = 0.004900, Train MSE: 0.016679, Train CE:0.083113, Train KL:6.039999, Val MSE:0.021961, Val CE:0.112565, Train ACC:0.998551, Val ACC:0.989063

Epoch 749/4000: 100%|██████████| 1/1 [00:00<00:00, 22.12it/s]

epoch: 748, beta = 0.004900, Train MSE: 0.016624, Train CE:0.082993, Train KL:6.041182, Val MSE:0.022367, Val CE:0.124169, Train ACC:0.997930, Val ACC:0.985417

Epoch 750/4000: 100%|██████████| 1/1 [00:00<00:00, 22.79it/s]

epoch: 749, beta = 0.004900, Train MSE: 0.017033, Train CE:0.083066, Train KL:6.040712, Val MSE:0.021979, Val CE:0.117421, Train ACC:0.997930, Val ACC:0.989583

Epoch 751/4000: 100%|██████████| 1/1 [00:00<00:00, 22.31it/s]

epoch: 750, beta = 0.004900, Train MSE: 0.016693, Train CE:0.083302, Train KL:6.043632, Val MSE:0.022222, Val CE:0.105379, Train ACC:0.998551, Val ACC:0.988021

Epoch 752/4000: 100%|██████████| 1/1 [00:00<00:00, 23.99it/s]

epoch: 751, beta = 0.004900, Train MSE: 0.016434, Train CE:0.083454, Train KL:6.042524, Val MSE:0.022203, Val CE:0.123767, Train ACC:0.998137, Val ACC:0.987500

Epoch 753/4000: 100%|██████████| 1/1 [00:00<00:00, 22.95it/s]

epoch: 752, beta = 0.004900, Train MSE: 0.016671, Train CE:0.082318, Train KL:6.048325, Val MSE:0.021701, Val CE:0.127593, Train ACC:0.998344, Val ACC:0.985938

Epoch 754/4000: 100%|██████████| 1/1 [00:00<00:00, 21.81it/s]

epoch: 753, beta = 0.004900, Train MSE: 0.016339, Train CE:0.084705, Train KL:6.047450, Val MSE:0.023489, Val CE:0.097924, Train ACC:0.998551, Val ACC:0.989063

Epoch 755/4000: 100%|██████████| 1/1 [00:00<00:00, 24.22it/s]

epoch: 754, beta = 0.004900, Train MSE: 0.017383, Train CE:0.105003, Train KL:6.045793, Val MSE:0.027575, Val CE:0.144215, Train ACC:0.995031, Val ACC:0.980729

Epoch 756/4000: 100%|██████████| 1/1 [00:00<00:00, 22.93it/s]

epoch: 755, beta = 0.004900, Train MSE: 0.022454, Train CE:0.090658, Train KL:6.067734, Val MSE:0.034316, Val CE:0.140700, Train ACC:0.993375, Val ACC:0.980208

Epoch 757/4000: 100%|██████████| 1/1 [00:00<00:00, 24.09it/s]

epoch: 756, beta = 0.004900, Train MSE: 0.030044, Train CE:0.097742, Train KL:6.051608, Val MSE:0.035330, Val CE:0.137346, Train ACC:0.988406, Val ACC:0.981771

Epoch 758/4000: 100%|██████████| 1/1 [00:00<00:00, 23.93it/s]

epoch: 757, beta = 0.004900, Train MSE: 0.029978, Train CE:0.090925, Train KL:6.046534, Val MSE:0.032035, Val CE:0.116508, Train ACC:0.993582, Val ACC:0.986979

Epoch 759/4000: 100%|██████████| 1/1 [00:00<00:00, 20.71it/s]

epoch: 758, beta = 0.004900, Train MSE: 0.026879, Train CE:0.083686, Train KL:6.065487, Val MSE:0.031818, Val CE:0.107484, Train ACC:0.997101, Val ACC:0.986458

Epoch 760/4000: 100%|██████████| 1/1 [00:00<00:00, 23.94it/s]

epoch: 759, beta = 0.004900, Train MSE: 0.027380, Train CE:0.085725, Train KL:6.057456, Val MSE:0.033123, Val CE:0.106213, Train ACC:0.995031, Val ACC:0.981771

Epoch 761/4000: 100%|██████████| 1/1 [00:00<00:00, 21.60it/s]

epoch: 760, beta = 0.004900, Train MSE: 0.027311, Train CE:0.085833, Train KL:6.049304, Val MSE:0.027843, Val CE:0.109123, Train ACC:0.994203, Val ACC:0.986979

Epoch 762/4000: 100%|██████████| 1/1 [00:00<00:00, 23.65it/s]

epoch: 761, beta = 0.004900, Train MSE: 0.022319, Train CE:0.082899, Train KL:6.053120, Val MSE:0.028773, Val CE:0.108630, Train ACC:0.996687, Val ACC:0.988021

Epoch 763/4000: 100%|██████████| 1/1 [00:00<00:00, 24.91it/s]

epoch: 762, beta = 0.004900, Train MSE: 0.024337, Train CE:0.082600, Train KL:6.051978, Val MSE:0.025400, Val CE:0.117747, Train ACC:0.996894, Val ACC:0.982813

Epoch 764/4000: 100%|██████████| 1/1 [00:00<00:00, 24.27it/s]

epoch: 763, beta = 0.003430, Train MSE: 0.020872, Train CE:0.084104, Train KL:6.048863, Val MSE:0.025979, Val CE:0.111625, Train ACC:0.996273, Val ACC:0.985417

Epoch 765/4000: 100%|██████████| 1/1 [00:00<00:00, 24.49it/s]

Learning rate updated: 0.000857375
epoch: 764, beta = 0.003430, Train MSE: 0.020905, Train CE:0.080692, Train KL:6.052237, Val MSE:0.025616, Val CE:0.098541, Train ACC:0.997723, Val ACC:0.989583

Epoch 766/4000: 100%|██████████| 1/1 [00:00<00:00, 22.68it/s]

epoch: 765, beta = 0.003430, Train MSE: 0.020192, Train CE:0.081113, Train KL:6.056849, Val MSE:0.024878, Val CE:0.094053, Train ACC:0.996894, Val ACC:0.989063

Epoch 767/4000: 100%|██████████| 1/1 [00:00<00:00, 23.04it/s]

epoch: 766, beta = 0.003430, Train MSE: 0.019019, Train CE:0.083082, Train KL:6.060256, Val MSE:0.024352, Val CE:0.109973, Train ACC:0.996480, Val ACC:0.989583

Epoch 768/4000: 100%|██████████| 1/1 [00:00<00:00, 23.68it/s]

epoch: 767, beta = 0.003430, Train MSE: 0.019120, Train CE:0.079145, Train KL:6.077256, Val MSE:0.022297, Val CE:0.112503, Train ACC:0.998758, Val ACC:0.988021

Epoch 769/4000: 100%|██████████| 1/1 [00:00<00:00, 24.06it/s]

epoch: 768, beta = 0.003430, Train MSE: 0.018167, Train CE:0.082626, Train KL:6.094375, Val MSE:0.021941, Val CE:0.106699, Train ACC:0.998137, Val ACC:0.988542

Epoch 770/4000: 100%|██████████| 1/1 [00:00<00:00, 23.14it/s]

epoch: 769, beta = 0.003430, Train MSE: 0.017700, Train CE:0.082639, Train KL:6.098670, Val MSE:0.023353, Val CE:0.104458, Train ACC:0.997101, Val ACC:0.988021

Epoch 771/4000: 100%|██████████| 1/1 [00:00<00:00, 23.48it/s]

epoch: 770, beta = 0.003430, Train MSE: 0.018537, Train CE:0.081040, Train KL:6.104048, Val MSE:0.023123, Val CE:0.104173, Train ACC:0.998965, Val ACC:0.989063

Epoch 772/4000: 100%|██████████| 1/1 [00:00<00:00, 23.79it/s]

epoch: 771, beta = 0.003430, Train MSE: 0.017739, Train CE:0.080775, Train KL:6.122935, Val MSE:0.023084, Val CE:0.099689, Train ACC:0.998137, Val ACC:0.990625

Epoch 773/4000: 100%|██████████| 1/1 [00:00<00:00, 22.91it/s]

epoch: 772, beta = 0.003430, Train MSE: 0.018186, Train CE:0.079327, Train KL:6.146606, Val MSE:0.022347, Val CE:0.099979, Train ACC:0.997723, Val ACC:0.991146

Epoch 774/4000: 100%|██████████| 1/1 [00:00<00:00, 20.27it/s]

epoch: 773, beta = 0.003430, Train MSE: 0.017858, Train CE:0.078845, Train KL:6.163277, Val MSE:0.022358, Val CE:0.100603, Train ACC:0.997723, Val ACC:0.988021

Epoch 775/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 774, beta = 0.003430, Train MSE: 0.017787, Train CE:0.079100, Train KL:6.175640, Val MSE:0.021149, Val CE:0.098079, Train ACC:0.997101, Val ACC:0.991146

Epoch 776/4000: 100%|██████████| 1/1 [00:00<00:00, 23.75it/s]

epoch: 775, beta = 0.002401, Train MSE: 0.016306, Train CE:0.077801, Train KL:6.191773, Val MSE:0.022399, Val CE:0.098009, Train ACC:0.997516, Val ACC:0.989583

Epoch 777/4000: 100%|██████████| 1/1 [00:00<00:00, 24.04it/s]

Learning rate updated: 0.0008145062499999999
epoch: 776, beta = 0.002401, Train MSE: 0.017267, Train CE:0.077397, Train KL:6.210147, Val MSE:0.022035, Val CE:0.098350, Train ACC:0.997930, Val ACC:0.988021

Epoch 778/4000: 100%|██████████| 1/1 [00:00<00:00, 23.53it/s]

epoch: 777, beta = 0.002401, Train MSE: 0.016421, Train CE:0.076086, Train KL:6.229071, Val MSE:0.022069, Val CE:0.098703, Train ACC:0.998965, Val ACC:0.987500

Epoch 779/4000: 100%|██████████| 1/1 [00:00<00:00, 23.50it/s]

epoch: 778, beta = 0.002401, Train MSE: 0.016308, Train CE:0.075696, Train KL:6.248052, Val MSE:0.021759, Val CE:0.094300, Train ACC:0.998344, Val ACC:0.989583

Epoch 780/4000: 100%|██████████| 1/1 [00:00<00:00, 19.52it/s]

epoch: 779, beta = 0.002401, Train MSE: 0.016100, Train CE:0.074548, Train KL:6.267881, Val MSE:0.021422, Val CE:0.091658, Train ACC:0.999379, Val ACC:0.992188

Epoch 781/4000: 100%|██████████| 1/1 [00:00<00:00, 22.81it/s]

epoch: 780, beta = 0.002401, Train MSE: 0.016053, Train CE:0.074180, Train KL:6.285640, Val MSE:0.021324, Val CE:0.087073, Train ACC:0.999172, Val ACC:0.990625

Epoch 782/4000: 100%|██████████| 1/1 [00:00<00:00, 21.18it/s]

epoch: 781, beta = 0.002401, Train MSE: 0.015958, Train CE:0.074636, Train KL:6.301627, Val MSE:0.020955, Val CE:0.087095, Train ACC:0.999172, Val ACC:0.990625

Epoch 783/4000: 100%|██████████| 1/1 [00:00<00:00, 16.36it/s]

epoch: 782, beta = 0.002401, Train MSE: 0.015652, Train CE:0.073550, Train KL:6.319520, Val MSE:0.020912, Val CE:0.092898, Train ACC:0.999586, Val ACC:0.989583

Epoch 784/4000: 100%|██████████| 1/1 [00:00<00:00, 18.86it/s]

epoch: 783, beta = 0.002401, Train MSE: 0.015699, Train CE:0.073368, Train KL:6.338264, Val MSE:0.021156, Val CE:0.095618, Train ACC:0.999172, Val ACC:0.989583

Epoch 785/4000: 100%|██████████| 1/1 [00:00<00:00, 20.50it/s]

epoch: 784, beta = 0.002401, Train MSE: 0.015404, Train CE:0.072927, Train KL:6.355376, Val MSE:0.021618, Val CE:0.096574, Train ACC:0.999379, Val ACC:0.989063

Epoch 786/4000: 100%|██████████| 1/1 [00:00<00:00, 21.74it/s]

epoch: 785, beta = 0.002401, Train MSE: 0.015496, Train CE:0.072735, Train KL:6.370886, Val MSE:0.021007, Val CE:0.094253, Train ACC:0.999379, Val ACC:0.989063

Epoch 787/4000: 100%|██████████| 1/1 [00:00<00:00, 21.39it/s]

epoch: 786, beta = 0.002401, Train MSE: 0.015262, Train CE:0.072205, Train KL:6.388706, Val MSE:0.020434, Val CE:0.092652, Train ACC:0.999586, Val ACC:0.990625

Epoch 788/4000: 100%|██████████| 1/1 [00:00<00:00, 21.50it/s]

epoch: 787, beta = 0.002401, Train MSE: 0.015169, Train CE:0.072113, Train KL:6.406005, Val MSE:0.020209, Val CE:0.092855, Train ACC:0.999379, Val ACC:0.990104

Epoch 789/4000: 100%|██████████| 1/1 [00:00<00:00, 22.98it/s]

epoch: 788, beta = 0.002401, Train MSE: 0.014996, Train CE:0.071609, Train KL:6.419696, Val MSE:0.020174, Val CE:0.091691, Train ACC:0.999172, Val ACC:0.990625

Epoch 790/4000: 100%|██████████| 1/1 [00:00<00:00, 22.96it/s]

epoch: 789, beta = 0.002401, Train MSE: 0.014985, Train CE:0.071505, Train KL:6.431134, Val MSE:0.020124, Val CE:0.089252, Train ACC:0.999379, Val ACC:0.992188

Epoch 791/4000: 100%|██████████| 1/1 [00:00<00:00, 22.70it/s]

epoch: 790, beta = 0.001681, Train MSE: 0.014809, Train CE:0.071115, Train KL:6.442640, Val MSE:0.020191, Val CE:0.089386, Train ACC:0.999586, Val ACC:0.991146

Epoch 792/4000: 100%|██████████| 1/1 [00:00<00:00, 22.34it/s]

Learning rate updated: 0.0007737809374999998
epoch: 791, beta = 0.001681, Train MSE: 0.014817, Train CE:0.070929, Train KL:6.455353, Val MSE:0.020329, Val CE:0.089251, Train ACC:0.999586, Val ACC:0.990625

Epoch 793/4000: 100%|██████████| 1/1 [00:00<00:00, 19.71it/s]

epoch: 792, beta = 0.001681, Train MSE: 0.014712, Train CE:0.070633, Train KL:6.468130, Val MSE:0.020255, Val CE:0.088978, Train ACC:0.999793, Val ACC:0.991146

Epoch 794/4000: 100%|██████████| 1/1 [00:00<00:00, 20.96it/s]

epoch: 793, beta = 0.001681, Train MSE: 0.014662, Train CE:0.070169, Train KL:6.480491, Val MSE:0.019819, Val CE:0.088373, Train ACC:0.999793, Val ACC:0.991667

Epoch 795/4000: 100%|██████████| 1/1 [00:00<00:00, 19.75it/s]

epoch: 794, beta = 0.001681, Train MSE: 0.014643, Train CE:0.069924, Train KL:6.493841, Val MSE:0.019633, Val CE:0.087835, Train ACC:0.999586, Val ACC:0.992188

Epoch 796/4000: 100%|██████████| 1/1 [00:00<00:00, 20.11it/s]

epoch: 795, beta = 0.001681, Train MSE: 0.014423, Train CE:0.069603, Train KL:6.506650, Val MSE:0.019668, Val CE:0.086830, Train ACC:0.999586, Val ACC:0.991667

Epoch 797/4000: 100%|██████████| 1/1 [00:00<00:00, 20.13it/s]

epoch: 796, beta = 0.001681, Train MSE: 0.014496, Train CE:0.069416, Train KL:6.518086, Val MSE:0.019721, Val CE:0.085752, Train ACC:0.999379, Val ACC:0.990625

Epoch 798/4000: 100%|██████████| 1/1 [00:00<00:00, 20.82it/s]

epoch: 797, beta = 0.001681, Train MSE: 0.014313, Train CE:0.069191, Train KL:6.530054, Val MSE:0.019792, Val CE:0.084560, Train ACC:0.999172, Val ACC:0.992708

Epoch 799/4000: 100%|██████████| 1/1 [00:00<00:00, 22.34it/s]

epoch: 798, beta = 0.001681, Train MSE: 0.014321, Train CE:0.068798, Train KL:6.543885, Val MSE:0.019915, Val CE:0.084411, Train ACC:0.999793, Val ACC:0.991146

Epoch 800/4000: 100%|██████████| 1/1 [00:00<00:00, 23.32it/s]

epoch: 799, beta = 0.001681, Train MSE: 0.014340, Train CE:0.068627, Train KL:6.557318, Val MSE:0.019686, Val CE:0.084688, Train ACC:0.999586, Val ACC:0.991146

Epoch 801/4000: 100%|██████████| 1/1 [00:00<00:00, 23.25it/s]

epoch: 800, beta = 0.001681, Train MSE: 0.014243, Train CE:0.068371, Train KL:6.569937, Val MSE:0.019727, Val CE:0.083573, Train ACC:0.999586, Val ACC:0.991667

Epoch 802/4000: 100%|██████████| 1/1 [00:00<00:00, 22.05it/s]

epoch: 801, beta = 0.001681, Train MSE: 0.014176, Train CE:0.068087, Train KL:6.582088, Val MSE:0.019426, Val CE:0.083501, Train ACC:0.999793, Val ACC:0.991667

Epoch 803/4000: 100%|██████████| 1/1 [00:00<00:00, 17.91it/s]

epoch: 802, beta = 0.001681, Train MSE: 0.014038, Train CE:0.067813, Train KL:6.594441, Val MSE:0.019406, Val CE:0.084482, Train ACC:0.999793, Val ACC:0.991146

Epoch 804/4000: 100%|██████████| 1/1 [00:00<00:00, 19.97it/s]

epoch: 803, beta = 0.001681, Train MSE: 0.014049, Train CE:0.067607, Train KL:6.606205, Val MSE:0.019204, Val CE:0.084402, Train ACC:0.999793, Val ACC:0.992708

Epoch 805/4000: 100%|██████████| 1/1 [00:00<00:00, 17.20it/s]

epoch: 804, beta = 0.001681, Train MSE: 0.014001, Train CE:0.067336, Train KL:6.616480, Val MSE:0.019317, Val CE:0.083336, Train ACC:0.999793, Val ACC:0.993229

Epoch 806/4000: 100%|██████████| 1/1 [00:00<00:00, 21.68it/s]

epoch: 805, beta = 0.001681, Train MSE: 0.013995, Train CE:0.067064, Train KL:6.625995, Val MSE:0.019388, Val CE:0.083864, Train ACC:0.999793, Val ACC:0.992188

Epoch 807/4000: 100%|██████████| 1/1 [00:00<00:00, 18.03it/s]

epoch: 806, beta = 0.001681, Train MSE: 0.013892, Train CE:0.066912, Train KL:6.635508, Val MSE:0.019518, Val CE:0.084051, Train ACC:0.999793, Val ACC:0.992708

Epoch 808/4000: 100%|██████████| 1/1 [00:00<00:00, 22.98it/s]

epoch: 807, beta = 0.001681, Train MSE: 0.013887, Train CE:0.066601, Train KL:6.644840, Val MSE:0.019268, Val CE:0.084346, Train ACC:0.999793, Val ACC:0.993229

Epoch 809/4000: 100%|██████████| 1/1 [00:00<00:00, 22.34it/s]

epoch: 808, beta = 0.001681, Train MSE: 0.013853, Train CE:0.066314, Train KL:6.653537, Val MSE:0.019165, Val CE:0.085327, Train ACC:0.999793, Val ACC:0.992708

Epoch 810/4000: 100%|██████████| 1/1 [00:00<00:00, 22.00it/s]

epoch: 809, beta = 0.001681, Train MSE: 0.013888, Train CE:0.066097, Train KL:6.661829, Val MSE:0.019106, Val CE:0.085239, Train ACC:0.999793, Val ACC:0.992188

Epoch 811/4000: 100%|██████████| 1/1 [00:00<00:00, 20.17it/s]

epoch: 810, beta = 0.001681, Train MSE: 0.013780, Train CE:0.065890, Train KL:6.669425, Val MSE:0.019187, Val CE:0.084690, Train ACC:0.999793, Val ACC:0.993750

Epoch 812/4000: 100%|██████████| 1/1 [00:00<00:00, 23.20it/s]

epoch: 811, beta = 0.001681, Train MSE: 0.013749, Train CE:0.065700, Train KL:6.674867, Val MSE:0.019099, Val CE:0.083813, Train ACC:0.999793, Val ACC:0.992708

Epoch 813/4000: 100%|██████████| 1/1 [00:00<00:00, 22.51it/s]

epoch: 812, beta = 0.001681, Train MSE: 0.013700, Train CE:0.065402, Train KL:6.680818, Val MSE:0.019063, Val CE:0.084112, Train ACC:0.999793, Val ACC:0.992708

Epoch 814/4000: 100%|██████████| 1/1 [00:00<00:00, 22.15it/s]

epoch: 813, beta = 0.001681, Train MSE: 0.013694, Train CE:0.065144, Train KL:6.687923, Val MSE:0.018962, Val CE:0.084030, Train ACC:0.999793, Val ACC:0.992708

Epoch 815/4000: 100%|██████████| 1/1 [00:00<00:00, 22.90it/s]

epoch: 814, beta = 0.001681, Train MSE: 0.013562, Train CE:0.064879, Train KL:6.695065, Val MSE:0.019021, Val CE:0.082791, Train ACC:0.999793, Val ACC:0.993229

Epoch 816/4000: 100%|██████████| 1/1 [00:00<00:00, 21.41it/s]

epoch: 815, beta = 0.001681, Train MSE: 0.013655, Train CE:0.064698, Train KL:6.699612, Val MSE:0.019073, Val CE:0.082345, Train ACC:0.999793, Val ACC:0.993229

Epoch 817/4000: 100%|██████████| 1/1 [00:00<00:00, 21.47it/s]

epoch: 816, beta = 0.001681, Train MSE: 0.013560, Train CE:0.064495, Train KL:6.702900, Val MSE:0.018954, Val CE:0.082505, Train ACC:0.999793, Val ACC:0.993229

Epoch 818/4000: 100%|██████████| 1/1 [00:00<00:00, 20.65it/s]

epoch: 817, beta = 0.001681, Train MSE: 0.013561, Train CE:0.064217, Train KL:6.706471, Val MSE:0.019031, Val CE:0.081817, Train ACC:0.999793, Val ACC:0.994271

Epoch 819/4000: 100%|██████████| 1/1 [00:00<00:00, 25.66it/s]

epoch: 818, beta = 0.001681, Train MSE: 0.013545, Train CE:0.064007, Train KL:6.709945, Val MSE:0.018860, Val CE:0.081390, Train ACC:0.999793, Val ACC:0.993750

Epoch 820/4000: 100%|██████████| 1/1 [00:00<00:00, 21.45it/s]

epoch: 819, beta = 0.001681, Train MSE: 0.013516, Train CE:0.063743, Train KL:6.712934, Val MSE:0.018813, Val CE:0.081589, Train ACC:0.999793, Val ACC:0.992708

Epoch 821/4000: 100%|██████████| 1/1 [00:00<00:00, 23.94it/s]

epoch: 820, beta = 0.001681, Train MSE: 0.013471, Train CE:0.063484, Train KL:6.715542, Val MSE:0.018758, Val CE:0.081161, Train ACC:0.999793, Val ACC:0.993750

Epoch 822/4000: 100%|██████████| 1/1 [00:00<00:00, 21.60it/s]

epoch: 821, beta = 0.001681, Train MSE: 0.013455, Train CE:0.063354, Train KL:6.717723, Val MSE:0.018724, Val CE:0.081080, Train ACC:0.999793, Val ACC:0.994271

Epoch 823/4000: 100%|██████████| 1/1 [00:00<00:00, 22.82it/s]

epoch: 822, beta = 0.001681, Train MSE: 0.013424, Train CE:0.063035, Train KL:6.719754, Val MSE:0.018724, Val CE:0.081412, Train ACC:0.999793, Val ACC:0.994792

Epoch 824/4000: 100%|██████████| 1/1 [00:00<00:00, 23.81it/s]

epoch: 823, beta = 0.001681, Train MSE: 0.013490, Train CE:0.062845, Train KL:6.720537, Val MSE:0.018709, Val CE:0.081572, Train ACC:0.999793, Val ACC:0.993750

Epoch 825/4000: 100%|██████████| 1/1 [00:00<00:00, 22.13it/s]

epoch: 824, beta = 0.001681, Train MSE: 0.013403, Train CE:0.062655, Train KL:6.721504, Val MSE:0.018660, Val CE:0.081548, Train ACC:0.999793, Val ACC:0.994271

Epoch 826/4000: 100%|██████████| 1/1 [00:00<00:00, 23.09it/s]

epoch: 825, beta = 0.001681, Train MSE: 0.013431, Train CE:0.062389, Train KL:6.722611, Val MSE:0.018721, Val CE:0.080753, Train ACC:0.999793, Val ACC:0.994792

Epoch 827/4000: 100%|██████████| 1/1 [00:00<00:00, 21.97it/s]

epoch: 826, beta = 0.001681, Train MSE: 0.013367, Train CE:0.062202, Train KL:6.723430, Val MSE:0.018615, Val CE:0.081330, Train ACC:0.999793, Val ACC:0.994271

Epoch 828/4000: 100%|██████████| 1/1 [00:00<00:00, 25.42it/s]

epoch: 827, beta = 0.001681, Train MSE: 0.013345, Train CE:0.061993, Train KL:6.724203, Val MSE:0.018561, Val CE:0.080941, Train ACC:0.999793, Val ACC:0.993750

Epoch 829/4000: 100%|██████████| 1/1 [00:00<00:00, 25.41it/s]

epoch: 828, beta = 0.001681, Train MSE: 0.013332, Train CE:0.061807, Train KL:6.725456, Val MSE:0.018422, Val CE:0.080977, Train ACC:0.999793, Val ACC:0.993750

Epoch 830/4000: 100%|██████████| 1/1 [00:00<00:00, 22.80it/s]

epoch: 829, beta = 0.001681, Train MSE: 0.013324, Train CE:0.061534, Train KL:6.726764, Val MSE:0.018417, Val CE:0.080343, Train ACC:0.999793, Val ACC:0.994271

Epoch 831/4000: 100%|██████████| 1/1 [00:00<00:00, 20.59it/s]

epoch: 830, beta = 0.001681, Train MSE: 0.013291, Train CE:0.061293, Train KL:6.727255, Val MSE:0.018456, Val CE:0.081079, Train ACC:0.999793, Val ACC:0.993750

Epoch 832/4000: 100%|██████████| 1/1 [00:00<00:00, 17.36it/s]

epoch: 831, beta = 0.001681, Train MSE: 0.013268, Train CE:0.061110, Train KL:6.727482, Val MSE:0.018532, Val CE:0.081087, Train ACC:0.999793, Val ACC:0.993229

Epoch 833/4000: 100%|██████████| 1/1 [00:00<00:00, 29.84it/s]

epoch: 832, beta = 0.001681, Train MSE: 0.013250, Train CE:0.060900, Train KL:6.728189, Val MSE:0.018424, Val CE:0.080540, Train ACC:0.999793, Val ACC:0.993750

Epoch 834/4000: 100%|██████████| 1/1 [00:00<00:00, 22.54it/s]

epoch: 833, beta = 0.001681, Train MSE: 0.013251, Train CE:0.060642, Train KL:6.728824, Val MSE:0.018449, Val CE:0.079896, Train ACC:0.999793, Val ACC:0.993750

Epoch 835/4000: 100%|██████████| 1/1 [00:00<00:00, 24.67it/s]

epoch: 834, beta = 0.001681, Train MSE: 0.013250, Train CE:0.060470, Train KL:6.729097, Val MSE:0.018228, Val CE:0.079720, Train ACC:0.999793, Val ACC:0.995313

Epoch 836/4000: 100%|██████████| 1/1 [00:00<00:00, 21.74it/s]

epoch: 835, beta = 0.001681, Train MSE: 0.013206, Train CE:0.060221, Train KL:6.729712, Val MSE:0.018242, Val CE:0.079923, Train ACC:0.999793, Val ACC:0.994792

Epoch 837/4000: 100%|██████████| 1/1 [00:00<00:00, 23.33it/s]

epoch: 836, beta = 0.001681, Train MSE: 0.013148, Train CE:0.059991, Train KL:6.730466, Val MSE:0.018247, Val CE:0.079800, Train ACC:0.999793, Val ACC:0.995313

Epoch 838/4000: 100%|██████████| 1/1 [00:00<00:00, 25.79it/s]

epoch: 837, beta = 0.001681, Train MSE: 0.013177, Train CE:0.059802, Train KL:6.730558, Val MSE:0.018198, Val CE:0.079436, Train ACC:0.999793, Val ACC:0.994792

Epoch 839/4000: 100%|██████████| 1/1 [00:00<00:00, 21.28it/s]

epoch: 838, beta = 0.001681, Train MSE: 0.013140, Train CE:0.059645, Train KL:6.730295, Val MSE:0.018385, Val CE:0.079231, Train ACC:0.999793, Val ACC:0.993750

Epoch 840/4000: 100%|██████████| 1/1 [00:00<00:00, 22.15it/s]

epoch: 839, beta = 0.001681, Train MSE: 0.013139, Train CE:0.059429, Train KL:6.730952, Val MSE:0.018251, Val CE:0.079839, Train ACC:0.999793, Val ACC:0.994271

Epoch 841/4000: 100%|██████████| 1/1 [00:00<00:00, 21.97it/s]

epoch: 840, beta = 0.001681, Train MSE: 0.013084, Train CE:0.059176, Train KL:6.732139, Val MSE:0.018280, Val CE:0.079374, Train ACC:0.999793, Val ACC:0.994271

Epoch 842/4000: 100%|██████████| 1/1 [00:00<00:00, 21.07it/s]

epoch: 841, beta = 0.001681, Train MSE: 0.013086, Train CE:0.058952, Train KL:6.733019, Val MSE:0.018201, Val CE:0.079052, Train ACC:0.999793, Val ACC:0.993229

Epoch 843/4000: 100%|██████████| 1/1 [00:00<00:00, 24.80it/s]

epoch: 842, beta = 0.001681, Train MSE: 0.013110, Train CE:0.058734, Train KL:6.733763, Val MSE:0.018212, Val CE:0.078814, Train ACC:0.999793, Val ACC:0.995313

Epoch 844/4000: 100%|██████████| 1/1 [00:00<00:00, 27.73it/s]

epoch: 843, beta = 0.001681, Train MSE: 0.013030, Train CE:0.058521, Train KL:6.735137, Val MSE:0.017976, Val CE:0.079398, Train ACC:0.999793, Val ACC:0.994271

Epoch 845/4000: 100%|██████████| 1/1 [00:00<00:00, 23.57it/s]

epoch: 844, beta = 0.001681, Train MSE: 0.013043, Train CE:0.058320, Train KL:6.736161, Val MSE:0.018135, Val CE:0.078473, Train ACC:0.999793, Val ACC:0.995313

Epoch 846/4000: 100%|██████████| 1/1 [00:00<00:00, 23.12it/s]

epoch: 845, beta = 0.001681, Train MSE: 0.013037, Train CE:0.058169, Train KL:6.736312, Val MSE:0.018153, Val CE:0.078599, Train ACC:0.999793, Val ACC:0.994792

Epoch 847/4000: 100%|██████████| 1/1 [00:00<00:00, 20.72it/s]

epoch: 846, beta = 0.001681, Train MSE: 0.013012, Train CE:0.057959, Train KL:6.737029, Val MSE:0.018157, Val CE:0.078870, Train ACC:0.999793, Val ACC:0.994271

Epoch 848/4000: 100%|██████████| 1/1 [00:00<00:00, 23.00it/s]

epoch: 847, beta = 0.001681, Train MSE: 0.013055, Train CE:0.057765, Train KL:6.738642, Val MSE:0.018128, Val CE:0.078536, Train ACC:0.999793, Val ACC:0.994792

Epoch 849/4000: 100%|██████████| 1/1 [00:00<00:00, 19.34it/s]

epoch: 848, beta = 0.001681, Train MSE: 0.012972, Train CE:0.057487, Train KL:6.739841, Val MSE:0.018135, Val CE:0.078616, Train ACC:0.999793, Val ACC:0.994792

Epoch 850/4000: 100%|██████████| 1/1 [00:00<00:00, 20.81it/s]

epoch: 849, beta = 0.001681, Train MSE: 0.012977, Train CE:0.057309, Train KL:6.740350, Val MSE:0.018024, Val CE:0.078730, Train ACC:0.999793, Val ACC:0.994792

Epoch 851/4000: 100%|██████████| 1/1 [00:00<00:00, 27.52it/s]

epoch: 850, beta = 0.001681, Train MSE: 0.012905, Train CE:0.057105, Train KL:6.741928, Val MSE:0.018033, Val CE:0.077751, Train ACC:0.999793, Val ACC:0.994792

Epoch 852/4000: 100%|██████████| 1/1 [00:00<00:00, 23.94it/s]

epoch: 851, beta = 0.001681, Train MSE: 0.012985, Train CE:0.056930, Train KL:6.743404, Val MSE:0.018036, Val CE:0.078354, Train ACC:0.999793, Val ACC:0.994792

Epoch 853/4000: 100%|██████████| 1/1 [00:00<00:00, 22.40it/s]

epoch: 852, beta = 0.001681, Train MSE: 0.012912, Train CE:0.056701, Train KL:6.744821, Val MSE:0.018059, Val CE:0.078704, Train ACC:0.999793, Val ACC:0.994271

Epoch 854/4000: 100%|██████████| 1/1 [00:00<00:00, 22.91it/s]

epoch: 853, beta = 0.001681, Train MSE: 0.012940, Train CE:0.056518, Train KL:6.745750, Val MSE:0.018047, Val CE:0.077715, Train ACC:0.999793, Val ACC:0.995313

Epoch 855/4000: 100%|██████████| 1/1 [00:00<00:00, 23.71it/s]

epoch: 854, beta = 0.001681, Train MSE: 0.012872, Train CE:0.056277, Train KL:6.747641, Val MSE:0.017963, Val CE:0.078196, Train ACC:0.999793, Val ACC:0.994271

Epoch 856/4000: 100%|██████████| 1/1 [00:00<00:00, 30.62it/s]

epoch: 855, beta = 0.001681, Train MSE: 0.012882, Train CE:0.056058, Train KL:6.749632, Val MSE:0.017975, Val CE:0.078116, Train ACC:0.999793, Val ACC:0.994271

Epoch 857/4000: 100%|██████████| 1/1 [00:00<00:00, 26.21it/s]

epoch: 856, beta = 0.001681, Train MSE: 0.012865, Train CE:0.055902, Train KL:6.750834, Val MSE:0.017893, Val CE:0.076746, Train ACC:0.999793, Val ACC:0.994792

Epoch 858/4000: 100%|██████████| 1/1 [00:00<00:00, 25.87it/s]

epoch: 857, beta = 0.001681, Train MSE: 0.012850, Train CE:0.055724, Train KL:6.752262, Val MSE:0.017829, Val CE:0.076929, Train ACC:0.999793, Val ACC:0.994792

Epoch 859/4000: 100%|██████████| 1/1 [00:00<00:00, 23.63it/s]

epoch: 858, beta = 0.001681, Train MSE: 0.012818, Train CE:0.055526, Train KL:6.754090, Val MSE:0.017869, Val CE:0.077043, Train ACC:0.999793, Val ACC:0.995313

Epoch 860/4000: 100%|██████████| 1/1 [00:00<00:00, 29.64it/s]

epoch: 859, beta = 0.001681, Train MSE: 0.012834, Train CE:0.055319, Train KL:6.755167, Val MSE:0.017864, Val CE:0.076357, Train ACC:0.999793, Val ACC:0.994792

Epoch 861/4000: 100%|██████████| 1/1 [00:00<00:00, 25.28it/s]

epoch: 860, beta = 0.001681, Train MSE: 0.012764, Train CE:0.055120, Train KL:6.756369, Val MSE:0.017974, Val CE:0.075917, Train ACC:0.999793, Val ACC:0.995833

Epoch 862/4000: 100%|██████████| 1/1 [00:00<00:00, 23.03it/s]

epoch: 861, beta = 0.001681, Train MSE: 0.012801, Train CE:0.054981, Train KL:6.758484, Val MSE:0.017910, Val CE:0.076943, Train ACC:0.999793, Val ACC:0.995313

Epoch 863/4000: 100%|██████████| 1/1 [00:00<00:00, 23.20it/s]

epoch: 862, beta = 0.001681, Train MSE: 0.012766, Train CE:0.054740, Train KL:6.761117, Val MSE:0.017906, Val CE:0.076600, Train ACC:0.999793, Val ACC:0.995833

Epoch 864/4000: 100%|██████████| 1/1 [00:00<00:00, 25.79it/s]

epoch: 863, beta = 0.001681, Train MSE: 0.012835, Train CE:0.054515, Train KL:6.761947, Val MSE:0.017755, Val CE:0.076675, Train ACC:0.999793, Val ACC:0.995313

Epoch 865/4000: 100%|██████████| 1/1 [00:00<00:00, 18.66it/s]

epoch: 864, beta = 0.001681, Train MSE: 0.012768, Train CE:0.054319, Train KL:6.763916, Val MSE:0.017772, Val CE:0.076595, Train ACC:0.999793, Val ACC:0.994792

Epoch 866/4000: 100%|██████████| 1/1 [00:00<00:00, 19.26it/s]

epoch: 865, beta = 0.001681, Train MSE: 0.012696, Train CE:0.054140, Train KL:6.766790, Val MSE:0.017775, Val CE:0.076204, Train ACC:0.999793, Val ACC:0.995313

Epoch 867/4000: 100%|██████████| 1/1 [00:00<00:00, 19.18it/s]

epoch: 866, beta = 0.001681, Train MSE: 0.012715, Train CE:0.053913, Train KL:6.768607, Val MSE:0.017749, Val CE:0.075821, Train ACC:0.999793, Val ACC:0.995833

Epoch 868/4000: 100%|██████████| 1/1 [00:00<00:00, 23.09it/s]

epoch: 867, beta = 0.001681, Train MSE: 0.012668, Train CE:0.053722, Train KL:6.769461, Val MSE:0.017865, Val CE:0.074972, Train ACC:0.999793, Val ACC:0.994792

Epoch 869/4000: 100%|██████████| 1/1 [00:00<00:00, 25.60it/s]

epoch: 868, beta = 0.001681, Train MSE: 0.012711, Train CE:0.053551, Train KL:6.770865, Val MSE:0.017782, Val CE:0.074109, Train ACC:0.999793, Val ACC:0.995313

Epoch 870/4000: 100%|██████████| 1/1 [00:00<00:00, 18.52it/s]

epoch: 869, beta = 0.001681, Train MSE: 0.012644, Train CE:0.053400, Train KL:6.773280, Val MSE:0.017660, Val CE:0.074083, Train ACC:0.999793, Val ACC:0.995313

Epoch 871/4000: 100%|██████████| 1/1 [00:00<00:00,  6.83it/s]

epoch: 870, beta = 0.001681, Train MSE: 0.012676, Train CE:0.053155, Train KL:6.775021, Val MSE:0.017505, Val CE:0.073881, Train ACC:0.999793, Val ACC:0.994792

Epoch 872/4000: 100%|██████████| 1/1 [00:00<00:00, 22.60it/s]

epoch: 871, beta = 0.001681, Train MSE: 0.012630, Train CE:0.052953, Train KL:6.776693, Val MSE:0.017494, Val CE:0.073659, Train ACC:0.999793, Val ACC:0.995833

Epoch 873/4000: 100%|██████████| 1/1 [00:00<00:00, 24.24it/s]

epoch: 872, beta = 0.001681, Train MSE: 0.012646, Train CE:0.052807, Train KL:6.778742, Val MSE:0.017498, Val CE:0.073955, Train ACC:0.999793, Val ACC:0.995833

Epoch 874/4000: 100%|██████████| 1/1 [00:00<00:00, 18.95it/s]

epoch: 873, beta = 0.001681, Train MSE: 0.012574, Train CE:0.052649, Train KL:6.780290, Val MSE:0.017544, Val CE:0.074931, Train ACC:0.999793, Val ACC:0.994792

Epoch 875/4000: 100%|██████████| 1/1 [00:00<00:00, 21.31it/s]

epoch: 874, beta = 0.001681, Train MSE: 0.012555, Train CE:0.052402, Train KL:6.782513, Val MSE:0.017645, Val CE:0.075062, Train ACC:0.999793, Val ACC:0.995313

Epoch 876/4000: 100%|██████████| 1/1 [00:00<00:00, 25.00it/s]

epoch: 875, beta = 0.001681, Train MSE: 0.012607, Train CE:0.052265, Train KL:6.784244, Val MSE:0.017465, Val CE:0.074232, Train ACC:0.999793, Val ACC:0.994792

Epoch 877/4000: 100%|██████████| 1/1 [00:00<00:00, 23.28it/s]

epoch: 876, beta = 0.001681, Train MSE: 0.012596, Train CE:0.052029, Train KL:6.785881, Val MSE:0.017443, Val CE:0.072548, Train ACC:0.999793, Val ACC:0.995833

Epoch 878/4000: 100%|██████████| 1/1 [00:00<00:00, 24.48it/s]

epoch: 877, beta = 0.001681, Train MSE: 0.012559, Train CE:0.051824, Train KL:6.788002, Val MSE:0.017366, Val CE:0.072766, Train ACC:1.000000, Val ACC:0.995313

Epoch 879/4000: 100%|██████████| 1/1 [00:00<00:00, 20.28it/s]

epoch: 878, beta = 0.001681, Train MSE: 0.012543, Train CE:0.051691, Train KL:6.790363, Val MSE:0.017387, Val CE:0.072668, Train ACC:0.999793, Val ACC:0.994792

Epoch 880/4000: 100%|██████████| 1/1 [00:00<00:00, 26.76it/s]

epoch: 879, beta = 0.001681, Train MSE: 0.012539, Train CE:0.051457, Train KL:6.792672, Val MSE:0.017447, Val CE:0.072785, Train ACC:1.000000, Val ACC:0.995833

Epoch 881/4000: 100%|██████████| 1/1 [00:00<00:00, 22.47it/s]

epoch: 880, beta = 0.001681, Train MSE: 0.012510, Train CE:0.051270, Train KL:6.794511, Val MSE:0.017457, Val CE:0.072378, Train ACC:1.000000, Val ACC:0.995313

Epoch 882/4000: 100%|██████████| 1/1 [00:00<00:00, 19.49it/s]

epoch: 881, beta = 0.001681, Train MSE: 0.012501, Train CE:0.051076, Train KL:6.795771, Val MSE:0.017514, Val CE:0.071469, Train ACC:0.999793, Val ACC:0.994792

Epoch 883/4000: 100%|██████████| 1/1 [00:00<00:00, 21.78it/s]

epoch: 882, beta = 0.001681, Train MSE: 0.012435, Train CE:0.050938, Train KL:6.797533, Val MSE:0.017602, Val CE:0.071070, Train ACC:0.999793, Val ACC:0.994792

Epoch 884/4000: 100%|██████████| 1/1 [00:00<00:00, 19.11it/s]

epoch: 883, beta = 0.001681, Train MSE: 0.012453, Train CE:0.050775, Train KL:6.799835, Val MSE:0.017424, Val CE:0.071892, Train ACC:0.999793, Val ACC:0.994792

Epoch 885/4000: 100%|██████████| 1/1 [00:00<00:00, 25.17it/s]

epoch: 884, beta = 0.001681, Train MSE: 0.012424, Train CE:0.050526, Train KL:6.802010, Val MSE:0.017393, Val CE:0.071373, Train ACC:0.999793, Val ACC:0.995313

Epoch 886/4000: 100%|██████████| 1/1 [00:00<00:00, 29.32it/s]

epoch: 885, beta = 0.001681, Train MSE: 0.012429, Train CE:0.050426, Train KL:6.803179, Val MSE:0.017463, Val CE:0.072792, Train ACC:0.999793, Val ACC:0.994792

Epoch 887/4000: 100%|██████████| 1/1 [00:00<00:00, 24.35it/s]

epoch: 886, beta = 0.001681, Train MSE: 0.012355, Train CE:0.050195, Train KL:6.805328, Val MSE:0.017347, Val CE:0.071966, Train ACC:0.999793, Val ACC:0.994792

Epoch 888/4000: 100%|██████████| 1/1 [00:00<00:00, 24.97it/s]

epoch: 887, beta = 0.001681, Train MSE: 0.012409, Train CE:0.050004, Train KL:6.807088, Val MSE:0.017372, Val CE:0.070645, Train ACC:0.999793, Val ACC:0.995313

Epoch 889/4000: 100%|██████████| 1/1 [00:00<00:00, 24.55it/s]

epoch: 888, beta = 0.001681, Train MSE: 0.012354, Train CE:0.049839, Train KL:6.808960, Val MSE:0.017357, Val CE:0.071018, Train ACC:1.000000, Val ACC:0.995313

Epoch 890/4000: 100%|██████████| 1/1 [00:00<00:00, 23.88it/s]

epoch: 889, beta = 0.001681, Train MSE: 0.012312, Train CE:0.049624, Train KL:6.811209, Val MSE:0.017259, Val CE:0.069726, Train ACC:0.999793, Val ACC:0.995833

Epoch 891/4000: 100%|██████████| 1/1 [00:00<00:00, 21.10it/s]

epoch: 890, beta = 0.001681, Train MSE: 0.012348, Train CE:0.049470, Train KL:6.811777, Val MSE:0.017140, Val CE:0.069055, Train ACC:1.000000, Val ACC:0.995833

Epoch 892/4000: 100%|██████████| 1/1 [00:00<00:00, 18.80it/s]

epoch: 891, beta = 0.001681, Train MSE: 0.012284, Train CE:0.049343, Train KL:6.812697, Val MSE:0.017241, Val CE:0.068922, Train ACC:1.000000, Val ACC:0.996354

Epoch 893/4000: 100%|██████████| 1/1 [00:00<00:00, 23.06it/s]

epoch: 892, beta = 0.001681, Train MSE: 0.012256, Train CE:0.049110, Train KL:6.814617, Val MSE:0.017277, Val CE:0.068558, Train ACC:1.000000, Val ACC:0.995833

Epoch 894/4000: 100%|██████████| 1/1 [00:00<00:00, 21.83it/s]

epoch: 893, beta = 0.001681, Train MSE: 0.012290, Train CE:0.048916, Train KL:6.815592, Val MSE:0.017100, Val CE:0.068026, Train ACC:0.999793, Val ACC:0.996354

Epoch 895/4000: 100%|██████████| 1/1 [00:00<00:00, 20.47it/s]

epoch: 894, beta = 0.001681, Train MSE: 0.012311, Train CE:0.048742, Train KL:6.816835, Val MSE:0.017395, Val CE:0.068787, Train ACC:0.999793, Val ACC:0.995833

Epoch 896/4000: 100%|██████████| 1/1 [00:00<00:00, 26.36it/s]

epoch: 895, beta = 0.001681, Train MSE: 0.012238, Train CE:0.048600, Train KL:6.818223, Val MSE:0.017231, Val CE:0.068671, Train ACC:1.000000, Val ACC:0.995313

Epoch 897/4000: 100%|██████████| 1/1 [00:00<00:00, 17.73it/s]

epoch: 896, beta = 0.001681, Train MSE: 0.012257, Train CE:0.048420, Train KL:6.818879, Val MSE:0.017181, Val CE:0.068065, Train ACC:1.000000, Val ACC:0.995313

Epoch 898/4000: 100%|██████████| 1/1 [00:00<00:00, 31.53it/s]

epoch: 897, beta = 0.001681, Train MSE: 0.012267, Train CE:0.048206, Train KL:6.819958, Val MSE:0.017115, Val CE:0.068035, Train ACC:1.000000, Val ACC:0.995313

Epoch 899/4000: 100%|██████████| 1/1 [00:00<00:00, 24.81it/s]

epoch: 898, beta = 0.001681, Train MSE: 0.012233, Train CE:0.048039, Train KL:6.821625, Val MSE:0.017275, Val CE:0.066724, Train ACC:1.000000, Val ACC:0.994792

Epoch 900/4000: 100%|██████████| 1/1 [00:00<00:00, 23.88it/s]

epoch: 899, beta = 0.001681, Train MSE: 0.012247, Train CE:0.047934, Train KL:6.822099, Val MSE:0.017040, Val CE:0.066747, Train ACC:1.000000, Val ACC:0.994792

Epoch 901/4000: 100%|██████████| 1/1 [00:00<00:00, 23.43it/s]

epoch: 900, beta = 0.001681, Train MSE: 0.012213, Train CE:0.047732, Train KL:6.823170, Val MSE:0.017234, Val CE:0.067496, Train ACC:1.000000, Val ACC:0.995833

Epoch 902/4000: 100%|██████████| 1/1 [00:00<00:00, 20.95it/s]

epoch: 901, beta = 0.001681, Train MSE: 0.012166, Train CE:0.047530, Train KL:6.825181, Val MSE:0.017056, Val CE:0.068808, Train ACC:1.000000, Val ACC:0.996354

Epoch 903/4000: 100%|██████████| 1/1 [00:00<00:00, 32.27it/s]

epoch: 902, beta = 0.001681, Train MSE: 0.012135, Train CE:0.047386, Train KL:6.827033, Val MSE:0.017118, Val CE:0.068651, Train ACC:1.000000, Val ACC:0.995833

Epoch 904/4000: 100%|██████████| 1/1 [00:00<00:00, 20.15it/s]

epoch: 903, beta = 0.001681, Train MSE: 0.012181, Train CE:0.047217, Train KL:6.828053, Val MSE:0.017125, Val CE:0.068858, Train ACC:1.000000, Val ACC:0.995313

Epoch 905/4000: 100%|██████████| 1/1 [00:00<00:00, 25.85it/s]

epoch: 904, beta = 0.001681, Train MSE: 0.012096, Train CE:0.047010, Train KL:6.829471, Val MSE:0.016989, Val CE:0.066182, Train ACC:1.000000, Val ACC:0.995833

Epoch 906/4000: 100%|██████████| 1/1 [00:00<00:00, 25.34it/s]

epoch: 905, beta = 0.001681, Train MSE: 0.012144, Train CE:0.046925, Train KL:6.829667, Val MSE:0.017066, Val CE:0.066689, Train ACC:1.000000, Val ACC:0.995833

Epoch 907/4000: 100%|██████████| 1/1 [00:00<00:00, 24.84it/s]

epoch: 906, beta = 0.001681, Train MSE: 0.012145, Train CE:0.046685, Train KL:6.830592, Val MSE:0.017143, Val CE:0.066958, Train ACC:1.000000, Val ACC:0.994792

Epoch 908/4000: 100%|██████████| 1/1 [00:00<00:00, 28.85it/s]

epoch: 907, beta = 0.001681, Train MSE: 0.012109, Train CE:0.046563, Train KL:6.832562, Val MSE:0.016900, Val CE:0.065107, Train ACC:1.000000, Val ACC:0.996354

Epoch 909/4000: 100%|██████████| 1/1 [00:00<00:00, 20.24it/s]

epoch: 908, beta = 0.001681, Train MSE: 0.012140, Train CE:0.046414, Train KL:6.833738, Val MSE:0.016943, Val CE:0.065285, Train ACC:1.000000, Val ACC:0.995313

Epoch 910/4000: 100%|██████████| 1/1 [00:00<00:00, 20.03it/s]

epoch: 909, beta = 0.001681, Train MSE: 0.012058, Train CE:0.046238, Train KL:6.834780, Val MSE:0.016790, Val CE:0.064505, Train ACC:1.000000, Val ACC:0.994792

Epoch 911/4000: 100%|██████████| 1/1 [00:00<00:00, 22.86it/s]

epoch: 910, beta = 0.001681, Train MSE: 0.012018, Train CE:0.045984, Train KL:6.835670, Val MSE:0.016955, Val CE:0.064463, Train ACC:1.000000, Val ACC:0.995313

Epoch 912/4000: 100%|██████████| 1/1 [00:00<00:00, 20.73it/s]

epoch: 911, beta = 0.001681, Train MSE: 0.012069, Train CE:0.045834, Train KL:6.837566, Val MSE:0.016921, Val CE:0.066019, Train ACC:1.000000, Val ACC:0.995833

Epoch 913/4000: 100%|██████████| 1/1 [00:00<00:00, 19.52it/s]

epoch: 912, beta = 0.001681, Train MSE: 0.012043, Train CE:0.045759, Train KL:6.838696, Val MSE:0.016963, Val CE:0.065539, Train ACC:1.000000, Val ACC:0.995313

Epoch 914/4000: 100%|██████████| 1/1 [00:00<00:00, 25.00it/s]

epoch: 913, beta = 0.001681, Train MSE: 0.012011, Train CE:0.045560, Train KL:6.838944, Val MSE:0.016946, Val CE:0.065915, Train ACC:1.000000, Val ACC:0.995313

Epoch 915/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 914, beta = 0.001681, Train MSE: 0.011945, Train CE:0.045373, Train KL:6.840574, Val MSE:0.017020, Val CE:0.067107, Train ACC:1.000000, Val ACC:0.995313

Epoch 916/4000: 100%|██████████| 1/1 [00:00<00:00, 25.70it/s]

epoch: 915, beta = 0.001681, Train MSE: 0.011995, Train CE:0.045200, Train KL:6.842235, Val MSE:0.016848, Val CE:0.064669, Train ACC:1.000000, Val ACC:0.995833

Epoch 917/4000: 100%|██████████| 1/1 [00:00<00:00, 26.92it/s]

epoch: 916, beta = 0.001681, Train MSE: 0.012009, Train CE:0.045037, Train KL:6.842561, Val MSE:0.017012, Val CE:0.064879, Train ACC:1.000000, Val ACC:0.995833

Epoch 918/4000: 100%|██████████| 1/1 [00:00<00:00, 17.80it/s]

epoch: 917, beta = 0.001681, Train MSE: 0.011893, Train CE:0.044904, Train KL:6.844328, Val MSE:0.017040, Val CE:0.063699, Train ACC:1.000000, Val ACC:0.995833

Epoch 919/4000: 100%|██████████| 1/1 [00:00<00:00, 29.76it/s]

epoch: 918, beta = 0.001681, Train MSE: 0.011994, Train CE:0.044674, Train KL:6.845269, Val MSE:0.016994, Val CE:0.063739, Train ACC:1.000000, Val ACC:0.995833

Epoch 920/4000: 100%|██████████| 1/1 [00:00<00:00, 25.25it/s]

epoch: 919, beta = 0.001681, Train MSE: 0.011932, Train CE:0.044533, Train KL:6.845835, Val MSE:0.016717, Val CE:0.064063, Train ACC:1.000000, Val ACC:0.994792

Epoch 921/4000: 100%|██████████| 1/1 [00:00<00:00, 25.55it/s]

epoch: 920, beta = 0.001681, Train MSE: 0.011881, Train CE:0.044369, Train KL:6.846947, Val MSE:0.016792, Val CE:0.062935, Train ACC:1.000000, Val ACC:0.994792

Epoch 922/4000: 100%|██████████| 1/1 [00:00<00:00, 23.95it/s]

epoch: 921, beta = 0.001681, Train MSE: 0.011932, Train CE:0.044223, Train KL:6.847852, Val MSE:0.016881, Val CE:0.062635, Train ACC:1.000000, Val ACC:0.995313

Epoch 923/4000: 100%|██████████| 1/1 [00:00<00:00, 23.07it/s]

epoch: 922, beta = 0.001681, Train MSE: 0.011900, Train CE:0.044063, Train KL:6.848326, Val MSE:0.017011, Val CE:0.063200, Train ACC:1.000000, Val ACC:0.994271

Epoch 924/4000: 100%|██████████| 1/1 [00:00<00:00, 23.38it/s]

epoch: 923, beta = 0.001681, Train MSE: 0.011867, Train CE:0.043910, Train KL:6.849598, Val MSE:0.016806, Val CE:0.064042, Train ACC:1.000000, Val ACC:0.994792

Epoch 925/4000: 100%|██████████| 1/1 [00:00<00:00, 25.70it/s]

epoch: 924, beta = 0.001681, Train MSE: 0.011864, Train CE:0.043754, Train KL:6.851394, Val MSE:0.016745, Val CE:0.063488, Train ACC:1.000000, Val ACC:0.995313

Epoch 926/4000: 100%|██████████| 1/1 [00:00<00:00, 23.85it/s]

epoch: 925, beta = 0.001681, Train MSE: 0.011817, Train CE:0.043569, Train KL:6.852149, Val MSE:0.016764, Val CE:0.062719, Train ACC:1.000000, Val ACC:0.995313

Epoch 927/4000: 100%|██████████| 1/1 [00:00<00:00, 24.34it/s]

epoch: 926, beta = 0.001681, Train MSE: 0.011827, Train CE:0.043422, Train KL:6.852029, Val MSE:0.016659, Val CE:0.062840, Train ACC:1.000000, Val ACC:0.994792

Epoch 928/4000: 100%|██████████| 1/1 [00:00<00:00, 27.20it/s]

epoch: 927, beta = 0.001681, Train MSE: 0.011802, Train CE:0.043275, Train KL:6.853324, Val MSE:0.016562, Val CE:0.062429, Train ACC:1.000000, Val ACC:0.995313

Epoch 929/4000: 100%|██████████| 1/1 [00:00<00:00, 20.52it/s]

epoch: 928, beta = 0.001681, Train MSE: 0.011772, Train CE:0.043100, Train KL:6.854058, Val MSE:0.016646, Val CE:0.063160, Train ACC:1.000000, Val ACC:0.995833

Epoch 930/4000: 100%|██████████| 1/1 [00:00<00:00, 19.05it/s]

epoch: 929, beta = 0.001681, Train MSE: 0.011784, Train CE:0.042967, Train KL:6.854449, Val MSE:0.016779, Val CE:0.063681, Train ACC:1.000000, Val ACC:0.995313

Epoch 931/4000: 100%|██████████| 1/1 [00:00<00:00, 19.00it/s]

epoch: 930, beta = 0.001681, Train MSE: 0.011766, Train CE:0.042827, Train KL:6.856196, Val MSE:0.016821, Val CE:0.062305, Train ACC:1.000000, Val ACC:0.995313

Epoch 932/4000: 100%|██████████| 1/1 [00:00<00:00, 23.42it/s]

epoch: 931, beta = 0.001681, Train MSE: 0.011833, Train CE:0.042700, Train KL:6.857169, Val MSE:0.016779, Val CE:0.061297, Train ACC:1.000000, Val ACC:0.995313

Epoch 933/4000: 100%|██████████| 1/1 [00:00<00:00, 25.14it/s]

epoch: 932, beta = 0.001681, Train MSE: 0.011741, Train CE:0.042540, Train KL:6.858267, Val MSE:0.016719, Val CE:0.060097, Train ACC:1.000000, Val ACC:0.995833

Epoch 934/4000: 100%|██████████| 1/1 [00:00<00:00, 31.44it/s]

epoch: 933, beta = 0.001681, Train MSE: 0.011770, Train CE:0.042335, Train KL:6.859715, Val MSE:0.016636, Val CE:0.060271, Train ACC:1.000000, Val ACC:0.996354

Epoch 935/4000: 100%|██████████| 1/1 [00:00<00:00, 27.48it/s]

epoch: 934, beta = 0.001681, Train MSE: 0.011758, Train CE:0.042154, Train KL:6.861802, Val MSE:0.016439, Val CE:0.061560, Train ACC:1.000000, Val ACC:0.995313

Epoch 936/4000: 100%|██████████| 1/1 [00:00<00:00, 25.74it/s]

epoch: 935, beta = 0.001681, Train MSE: 0.011715, Train CE:0.042042, Train KL:6.863429, Val MSE:0.016716, Val CE:0.060979, Train ACC:1.000000, Val ACC:0.995313

Epoch 937/4000: 100%|██████████| 1/1 [00:00<00:00, 20.68it/s]

epoch: 936, beta = 0.001681, Train MSE: 0.011739, Train CE:0.041860, Train KL:6.864573, Val MSE:0.016585, Val CE:0.060843, Train ACC:1.000000, Val ACC:0.995313

Epoch 938/4000: 100%|██████████| 1/1 [00:00<00:00, 23.27it/s]

epoch: 937, beta = 0.001681, Train MSE: 0.011678, Train CE:0.041725, Train KL:6.866636, Val MSE:0.016630, Val CE:0.061336, Train ACC:1.000000, Val ACC:0.995833

Epoch 939/4000: 100%|██████████| 1/1 [00:00<00:00, 18.31it/s]

epoch: 938, beta = 0.001681, Train MSE: 0.011631, Train CE:0.041588, Train KL:6.867760, Val MSE:0.016497, Val CE:0.060310, Train ACC:1.000000, Val ACC:0.995313

Epoch 940/4000: 100%|██████████| 1/1 [00:00<00:00, 24.96it/s]

epoch: 939, beta = 0.001681, Train MSE: 0.011642, Train CE:0.041383, Train KL:6.868627, Val MSE:0.016474, Val CE:0.060139, Train ACC:1.000000, Val ACC:0.995313

Epoch 941/4000: 100%|██████████| 1/1 [00:00<00:00, 23.50it/s]

epoch: 940, beta = 0.001681, Train MSE: 0.011644, Train CE:0.041275, Train KL:6.870344, Val MSE:0.016554, Val CE:0.060092, Train ACC:1.000000, Val ACC:0.995313

Epoch 942/4000: 100%|██████████| 1/1 [00:00<00:00, 21.00it/s]

epoch: 941, beta = 0.001681, Train MSE: 0.011614, Train CE:0.041114, Train KL:6.871552, Val MSE:0.016568, Val CE:0.060629, Train ACC:1.000000, Val ACC:0.994271

Epoch 943/4000: 100%|██████████| 1/1 [00:00<00:00, 18.48it/s]

epoch: 942, beta = 0.001681, Train MSE: 0.011619, Train CE:0.040972, Train KL:6.872187, Val MSE:0.016582, Val CE:0.060674, Train ACC:1.000000, Val ACC:0.994792

Epoch 944/4000: 100%|██████████| 1/1 [00:00<00:00, 26.26it/s]

epoch: 943, beta = 0.001681, Train MSE: 0.011598, Train CE:0.040808, Train KL:6.873062, Val MSE:0.016489, Val CE:0.059757, Train ACC:1.000000, Val ACC:0.994792

Epoch 945/4000: 100%|██████████| 1/1 [00:00<00:00, 23.08it/s]

epoch: 944, beta = 0.001681, Train MSE: 0.011543, Train CE:0.040677, Train KL:6.874267, Val MSE:0.016372, Val CE:0.058678, Train ACC:1.000000, Val ACC:0.995833

Epoch 946/4000: 100%|██████████| 1/1 [00:00<00:00, 23.80it/s]

epoch: 945, beta = 0.001681, Train MSE: 0.011562, Train CE:0.040539, Train KL:6.874082, Val MSE:0.016458, Val CE:0.058751, Train ACC:1.000000, Val ACC:0.995833

Epoch 947/4000: 100%|██████████| 1/1 [00:00<00:00, 21.42it/s]

epoch: 946, beta = 0.001681, Train MSE: 0.011558, Train CE:0.040315, Train KL:6.875225, Val MSE:0.016426, Val CE:0.059289, Train ACC:1.000000, Val ACC:0.995833

Epoch 948/4000: 100%|██████████| 1/1 [00:00<00:00, 19.09it/s]

epoch: 947, beta = 0.001681, Train MSE: 0.011546, Train CE:0.040247, Train KL:6.876602, Val MSE:0.016353, Val CE:0.058547, Train ACC:1.000000, Val ACC:0.995313

Epoch 949/4000: 100%|██████████| 1/1 [00:00<00:00, 25.92it/s]

epoch: 948, beta = 0.001681, Train MSE: 0.011562, Train CE:0.040136, Train KL:6.876948, Val MSE:0.016424, Val CE:0.058653, Train ACC:1.000000, Val ACC:0.995313

Epoch 950/4000: 100%|██████████| 1/1 [00:00<00:00, 22.96it/s]

epoch: 949, beta = 0.001681, Train MSE: 0.011489, Train CE:0.039935, Train KL:6.877863, Val MSE:0.016420, Val CE:0.058117, Train ACC:1.000000, Val ACC:0.995313

Epoch 951/4000: 100%|██████████| 1/1 [00:00<00:00, 22.82it/s]

epoch: 950, beta = 0.001681, Train MSE: 0.011496, Train CE:0.039829, Train KL:6.878320, Val MSE:0.016288, Val CE:0.058209, Train ACC:1.000000, Val ACC:0.994792

Epoch 952/4000: 100%|██████████| 1/1 [00:00<00:00, 18.77it/s]

epoch: 951, beta = 0.001681, Train MSE: 0.011495, Train CE:0.039653, Train KL:6.879088, Val MSE:0.016215, Val CE:0.058778, Train ACC:1.000000, Val ACC:0.994792

Epoch 953/4000: 100%|██████████| 1/1 [00:00<00:00, 18.98it/s]

epoch: 952, beta = 0.001681, Train MSE: 0.011438, Train CE:0.039529, Train KL:6.880459, Val MSE:0.016282, Val CE:0.057948, Train ACC:1.000000, Val ACC:0.995313

Epoch 954/4000: 100%|██████████| 1/1 [00:00<00:00, 21.34it/s]

epoch: 953, beta = 0.001681, Train MSE: 0.011516, Train CE:0.039381, Train KL:6.880890, Val MSE:0.016364, Val CE:0.058477, Train ACC:1.000000, Val ACC:0.995313

Epoch 955/4000: 100%|██████████| 1/1 [00:00<00:00, 25.59it/s]

epoch: 954, beta = 0.001681, Train MSE: 0.011470, Train CE:0.039244, Train KL:6.881821, Val MSE:0.016271, Val CE:0.058176, Train ACC:1.000000, Val ACC:0.994792

Epoch 956/4000: 100%|██████████| 1/1 [00:00<00:00, 24.28it/s]

epoch: 955, beta = 0.001681, Train MSE: 0.011468, Train CE:0.039087, Train KL:6.882497, Val MSE:0.016283, Val CE:0.057083, Train ACC:1.000000, Val ACC:0.995313

Epoch 957/4000: 100%|██████████| 1/1 [00:00<00:00, 29.41it/s]

epoch: 956, beta = 0.001681, Train MSE: 0.011432, Train CE:0.038950, Train KL:6.883189, Val MSE:0.016430, Val CE:0.057597, Train ACC:1.000000, Val ACC:0.995313

Epoch 958/4000: 100%|██████████| 1/1 [00:00<00:00, 28.90it/s]

epoch: 957, beta = 0.001681, Train MSE: 0.011516, Train CE:0.038891, Train KL:6.884924, Val MSE:0.016265, Val CE:0.055568, Train ACC:1.000000, Val ACC:0.996354

Epoch 959/4000: 100%|██████████| 1/1 [00:00<00:00, 19.76it/s]

epoch: 958, beta = 0.001681, Train MSE: 0.011494, Train CE:0.038820, Train KL:6.885420, Val MSE:0.016236, Val CE:0.059912, Train ACC:1.000000, Val ACC:0.994271

Epoch 960/4000: 100%|██████████| 1/1 [00:00<00:00, 25.96it/s]

epoch: 959, beta = 0.001681, Train MSE: 0.011451, Train CE:0.038770, Train KL:6.888731, Val MSE:0.016368, Val CE:0.056485, Train ACC:1.000000, Val ACC:0.995833

Epoch 961/4000: 100%|██████████| 1/1 [00:00<00:00, 27.11it/s]

epoch: 960, beta = 0.001681, Train MSE: 0.011427, Train CE:0.038642, Train KL:6.887600, Val MSE:0.016376, Val CE:0.057720, Train ACC:1.000000, Val ACC:0.994792

Epoch 962/4000: 100%|██████████| 1/1 [00:00<00:00, 23.03it/s]

epoch: 961, beta = 0.001681, Train MSE: 0.011446, Train CE:0.038310, Train KL:6.889300, Val MSE:0.016152, Val CE:0.056897, Train ACC:1.000000, Val ACC:0.994271

Epoch 963/4000: 100%|██████████| 1/1 [00:00<00:00, 23.54it/s]

epoch: 962, beta = 0.001681, Train MSE: 0.011327, Train CE:0.038154, Train KL:6.890907, Val MSE:0.016236, Val CE:0.056071, Train ACC:1.000000, Val ACC:0.994271

Epoch 964/4000: 100%|██████████| 1/1 [00:00<00:00, 23.43it/s]

epoch: 963, beta = 0.001681, Train MSE: 0.011417, Train CE:0.037979, Train KL:6.892436, Val MSE:0.016268, Val CE:0.057740, Train ACC:1.000000, Val ACC:0.995313

Epoch 965/4000: 100%|██████████| 1/1 [00:00<00:00, 22.23it/s]

epoch: 964, beta = 0.001681, Train MSE: 0.011459, Train CE:0.037921, Train KL:6.893813, Val MSE:0.016186, Val CE:0.054678, Train ACC:1.000000, Val ACC:0.996354

Epoch 966/4000: 100%|██████████| 1/1 [00:00<00:00, 22.38it/s]

epoch: 965, beta = 0.001681, Train MSE: 0.011379, Train CE:0.037883, Train KL:6.893664, Val MSE:0.016181, Val CE:0.056345, Train ACC:1.000000, Val ACC:0.995313

Epoch 967/4000: 100%|██████████| 1/1 [00:00<00:00, 31.47it/s]

epoch: 966, beta = 0.001681, Train MSE: 0.011339, Train CE:0.037613, Train KL:6.896690, Val MSE:0.016073, Val CE:0.056219, Train ACC:1.000000, Val ACC:0.994271

Epoch 968/4000: 100%|██████████| 1/1 [00:00<00:00, 24.17it/s]

epoch: 967, beta = 0.001681, Train MSE: 0.011291, Train CE:0.037467, Train KL:6.897388, Val MSE:0.016157, Val CE:0.054380, Train ACC:1.000000, Val ACC:0.995833

Epoch 969/4000: 100%|██████████| 1/1 [00:00<00:00, 23.69it/s]

epoch: 968, beta = 0.001681, Train MSE: 0.011290, Train CE:0.037365, Train KL:6.898371, Val MSE:0.016250, Val CE:0.056478, Train ACC:1.000000, Val ACC:0.995313

Epoch 970/4000: 100%|██████████| 1/1 [00:00<00:00, 20.56it/s]

epoch: 969, beta = 0.001681, Train MSE: 0.011365, Train CE:0.037231, Train KL:6.900776, Val MSE:0.016090, Val CE:0.055398, Train ACC:1.000000, Val ACC:0.994792

Epoch 971/4000: 100%|██████████| 1/1 [00:00<00:00, 22.21it/s]

epoch: 970, beta = 0.001681, Train MSE: 0.011324, Train CE:0.037117, Train KL:6.901317, Val MSE:0.015898, Val CE:0.059696, Train ACC:1.000000, Val ACC:0.994792

Epoch 972/4000: 100%|██████████| 1/1 [00:00<00:00, 17.36it/s]

epoch: 971, beta = 0.001681, Train MSE: 0.011255, Train CE:0.036944, Train KL:6.904756, Val MSE:0.015839, Val CE:0.058023, Train ACC:1.000000, Val ACC:0.993750

Epoch 973/4000: 100%|██████████| 1/1 [00:00<00:00, 19.39it/s]

epoch: 972, beta = 0.001681, Train MSE: 0.011215, Train CE:0.036745, Train KL:6.906202, Val MSE:0.015891, Val CE:0.054049, Train ACC:1.000000, Val ACC:0.995313

Epoch 974/4000: 100%|██████████| 1/1 [00:00<00:00, 21.44it/s]

epoch: 973, beta = 0.001681, Train MSE: 0.011266, Train CE:0.036677, Train KL:6.906045, Val MSE:0.016194, Val CE:0.055773, Train ACC:1.000000, Val ACC:0.993750

Epoch 975/4000: 100%|██████████| 1/1 [00:00<00:00, 28.84it/s]

epoch: 974, beta = 0.001681, Train MSE: 0.011233, Train CE:0.036587, Train KL:6.909301, Val MSE:0.015795, Val CE:0.054621, Train ACC:1.000000, Val ACC:0.994792

Epoch 976/4000: 100%|██████████| 1/1 [00:00<00:00, 22.91it/s]

epoch: 975, beta = 0.001681, Train MSE: 0.011196, Train CE:0.036352, Train KL:6.909875, Val MSE:0.015884, Val CE:0.054574, Train ACC:1.000000, Val ACC:0.995313

Epoch 977/4000: 100%|██████████| 1/1 [00:00<00:00, 20.00it/s]

epoch: 976, beta = 0.001681, Train MSE: 0.011171, Train CE:0.036223, Train KL:6.910424, Val MSE:0.015954, Val CE:0.055367, Train ACC:1.000000, Val ACC:0.995833

Epoch 978/4000: 100%|██████████| 1/1 [00:00<00:00, 23.19it/s]

epoch: 977, beta = 0.001681, Train MSE: 0.011187, Train CE:0.036161, Train KL:6.911849, Val MSE:0.015857, Val CE:0.053271, Train ACC:1.000000, Val ACC:0.995833

Epoch 979/4000: 100%|██████████| 1/1 [00:00<00:00, 18.23it/s]

epoch: 978, beta = 0.001681, Train MSE: 0.011137, Train CE:0.036075, Train KL:6.910811, Val MSE:0.015969, Val CE:0.056081, Train ACC:1.000000, Val ACC:0.994271

Epoch 980/4000: 100%|██████████| 1/1 [00:00<00:00, 27.08it/s]

epoch: 979, beta = 0.001681, Train MSE: 0.011172, Train CE:0.035980, Train KL:6.912121, Val MSE:0.015987, Val CE:0.054630, Train ACC:1.000000, Val ACC:0.995833

Epoch 981/4000: 100%|██████████| 1/1 [00:00<00:00, 22.85it/s]

epoch: 980, beta = 0.001681, Train MSE: 0.011110, Train CE:0.035779, Train KL:6.912179, Val MSE:0.015928, Val CE:0.055034, Train ACC:1.000000, Val ACC:0.994792

Epoch 982/4000: 100%|██████████| 1/1 [00:00<00:00, 32.44it/s]

epoch: 981, beta = 0.001681, Train MSE: 0.011090, Train CE:0.035610, Train KL:6.912299, Val MSE:0.016082, Val CE:0.054102, Train ACC:1.000000, Val ACC:0.994792

Epoch 983/4000: 100%|██████████| 1/1 [00:00<00:00, 26.27it/s]

epoch: 982, beta = 0.001681, Train MSE: 0.011081, Train CE:0.035484, Train KL:6.913393, Val MSE:0.015841, Val CE:0.054286, Train ACC:1.000000, Val ACC:0.995313

Epoch 984/4000: 100%|██████████| 1/1 [00:00<00:00, 28.82it/s]

epoch: 983, beta = 0.001681, Train MSE: 0.011034, Train CE:0.035346, Train KL:6.914515, Val MSE:0.015852, Val CE:0.054452, Train ACC:1.000000, Val ACC:0.994792

Epoch 985/4000: 100%|██████████| 1/1 [00:00<00:00, 22.71it/s]

epoch: 984, beta = 0.001681, Train MSE: 0.011059, Train CE:0.035194, Train KL:6.915617, Val MSE:0.016082, Val CE:0.054460, Train ACC:1.000000, Val ACC:0.995833

Epoch 986/4000: 100%|██████████| 1/1 [00:00<00:00, 18.85it/s]

epoch: 985, beta = 0.001681, Train MSE: 0.011030, Train CE:0.035049, Train KL:6.916658, Val MSE:0.015833, Val CE:0.053593, Train ACC:1.000000, Val ACC:0.995833

Epoch 987/4000: 100%|██████████| 1/1 [00:00<00:00, 23.98it/s]

epoch: 986, beta = 0.001681, Train MSE: 0.011026, Train CE:0.034943, Train KL:6.917091, Val MSE:0.016050, Val CE:0.055834, Train ACC:1.000000, Val ACC:0.994271

Epoch 988/4000: 100%|██████████| 1/1 [00:00<00:00, 25.05it/s]

epoch: 987, beta = 0.001681, Train MSE: 0.011062, Train CE:0.034924, Train KL:6.918095, Val MSE:0.015805, Val CE:0.051756, Train ACC:1.000000, Val ACC:0.996354

Epoch 989/4000: 100%|██████████| 1/1 [00:00<00:00, 24.03it/s]

epoch: 988, beta = 0.001681, Train MSE: 0.011108, Train CE:0.034820, Train KL:6.917706, Val MSE:0.015713, Val CE:0.054076, Train ACC:1.000000, Val ACC:0.994792

Epoch 990/4000: 100%|██████████| 1/1 [00:00<00:00, 23.19it/s]

epoch: 989, beta = 0.001681, Train MSE: 0.011037, Train CE:0.034653, Train KL:6.919357, Val MSE:0.015685, Val CE:0.052069, Train ACC:1.000000, Val ACC:0.995833

Epoch 991/4000: 100%|██████████| 1/1 [00:00<00:00, 23.56it/s]

epoch: 990, beta = 0.001681, Train MSE: 0.010974, Train CE:0.034453, Train KL:6.918960, Val MSE:0.015676, Val CE:0.052278, Train ACC:1.000000, Val ACC:0.994792

Epoch 992/4000: 100%|██████████| 1/1 [00:00<00:00, 19.47it/s]

epoch: 991, beta = 0.001681, Train MSE: 0.010996, Train CE:0.034369, Train KL:6.919264, Val MSE:0.015758, Val CE:0.052213, Train ACC:1.000000, Val ACC:0.995313

Epoch 993/4000: 100%|██████████| 1/1 [00:00<00:00, 26.93it/s]

epoch: 992, beta = 0.001681, Train MSE: 0.010929, Train CE:0.034208, Train KL:6.920415, Val MSE:0.015709, Val CE:0.052154, Train ACC:1.000000, Val ACC:0.995313

Epoch 994/4000: 100%|██████████| 1/1 [00:00<00:00, 23.77it/s]

epoch: 993, beta = 0.001681, Train MSE: 0.010951, Train CE:0.034064, Train KL:6.921748, Val MSE:0.015745, Val CE:0.055225, Train ACC:1.000000, Val ACC:0.994792

Epoch 995/4000: 100%|██████████| 1/1 [00:00<00:00, 26.58it/s]

epoch: 994, beta = 0.001681, Train MSE: 0.010940, Train CE:0.033999, Train KL:6.922950, Val MSE:0.015627, Val CE:0.053131, Train ACC:1.000000, Val ACC:0.995313

Epoch 996/4000: 100%|██████████| 1/1 [00:00<00:00, 20.95it/s]

epoch: 995, beta = 0.001681, Train MSE: 0.010938, Train CE:0.033907, Train KL:6.923201, Val MSE:0.015768, Val CE:0.054191, Train ACC:1.000000, Val ACC:0.993750

Epoch 997/4000: 100%|██████████| 1/1 [00:00<00:00, 25.39it/s]

epoch: 996, beta = 0.001681, Train MSE: 0.010905, Train CE:0.033741, Train KL:6.925533, Val MSE:0.015695, Val CE:0.052549, Train ACC:1.000000, Val ACC:0.994271

Epoch 998/4000: 100%|██████████| 1/1 [00:00<00:00, 23.72it/s]

epoch: 997, beta = 0.001176, Train MSE: 0.010917, Train CE:0.033599, Train KL:6.926165, Val MSE:0.015604, Val CE:0.052638, Train ACC:1.000000, Val ACC:0.995313

Epoch 999/4000: 100%|██████████| 1/1 [00:00<00:00, 24.82it/s]

Learning rate updated: 0.0007350918906249997
epoch: 998, beta = 0.001176, Train MSE: 0.010885, Train CE:0.033450, Train KL:6.927916, Val MSE:0.015511, Val CE:0.052950, Train ACC:1.000000, Val ACC:0.995833

Epoch 1000/4000: 100%|██████████| 1/1 [00:00<00:00, 25.14it/s]

epoch: 999, beta = 0.001176, Train MSE: 0.010848, Train CE:0.033349, Train KL:6.931108, Val MSE:0.015481, Val CE:0.051943, Train ACC:1.000000, Val ACC:0.995833

Epoch 1001/4000: 100%|██████████| 1/1 [00:00<00:00, 24.26it/s]

epoch: 1000, beta = 0.001176, Train MSE: 0.010869, Train CE:0.033204, Train KL:6.934511, Val MSE:0.015480, Val CE:0.051392, Train ACC:1.000000, Val ACC:0.995313

Epoch 1002/4000: 100%|██████████| 1/1 [00:00<00:00, 23.59it/s]

epoch: 1001, beta = 0.001176, Train MSE: 0.010826, Train CE:0.033118, Train KL:6.940765, Val MSE:0.015446, Val CE:0.051862, Train ACC:1.000000, Val ACC:0.994792

Epoch 1003/4000: 100%|██████████| 1/1 [00:00<00:00, 19.76it/s]

epoch: 1002, beta = 0.001176, Train MSE: 0.010768, Train CE:0.033022, Train KL:6.948105, Val MSE:0.015596, Val CE:0.050150, Train ACC:1.000000, Val ACC:0.995313

Epoch 1004/4000: 100%|██████████| 1/1 [00:00<00:00, 31.30it/s]

epoch: 1003, beta = 0.001176, Train MSE: 0.010792, Train CE:0.032962, Train KL:6.954308, Val MSE:0.015664, Val CE:0.052575, Train ACC:1.000000, Val ACC:0.993750

Epoch 1005/4000: 100%|██████████| 1/1 [00:00<00:00, 23.58it/s]

epoch: 1004, beta = 0.001176, Train MSE: 0.010829, Train CE:0.032835, Train KL:6.963068, Val MSE:0.015510, Val CE:0.051941, Train ACC:1.000000, Val ACC:0.994792

Epoch 1006/4000: 100%|██████████| 1/1 [00:00<00:00, 24.59it/s]

epoch: 1005, beta = 0.001176, Train MSE: 0.010750, Train CE:0.032654, Train KL:6.972781, Val MSE:0.015555, Val CE:0.051147, Train ACC:1.000000, Val ACC:0.994792

Epoch 1007/4000: 100%|██████████| 1/1 [00:00<00:00, 23.94it/s]

epoch: 1006, beta = 0.001176, Train MSE: 0.010707, Train CE:0.032554, Train KL:6.981899, Val MSE:0.015599, Val CE:0.052556, Train ACC:1.000000, Val ACC:0.994271

Epoch 1008/4000: 100%|██████████| 1/1 [00:00<00:00, 24.04it/s]

epoch: 1007, beta = 0.001176, Train MSE: 0.010696, Train CE:0.032495, Train KL:6.992305, Val MSE:0.015560, Val CE:0.050890, Train ACC:1.000000, Val ACC:0.995833

Epoch 1009/4000: 100%|██████████| 1/1 [00:00<00:00, 23.88it/s]

epoch: 1008, beta = 0.001176, Train MSE: 0.010697, Train CE:0.032397, Train KL:7.002279, Val MSE:0.015408, Val CE:0.052667, Train ACC:1.000000, Val ACC:0.994792

Epoch 1010/4000: 100%|██████████| 1/1 [00:00<00:00, 23.33it/s]

epoch: 1009, beta = 0.001176, Train MSE: 0.010602, Train CE:0.032256, Train KL:7.012924, Val MSE:0.015347, Val CE:0.051407, Train ACC:1.000000, Val ACC:0.995313

Epoch 1011/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 1010, beta = 0.001176, Train MSE: 0.010588, Train CE:0.032106, Train KL:7.023044, Val MSE:0.015377, Val CE:0.050177, Train ACC:1.000000, Val ACC:0.995833

Epoch 1012/4000: 100%|██████████| 1/1 [00:00<00:00, 24.06it/s]

epoch: 1011, beta = 0.001176, Train MSE: 0.010586, Train CE:0.031980, Train KL:7.032791, Val MSE:0.015499, Val CE:0.050184, Train ACC:1.000000, Val ACC:0.995833

Epoch 1013/4000: 100%|██████████| 1/1 [00:00<00:00, 24.71it/s]

epoch: 1012, beta = 0.001176, Train MSE: 0.010559, Train CE:0.031893, Train KL:7.042583, Val MSE:0.015259, Val CE:0.049899, Train ACC:1.000000, Val ACC:0.995313

Epoch 1014/4000: 100%|██████████| 1/1 [00:00<00:00, 24.01it/s]

epoch: 1013, beta = 0.001176, Train MSE: 0.010582, Train CE:0.031766, Train KL:7.052205, Val MSE:0.015372, Val CE:0.052719, Train ACC:1.000000, Val ACC:0.994792

Epoch 1015/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 1014, beta = 0.001176, Train MSE: 0.010503, Train CE:0.031685, Train KL:7.062257, Val MSE:0.015403, Val CE:0.051650, Train ACC:1.000000, Val ACC:0.994271

Epoch 1016/4000: 100%|██████████| 1/1 [00:00<00:00, 28.85it/s]

epoch: 1015, beta = 0.001176, Train MSE: 0.010461, Train CE:0.031503, Train KL:7.069761, Val MSE:0.015356, Val CE:0.050004, Train ACC:1.000000, Val ACC:0.995313

Epoch 1017/4000: 100%|██████████| 1/1 [00:00<00:00, 23.71it/s]

epoch: 1016, beta = 0.001176, Train MSE: 0.010463, Train CE:0.031419, Train KL:7.077533, Val MSE:0.015410, Val CE:0.050626, Train ACC:1.000000, Val ACC:0.994792

Epoch 1018/4000: 100%|██████████| 1/1 [00:00<00:00, 24.34it/s]

epoch: 1017, beta = 0.001176, Train MSE: 0.010479, Train CE:0.031350, Train KL:7.086587, Val MSE:0.015199, Val CE:0.049840, Train ACC:1.000000, Val ACC:0.994792

Epoch 1019/4000: 100%|██████████| 1/1 [00:00<00:00, 24.46it/s]

epoch: 1018, beta = 0.001176, Train MSE: 0.010466, Train CE:0.031184, Train KL:7.093596, Val MSE:0.015203, Val CE:0.051554, Train ACC:1.000000, Val ACC:0.994792

Epoch 1020/4000: 100%|██████████| 1/1 [00:00<00:00, 25.35it/s]

epoch: 1019, beta = 0.001176, Train MSE: 0.010376, Train CE:0.031088, Train KL:7.101381, Val MSE:0.015203, Val CE:0.050080, Train ACC:1.000000, Val ACC:0.995833

Epoch 1021/4000: 100%|██████████| 1/1 [00:00<00:00, 25.12it/s]

epoch: 1020, beta = 0.001176, Train MSE: 0.010348, Train CE:0.031013, Train KL:7.107713, Val MSE:0.015120, Val CE:0.049821, Train ACC:1.000000, Val ACC:0.995833

Epoch 1022/4000: 100%|██████████| 1/1 [00:00<00:00, 23.96it/s]

epoch: 1021, beta = 0.001176, Train MSE: 0.010383, Train CE:0.030936, Train KL:7.113264, Val MSE:0.015085, Val CE:0.051575, Train ACC:1.000000, Val ACC:0.994271

Epoch 1023/4000: 100%|██████████| 1/1 [00:00<00:00, 23.84it/s]

epoch: 1022, beta = 0.001176, Train MSE: 0.010336, Train CE:0.030832, Train KL:7.120599, Val MSE:0.015176, Val CE:0.048901, Train ACC:1.000000, Val ACC:0.994792

Epoch 1024/4000: 100%|██████████| 1/1 [00:00<00:00, 24.02it/s]

epoch: 1023, beta = 0.001176, Train MSE: 0.010390, Train CE:0.030716, Train KL:7.125662, Val MSE:0.015172, Val CE:0.050158, Train ACC:1.000000, Val ACC:0.995313

Epoch 1025/4000: 100%|██████████| 1/1 [00:00<00:00, 24.02it/s]

epoch: 1024, beta = 0.001176, Train MSE: 0.010432, Train CE:0.030625, Train KL:7.130592, Val MSE:0.015147, Val CE:0.049056, Train ACC:1.000000, Val ACC:0.995833

Epoch 1026/4000: 100%|██████████| 1/1 [00:00<00:00, 23.98it/s]

epoch: 1025, beta = 0.001176, Train MSE: 0.010356, Train CE:0.030457, Train KL:7.134668, Val MSE:0.014951, Val CE:0.050459, Train ACC:1.000000, Val ACC:0.995313

Epoch 1027/4000: 100%|██████████| 1/1 [00:00<00:00, 24.08it/s]

epoch: 1026, beta = 0.001176, Train MSE: 0.010328, Train CE:0.030323, Train KL:7.139937, Val MSE:0.015133, Val CE:0.049829, Train ACC:1.000000, Val ACC:0.994271

Epoch 1028/4000: 100%|██████████| 1/1 [00:00<00:00, 23.91it/s]

epoch: 1027, beta = 0.001176, Train MSE: 0.010294, Train CE:0.030227, Train KL:7.142194, Val MSE:0.014975, Val CE:0.048183, Train ACC:1.000000, Val ACC:0.994792

Epoch 1029/4000: 100%|██████████| 1/1 [00:00<00:00, 24.04it/s]

epoch: 1028, beta = 0.001176, Train MSE: 0.010278, Train CE:0.030170, Train KL:7.145244, Val MSE:0.015137, Val CE:0.051232, Train ACC:1.000000, Val ACC:0.994792

Epoch 1030/4000: 100%|██████████| 1/1 [00:00<00:00, 23.90it/s]

epoch: 1029, beta = 0.001176, Train MSE: 0.010319, Train CE:0.030074, Train KL:7.149858, Val MSE:0.014944, Val CE:0.048963, Train ACC:1.000000, Val ACC:0.995313

Epoch 1031/4000: 100%|██████████| 1/1 [00:00<00:00, 22.29it/s]

epoch: 1030, beta = 0.001176, Train MSE: 0.010288, Train CE:0.029917, Train KL:7.151172, Val MSE:0.015043, Val CE:0.049918, Train ACC:1.000000, Val ACC:0.994792

Epoch 1032/4000: 100%|██████████| 1/1 [00:00<00:00, 20.85it/s]

epoch: 1031, beta = 0.001176, Train MSE: 0.010213, Train CE:0.029820, Train KL:7.153826, Val MSE:0.014903, Val CE:0.048550, Train ACC:1.000000, Val ACC:0.995833

Epoch 1033/4000: 100%|██████████| 1/1 [00:00<00:00, 23.67it/s]

epoch: 1032, beta = 0.001176, Train MSE: 0.010200, Train CE:0.029711, Train KL:7.156510, Val MSE:0.014847, Val CE:0.048492, Train ACC:1.000000, Val ACC:0.994271

Epoch 1034/4000: 100%|██████████| 1/1 [00:00<00:00, 24.65it/s]

epoch: 1033, beta = 0.001176, Train MSE: 0.010170, Train CE:0.029613, Train KL:7.157608, Val MSE:0.014874, Val CE:0.050425, Train ACC:1.000000, Val ACC:0.993229

Epoch 1035/4000: 100%|██████████| 1/1 [00:00<00:00, 24.24it/s]

epoch: 1034, beta = 0.001176, Train MSE: 0.010184, Train CE:0.029504, Train KL:7.159534, Val MSE:0.014851, Val CE:0.049206, Train ACC:1.000000, Val ACC:0.995833

Epoch 1036/4000: 100%|██████████| 1/1 [00:00<00:00, 23.87it/s]

epoch: 1035, beta = 0.001176, Train MSE: 0.010197, Train CE:0.029489, Train KL:7.160999, Val MSE:0.014904, Val CE:0.049157, Train ACC:1.000000, Val ACC:0.994792

Epoch 1037/4000: 100%|██████████| 1/1 [00:00<00:00, 21.73it/s]

epoch: 1036, beta = 0.001176, Train MSE: 0.010149, Train CE:0.029330, Train KL:7.162032, Val MSE:0.014849, Val CE:0.047619, Train ACC:1.000000, Val ACC:0.995313

Epoch 1038/4000: 100%|██████████| 1/1 [00:00<00:00, 23.67it/s]

epoch: 1037, beta = 0.001176, Train MSE: 0.010129, Train CE:0.029233, Train KL:7.162137, Val MSE:0.014767, Val CE:0.049002, Train ACC:1.000000, Val ACC:0.995313

Epoch 1039/4000: 100%|██████████| 1/1 [00:00<00:00, 25.35it/s]

epoch: 1038, beta = 0.001176, Train MSE: 0.010134, Train CE:0.029116, Train KL:7.163925, Val MSE:0.014692, Val CE:0.049103, Train ACC:1.000000, Val ACC:0.994271

Epoch 1040/4000: 100%|██████████| 1/1 [00:00<00:00, 24.94it/s]

epoch: 1039, beta = 0.001176, Train MSE: 0.010121, Train CE:0.028992, Train KL:7.163750, Val MSE:0.014704, Val CE:0.047848, Train ACC:1.000000, Val ACC:0.995833

Epoch 1041/4000: 100%|██████████| 1/1 [00:00<00:00, 24.02it/s]

epoch: 1040, beta = 0.001176, Train MSE: 0.010148, Train CE:0.028939, Train KL:7.163667, Val MSE:0.014833, Val CE:0.049680, Train ACC:1.000000, Val ACC:0.994792

Epoch 1042/4000: 100%|██████████| 1/1 [00:00<00:00, 26.03it/s]

epoch: 1041, beta = 0.001176, Train MSE: 0.010143, Train CE:0.028904, Train KL:7.165280, Val MSE:0.014673, Val CE:0.047532, Train ACC:1.000000, Val ACC:0.995833

Epoch 1043/4000: 100%|██████████| 1/1 [00:00<00:00, 24.07it/s]

epoch: 1042, beta = 0.001176, Train MSE: 0.010152, Train CE:0.028755, Train KL:7.164184, Val MSE:0.014834, Val CE:0.049729, Train ACC:1.000000, Val ACC:0.994271

Epoch 1044/4000: 100%|██████████| 1/1 [00:00<00:00, 23.98it/s]

epoch: 1043, beta = 0.001176, Train MSE: 0.010094, Train CE:0.028681, Train KL:7.165588, Val MSE:0.014744, Val CE:0.048064, Train ACC:1.000000, Val ACC:0.995833

Epoch 1045/4000: 100%|██████████| 1/1 [00:00<00:00, 24.53it/s]

epoch: 1044, beta = 0.001176, Train MSE: 0.010103, Train CE:0.028617, Train KL:7.164701, Val MSE:0.014682, Val CE:0.048257, Train ACC:1.000000, Val ACC:0.994792

Epoch 1046/4000: 100%|██████████| 1/1 [00:00<00:00, 24.25it/s]

epoch: 1045, beta = 0.001176, Train MSE: 0.010085, Train CE:0.028455, Train KL:7.164642, Val MSE:0.014651, Val CE:0.048550, Train ACC:1.000000, Val ACC:0.995833

Epoch 1047/4000: 100%|██████████| 1/1 [00:00<00:00, 24.74it/s]

epoch: 1046, beta = 0.001176, Train MSE: 0.010018, Train CE:0.028295, Train KL:7.166236, Val MSE:0.014756, Val CE:0.049113, Train ACC:1.000000, Val ACC:0.995833

Epoch 1048/4000: 100%|██████████| 1/1 [00:00<00:00, 24.27it/s]

epoch: 1047, beta = 0.001176, Train MSE: 0.010079, Train CE:0.028219, Train KL:7.166787, Val MSE:0.014641, Val CE:0.049080, Train ACC:1.000000, Val ACC:0.994792

Epoch 1049/4000: 100%|██████████| 1/1 [00:00<00:00, 27.42it/s]

epoch: 1048, beta = 0.001176, Train MSE: 0.010046, Train CE:0.028133, Train KL:7.166157, Val MSE:0.014606, Val CE:0.047522, Train ACC:1.000000, Val ACC:0.996354

Epoch 1050/4000: 100%|██████████| 1/1 [00:00<00:00, 23.99it/s]

epoch: 1049, beta = 0.001176, Train MSE: 0.010040, Train CE:0.028045, Train KL:7.166460, Val MSE:0.014585, Val CE:0.048446, Train ACC:1.000000, Val ACC:0.995313

Epoch 1051/4000: 100%|██████████| 1/1 [00:00<00:00, 25.70it/s]

epoch: 1050, beta = 0.001176, Train MSE: 0.010041, Train CE:0.027955, Train KL:7.168287, Val MSE:0.014568, Val CE:0.048221, Train ACC:1.000000, Val ACC:0.994271

Epoch 1052/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 1051, beta = 0.001176, Train MSE: 0.009990, Train CE:0.027839, Train KL:7.167268, Val MSE:0.014522, Val CE:0.047561, Train ACC:1.000000, Val ACC:0.995313

Epoch 1053/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 1052, beta = 0.001176, Train MSE: 0.010038, Train CE:0.027772, Train KL:7.167719, Val MSE:0.014777, Val CE:0.049751, Train ACC:1.000000, Val ACC:0.994271

Epoch 1054/4000: 100%|██████████| 1/1 [00:00<00:00, 24.61it/s]

epoch: 1053, beta = 0.001176, Train MSE: 0.010057, Train CE:0.027691, Train KL:7.170095, Val MSE:0.014687, Val CE:0.047102, Train ACC:1.000000, Val ACC:0.995313

Epoch 1055/4000: 100%|██████████| 1/1 [00:00<00:00, 24.02it/s]

epoch: 1054, beta = 0.001176, Train MSE: 0.010077, Train CE:0.027613, Train KL:7.168591, Val MSE:0.014712, Val CE:0.049405, Train ACC:1.000000, Val ACC:0.994792

Epoch 1056/4000: 100%|██████████| 1/1 [00:00<00:00, 23.95it/s]

epoch: 1055, beta = 0.001176, Train MSE: 0.009930, Train CE:0.027593, Train KL:7.171352, Val MSE:0.014617, Val CE:0.046694, Train ACC:1.000000, Val ACC:0.995833

Epoch 1057/4000: 100%|██████████| 1/1 [00:00<00:00, 24.75it/s]

epoch: 1056, beta = 0.001176, Train MSE: 0.009975, Train CE:0.027433, Train KL:7.171095, Val MSE:0.014634, Val CE:0.047874, Train ACC:1.000000, Val ACC:0.994792

Epoch 1058/4000: 100%|██████████| 1/1 [00:00<00:00, 23.48it/s]

epoch: 1057, beta = 0.001176, Train MSE: 0.009903, Train CE:0.027272, Train KL:7.172314, Val MSE:0.014608, Val CE:0.048178, Train ACC:1.000000, Val ACC:0.995313

Epoch 1059/4000: 100%|██████████| 1/1 [00:00<00:00, 23.63it/s]

epoch: 1058, beta = 0.001176, Train MSE: 0.009872, Train CE:0.027154, Train KL:7.174795, Val MSE:0.014515, Val CE:0.048730, Train ACC:1.000000, Val ACC:0.994792

Epoch 1060/4000: 100%|██████████| 1/1 [00:00<00:00, 23.95it/s]

epoch: 1059, beta = 0.001176, Train MSE: 0.009869, Train CE:0.027055, Train KL:7.175307, Val MSE:0.014623, Val CE:0.048755, Train ACC:1.000000, Val ACC:0.994271

Epoch 1061/4000: 100%|██████████| 1/1 [00:00<00:00, 24.26it/s]

epoch: 1060, beta = 0.001176, Train MSE: 0.009892, Train CE:0.027015, Train KL:7.175394, Val MSE:0.014607, Val CE:0.047648, Train ACC:1.000000, Val ACC:0.995313

Epoch 1062/4000: 100%|██████████| 1/1 [00:00<00:00, 17.42it/s]

epoch: 1061, beta = 0.001176, Train MSE: 0.009856, Train CE:0.026917, Train KL:7.177010, Val MSE:0.014350, Val CE:0.047995, Train ACC:1.000000, Val ACC:0.994792

Epoch 1063/4000: 100%|██████████| 1/1 [00:00<00:00, 23.29it/s]

epoch: 1062, beta = 0.001176, Train MSE: 0.009821, Train CE:0.026789, Train KL:7.178573, Val MSE:0.014392, Val CE:0.047158, Train ACC:1.000000, Val ACC:0.995833

Epoch 1064/4000: 100%|██████████| 1/1 [00:00<00:00, 24.07it/s]

epoch: 1063, beta = 0.001176, Train MSE: 0.009858, Train CE:0.026735, Train KL:7.178658, Val MSE:0.014578, Val CE:0.046886, Train ACC:1.000000, Val ACC:0.995833

Epoch 1065/4000: 100%|██████████| 1/1 [00:00<00:00, 23.86it/s]

epoch: 1064, beta = 0.001176, Train MSE: 0.009821, Train CE:0.026636, Train KL:7.179595, Val MSE:0.014414, Val CE:0.046827, Train ACC:1.000000, Val ACC:0.995833

Epoch 1066/4000: 100%|██████████| 1/1 [00:00<00:00, 24.73it/s]

epoch: 1065, beta = 0.000824, Train MSE: 0.009827, Train CE:0.026542, Train KL:7.180280, Val MSE:0.014388, Val CE:0.046977, Train ACC:1.000000, Val ACC:0.996354

Epoch 1067/4000: 100%|██████████| 1/1 [00:00<00:00, 24.17it/s]

Learning rate updated: 0.0006983372960937497
epoch: 1066, beta = 0.000824, Train MSE: 0.009800, Train CE:0.026438, Train KL:7.181728, Val MSE:0.014413, Val CE:0.048139, Train ACC:1.000000, Val ACC:0.995313

Epoch 1068/4000: 100%|██████████| 1/1 [00:00<00:00, 24.02it/s]

epoch: 1067, beta = 0.000824, Train MSE: 0.009807, Train CE:0.026420, Train KL:7.184441, Val MSE:0.014270, Val CE:0.045173, Train ACC:1.000000, Val ACC:0.996354

Epoch 1069/4000: 100%|██████████| 1/1 [00:00<00:00, 23.91it/s]

epoch: 1068, beta = 0.000824, Train MSE: 0.009828, Train CE:0.026540, Train KL:7.185260, Val MSE:0.014580, Val CE:0.049284, Train ACC:1.000000, Val ACC:0.993750

Epoch 1070/4000: 100%|██████████| 1/1 [00:00<00:00, 24.93it/s]

epoch: 1069, beta = 0.000824, Train MSE: 0.009866, Train CE:0.026420, Train KL:7.192250, Val MSE:0.014260, Val CE:0.046845, Train ACC:1.000000, Val ACC:0.994792

Epoch 1071/4000: 100%|██████████| 1/1 [00:00<00:00, 23.97it/s]

epoch: 1070, beta = 0.000824, Train MSE: 0.009982, Train CE:0.026190, Train KL:7.196621, Val MSE:0.014388, Val CE:0.048221, Train ACC:1.000000, Val ACC:0.994271

Epoch 1072/4000: 100%|██████████| 1/1 [00:00<00:00, 24.13it/s]

epoch: 1071, beta = 0.000824, Train MSE: 0.009751, Train CE:0.026013, Train KL:7.202811, Val MSE:0.014303, Val CE:0.047428, Train ACC:1.000000, Val ACC:0.994792

Epoch 1073/4000: 100%|██████████| 1/1 [00:00<00:00, 24.21it/s]

epoch: 1072, beta = 0.000824, Train MSE: 0.009768, Train CE:0.025941, Train KL:7.208480, Val MSE:0.014190, Val CE:0.046419, Train ACC:1.000000, Val ACC:0.994271

Epoch 1074/4000: 100%|██████████| 1/1 [00:00<00:00, 24.88it/s]

epoch: 1073, beta = 0.000824, Train MSE: 0.009788, Train CE:0.025887, Train KL:7.215396, Val MSE:0.014250, Val CE:0.047246, Train ACC:1.000000, Val ACC:0.995313

Epoch 1075/4000: 100%|██████████| 1/1 [00:00<00:00, 23.94it/s]

epoch: 1074, beta = 0.000824, Train MSE: 0.009705, Train CE:0.025862, Train KL:7.223929, Val MSE:0.014119, Val CE:0.046374, Train ACC:1.000000, Val ACC:0.995833

Epoch 1076/4000: 100%|██████████| 1/1 [00:00<00:00, 23.54it/s]

epoch: 1075, beta = 0.000824, Train MSE: 0.009660, Train CE:0.025691, Train KL:7.229825, Val MSE:0.014318, Val CE:0.046255, Train ACC:1.000000, Val ACC:0.995833

Epoch 1077/4000: 100%|██████████| 1/1 [00:00<00:00, 23.57it/s]

epoch: 1076, beta = 0.000824, Train MSE: 0.009640, Train CE:0.025589, Train KL:7.238070, Val MSE:0.014217, Val CE:0.047489, Train ACC:1.000000, Val ACC:0.994792

Epoch 1078/4000: 100%|██████████| 1/1 [00:00<00:00, 22.84it/s]

epoch: 1077, beta = 0.000576, Train MSE: 0.009612, Train CE:0.025505, Train KL:7.247427, Val MSE:0.014101, Val CE:0.046910, Train ACC:1.000000, Val ACC:0.995833

Epoch 1079/4000: 100%|██████████| 1/1 [00:00<00:00, 23.78it/s]

Learning rate updated: 0.0006634204312890621
epoch: 1078, beta = 0.000576, Train MSE: 0.009611, Train CE:0.025413, Train KL:7.255180, Val MSE:0.014170, Val CE:0.047490, Train ACC:1.000000, Val ACC:0.994792

Epoch 1080/4000: 100%|██████████| 1/1 [00:00<00:00, 24.01it/s]

epoch: 1079, beta = 0.000576, Train MSE: 0.009606, Train CE:0.025326, Train KL:7.264114, Val MSE:0.014073, Val CE:0.046727, Train ACC:1.000000, Val ACC:0.995833

Epoch 1081/4000: 100%|██████████| 1/1 [00:00<00:00, 23.41it/s]

epoch: 1080, beta = 0.000576, Train MSE: 0.009538, Train CE:0.025270, Train KL:7.273279, Val MSE:0.014075, Val CE:0.046192, Train ACC:1.000000, Val ACC:0.994792

Epoch 1082/4000: 100%|██████████| 1/1 [00:00<00:00, 25.40it/s]

epoch: 1081, beta = 0.000576, Train MSE: 0.009530, Train CE:0.025166, Train KL:7.283472, Val MSE:0.014082, Val CE:0.047711, Train ACC:1.000000, Val ACC:0.994792

Epoch 1083/4000: 100%|██████████| 1/1 [00:00<00:00, 23.92it/s]

epoch: 1082, beta = 0.000576, Train MSE: 0.009505, Train CE:0.025094, Train KL:7.294430, Val MSE:0.014050, Val CE:0.046560, Train ACC:1.000000, Val ACC:0.995833

Epoch 1084/4000: 100%|██████████| 1/1 [00:00<00:00, 23.81it/s]

epoch: 1083, beta = 0.000576, Train MSE: 0.009498, Train CE:0.025061, Train KL:7.305134, Val MSE:0.014115, Val CE:0.046654, Train ACC:1.000000, Val ACC:0.995833

Epoch 1085/4000: 100%|██████████| 1/1 [00:00<00:00, 24.08it/s]

epoch: 1084, beta = 0.000576, Train MSE: 0.009471, Train CE:0.024908, Train KL:7.315576, Val MSE:0.013982, Val CE:0.046923, Train ACC:1.000000, Val ACC:0.994792

Epoch 1086/4000: 100%|██████████| 1/1 [00:00<00:00, 22.66it/s]

epoch: 1085, beta = 0.000576, Train MSE: 0.009417, Train CE:0.024881, Train KL:7.326993, Val MSE:0.013926, Val CE:0.045985, Train ACC:1.000000, Val ACC:0.995833

Epoch 1087/4000: 100%|██████████| 1/1 [00:00<00:00, 23.13it/s]

epoch: 1086, beta = 0.000576, Train MSE: 0.009469, Train CE:0.024795, Train KL:7.338274, Val MSE:0.014007, Val CE:0.046670, Train ACC:1.000000, Val ACC:0.995313

Epoch 1088/4000: 100%|██████████| 1/1 [00:00<00:00, 23.44it/s]

epoch: 1087, beta = 0.000576, Train MSE: 0.009407, Train CE:0.024713, Train KL:7.349273, Val MSE:0.013971, Val CE:0.046528, Train ACC:1.000000, Val ACC:0.995833

Epoch 1089/4000: 100%|██████████| 1/1 [00:00<00:00, 23.36it/s]

epoch: 1088, beta = 0.000576, Train MSE: 0.009391, Train CE:0.024681, Train KL:7.360440, Val MSE:0.013899, Val CE:0.046952, Train ACC:1.000000, Val ACC:0.995833

Epoch 1090/4000: 100%|██████████| 1/1 [00:00<00:00, 23.98it/s]

Learning rate updated: 0.000630249409724609
epoch: 1089, beta = 0.000576, Train MSE: 0.009391, Train CE:0.024546, Train KL:7.372036, Val MSE:0.013944, Val CE:0.046425, Train ACC:1.000000, Val ACC:0.995313

Epoch 1091/4000: 100%|██████████| 1/1 [00:00<00:00, 21.79it/s]

epoch: 1090, beta = 0.000576, Train MSE: 0.009382, Train CE:0.024461, Train KL:7.383219, Val MSE:0.013791, Val CE:0.045900, Train ACC:1.000000, Val ACC:0.995833

Epoch 1092/4000: 100%|██████████| 1/1 [00:00<00:00, 20.50it/s]

epoch: 1091, beta = 0.000576, Train MSE: 0.009337, Train CE:0.024401, Train KL:7.393449, Val MSE:0.013921, Val CE:0.046437, Train ACC:1.000000, Val ACC:0.995313

Epoch 1093/4000: 100%|██████████| 1/1 [00:00<00:00, 21.41it/s]

epoch: 1092, beta = 0.000576, Train MSE: 0.009332, Train CE:0.024299, Train KL:7.403748, Val MSE:0.013835, Val CE:0.046350, Train ACC:1.000000, Val ACC:0.995313

Epoch 1094/4000: 100%|██████████| 1/1 [00:00<00:00, 21.83it/s]

epoch: 1093, beta = 0.000576, Train MSE: 0.009337, Train CE:0.024247, Train KL:7.414140, Val MSE:0.013767, Val CE:0.045994, Train ACC:1.000000, Val ACC:0.995833

Epoch 1095/4000: 100%|██████████| 1/1 [00:00<00:00, 23.78it/s]

epoch: 1094, beta = 0.000576, Train MSE: 0.009309, Train CE:0.024188, Train KL:7.424633, Val MSE:0.013740, Val CE:0.044987, Train ACC:1.000000, Val ACC:0.995833

Epoch 1096/4000: 100%|██████████| 1/1 [00:00<00:00, 23.88it/s]

epoch: 1095, beta = 0.000576, Train MSE: 0.009281, Train CE:0.024088, Train KL:7.433846, Val MSE:0.013755, Val CE:0.044948, Train ACC:1.000000, Val ACC:0.994792

Epoch 1097/4000: 100%|██████████| 1/1 [00:00<00:00, 24.44it/s]

epoch: 1096, beta = 0.000576, Train MSE: 0.009272, Train CE:0.024048, Train KL:7.443436, Val MSE:0.013703, Val CE:0.044880, Train ACC:1.000000, Val ACC:0.995313

Epoch 1098/4000: 100%|██████████| 1/1 [00:00<00:00, 24.56it/s]

epoch: 1097, beta = 0.000576, Train MSE: 0.009232, Train CE:0.023952, Train KL:7.452865, Val MSE:0.013614, Val CE:0.045074, Train ACC:1.000000, Val ACC:0.994792

Epoch 1099/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 1098, beta = 0.000576, Train MSE: 0.009223, Train CE:0.023886, Train KL:7.461987, Val MSE:0.013716, Val CE:0.045991, Train ACC:1.000000, Val ACC:0.994792

Epoch 1100/4000: 100%|██████████| 1/1 [00:00<00:00, 24.03it/s]

epoch: 1099, beta = 0.000576, Train MSE: 0.009219, Train CE:0.023827, Train KL:7.470861, Val MSE:0.013734, Val CE:0.045196, Train ACC:1.000000, Val ACC:0.994792

Epoch 1101/4000: 100%|██████████| 1/1 [00:00<00:00, 24.41it/s]

epoch: 1100, beta = 0.000576, Train MSE: 0.009176, Train CE:0.023731, Train KL:7.479177, Val MSE:0.013590, Val CE:0.046142, Train ACC:1.000000, Val ACC:0.995833

Epoch 1102/4000: 100%|██████████| 1/1 [00:00<00:00, 23.51it/s]

epoch: 1101, beta = 0.000576, Train MSE: 0.009200, Train CE:0.023670, Train KL:7.487443, Val MSE:0.013523, Val CE:0.045972, Train ACC:1.000000, Val ACC:0.994792

Epoch 1103/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 1102, beta = 0.000576, Train MSE: 0.009133, Train CE:0.023609, Train KL:7.495394, Val MSE:0.013688, Val CE:0.045696, Train ACC:1.000000, Val ACC:0.995833

Epoch 1104/4000: 100%|██████████| 1/1 [00:00<00:00, 23.96it/s]

epoch: 1103, beta = 0.000576, Train MSE: 0.009138, Train CE:0.023535, Train KL:7.502771, Val MSE:0.013609, Val CE:0.046252, Train ACC:1.000000, Val ACC:0.994792

Epoch 1105/4000: 100%|██████████| 1/1 [00:00<00:00, 23.97it/s]

epoch: 1104, beta = 0.000576, Train MSE: 0.009118, Train CE:0.023460, Train KL:7.509964, Val MSE:0.013608, Val CE:0.046384, Train ACC:1.000000, Val ACC:0.994271

Epoch 1106/4000: 100%|██████████| 1/1 [00:00<00:00, 24.29it/s]

epoch: 1105, beta = 0.000576, Train MSE: 0.009114, Train CE:0.023427, Train KL:7.516615, Val MSE:0.013544, Val CE:0.045005, Train ACC:1.000000, Val ACC:0.995833

Epoch 1107/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 1106, beta = 0.000404, Train MSE: 0.009096, Train CE:0.023328, Train KL:7.523407, Val MSE:0.013548, Val CE:0.046080, Train ACC:1.000000, Val ACC:0.994271

Epoch 1108/4000: 100%|██████████| 1/1 [00:00<00:00, 24.02it/s]

Learning rate updated: 0.0005987369392383785
epoch: 1107, beta = 0.000404, Train MSE: 0.009101, Train CE:0.023260, Train KL:7.529653, Val MSE:0.013431, Val CE:0.045346, Train ACC:1.000000, Val ACC:0.995833

Epoch 1109/4000: 100%|██████████| 1/1 [00:00<00:00, 24.06it/s]

epoch: 1108, beta = 0.000404, Train MSE: 0.009100, Train CE:0.023207, Train KL:7.535276, Val MSE:0.013420, Val CE:0.044728, Train ACC:1.000000, Val ACC:0.995833

Epoch 1110/4000: 100%|██████████| 1/1 [00:00<00:00, 24.01it/s]

epoch: 1109, beta = 0.000404, Train MSE: 0.009078, Train CE:0.023142, Train KL:7.541767, Val MSE:0.013567, Val CE:0.045698, Train ACC:1.000000, Val ACC:0.994792

Epoch 1111/4000: 100%|██████████| 1/1 [00:00<00:00, 25.31it/s]

epoch: 1110, beta = 0.000404, Train MSE: 0.009110, Train CE:0.023094, Train KL:7.548820, Val MSE:0.013454, Val CE:0.043632, Train ACC:1.000000, Val ACC:0.996354

Epoch 1112/4000: 100%|██████████| 1/1 [00:00<00:00, 25.36it/s]

epoch: 1111, beta = 0.000404, Train MSE: 0.009054, Train CE:0.023041, Train KL:7.555067, Val MSE:0.013477, Val CE:0.044871, Train ACC:1.000000, Val ACC:0.995313

Epoch 1113/4000: 100%|██████████| 1/1 [00:00<00:00, 25.02it/s]

epoch: 1112, beta = 0.000404, Train MSE: 0.009039, Train CE:0.022928, Train KL:7.562629, Val MSE:0.013332, Val CE:0.045011, Train ACC:1.000000, Val ACC:0.995313

Epoch 1114/4000: 100%|██████████| 1/1 [00:00<00:00, 22.48it/s]

epoch: 1113, beta = 0.000404, Train MSE: 0.009005, Train CE:0.022908, Train KL:7.569766, Val MSE:0.013348, Val CE:0.044025, Train ACC:1.000000, Val ACC:0.995833

Epoch 1115/4000: 100%|██████████| 1/1 [00:00<00:00, 20.60it/s]

epoch: 1114, beta = 0.000404, Train MSE: 0.009017, Train CE:0.022821, Train KL:7.576482, Val MSE:0.013400, Val CE:0.045447, Train ACC:1.000000, Val ACC:0.994792

Epoch 1116/4000: 100%|██████████| 1/1 [00:00<00:00, 24.24it/s]

epoch: 1115, beta = 0.000404, Train MSE: 0.009020, Train CE:0.022756, Train KL:7.583942, Val MSE:0.013262, Val CE:0.045321, Train ACC:1.000000, Val ACC:0.995833

Epoch 1117/4000: 100%|██████████| 1/1 [00:00<00:00, 23.95it/s]

epoch: 1116, beta = 0.000404, Train MSE: 0.009004, Train CE:0.022689, Train KL:7.591660, Val MSE:0.013251, Val CE:0.045108, Train ACC:1.000000, Val ACC:0.994792

Epoch 1118/4000: 100%|██████████| 1/1 [00:00<00:00, 23.97it/s]

epoch: 1117, beta = 0.000404, Train MSE: 0.008986, Train CE:0.022611, Train KL:7.598196, Val MSE:0.013254, Val CE:0.045301, Train ACC:1.000000, Val ACC:0.994271

Epoch 1119/4000: 100%|██████████| 1/1 [00:00<00:00, 23.97it/s]

epoch: 1118, beta = 0.000404, Train MSE: 0.008983, Train CE:0.022549, Train KL:7.605603, Val MSE:0.013222, Val CE:0.044022, Train ACC:1.000000, Val ACC:0.995833

Epoch 1120/4000: 100%|██████████| 1/1 [00:00<00:00, 24.01it/s]

epoch: 1119, beta = 0.000404, Train MSE: 0.008949, Train CE:0.022504, Train KL:7.613335, Val MSE:0.013166, Val CE:0.045125, Train ACC:1.000000, Val ACC:0.994792

Epoch 1121/4000: 100%|██████████| 1/1 [00:00<00:00, 24.02it/s]

epoch: 1120, beta = 0.000282, Train MSE: 0.008914, Train CE:0.022432, Train KL:7.620543, Val MSE:0.013169, Val CE:0.044925, Train ACC:1.000000, Val ACC:0.994792

Epoch 1122/4000: 100%|██████████| 1/1 [00:00<00:00, 23.78it/s]

Learning rate updated: 0.0005688000922764595
epoch: 1121, beta = 0.000282, Train MSE: 0.008929, Train CE:0.022368, Train KL:7.626655, Val MSE:0.013231, Val CE:0.044229, Train ACC:1.000000, Val ACC:0.994792

Epoch 1123/4000: 100%|██████████| 1/1 [00:00<00:00, 24.04it/s]

epoch: 1122, beta = 0.000282, Train MSE: 0.008942, Train CE:0.022306, Train KL:7.633695, Val MSE:0.013268, Val CE:0.045336, Train ACC:1.000000, Val ACC:0.994271

Epoch 1124/4000: 100%|██████████| 1/1 [00:00<00:00, 26.35it/s]

epoch: 1123, beta = 0.000282, Train MSE: 0.008914, Train CE:0.022262, Train KL:7.641241, Val MSE:0.013141, Val CE:0.045318, Train ACC:1.000000, Val ACC:0.994792

Epoch 1125/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 1124, beta = 0.000282, Train MSE: 0.008885, Train CE:0.022201, Train KL:7.648777, Val MSE:0.013156, Val CE:0.044592, Train ACC:1.000000, Val ACC:0.994792

Epoch 1126/4000: 100%|██████████| 1/1 [00:00<00:00, 24.21it/s]

epoch: 1125, beta = 0.000282, Train MSE: 0.008881, Train CE:0.022126, Train KL:7.656440, Val MSE:0.013194, Val CE:0.044605, Train ACC:1.000000, Val ACC:0.995833

Epoch 1127/4000: 100%|██████████| 1/1 [00:00<00:00, 28.84it/s]

epoch: 1126, beta = 0.000282, Train MSE: 0.008888, Train CE:0.022061, Train KL:7.664380, Val MSE:0.013184, Val CE:0.043982, Train ACC:1.000000, Val ACC:0.995833

Epoch 1128/4000: 100%|██████████| 1/1 [00:00<00:00, 23.95it/s]

epoch: 1127, beta = 0.000282, Train MSE: 0.008863, Train CE:0.022014, Train KL:7.671845, Val MSE:0.013220, Val CE:0.043646, Train ACC:1.000000, Val ACC:0.995833

Epoch 1129/4000: 100%|██████████| 1/1 [00:00<00:00, 24.04it/s]

epoch: 1128, beta = 0.000282, Train MSE: 0.008861, Train CE:0.021948, Train KL:7.680290, Val MSE:0.013266, Val CE:0.044815, Train ACC:1.000000, Val ACC:0.995833

Epoch 1130/4000: 100%|██████████| 1/1 [00:00<00:00, 24.03it/s]

epoch: 1129, beta = 0.000282, Train MSE: 0.008834, Train CE:0.021944, Train KL:7.689142, Val MSE:0.013162, Val CE:0.043691, Train ACC:1.000000, Val ACC:0.995833

Epoch 1131/4000: 100%|██████████| 1/1 [00:00<00:00, 23.94it/s]

epoch: 1130, beta = 0.000282, Train MSE: 0.008837, Train CE:0.021829, Train KL:7.696392, Val MSE:0.013205, Val CE:0.043951, Train ACC:1.000000, Val ACC:0.995833

Epoch 1132/4000: 100%|██████████| 1/1 [00:00<00:00, 23.89it/s]

epoch: 1131, beta = 0.000282, Train MSE: 0.008801, Train CE:0.021777, Train KL:7.704806, Val MSE:0.013185, Val CE:0.044682, Train ACC:1.000000, Val ACC:0.995833

Epoch 1133/4000: 100%|██████████| 1/1 [00:00<00:00, 24.03it/s]

Learning rate updated: 0.0005403600876626365
epoch: 1132, beta = 0.000282, Train MSE: 0.008771, Train CE:0.021723, Train KL:7.713709, Val MSE:0.013087, Val CE:0.044087, Train ACC:1.000000, Val ACC:0.994792

Epoch 1134/4000: 100%|██████████| 1/1 [00:00<00:00, 27.11it/s]

epoch: 1133, beta = 0.000282, Train MSE: 0.008787, Train CE:0.021658, Train KL:7.721244, Val MSE:0.013034, Val CE:0.044431, Train ACC:1.000000, Val ACC:0.994792

Epoch 1135/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 1134, beta = 0.000282, Train MSE: 0.008767, Train CE:0.021590, Train KL:7.728727, Val MSE:0.013165, Val CE:0.044986, Train ACC:1.000000, Val ACC:0.994792

Epoch 1136/4000: 100%|██████████| 1/1 [00:00<00:00, 22.99it/s]

epoch: 1135, beta = 0.000282, Train MSE: 0.008755, Train CE:0.021558, Train KL:7.736722, Val MSE:0.013059, Val CE:0.043949, Train ACC:1.000000, Val ACC:0.994792

Epoch 1137/4000: 100%|██████████| 1/1 [00:00<00:00, 24.04it/s]

epoch: 1136, beta = 0.000282, Train MSE: 0.008748, Train CE:0.021492, Train KL:7.743749, Val MSE:0.013053, Val CE:0.044583, Train ACC:1.000000, Val ACC:0.994792

Epoch 1138/4000: 100%|██████████| 1/1 [00:00<00:00, 24.09it/s]

epoch: 1137, beta = 0.000282, Train MSE: 0.008721, Train CE:0.021448, Train KL:7.751283, Val MSE:0.013008, Val CE:0.044886, Train ACC:1.000000, Val ACC:0.994792

Epoch 1139/4000: 100%|██████████| 1/1 [00:00<00:00, 23.57it/s]

epoch: 1138, beta = 0.000282, Train MSE: 0.008701, Train CE:0.021383, Train KL:7.758874, Val MSE:0.013051, Val CE:0.044496, Train ACC:1.000000, Val ACC:0.995313

Epoch 1140/4000: 100%|██████████| 1/1 [00:00<00:00, 24.36it/s]

epoch: 1139, beta = 0.000282, Train MSE: 0.008718, Train CE:0.021336, Train KL:7.766100, Val MSE:0.012970, Val CE:0.044510, Train ACC:1.000000, Val ACC:0.995833

Epoch 1141/4000: 100%|██████████| 1/1 [00:00<00:00, 23.98it/s]

epoch: 1140, beta = 0.000282, Train MSE: 0.008705, Train CE:0.021266, Train KL:7.772670, Val MSE:0.013007, Val CE:0.044168, Train ACC:1.000000, Val ACC:0.995833

Epoch 1142/4000: 100%|██████████| 1/1 [00:00<00:00, 22.96it/s]

epoch: 1141, beta = 0.000282, Train MSE: 0.008709, Train CE:0.021215, Train KL:7.779515, Val MSE:0.012925, Val CE:0.043841, Train ACC:1.000000, Val ACC:0.995313

Epoch 1143/4000: 100%|██████████| 1/1 [00:00<00:00, 24.01it/s]

epoch: 1142, beta = 0.000282, Train MSE: 0.008662, Train CE:0.021175, Train KL:7.787002, Val MSE:0.012964, Val CE:0.043887, Train ACC:1.000000, Val ACC:0.994792

Epoch 1144/4000: 100%|██████████| 1/1 [00:00<00:00, 19.01it/s]

Learning rate updated: 0.0005133420832795047
epoch: 1143, beta = 0.000282, Train MSE: 0.008653, Train CE:0.021113, Train KL:7.793622, Val MSE:0.012929, Val CE:0.044304, Train ACC:1.000000, Val ACC:0.994792

Epoch 1145/4000: 100%|██████████| 1/1 [00:00<00:00, 23.03it/s]

epoch: 1144, beta = 0.000282, Train MSE: 0.008661, Train CE:0.021060, Train KL:7.799905, Val MSE:0.012848, Val CE:0.044735, Train ACC:1.000000, Val ACC:0.994792

Epoch 1146/4000: 100%|██████████| 1/1 [00:00<00:00, 24.44it/s]

epoch: 1145, beta = 0.000282, Train MSE: 0.008654, Train CE:0.021015, Train KL:7.806367, Val MSE:0.012801, Val CE:0.044252, Train ACC:1.000000, Val ACC:0.994792

Epoch 1147/4000: 100%|██████████| 1/1 [00:00<00:00, 20.91it/s]

epoch: 1146, beta = 0.000282, Train MSE: 0.008657, Train CE:0.020952, Train KL:7.812972, Val MSE:0.012888, Val CE:0.044078, Train ACC:1.000000, Val ACC:0.994792

Epoch 1148/4000: 100%|██████████| 1/1 [00:00<00:00, 24.09it/s]

epoch: 1147, beta = 0.000282, Train MSE: 0.008624, Train CE:0.020890, Train KL:7.818965, Val MSE:0.012799, Val CE:0.043444, Train ACC:1.000000, Val ACC:0.995313

Epoch 1149/4000: 100%|██████████| 1/1 [00:00<00:00, 23.59it/s]

epoch: 1148, beta = 0.000282, Train MSE: 0.008618, Train CE:0.020863, Train KL:7.824353, Val MSE:0.012772, Val CE:0.044185, Train ACC:1.000000, Val ACC:0.994792

Epoch 1150/4000: 100%|██████████| 1/1 [00:00<00:00, 21.81it/s]

epoch: 1149, beta = 0.000282, Train MSE: 0.008589, Train CE:0.020813, Train KL:7.830406, Val MSE:0.012798, Val CE:0.044419, Train ACC:1.000000, Val ACC:0.995313

Epoch 1151/4000: 100%|██████████| 1/1 [00:00<00:00, 21.53it/s]

epoch: 1150, beta = 0.000282, Train MSE: 0.008602, Train CE:0.020761, Train KL:7.835782, Val MSE:0.012770, Val CE:0.044119, Train ACC:1.000000, Val ACC:0.995313

Epoch 1152/4000: 100%|██████████| 1/1 [00:00<00:00, 28.88it/s]

epoch: 1151, beta = 0.000282, Train MSE: 0.008575, Train CE:0.020711, Train KL:7.841247, Val MSE:0.012820, Val CE:0.043896, Train ACC:1.000000, Val ACC:0.995313

Epoch 1153/4000: 100%|██████████| 1/1 [00:00<00:00, 23.97it/s]

epoch: 1152, beta = 0.000282, Train MSE: 0.008578, Train CE:0.020657, Train KL:7.847083, Val MSE:0.012803, Val CE:0.043537, Train ACC:1.000000, Val ACC:0.995313

Epoch 1154/4000: 100%|██████████| 1/1 [00:00<00:00, 23.54it/s]

epoch: 1153, beta = 0.000282, Train MSE: 0.008551, Train CE:0.020604, Train KL:7.852402, Val MSE:0.012792, Val CE:0.043203, Train ACC:1.000000, Val ACC:0.994792

Epoch 1155/4000: 100%|██████████| 1/1 [00:00<00:00, 24.02it/s]

epoch: 1154, beta = 0.000282, Train MSE: 0.008581, Train CE:0.020564, Train KL:7.856946, Val MSE:0.012768, Val CE:0.044064, Train ACC:1.000000, Val ACC:0.994792

Epoch 1156/4000: 100%|██████████| 1/1 [00:00<00:00, 24.60it/s]

epoch: 1155, beta = 0.000282, Train MSE: 0.008543, Train CE:0.020523, Train KL:7.862222, Val MSE:0.012747, Val CE:0.043245, Train ACC:1.000000, Val ACC:0.994792

Epoch 1157/4000: 100%|██████████| 1/1 [00:00<00:00, 23.62it/s]

epoch: 1156, beta = 0.000282, Train MSE: 0.008532, Train CE:0.020453, Train KL:7.866838, Val MSE:0.012747, Val CE:0.043721, Train ACC:1.000000, Val ACC:0.994792

Epoch 1158/4000: 100%|██████████| 1/1 [00:00<00:00, 22.83it/s]

epoch: 1157, beta = 0.000282, Train MSE: 0.008525, Train CE:0.020427, Train KL:7.871967, Val MSE:0.012698, Val CE:0.044033, Train ACC:1.000000, Val ACC:0.994792

Epoch 1159/4000: 100%|██████████| 1/1 [00:00<00:00, 22.60it/s]

epoch: 1158, beta = 0.000282, Train MSE: 0.008518, Train CE:0.020383, Train KL:7.876967, Val MSE:0.012708, Val CE:0.043514, Train ACC:1.000000, Val ACC:0.994271

Epoch 1160/4000: 100%|██████████| 1/1 [00:00<00:00, 20.86it/s]

epoch: 1159, beta = 0.000282, Train MSE: 0.008505, Train CE:0.020319, Train KL:7.881260, Val MSE:0.012724, Val CE:0.043864, Train ACC:1.000000, Val ACC:0.994792

Epoch 1161/4000: 100%|██████████| 1/1 [00:00<00:00, 22.88it/s]

epoch: 1160, beta = 0.000282, Train MSE: 0.008507, Train CE:0.020252, Train KL:7.886327, Val MSE:0.012662, Val CE:0.043902, Train ACC:1.000000, Val ACC:0.994792

Epoch 1162/4000: 100%|██████████| 1/1 [00:00<00:00, 22.28it/s]

epoch: 1161, beta = 0.000282, Train MSE: 0.008478, Train CE:0.020229, Train KL:7.890943, Val MSE:0.012726, Val CE:0.043477, Train ACC:1.000000, Val ACC:0.995833

Epoch 1163/4000: 100%|██████████| 1/1 [00:00<00:00, 24.10it/s]

epoch: 1162, beta = 0.000282, Train MSE: 0.008490, Train CE:0.020187, Train KL:7.895147, Val MSE:0.012723, Val CE:0.044553, Train ACC:1.000000, Val ACC:0.995833

Epoch 1164/4000: 100%|██████████| 1/1 [00:00<00:00, 25.12it/s]

epoch: 1163, beta = 0.000198, Train MSE: 0.008479, Train CE:0.020122, Train KL:7.900073, Val MSE:0.012704, Val CE:0.043812, Train ACC:1.000000, Val ACC:0.995313

Epoch 1165/4000: 100%|██████████| 1/1 [00:00<00:00, 23.10it/s]

Learning rate updated: 0.00048767497911552944
epoch: 1164, beta = 0.000198, Train MSE: 0.008469, Train CE:0.020079, Train KL:7.904239, Val MSE:0.012694, Val CE:0.043940, Train ACC:1.000000, Val ACC:0.995833

Epoch 1166/4000: 100%|██████████| 1/1 [00:00<00:00, 24.61it/s]

epoch: 1165, beta = 0.000198, Train MSE: 0.008445, Train CE:0.020026, Train KL:7.908692, Val MSE:0.012701, Val CE:0.044229, Train ACC:1.000000, Val ACC:0.994792

Epoch 1167/4000: 100%|██████████| 1/1 [00:00<00:00, 24.38it/s]

epoch: 1166, beta = 0.000198, Train MSE: 0.008450, Train CE:0.020003, Train KL:7.913059, Val MSE:0.012624, Val CE:0.043203, Train ACC:1.000000, Val ACC:0.994271

Epoch 1168/4000: 100%|██████████| 1/1 [00:00<00:00, 23.38it/s]

epoch: 1167, beta = 0.000198, Train MSE: 0.008447, Train CE:0.019934, Train KL:7.917383, Val MSE:0.012629, Val CE:0.043877, Train ACC:1.000000, Val ACC:0.994271

Epoch 1169/4000: 100%|██████████| 1/1 [00:00<00:00, 24.02it/s]

epoch: 1168, beta = 0.000198, Train MSE: 0.008429, Train CE:0.019906, Train KL:7.922194, Val MSE:0.012595, Val CE:0.043961, Train ACC:1.000000, Val ACC:0.994271

Epoch 1170/4000: 100%|██████████| 1/1 [00:00<00:00, 24.42it/s]

epoch: 1169, beta = 0.000198, Train MSE: 0.008416, Train CE:0.019852, Train KL:7.926548, Val MSE:0.012616, Val CE:0.043237, Train ACC:1.000000, Val ACC:0.994792

Epoch 1171/4000: 100%|██████████| 1/1 [00:00<00:00, 19.66it/s]

epoch: 1170, beta = 0.000198, Train MSE: 0.008413, Train CE:0.019816, Train KL:7.931172, Val MSE:0.012632, Val CE:0.044058, Train ACC:1.000000, Val ACC:0.993750

Epoch 1172/4000: 100%|██████████| 1/1 [00:00<00:00, 23.41it/s]

epoch: 1171, beta = 0.000198, Train MSE: 0.008396, Train CE:0.019770, Train KL:7.936691, Val MSE:0.012596, Val CE:0.043799, Train ACC:1.000000, Val ACC:0.993750

Epoch 1173/4000: 100%|██████████| 1/1 [00:00<00:00, 23.45it/s]

epoch: 1172, beta = 0.000198, Train MSE: 0.008388, Train CE:0.019712, Train KL:7.941317, Val MSE:0.012492, Val CE:0.042861, Train ACC:1.000000, Val ACC:0.993750

Epoch 1174/4000: 100%|██████████| 1/1 [00:00<00:00, 25.11it/s]

epoch: 1173, beta = 0.000198, Train MSE: 0.008383, Train CE:0.019679, Train KL:7.945821, Val MSE:0.012578, Val CE:0.044146, Train ACC:1.000000, Val ACC:0.994271

Epoch 1175/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 1174, beta = 0.000198, Train MSE: 0.008375, Train CE:0.019638, Train KL:7.951118, Val MSE:0.012510, Val CE:0.043416, Train ACC:1.000000, Val ACC:0.994792

Epoch 1176/4000: 100%|██████████| 1/1 [00:00<00:00, 24.54it/s]

epoch: 1175, beta = 0.000198, Train MSE: 0.008373, Train CE:0.019582, Train KL:7.955834, Val MSE:0.012515, Val CE:0.042623, Train ACC:1.000000, Val ACC:0.995313

Epoch 1177/4000: 100%|██████████| 1/1 [00:00<00:00, 21.88it/s]

epoch: 1176, beta = 0.000198, Train MSE: 0.008353, Train CE:0.019554, Train KL:7.960821, Val MSE:0.012588, Val CE:0.044392, Train ACC:1.000000, Val ACC:0.994792

Epoch 1178/4000: 100%|██████████| 1/1 [00:00<00:00, 22.82it/s]

epoch: 1177, beta = 0.000198, Train MSE: 0.008369, Train CE:0.019543, Train KL:7.966354, Val MSE:0.012565, Val CE:0.043012, Train ACC:1.000000, Val ACC:0.995313

Epoch 1179/4000: 100%|██████████| 1/1 [00:00<00:00, 23.02it/s]

epoch: 1178, beta = 0.000198, Train MSE: 0.008353, Train CE:0.019464, Train KL:7.970758, Val MSE:0.012469, Val CE:0.043349, Train ACC:1.000000, Val ACC:0.994271

Epoch 1180/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 1179, beta = 0.000198, Train MSE: 0.008331, Train CE:0.019397, Train KL:7.975706, Val MSE:0.012430, Val CE:0.045179, Train ACC:1.000000, Val ACC:0.994271

Epoch 1181/4000: 100%|██████████| 1/1 [00:00<00:00, 23.76it/s]

epoch: 1180, beta = 0.000198, Train MSE: 0.008335, Train CE:0.019412, Train KL:7.981086, Val MSE:0.012464, Val CE:0.042912, Train ACC:1.000000, Val ACC:0.994271

Epoch 1182/4000: 100%|██████████| 1/1 [00:00<00:00, 27.00it/s]

epoch: 1181, beta = 0.000198, Train MSE: 0.008327, Train CE:0.019411, Train KL:7.985889, Val MSE:0.012455, Val CE:0.044542, Train ACC:1.000000, Val ACC:0.994271

Epoch 1183/4000: 100%|██████████| 1/1 [00:00<00:00, 27.12it/s]

epoch: 1182, beta = 0.000198, Train MSE: 0.008312, Train CE:0.019294, Train KL:7.990752, Val MSE:0.012438, Val CE:0.045438, Train ACC:1.000000, Val ACC:0.994271

Epoch 1184/4000: 100%|██████████| 1/1 [00:00<00:00, 28.85it/s]

epoch: 1183, beta = 0.000198, Train MSE: 0.008310, Train CE:0.019265, Train KL:7.995330, Val MSE:0.012411, Val CE:0.043464, Train ACC:1.000000, Val ACC:0.994271

Epoch 1185/4000: 100%|██████████| 1/1 [00:00<00:00, 23.81it/s]

epoch: 1184, beta = 0.000198, Train MSE: 0.008354, Train CE:0.019221, Train KL:7.999986, Val MSE:0.012358, Val CE:0.044710, Train ACC:1.000000, Val ACC:0.993750

Epoch 1186/4000: 100%|██████████| 1/1 [00:00<00:00, 24.12it/s]

epoch: 1185, beta = 0.000138, Train MSE: 0.008319, Train CE:0.019159, Train KL:8.005508, Val MSE:0.012463, Val CE:0.044885, Train ACC:1.000000, Val ACC:0.994271

Epoch 1187/4000: 100%|██████████| 1/1 [00:00<00:00, 25.83it/s]

Learning rate updated: 0.00046329123015975297
epoch: 1186, beta = 0.000138, Train MSE: 0.008305, Train CE:0.019103, Train KL:8.010373, Val MSE:0.012347, Val CE:0.043551, Train ACC:1.000000, Val ACC:0.995313

Epoch 1188/4000: 100%|██████████| 1/1 [00:00<00:00, 23.15it/s]

epoch: 1187, beta = 0.000138, Train MSE: 0.008306, Train CE:0.019084, Train KL:8.015106, Val MSE:0.012339, Val CE:0.044494, Train ACC:1.000000, Val ACC:0.994271

Epoch 1189/4000: 100%|██████████| 1/1 [00:00<00:00, 26.40it/s]

epoch: 1188, beta = 0.000138, Train MSE: 0.008248, Train CE:0.019031, Train KL:8.020670, Val MSE:0.012436, Val CE:0.043675, Train ACC:1.000000, Val ACC:0.994271

Epoch 1190/4000: 100%|██████████| 1/1 [00:00<00:00, 23.32it/s]

epoch: 1189, beta = 0.000138, Train MSE: 0.008263, Train CE:0.019005, Train KL:8.025563, Val MSE:0.012373, Val CE:0.042074, Train ACC:1.000000, Val ACC:0.995313

Epoch 1191/4000: 100%|██████████| 1/1 [00:00<00:00, 22.56it/s]

epoch: 1190, beta = 0.000138, Train MSE: 0.008269, Train CE:0.018976, Train KL:8.030066, Val MSE:0.012429, Val CE:0.043036, Train ACC:1.000000, Val ACC:0.994271

Epoch 1192/4000: 100%|██████████| 1/1 [00:00<00:00, 24.08it/s]

epoch: 1191, beta = 0.000138, Train MSE: 0.008234, Train CE:0.018898, Train KL:8.035451, Val MSE:0.012347, Val CE:0.044614, Train ACC:1.000000, Val ACC:0.994271

Epoch 1193/4000: 100%|██████████| 1/1 [00:00<00:00, 24.73it/s]

epoch: 1192, beta = 0.000138, Train MSE: 0.008229, Train CE:0.018889, Train KL:8.041052, Val MSE:0.012273, Val CE:0.043768, Train ACC:1.000000, Val ACC:0.994271

Epoch 1194/4000: 100%|██████████| 1/1 [00:00<00:00, 23.87it/s]

epoch: 1193, beta = 0.000138, Train MSE: 0.008230, Train CE:0.018834, Train KL:8.045859, Val MSE:0.012373, Val CE:0.043709, Train ACC:1.000000, Val ACC:0.994271

Epoch 1195/4000: 100%|██████████| 1/1 [00:00<00:00, 23.35it/s]

epoch: 1194, beta = 0.000138, Train MSE: 0.008198, Train CE:0.018782, Train KL:8.050883, Val MSE:0.012321, Val CE:0.043548, Train ACC:1.000000, Val ACC:0.994271

Epoch 1196/4000: 100%|██████████| 1/1 [00:00<00:00, 23.98it/s]

epoch: 1195, beta = 0.000138, Train MSE: 0.008207, Train CE:0.018754, Train KL:8.056694, Val MSE:0.012336, Val CE:0.043442, Train ACC:1.000000, Val ACC:0.994271

Epoch 1197/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 1196, beta = 0.000138, Train MSE: 0.008193, Train CE:0.018697, Train KL:8.062408, Val MSE:0.012269, Val CE:0.043861, Train ACC:1.000000, Val ACC:0.994792

Epoch 1198/4000: 100%|██████████| 1/1 [00:00<00:00, 18.63it/s]

epoch: 1197, beta = 0.000138, Train MSE: 0.008193, Train CE:0.018669, Train KL:8.067567, Val MSE:0.012344, Val CE:0.045736, Train ACC:1.000000, Val ACC:0.994271

Epoch 1199/4000: 100%|██████████| 1/1 [00:00<00:00, 21.87it/s]

epoch: 1198, beta = 0.000138, Train MSE: 0.008184, Train CE:0.018646, Train KL:8.072845, Val MSE:0.012367, Val CE:0.044088, Train ACC:1.000000, Val ACC:0.994792

Epoch 1200/4000: 100%|██████████| 1/1 [00:00<00:00, 21.09it/s]

epoch: 1199, beta = 0.000097, Train MSE: 0.008169, Train CE:0.018588, Train KL:8.078108, Val MSE:0.012311, Val CE:0.044375, Train ACC:1.000000, Val ACC:0.994792

Epoch 1201/4000: 100%|██████████| 1/1 [00:00<00:00, 24.61it/s]

Learning rate updated: 0.0004401266686517653
epoch: 1200, beta = 0.000097, Train MSE: 0.008145, Train CE:0.018536, Train KL:8.083897, Val MSE:0.012281, Val CE:0.044710, Train ACC:1.000000, Val ACC:0.993750

Epoch 1202/4000: 100%|██████████| 1/1 [00:00<00:00, 24.13it/s]

epoch: 1201, beta = 0.000097, Train MSE: 0.008144, Train CE:0.018524, Train KL:8.089272, Val MSE:0.012243, Val CE:0.043196, Train ACC:1.000000, Val ACC:0.993750

Epoch 1203/4000: 100%|██████████| 1/1 [00:00<00:00, 24.08it/s]

epoch: 1202, beta = 0.000097, Train MSE: 0.008151, Train CE:0.018473, Train KL:8.094158, Val MSE:0.012249, Val CE:0.043283, Train ACC:1.000000, Val ACC:0.994792

Epoch 1204/4000: 100%|██████████| 1/1 [00:00<00:00, 27.20it/s]

epoch: 1203, beta = 0.000097, Train MSE: 0.008134, Train CE:0.018430, Train KL:8.099601, Val MSE:0.012211, Val CE:0.044223, Train ACC:1.000000, Val ACC:0.994271

Epoch 1205/4000: 100%|██████████| 1/1 [00:00<00:00, 23.91it/s]

epoch: 1204, beta = 0.000097, Train MSE: 0.008118, Train CE:0.018379, Train KL:8.105309, Val MSE:0.012175, Val CE:0.044393, Train ACC:1.000000, Val ACC:0.994271

Epoch 1206/4000: 100%|██████████| 1/1 [00:00<00:00, 24.27it/s]

epoch: 1205, beta = 0.000097, Train MSE: 0.008121, Train CE:0.018349, Train KL:8.110637, Val MSE:0.012105, Val CE:0.043252, Train ACC:1.000000, Val ACC:0.994271

Epoch 1207/4000: 100%|██████████| 1/1 [00:00<00:00, 24.26it/s]

epoch: 1206, beta = 0.000097, Train MSE: 0.008114, Train CE:0.018322, Train KL:8.115856, Val MSE:0.012186, Val CE:0.043978, Train ACC:1.000000, Val ACC:0.994271

Epoch 1208/4000: 100%|██████████| 1/1 [00:00<00:00, 25.42it/s]

epoch: 1207, beta = 0.000097, Train MSE: 0.008124, Train CE:0.018290, Train KL:8.121984, Val MSE:0.012156, Val CE:0.043503, Train ACC:1.000000, Val ACC:0.994271

Epoch 1209/4000: 100%|██████████| 1/1 [00:00<00:00, 26.02it/s]

epoch: 1208, beta = 0.000097, Train MSE: 0.008082, Train CE:0.018235, Train KL:8.127488, Val MSE:0.012194, Val CE:0.042797, Train ACC:1.000000, Val ACC:0.994271

Epoch 1210/4000: 100%|██████████| 1/1 [00:00<00:00, 25.86it/s]

epoch: 1209, beta = 0.000097, Train MSE: 0.008088, Train CE:0.018198, Train KL:8.132564, Val MSE:0.012151, Val CE:0.043940, Train ACC:1.000000, Val ACC:0.994271

Epoch 1211/4000: 100%|██████████| 1/1 [00:00<00:00, 24.17it/s]

epoch: 1210, beta = 0.000097, Train MSE: 0.008073, Train CE:0.018166, Train KL:8.138458, Val MSE:0.012159, Val CE:0.043991, Train ACC:1.000000, Val ACC:0.995313

Epoch 1212/4000: 100%|██████████| 1/1 [00:00<00:00, 24.03it/s]

Learning rate updated: 0.00041812033521917703
epoch: 1211, beta = 0.000097, Train MSE: 0.008075, Train CE:0.018127, Train KL:8.144112, Val MSE:0.012169, Val CE:0.043137, Train ACC:1.000000, Val ACC:0.995313

Epoch 1213/4000: 100%|██████████| 1/1 [00:00<00:00, 24.63it/s]

epoch: 1212, beta = 0.000097, Train MSE: 0.008044, Train CE:0.018095, Train KL:8.149269, Val MSE:0.012145, Val CE:0.043484, Train ACC:1.000000, Val ACC:0.994271

Epoch 1214/4000: 100%|██████████| 1/1 [00:00<00:00, 26.11it/s]

epoch: 1213, beta = 0.000097, Train MSE: 0.008032, Train CE:0.018053, Train KL:8.154685, Val MSE:0.012089, Val CE:0.044008, Train ACC:1.000000, Val ACC:0.994271

Epoch 1215/4000: 100%|██████████| 1/1 [00:00<00:00, 26.45it/s]

epoch: 1214, beta = 0.000097, Train MSE: 0.008060, Train CE:0.018035, Train KL:8.160114, Val MSE:0.012087, Val CE:0.043711, Train ACC:1.000000, Val ACC:0.994792

Epoch 1216/4000: 100%|██████████| 1/1 [00:00<00:00, 24.87it/s]

epoch: 1215, beta = 0.000097, Train MSE: 0.008037, Train CE:0.017989, Train KL:8.165378, Val MSE:0.012028, Val CE:0.043265, Train ACC:1.000000, Val ACC:0.995313

Epoch 1217/4000: 100%|██████████| 1/1 [00:00<00:00, 23.41it/s]

epoch: 1216, beta = 0.000097, Train MSE: 0.008026, Train CE:0.017956, Train KL:8.170163, Val MSE:0.012085, Val CE:0.044307, Train ACC:1.000000, Val ACC:0.994271

Epoch 1218/4000: 100%|██████████| 1/1 [00:00<00:00, 24.85it/s]

epoch: 1217, beta = 0.000097, Train MSE: 0.008041, Train CE:0.017925, Train KL:8.175374, Val MSE:0.012098, Val CE:0.043461, Train ACC:1.000000, Val ACC:0.994271

Epoch 1219/4000: 100%|██████████| 1/1 [00:00<00:00, 25.58it/s]

epoch: 1218, beta = 0.000097, Train MSE: 0.008024, Train CE:0.017882, Train KL:8.180607, Val MSE:0.012049, Val CE:0.043030, Train ACC:1.000000, Val ACC:0.994271

Epoch 1220/4000: 100%|██████████| 1/1 [00:00<00:00, 24.81it/s]

epoch: 1219, beta = 0.000097, Train MSE: 0.008025, Train CE:0.017849, Train KL:8.185873, Val MSE:0.012064, Val CE:0.044142, Train ACC:1.000000, Val ACC:0.994271

Epoch 1221/4000: 100%|██████████| 1/1 [00:00<00:00, 21.96it/s]

epoch: 1220, beta = 0.000097, Train MSE: 0.008010, Train CE:0.017820, Train KL:8.191132, Val MSE:0.012008, Val CE:0.043172, Train ACC:1.000000, Val ACC:0.993750

Epoch 1222/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 1221, beta = 0.000097, Train MSE: 0.007992, Train CE:0.017787, Train KL:8.196231, Val MSE:0.011954, Val CE:0.042993, Train ACC:1.000000, Val ACC:0.994271

Epoch 1223/4000: 100%|██████████| 1/1 [00:00<00:00, 24.71it/s]

Learning rate updated: 0.00039721431845821814
epoch: 1222, beta = 0.000097, Train MSE: 0.007980, Train CE:0.017748, Train KL:8.201409, Val MSE:0.012000, Val CE:0.044287, Train ACC:1.000000, Val ACC:0.994271

Epoch 1224/4000: 100%|██████████| 1/1 [00:00<00:00, 24.22it/s]

epoch: 1223, beta = 0.000097, Train MSE: 0.007979, Train CE:0.017720, Train KL:8.206885, Val MSE:0.011966, Val CE:0.043596, Train ACC:1.000000, Val ACC:0.994271

Epoch 1225/4000: 100%|██████████| 1/1 [00:00<00:00, 20.09it/s]

epoch: 1224, beta = 0.000097, Train MSE: 0.007973, Train CE:0.017665, Train KL:8.211619, Val MSE:0.011950, Val CE:0.042690, Train ACC:1.000000, Val ACC:0.994271

Epoch 1226/4000: 100%|██████████| 1/1 [00:00<00:00, 23.43it/s]

epoch: 1225, beta = 0.000097, Train MSE: 0.007973, Train CE:0.017666, Train KL:8.215931, Val MSE:0.011976, Val CE:0.043709, Train ACC:1.000000, Val ACC:0.994271

Epoch 1227/4000: 100%|██████████| 1/1 [00:00<00:00, 24.28it/s]

epoch: 1226, beta = 0.000097, Train MSE: 0.007955, Train CE:0.017615, Train KL:8.220820, Val MSE:0.011935, Val CE:0.043527, Train ACC:1.000000, Val ACC:0.994271

Epoch 1228/4000: 100%|██████████| 1/1 [00:00<00:00, 24.41it/s]

epoch: 1227, beta = 0.000097, Train MSE: 0.007940, Train CE:0.017575, Train KL:8.225426, Val MSE:0.011979, Val CE:0.043289, Train ACC:1.000000, Val ACC:0.993750

Epoch 1229/4000: 100%|██████████| 1/1 [00:00<00:00, 24.67it/s]

epoch: 1228, beta = 0.000097, Train MSE: 0.007938, Train CE:0.017553, Train KL:8.229722, Val MSE:0.011919, Val CE:0.043850, Train ACC:1.000000, Val ACC:0.994271

Epoch 1230/4000: 100%|██████████| 1/1 [00:00<00:00, 24.75it/s]

epoch: 1229, beta = 0.000097, Train MSE: 0.007925, Train CE:0.017521, Train KL:8.234470, Val MSE:0.011911, Val CE:0.043545, Train ACC:1.000000, Val ACC:0.994271

Epoch 1231/4000: 100%|██████████| 1/1 [00:00<00:00, 19.70it/s]

epoch: 1230, beta = 0.000097, Train MSE: 0.007924, Train CE:0.017479, Train KL:8.238909, Val MSE:0.011914, Val CE:0.043055, Train ACC:1.000000, Val ACC:0.994271

Epoch 1232/4000: 100%|██████████| 1/1 [00:00<00:00, 23.83it/s]

epoch: 1231, beta = 0.000097, Train MSE: 0.007923, Train CE:0.017451, Train KL:8.243161, Val MSE:0.011920, Val CE:0.043984, Train ACC:1.000000, Val ACC:0.994271

Epoch 1233/4000: 100%|██████████| 1/1 [00:00<00:00, 23.99it/s]

epoch: 1232, beta = 0.000097, Train MSE: 0.007906, Train CE:0.017419, Train KL:8.247838, Val MSE:0.011945, Val CE:0.043609, Train ACC:1.000000, Val ACC:0.994271

Epoch 1234/4000: 100%|██████████| 1/1 [00:00<00:00, 24.42it/s]

Learning rate updated: 0.0003773536025353072
epoch: 1233, beta = 0.000097, Train MSE: 0.007911, Train CE:0.017388, Train KL:8.252129, Val MSE:0.011884, Val CE:0.042953, Train ACC:1.000000, Val ACC:0.994271

Epoch 1235/4000: 100%|██████████| 1/1 [00:00<00:00, 24.78it/s]

epoch: 1234, beta = 0.000097, Train MSE: 0.007906, Train CE:0.017362, Train KL:8.256187, Val MSE:0.011893, Val CE:0.043868, Train ACC:1.000000, Val ACC:0.994271

Epoch 1236/4000: 100%|██████████| 1/1 [00:00<00:00, 24.07it/s]

epoch: 1235, beta = 0.000097, Train MSE: 0.007887, Train CE:0.017327, Train KL:8.260540, Val MSE:0.011888, Val CE:0.044309, Train ACC:1.000000, Val ACC:0.994271

Epoch 1237/4000: 100%|██████████| 1/1 [00:00<00:00, 24.80it/s]

epoch: 1236, beta = 0.000097, Train MSE: 0.007882, Train CE:0.017297, Train KL:8.264662, Val MSE:0.011907, Val CE:0.044186, Train ACC:1.000000, Val ACC:0.994271

Epoch 1238/4000: 100%|██████████| 1/1 [00:00<00:00, 23.91it/s]

epoch: 1237, beta = 0.000097, Train MSE: 0.007877, Train CE:0.017264, Train KL:8.268662, Val MSE:0.011922, Val CE:0.044124, Train ACC:1.000000, Val ACC:0.994271

Epoch 1239/4000: 100%|██████████| 1/1 [00:00<00:00, 23.80it/s]

epoch: 1238, beta = 0.000097, Train MSE: 0.007879, Train CE:0.017240, Train KL:8.272731, Val MSE:0.011906, Val CE:0.043876, Train ACC:1.000000, Val ACC:0.994271

Epoch 1240/4000: 100%|██████████| 1/1 [00:00<00:00, 24.01it/s]

epoch: 1239, beta = 0.000097, Train MSE: 0.007864, Train CE:0.017212, Train KL:8.276769, Val MSE:0.011941, Val CE:0.042942, Train ACC:1.000000, Val ACC:0.994271

Epoch 1241/4000: 100%|██████████| 1/1 [00:00<00:00, 23.84it/s]

epoch: 1240, beta = 0.000097, Train MSE: 0.007868, Train CE:0.017163, Train KL:8.280802, Val MSE:0.011902, Val CE:0.043184, Train ACC:1.000000, Val ACC:0.994271

Epoch 1242/4000: 100%|██████████| 1/1 [00:00<00:00, 24.02it/s]

epoch: 1241, beta = 0.000097, Train MSE: 0.007845, Train CE:0.017142, Train KL:8.284668, Val MSE:0.011907, Val CE:0.043436, Train ACC:1.000000, Val ACC:0.994271

Epoch 1243/4000: 100%|██████████| 1/1 [00:00<00:00, 22.98it/s]

epoch: 1242, beta = 0.000097, Train MSE: 0.007848, Train CE:0.017109, Train KL:8.288513, Val MSE:0.011843, Val CE:0.043458, Train ACC:1.000000, Val ACC:0.994271

Epoch 1244/4000: 100%|██████████| 1/1 [00:00<00:00, 23.97it/s]

epoch: 1243, beta = 0.000097, Train MSE: 0.007823, Train CE:0.017085, Train KL:8.292304, Val MSE:0.011839, Val CE:0.043302, Train ACC:1.000000, Val ACC:0.994271

Epoch 1245/4000: 100%|██████████| 1/1 [00:00<00:00, 22.49it/s]

Learning rate updated: 0.0003584859224085418
epoch: 1244, beta = 0.000097, Train MSE: 0.007836, Train CE:0.017064, Train KL:8.296023, Val MSE:0.011843, Val CE:0.043031, Train ACC:1.000000, Val ACC:0.994271

Epoch 1246/4000: 100%|██████████| 1/1 [00:00<00:00, 24.03it/s]

epoch: 1245, beta = 0.000097, Train MSE: 0.007834, Train CE:0.017022, Train KL:8.299805, Val MSE:0.011844, Val CE:0.042967, Train ACC:1.000000, Val ACC:0.994271

Epoch 1247/4000: 100%|██████████| 1/1 [00:00<00:00, 24.63it/s]

epoch: 1246, beta = 0.000097, Train MSE: 0.007817, Train CE:0.016997, Train KL:8.303231, Val MSE:0.011850, Val CE:0.042346, Train ACC:1.000000, Val ACC:0.994271

Epoch 1248/4000: 100%|██████████| 1/1 [00:00<00:00, 24.03it/s]

epoch: 1247, beta = 0.000097, Train MSE: 0.007834, Train CE:0.016979, Train KL:8.306498, Val MSE:0.011856, Val CE:0.042707, Train ACC:1.000000, Val ACC:0.994271

Epoch 1249/4000: 100%|██████████| 1/1 [00:00<00:00, 23.85it/s]

epoch: 1248, beta = 0.000097, Train MSE: 0.007815, Train CE:0.016938, Train KL:8.309925, Val MSE:0.011797, Val CE:0.043135, Train ACC:1.000000, Val ACC:0.994271

Epoch 1250/4000: 100%|██████████| 1/1 [00:00<00:00, 25.20it/s]

epoch: 1249, beta = 0.000097, Train MSE: 0.007794, Train CE:0.016921, Train KL:8.313488, Val MSE:0.011758, Val CE:0.043420, Train ACC:1.000000, Val ACC:0.994271

Epoch 1251/4000: 100%|██████████| 1/1 [00:00<00:00, 19.05it/s]

epoch: 1250, beta = 0.000097, Train MSE: 0.007813, Train CE:0.016900, Train KL:8.316994, Val MSE:0.011786, Val CE:0.043768, Train ACC:1.000000, Val ACC:0.994271

Epoch 1252/4000: 100%|██████████| 1/1 [00:00<00:00, 22.81it/s]

epoch: 1251, beta = 0.000097, Train MSE: 0.007805, Train CE:0.016859, Train KL:8.320582, Val MSE:0.011756, Val CE:0.044238, Train ACC:1.000000, Val ACC:0.993750

Epoch 1253/4000: 100%|██████████| 1/1 [00:00<00:00, 24.24it/s]

epoch: 1252, beta = 0.000097, Train MSE: 0.007789, Train CE:0.016842, Train KL:8.324079, Val MSE:0.011743, Val CE:0.043155, Train ACC:1.000000, Val ACC:0.993750

Epoch 1254/4000: 100%|██████████| 1/1 [00:00<00:00, 20.56it/s]

epoch: 1253, beta = 0.000097, Train MSE: 0.007781, Train CE:0.016822, Train KL:8.327386, Val MSE:0.011712, Val CE:0.043517, Train ACC:1.000000, Val ACC:0.994271

Epoch 1255/4000: 100%|██████████| 1/1 [00:00<00:00, 24.19it/s]

epoch: 1254, beta = 0.000097, Train MSE: 0.007772, Train CE:0.016776, Train KL:8.331054, Val MSE:0.011740, Val CE:0.043675, Train ACC:1.000000, Val ACC:0.994271

Epoch 1256/4000: 100%|██████████| 1/1 [00:00<00:00, 23.17it/s]

Learning rate updated: 0.0003405616262881147
epoch: 1255, beta = 0.000097, Train MSE: 0.007772, Train CE:0.016755, Train KL:8.334543, Val MSE:0.011714, Val CE:0.043558, Train ACC:1.000000, Val ACC:0.994271

Epoch 1257/4000: 100%|██████████| 1/1 [00:00<00:00, 26.77it/s]

epoch: 1256, beta = 0.000097, Train MSE: 0.007759, Train CE:0.016725, Train KL:8.337977, Val MSE:0.011677, Val CE:0.044141, Train ACC:1.000000, Val ACC:0.994271

Epoch 1258/4000: 100%|██████████| 1/1 [00:00<00:00, 23.93it/s]

epoch: 1257, beta = 0.000097, Train MSE: 0.007758, Train CE:0.016701, Train KL:8.341322, Val MSE:0.011676, Val CE:0.044275, Train ACC:1.000000, Val ACC:0.994271

Epoch 1259/4000: 100%|██████████| 1/1 [00:00<00:00, 23.50it/s]

epoch: 1258, beta = 0.000097, Train MSE: 0.007747, Train CE:0.016668, Train KL:8.344615, Val MSE:0.011668, Val CE:0.044404, Train ACC:1.000000, Val ACC:0.994271

Epoch 1260/4000: 100%|██████████| 1/1 [00:00<00:00, 24.34it/s]

epoch: 1259, beta = 0.000097, Train MSE: 0.007744, Train CE:0.016650, Train KL:8.347816, Val MSE:0.011630, Val CE:0.044665, Train ACC:1.000000, Val ACC:0.994271

Epoch 1261/4000: 100%|██████████| 1/1 [00:00<00:00, 24.30it/s]

epoch: 1260, beta = 0.000097, Train MSE: 0.007746, Train CE:0.016625, Train KL:8.350986, Val MSE:0.011611, Val CE:0.044168, Train ACC:1.000000, Val ACC:0.994271

Epoch 1262/4000: 100%|██████████| 1/1 [00:00<00:00, 24.03it/s]

epoch: 1261, beta = 0.000097, Train MSE: 0.007747, Train CE:0.016593, Train KL:8.354100, Val MSE:0.011640, Val CE:0.043555, Train ACC:1.000000, Val ACC:0.994271

Epoch 1263/4000: 100%|██████████| 1/1 [00:00<00:00, 23.88it/s]

epoch: 1262, beta = 0.000097, Train MSE: 0.007741, Train CE:0.016577, Train KL:8.357244, Val MSE:0.011686, Val CE:0.043186, Train ACC:1.000000, Val ACC:0.994271

Epoch 1264/4000: 100%|██████████| 1/1 [00:00<00:00, 23.30it/s]

epoch: 1263, beta = 0.000097, Train MSE: 0.007732, Train CE:0.016543, Train KL:8.360281, Val MSE:0.011638, Val CE:0.043532, Train ACC:1.000000, Val ACC:0.994271

Epoch 1265/4000: 100%|██████████| 1/1 [00:00<00:00, 20.90it/s]

epoch: 1264, beta = 0.000097, Train MSE: 0.007723, Train CE:0.016514, Train KL:8.363317, Val MSE:0.011634, Val CE:0.043420, Train ACC:1.000000, Val ACC:0.994271

Epoch 1266/4000: 100%|██████████| 1/1 [00:00<00:00, 24.04it/s]

epoch: 1265, beta = 0.000097, Train MSE: 0.007705, Train CE:0.016485, Train KL:8.366344, Val MSE:0.011659, Val CE:0.043088, Train ACC:1.000000, Val ACC:0.994271

Epoch 1267/4000: 100%|██████████| 1/1 [00:00<00:00, 23.55it/s]

Learning rate updated: 0.00032353354497370894
epoch: 1266, beta = 0.000097, Train MSE: 0.007718, Train CE:0.016467, Train KL:8.369361, Val MSE:0.011623, Val CE:0.042907, Train ACC:1.000000, Val ACC:0.994271

Epoch 1268/4000: 100%|██████████| 1/1 [00:00<00:00, 23.51it/s]

epoch: 1267, beta = 0.000097, Train MSE: 0.007706, Train CE:0.016435, Train KL:8.372494, Val MSE:0.011606, Val CE:0.042902, Train ACC:1.000000, Val ACC:0.994271

Epoch 1269/4000: 100%|██████████| 1/1 [00:00<00:00, 22.76it/s]

epoch: 1268, beta = 0.000097, Train MSE: 0.007687, Train CE:0.016410, Train KL:8.375346, Val MSE:0.011615, Val CE:0.042818, Train ACC:1.000000, Val ACC:0.994271

Epoch 1270/4000: 100%|██████████| 1/1 [00:00<00:00, 24.09it/s]

epoch: 1269, beta = 0.000097, Train MSE: 0.007693, Train CE:0.016393, Train KL:8.378147, Val MSE:0.011573, Val CE:0.042974, Train ACC:1.000000, Val ACC:0.994271

Epoch 1271/4000: 100%|██████████| 1/1 [00:00<00:00, 23.67it/s]

epoch: 1270, beta = 0.000097, Train MSE: 0.007689, Train CE:0.016365, Train KL:8.380935, Val MSE:0.011581, Val CE:0.043059, Train ACC:1.000000, Val ACC:0.994271

Epoch 1272/4000: 100%|██████████| 1/1 [00:00<00:00, 24.26it/s]

epoch: 1271, beta = 0.000097, Train MSE: 0.007685, Train CE:0.016344, Train KL:8.383601, Val MSE:0.011612, Val CE:0.043197, Train ACC:1.000000, Val ACC:0.994271

Epoch 1273/4000: 100%|██████████| 1/1 [00:00<00:00, 24.55it/s]

epoch: 1272, beta = 0.000097, Train MSE: 0.007666, Train CE:0.016321, Train KL:8.386389, Val MSE:0.011566, Val CE:0.043496, Train ACC:1.000000, Val ACC:0.994271

Epoch 1274/4000: 100%|██████████| 1/1 [00:00<00:00, 24.25it/s]

epoch: 1273, beta = 0.000097, Train MSE: 0.007661, Train CE:0.016294, Train KL:8.389144, Val MSE:0.011574, Val CE:0.043410, Train ACC:1.000000, Val ACC:0.994271

Epoch 1275/4000: 100%|██████████| 1/1 [00:00<00:00, 24.03it/s]

epoch: 1274, beta = 0.000097, Train MSE: 0.007655, Train CE:0.016264, Train KL:8.391962, Val MSE:0.011566, Val CE:0.043313, Train ACC:1.000000, Val ACC:0.994271

Epoch 1276/4000: 100%|██████████| 1/1 [00:00<00:00, 29.29it/s]

epoch: 1275, beta = 0.000097, Train MSE: 0.007670, Train CE:0.016246, Train KL:8.394773, Val MSE:0.011561, Val CE:0.043675, Train ACC:1.000000, Val ACC:0.994271

Epoch 1277/4000: 100%|██████████| 1/1 [00:00<00:00, 27.05it/s]

epoch: 1276, beta = 0.000097, Train MSE: 0.007657, Train CE:0.016220, Train KL:8.397432, Val MSE:0.011600, Val CE:0.043605, Train ACC:1.000000, Val ACC:0.994271

Epoch 1278/4000: 100%|██████████| 1/1 [00:00<00:00, 23.37it/s]

Learning rate updated: 0.00030735686772502346
epoch: 1277, beta = 0.000097, Train MSE: 0.007643, Train CE:0.016184, Train KL:8.399811, Val MSE:0.011584, Val CE:0.043629, Train ACC:1.000000, Val ACC:0.994271

Epoch 1279/4000: 100%|██████████| 1/1 [00:00<00:00, 19.16it/s]

epoch: 1278, beta = 0.000097, Train MSE: 0.007649, Train CE:0.016176, Train KL:8.402197, Val MSE:0.011508, Val CE:0.044181, Train ACC:1.000000, Val ACC:0.994271

Epoch 1280/4000: 100%|██████████| 1/1 [00:00<00:00, 22.57it/s]

epoch: 1279, beta = 0.000097, Train MSE: 0.007637, Train CE:0.016155, Train KL:8.404807, Val MSE:0.011535, Val CE:0.044121, Train ACC:1.000000, Val ACC:0.994271

Epoch 1281/4000: 100%|██████████| 1/1 [00:00<00:00, 24.07it/s]

epoch: 1280, beta = 0.000097, Train MSE: 0.007633, Train CE:0.016129, Train KL:8.407338, Val MSE:0.011497, Val CE:0.043595, Train ACC:1.000000, Val ACC:0.994271

Epoch 1282/4000: 100%|██████████| 1/1 [00:00<00:00, 20.50it/s]

epoch: 1281, beta = 0.000097, Train MSE: 0.007628, Train CE:0.016102, Train KL:8.409729, Val MSE:0.011526, Val CE:0.043726, Train ACC:1.000000, Val ACC:0.994271

Epoch 1283/4000: 100%|██████████| 1/1 [00:00<00:00, 24.28it/s]

epoch: 1282, beta = 0.000097, Train MSE: 0.007633, Train CE:0.016087, Train KL:8.412091, Val MSE:0.011528, Val CE:0.043987, Train ACC:1.000000, Val ACC:0.994271

Epoch 1284/4000: 100%|██████████| 1/1 [00:00<00:00, 24.61it/s]

epoch: 1283, beta = 0.000097, Train MSE: 0.007618, Train CE:0.016059, Train KL:8.414453, Val MSE:0.011494, Val CE:0.043820, Train ACC:1.000000, Val ACC:0.994271

Epoch 1285/4000: 100%|██████████| 1/1 [00:00<00:00, 23.74it/s]

epoch: 1284, beta = 0.000097, Train MSE: 0.007607, Train CE:0.016039, Train KL:8.416740, Val MSE:0.011469, Val CE:0.042949, Train ACC:1.000000, Val ACC:0.994271

Epoch 1286/4000: 100%|██████████| 1/1 [00:00<00:00, 22.04it/s]

epoch: 1285, beta = 0.000097, Train MSE: 0.007616, Train CE:0.016017, Train KL:8.419024, Val MSE:0.011502, Val CE:0.043254, Train ACC:1.000000, Val ACC:0.994271

Epoch 1287/4000: 100%|██████████| 1/1 [00:00<00:00, 24.56it/s]

epoch: 1286, beta = 0.000097, Train MSE: 0.007609, Train CE:0.016005, Train KL:8.421511, Val MSE:0.011500, Val CE:0.044093, Train ACC:1.000000, Val ACC:0.993750

Epoch 1288/4000: 100%|██████████| 1/1 [00:00<00:00, 23.75it/s]

epoch: 1287, beta = 0.000097, Train MSE: 0.007595, Train CE:0.015973, Train KL:8.423882, Val MSE:0.011508, Val CE:0.043405, Train ACC:1.000000, Val ACC:0.994271

Epoch 1289/4000: 100%|██████████| 1/1 [00:00<00:00, 23.96it/s]

Learning rate updated: 0.00029198902433877225
epoch: 1288, beta = 0.000097, Train MSE: 0.007589, Train CE:0.015945, Train KL:8.426092, Val MSE:0.011468, Val CE:0.043317, Train ACC:1.000000, Val ACC:0.994271

Epoch 1290/4000: 100%|██████████| 1/1 [00:00<00:00, 23.54it/s]

epoch: 1289, beta = 0.000097, Train MSE: 0.007603, Train CE:0.015929, Train KL:8.428552, Val MSE:0.011465, Val CE:0.043879, Train ACC:1.000000, Val ACC:0.994271

Epoch 1291/4000: 100%|██████████| 1/1 [00:00<00:00, 24.49it/s]

epoch: 1290, beta = 0.000097, Train MSE: 0.007583, Train CE:0.015918, Train KL:8.430940, Val MSE:0.011447, Val CE:0.043755, Train ACC:1.000000, Val ACC:0.994271

Epoch 1292/4000: 100%|██████████| 1/1 [00:00<00:00, 22.98it/s]

epoch: 1291, beta = 0.000097, Train MSE: 0.007593, Train CE:0.015878, Train KL:8.432955, Val MSE:0.011478, Val CE:0.043150, Train ACC:1.000000, Val ACC:0.994271

Epoch 1293/4000: 100%|██████████| 1/1 [00:00<00:00, 23.99it/s]

epoch: 1292, beta = 0.000097, Train MSE: 0.007580, Train CE:0.015864, Train KL:8.434911, Val MSE:0.011430, Val CE:0.043749, Train ACC:1.000000, Val ACC:0.994271

Epoch 1294/4000: 100%|██████████| 1/1 [00:00<00:00, 23.38it/s]

epoch: 1293, beta = 0.000097, Train MSE: 0.007567, Train CE:0.015835, Train KL:8.437181, Val MSE:0.011414, Val CE:0.044401, Train ACC:1.000000, Val ACC:0.994271

Epoch 1295/4000: 100%|██████████| 1/1 [00:00<00:00, 23.41it/s]

epoch: 1294, beta = 0.000097, Train MSE: 0.007576, Train CE:0.015827, Train KL:8.439608, Val MSE:0.011430, Val CE:0.043522, Train ACC:1.000000, Val ACC:0.994271

Epoch 1296/4000: 100%|██████████| 1/1 [00:00<00:00, 23.70it/s]

epoch: 1295, beta = 0.000097, Train MSE: 0.007556, Train CE:0.015796, Train KL:8.441710, Val MSE:0.011437, Val CE:0.043009, Train ACC:1.000000, Val ACC:0.994271

Epoch 1297/4000: 100%|██████████| 1/1 [00:00<00:00, 24.10it/s]

epoch: 1296, beta = 0.000097, Train MSE: 0.007554, Train CE:0.015786, Train KL:8.443687, Val MSE:0.011459, Val CE:0.044126, Train ACC:1.000000, Val ACC:0.993750

Epoch 1298/4000: 100%|██████████| 1/1 [00:00<00:00, 24.30it/s]

epoch: 1297, beta = 0.000097, Train MSE: 0.007558, Train CE:0.015759, Train KL:8.445779, Val MSE:0.011419, Val CE:0.044699, Train ACC:1.000000, Val ACC:0.994271

Epoch 1299/4000: 100%|██████████| 1/1 [00:00<00:00, 25.03it/s]

epoch: 1298, beta = 0.000097, Train MSE: 0.007547, Train CE:0.015752, Train KL:8.447925, Val MSE:0.011376, Val CE:0.043498, Train ACC:1.000000, Val ACC:0.994271

Epoch 1300/4000: 100%|██████████| 1/1 [00:00<00:00, 24.61it/s]

Learning rate updated: 0.00027738957312183364
epoch: 1299, beta = 0.000097, Train MSE: 0.007549, Train CE:0.015720, Train KL:8.449989, Val MSE:0.011406, Val CE:0.043809, Train ACC:1.000000, Val ACC:0.994792

Epoch 1301/4000: 100%|██████████| 1/1 [00:00<00:00, 23.43it/s]

epoch: 1300, beta = 0.000097, Train MSE: 0.007535, Train CE:0.015678, Train KL:8.452148, Val MSE:0.011373, Val CE:0.044488, Train ACC:1.000000, Val ACC:0.994271

Epoch 1302/4000: 100%|██████████| 1/1 [00:00<00:00, 24.19it/s]

epoch: 1301, beta = 0.000097, Train MSE: 0.007539, Train CE:0.015685, Train KL:8.454164, Val MSE:0.011389, Val CE:0.043347, Train ACC:1.000000, Val ACC:0.994271

Epoch 1303/4000: 100%|██████████| 1/1 [00:00<00:00, 23.44it/s]

epoch: 1302, beta = 0.000097, Train MSE: 0.007532, Train CE:0.015656, Train KL:8.456001, Val MSE:0.011348, Val CE:0.042987, Train ACC:1.000000, Val ACC:0.994271

Epoch 1304/4000: 100%|██████████| 1/1 [00:00<00:00, 19.76it/s]

epoch: 1303, beta = 0.000097, Train MSE: 0.007526, Train CE:0.015642, Train KL:8.457905, Val MSE:0.011386, Val CE:0.043747, Train ACC:1.000000, Val ACC:0.994271

Epoch 1305/4000: 100%|██████████| 1/1 [00:00<00:00, 23.55it/s]

epoch: 1304, beta = 0.000097, Train MSE: 0.007523, Train CE:0.015615, Train KL:8.459967, Val MSE:0.011409, Val CE:0.044125, Train ACC:1.000000, Val ACC:0.994271

Epoch 1306/4000: 100%|██████████| 1/1 [00:00<00:00, 23.73it/s]

epoch: 1305, beta = 0.000097, Train MSE: 0.007513, Train CE:0.015597, Train KL:8.461908, Val MSE:0.011355, Val CE:0.043355, Train ACC:1.000000, Val ACC:0.994271

Epoch 1307/4000: 100%|██████████| 1/1 [00:00<00:00, 24.96it/s]

epoch: 1306, beta = 0.000097, Train MSE: 0.007507, Train CE:0.015576, Train KL:8.463737, Val MSE:0.011378, Val CE:0.043181, Train ACC:1.000000, Val ACC:0.994271

Epoch 1308/4000: 100%|██████████| 1/1 [00:00<00:00, 24.05it/s]

epoch: 1307, beta = 0.000097, Train MSE: 0.007513, Train CE:0.015555, Train KL:8.465663, Val MSE:0.011375, Val CE:0.043750, Train ACC:1.000000, Val ACC:0.994271

Epoch 1309/4000: 100%|██████████| 1/1 [00:00<00:00, 24.11it/s]

epoch: 1308, beta = 0.000097, Train MSE: 0.007507, Train CE:0.015544, Train KL:8.467721, Val MSE:0.011375, Val CE:0.043573, Train ACC:1.000000, Val ACC:0.994271

Epoch 1310/4000: 100%|██████████| 1/1 [00:00<00:00, 22.33it/s]

epoch: 1309, beta = 0.000097, Train MSE: 0.007488, Train CE:0.015511, Train KL:8.469640, Val MSE:0.011365, Val CE:0.043154, Train ACC:1.000000, Val ACC:0.994271

Epoch 1311/4000: 100%|██████████| 1/1 [00:00<00:00, 22.36it/s]

Learning rate updated: 0.0002635200944657419
epoch: 1310, beta = 0.000097, Train MSE: 0.007499, Train CE:0.015502, Train KL:8.471498, Val MSE:0.011387, Val CE:0.043876, Train ACC:1.000000, Val ACC:0.994271

Epoch 1312/4000: 100%|██████████| 1/1 [00:00<00:00, 23.69it/s]

epoch: 1311, beta = 0.000097, Train MSE: 0.007478, Train CE:0.015478, Train KL:8.473376, Val MSE:0.011386, Val CE:0.044047, Train ACC:1.000000, Val ACC:0.993750

Epoch 1313/4000: 100%|██████████| 1/1 [00:00<00:00, 24.12it/s]

epoch: 1312, beta = 0.000097, Train MSE: 0.007482, Train CE:0.015456, Train KL:8.475153, Val MSE:0.011340, Val CE:0.043404, Train ACC:1.000000, Val ACC:0.994271

Epoch 1314/4000: 100%|██████████| 1/1 [00:00<00:00, 22.98it/s]

epoch: 1313, beta = 0.000097, Train MSE: 0.007483, Train CE:0.015444, Train KL:8.476830, Val MSE:0.011383, Val CE:0.043664, Train ACC:1.000000, Val ACC:0.994271

Epoch 1315/4000: 100%|██████████| 1/1 [00:00<00:00, 22.46it/s]

epoch: 1314, beta = 0.000097, Train MSE: 0.007471, Train CE:0.015420, Train KL:8.478560, Val MSE:0.011335, Val CE:0.043532, Train ACC:1.000000, Val ACC:0.994271

Epoch 1316/4000: 100%|██████████| 1/1 [00:00<00:00, 24.45it/s]

epoch: 1315, beta = 0.000097, Train MSE: 0.007459, Train CE:0.015401, Train KL:8.480387, Val MSE:0.011332, Val CE:0.043642, Train ACC:1.000000, Val ACC:0.994271

Epoch 1317/4000: 100%|██████████| 1/1 [00:00<00:00, 24.21it/s]

epoch: 1316, beta = 0.000097, Train MSE: 0.007469, Train CE:0.015382, Train KL:8.482117, Val MSE:0.011302, Val CE:0.044297, Train ACC:1.000000, Val ACC:0.994271

Epoch 1318/4000: 100%|██████████| 1/1 [00:00<00:00, 24.02it/s]

epoch: 1317, beta = 0.000097, Train MSE: 0.007471, Train CE:0.015366, Train KL:8.483759, Val MSE:0.011341, Val CE:0.043542, Train ACC:1.000000, Val ACC:0.994271

Epoch 1319/4000: 100%|██████████| 1/1 [00:00<00:00, 22.64it/s]

epoch: 1318, beta = 0.000097, Train MSE: 0.007455, Train CE:0.015334, Train KL:8.485305, Val MSE:0.011298, Val CE:0.044059, Train ACC:1.000000, Val ACC:0.994271

Epoch 1320/4000: 100%|██████████| 1/1 [00:00<00:00, 22.88it/s]

epoch: 1319, beta = 0.000097, Train MSE: 0.007449, Train CE:0.015329, Train KL:8.487012, Val MSE:0.011319, Val CE:0.043946, Train ACC:1.000000, Val ACC:0.994271

Epoch 1321/4000: 100%|██████████| 1/1 [00:00<00:00, 24.20it/s]

epoch: 1320, beta = 0.000097, Train MSE: 0.007444, Train CE:0.015300, Train KL:8.488845, Val MSE:0.011382, Val CE:0.043738, Train ACC:1.000000, Val ACC:0.994271

Epoch 1322/4000: 100%|██████████| 1/1 [00:00<00:00, 26.65it/s]

Learning rate updated: 0.0002503440897424548
epoch: 1321, beta = 0.000097, Train MSE: 0.007448, Train CE:0.015289, Train KL:8.490560, Val MSE:0.011287, Val CE:0.043350, Train ACC:1.000000, Val ACC:0.994271

Epoch 1323/4000: 100%|██████████| 1/1 [00:00<00:00, 24.03it/s]

epoch: 1322, beta = 0.000097, Train MSE: 0.007453, Train CE:0.015267, Train KL:8.492102, Val MSE:0.011338, Val CE:0.043731, Train ACC:1.000000, Val ACC:0.994271

Epoch 1324/4000: 100%|██████████| 1/1 [00:00<00:00, 22.63it/s]

epoch: 1323, beta = 0.000097, Train MSE: 0.007438, Train CE:0.015248, Train KL:8.493719, Val MSE:0.011298, Val CE:0.043922, Train ACC:1.000000, Val ACC:0.994271

Epoch 1325/4000: 100%|██████████| 1/1 [00:00<00:00, 24.01it/s]

epoch: 1324, beta = 0.000097, Train MSE: 0.007446, Train CE:0.015239, Train KL:8.495238, Val MSE:0.011288, Val CE:0.043754, Train ACC:1.000000, Val ACC:0.994271

Epoch 1326/4000: 100%|██████████| 1/1 [00:00<00:00, 23.42it/s]

epoch: 1325, beta = 0.000097, Train MSE: 0.007433, Train CE:0.015218, Train KL:8.496743, Val MSE:0.011270, Val CE:0.043955, Train ACC:1.000000, Val ACC:0.994271

Epoch 1327/4000: 100%|██████████| 1/1 [00:00<00:00, 22.25it/s]

epoch: 1326, beta = 0.000097, Train MSE: 0.007417, Train CE:0.015196, Train KL:8.498336, Val MSE:0.011283, Val CE:0.044153, Train ACC:1.000000, Val ACC:0.994271

Epoch 1328/4000: 100%|██████████| 1/1 [00:00<00:00, 23.78it/s]

epoch: 1327, beta = 0.000097, Train MSE: 0.007423, Train CE:0.015189, Train KL:8.499934, Val MSE:0.011273, Val CE:0.043705, Train ACC:1.000000, Val ACC:0.994271

Epoch 1329/4000: 100%|██████████| 1/1 [00:00<00:00, 23.93it/s]

epoch: 1328, beta = 0.000097, Train MSE: 0.007416, Train CE:0.015162, Train KL:8.501457, Val MSE:0.011271, Val CE:0.043748, Train ACC:1.000000, Val ACC:0.994271

Epoch 1330/4000: 100%|██████████| 1/1 [00:00<00:00, 24.33it/s]

epoch: 1329, beta = 0.000097, Train MSE: 0.007412, Train CE:0.015150, Train KL:8.503027, Val MSE:0.011219, Val CE:0.043313, Train ACC:1.000000, Val ACC:0.994271

Epoch 1331/4000: 100%|██████████| 1/1 [00:00<00:00, 24.08it/s]

epoch: 1330, beta = 0.000097, Train MSE: 0.007414, Train CE:0.015133, Train KL:8.504715, Val MSE:0.011235, Val CE:0.044169, Train ACC:1.000000, Val ACC:0.994271

Epoch 1332/4000: 100%|██████████| 1/1 [00:00<00:00, 23.32it/s]

epoch: 1331, beta = 0.000097, Train MSE: 0.007416, Train CE:0.015114, Train KL:8.506449, Val MSE:0.011257, Val CE:0.044502, Train ACC:1.000000, Val ACC:0.994271

Epoch 1333/4000: 100%|██████████| 1/1 [00:00<00:00, 24.04it/s]

Learning rate updated: 0.00023782688525533205
epoch: 1332, beta = 0.000097, Train MSE: 0.007405, Train CE:0.015106, Train KL:8.508042, Val MSE:0.011247, Val CE:0.043844, Train ACC:1.000000, Val ACC:0.993750

Epoch 1334/4000: 100%|██████████| 1/1 [00:00<00:00, 25.83it/s]

epoch: 1333, beta = 0.000097, Train MSE: 0.007398, Train CE:0.015077, Train KL:8.509306, Val MSE:0.011221, Val CE:0.043622, Train ACC:1.000000, Val ACC:0.994271

Epoch 1335/4000: 100%|██████████| 1/1 [00:00<00:00, 23.50it/s]

epoch: 1334, beta = 0.000097, Train MSE: 0.007411, Train CE:0.015067, Train KL:8.510729, Val MSE:0.011230, Val CE:0.043567, Train ACC:1.000000, Val ACC:0.994271

Epoch 1336/4000: 100%|██████████| 1/1 [00:00<00:00, 24.58it/s]

epoch: 1335, beta = 0.000097, Train MSE: 0.007393, Train CE:0.015042, Train KL:8.512316, Val MSE:0.011251, Val CE:0.043781, Train ACC:1.000000, Val ACC:0.994271

Epoch 1337/4000: 100%|██████████| 1/1 [00:00<00:00, 24.67it/s]

epoch: 1336, beta = 0.000097, Train MSE: 0.007390, Train CE:0.015027, Train KL:8.513832, Val MSE:0.011244, Val CE:0.043557, Train ACC:1.000000, Val ACC:0.994271

Epoch 1338/4000: 100%|██████████| 1/1 [00:00<00:00, 22.59it/s]

epoch: 1337, beta = 0.000097, Train MSE: 0.007385, Train CE:0.015015, Train KL:8.515285, Val MSE:0.011223, Val CE:0.043790, Train ACC:1.000000, Val ACC:0.993750

Epoch 1339/4000: 100%|██████████| 1/1 [00:00<00:00, 23.84it/s]

epoch: 1338, beta = 0.000097, Train MSE: 0.007377, Train CE:0.015001, Train KL:8.516740, Val MSE:0.011209, Val CE:0.044270, Train ACC:1.000000, Val ACC:0.994271

Epoch 1340/4000: 100%|██████████| 1/1 [00:00<00:00, 24.62it/s]

epoch: 1339, beta = 0.000097, Train MSE: 0.007374, Train CE:0.014976, Train KL:8.518297, Val MSE:0.011213, Val CE:0.044156, Train ACC:1.000000, Val ACC:0.994271

Epoch 1341/4000: 100%|██████████| 1/1 [00:00<00:00, 27.46it/s]

epoch: 1340, beta = 0.000097, Train MSE: 0.007369, Train CE:0.014961, Train KL:8.519644, Val MSE:0.011217, Val CE:0.043731, Train ACC:1.000000, Val ACC:0.994271

Epoch 1342/4000: 100%|██████████| 1/1 [00:00<00:00, 23.35it/s]

epoch: 1341, beta = 0.000097, Train MSE: 0.007362, Train CE:0.014953, Train KL:8.521101, Val MSE:0.011213, Val CE:0.043629, Train ACC:1.000000, Val ACC:0.994271

Epoch 1343/4000: 100%|██████████| 1/1 [00:00<00:00, 23.81it/s]

epoch: 1342, beta = 0.000097, Train MSE: 0.007367, Train CE:0.014937, Train KL:8.522628, Val MSE:0.011189, Val CE:0.043926, Train ACC:1.000000, Val ACC:0.993750

Epoch 1344/4000: 100%|██████████| 1/1 [00:00<00:00, 24.03it/s]

Learning rate updated: 0.00022593554099256544
epoch: 1343, beta = 0.000097, Train MSE: 0.007366, Train CE:0.014916, Train KL:8.524122, Val MSE:0.011170, Val CE:0.043872, Train ACC:1.000000, Val ACC:0.993750

Epoch 1345/4000: 100%|██████████| 1/1 [00:00<00:00, 24.76it/s]

epoch: 1344, beta = 0.000097, Train MSE: 0.007360, Train CE:0.014895, Train KL:8.525404, Val MSE:0.011151, Val CE:0.043489, Train ACC:1.000000, Val ACC:0.993750

Epoch 1346/4000: 100%|██████████| 1/1 [00:00<00:00, 23.93it/s]

epoch: 1345, beta = 0.000097, Train MSE: 0.007370, Train CE:0.014888, Train KL:8.526631, Val MSE:0.011206, Val CE:0.043679, Train ACC:1.000000, Val ACC:0.993750

Epoch 1347/4000: 100%|██████████| 1/1 [00:00<00:00, 22.92it/s]

epoch: 1346, beta = 0.000097, Train MSE: 0.007366, Train CE:0.014862, Train KL:8.527989, Val MSE:0.011141, Val CE:0.043622, Train ACC:1.000000, Val ACC:0.993750

Epoch 1348/4000: 100%|██████████| 1/1 [00:00<00:00, 24.04it/s]

epoch: 1347, beta = 0.000097, Train MSE: 0.007347, Train CE:0.014850, Train KL:8.529389, Val MSE:0.011157, Val CE:0.043708, Train ACC:1.000000, Val ACC:0.994271

Epoch 1349/4000: 100%|██████████| 1/1 [00:00<00:00, 22.03it/s]

epoch: 1348, beta = 0.000097, Train MSE: 0.007339, Train CE:0.014839, Train KL:8.530757, Val MSE:0.011141, Val CE:0.044021, Train ACC:1.000000, Val ACC:0.993750

Epoch 1350/4000: 100%|██████████| 1/1 [00:00<00:00, 23.11it/s]

epoch: 1349, beta = 0.000097, Train MSE: 0.007340, Train CE:0.014817, Train KL:8.532084, Val MSE:0.011135, Val CE:0.043823, Train ACC:1.000000, Val ACC:0.993750

Epoch 1351/4000: 100%|██████████| 1/1 [00:00<00:00, 25.58it/s]

epoch: 1350, beta = 0.000097, Train MSE: 0.007347, Train CE:0.014808, Train KL:8.533334, Val MSE:0.011144, Val CE:0.043612, Train ACC:1.000000, Val ACC:0.994271

Epoch 1352/4000: 100%|██████████| 1/1 [00:00<00:00, 19.90it/s]

epoch: 1351, beta = 0.000097, Train MSE: 0.007337, Train CE:0.014788, Train KL:8.534689, Val MSE:0.011182, Val CE:0.043890, Train ACC:1.000000, Val ACC:0.994271

Epoch 1353/4000: 100%|██████████| 1/1 [00:00<00:00, 23.04it/s]

epoch: 1352, beta = 0.000097, Train MSE: 0.007335, Train CE:0.014775, Train KL:8.536098, Val MSE:0.011162, Val CE:0.043593, Train ACC:1.000000, Val ACC:0.994271

Epoch 1354/4000: 100%|██████████| 1/1 [00:00<00:00, 24.73it/s]

epoch: 1353, beta = 0.000097, Train MSE: 0.007344, Train CE:0.014767, Train KL:8.537345, Val MSE:0.011156, Val CE:0.043595, Train ACC:1.000000, Val ACC:0.994271

Epoch 1355/4000: 100%|██████████| 1/1 [00:00<00:00, 25.14it/s]

Learning rate updated: 0.00021463876394293716
epoch: 1354, beta = 0.000097, Train MSE: 0.007326, Train CE:0.014744, Train KL:8.538678, Val MSE:0.011147, Val CE:0.043358, Train ACC:1.000000, Val ACC:0.993750

Epoch 1356/4000: 100%|██████████| 1/1 [00:00<00:00, 24.47it/s]

epoch: 1355, beta = 0.000097, Train MSE: 0.007328, Train CE:0.014730, Train KL:8.540063, Val MSE:0.011159, Val CE:0.043489, Train ACC:1.000000, Val ACC:0.994271

Epoch 1357/4000: 100%|██████████| 1/1 [00:00<00:00, 23.77it/s]

epoch: 1356, beta = 0.000097, Train MSE: 0.007320, Train CE:0.014716, Train KL:8.541390, Val MSE:0.011167, Val CE:0.043985, Train ACC:1.000000, Val ACC:0.993750

Epoch 1358/4000: 100%|██████████| 1/1 [00:00<00:00, 23.92it/s]

epoch: 1357, beta = 0.000097, Train MSE: 0.007319, Train CE:0.014700, Train KL:8.542717, Val MSE:0.011158, Val CE:0.044032, Train ACC:1.000000, Val ACC:0.994271

Epoch 1359/4000: 100%|██████████| 1/1 [00:00<00:00, 24.06it/s]

epoch: 1358, beta = 0.000097, Train MSE: 0.007312, Train CE:0.014681, Train KL:8.543911, Val MSE:0.011125, Val CE:0.043939, Train ACC:1.000000, Val ACC:0.994271

Epoch 1360/4000: 100%|██████████| 1/1 [00:00<00:00, 24.03it/s]

epoch: 1359, beta = 0.000097, Train MSE: 0.007308, Train CE:0.014671, Train KL:8.545174, Val MSE:0.011126, Val CE:0.043568, Train ACC:1.000000, Val ACC:0.994271

Epoch 1361/4000: 100%|██████████| 1/1 [00:00<00:00, 24.97it/s]

epoch: 1360, beta = 0.000097, Train MSE: 0.007307, Train CE:0.014661, Train KL:8.546516, Val MSE:0.011133, Val CE:0.044058, Train ACC:1.000000, Val ACC:0.993750

Epoch 1362/4000: 100%|██████████| 1/1 [00:00<00:00, 23.89it/s]

epoch: 1361, beta = 0.000097, Train MSE: 0.007305, Train CE:0.014648, Train KL:8.547994, Val MSE:0.011159, Val CE:0.043805, Train ACC:1.000000, Val ACC:0.993750

Epoch 1363/4000: 100%|██████████| 1/1 [00:00<00:00, 24.35it/s]

epoch: 1362, beta = 0.000097, Train MSE: 0.007308, Train CE:0.014630, Train KL:8.549150, Val MSE:0.011132, Val CE:0.043539, Train ACC:1.000000, Val ACC:0.994271

Epoch 1364/4000: 100%|██████████| 1/1 [00:00<00:00, 24.06it/s]

epoch: 1363, beta = 0.000097, Train MSE: 0.007294, Train CE:0.014619, Train KL:8.550397, Val MSE:0.011130, Val CE:0.044146, Train ACC:1.000000, Val ACC:0.994271

Epoch 1365/4000: 100%|██████████| 1/1 [00:00<00:00, 24.37it/s]

epoch: 1364, beta = 0.000097, Train MSE: 0.007300, Train CE:0.014596, Train KL:8.551812, Val MSE:0.011088, Val CE:0.044220, Train ACC:1.000000, Val ACC:0.994271

Epoch 1366/4000: 100%|██████████| 1/1 [00:00<00:00, 24.43it/s]

Learning rate updated: 0.0002039068257457903
epoch: 1365, beta = 0.000097, Train MSE: 0.007292, Train CE:0.014590, Train KL:8.553146, Val MSE:0.011124, Val CE:0.044021, Train ACC:1.000000, Val ACC:0.994271

Epoch 1367/4000: 100%|██████████| 1/1 [00:00<00:00, 23.61it/s]

epoch: 1366, beta = 0.000097, Train MSE: 0.007294, Train CE:0.014569, Train KL:8.554227, Val MSE:0.011100, Val CE:0.043810, Train ACC:1.000000, Val ACC:0.993750

Epoch 1368/4000: 100%|██████████| 1/1 [00:00<00:00, 24.64it/s]

epoch: 1367, beta = 0.000097, Train MSE: 0.007274, Train CE:0.014556, Train KL:8.555294, Val MSE:0.011099, Val CE:0.043721, Train ACC:1.000000, Val ACC:0.994271

Epoch 1369/4000: 100%|██████████| 1/1 [00:00<00:00, 22.58it/s]

epoch: 1368, beta = 0.000097, Train MSE: 0.007291, Train CE:0.014542, Train KL:8.556511, Val MSE:0.011116, Val CE:0.044092, Train ACC:1.000000, Val ACC:0.993750

Epoch 1370/4000: 100%|██████████| 1/1 [00:00<00:00, 23.96it/s]

epoch: 1369, beta = 0.000097, Train MSE: 0.007276, Train CE:0.014532, Train KL:8.557921, Val MSE:0.011078, Val CE:0.044204, Train ACC:1.000000, Val ACC:0.994271

Epoch 1371/4000: 100%|██████████| 1/1 [00:00<00:00, 27.21it/s]

epoch: 1370, beta = 0.000097, Train MSE: 0.007286, Train CE:0.014514, Train KL:8.559157, Val MSE:0.011081, Val CE:0.044048, Train ACC:1.000000, Val ACC:0.993750

Epoch 1372/4000: 100%|██████████| 1/1 [00:00<00:00, 27.90it/s]

epoch: 1371, beta = 0.000097, Train MSE: 0.007272, Train CE:0.014499, Train KL:8.560212, Val MSE:0.011112, Val CE:0.044057, Train ACC:1.000000, Val ACC:0.994271

Epoch 1373/4000: 100%|██████████| 1/1 [00:00<00:00, 23.65it/s]

epoch: 1372, beta = 0.000097, Train MSE: 0.007265, Train CE:0.014483, Train KL:8.561423, Val MSE:0.011127, Val CE:0.043916, Train ACC:1.000000, Val ACC:0.993750

Epoch 1374/4000: 100%|██████████| 1/1 [00:00<00:00, 23.55it/s]

epoch: 1373, beta = 0.000097, Train MSE: 0.007268, Train CE:0.014477, Train KL:8.562609, Val MSE:0.011084, Val CE:0.044266, Train ACC:1.000000, Val ACC:0.993750

Epoch 1375/4000: 100%|██████████| 1/1 [00:00<00:00, 24.25it/s]

epoch: 1374, beta = 0.000097, Train MSE: 0.007272, Train CE:0.014469, Train KL:8.563882, Val MSE:0.011104, Val CE:0.044001, Train ACC:1.000000, Val ACC:0.993750

Epoch 1376/4000: 100%|██████████| 1/1 [00:00<00:00, 24.54it/s]

epoch: 1375, beta = 0.000097, Train MSE: 0.007250, Train CE:0.014452, Train KL:8.564941, Val MSE:0.011067, Val CE:0.043637, Train ACC:1.000000, Val ACC:0.993229

Epoch 1377/4000: 100%|██████████| 1/1 [00:00<00:00, 27.19it/s]

Learning rate updated: 0.00019371148445850077
epoch: 1376, beta = 0.000097, Train MSE: 0.007255, Train CE:0.014436, Train KL:8.566011, Val MSE:0.011059, Val CE:0.043738, Train ACC:1.000000, Val ACC:0.993229

Epoch 1378/4000: 100%|██████████| 1/1 [00:00<00:00, 19.51it/s]

epoch: 1377, beta = 0.000097, Train MSE: 0.007255, Train CE:0.014421, Train KL:8.567347, Val MSE:0.011059, Val CE:0.044007, Train ACC:1.000000, Val ACC:0.994271

Epoch 1379/4000: 100%|██████████| 1/1 [00:00<00:00, 21.86it/s]

epoch: 1378, beta = 0.000097, Train MSE: 0.007259, Train CE:0.014402, Train KL:8.568510, Val MSE:0.011044, Val CE:0.043774, Train ACC:1.000000, Val ACC:0.994271

Epoch 1380/4000: 100%|██████████| 1/1 [00:00<00:00, 20.85it/s]

epoch: 1379, beta = 0.000097, Train MSE: 0.007248, Train CE:0.014390, Train KL:8.569540, Val MSE:0.011054, Val CE:0.043535, Train ACC:1.000000, Val ACC:0.993750

Epoch 1381/4000: 100%|██████████| 1/1 [00:00<00:00, 23.23it/s]

epoch: 1380, beta = 0.000097, Train MSE: 0.007240, Train CE:0.014381, Train KL:8.570535, Val MSE:0.011035, Val CE:0.043576, Train ACC:1.000000, Val ACC:0.993750

Epoch 1382/4000: 100%|██████████| 1/1 [00:00<00:00, 24.29it/s]

epoch: 1381, beta = 0.000097, Train MSE: 0.007238, Train CE:0.014363, Train KL:8.571648, Val MSE:0.011030, Val CE:0.043890, Train ACC:1.000000, Val ACC:0.993750

Epoch 1383/4000: 100%|██████████| 1/1 [00:00<00:00, 24.04it/s]

epoch: 1382, beta = 0.000097, Train MSE: 0.007239, Train CE:0.014356, Train KL:8.572779, Val MSE:0.011053, Val CE:0.043802, Train ACC:1.000000, Val ACC:0.993750

Epoch 1384/4000: 100%|██████████| 1/1 [00:00<00:00, 21.76it/s]

epoch: 1383, beta = 0.000097, Train MSE: 0.007234, Train CE:0.014339, Train KL:8.573645, Val MSE:0.011015, Val CE:0.043550, Train ACC:1.000000, Val ACC:0.994271

Epoch 1385/4000: 100%|██████████| 1/1 [00:00<00:00, 23.97it/s]

epoch: 1384, beta = 0.000097, Train MSE: 0.007230, Train CE:0.014331, Train KL:8.574594, Val MSE:0.011068, Val CE:0.043857, Train ACC:1.000000, Val ACC:0.994271

Epoch 1386/4000: 100%|██████████| 1/1 [00:00<00:00, 24.04it/s]

epoch: 1385, beta = 0.000097, Train MSE: 0.007231, Train CE:0.014312, Train KL:8.575768, Val MSE:0.011034, Val CE:0.043811, Train ACC:1.000000, Val ACC:0.993750

Epoch 1387/4000: 100%|██████████| 1/1 [00:00<00:00, 25.43it/s]

epoch: 1386, beta = 0.000097, Train MSE: 0.007216, Train CE:0.014305, Train KL:8.576923, Val MSE:0.011045, Val CE:0.043782, Train ACC:1.000000, Val ACC:0.993750

Epoch 1388/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

Learning rate updated: 0.00018402591023557573
epoch: 1387, beta = 0.000097, Train MSE: 0.007231, Train CE:0.014293, Train KL:8.577955, Val MSE:0.011033, Val CE:0.043659, Train ACC:1.000000, Val ACC:0.993750

Epoch 1389/4000: 100%|██████████| 1/1 [00:00<00:00, 24.58it/s]

epoch: 1388, beta = 0.000097, Train MSE: 0.007215, Train CE:0.014277, Train KL:8.578873, Val MSE:0.011028, Val CE:0.043772, Train ACC:1.000000, Val ACC:0.993750

Epoch 1390/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 1389, beta = 0.000097, Train MSE: 0.007216, Train CE:0.014266, Train KL:8.579823, Val MSE:0.011032, Val CE:0.044207, Train ACC:1.000000, Val ACC:0.993750

Epoch 1391/4000: 100%|██████████| 1/1 [00:00<00:00, 23.89it/s]

epoch: 1390, beta = 0.000097, Train MSE: 0.007216, Train CE:0.014249, Train KL:8.580848, Val MSE:0.011058, Val CE:0.044131, Train ACC:1.000000, Val ACC:0.993750

Epoch 1392/4000: 100%|██████████| 1/1 [00:00<00:00, 20.09it/s]

epoch: 1391, beta = 0.000097, Train MSE: 0.007206, Train CE:0.014241, Train KL:8.581887, Val MSE:0.011032, Val CE:0.043848, Train ACC:1.000000, Val ACC:0.994271

Epoch 1393/4000: 100%|██████████| 1/1 [00:00<00:00, 23.92it/s]

epoch: 1392, beta = 0.000097, Train MSE: 0.007217, Train CE:0.014232, Train KL:8.582755, Val MSE:0.011015, Val CE:0.043991, Train ACC:1.000000, Val ACC:0.993750

Epoch 1394/4000: 100%|██████████| 1/1 [00:00<00:00, 23.28it/s]

epoch: 1393, beta = 0.000097, Train MSE: 0.007207, Train CE:0.014221, Train KL:8.583754, Val MSE:0.011037, Val CE:0.043991, Train ACC:1.000000, Val ACC:0.993750

Epoch 1395/4000: 100%|██████████| 1/1 [00:00<00:00, 24.01it/s]

epoch: 1394, beta = 0.000097, Train MSE: 0.007201, Train CE:0.014207, Train KL:8.584886, Val MSE:0.011030, Val CE:0.044440, Train ACC:1.000000, Val ACC:0.994271

Epoch 1396/4000: 100%|██████████| 1/1 [00:00<00:00, 21.10it/s]

epoch: 1395, beta = 0.000097, Train MSE: 0.007207, Train CE:0.014201, Train KL:8.585960, Val MSE:0.011000, Val CE:0.044010, Train ACC:1.000000, Val ACC:0.993750

Epoch 1397/4000: 100%|██████████| 1/1 [00:00<00:00, 24.42it/s]

epoch: 1396, beta = 0.000097, Train MSE: 0.007202, Train CE:0.014181, Train KL:8.586649, Val MSE:0.010984, Val CE:0.043581, Train ACC:1.000000, Val ACC:0.994271

Epoch 1398/4000: 100%|██████████| 1/1 [00:00<00:00, 24.49it/s]

epoch: 1397, beta = 0.000097, Train MSE: 0.007206, Train CE:0.014168, Train KL:8.587582, Val MSE:0.011050, Val CE:0.044123, Train ACC:1.000000, Val ACC:0.993750

Epoch 1399/4000: 100%|██████████| 1/1 [00:00<00:00, 24.24it/s]

Learning rate updated: 0.00017482461472379692
epoch: 1398, beta = 0.000097, Train MSE: 0.007188, Train CE:0.014153, Train KL:8.588750, Val MSE:0.011007, Val CE:0.044064, Train ACC:1.000000, Val ACC:0.994271

Epoch 1400/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 1399, beta = 0.000097, Train MSE: 0.007196, Train CE:0.014134, Train KL:8.589854, Val MSE:0.010983, Val CE:0.044113, Train ACC:1.000000, Val ACC:0.993750

Epoch 1401/4000: 100%|██████████| 1/1 [00:00<00:00, 23.87it/s]

epoch: 1400, beta = 0.000097, Train MSE: 0.007189, Train CE:0.014128, Train KL:8.590650, Val MSE:0.010993, Val CE:0.043556, Train ACC:1.000000, Val ACC:0.994271

Epoch 1402/4000: 100%|██████████| 1/1 [00:00<00:00, 24.92it/s]

epoch: 1401, beta = 0.000097, Train MSE: 0.007189, Train CE:0.014115, Train KL:8.591429, Val MSE:0.010938, Val CE:0.043737, Train ACC:1.000000, Val ACC:0.993750

Epoch 1403/4000: 100%|██████████| 1/1 [00:00<00:00, 23.93it/s]

epoch: 1402, beta = 0.000097, Train MSE: 0.007188, Train CE:0.014109, Train KL:8.592387, Val MSE:0.010970, Val CE:0.043957, Train ACC:1.000000, Val ACC:0.993750

Epoch 1404/4000: 100%|██████████| 1/1 [00:00<00:00, 23.72it/s]

epoch: 1403, beta = 0.000097, Train MSE: 0.007179, Train CE:0.014091, Train KL:8.593527, Val MSE:0.010989, Val CE:0.043887, Train ACC:1.000000, Val ACC:0.993750

Epoch 1405/4000: 100%|██████████| 1/1 [00:00<00:00, 19.12it/s]

epoch: 1404, beta = 0.000097, Train MSE: 0.007182, Train CE:0.014080, Train KL:8.594480, Val MSE:0.010990, Val CE:0.043761, Train ACC:1.000000, Val ACC:0.993750

Epoch 1406/4000: 100%|██████████| 1/1 [00:00<00:00, 21.91it/s]

epoch: 1405, beta = 0.000097, Train MSE: 0.007164, Train CE:0.014077, Train KL:8.595206, Val MSE:0.010982, Val CE:0.043668, Train ACC:1.000000, Val ACC:0.993750

Epoch 1407/4000: 100%|██████████| 1/1 [00:00<00:00, 23.44it/s]

epoch: 1406, beta = 0.000097, Train MSE: 0.007172, Train CE:0.014063, Train KL:8.596009, Val MSE:0.010973, Val CE:0.043852, Train ACC:1.000000, Val ACC:0.993750

Epoch 1408/4000: 100%|██████████| 1/1 [00:00<00:00, 23.85it/s]

epoch: 1407, beta = 0.000097, Train MSE: 0.007176, Train CE:0.014050, Train KL:8.597021, Val MSE:0.010966, Val CE:0.043831, Train ACC:1.000000, Val ACC:0.993750

Epoch 1409/4000: 100%|██████████| 1/1 [00:00<00:00, 24.21it/s]

epoch: 1408, beta = 0.000097, Train MSE: 0.007169, Train CE:0.014042, Train KL:8.598045, Val MSE:0.010991, Val CE:0.043960, Train ACC:1.000000, Val ACC:0.993750

Epoch 1410/4000: 100%|██████████| 1/1 [00:00<00:00, 18.60it/s]

Learning rate updated: 0.00016608338398760707
epoch: 1409, beta = 0.000097, Train MSE: 0.007161, Train CE:0.014027, Train KL:8.598908, Val MSE:0.010940, Val CE:0.043644, Train ACC:1.000000, Val ACC:0.993750

Epoch 1411/4000: 100%|██████████| 1/1 [00:00<00:00, 23.97it/s]

epoch: 1410, beta = 0.000097, Train MSE: 0.007157, Train CE:0.014019, Train KL:8.599793, Val MSE:0.010949, Val CE:0.043993, Train ACC:1.000000, Val ACC:0.993750

Epoch 1412/4000: 100%|██████████| 1/1 [00:00<00:00, 23.72it/s]

epoch: 1411, beta = 0.000097, Train MSE: 0.007166, Train CE:0.014005, Train KL:8.600715, Val MSE:0.010964, Val CE:0.044057, Train ACC:1.000000, Val ACC:0.994271

Epoch 1413/4000: 100%|██████████| 1/1 [00:00<00:00, 23.69it/s]

epoch: 1412, beta = 0.000097, Train MSE: 0.007160, Train CE:0.013991, Train KL:8.601630, Val MSE:0.010944, Val CE:0.043853, Train ACC:1.000000, Val ACC:0.993750

Epoch 1414/4000: 100%|██████████| 1/1 [00:00<00:00, 21.74it/s]

epoch: 1413, beta = 0.000097, Train MSE: 0.007160, Train CE:0.013980, Train KL:8.602396, Val MSE:0.010955, Val CE:0.043778, Train ACC:1.000000, Val ACC:0.993750

Epoch 1415/4000: 100%|██████████| 1/1 [00:00<00:00, 21.06it/s]

epoch: 1414, beta = 0.000097, Train MSE: 0.007154, Train CE:0.013973, Train KL:8.603148, Val MSE:0.010946, Val CE:0.043688, Train ACC:1.000000, Val ACC:0.993750

Epoch 1416/4000: 100%|██████████| 1/1 [00:00<00:00, 23.99it/s]

epoch: 1415, beta = 0.000097, Train MSE: 0.007164, Train CE:0.013963, Train KL:8.604118, Val MSE:0.010930, Val CE:0.044075, Train ACC:1.000000, Val ACC:0.994271

Epoch 1417/4000: 100%|██████████| 1/1 [00:00<00:00, 24.81it/s]

epoch: 1416, beta = 0.000097, Train MSE: 0.007154, Train CE:0.013953, Train KL:8.605251, Val MSE:0.010950, Val CE:0.044214, Train ACC:1.000000, Val ACC:0.994271

Epoch 1418/4000: 100%|██████████| 1/1 [00:00<00:00, 22.81it/s]

epoch: 1417, beta = 0.000097, Train MSE: 0.007141, Train CE:0.013945, Train KL:8.606121, Val MSE:0.010943, Val CE:0.043665, Train ACC:1.000000, Val ACC:0.994271

Epoch 1419/4000: 100%|██████████| 1/1 [00:00<00:00, 23.03it/s]

epoch: 1418, beta = 0.000097, Train MSE: 0.007143, Train CE:0.013926, Train KL:8.606725, Val MSE:0.010938, Val CE:0.043607, Train ACC:1.000000, Val ACC:0.993750

Epoch 1420/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 1419, beta = 0.000097, Train MSE: 0.007151, Train CE:0.013922, Train KL:8.607448, Val MSE:0.010952, Val CE:0.044046, Train ACC:1.000000, Val ACC:0.993750

Epoch 1421/4000: 100%|██████████| 1/1 [00:00<00:00, 22.02it/s]

Learning rate updated: 0.0001577792147882267
epoch: 1420, beta = 0.000097, Train MSE: 0.007134, Train CE:0.013901, Train KL:8.608491, Val MSE:0.010952, Val CE:0.044436, Train ACC:1.000000, Val ACC:0.993750

Epoch 1422/4000: 100%|██████████| 1/1 [00:00<00:00, 25.12it/s]

epoch: 1421, beta = 0.000097, Train MSE: 0.007140, Train CE:0.013901, Train KL:8.609611, Val MSE:0.010921, Val CE:0.044123, Train ACC:1.000000, Val ACC:0.993750

Epoch 1423/4000: 100%|██████████| 1/1 [00:00<00:00, 24.59it/s]

epoch: 1422, beta = 0.000097, Train MSE: 0.007119, Train CE:0.013880, Train KL:8.610271, Val MSE:0.010925, Val CE:0.043610, Train ACC:1.000000, Val ACC:0.993750

Epoch 1424/4000: 100%|██████████| 1/1 [00:00<00:00, 23.38it/s]

epoch: 1423, beta = 0.000097, Train MSE: 0.007129, Train CE:0.013881, Train KL:8.610672, Val MSE:0.010961, Val CE:0.043585, Train ACC:1.000000, Val ACC:0.993750

Epoch 1425/4000: 100%|██████████| 1/1 [00:00<00:00, 23.57it/s]

epoch: 1424, beta = 0.000097, Train MSE: 0.007129, Train CE:0.013865, Train KL:8.611405, Val MSE:0.010930, Val CE:0.043976, Train ACC:1.000000, Val ACC:0.993750

Epoch 1426/4000: 100%|██████████| 1/1 [00:00<00:00, 24.01it/s]

epoch: 1425, beta = 0.000097, Train MSE: 0.007129, Train CE:0.013860, Train KL:8.612442, Val MSE:0.010939, Val CE:0.044180, Train ACC:1.000000, Val ACC:0.993750

Epoch 1427/4000: 100%|██████████| 1/1 [00:00<00:00, 24.02it/s]

epoch: 1426, beta = 0.000097, Train MSE: 0.007128, Train CE:0.013845, Train KL:8.613366, Val MSE:0.010908, Val CE:0.043700, Train ACC:1.000000, Val ACC:0.993750

Epoch 1428/4000: 100%|██████████| 1/1 [00:00<00:00, 22.99it/s]

epoch: 1427, beta = 0.000097, Train MSE: 0.007111, Train CE:0.013828, Train KL:8.614028, Val MSE:0.010895, Val CE:0.043538, Train ACC:1.000000, Val ACC:0.993750

Epoch 1429/4000: 100%|██████████| 1/1 [00:00<00:00, 23.99it/s]

epoch: 1428, beta = 0.000097, Train MSE: 0.007120, Train CE:0.013819, Train KL:8.614662, Val MSE:0.010951, Val CE:0.043646, Train ACC:1.000000, Val ACC:0.993750

Epoch 1430/4000: 100%|██████████| 1/1 [00:00<00:00, 19.99it/s]

epoch: 1429, beta = 0.000097, Train MSE: 0.007130, Train CE:0.013811, Train KL:8.615446, Val MSE:0.010948, Val CE:0.044407, Train ACC:1.000000, Val ACC:0.993750

Epoch 1431/4000: 100%|██████████| 1/1 [00:00<00:00, 23.02it/s]

epoch: 1430, beta = 0.000097, Train MSE: 0.007121, Train CE:0.013803, Train KL:8.616440, Val MSE:0.010901, Val CE:0.043913, Train ACC:1.000000, Val ACC:0.994271

Epoch 1432/4000: 100%|██████████| 1/1 [00:00<00:00, 23.28it/s]

Learning rate updated: 0.00014989025404881537
epoch: 1431, beta = 0.000097, Train MSE: 0.007109, Train CE:0.013792, Train KL:8.617254, Val MSE:0.010901, Val CE:0.044154, Train ACC:1.000000, Val ACC:0.993750

Epoch 1433/4000: 100%|██████████| 1/1 [00:00<00:00, 21.83it/s]

epoch: 1432, beta = 0.000097, Train MSE: 0.007117, Train CE:0.013784, Train KL:8.617937, Val MSE:0.010905, Val CE:0.043718, Train ACC:1.000000, Val ACC:0.993750

Epoch 1434/4000: 100%|██████████| 1/1 [00:00<00:00, 23.63it/s]

epoch: 1433, beta = 0.000097, Train MSE: 0.007111, Train CE:0.013775, Train KL:8.618630, Val MSE:0.010880, Val CE:0.043759, Train ACC:1.000000, Val ACC:0.993750

Epoch 1435/4000: 100%|██████████| 1/1 [00:00<00:00, 23.57it/s]

epoch: 1434, beta = 0.000097, Train MSE: 0.007100, Train CE:0.013767, Train KL:8.619504, Val MSE:0.010903, Val CE:0.043944, Train ACC:1.000000, Val ACC:0.993750

Epoch 1436/4000: 100%|██████████| 1/1 [00:00<00:00, 22.86it/s]

epoch: 1435, beta = 0.000097, Train MSE: 0.007110, Train CE:0.013749, Train KL:8.620421, Val MSE:0.010901, Val CE:0.043711, Train ACC:1.000000, Val ACC:0.993750

Epoch 1437/4000: 100%|██████████| 1/1 [00:00<00:00, 23.48it/s]

epoch: 1436, beta = 0.000097, Train MSE: 0.007105, Train CE:0.013745, Train KL:8.621111, Val MSE:0.010885, Val CE:0.043669, Train ACC:1.000000, Val ACC:0.993750

Epoch 1438/4000: 100%|██████████| 1/1 [00:00<00:00, 23.01it/s]

epoch: 1437, beta = 0.000097, Train MSE: 0.007098, Train CE:0.013739, Train KL:8.621676, Val MSE:0.010908, Val CE:0.043632, Train ACC:1.000000, Val ACC:0.993750

Epoch 1439/4000: 100%|██████████| 1/1 [00:00<00:00, 24.04it/s]

epoch: 1438, beta = 0.000097, Train MSE: 0.007093, Train CE:0.013726, Train KL:8.622336, Val MSE:0.010915, Val CE:0.043932, Train ACC:1.000000, Val ACC:0.993750

Epoch 1440/4000: 100%|██████████| 1/1 [00:00<00:00, 24.30it/s]

epoch: 1439, beta = 0.000097, Train MSE: 0.007093, Train CE:0.013717, Train KL:8.623255, Val MSE:0.010886, Val CE:0.044168, Train ACC:1.000000, Val ACC:0.993750

Epoch 1441/4000: 100%|██████████| 1/1 [00:00<00:00, 24.01it/s]

epoch: 1440, beta = 0.000097, Train MSE: 0.007102, Train CE:0.013709, Train KL:8.624104, Val MSE:0.010879, Val CE:0.043913, Train ACC:1.000000, Val ACC:0.993750

Epoch 1442/4000: 100%|██████████| 1/1 [00:00<00:00, 23.97it/s]

epoch: 1441, beta = 0.000097, Train MSE: 0.007088, Train CE:0.013694, Train KL:8.624806, Val MSE:0.010876, Val CE:0.043612, Train ACC:1.000000, Val ACC:0.993750

Epoch 1443/4000: 100%|██████████| 1/1 [00:00<00:00, 23.95it/s]

Learning rate updated: 0.00014239574134637458
epoch: 1442, beta = 0.000097, Train MSE: 0.007091, Train CE:0.013685, Train KL:8.625381, Val MSE:0.010866, Val CE:0.043333, Train ACC:1.000000, Val ACC:0.994271

Epoch 1444/4000: 100%|██████████| 1/1 [00:00<00:00, 24.24it/s]

epoch: 1443, beta = 0.000097, Train MSE: 0.007083, Train CE:0.013674, Train KL:8.626133, Val MSE:0.010874, Val CE:0.043889, Train ACC:1.000000, Val ACC:0.993750

Epoch 1445/4000: 100%|██████████| 1/1 [00:00<00:00, 23.93it/s]

epoch: 1444, beta = 0.000097, Train MSE: 0.007081, Train CE:0.013665, Train KL:8.627017, Val MSE:0.010898, Val CE:0.043831, Train ACC:1.000000, Val ACC:0.994271

Epoch 1446/4000: 100%|██████████| 1/1 [00:00<00:00, 26.01it/s]

epoch: 1445, beta = 0.000097, Train MSE: 0.007073, Train CE:0.013659, Train KL:8.627848, Val MSE:0.010859, Val CE:0.043809, Train ACC:1.000000, Val ACC:0.993750

Epoch 1447/4000: 100%|██████████| 1/1 [00:00<00:00, 24.32it/s]

epoch: 1446, beta = 0.000097, Train MSE: 0.007085, Train CE:0.013648, Train KL:8.628437, Val MSE:0.010883, Val CE:0.043677, Train ACC:1.000000, Val ACC:0.993750

Epoch 1448/4000: 100%|██████████| 1/1 [00:00<00:00, 24.56it/s]

epoch: 1447, beta = 0.000097, Train MSE: 0.007078, Train CE:0.013636, Train KL:8.628951, Val MSE:0.010857, Val CE:0.043647, Train ACC:1.000000, Val ACC:0.993750

Epoch 1449/4000: 100%|██████████| 1/1 [00:00<00:00, 24.07it/s]

epoch: 1448, beta = 0.000097, Train MSE: 0.007073, Train CE:0.013626, Train KL:8.629637, Val MSE:0.010846, Val CE:0.043979, Train ACC:1.000000, Val ACC:0.993750

Epoch 1450/4000: 100%|██████████| 1/1 [00:00<00:00, 23.84it/s]

epoch: 1449, beta = 0.000097, Train MSE: 0.007079, Train CE:0.013616, Train KL:8.630467, Val MSE:0.010845, Val CE:0.044069, Train ACC:1.000000, Val ACC:0.994271

Epoch 1451/4000: 100%|██████████| 1/1 [00:00<00:00, 23.77it/s]

epoch: 1450, beta = 0.000097, Train MSE: 0.007054, Train CE:0.013610, Train KL:8.631222, Val MSE:0.010825, Val CE:0.043989, Train ACC:1.000000, Val ACC:0.993750

Epoch 1452/4000: 100%|██████████| 1/1 [00:00<00:00, 23.92it/s]

epoch: 1451, beta = 0.000097, Train MSE: 0.007066, Train CE:0.013602, Train KL:8.631780, Val MSE:0.010842, Val CE:0.043894, Train ACC:1.000000, Val ACC:0.993750

Epoch 1453/4000: 100%|██████████| 1/1 [00:00<00:00, 21.04it/s]

epoch: 1452, beta = 0.000097, Train MSE: 0.007066, Train CE:0.013594, Train KL:8.632380, Val MSE:0.010870, Val CE:0.043801, Train ACC:1.000000, Val ACC:0.993750

Epoch 1454/4000: 100%|██████████| 1/1 [00:00<00:00, 23.93it/s]

Learning rate updated: 0.00013527595427905584
epoch: 1453, beta = 0.000097, Train MSE: 0.007073, Train CE:0.013583, Train KL:8.633151, Val MSE:0.010865, Val CE:0.044034, Train ACC:1.000000, Val ACC:0.994271

Epoch 1455/4000: 100%|██████████| 1/1 [00:00<00:00, 22.08it/s]

epoch: 1454, beta = 0.000097, Train MSE: 0.007062, Train CE:0.013575, Train KL:8.633987, Val MSE:0.010889, Val CE:0.043965, Train ACC:1.000000, Val ACC:0.993750

Epoch 1456/4000: 100%|██████████| 1/1 [00:00<00:00, 23.41it/s]

epoch: 1455, beta = 0.000097, Train MSE: 0.007045, Train CE:0.013565, Train KL:8.634627, Val MSE:0.010867, Val CE:0.043684, Train ACC:1.000000, Val ACC:0.993750

Epoch 1457/4000: 100%|██████████| 1/1 [00:00<00:00, 22.32it/s]

epoch: 1456, beta = 0.000097, Train MSE: 0.007050, Train CE:0.013558, Train KL:8.635158, Val MSE:0.010843, Val CE:0.043670, Train ACC:1.000000, Val ACC:0.993750

Epoch 1458/4000: 100%|██████████| 1/1 [00:00<00:00, 24.44it/s]

epoch: 1457, beta = 0.000097, Train MSE: 0.007054, Train CE:0.013546, Train KL:8.635715, Val MSE:0.010847, Val CE:0.043912, Train ACC:1.000000, Val ACC:0.993750

Epoch 1459/4000: 100%|██████████| 1/1 [00:00<00:00, 24.42it/s]

epoch: 1458, beta = 0.000097, Train MSE: 0.007065, Train CE:0.013543, Train KL:8.636392, Val MSE:0.010857, Val CE:0.043860, Train ACC:1.000000, Val ACC:0.994271

Epoch 1460/4000: 100%|██████████| 1/1 [00:00<00:00, 24.48it/s]

epoch: 1459, beta = 0.000097, Train MSE: 0.007055, Train CE:0.013531, Train KL:8.637067, Val MSE:0.010845, Val CE:0.044054, Train ACC:1.000000, Val ACC:0.993750

Epoch 1461/4000: 100%|██████████| 1/1 [00:00<00:00, 22.91it/s]

epoch: 1460, beta = 0.000097, Train MSE: 0.007053, Train CE:0.013520, Train KL:8.637623, Val MSE:0.010828, Val CE:0.043854, Train ACC:1.000000, Val ACC:0.993750

Epoch 1462/4000: 100%|██████████| 1/1 [00:00<00:00, 24.43it/s]

epoch: 1461, beta = 0.000097, Train MSE: 0.007047, Train CE:0.013515, Train KL:8.638102, Val MSE:0.010830, Val CE:0.043747, Train ACC:1.000000, Val ACC:0.993750

Epoch 1463/4000: 100%|██████████| 1/1 [00:00<00:00, 21.86it/s]

epoch: 1462, beta = 0.000097, Train MSE: 0.007048, Train CE:0.013507, Train KL:8.638696, Val MSE:0.010831, Val CE:0.043885, Train ACC:1.000000, Val ACC:0.993750

Epoch 1464/4000: 100%|██████████| 1/1 [00:00<00:00, 26.62it/s]

epoch: 1463, beta = 0.000097, Train MSE: 0.007044, Train CE:0.013502, Train KL:8.639362, Val MSE:0.010851, Val CE:0.043897, Train ACC:1.000000, Val ACC:0.993750

Epoch 1465/4000: 100%|██████████| 1/1 [00:00<00:00, 19.79it/s]

Learning rate updated: 0.00012851215656510304
epoch: 1464, beta = 0.000097, Train MSE: 0.007055, Train CE:0.013485, Train KL:8.640100, Val MSE:0.010863, Val CE:0.043845, Train ACC:1.000000, Val ACC:0.993750

Epoch 1466/4000: 100%|██████████| 1/1 [00:00<00:00, 25.28it/s]

epoch: 1465, beta = 0.000097, Train MSE: 0.007036, Train CE:0.013474, Train KL:8.640847, Val MSE:0.010831, Val CE:0.043715, Train ACC:1.000000, Val ACC:0.993750

Epoch 1467/4000: 100%|██████████| 1/1 [00:00<00:00, 22.32it/s]

epoch: 1466, beta = 0.000097, Train MSE: 0.007038, Train CE:0.013463, Train KL:8.641521, Val MSE:0.010793, Val CE:0.043631, Train ACC:1.000000, Val ACC:0.993750

Epoch 1468/4000: 100%|██████████| 1/1 [00:00<00:00, 22.10it/s]

epoch: 1467, beta = 0.000097, Train MSE: 0.007045, Train CE:0.013464, Train KL:8.642151, Val MSE:0.010793, Val CE:0.043722, Train ACC:1.000000, Val ACC:0.993750

Epoch 1469/4000: 100%|██████████| 1/1 [00:00<00:00, 24.03it/s]

epoch: 1468, beta = 0.000097, Train MSE: 0.007039, Train CE:0.013457, Train KL:8.642821, Val MSE:0.010779, Val CE:0.043504, Train ACC:1.000000, Val ACC:0.993750

Epoch 1470/4000: 100%|██████████| 1/1 [00:00<00:00, 21.20it/s]

epoch: 1469, beta = 0.000097, Train MSE: 0.007035, Train CE:0.013443, Train KL:8.643373, Val MSE:0.010799, Val CE:0.043895, Train ACC:1.000000, Val ACC:0.993750

Epoch 1471/4000: 100%|██████████| 1/1 [00:00<00:00, 28.84it/s]

epoch: 1470, beta = 0.000097, Train MSE: 0.007027, Train CE:0.013435, Train KL:8.643958, Val MSE:0.010821, Val CE:0.043970, Train ACC:1.000000, Val ACC:0.993750

Epoch 1472/4000: 100%|██████████| 1/1 [00:00<00:00, 24.07it/s]

epoch: 1471, beta = 0.000097, Train MSE: 0.007029, Train CE:0.013423, Train KL:8.644563, Val MSE:0.010804, Val CE:0.043826, Train ACC:1.000000, Val ACC:0.993750

Epoch 1473/4000: 100%|██████████| 1/1 [00:00<00:00, 21.90it/s]

epoch: 1472, beta = 0.000097, Train MSE: 0.007035, Train CE:0.013425, Train KL:8.645213, Val MSE:0.010772, Val CE:0.044054, Train ACC:1.000000, Val ACC:0.993750

Epoch 1474/4000: 100%|██████████| 1/1 [00:00<00:00, 21.93it/s]

epoch: 1473, beta = 0.000097, Train MSE: 0.007037, Train CE:0.013411, Train KL:8.645811, Val MSE:0.010834, Val CE:0.043899, Train ACC:1.000000, Val ACC:0.993750

Epoch 1475/4000: 100%|██████████| 1/1 [00:00<00:00, 24.02it/s]

epoch: 1474, beta = 0.000097, Train MSE: 0.007031, Train CE:0.013399, Train KL:8.646420, Val MSE:0.010777, Val CE:0.043873, Train ACC:1.000000, Val ACC:0.993750

Epoch 1476/4000: 100%|██████████| 1/1 [00:00<00:00, 24.42it/s]

Learning rate updated: 0.00012208654873684788
epoch: 1475, beta = 0.000097, Train MSE: 0.007023, Train CE:0.013390, Train KL:8.647039, Val MSE:0.010791, Val CE:0.043759, Train ACC:1.000000, Val ACC:0.993750

Epoch 1477/4000: 100%|██████████| 1/1 [00:00<00:00, 24.09it/s]

epoch: 1476, beta = 0.000097, Train MSE: 0.007011, Train CE:0.013388, Train KL:8.647700, Val MSE:0.010775, Val CE:0.043819, Train ACC:1.000000, Val ACC:0.993750

Epoch 1478/4000: 100%|██████████| 1/1 [00:00<00:00, 22.60it/s]

epoch: 1477, beta = 0.000097, Train MSE: 0.007023, Train CE:0.013384, Train KL:8.648291, Val MSE:0.010766, Val CE:0.043761, Train ACC:1.000000, Val ACC:0.993750

Epoch 1479/4000: 100%|██████████| 1/1 [00:00<00:00, 18.57it/s]

epoch: 1478, beta = 0.000097, Train MSE: 0.007021, Train CE:0.013370, Train KL:8.648946, Val MSE:0.010784, Val CE:0.043721, Train ACC:1.000000, Val ACC:0.993750

Epoch 1480/4000: 100%|██████████| 1/1 [00:00<00:00, 23.97it/s]

epoch: 1479, beta = 0.000097, Train MSE: 0.007015, Train CE:0.013368, Train KL:8.649515, Val MSE:0.010798, Val CE:0.043584, Train ACC:1.000000, Val ACC:0.993750

Epoch 1481/4000: 100%|██████████| 1/1 [00:00<00:00, 26.09it/s]

epoch: 1480, beta = 0.000097, Train MSE: 0.007015, Train CE:0.013351, Train KL:8.650089, Val MSE:0.010772, Val CE:0.043874, Train ACC:1.000000, Val ACC:0.993750

Epoch 1482/4000: 100%|██████████| 1/1 [00:00<00:00, 24.02it/s]

epoch: 1481, beta = 0.000097, Train MSE: 0.007015, Train CE:0.013354, Train KL:8.650685, Val MSE:0.010789, Val CE:0.043865, Train ACC:1.000000, Val ACC:0.993750

Epoch 1483/4000: 100%|██████████| 1/1 [00:00<00:00, 24.01it/s]

epoch: 1482, beta = 0.000097, Train MSE: 0.007021, Train CE:0.013342, Train KL:8.651225, Val MSE:0.010754, Val CE:0.043588, Train ACC:1.000000, Val ACC:0.993750

Epoch 1484/4000: 100%|██████████| 1/1 [00:00<00:00, 24.01it/s]

epoch: 1483, beta = 0.000097, Train MSE: 0.007015, Train CE:0.013325, Train KL:8.651761, Val MSE:0.010766, Val CE:0.043739, Train ACC:1.000000, Val ACC:0.993750

Epoch 1485/4000: 100%|██████████| 1/1 [00:00<00:00, 23.81it/s]

epoch: 1484, beta = 0.000097, Train MSE: 0.007017, Train CE:0.013327, Train KL:8.652326, Val MSE:0.010762, Val CE:0.043828, Train ACC:1.000000, Val ACC:0.993750

Epoch 1486/4000: 100%|██████████| 1/1 [00:00<00:00, 24.04it/s]

epoch: 1485, beta = 0.000097, Train MSE: 0.007011, Train CE:0.013317, Train KL:8.652978, Val MSE:0.010757, Val CE:0.043899, Train ACC:1.000000, Val ACC:0.993750

Epoch 1487/4000: 100%|██████████| 1/1 [00:00<00:00, 22.99it/s]

Learning rate updated: 0.00011598222130000548
epoch: 1486, beta = 0.000097, Train MSE: 0.007000, Train CE:0.013315, Train KL:8.653690, Val MSE:0.010757, Val CE:0.044067, Train ACC:1.000000, Val ACC:0.993750

Epoch 1488/4000: 100%|██████████| 1/1 [00:00<00:00, 24.60it/s]

epoch: 1487, beta = 0.000097, Train MSE: 0.007007, Train CE:0.013301, Train KL:8.654326, Val MSE:0.010747, Val CE:0.043796, Train ACC:1.000000, Val ACC:0.993750

Epoch 1489/4000: 100%|██████████| 1/1 [00:00<00:00, 24.27it/s]

epoch: 1488, beta = 0.000097, Train MSE: 0.007007, Train CE:0.013295, Train KL:8.654826, Val MSE:0.010734, Val CE:0.043747, Train ACC:1.000000, Val ACC:0.993750

Epoch 1490/4000: 100%|██████████| 1/1 [00:00<00:00, 23.93it/s]

epoch: 1489, beta = 0.000097, Train MSE: 0.006998, Train CE:0.013289, Train KL:8.655263, Val MSE:0.010783, Val CE:0.043383, Train ACC:1.000000, Val ACC:0.993750

Epoch 1491/4000: 100%|██████████| 1/1 [00:00<00:00, 24.11it/s]

epoch: 1490, beta = 0.000097, Train MSE: 0.006999, Train CE:0.013277, Train KL:8.655844, Val MSE:0.010750, Val CE:0.043595, Train ACC:1.000000, Val ACC:0.993229

Epoch 1492/4000: 100%|██████████| 1/1 [00:00<00:00, 25.30it/s]

epoch: 1491, beta = 0.000097, Train MSE: 0.006999, Train CE:0.013275, Train KL:8.656495, Val MSE:0.010748, Val CE:0.043902, Train ACC:1.000000, Val ACC:0.993750

Epoch 1493/4000: 100%|██████████| 1/1 [00:00<00:00, 24.02it/s]

epoch: 1492, beta = 0.000097, Train MSE: 0.006992, Train CE:0.013260, Train KL:8.657104, Val MSE:0.010789, Val CE:0.043570, Train ACC:1.000000, Val ACC:0.993750

Epoch 1494/4000: 100%|██████████| 1/1 [00:00<00:00, 24.62it/s]

epoch: 1493, beta = 0.000097, Train MSE: 0.006995, Train CE:0.013252, Train KL:8.657626, Val MSE:0.010748, Val CE:0.043728, Train ACC:1.000000, Val ACC:0.993750

Epoch 1495/4000: 100%|██████████| 1/1 [00:00<00:00, 23.87it/s]

epoch: 1494, beta = 0.000097, Train MSE: 0.006993, Train CE:0.013252, Train KL:8.658135, Val MSE:0.010708, Val CE:0.043887, Train ACC:1.000000, Val ACC:0.993750

Epoch 1496/4000: 100%|██████████| 1/1 [00:00<00:00, 24.30it/s]

epoch: 1495, beta = 0.000097, Train MSE: 0.006992, Train CE:0.013239, Train KL:8.658772, Val MSE:0.010778, Val CE:0.044299, Train ACC:1.000000, Val ACC:0.993750

Epoch 1497/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 1496, beta = 0.000097, Train MSE: 0.006993, Train CE:0.013240, Train KL:8.659432, Val MSE:0.010732, Val CE:0.044307, Train ACC:1.000000, Val ACC:0.994271

Epoch 1498/4000: 100%|██████████| 1/1 [00:00<00:00, 24.62it/s]

Learning rate updated: 0.00011018311023500519
epoch: 1497, beta = 0.000097, Train MSE: 0.006981, Train CE:0.013226, Train KL:8.659978, Val MSE:0.010738, Val CE:0.043777, Train ACC:1.000000, Val ACC:0.993750

Epoch 1499/4000: 100%|██████████| 1/1 [00:00<00:00, 24.60it/s]

epoch: 1498, beta = 0.000097, Train MSE: 0.006984, Train CE:0.013223, Train KL:8.660414, Val MSE:0.010724, Val CE:0.043677, Train ACC:1.000000, Val ACC:0.993750

Epoch 1500/4000: 100%|██████████| 1/1 [00:00<00:00, 24.36it/s]

epoch: 1499, beta = 0.000097, Train MSE: 0.006981, Train CE:0.013218, Train KL:8.660898, Val MSE:0.010745, Val CE:0.043825, Train ACC:1.000000, Val ACC:0.993750

Epoch 1501/4000: 100%|██████████| 1/1 [00:00<00:00, 24.26it/s]

epoch: 1500, beta = 0.000097, Train MSE: 0.006979, Train CE:0.013203, Train KL:8.661546, Val MSE:0.010713, Val CE:0.043975, Train ACC:1.000000, Val ACC:0.993750

Epoch 1502/4000: 100%|██████████| 1/1 [00:00<00:00, 23.02it/s]

epoch: 1501, beta = 0.000097, Train MSE: 0.006984, Train CE:0.013196, Train KL:8.662199, Val MSE:0.010745, Val CE:0.043940, Train ACC:1.000000, Val ACC:0.993750

Epoch 1503/4000: 100%|██████████| 1/1 [00:00<00:00, 19.41it/s]

epoch: 1502, beta = 0.000097, Train MSE: 0.006986, Train CE:0.013194, Train KL:8.662733, Val MSE:0.010735, Val CE:0.043910, Train ACC:1.000000, Val ACC:0.993750

Epoch 1504/4000: 100%|██████████| 1/1 [00:00<00:00, 23.46it/s]

epoch: 1503, beta = 0.000097, Train MSE: 0.006982, Train CE:0.013183, Train KL:8.663119, Val MSE:0.010738, Val CE:0.043622, Train ACC:1.000000, Val ACC:0.993750

Epoch 1505/4000: 100%|██████████| 1/1 [00:00<00:00, 23.40it/s]

epoch: 1504, beta = 0.000097, Train MSE: 0.006972, Train CE:0.013177, Train KL:8.663486, Val MSE:0.010713, Val CE:0.043870, Train ACC:1.000000, Val ACC:0.993750

Epoch 1506/4000: 100%|██████████| 1/1 [00:00<00:00, 25.09it/s]

epoch: 1505, beta = 0.000097, Train MSE: 0.006973, Train CE:0.013178, Train KL:8.663984, Val MSE:0.010738, Val CE:0.044094, Train ACC:1.000000, Val ACC:0.993229

Epoch 1507/4000: 100%|██████████| 1/1 [00:00<00:00, 23.34it/s]

epoch: 1506, beta = 0.000097, Train MSE: 0.006971, Train CE:0.013169, Train KL:8.664632, Val MSE:0.010728, Val CE:0.044106, Train ACC:1.000000, Val ACC:0.993750

Epoch 1508/4000: 100%|██████████| 1/1 [00:00<00:00, 22.67it/s]

epoch: 1507, beta = 0.000097, Train MSE: 0.006975, Train CE:0.013160, Train KL:8.665261, Val MSE:0.010727, Val CE:0.044282, Train ACC:1.000000, Val ACC:0.993750

Epoch 1509/4000: 100%|██████████| 1/1 [00:00<00:00, 21.59it/s]

Learning rate updated: 0.00010467395472325493
epoch: 1508, beta = 0.000097, Train MSE: 0.006963, Train CE:0.013150, Train KL:8.665823, Val MSE:0.010712, Val CE:0.044172, Train ACC:1.000000, Val ACC:0.993229

Epoch 1510/4000: 100%|██████████| 1/1 [00:00<00:00, 22.99it/s]

epoch: 1509, beta = 0.000097, Train MSE: 0.006965, Train CE:0.013145, Train KL:8.666294, Val MSE:0.010706, Val CE:0.043882, Train ACC:1.000000, Val ACC:0.993750

Epoch 1511/4000: 100%|██████████| 1/1 [00:00<00:00, 20.42it/s]

epoch: 1510, beta = 0.000097, Train MSE: 0.006969, Train CE:0.013136, Train KL:8.666691, Val MSE:0.010716, Val CE:0.043890, Train ACC:1.000000, Val ACC:0.993750

Epoch 1512/4000: 100%|██████████| 1/1 [00:00<00:00, 26.56it/s]

epoch: 1511, beta = 0.000097, Train MSE: 0.006956, Train CE:0.013132, Train KL:8.667136, Val MSE:0.010738, Val CE:0.043906, Train ACC:1.000000, Val ACC:0.993750

Epoch 1513/4000: 100%|██████████| 1/1 [00:00<00:00, 24.01it/s]

epoch: 1512, beta = 0.000097, Train MSE: 0.006958, Train CE:0.013119, Train KL:8.667629, Val MSE:0.010709, Val CE:0.043726, Train ACC:1.000000, Val ACC:0.993750

Epoch 1514/4000: 100%|██████████| 1/1 [00:00<00:00, 25.07it/s]

epoch: 1513, beta = 0.000097, Train MSE: 0.006964, Train CE:0.013123, Train KL:8.668149, Val MSE:0.010732, Val CE:0.043934, Train ACC:1.000000, Val ACC:0.993750

Epoch 1515/4000: 100%|██████████| 1/1 [00:00<00:00, 26.68it/s]

epoch: 1514, beta = 0.000097, Train MSE: 0.006954, Train CE:0.013113, Train KL:8.668665, Val MSE:0.010693, Val CE:0.043862, Train ACC:1.000000, Val ACC:0.993750

Epoch 1516/4000: 100%|██████████| 1/1 [00:00<00:00, 27.16it/s]

epoch: 1515, beta = 0.000097, Train MSE: 0.006968, Train CE:0.013107, Train KL:8.669159, Val MSE:0.010701, Val CE:0.043748, Train ACC:1.000000, Val ACC:0.994271

Epoch 1517/4000: 100%|██████████| 1/1 [00:00<00:00, 21.65it/s]

epoch: 1516, beta = 0.000097, Train MSE: 0.006956, Train CE:0.013096, Train KL:8.669685, Val MSE:0.010709, Val CE:0.043851, Train ACC:1.000000, Val ACC:0.993750

Epoch 1518/4000: 100%|██████████| 1/1 [00:00<00:00, 25.44it/s]

epoch: 1517, beta = 0.000097, Train MSE: 0.006945, Train CE:0.013096, Train KL:8.670159, Val MSE:0.010694, Val CE:0.043753, Train ACC:1.000000, Val ACC:0.993750

Epoch 1519/4000: 100%|██████████| 1/1 [00:00<00:00, 24.70it/s]

epoch: 1518, beta = 0.000097, Train MSE: 0.006953, Train CE:0.013084, Train KL:8.670587, Val MSE:0.010700, Val CE:0.043542, Train ACC:1.000000, Val ACC:0.994271

Epoch 1520/4000: 100%|██████████| 1/1 [00:00<00:00, 25.93it/s]

Learning rate updated: 9.944025698709218e-05
epoch: 1519, beta = 0.000097, Train MSE: 0.006950, Train CE:0.013073, Train KL:8.671072, Val MSE:0.010733, Val CE:0.043860, Train ACC:1.000000, Val ACC:0.994271

Epoch 1521/4000: 100%|██████████| 1/1 [00:00<00:00, 23.67it/s]

epoch: 1520, beta = 0.000097, Train MSE: 0.006959, Train CE:0.013068, Train KL:8.671619, Val MSE:0.010674, Val CE:0.043846, Train ACC:1.000000, Val ACC:0.994271

Epoch 1522/4000: 100%|██████████| 1/1 [00:00<00:00, 23.96it/s]

epoch: 1521, beta = 0.000097, Train MSE: 0.006943, Train CE:0.013071, Train KL:8.672129, Val MSE:0.010714, Val CE:0.043745, Train ACC:1.000000, Val ACC:0.993750

Epoch 1523/4000: 100%|██████████| 1/1 [00:00<00:00, 23.76it/s]

epoch: 1522, beta = 0.000097, Train MSE: 0.006946, Train CE:0.013060, Train KL:8.672586, Val MSE:0.010686, Val CE:0.043765, Train ACC:1.000000, Val ACC:0.994271

Epoch 1524/4000: 100%|██████████| 1/1 [00:00<00:00, 26.11it/s]

epoch: 1523, beta = 0.000097, Train MSE: 0.006948, Train CE:0.013057, Train KL:8.673043, Val MSE:0.010692, Val CE:0.043779, Train ACC:1.000000, Val ACC:0.993750

Epoch 1525/4000: 100%|██████████| 1/1 [00:00<00:00, 26.68it/s]

epoch: 1524, beta = 0.000097, Train MSE: 0.006946, Train CE:0.013054, Train KL:8.673531, Val MSE:0.010713, Val CE:0.043886, Train ACC:1.000000, Val ACC:0.993750

Epoch 1526/4000: 100%|██████████| 1/1 [00:00<00:00, 23.43it/s]

epoch: 1525, beta = 0.000097, Train MSE: 0.006943, Train CE:0.013044, Train KL:8.674059, Val MSE:0.010674, Val CE:0.044211, Train ACC:1.000000, Val ACC:0.993750

Epoch 1527/4000: 100%|██████████| 1/1 [00:00<00:00, 20.58it/s]

epoch: 1526, beta = 0.000097, Train MSE: 0.006939, Train CE:0.013034, Train KL:8.674527, Val MSE:0.010702, Val CE:0.043898, Train ACC:1.000000, Val ACC:0.993750

Epoch 1528/4000: 100%|██████████| 1/1 [00:00<00:00, 22.56it/s]

epoch: 1527, beta = 0.000097, Train MSE: 0.006935, Train CE:0.013035, Train KL:8.674930, Val MSE:0.010641, Val CE:0.043468, Train ACC:1.000000, Val ACC:0.993750

Epoch 1529/4000: 100%|██████████| 1/1 [00:00<00:00, 23.71it/s]

epoch: 1528, beta = 0.000097, Train MSE: 0.006931, Train CE:0.013024, Train KL:8.675396, Val MSE:0.010679, Val CE:0.043789, Train ACC:1.000000, Val ACC:0.993750

Epoch 1530/4000: 100%|██████████| 1/1 [00:00<00:00, 21.80it/s]

epoch: 1529, beta = 0.000097, Train MSE: 0.006933, Train CE:0.013015, Train KL:8.675952, Val MSE:0.010673, Val CE:0.043586, Train ACC:1.000000, Val ACC:0.993750

Epoch 1531/4000: 100%|██████████| 1/1 [00:00<00:00, 24.27it/s]

Learning rate updated: 9.446824413773756e-05
epoch: 1530, beta = 0.000097, Train MSE: 0.006930, Train CE:0.013009, Train KL:8.676553, Val MSE:0.010676, Val CE:0.043912, Train ACC:1.000000, Val ACC:0.993229

Epoch 1532/4000: 100%|██████████| 1/1 [00:00<00:00, 24.04it/s]

epoch: 1531, beta = 0.000097, Train MSE: 0.006936, Train CE:0.013002, Train KL:8.677073, Val MSE:0.010684, Val CE:0.044029, Train ACC:1.000000, Val ACC:0.993750

Epoch 1533/4000: 100%|██████████| 1/1 [00:00<00:00, 24.63it/s]

epoch: 1532, beta = 0.000097, Train MSE: 0.006934, Train CE:0.013004, Train KL:8.677463, Val MSE:0.010675, Val CE:0.043631, Train ACC:1.000000, Val ACC:0.993750

Epoch 1534/4000: 100%|██████████| 1/1 [00:00<00:00, 22.00it/s]

epoch: 1533, beta = 0.000097, Train MSE: 0.006931, Train CE:0.012991, Train KL:8.677752, Val MSE:0.010675, Val CE:0.043621, Train ACC:1.000000, Val ACC:0.993750

Epoch 1535/4000: 100%|██████████| 1/1 [00:00<00:00, 23.83it/s]

epoch: 1534, beta = 0.000097, Train MSE: 0.006930, Train CE:0.012979, Train KL:8.678150, Val MSE:0.010646, Val CE:0.043663, Train ACC:1.000000, Val ACC:0.993750

Epoch 1536/4000: 100%|██████████| 1/1 [00:00<00:00, 24.15it/s]

epoch: 1535, beta = 0.000097, Train MSE: 0.006923, Train CE:0.012980, Train KL:8.678665, Val MSE:0.010665, Val CE:0.043869, Train ACC:1.000000, Val ACC:0.993750

Epoch 1537/4000: 100%|██████████| 1/1 [00:00<00:00, 25.28it/s]

epoch: 1536, beta = 0.000097, Train MSE: 0.006920, Train CE:0.012968, Train KL:8.679259, Val MSE:0.010696, Val CE:0.043899, Train ACC:1.000000, Val ACC:0.993750

Epoch 1538/4000: 100%|██████████| 1/1 [00:00<00:00, 24.67it/s]

epoch: 1537, beta = 0.000097, Train MSE: 0.006929, Train CE:0.012964, Train KL:8.679802, Val MSE:0.010675, Val CE:0.043924, Train ACC:1.000000, Val ACC:0.993750

Epoch 1539/4000: 100%|██████████| 1/1 [00:00<00:00, 24.85it/s]

epoch: 1538, beta = 0.000097, Train MSE: 0.006918, Train CE:0.012960, Train KL:8.680227, Val MSE:0.010696, Val CE:0.043866, Train ACC:1.000000, Val ACC:0.993750

Epoch 1540/4000: 100%|██████████| 1/1 [00:00<00:00, 21.78it/s]

epoch: 1539, beta = 0.000097, Train MSE: 0.006924, Train CE:0.012959, Train KL:8.680542, Val MSE:0.010655, Val CE:0.043566, Train ACC:1.000000, Val ACC:0.993750

Epoch 1541/4000: 100%|██████████| 1/1 [00:00<00:00, 23.93it/s]

epoch: 1540, beta = 0.000097, Train MSE: 0.006913, Train CE:0.012944, Train KL:8.680877, Val MSE:0.010650, Val CE:0.043555, Train ACC:1.000000, Val ACC:0.993750

Epoch 1542/4000: 100%|██████████| 1/1 [00:00<00:00, 21.11it/s]

Learning rate updated: 8.974483193085068e-05
epoch: 1541, beta = 0.000097, Train MSE: 0.006920, Train CE:0.012943, Train KL:8.681266, Val MSE:0.010660, Val CE:0.043849, Train ACC:1.000000, Val ACC:0.993750

Epoch 1543/4000: 100%|██████████| 1/1 [00:00<00:00, 23.60it/s]

epoch: 1542, beta = 0.000097, Train MSE: 0.006913, Train CE:0.012937, Train KL:8.681772, Val MSE:0.010642, Val CE:0.044017, Train ACC:1.000000, Val ACC:0.993750

Epoch 1544/4000: 100%|██████████| 1/1 [00:00<00:00, 23.56it/s]

epoch: 1543, beta = 0.000097, Train MSE: 0.006908, Train CE:0.012929, Train KL:8.682255, Val MSE:0.010622, Val CE:0.044062, Train ACC:1.000000, Val ACC:0.993750

Epoch 1545/4000: 100%|██████████| 1/1 [00:00<00:00, 23.72it/s]

epoch: 1544, beta = 0.000097, Train MSE: 0.006909, Train CE:0.012931, Train KL:8.682674, Val MSE:0.010665, Val CE:0.043909, Train ACC:1.000000, Val ACC:0.993750

Epoch 1546/4000: 100%|██████████| 1/1 [00:00<00:00, 23.42it/s]

epoch: 1545, beta = 0.000097, Train MSE: 0.006913, Train CE:0.012916, Train KL:8.683041, Val MSE:0.010660, Val CE:0.043754, Train ACC:1.000000, Val ACC:0.993750

Epoch 1547/4000: 100%|██████████| 1/1 [00:00<00:00, 24.51it/s]

epoch: 1546, beta = 0.000097, Train MSE: 0.006906, Train CE:0.012919, Train KL:8.683393, Val MSE:0.010648, Val CE:0.043863, Train ACC:1.000000, Val ACC:0.993750

Epoch 1548/4000: 100%|██████████| 1/1 [00:00<00:00, 24.44it/s]

epoch: 1547, beta = 0.000097, Train MSE: 0.006911, Train CE:0.012904, Train KL:8.683762, Val MSE:0.010637, Val CE:0.043682, Train ACC:1.000000, Val ACC:0.993750

Epoch 1549/4000: 100%|██████████| 1/1 [00:00<00:00, 23.42it/s]

epoch: 1548, beta = 0.000097, Train MSE: 0.006913, Train CE:0.012904, Train KL:8.684134, Val MSE:0.010639, Val CE:0.043835, Train ACC:1.000000, Val ACC:0.993750

Epoch 1550/4000: 100%|██████████| 1/1 [00:00<00:00, 20.57it/s]

epoch: 1549, beta = 0.000097, Train MSE: 0.006899, Train CE:0.012897, Train KL:8.684563, Val MSE:0.010658, Val CE:0.043846, Train ACC:1.000000, Val ACC:0.993750

Epoch 1551/4000: 100%|██████████| 1/1 [00:00<00:00, 20.15it/s]

epoch: 1550, beta = 0.000097, Train MSE: 0.006893, Train CE:0.012887, Train KL:8.684983, Val MSE:0.010640, Val CE:0.043726, Train ACC:1.000000, Val ACC:0.993750

Epoch 1552/4000: 100%|██████████| 1/1 [00:00<00:00, 23.89it/s]

epoch: 1551, beta = 0.000097, Train MSE: 0.006909, Train CE:0.012894, Train KL:8.685361, Val MSE:0.010655, Val CE:0.043784, Train ACC:1.000000, Val ACC:0.993750

Epoch 1553/4000: 100%|██████████| 1/1 [00:00<00:00, 24.90it/s]

Learning rate updated: 8.525759033430814e-05
epoch: 1552, beta = 0.000097, Train MSE: 0.006908, Train CE:0.012886, Train KL:8.685693, Val MSE:0.010627, Val CE:0.043491, Train ACC:1.000000, Val ACC:0.993750

Epoch 1554/4000: 100%|██████████| 1/1 [00:00<00:00, 25.34it/s]

epoch: 1553, beta = 0.000097, Train MSE: 0.006901, Train CE:0.012873, Train KL:8.686018, Val MSE:0.010648, Val CE:0.043483, Train ACC:1.000000, Val ACC:0.993750

Epoch 1555/4000: 100%|██████████| 1/1 [00:00<00:00, 25.18it/s]

epoch: 1554, beta = 0.000097, Train MSE: 0.006899, Train CE:0.012864, Train KL:8.686399, Val MSE:0.010610, Val CE:0.043901, Train ACC:1.000000, Val ACC:0.993750

Epoch 1556/4000: 100%|██████████| 1/1 [00:00<00:00, 22.28it/s]

epoch: 1555, beta = 0.000097, Train MSE: 0.006902, Train CE:0.012863, Train KL:8.686853, Val MSE:0.010608, Val CE:0.043803, Train ACC:1.000000, Val ACC:0.993750

Epoch 1557/4000: 100%|██████████| 1/1 [00:00<00:00, 27.13it/s]

epoch: 1556, beta = 0.000097, Train MSE: 0.006899, Train CE:0.012858, Train KL:8.687326, Val MSE:0.010631, Val CE:0.043975, Train ACC:1.000000, Val ACC:0.993750

Epoch 1558/4000: 100%|██████████| 1/1 [00:00<00:00, 21.23it/s]

epoch: 1557, beta = 0.000097, Train MSE: 0.006898, Train CE:0.012856, Train KL:8.687757, Val MSE:0.010621, Val CE:0.044021, Train ACC:1.000000, Val ACC:0.993750

Epoch 1559/4000: 100%|██████████| 1/1 [00:00<00:00, 23.83it/s]

epoch: 1558, beta = 0.000097, Train MSE: 0.006896, Train CE:0.012843, Train KL:8.688151, Val MSE:0.010593, Val CE:0.043727, Train ACC:1.000000, Val ACC:0.994271

Epoch 1560/4000: 100%|██████████| 1/1 [00:00<00:00, 24.30it/s]

epoch: 1559, beta = 0.000097, Train MSE: 0.006894, Train CE:0.012835, Train KL:8.688453, Val MSE:0.010643, Val CE:0.043749, Train ACC:1.000000, Val ACC:0.993750

Epoch 1561/4000: 100%|██████████| 1/1 [00:00<00:00, 25.67it/s]

epoch: 1560, beta = 0.000097, Train MSE: 0.006893, Train CE:0.012832, Train KL:8.688768, Val MSE:0.010628, Val CE:0.043661, Train ACC:1.000000, Val ACC:0.993750

Epoch 1562/4000: 100%|██████████| 1/1 [00:00<00:00, 23.89it/s]

epoch: 1561, beta = 0.000097, Train MSE: 0.006877, Train CE:0.012830, Train KL:8.689147, Val MSE:0.010635, Val CE:0.043641, Train ACC:1.000000, Val ACC:0.993750

Epoch 1563/4000: 100%|██████████| 1/1 [00:00<00:00, 23.72it/s]

epoch: 1562, beta = 0.000097, Train MSE: 0.006894, Train CE:0.012825, Train KL:8.689541, Val MSE:0.010601, Val CE:0.043845, Train ACC:1.000000, Val ACC:0.993750

Epoch 1564/4000: 100%|██████████| 1/1 [00:00<00:00, 27.39it/s]

Learning rate updated: 8.099471081759274e-05
epoch: 1563, beta = 0.000097, Train MSE: 0.006890, Train CE:0.012821, Train KL:8.689921, Val MSE:0.010596, Val CE:0.043718, Train ACC:1.000000, Val ACC:0.993750

Epoch 1565/4000: 100%|██████████| 1/1 [00:00<00:00, 27.90it/s]

epoch: 1564, beta = 0.000097, Train MSE: 0.006886, Train CE:0.012812, Train KL:8.690311, Val MSE:0.010616, Val CE:0.043831, Train ACC:1.000000, Val ACC:0.993750

Epoch 1566/4000: 100%|██████████| 1/1 [00:00<00:00, 27.33it/s]

epoch: 1565, beta = 0.000097, Train MSE: 0.006889, Train CE:0.012810, Train KL:8.690613, Val MSE:0.010604, Val CE:0.043551, Train ACC:1.000000, Val ACC:0.993750

Epoch 1567/4000: 100%|██████████| 1/1 [00:00<00:00, 24.11it/s]

epoch: 1566, beta = 0.000097, Train MSE: 0.006878, Train CE:0.012806, Train KL:8.690914, Val MSE:0.010612, Val CE:0.043768, Train ACC:1.000000, Val ACC:0.993750

Epoch 1568/4000: 100%|██████████| 1/1 [00:00<00:00, 24.12it/s]

epoch: 1567, beta = 0.000097, Train MSE: 0.006885, Train CE:0.012797, Train KL:8.691269, Val MSE:0.010612, Val CE:0.043735, Train ACC:1.000000, Val ACC:0.993750

Epoch 1569/4000: 100%|██████████| 1/1 [00:00<00:00, 26.38it/s]

epoch: 1568, beta = 0.000097, Train MSE: 0.006891, Train CE:0.012793, Train KL:8.691657, Val MSE:0.010600, Val CE:0.044006, Train ACC:1.000000, Val ACC:0.994271

Epoch 1570/4000: 100%|██████████| 1/1 [00:00<00:00, 20.65it/s]

epoch: 1569, beta = 0.000097, Train MSE: 0.006883, Train CE:0.012787, Train KL:8.692047, Val MSE:0.010616, Val CE:0.043678, Train ACC:1.000000, Val ACC:0.993750

Epoch 1571/4000: 100%|██████████| 1/1 [00:00<00:00, 19.69it/s]

epoch: 1570, beta = 0.000097, Train MSE: 0.006880, Train CE:0.012785, Train KL:8.692380, Val MSE:0.010621, Val CE:0.043571, Train ACC:1.000000, Val ACC:0.993750

Epoch 1572/4000: 100%|██████████| 1/1 [00:00<00:00, 23.29it/s]

epoch: 1571, beta = 0.000097, Train MSE: 0.006881, Train CE:0.012785, Train KL:8.692670, Val MSE:0.010633, Val CE:0.043522, Train ACC:1.000000, Val ACC:0.993750

Epoch 1573/4000: 100%|██████████| 1/1 [00:00<00:00, 23.56it/s]

epoch: 1572, beta = 0.000097, Train MSE: 0.006876, Train CE:0.012769, Train KL:8.692998, Val MSE:0.010609, Val CE:0.043484, Train ACC:1.000000, Val ACC:0.993750

Epoch 1574/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 1573, beta = 0.000097, Train MSE: 0.006873, Train CE:0.012767, Train KL:8.693371, Val MSE:0.010634, Val CE:0.043727, Train ACC:1.000000, Val ACC:0.993750

Epoch 1575/4000: 100%|██████████| 1/1 [00:00<00:00, 27.88it/s]

Learning rate updated: 7.69449752767131e-05
epoch: 1574, beta = 0.000097, Train MSE: 0.006870, Train CE:0.012757, Train KL:8.693763, Val MSE:0.010612, Val CE:0.043696, Train ACC:1.000000, Val ACC:0.993750

Epoch 1576/4000: 100%|██████████| 1/1 [00:00<00:00, 24.35it/s]

epoch: 1575, beta = 0.000097, Train MSE: 0.006873, Train CE:0.012760, Train KL:8.694077, Val MSE:0.010636, Val CE:0.043633, Train ACC:1.000000, Val ACC:0.993750

Epoch 1577/4000: 100%|██████████| 1/1 [00:00<00:00, 23.84it/s]

epoch: 1576, beta = 0.000097, Train MSE: 0.006876, Train CE:0.012753, Train KL:8.694377, Val MSE:0.010586, Val CE:0.043489, Train ACC:1.000000, Val ACC:0.993750

Epoch 1578/4000: 100%|██████████| 1/1 [00:00<00:00, 23.46it/s]

epoch: 1577, beta = 0.000097, Train MSE: 0.006868, Train CE:0.012745, Train KL:8.694714, Val MSE:0.010579, Val CE:0.043928, Train ACC:1.000000, Val ACC:0.993750

Epoch 1579/4000: 100%|██████████| 1/1 [00:00<00:00, 23.28it/s]

epoch: 1578, beta = 0.000097, Train MSE: 0.006869, Train CE:0.012744, Train KL:8.695084, Val MSE:0.010595, Val CE:0.043590, Train ACC:1.000000, Val ACC:0.993750

Epoch 1580/4000: 100%|██████████| 1/1 [00:00<00:00, 23.99it/s]

epoch: 1579, beta = 0.000097, Train MSE: 0.006869, Train CE:0.012740, Train KL:8.695417, Val MSE:0.010580, Val CE:0.043771, Train ACC:1.000000, Val ACC:0.993750

Epoch 1581/4000: 100%|██████████| 1/1 [00:00<00:00, 22.99it/s]

epoch: 1580, beta = 0.000097, Train MSE: 0.006867, Train CE:0.012735, Train KL:8.695718, Val MSE:0.010612, Val CE:0.043729, Train ACC:1.000000, Val ACC:0.993750

Epoch 1582/4000: 100%|██████████| 1/1 [00:00<00:00, 21.72it/s]

epoch: 1581, beta = 0.000097, Train MSE: 0.006870, Train CE:0.012726, Train KL:8.696044, Val MSE:0.010572, Val CE:0.043654, Train ACC:1.000000, Val ACC:0.993750

Epoch 1583/4000: 100%|██████████| 1/1 [00:00<00:00, 23.37it/s]

epoch: 1582, beta = 0.000097, Train MSE: 0.006859, Train CE:0.012730, Train KL:8.696357, Val MSE:0.010577, Val CE:0.043655, Train ACC:1.000000, Val ACC:0.993229

Epoch 1584/4000: 100%|██████████| 1/1 [00:00<00:00, 25.08it/s]

epoch: 1583, beta = 0.000097, Train MSE: 0.006865, Train CE:0.012717, Train KL:8.696691, Val MSE:0.010602, Val CE:0.043632, Train ACC:1.000000, Val ACC:0.993750

Epoch 1585/4000: 100%|██████████| 1/1 [00:00<00:00, 24.53it/s]

epoch: 1584, beta = 0.000097, Train MSE: 0.006863, Train CE:0.012715, Train KL:8.697010, Val MSE:0.010590, Val CE:0.043717, Train ACC:1.000000, Val ACC:0.993750

Epoch 1586/4000: 100%|██████████| 1/1 [00:00<00:00, 24.39it/s]

Learning rate updated: 7.309772651287744e-05
epoch: 1585, beta = 0.000097, Train MSE: 0.006858, Train CE:0.012706, Train KL:8.697332, Val MSE:0.010555, Val CE:0.043577, Train ACC:1.000000, Val ACC:0.993750

Epoch 1587/4000: 100%|██████████| 1/1 [00:00<00:00, 23.24it/s]

epoch: 1586, beta = 0.000097, Train MSE: 0.006865, Train CE:0.012706, Train KL:8.697651, Val MSE:0.010567, Val CE:0.043861, Train ACC:1.000000, Val ACC:0.993229

Epoch 1588/4000: 100%|██████████| 1/1 [00:00<00:00, 24.04it/s]

epoch: 1587, beta = 0.000097, Train MSE: 0.006858, Train CE:0.012699, Train KL:8.697966, Val MSE:0.010553, Val CE:0.043810, Train ACC:1.000000, Val ACC:0.993750

Epoch 1589/4000: 100%|██████████| 1/1 [00:00<00:00, 23.29it/s]

epoch: 1588, beta = 0.000097, Train MSE: 0.006846, Train CE:0.012699, Train KL:8.698259, Val MSE:0.010560, Val CE:0.043517, Train ACC:1.000000, Val ACC:0.993750

Epoch 1590/4000: 100%|██████████| 1/1 [00:00<00:00, 28.84it/s]

epoch: 1589, beta = 0.000097, Train MSE: 0.006867, Train CE:0.012688, Train KL:8.698577, Val MSE:0.010571, Val CE:0.043622, Train ACC:1.000000, Val ACC:0.993750

Epoch 1591/4000: 100%|██████████| 1/1 [00:00<00:00, 24.25it/s]

epoch: 1590, beta = 0.000097, Train MSE: 0.006863, Train CE:0.012680, Train KL:8.698903, Val MSE:0.010581, Val CE:0.043764, Train ACC:1.000000, Val ACC:0.993750

Epoch 1592/4000: 100%|██████████| 1/1 [00:00<00:00, 22.30it/s]

epoch: 1591, beta = 0.000097, Train MSE: 0.006858, Train CE:0.012680, Train KL:8.699221, Val MSE:0.010603, Val CE:0.043645, Train ACC:1.000000, Val ACC:0.993750

Epoch 1593/4000: 100%|██████████| 1/1 [00:00<00:00, 21.70it/s]

epoch: 1592, beta = 0.000097, Train MSE: 0.006861, Train CE:0.012681, Train KL:8.699508, Val MSE:0.010572, Val CE:0.043496, Train ACC:1.000000, Val ACC:0.993750

Epoch 1594/4000: 100%|██████████| 1/1 [00:00<00:00, 21.28it/s]

epoch: 1593, beta = 0.000097, Train MSE: 0.006866, Train CE:0.012672, Train KL:8.699790, Val MSE:0.010579, Val CE:0.043494, Train ACC:1.000000, Val ACC:0.993750

Epoch 1595/4000: 100%|██████████| 1/1 [00:00<00:00, 19.52it/s]

epoch: 1594, beta = 0.000097, Train MSE: 0.006855, Train CE:0.012671, Train KL:8.700060, Val MSE:0.010582, Val CE:0.043540, Train ACC:1.000000, Val ACC:0.993750

Epoch 1596/4000: 100%|██████████| 1/1 [00:00<00:00, 22.12it/s]

epoch: 1595, beta = 0.000097, Train MSE: 0.006844, Train CE:0.012662, Train KL:8.700346, Val MSE:0.010565, Val CE:0.043795, Train ACC:1.000000, Val ACC:0.993750

Epoch 1597/4000: 100%|██████████| 1/1 [00:00<00:00, 24.13it/s]

Learning rate updated: 6.944284018723356e-05

epoch: 1596, beta = 0.000097, Train MSE: 0.006853, Train CE:0.012655, Train KL:8.700667, Val MSE:0.010596, Val CE:0.043769, Train ACC:1.000000, Val ACC:0.993750

Epoch 1598/4000: 100%|██████████| 1/1 [00:00<00:00, 24.33it/s]

epoch: 1597, beta = 0.000097, Train MSE: 0.006847, Train CE:0.012654, Train KL:8.701013, Val MSE:0.010585, Val CE:0.043820, Train ACC:1.000000, Val ACC:0.993750

Epoch 1599/4000: 100%|██████████| 1/1 [00:00<00:00, 24.14it/s]

epoch: 1598, beta = 0.000097, Train MSE: 0.006854, Train CE:0.012650, Train KL:8.701309, Val MSE:0.010547, Val CE:0.043628, Train ACC:1.000000, Val ACC:0.993750

Epoch 1600/4000: 100%|██████████| 1/1 [00:00<00:00, 24.05it/s]

epoch: 1599, beta = 0.000097, Train MSE: 0.006865, Train CE:0.012641, Train KL:8.701590, Val MSE:0.010574, Val CE:0.043660, Train ACC:1.000000, Val ACC:0.993750

Epoch 1601/4000: 100%|██████████| 1/1 [00:00<00:00, 23.00it/s]

epoch: 1600, beta = 0.000097, Train MSE: 0.006852, Train CE:0.012642, Train KL:8.701867, Val MSE:0.010563, Val CE:0.043643, Train ACC:1.000000, Val ACC:0.993750

Epoch 1602/4000: 100%|██████████| 1/1 [00:00<00:00, 23.65it/s]

epoch: 1601, beta = 0.000097, Train MSE: 0.006845, Train CE:0.012639, Train KL:8.702169, Val MSE:0.010539, Val CE:0.043807, Train ACC:1.000000, Val ACC:0.993750

Epoch 1603/4000: 100%|██████████| 1/1 [00:00<00:00, 22.06it/s]

epoch: 1602, beta = 0.000097, Train MSE: 0.006851, Train CE:0.012638, Train KL:8.702473, Val MSE:0.010563, Val CE:0.043703, Train ACC:1.000000, Val ACC:0.993750

Epoch 1604/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 1603, beta = 0.000097, Train MSE: 0.006836, Train CE:0.012625, Train KL:8.702784, Val MSE:0.010588, Val CE:0.043680, Train ACC:1.000000, Val ACC:0.993750

Epoch 1605/4000: 100%|██████████| 1/1 [00:00<00:00, 22.51it/s]

epoch: 1604, beta = 0.000097, Train MSE: 0.006840, Train CE:0.012625, Train KL:8.703073, Val MSE:0.010558, Val CE:0.043409, Train ACC:1.000000, Val ACC:0.994271

Epoch 1606/4000: 100%|██████████| 1/1 [00:00<00:00, 24.06it/s]

epoch: 1605, beta = 0.000097, Train MSE: 0.006848, Train CE:0.012612, Train KL:8.703366, Val MSE:0.010556, Val CE:0.043629, Train ACC:1.000000, Val ACC:0.993750

Epoch 1607/4000: 100%|██████████| 1/1 [00:00<00:00, 24.07it/s]

epoch: 1606, beta = 0.000097, Train MSE: 0.006844, Train CE:0.012613, Train KL:8.703690, Val MSE:0.010562, Val CE:0.043787, Train ACC:1.000000, Val ACC:0.993750

Epoch 1608/4000: 100%|██████████| 1/1 [00:00<00:00, 24.60it/s]

Learning rate updated: 6.597069817787189e-05
epoch: 1607, beta = 0.000097, Train MSE: 0.006845, Train CE:0.012614, Train KL:8.704036, Val MSE:0.010554, Val CE:0.043588, Train ACC:1.000000, Val ACC:0.993750

Epoch 1609/4000: 100%|██████████| 1/1 [00:00<00:00, 23.31it/s]

epoch: 1608, beta = 0.000097, Train MSE: 0.006843, Train CE:0.012602, Train KL:8.704374, Val MSE:0.010541, Val CE:0.043747, Train ACC:1.000000, Val ACC:0.993750

Epoch 1610/4000: 100%|██████████| 1/1 [00:00<00:00, 23.93it/s]

epoch: 1609, beta = 0.000097, Train MSE: 0.006830, Train CE:0.012604, Train KL:8.704655, Val MSE:0.010573, Val CE:0.044061, Train ACC:1.000000, Val ACC:0.993750

Epoch 1611/4000: 100%|██████████| 1/1 [00:00<00:00, 21.24it/s]

epoch: 1610, beta = 0.000097, Train MSE: 0.006840, Train CE:0.012598, Train KL:8.704918, Val MSE:0.010553, Val CE:0.043887, Train ACC:1.000000, Val ACC:0.993750

Epoch 1612/4000: 100%|██████████| 1/1 [00:00<00:00, 23.96it/s]

epoch: 1611, beta = 0.000097, Train MSE: 0.006832, Train CE:0.012590, Train KL:8.705186, Val MSE:0.010557, Val CE:0.044057, Train ACC:1.000000, Val ACC:0.993750

Epoch 1613/4000: 100%|██████████| 1/1 [00:00<00:00, 24.04it/s]

epoch: 1612, beta = 0.000097, Train MSE: 0.006836, Train CE:0.012588, Train KL:8.705464, Val MSE:0.010563, Val CE:0.043648, Train ACC:1.000000, Val ACC:0.993750

Epoch 1614/4000: 100%|██████████| 1/1 [00:00<00:00, 24.02it/s]

epoch: 1613, beta = 0.000097, Train MSE: 0.006839, Train CE:0.012590, Train KL:8.705756, Val MSE:0.010568, Val CE:0.043668, Train ACC:1.000000, Val ACC:0.993750

Epoch 1615/4000: 100%|██████████| 1/1 [00:00<00:00, 21.41it/s]

epoch: 1614, beta = 0.000097, Train MSE: 0.006842, Train CE:0.012580, Train KL:8.706056, Val MSE:0.010554, Val CE:0.043494, Train ACC:1.000000, Val ACC:0.993750

Epoch 1616/4000: 100%|██████████| 1/1 [00:00<00:00, 19.52it/s]

epoch: 1615, beta = 0.000097, Train MSE: 0.006831, Train CE:0.012570, Train KL:8.706369, Val MSE:0.010545, Val CE:0.043668, Train ACC:1.000000, Val ACC:0.993750

Epoch 1617/4000: 100%|██████████| 1/1 [00:00<00:00, 21.53it/s]

epoch: 1616, beta = 0.000097, Train MSE: 0.006833, Train CE:0.012569, Train KL:8.706687, Val MSE:0.010529, Val CE:0.043444, Train ACC:1.000000, Val ACC:0.993750

Epoch 1618/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 1617, beta = 0.000097, Train MSE: 0.006827, Train CE:0.012562, Train KL:8.707004, Val MSE:0.010582, Val CE:0.043553, Train ACC:1.000000, Val ACC:0.993750

Epoch 1619/4000: 100%|██████████| 1/1 [00:00<00:00, 24.67it/s]

Learning rate updated: 6.267216326897829e-05
epoch: 1618, beta = 0.000097, Train MSE: 0.006824, Train CE:0.012558, Train KL:8.707302, Val MSE:0.010568, Val CE:0.043969, Train ACC:1.000000, Val ACC:0.993750

Epoch 1620/4000: 100%|██████████| 1/1 [00:00<00:00, 24.15it/s]

epoch: 1619, beta = 0.000097, Train MSE: 0.006833, Train CE:0.012559, Train KL:8.707582, Val MSE:0.010543, Val CE:0.043615, Train ACC:1.000000, Val ACC:0.993750

Epoch 1621/4000: 100%|██████████| 1/1 [00:00<00:00, 25.11it/s]

epoch: 1620, beta = 0.000097, Train MSE: 0.006835, Train CE:0.012552, Train KL:8.707838, Val MSE:0.010551, Val CE:0.043606, Train ACC:1.000000, Val ACC:0.993750

Epoch 1622/4000: 100%|██████████| 1/1 [00:00<00:00, 24.74it/s]

epoch: 1621, beta = 0.000097, Train MSE: 0.006827, Train CE:0.012553, Train KL:8.708077, Val MSE:0.010535, Val CE:0.043375, Train ACC:1.000000, Val ACC:0.993750

Epoch 1623/4000: 100%|██████████| 1/1 [00:00<00:00, 22.32it/s]

epoch: 1622, beta = 0.000097, Train MSE: 0.006828, Train CE:0.012550, Train KL:8.708339, Val MSE:0.010545, Val CE:0.043656, Train ACC:1.000000, Val ACC:0.993750

Epoch 1624/4000: 100%|██████████| 1/1 [00:00<00:00, 26.48it/s]

epoch: 1623, beta = 0.000097, Train MSE: 0.006832, Train CE:0.012543, Train KL:8.708613, Val MSE:0.010579, Val CE:0.043481, Train ACC:1.000000, Val ACC:0.993750

Epoch 1625/4000: 100%|██████████| 1/1 [00:00<00:00, 18.53it/s]

epoch: 1624, beta = 0.000097, Train MSE: 0.006834, Train CE:0.012542, Train KL:8.708885, Val MSE:0.010530, Val CE:0.043559, Train ACC:1.000000, Val ACC:0.993750

Epoch 1626/4000: 100%|██████████| 1/1 [00:00<00:00, 21.42it/s]

epoch: 1625, beta = 0.000097, Train MSE: 0.006814, Train CE:0.012535, Train KL:8.709182, Val MSE:0.010547, Val CE:0.043669, Train ACC:1.000000, Val ACC:0.993750

Epoch 1627/4000: 100%|██████████| 1/1 [00:00<00:00, 25.12it/s]

epoch: 1626, beta = 0.000097, Train MSE: 0.006826, Train CE:0.012534, Train KL:8.709467, Val MSE:0.010562, Val CE:0.043780, Train ACC:1.000000, Val ACC:0.993750

Epoch 1628/4000: 100%|██████████| 1/1 [00:00<00:00, 24.61it/s]

epoch: 1627, beta = 0.000097, Train MSE: 0.006818, Train CE:0.012533, Train KL:8.709760, Val MSE:0.010528, Val CE:0.043461, Train ACC:1.000000, Val ACC:0.993750

Epoch 1629/4000: 100%|██████████| 1/1 [00:00<00:00, 21.50it/s]

epoch: 1628, beta = 0.000097, Train MSE: 0.006822, Train CE:0.012522, Train KL:8.710012, Val MSE:0.010540, Val CE:0.043554, Train ACC:1.000000, Val ACC:0.993750

Epoch 1630/4000: 100%|██████████| 1/1 [00:00<00:00, 21.06it/s]

Learning rate updated: 5.953855510552937e-05
epoch: 1629, beta = 0.000097, Train MSE: 0.006824, Train CE:0.012521, Train KL:8.710264, Val MSE:0.010531, Val CE:0.043377, Train ACC:1.000000, Val ACC:0.993750

Epoch 1631/4000: 100%|██████████| 1/1 [00:00<00:00, 24.47it/s]

epoch: 1630, beta = 0.000097, Train MSE: 0.006822, Train CE:0.012515, Train KL:8.710554, Val MSE:0.010558, Val CE:0.043755, Train ACC:1.000000, Val ACC:0.993750

Epoch 1632/4000: 100%|██████████| 1/1 [00:00<00:00, 24.05it/s]

epoch: 1631, beta = 0.000097, Train MSE: 0.006818, Train CE:0.012512, Train KL:8.710835, Val MSE:0.010542, Val CE:0.043720, Train ACC:1.000000, Val ACC:0.993750

Epoch 1633/4000: 100%|██████████| 1/1 [00:00<00:00, 22.99it/s]

epoch: 1632, beta = 0.000097, Train MSE: 0.006828, Train CE:0.012503, Train KL:8.711092, Val MSE:0.010527, Val CE:0.043809, Train ACC:1.000000, Val ACC:0.993229

Epoch 1634/4000: 100%|██████████| 1/1 [00:00<00:00, 24.28it/s]

epoch: 1633, beta = 0.000097, Train MSE: 0.006815, Train CE:0.012503, Train KL:8.711335, Val MSE:0.010547, Val CE:0.043720, Train ACC:1.000000, Val ACC:0.993750

Epoch 1635/4000: 100%|██████████| 1/1 [00:00<00:00, 21.83it/s]

epoch: 1634, beta = 0.000097, Train MSE: 0.006815, Train CE:0.012503, Train KL:8.711566, Val MSE:0.010530, Val CE:0.043631, Train ACC:1.000000, Val ACC:0.993750

Epoch 1636/4000: 100%|██████████| 1/1 [00:00<00:00, 21.07it/s]

epoch: 1635, beta = 0.000097, Train MSE: 0.006809, Train CE:0.012499, Train KL:8.711802, Val MSE:0.010522, Val CE:0.043668, Train ACC:1.000000, Val ACC:0.993750

Epoch 1637/4000: 100%|██████████| 1/1 [00:00<00:00, 23.79it/s]

epoch: 1636, beta = 0.000097, Train MSE: 0.006812, Train CE:0.012492, Train KL:8.712063, Val MSE:0.010534, Val CE:0.043611, Train ACC:1.000000, Val ACC:0.993750

Epoch 1638/4000: 100%|██████████| 1/1 [00:00<00:00, 24.14it/s]

epoch: 1637, beta = 0.000097, Train MSE: 0.006805, Train CE:0.012481, Train KL:8.712338, Val MSE:0.010520, Val CE:0.043600, Train ACC:1.000000, Val ACC:0.993750

Epoch 1639/4000: 100%|██████████| 1/1 [00:00<00:00, 20.51it/s]

epoch: 1638, beta = 0.000097, Train MSE: 0.006814, Train CE:0.012481, Train KL:8.712620, Val MSE:0.010531, Val CE:0.043711, Train ACC:1.000000, Val ACC:0.993750

Epoch 1640/4000: 100%|██████████| 1/1 [00:00<00:00, 23.54it/s]

epoch: 1639, beta = 0.000097, Train MSE: 0.006817, Train CE:0.012476, Train KL:8.712894, Val MSE:0.010515, Val CE:0.043824, Train ACC:1.000000, Val ACC:0.993750

Epoch 1641/4000: 100%|██████████| 1/1 [00:00<00:00, 24.65it/s]

Learning rate updated: 5.65616273502529e-05
epoch: 1640, beta = 0.000097, Train MSE: 0.006808, Train CE:0.012475, Train KL:8.713121, Val MSE:0.010533, Val CE:0.043568, Train ACC:1.000000, Val ACC:0.993750

Epoch 1642/4000: 100%|██████████| 1/1 [00:00<00:00, 24.91it/s]

epoch: 1641, beta = 0.000097, Train MSE: 0.006805, Train CE:0.012471, Train KL:8.713338, Val MSE:0.010511, Val CE:0.043715, Train ACC:1.000000, Val ACC:0.993750

Epoch 1643/4000: 100%|██████████| 1/1 [00:00<00:00, 24.60it/s]

epoch: 1642, beta = 0.000097, Train MSE: 0.006805, Train CE:0.012470, Train KL:8.713538, Val MSE:0.010516, Val CE:0.043379, Train ACC:1.000000, Val ACC:0.993750

Epoch 1644/4000: 100%|██████████| 1/1 [00:00<00:00, 24.85it/s]

epoch: 1643, beta = 0.000097, Train MSE: 0.006810, Train CE:0.012464, Train KL:8.713768, Val MSE:0.010528, Val CE:0.043679, Train ACC:1.000000, Val ACC:0.993750

Epoch 1645/4000: 100%|██████████| 1/1 [00:00<00:00, 23.88it/s]

epoch: 1644, beta = 0.000097, Train MSE: 0.006811, Train CE:0.012463, Train KL:8.714029, Val MSE:0.010504, Val CE:0.043752, Train ACC:1.000000, Val ACC:0.993750

Epoch 1646/4000: 100%|██████████| 1/1 [00:00<00:00, 23.53it/s]

epoch: 1645, beta = 0.000097, Train MSE: 0.006797, Train CE:0.012461, Train KL:8.714300, Val MSE:0.010502, Val CE:0.043877, Train ACC:1.000000, Val ACC:0.993750

Epoch 1647/4000: 100%|██████████| 1/1 [00:00<00:00, 23.15it/s]

epoch: 1646, beta = 0.000097, Train MSE: 0.006796, Train CE:0.012458, Train KL:8.714549, Val MSE:0.010485, Val CE:0.043883, Train ACC:1.000000, Val ACC:0.993750

Epoch 1648/4000: 100%|██████████| 1/1 [00:00<00:00, 20.79it/s]

epoch: 1647, beta = 0.000097, Train MSE: 0.006810, Train CE:0.012450, Train KL:8.714777, Val MSE:0.010514, Val CE:0.043829, Train ACC:1.000000, Val ACC:0.993750

Epoch 1649/4000: 100%|██████████| 1/1 [00:00<00:00, 23.09it/s]

epoch: 1648, beta = 0.000097, Train MSE: 0.006804, Train CE:0.012447, Train KL:8.714988, Val MSE:0.010470, Val CE:0.043781, Train ACC:1.000000, Val ACC:0.993750

Epoch 1650/4000: 100%|██████████| 1/1 [00:00<00:00, 23.35it/s]

epoch: 1649, beta = 0.000097, Train MSE: 0.006796, Train CE:0.012449, Train KL:8.715194, Val MSE:0.010490, Val CE:0.043617, Train ACC:1.000000, Val ACC:0.993750

Epoch 1651/4000: 100%|██████████| 1/1 [00:00<00:00, 24.65it/s]

epoch: 1650, beta = 0.000097, Train MSE: 0.006817, Train CE:0.012441, Train KL:8.715418, Val MSE:0.010502, Val CE:0.043544, Train ACC:1.000000, Val ACC:0.993750

Epoch 1652/4000: 100%|██████████| 1/1 [00:00<00:00, 24.60it/s]

Learning rate updated: 5.373354598274025e-05
epoch: 1651, beta = 0.000097, Train MSE: 0.006807, Train CE:0.012439, Train KL:8.715663, Val MSE:0.010484, Val CE:0.043473, Train ACC:1.000000, Val ACC:0.993750

Epoch 1653/4000: 100%|██████████| 1/1 [00:00<00:00, 24.06it/s]

epoch: 1652, beta = 0.000097, Train MSE: 0.006793, Train CE:0.012430, Train KL:8.715919, Val MSE:0.010510, Val CE:0.043597, Train ACC:1.000000, Val ACC:0.993750

Epoch 1654/4000: 100%|██████████| 1/1 [00:00<00:00, 20.91it/s]

epoch: 1653, beta = 0.000097, Train MSE: 0.006801, Train CE:0.012435, Train KL:8.716152, Val MSE:0.010520, Val CE:0.043592, Train ACC:1.000000, Val ACC:0.993750

Epoch 1655/4000: 100%|██████████| 1/1 [00:00<00:00, 23.98it/s]

epoch: 1654, beta = 0.000097, Train MSE: 0.006798, Train CE:0.012429, Train KL:8.716374, Val MSE:0.010461, Val CE:0.043663, Train ACC:1.000000, Val ACC:0.993750

Epoch 1656/4000: 100%|██████████| 1/1 [00:00<00:00, 24.60it/s]

epoch: 1655, beta = 0.000097, Train MSE: 0.006795, Train CE:0.012419, Train KL:8.716585, Val MSE:0.010490, Val CE:0.043698, Train ACC:1.000000, Val ACC:0.993750

Epoch 1657/4000: 100%|██████████| 1/1 [00:00<00:00, 26.93it/s]

epoch: 1656, beta = 0.000097, Train MSE: 0.006801, Train CE:0.012426, Train KL:8.716781, Val MSE:0.010481, Val CE:0.043576, Train ACC:1.000000, Val ACC:0.993750

Epoch 1658/4000: 100%|██████████| 1/1 [00:00<00:00, 24.60it/s]

epoch: 1657, beta = 0.000097, Train MSE: 0.006804, Train CE:0.012415, Train KL:8.717000, Val MSE:0.010489, Val CE:0.043597, Train ACC:1.000000, Val ACC:0.993750

Epoch 1659/4000: 100%|██████████| 1/1 [00:00<00:00, 23.83it/s]

epoch: 1658, beta = 0.000097, Train MSE: 0.006798, Train CE:0.012414, Train KL:8.717237, Val MSE:0.010502, Val CE:0.043657, Train ACC:1.000000, Val ACC:0.993750

Epoch 1660/4000: 100%|██████████| 1/1 [00:00<00:00, 20.46it/s]

epoch: 1659, beta = 0.000097, Train MSE: 0.006801, Train CE:0.012418, Train KL:8.717483, Val MSE:0.010501, Val CE:0.043642, Train ACC:1.000000, Val ACC:0.993750

Epoch 1661/4000: 100%|██████████| 1/1 [00:00<00:00, 20.94it/s]

epoch: 1660, beta = 0.000097, Train MSE: 0.006790, Train CE:0.012410, Train KL:8.717740, Val MSE:0.010498, Val CE:0.043644, Train ACC:1.000000, Val ACC:0.993750

Epoch 1662/4000: 100%|██████████| 1/1 [00:00<00:00, 21.23it/s]

epoch: 1661, beta = 0.000097, Train MSE: 0.006793, Train CE:0.012401, Train KL:8.717971, Val MSE:0.010514, Val CE:0.043641, Train ACC:1.000000, Val ACC:0.993750

Epoch 1663/4000: 100%|██████████| 1/1 [00:00<00:00, 24.08it/s]

Learning rate updated: 5.104686868360323e-05
epoch: 1662, beta = 0.000097, Train MSE: 0.006786, Train CE:0.012400, Train KL:8.718181, Val MSE:0.010473, Val CE:0.043499, Train ACC:1.000000, Val ACC:0.993750

Epoch 1664/4000: 100%|██████████| 1/1 [00:00<00:00, 25.77it/s]

epoch: 1663, beta = 0.000097, Train MSE: 0.006794, Train CE:0.012390, Train KL:8.718382, Val MSE:0.010466, Val CE:0.043743, Train ACC:1.000000, Val ACC:0.993750

Epoch 1665/4000: 100%|██████████| 1/1 [00:00<00:00, 25.91it/s]

epoch: 1664, beta = 0.000097, Train MSE: 0.006791, Train CE:0.012388, Train KL:8.718576, Val MSE:0.010521, Val CE:0.043597, Train ACC:1.000000, Val ACC:0.993750

Epoch 1666/4000: 100%|██████████| 1/1 [00:00<00:00, 24.02it/s]

epoch: 1665, beta = 0.000097, Train MSE: 0.006788, Train CE:0.012387, Train KL:8.718775, Val MSE:0.010470, Val CE:0.043649, Train ACC:1.000000, Val ACC:0.993750

Epoch 1667/4000: 100%|██████████| 1/1 [00:00<00:00, 20.80it/s]

epoch: 1666, beta = 0.000097, Train MSE: 0.006789, Train CE:0.012392, Train KL:8.718976, Val MSE:0.010485, Val CE:0.043528, Train ACC:1.000000, Val ACC:0.993750

Epoch 1668/4000: 100%|██████████| 1/1 [00:00<00:00, 23.81it/s]

epoch: 1667, beta = 0.000097, Train MSE: 0.006787, Train CE:0.012378, Train KL:8.719201, Val MSE:0.010484, Val CE:0.043577, Train ACC:1.000000, Val ACC:0.993750

Epoch 1669/4000: 100%|██████████| 1/1 [00:00<00:00, 23.29it/s]

epoch: 1668, beta = 0.000097, Train MSE: 0.006790, Train CE:0.012382, Train KL:8.719419, Val MSE:0.010482, Val CE:0.043466, Train ACC:1.000000, Val ACC:0.993750

Epoch 1670/4000: 100%|██████████| 1/1 [00:00<00:00, 25.14it/s]

epoch: 1669, beta = 0.000097, Train MSE: 0.006788, Train CE:0.012374, Train KL:8.719649, Val MSE:0.010473, Val CE:0.043739, Train ACC:1.000000, Val ACC:0.993750

Epoch 1671/4000: 100%|██████████| 1/1 [00:00<00:00, 24.05it/s]

epoch: 1670, beta = 0.000097, Train MSE: 0.006781, Train CE:0.012380, Train KL:8.719863, Val MSE:0.010492, Val CE:0.043412, Train ACC:1.000000, Val ACC:0.993750

Epoch 1672/4000: 100%|██████████| 1/1 [00:00<00:00, 21.22it/s]

epoch: 1671, beta = 0.000097, Train MSE: 0.006780, Train CE:0.012375, Train KL:8.720058, Val MSE:0.010477, Val CE:0.043549, Train ACC:1.000000, Val ACC:0.993750

Epoch 1673/4000: 100%|██████████| 1/1 [00:00<00:00, 24.24it/s]

epoch: 1672, beta = 0.000097, Train MSE: 0.006797, Train CE:0.012372, Train KL:8.720244, Val MSE:0.010483, Val CE:0.043429, Train ACC:1.000000, Val ACC:0.993750

Epoch 1674/4000: 100%|██████████| 1/1 [00:00<00:00, 26.02it/s]

Learning rate updated: 4.849452524942307e-05
epoch: 1673, beta = 0.000097, Train MSE: 0.006779, Train CE:0.012367, Train KL:8.720449, Val MSE:0.010468, Val CE:0.043306, Train ACC:1.000000, Val ACC:0.993750

Epoch 1675/4000: 100%|██████████| 1/1 [00:00<00:00, 22.60it/s]

epoch: 1674, beta = 0.000097, Train MSE: 0.006785, Train CE:0.012364, Train KL:8.720670, Val MSE:0.010451, Val CE:0.043306, Train ACC:1.000000, Val ACC:0.993750

Epoch 1676/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 1675, beta = 0.000097, Train MSE: 0.006774, Train CE:0.012353, Train KL:8.720893, Val MSE:0.010480, Val CE:0.043629, Train ACC:1.000000, Val ACC:0.993750

Epoch 1677/4000: 100%|██████████| 1/1 [00:00<00:00, 24.21it/s]

epoch: 1676, beta = 0.000097, Train MSE: 0.006784, Train CE:0.012358, Train KL:8.721119, Val MSE:0.010466, Val CE:0.043318, Train ACC:1.000000, Val ACC:0.993750

Epoch 1678/4000: 100%|██████████| 1/1 [00:00<00:00, 20.90it/s]

epoch: 1677, beta = 0.000097, Train MSE: 0.006778, Train CE:0.012351, Train KL:8.721345, Val MSE:0.010495, Val CE:0.043529, Train ACC:1.000000, Val ACC:0.993750

Epoch 1679/4000: 100%|██████████| 1/1 [00:00<00:00, 24.05it/s]

epoch: 1678, beta = 0.000097, Train MSE: 0.006781, Train CE:0.012350, Train KL:8.721571, Val MSE:0.010497, Val CE:0.043490, Train ACC:1.000000, Val ACC:0.993750

Epoch 1680/4000: 100%|██████████| 1/1 [00:00<00:00, 24.70it/s]

epoch: 1679, beta = 0.000097, Train MSE: 0.006781, Train CE:0.012351, Train KL:8.721795, Val MSE:0.010505, Val CE:0.043434, Train ACC:1.000000, Val ACC:0.993750

Epoch 1681/4000: 100%|██████████| 1/1 [00:00<00:00, 22.89it/s]

epoch: 1680, beta = 0.000097, Train MSE: 0.006784, Train CE:0.012343, Train KL:8.722016, Val MSE:0.010486, Val CE:0.043640, Train ACC:1.000000, Val ACC:0.993750

Epoch 1682/4000: 100%|██████████| 1/1 [00:00<00:00, 20.93it/s]

epoch: 1681, beta = 0.000097, Train MSE: 0.006775, Train CE:0.012340, Train KL:8.722222, Val MSE:0.010491, Val CE:0.043760, Train ACC:1.000000, Val ACC:0.993750

Epoch 1683/4000: 100%|██████████| 1/1 [00:00<00:00, 22.71it/s]

epoch: 1682, beta = 0.000097, Train MSE: 0.006779, Train CE:0.012336, Train KL:8.722426, Val MSE:0.010469, Val CE:0.043689, Train ACC:1.000000, Val ACC:0.993750

Epoch 1684/4000: 100%|██████████| 1/1 [00:00<00:00, 24.12it/s]

epoch: 1683, beta = 0.000097, Train MSE: 0.006778, Train CE:0.012334, Train KL:8.722617, Val MSE:0.010508, Val CE:0.043555, Train ACC:1.000000, Val ACC:0.993750

Epoch 1685/4000: 100%|██████████| 1/1 [00:00<00:00, 24.63it/s]

Learning rate updated: 4.606979898695191e-05
epoch: 1684, beta = 0.000097, Train MSE: 0.006781, Train CE:0.012330, Train KL:8.722826, Val MSE:0.010487, Val CE:0.043450, Train ACC:1.000000, Val ACC:0.993750

Epoch 1686/4000: 100%|██████████| 1/1 [00:00<00:00, 25.27it/s]

epoch: 1685, beta = 0.000097, Train MSE: 0.006771, Train CE:0.012327, Train KL:8.723047, Val MSE:0.010477, Val CE:0.043409, Train ACC:1.000000, Val ACC:0.993750

Epoch 1687/4000: 100%|██████████| 1/1 [00:00<00:00, 23.58it/s]

epoch: 1686, beta = 0.000097, Train MSE: 0.006781, Train CE:0.012322, Train KL:8.723269, Val MSE:0.010486, Val CE:0.043599, Train ACC:1.000000, Val ACC:0.993750

Epoch 1688/4000: 100%|██████████| 1/1 [00:00<00:00, 24.03it/s]

epoch: 1687, beta = 0.000097, Train MSE: 0.006776, Train CE:0.012322, Train KL:8.723507, Val MSE:0.010486, Val CE:0.043548, Train ACC:1.000000, Val ACC:0.993750

Epoch 1689/4000: 100%|██████████| 1/1 [00:00<00:00, 25.11it/s]

epoch: 1688, beta = 0.000097, Train MSE: 0.006776, Train CE:0.012320, Train KL:8.723742, Val MSE:0.010462, Val CE:0.043545, Train ACC:1.000000, Val ACC:0.993750

Epoch 1690/4000: 100%|██████████| 1/1 [00:00<00:00, 23.95it/s]

epoch: 1689, beta = 0.000097, Train MSE: 0.006773, Train CE:0.012313, Train KL:8.723960, Val MSE:0.010476, Val CE:0.043612, Train ACC:1.000000, Val ACC:0.993750

Epoch 1691/4000: 100%|██████████| 1/1 [00:00<00:00, 23.80it/s]

epoch: 1690, beta = 0.000097, Train MSE: 0.006772, Train CE:0.012316, Train KL:8.724152, Val MSE:0.010484, Val CE:0.043543, Train ACC:1.000000, Val ACC:0.993750

Epoch 1692/4000: 100%|██████████| 1/1 [00:00<00:00, 24.11it/s]

epoch: 1691, beta = 0.000097, Train MSE: 0.006780, Train CE:0.012310, Train KL:8.724327, Val MSE:0.010481, Val CE:0.043414, Train ACC:1.000000, Val ACC:0.993750

Epoch 1693/4000: 100%|██████████| 1/1 [00:00<00:00, 22.32it/s]

epoch: 1692, beta = 0.000097, Train MSE: 0.006776, Train CE:0.012308, Train KL:8.724511, Val MSE:0.010435, Val CE:0.043404, Train ACC:1.000000, Val ACC:0.993750

Epoch 1694/4000: 100%|██████████| 1/1 [00:00<00:00, 24.44it/s]

epoch: 1693, beta = 0.000097, Train MSE: 0.006764, Train CE:0.012307, Train KL:8.724715, Val MSE:0.010459, Val CE:0.043486, Train ACC:1.000000, Val ACC:0.993750

Epoch 1695/4000: 100%|██████████| 1/1 [00:00<00:00, 24.10it/s]

epoch: 1694, beta = 0.000097, Train MSE: 0.006766, Train CE:0.012302, Train KL:8.724936, Val MSE:0.010479, Val CE:0.043629, Train ACC:1.000000, Val ACC:0.993750

Epoch 1696/4000: 100%|██████████| 1/1 [00:00<00:00, 24.85it/s]

Learning rate updated: 4.376630903760431e-05
epoch: 1695, beta = 0.000097, Train MSE: 0.006767, Train CE:0.012298, Train KL:8.725163, Val MSE:0.010443, Val CE:0.043599, Train ACC:1.000000, Val ACC:0.993750

Epoch 1697/4000: 100%|██████████| 1/1 [00:00<00:00, 24.04it/s]

epoch: 1696, beta = 0.000097, Train MSE: 0.006782, Train CE:0.012296, Train KL:8.725377, Val MSE:0.010450, Val CE:0.043451, Train ACC:1.000000, Val ACC:0.993750

Epoch 1698/4000: 100%|██████████| 1/1 [00:00<00:00, 23.80it/s]

epoch: 1697, beta = 0.000097, Train MSE: 0.006764, Train CE:0.012295, Train KL:8.725580, Val MSE:0.010482, Val CE:0.043559, Train ACC:1.000000, Val ACC:0.993750

Epoch 1699/4000: 100%|██████████| 1/1 [00:00<00:00, 28.84it/s]

epoch: 1698, beta = 0.000097, Train MSE: 0.006764, Train CE:0.012291, Train KL:8.725779, Val MSE:0.010466, Val CE:0.043424, Train ACC:1.000000, Val ACC:0.993750

Epoch 1700/4000: 100%|██████████| 1/1 [00:00<00:00, 24.68it/s]

epoch: 1699, beta = 0.000097, Train MSE: 0.006771, Train CE:0.012285, Train KL:8.725975, Val MSE:0.010457, Val CE:0.043475, Train ACC:1.000000, Val ACC:0.993750

Epoch 1701/4000: 100%|██████████| 1/1 [00:00<00:00, 23.99it/s]

epoch: 1700, beta = 0.000097, Train MSE: 0.006765, Train CE:0.012283, Train KL:8.726187, Val MSE:0.010449, Val CE:0.043488, Train ACC:1.000000, Val ACC:0.993750

Epoch 1702/4000: 100%|██████████| 1/1 [00:00<00:00, 24.05it/s]

epoch: 1701, beta = 0.000097, Train MSE: 0.006763, Train CE:0.012280, Train KL:8.726400, Val MSE:0.010452, Val CE:0.043616, Train ACC:1.000000, Val ACC:0.993750

Epoch 1703/4000: 100%|██████████| 1/1 [00:00<00:00, 22.21it/s]

epoch: 1702, beta = 0.000097, Train MSE: 0.006753, Train CE:0.012277, Train KL:8.726606, Val MSE:0.010452, Val CE:0.043633, Train ACC:1.000000, Val ACC:0.993750

Epoch 1704/4000: 100%|██████████| 1/1 [00:00<00:00, 23.87it/s]

epoch: 1703, beta = 0.000097, Train MSE: 0.006752, Train CE:0.012275, Train KL:8.726795, Val MSE:0.010478, Val CE:0.043868, Train ACC:1.000000, Val ACC:0.993750

Epoch 1705/4000: 100%|██████████| 1/1 [00:00<00:00, 20.25it/s]

epoch: 1704, beta = 0.000097, Train MSE: 0.006771, Train CE:0.012277, Train KL:8.726974, Val MSE:0.010444, Val CE:0.043727, Train ACC:1.000000, Val ACC:0.993750

Epoch 1706/4000: 100%|██████████| 1/1 [00:00<00:00, 22.63it/s]

epoch: 1705, beta = 0.000097, Train MSE: 0.006758, Train CE:0.012268, Train KL:8.727148, Val MSE:0.010451, Val CE:0.043588, Train ACC:1.000000, Val ACC:0.993750

Epoch 1707/4000: 100%|██████████| 1/1 [00:00<00:00, 22.85it/s]

Learning rate updated: 4.157799358572409e-05
epoch: 1706, beta = 0.000097, Train MSE: 0.006758, Train CE:0.012269, Train KL:8.727315, Val MSE:0.010471, Val CE:0.043565, Train ACC:1.000000, Val ACC:0.993750

Epoch 1708/4000: 100%|██████████| 1/1 [00:00<00:00, 22.03it/s]

epoch: 1707, beta = 0.000097, Train MSE: 0.006756, Train CE:0.012266, Train KL:8.727487, Val MSE:0.010449, Val CE:0.043538, Train ACC:1.000000, Val ACC:0.993750

Epoch 1709/4000: 100%|██████████| 1/1 [00:00<00:00, 21.37it/s]

epoch: 1708, beta = 0.000097, Train MSE: 0.006757, Train CE:0.012260, Train KL:8.727656, Val MSE:0.010432, Val CE:0.043521, Train ACC:1.000000, Val ACC:0.993750

Epoch 1710/4000: 100%|██████████| 1/1 [00:00<00:00, 24.39it/s]

epoch: 1709, beta = 0.000097, Train MSE: 0.006756, Train CE:0.012259, Train KL:8.727838, Val MSE:0.010448, Val CE:0.043404, Train ACC:1.000000, Val ACC:0.993750

Epoch 1711/4000: 100%|██████████| 1/1 [00:00<00:00, 23.60it/s]

epoch: 1710, beta = 0.000097, Train MSE: 0.006757, Train CE:0.012256, Train KL:8.728022, Val MSE:0.010456, Val CE:0.043452, Train ACC:1.000000, Val ACC:0.993750

Epoch 1712/4000: 100%|██████████| 1/1 [00:00<00:00, 24.87it/s]

epoch: 1711, beta = 0.000097, Train MSE: 0.006749, Train CE:0.012254, Train KL:8.728203, Val MSE:0.010448, Val CE:0.043696, Train ACC:1.000000, Val ACC:0.993750

Epoch 1713/4000: 100%|██████████| 1/1 [00:00<00:00, 21.72it/s]

epoch: 1712, beta = 0.000097, Train MSE: 0.006754, Train CE:0.012255, Train KL:8.728380, Val MSE:0.010451, Val CE:0.043544, Train ACC:1.000000, Val ACC:0.993750

Epoch 1714/4000: 100%|██████████| 1/1 [00:00<00:00, 24.03it/s]

epoch: 1713, beta = 0.000097, Train MSE: 0.006759, Train CE:0.012245, Train KL:8.728545, Val MSE:0.010474, Val CE:0.043684, Train ACC:1.000000, Val ACC:0.993750

Epoch 1715/4000: 100%|██████████| 1/1 [00:00<00:00, 23.32it/s]

epoch: 1714, beta = 0.000097, Train MSE: 0.006760, Train CE:0.012245, Train KL:8.728707, Val MSE:0.010478, Val CE:0.043743, Train ACC:1.000000, Val ACC:0.993750

Epoch 1716/4000: 100%|██████████| 1/1 [00:00<00:00, 23.19it/s]

epoch: 1715, beta = 0.000097, Train MSE: 0.006757, Train CE:0.012243, Train KL:8.728877, Val MSE:0.010449, Val CE:0.043551, Train ACC:1.000000, Val ACC:0.993750

Epoch 1717/4000: 100%|██████████| 1/1 [00:00<00:00, 22.87it/s]

epoch: 1716, beta = 0.000097, Train MSE: 0.006747, Train CE:0.012237, Train KL:8.729052, Val MSE:0.010481, Val CE:0.043683, Train ACC:1.000000, Val ACC:0.993750

Epoch 1718/4000: 100%|██████████| 1/1 [00:00<00:00, 24.40it/s]

Learning rate updated: 3.9499093906437885e-05
epoch: 1717, beta = 0.000097, Train MSE: 0.006754, Train CE:0.012238, Train KL:8.729233, Val MSE:0.010442, Val CE:0.043607, Train ACC:1.000000, Val ACC:0.993750

Epoch 1719/4000: 100%|██████████| 1/1 [00:00<00:00, 23.57it/s]

epoch: 1718, beta = 0.000097, Train MSE: 0.006754, Train CE:0.012236, Train KL:8.729418, Val MSE:0.010467, Val CE:0.043811, Train ACC:1.000000, Val ACC:0.993750

Epoch 1720/4000: 100%|██████████| 1/1 [00:00<00:00, 22.28it/s]

epoch: 1719, beta = 0.000097, Train MSE: 0.006745, Train CE:0.012231, Train KL:8.729592, Val MSE:0.010456, Val CE:0.043863, Train ACC:1.000000, Val ACC:0.993750

Epoch 1721/4000: 100%|██████████| 1/1 [00:00<00:00, 23.58it/s]

epoch: 1720, beta = 0.000097, Train MSE: 0.006752, Train CE:0.012231, Train KL:8.729767, Val MSE:0.010464, Val CE:0.043713, Train ACC:1.000000, Val ACC:0.993750

Epoch 1722/4000: 100%|██████████| 1/1 [00:00<00:00, 23.03it/s]

epoch: 1721, beta = 0.000097, Train MSE: 0.006755, Train CE:0.012223, Train KL:8.729937, Val MSE:0.010435, Val CE:0.043430, Train ACC:1.000000, Val ACC:0.993750

Epoch 1723/4000: 100%|██████████| 1/1 [00:00<00:00, 24.08it/s]

epoch: 1722, beta = 0.000097, Train MSE: 0.006747, Train CE:0.012221, Train KL:8.730113, Val MSE:0.010419, Val CE:0.043724, Train ACC:1.000000, Val ACC:0.993750

Epoch 1724/4000: 100%|██████████| 1/1 [00:00<00:00, 23.84it/s]

epoch: 1723, beta = 0.000097, Train MSE: 0.006758, Train CE:0.012222, Train KL:8.730288, Val MSE:0.010439, Val CE:0.043532, Train ACC:1.000000, Val ACC:0.993750

Epoch 1725/4000: 100%|██████████| 1/1 [00:00<00:00, 23.63it/s]

epoch: 1724, beta = 0.000097, Train MSE: 0.006746, Train CE:0.012219, Train KL:8.730460, Val MSE:0.010458, Val CE:0.043491, Train ACC:1.000000, Val ACC:0.993750

Epoch 1726/4000: 100%|██████████| 1/1 [00:00<00:00, 22.46it/s]

epoch: 1725, beta = 0.000097, Train MSE: 0.006750, Train CE:0.012218, Train KL:8.730627, Val MSE:0.010455, Val CE:0.043507, Train ACC:1.000000, Val ACC:0.993750

Epoch 1727/4000: 100%|██████████| 1/1 [00:00<00:00, 23.98it/s]

epoch: 1726, beta = 0.000097, Train MSE: 0.006755, Train CE:0.012211, Train KL:8.730798, Val MSE:0.010452, Val CE:0.043646, Train ACC:1.000000, Val ACC:0.993750

Epoch 1728/4000: 100%|██████████| 1/1 [00:00<00:00, 24.17it/s]

epoch: 1727, beta = 0.000097, Train MSE: 0.006759, Train CE:0.012213, Train KL:8.730971, Val MSE:0.010441, Val CE:0.043506, Train ACC:1.000000, Val ACC:0.993750

Epoch 1729/4000: 100%|██████████| 1/1 [00:00<00:00, 25.07it/s]

Learning rate updated: 3.752413921111599e-05
epoch: 1728, beta = 0.000097, Train MSE: 0.006746, Train CE:0.012212, Train KL:8.731140, Val MSE:0.010460, Val CE:0.043653, Train ACC:1.000000, Val ACC:0.993750

Epoch 1730/4000: 100%|██████████| 1/1 [00:00<00:00, 24.68it/s]

epoch: 1729, beta = 0.000097, Train MSE: 0.006744, Train CE:0.012206, Train KL:8.731301, Val MSE:0.010421, Val CE:0.043436, Train ACC:1.000000, Val ACC:0.993750

Epoch 1731/4000: 100%|██████████| 1/1 [00:00<00:00, 18.78it/s]

epoch: 1730, beta = 0.000097, Train MSE: 0.006746, Train CE:0.012209, Train KL:8.731456, Val MSE:0.010447, Val CE:0.043617, Train ACC:1.000000, Val ACC:0.993750

Epoch 1732/4000: 100%|██████████| 1/1 [00:00<00:00, 24.31it/s]

epoch: 1731, beta = 0.000097, Train MSE: 0.006747, Train CE:0.012203, Train KL:8.731622, Val MSE:0.010438, Val CE:0.043482, Train ACC:1.000000, Val ACC:0.993750

Epoch 1733/4000: 100%|██████████| 1/1 [00:00<00:00, 24.37it/s]

epoch: 1732, beta = 0.000097, Train MSE: 0.006741, Train CE:0.012199, Train KL:8.731793, Val MSE:0.010475, Val CE:0.043420, Train ACC:1.000000, Val ACC:0.993750

Epoch 1734/4000: 100%|██████████| 1/1 [00:00<00:00, 23.71it/s]

epoch: 1733, beta = 0.000097, Train MSE: 0.006741, Train CE:0.012196, Train KL:8.731958, Val MSE:0.010436, Val CE:0.043591, Train ACC:1.000000, Val ACC:0.993750

Epoch 1735/4000: 100%|██████████| 1/1 [00:00<00:00, 24.55it/s]

epoch: 1734, beta = 0.000097, Train MSE: 0.006749, Train CE:0.012184, Train KL:8.732111, Val MSE:0.010442, Val CE:0.043699, Train ACC:1.000000, Val ACC:0.993750

Epoch 1736/4000: 100%|██████████| 1/1 [00:00<00:00, 24.91it/s]

epoch: 1735, beta = 0.000097, Train MSE: 0.006744, Train CE:0.012193, Train KL:8.732260, Val MSE:0.010423, Val CE:0.043455, Train ACC:1.000000, Val ACC:0.993750

Epoch 1737/4000: 100%|██████████| 1/1 [00:00<00:00, 23.02it/s]

epoch: 1736, beta = 0.000097, Train MSE: 0.006742, Train CE:0.012190, Train KL:8.732403, Val MSE:0.010466, Val CE:0.043441, Train ACC:1.000000, Val ACC:0.993750

Epoch 1738/4000: 100%|██████████| 1/1 [00:00<00:00, 25.79it/s]

epoch: 1737, beta = 0.000097, Train MSE: 0.006736, Train CE:0.012185, Train KL:8.732552, Val MSE:0.010424, Val CE:0.043452, Train ACC:1.000000, Val ACC:0.993750

Epoch 1739/4000: 100%|██████████| 1/1 [00:00<00:00, 23.19it/s]

epoch: 1738, beta = 0.000097, Train MSE: 0.006735, Train CE:0.012184, Train KL:8.732705, Val MSE:0.010457, Val CE:0.043426, Train ACC:1.000000, Val ACC:0.993750

Epoch 1740/4000: 100%|██████████| 1/1 [00:00<00:00, 21.44it/s]

Learning rate updated: 3.564793225056019e-05
epoch: 1739, beta = 0.000097, Train MSE: 0.006737, Train CE:0.012182, Train KL:8.732858, Val MSE:0.010450, Val CE:0.043590, Train ACC:1.000000, Val ACC:0.993750

Epoch 1741/4000: 100%|██████████| 1/1 [00:00<00:00, 28.45it/s]

epoch: 1740, beta = 0.000097, Train MSE: 0.006737, Train CE:0.012179, Train KL:8.733013, Val MSE:0.010457, Val CE:0.043490, Train ACC:1.000000, Val ACC:0.993750

Epoch 1742/4000: 100%|██████████| 1/1 [00:00<00:00, 24.37it/s]

epoch: 1741, beta = 0.000097, Train MSE: 0.006740, Train CE:0.012173, Train KL:8.733165, Val MSE:0.010429, Val CE:0.043352, Train ACC:1.000000, Val ACC:0.993750

Epoch 1743/4000: 100%|██████████| 1/1 [00:00<00:00, 23.11it/s]

epoch: 1742, beta = 0.000097, Train MSE: 0.006745, Train CE:0.012177, Train KL:8.733321, Val MSE:0.010445, Val CE:0.043533, Train ACC:1.000000, Val ACC:0.993750

Epoch 1744/4000: 100%|██████████| 1/1 [00:00<00:00, 24.08it/s]

epoch: 1743, beta = 0.000097, Train MSE: 0.006724, Train CE:0.012174, Train KL:8.733482, Val MSE:0.010417, Val CE:0.043493, Train ACC:1.000000, Val ACC:0.993750

Epoch 1745/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 1744, beta = 0.000097, Train MSE: 0.006743, Train CE:0.012170, Train KL:8.733648, Val MSE:0.010448, Val CE:0.043476, Train ACC:1.000000, Val ACC:0.993750

Epoch 1746/4000: 100%|██████████| 1/1 [00:00<00:00, 21.26it/s]

epoch: 1745, beta = 0.000097, Train MSE: 0.006734, Train CE:0.012170, Train KL:8.733812, Val MSE:0.010442, Val CE:0.043395, Train ACC:1.000000, Val ACC:0.993750

Epoch 1747/4000: 100%|██████████| 1/1 [00:00<00:00, 24.39it/s]

epoch: 1746, beta = 0.000097, Train MSE: 0.006740, Train CE:0.012167, Train KL:8.733971, Val MSE:0.010449, Val CE:0.043752, Train ACC:1.000000, Val ACC:0.993750

Epoch 1748/4000: 100%|██████████| 1/1 [00:00<00:00, 25.70it/s]

epoch: 1747, beta = 0.000097, Train MSE: 0.006733, Train CE:0.012166, Train KL:8.734127, Val MSE:0.010406, Val CE:0.043637, Train ACC:1.000000, Val ACC:0.993750

Epoch 1749/4000: 100%|██████████| 1/1 [00:00<00:00, 25.88it/s]

epoch: 1748, beta = 0.000097, Train MSE: 0.006737, Train CE:0.012162, Train KL:8.734282, Val MSE:0.010446, Val CE:0.043678, Train ACC:1.000000, Val ACC:0.993750

Epoch 1750/4000: 100%|██████████| 1/1 [00:00<00:00, 21.82it/s]

epoch: 1749, beta = 0.000097, Train MSE: 0.006730, Train CE:0.012156, Train KL:8.734437, Val MSE:0.010426, Val CE:0.043545, Train ACC:1.000000, Val ACC:0.993750

Epoch 1751/4000: 100%|██████████| 1/1 [00:00<00:00, 24.18it/s]

Learning rate updated: 3.3865535638032174e-05
epoch: 1750, beta = 0.000097, Train MSE: 0.006732, Train CE:0.012161, Train KL:8.734593, Val MSE:0.010432, Val CE:0.043736, Train ACC:1.000000, Val ACC:0.993750

Epoch 1752/4000: 100%|██████████| 1/1 [00:00<00:00, 18.94it/s]

epoch: 1751, beta = 0.000097, Train MSE: 0.006743, Train CE:0.012153, Train KL:8.734751, Val MSE:0.010435, Val CE:0.043669, Train ACC:1.000000, Val ACC:0.993750

Epoch 1753/4000: 100%|██████████| 1/1 [00:00<00:00, 22.28it/s]

epoch: 1752, beta = 0.000097, Train MSE: 0.006728, Train CE:0.012149, Train KL:8.734898, Val MSE:0.010441, Val CE:0.043701, Train ACC:1.000000, Val ACC:0.993750

Epoch 1754/4000: 100%|██████████| 1/1 [00:00<00:00, 22.32it/s]

epoch: 1753, beta = 0.000097, Train MSE: 0.006733, Train CE:0.012150, Train KL:8.735044, Val MSE:0.010444, Val CE:0.043244, Train ACC:1.000000, Val ACC:0.993750

Epoch 1755/4000: 100%|██████████| 1/1 [00:00<00:00, 23.96it/s]

epoch: 1754, beta = 0.000097, Train MSE: 0.006726, Train CE:0.012150, Train KL:8.735182, Val MSE:0.010471, Val CE:0.043651, Train ACC:1.000000, Val ACC:0.993750

Epoch 1756/4000: 100%|██████████| 1/1 [00:00<00:00, 22.41it/s]

epoch: 1755, beta = 0.000097, Train MSE: 0.006719, Train CE:0.012141, Train KL:8.735322, Val MSE:0.010427, Val CE:0.043457, Train ACC:1.000000, Val ACC:0.993750

Epoch 1757/4000: 100%|██████████| 1/1 [00:00<00:00, 24.20it/s]

epoch: 1756, beta = 0.000097, Train MSE: 0.006738, Train CE:0.012136, Train KL:8.735456, Val MSE:0.010409, Val CE:0.043607, Train ACC:1.000000, Val ACC:0.993750

Epoch 1758/4000: 100%|██████████| 1/1 [00:00<00:00, 24.24it/s]

epoch: 1757, beta = 0.000097, Train MSE: 0.006734, Train CE:0.012136, Train KL:8.735594, Val MSE:0.010436, Val CE:0.043783, Train ACC:1.000000, Val ACC:0.993750

Epoch 1759/4000: 100%|██████████| 1/1 [00:00<00:00, 24.02it/s]

epoch: 1758, beta = 0.000097, Train MSE: 0.006730, Train CE:0.012138, Train KL:8.735729, Val MSE:0.010430, Val CE:0.043570, Train ACC:1.000000, Val ACC:0.993750

Epoch 1760/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 1759, beta = 0.000097, Train MSE: 0.006729, Train CE:0.012141, Train KL:8.735864, Val MSE:0.010427, Val CE:0.043804, Train ACC:1.000000, Val ACC:0.993750

Epoch 1761/4000: 100%|██████████| 1/1 [00:00<00:00, 24.32it/s]

epoch: 1760, beta = 0.000097, Train MSE: 0.006730, Train CE:0.012132, Train KL:8.736001, Val MSE:0.010415, Val CE:0.043521, Train ACC:1.000000, Val ACC:0.993750

Epoch 1762/4000: 100%|██████████| 1/1 [00:00<00:00, 25.11it/s]

Learning rate updated: 3.2172258856130564e-05
epoch: 1761, beta = 0.000097, Train MSE: 0.006720, Train CE:0.012132, Train KL:8.736142, Val MSE:0.010422, Val CE:0.043813, Train ACC:1.000000, Val ACC:0.993750

Epoch 1763/4000: 100%|██████████| 1/1 [00:00<00:00, 24.19it/s]

epoch: 1762, beta = 0.000097, Train MSE: 0.006729, Train CE:0.012130, Train KL:8.736282, Val MSE:0.010449, Val CE:0.043660, Train ACC:1.000000, Val ACC:0.993750

Epoch 1764/4000: 100%|██████████| 1/1 [00:00<00:00, 23.35it/s]

epoch: 1763, beta = 0.000097, Train MSE: 0.006717, Train CE:0.012128, Train KL:8.736410, Val MSE:0.010402, Val CE:0.043589, Train ACC:1.000000, Val ACC:0.993750

Epoch 1765/4000: 100%|██████████| 1/1 [00:00<00:00, 23.60it/s]

epoch: 1764, beta = 0.000097, Train MSE: 0.006714, Train CE:0.012125, Train KL:8.736526, Val MSE:0.010430, Val CE:0.043616, Train ACC:1.000000, Val ACC:0.993750

Epoch 1766/4000: 100%|██████████| 1/1 [00:00<00:00, 23.69it/s]

epoch: 1765, beta = 0.000097, Train MSE: 0.006728, Train CE:0.012126, Train KL:8.736638, Val MSE:0.010422, Val CE:0.043441, Train ACC:1.000000, Val ACC:0.993750

Epoch 1767/4000: 100%|██████████| 1/1 [00:00<00:00, 24.74it/s]

epoch: 1766, beta = 0.000097, Train MSE: 0.006721, Train CE:0.012127, Train KL:8.736767, Val MSE:0.010413, Val CE:0.043559, Train ACC:1.000000, Val ACC:0.993750

Epoch 1768/4000: 100%|██████████| 1/1 [00:00<00:00, 24.05it/s]

epoch: 1767, beta = 0.000097, Train MSE: 0.006732, Train CE:0.012119, Train KL:8.736901, Val MSE:0.010399, Val CE:0.043401, Train ACC:1.000000, Val ACC:0.993750

Epoch 1769/4000: 100%|██████████| 1/1 [00:00<00:00, 24.59it/s]

epoch: 1768, beta = 0.000097, Train MSE: 0.006728, Train CE:0.012122, Train KL:8.737041, Val MSE:0.010420, Val CE:0.043675, Train ACC:1.000000, Val ACC:0.993750

Epoch 1770/4000: 100%|██████████| 1/1 [00:00<00:00, 22.15it/s]

epoch: 1769, beta = 0.000097, Train MSE: 0.006727, Train CE:0.012116, Train KL:8.737179, Val MSE:0.010421, Val CE:0.043459, Train ACC:1.000000, Val ACC:0.993750

Epoch 1771/4000: 100%|██████████| 1/1 [00:00<00:00, 24.10it/s]

epoch: 1770, beta = 0.000097, Train MSE: 0.006728, Train CE:0.012110, Train KL:8.737316, Val MSE:0.010403, Val CE:0.043454, Train ACC:1.000000, Val ACC:0.993750

Epoch 1772/4000: 100%|██████████| 1/1 [00:00<00:00, 23.13it/s]

epoch: 1771, beta = 0.000097, Train MSE: 0.006724, Train CE:0.012115, Train KL:8.737454, Val MSE:0.010421, Val CE:0.043449, Train ACC:1.000000, Val ACC:0.993750

Epoch 1773/4000: 100%|██████████| 1/1 [00:00<00:00, 20.49it/s]

Learning rate updated: 3.056364591332403e-05
epoch: 1772, beta = 0.000097, Train MSE: 0.006725, Train CE:0.012109, Train KL:8.737589, Val MSE:0.010423, Val CE:0.043437, Train ACC:1.000000, Val ACC:0.993750

Epoch 1774/4000: 100%|██████████| 1/1 [00:00<00:00, 23.85it/s]

epoch: 1773, beta = 0.000097, Train MSE: 0.006720, Train CE:0.012106, Train KL:8.737720, Val MSE:0.010426, Val CE:0.043268, Train ACC:1.000000, Val ACC:0.993750

Epoch 1775/4000: 100%|██████████| 1/1 [00:00<00:00, 22.59it/s]

epoch: 1774, beta = 0.000097, Train MSE: 0.006735, Train CE:0.012105, Train KL:8.737838, Val MSE:0.010419, Val CE:0.043489, Train ACC:1.000000, Val ACC:0.993750

Epoch 1776/4000: 100%|██████████| 1/1 [00:00<00:00, 24.10it/s]

epoch: 1775, beta = 0.000097, Train MSE: 0.006725, Train CE:0.012118, Train KL:8.737967, Val MSE:0.010411, Val CE:0.043248, Train ACC:1.000000, Val ACC:0.993750

Epoch 1777/4000: 100%|██████████| 1/1 [00:00<00:00, 23.90it/s]

epoch: 1776, beta = 0.000097, Train MSE: 0.006722, Train CE:0.012099, Train KL:8.738111, Val MSE:0.010433, Val CE:0.043359, Train ACC:1.000000, Val ACC:0.993750

Epoch 1778/4000: 100%|██████████| 1/1 [00:00<00:00, 24.09it/s]

epoch: 1777, beta = 0.000097, Train MSE: 0.006729, Train CE:0.012099, Train KL:8.738261, Val MSE:0.010423, Val CE:0.043543, Train ACC:1.000000, Val ACC:0.993750

Epoch 1779/4000: 100%|██████████| 1/1 [00:00<00:00, 22.83it/s]

epoch: 1778, beta = 0.000097, Train MSE: 0.006725, Train CE:0.012098, Train KL:8.738425, Val MSE:0.010396, Val CE:0.043654, Train ACC:1.000000, Val ACC:0.993750

Epoch 1780/4000: 100%|██████████| 1/1 [00:00<00:00, 24.02it/s]

epoch: 1779, beta = 0.000097, Train MSE: 0.006718, Train CE:0.012095, Train KL:8.738583, Val MSE:0.010442, Val CE:0.043748, Train ACC:1.000000, Val ACC:0.993750

Epoch 1781/4000: 100%|██████████| 1/1 [00:00<00:00, 22.86it/s]

epoch: 1780, beta = 0.000097, Train MSE: 0.006716, Train CE:0.012096, Train KL:8.738721, Val MSE:0.010388, Val CE:0.043643, Train ACC:1.000000, Val ACC:0.993750

Epoch 1782/4000: 100%|██████████| 1/1 [00:00<00:00, 23.09it/s]

epoch: 1781, beta = 0.000097, Train MSE: 0.006723, Train CE:0.012093, Train KL:8.738855, Val MSE:0.010417, Val CE:0.043794, Train ACC:1.000000, Val ACC:0.993750

Epoch 1783/4000: 100%|██████████| 1/1 [00:00<00:00, 21.55it/s]

epoch: 1782, beta = 0.000097, Train MSE: 0.006715, Train CE:0.012088, Train KL:8.738988, Val MSE:0.010416, Val CE:0.043772, Train ACC:1.000000, Val ACC:0.993750

Epoch 1784/4000: 100%|██████████| 1/1 [00:00<00:00, 22.82it/s]

Learning rate updated: 2.903546361765783e-05
epoch: 1783, beta = 0.000097, Train MSE: 0.006712, Train CE:0.012087, Train KL:8.739120, Val MSE:0.010386, Val CE:0.043682, Train ACC:1.000000, Val ACC:0.993750

Epoch 1785/4000: 100%|██████████| 1/1 [00:00<00:00, 24.29it/s]

epoch: 1784, beta = 0.000097, Train MSE: 0.006712, Train CE:0.012095, Train KL:8.739255, Val MSE:0.010411, Val CE:0.043451, Train ACC:1.000000, Val ACC:0.993750

Epoch 1786/4000: 100%|██████████| 1/1 [00:00<00:00, 22.80it/s]

epoch: 1785, beta = 0.000097, Train MSE: 0.006714, Train CE:0.012082, Train KL:8.739385, Val MSE:0.010359, Val CE:0.043470, Train ACC:1.000000, Val ACC:0.993750

Epoch 1787/4000: 100%|██████████| 1/1 [00:00<00:00, 23.76it/s]

epoch: 1786, beta = 0.000097, Train MSE: 0.006724, Train CE:0.012079, Train KL:8.739514, Val MSE:0.010402, Val CE:0.043314, Train ACC:1.000000, Val ACC:0.993750

Epoch 1788/4000: 100%|██████████| 1/1 [00:00<00:00, 27.34it/s]

epoch: 1787, beta = 0.000097, Train MSE: 0.006719, Train CE:0.012081, Train KL:8.739651, Val MSE:0.010404, Val CE:0.043498, Train ACC:1.000000, Val ACC:0.993750

Epoch 1789/4000: 100%|██████████| 1/1 [00:00<00:00, 23.68it/s]

epoch: 1788, beta = 0.000097, Train MSE: 0.006724, Train CE:0.012078, Train KL:8.739788, Val MSE:0.010404, Val CE:0.043492, Train ACC:1.000000, Val ACC:0.993750

Epoch 1790/4000: 100%|██████████| 1/1 [00:00<00:00, 24.22it/s]

epoch: 1789, beta = 0.000097, Train MSE: 0.006708, Train CE:0.012071, Train KL:8.739931, Val MSE:0.010435, Val CE:0.043753, Train ACC:1.000000, Val ACC:0.993750

Epoch 1791/4000: 100%|██████████| 1/1 [00:00<00:00, 24.05it/s]

epoch: 1790, beta = 0.000097, Train MSE: 0.006709, Train CE:0.012075, Train KL:8.740069, Val MSE:0.010435, Val CE:0.043566, Train ACC:1.000000, Val ACC:0.993750

Epoch 1792/4000: 100%|██████████| 1/1 [00:00<00:00, 22.83it/s]

epoch: 1791, beta = 0.000097, Train MSE: 0.006706, Train CE:0.012072, Train KL:8.740201, Val MSE:0.010425, Val CE:0.043686, Train ACC:1.000000, Val ACC:0.993750

Epoch 1793/4000: 100%|██████████| 1/1 [00:00<00:00, 23.34it/s]

epoch: 1792, beta = 0.000097, Train MSE: 0.006721, Train CE:0.012070, Train KL:8.740326, Val MSE:0.010391, Val CE:0.043726, Train ACC:1.000000, Val ACC:0.993750

Epoch 1794/4000: 100%|██████████| 1/1 [00:00<00:00, 21.23it/s]

epoch: 1793, beta = 0.000097, Train MSE: 0.006718, Train CE:0.012070, Train KL:8.740441, Val MSE:0.010369, Val CE:0.043627, Train ACC:1.000000, Val ACC:0.993750

Epoch 1795/4000: 100%|██████████| 1/1 [00:00<00:00, 19.97it/s]

Learning rate updated: 2.758369043677494e-05
epoch: 1794, beta = 0.000097, Train MSE: 0.006715, Train CE:0.012074, Train KL:8.740554, Val MSE:0.010395, Val CE:0.043452, Train ACC:1.000000, Val ACC:0.993750

Epoch 1796/4000: 100%|██████████| 1/1 [00:00<00:00, 22.96it/s]

epoch: 1795, beta = 0.000097, Train MSE: 0.006706, Train CE:0.012061, Train KL:8.740674, Val MSE:0.010374, Val CE:0.043475, Train ACC:1.000000, Val ACC:0.993750

Epoch 1797/4000: 100%|██████████| 1/1 [00:00<00:00, 24.41it/s]

epoch: 1796, beta = 0.000097, Train MSE: 0.006707, Train CE:0.012065, Train KL:8.740792, Val MSE:0.010412, Val CE:0.043512, Train ACC:1.000000, Val ACC:0.993750

Epoch 1798/4000: 100%|██████████| 1/1 [00:00<00:00, 25.59it/s]

epoch: 1797, beta = 0.000097, Train MSE: 0.006705, Train CE:0.012063, Train KL:8.740923, Val MSE:0.010414, Val CE:0.043788, Train ACC:1.000000, Val ACC:0.993750

Epoch 1799/4000: 100%|██████████| 1/1 [00:00<00:00, 23.94it/s]

epoch: 1798, beta = 0.000097, Train MSE: 0.006709, Train CE:0.012059, Train KL:8.741059, Val MSE:0.010389, Val CE:0.043556, Train ACC:1.000000, Val ACC:0.993750

Epoch 1800/4000: 100%|██████████| 1/1 [00:00<00:00, 27.13it/s]

epoch: 1799, beta = 0.000097, Train MSE: 0.006725, Train CE:0.012059, Train KL:8.741189, Val MSE:0.010396, Val CE:0.043742, Train ACC:1.000000, Val ACC:0.993750

Epoch 1801/4000: 100%|██████████| 1/1 [00:00<00:00, 27.27it/s]

epoch: 1800, beta = 0.000097, Train MSE: 0.006708, Train CE:0.012056, Train KL:8.741321, Val MSE:0.010402, Val CE:0.043445, Train ACC:1.000000, Val ACC:0.993750

Epoch 1802/4000: 100%|██████████| 1/1 [00:00<00:00, 23.80it/s]

epoch: 1801, beta = 0.000097, Train MSE: 0.006706, Train CE:0.012053, Train KL:8.741448, Val MSE:0.010402, Val CE:0.043693, Train ACC:1.000000, Val ACC:0.993750

Epoch 1803/4000: 100%|██████████| 1/1 [00:00<00:00, 24.69it/s]

epoch: 1802, beta = 0.000097, Train MSE: 0.006710, Train CE:0.012051, Train KL:8.741573, Val MSE:0.010403, Val CE:0.043477, Train ACC:1.000000, Val ACC:0.993750

Epoch 1804/4000: 100%|██████████| 1/1 [00:00<00:00, 23.31it/s]

epoch: 1803, beta = 0.000097, Train MSE: 0.006712, Train CE:0.012051, Train KL:8.741682, Val MSE:0.010407, Val CE:0.043734, Train ACC:1.000000, Val ACC:0.993750

Epoch 1805/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 1804, beta = 0.000097, Train MSE: 0.006714, Train CE:0.012050, Train KL:8.741783, Val MSE:0.010413, Val CE:0.043719, Train ACC:1.000000, Val ACC:0.993750

Epoch 1806/4000: 100%|██████████| 1/1 [00:00<00:00, 23.93it/s]

Learning rate updated: 2.620450591493619e-05
epoch: 1805, beta = 0.000097, Train MSE: 0.006701, Train CE:0.012042, Train KL:8.741888, Val MSE:0.010418, Val CE:0.043661, Train ACC:1.000000, Val ACC:0.993750

Epoch 1807/4000: 100%|██████████| 1/1 [00:00<00:00, 24.11it/s]

epoch: 1806, beta = 0.000097, Train MSE: 0.006708, Train CE:0.012042, Train KL:8.741991, Val MSE:0.010407, Val CE:0.043332, Train ACC:1.000000, Val ACC:0.993750

Epoch 1808/4000: 100%|██████████| 1/1 [00:00<00:00, 24.97it/s]

epoch: 1807, beta = 0.000097, Train MSE: 0.006709, Train CE:0.012044, Train KL:8.742100, Val MSE:0.010393, Val CE:0.043463, Train ACC:1.000000, Val ACC:0.993750

Epoch 1809/4000: 100%|██████████| 1/1 [00:00<00:00, 23.90it/s]

epoch: 1808, beta = 0.000097, Train MSE: 0.006707, Train CE:0.012041, Train KL:8.742215, Val MSE:0.010405, Val CE:0.043339, Train ACC:1.000000, Val ACC:0.993750

Epoch 1810/4000: 100%|██████████| 1/1 [00:00<00:00, 24.57it/s]

epoch: 1809, beta = 0.000097, Train MSE: 0.006711, Train CE:0.012038, Train KL:8.742337, Val MSE:0.010415, Val CE:0.043635, Train ACC:1.000000, Val ACC:0.993750

Epoch 1811/4000: 100%|██████████| 1/1 [00:00<00:00, 23.04it/s]

epoch: 1810, beta = 0.000097, Train MSE: 0.006705, Train CE:0.012040, Train KL:8.742464, Val MSE:0.010389, Val CE:0.043340, Train ACC:1.000000, Val ACC:0.993750

Epoch 1812/4000: 100%|██████████| 1/1 [00:00<00:00, 26.02it/s]

epoch: 1811, beta = 0.000097, Train MSE: 0.006710, Train CE:0.012034, Train KL:8.742585, Val MSE:0.010398, Val CE:0.043718, Train ACC:1.000000, Val ACC:0.993750

Epoch 1813/4000: 100%|██████████| 1/1 [00:00<00:00, 24.73it/s]

epoch: 1812, beta = 0.000097, Train MSE: 0.006710, Train CE:0.012031, Train KL:8.742710, Val MSE:0.010384, Val CE:0.043524, Train ACC:1.000000, Val ACC:0.993750

Epoch 1814/4000: 100%|██████████| 1/1 [00:00<00:00, 23.68it/s]

epoch: 1813, beta = 0.000097, Train MSE: 0.006702, Train CE:0.012034, Train KL:8.742836, Val MSE:0.010414, Val CE:0.043547, Train ACC:1.000000, Val ACC:0.993750

Epoch 1815/4000: 100%|██████████| 1/1 [00:00<00:00, 20.16it/s]

epoch: 1814, beta = 0.000097, Train MSE: 0.006706, Train CE:0.012036, Train KL:8.742962, Val MSE:0.010385, Val CE:0.043707, Train ACC:1.000000, Val ACC:0.993750

Epoch 1816/4000: 100%|██████████| 1/1 [00:00<00:00, 23.86it/s]

epoch: 1815, beta = 0.000097, Train MSE: 0.006702, Train CE:0.012032, Train KL:8.743084, Val MSE:0.010421, Val CE:0.043735, Train ACC:1.000000, Val ACC:0.993750

Epoch 1817/4000: 100%|██████████| 1/1 [00:00<00:00, 23.91it/s]

Learning rate updated: 2.489428061918938e-05
epoch: 1816, beta = 0.000097, Train MSE: 0.006713, Train CE:0.012029, Train KL:8.743204, Val MSE:0.010400, Val CE:0.043355, Train ACC:1.000000, Val ACC:0.993750

Epoch 1818/4000: 100%|██████████| 1/1 [00:00<00:00, 27.93it/s]

epoch: 1817, beta = 0.000097, Train MSE: 0.006700, Train CE:0.012025, Train KL:8.743322, Val MSE:0.010413, Val CE:0.043562, Train ACC:1.000000, Val ACC:0.993750

Epoch 1819/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 1818, beta = 0.000097, Train MSE: 0.006707, Train CE:0.012023, Train KL:8.743439, Val MSE:0.010386, Val CE:0.043291, Train ACC:1.000000, Val ACC:0.993750

Epoch 1820/4000: 100%|██████████| 1/1 [00:00<00:00, 24.18it/s]

epoch: 1819, beta = 0.000097, Train MSE: 0.006703, Train CE:0.012019, Train KL:8.743550, Val MSE:0.010351, Val CE:0.043536, Train ACC:1.000000, Val ACC:0.993750

Epoch 1821/4000: 100%|██████████| 1/1 [00:00<00:00, 24.61it/s]

epoch: 1820, beta = 0.000097, Train MSE: 0.006700, Train CE:0.012024, Train KL:8.743664, Val MSE:0.010390, Val CE:0.043376, Train ACC:1.000000, Val ACC:0.993750

Epoch 1822/4000: 100%|██████████| 1/1 [00:00<00:00, 25.93it/s]

epoch: 1821, beta = 0.000097, Train MSE: 0.006704, Train CE:0.012018, Train KL:8.743783, Val MSE:0.010395, Val CE:0.043462, Train ACC:1.000000, Val ACC:0.993750

Epoch 1823/4000: 100%|██████████| 1/1 [00:00<00:00, 23.52it/s]

epoch: 1822, beta = 0.000097, Train MSE: 0.006692, Train CE:0.012020, Train KL:8.743910, Val MSE:0.010395, Val CE:0.043505, Train ACC:1.000000, Val ACC:0.993750

Epoch 1824/4000: 100%|██████████| 1/1 [00:00<00:00, 23.98it/s]

epoch: 1823, beta = 0.000097, Train MSE: 0.006702, Train CE:0.012015, Train KL:8.744039, Val MSE:0.010388, Val CE:0.043525, Train ACC:1.000000, Val ACC:0.993750

Epoch 1825/4000: 100%|██████████| 1/1 [00:00<00:00, 24.33it/s]

epoch: 1824, beta = 0.000097, Train MSE: 0.006703, Train CE:0.012020, Train KL:8.744161, Val MSE:0.010431, Val CE:0.043496, Train ACC:1.000000, Val ACC:0.993750

Epoch 1826/4000: 100%|██████████| 1/1 [00:00<00:00, 25.34it/s]

epoch: 1825, beta = 0.000097, Train MSE: 0.006694, Train CE:0.012019, Train KL:8.744283, Val MSE:0.010401, Val CE:0.043431, Train ACC:1.000000, Val ACC:0.993750

Epoch 1827/4000: 100%|██████████| 1/1 [00:00<00:00, 24.05it/s]

epoch: 1826, beta = 0.000097, Train MSE: 0.006707, Train CE:0.012008, Train KL:8.744394, Val MSE:0.010383, Val CE:0.043495, Train ACC:1.000000, Val ACC:0.993750

Epoch 1828/4000: 100%|██████████| 1/1 [00:00<00:00, 26.30it/s]

Learning rate updated: 2.364956658822991e-05
epoch: 1827, beta = 0.000097, Train MSE: 0.006696, Train CE:0.012003, Train KL:8.744500, Val MSE:0.010382, Val CE:0.043270, Train ACC:1.000000, Val ACC:0.993750

Epoch 1829/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 1828, beta = 0.000097, Train MSE: 0.006698, Train CE:0.012011, Train KL:8.744599, Val MSE:0.010387, Val CE:0.043531, Train ACC:1.000000, Val ACC:0.993750

Epoch 1830/4000: 100%|██████████| 1/1 [00:00<00:00, 23.96it/s]

epoch: 1829, beta = 0.000097, Train MSE: 0.006695, Train CE:0.012003, Train KL:8.744700, Val MSE:0.010401, Val CE:0.043539, Train ACC:1.000000, Val ACC:0.993750

Epoch 1831/4000: 100%|██████████| 1/1 [00:00<00:00, 23.36it/s]

epoch: 1830, beta = 0.000097, Train MSE: 0.006694, Train CE:0.012005, Train KL:8.744807, Val MSE:0.010378, Val CE:0.043266, Train ACC:1.000000, Val ACC:0.993750

Epoch 1832/4000: 100%|██████████| 1/1 [00:00<00:00, 24.26it/s]

epoch: 1831, beta = 0.000097, Train MSE: 0.006701, Train CE:0.012006, Train KL:8.744919, Val MSE:0.010386, Val CE:0.043611, Train ACC:1.000000, Val ACC:0.993750

Epoch 1833/4000: 100%|██████████| 1/1 [00:00<00:00, 24.60it/s]

epoch: 1832, beta = 0.000097, Train MSE: 0.006690, Train CE:0.011999, Train KL:8.745040, Val MSE:0.010383, Val CE:0.043497, Train ACC:1.000000, Val ACC:0.993750

Epoch 1834/4000: 100%|██████████| 1/1 [00:00<00:00, 24.01it/s]

epoch: 1833, beta = 0.000097, Train MSE: 0.006700, Train CE:0.011996, Train KL:8.745160, Val MSE:0.010405, Val CE:0.043604, Train ACC:1.000000, Val ACC:0.993750

Epoch 1835/4000: 100%|██████████| 1/1 [00:00<00:00, 22.35it/s]

epoch: 1834, beta = 0.000097, Train MSE: 0.006691, Train CE:0.011996, Train KL:8.745280, Val MSE:0.010409, Val CE:0.043615, Train ACC:1.000000, Val ACC:0.993750

Epoch 1836/4000: 100%|██████████| 1/1 [00:00<00:00, 18.23it/s]

epoch: 1835, beta = 0.000097, Train MSE: 0.006692, Train CE:0.011994, Train KL:8.745388, Val MSE:0.010385, Val CE:0.043702, Train ACC:1.000000, Val ACC:0.993750

Epoch 1837/4000: 100%|██████████| 1/1 [00:00<00:00, 23.57it/s]

epoch: 1836, beta = 0.000097, Train MSE: 0.006685, Train CE:0.011999, Train KL:8.745483, Val MSE:0.010400, Val CE:0.043538, Train ACC:1.000000, Val ACC:0.993750

Epoch 1838/4000: 100%|██████████| 1/1 [00:00<00:00, 22.29it/s]

epoch: 1837, beta = 0.000097, Train MSE: 0.006692, Train CE:0.011989, Train KL:8.745569, Val MSE:0.010401, Val CE:0.043509, Train ACC:1.000000, Val ACC:0.993750

Epoch 1839/4000: 100%|██████████| 1/1 [00:00<00:00, 23.73it/s]

Learning rate updated: 2.2467088258818413e-05
epoch: 1838, beta = 0.000097, Train MSE: 0.006692, Train CE:0.011987, Train KL:8.745655, Val MSE:0.010378, Val CE:0.043377, Train ACC:1.000000, Val ACC:0.993750

Epoch 1840/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 1839, beta = 0.000097, Train MSE: 0.006691, Train CE:0.011991, Train KL:8.745741, Val MSE:0.010380, Val CE:0.043487, Train ACC:1.000000, Val ACC:0.993750

Epoch 1841/4000: 100%|██████████| 1/1 [00:00<00:00, 23.34it/s]

epoch: 1840, beta = 0.000097, Train MSE: 0.006698, Train CE:0.011989, Train KL:8.745824, Val MSE:0.010385, Val CE:0.043524, Train ACC:1.000000, Val ACC:0.993750

Epoch 1842/4000: 100%|██████████| 1/1 [00:00<00:00, 22.85it/s]

epoch: 1841, beta = 0.000097, Train MSE: 0.006700, Train CE:0.011987, Train KL:8.745916, Val MSE:0.010376, Val CE:0.043557, Train ACC:1.000000, Val ACC:0.993750

Epoch 1843/4000: 100%|██████████| 1/1 [00:00<00:00, 23.33it/s]

epoch: 1842, beta = 0.000097, Train MSE: 0.006695, Train CE:0.011986, Train KL:8.746016, Val MSE:0.010385, Val CE:0.043589, Train ACC:1.000000, Val ACC:0.993750

Epoch 1844/4000: 100%|██████████| 1/1 [00:00<00:00, 22.30it/s]

epoch: 1843, beta = 0.000097, Train MSE: 0.006691, Train CE:0.011987, Train KL:8.746111, Val MSE:0.010398, Val CE:0.043507, Train ACC:1.000000, Val ACC:0.993750

Epoch 1845/4000: 100%|██████████| 1/1 [00:00<00:00, 23.17it/s]

epoch: 1844, beta = 0.000097, Train MSE: 0.006697, Train CE:0.011978, Train KL:8.746201, Val MSE:0.010368, Val CE:0.043476, Train ACC:1.000000, Val ACC:0.993750

Epoch 1846/4000: 100%|██████████| 1/1 [00:00<00:00, 23.75it/s]

epoch: 1845, beta = 0.000097, Train MSE: 0.006687, Train CE:0.011980, Train KL:8.746288, Val MSE:0.010399, Val CE:0.043410, Train ACC:1.000000, Val ACC:0.993750

Epoch 1847/4000: 100%|██████████| 1/1 [00:00<00:00, 24.52it/s]

epoch: 1846, beta = 0.000097, Train MSE: 0.006689, Train CE:0.011980, Train KL:8.746381, Val MSE:0.010401, Val CE:0.043552, Train ACC:1.000000, Val ACC:0.993750

Epoch 1848/4000: 100%|██████████| 1/1 [00:00<00:00, 24.09it/s]

epoch: 1847, beta = 0.000097, Train MSE: 0.006688, Train CE:0.011977, Train KL:8.746473, Val MSE:0.010373, Val CE:0.043857, Train ACC:1.000000, Val ACC:0.993750

Epoch 1849/4000: 100%|██████████| 1/1 [00:00<00:00, 23.99it/s]

epoch: 1848, beta = 0.000097, Train MSE: 0.006697, Train CE:0.011975, Train KL:8.746568, Val MSE:0.010399, Val CE:0.043539, Train ACC:1.000000, Val ACC:0.993750

Epoch 1850/4000: 100%|██████████| 1/1 [00:00<00:00, 24.17it/s]

Learning rate updated: 2.134373384587749e-05
epoch: 1849, beta = 0.000097, Train MSE: 0.006699, Train CE:0.011978, Train KL:8.746659, Val MSE:0.010375, Val CE:0.043721, Train ACC:1.000000, Val ACC:0.993229

Epoch 1851/4000: 100%|██████████| 1/1 [00:00<00:00, 24.01it/s]

epoch: 1850, beta = 0.000097, Train MSE: 0.006691, Train CE:0.011976, Train KL:8.746754, Val MSE:0.010364, Val CE:0.043529, Train ACC:1.000000, Val ACC:0.993750

Epoch 1852/4000: 100%|██████████| 1/1 [00:00<00:00, 24.02it/s]

epoch: 1851, beta = 0.000097, Train MSE: 0.006693, Train CE:0.011970, Train KL:8.746849, Val MSE:0.010389, Val CE:0.043642, Train ACC:1.000000, Val ACC:0.993229

Epoch 1853/4000: 100%|██████████| 1/1 [00:00<00:00, 23.99it/s]

epoch: 1852, beta = 0.000097, Train MSE: 0.006688, Train CE:0.011970, Train KL:8.746944, Val MSE:0.010374, Val CE:0.043558, Train ACC:1.000000, Val ACC:0.993750

Epoch 1854/4000: 100%|██████████| 1/1 [00:00<00:00, 23.89it/s]

epoch: 1853, beta = 0.000097, Train MSE: 0.006689, Train CE:0.011971, Train KL:8.747046, Val MSE:0.010366, Val CE:0.043545, Train ACC:1.000000, Val ACC:0.993750

Epoch 1855/4000: 100%|██████████| 1/1 [00:00<00:00, 21.48it/s]

epoch: 1854, beta = 0.000097, Train MSE: 0.006685, Train CE:0.011968, Train KL:8.747149, Val MSE:0.010362, Val CE:0.043673, Train ACC:1.000000, Val ACC:0.993750

Epoch 1856/4000: 100%|██████████| 1/1 [00:00<00:00, 24.05it/s]

epoch: 1855, beta = 0.000097, Train MSE: 0.006687, Train CE:0.011962, Train KL:8.747254, Val MSE:0.010393, Val CE:0.043557, Train ACC:1.000000, Val ACC:0.993750

Epoch 1857/4000: 100%|██████████| 1/1 [00:00<00:00, 27.88it/s]

epoch: 1856, beta = 0.000097, Train MSE: 0.006688, Train CE:0.011962, Train KL:8.747355, Val MSE:0.010371, Val CE:0.043791, Train ACC:1.000000, Val ACC:0.993750

Epoch 1858/4000: 100%|██████████| 1/1 [00:00<00:00, 23.30it/s]

epoch: 1857, beta = 0.000097, Train MSE: 0.006688, Train CE:0.011963, Train KL:8.747452, Val MSE:0.010375, Val CE:0.043628, Train ACC:1.000000, Val ACC:0.993750

Epoch 1859/4000: 100%|██████████| 1/1 [00:00<00:00, 23.70it/s]

epoch: 1858, beta = 0.000097, Train MSE: 0.006681, Train CE:0.011965, Train KL:8.747549, Val MSE:0.010393, Val CE:0.043530, Train ACC:1.000000, Val ACC:0.993750

Epoch 1860/4000: 100%|██████████| 1/1 [00:00<00:00, 23.52it/s]

epoch: 1859, beta = 0.000097, Train MSE: 0.006692, Train CE:0.011963, Train KL:8.747638, Val MSE:0.010396, Val CE:0.043522, Train ACC:1.000000, Val ACC:0.993750

Epoch 1861/4000: 100%|██████████| 1/1 [00:00<00:00, 21.44it/s]

Learning rate updated: 2.0276547153583614e-05
epoch: 1860, beta = 0.000097, Train MSE: 0.006693, Train CE:0.011956, Train KL:8.747731, Val MSE:0.010381, Val CE:0.043579, Train ACC:1.000000, Val ACC:0.993750

Epoch 1862/4000: 100%|██████████| 1/1 [00:00<00:00, 23.89it/s]

epoch: 1861, beta = 0.000097, Train MSE: 0.006679, Train CE:0.011956, Train KL:8.747827, Val MSE:0.010396, Val CE:0.043530, Train ACC:1.000000, Val ACC:0.993750

Epoch 1863/4000: 100%|██████████| 1/1 [00:00<00:00, 24.13it/s]

epoch: 1862, beta = 0.000097, Train MSE: 0.006690, Train CE:0.011956, Train KL:8.747916, Val MSE:0.010358, Val CE:0.043673, Train ACC:1.000000, Val ACC:0.993750

Epoch 1864/4000: 100%|██████████| 1/1 [00:00<00:00, 23.97it/s]

epoch: 1863, beta = 0.000097, Train MSE: 0.006678, Train CE:0.011953, Train KL:8.748004, Val MSE:0.010406, Val CE:0.043555, Train ACC:1.000000, Val ACC:0.993750

Epoch 1865/4000: 100%|██████████| 1/1 [00:00<00:00, 24.19it/s]

epoch: 1864, beta = 0.000097, Train MSE: 0.006685, Train CE:0.011951, Train KL:8.748092, Val MSE:0.010383, Val CE:0.043523, Train ACC:1.000000, Val ACC:0.993750

Epoch 1866/4000: 100%|██████████| 1/1 [00:00<00:00, 20.57it/s]

epoch: 1865, beta = 0.000097, Train MSE: 0.006693, Train CE:0.011959, Train KL:8.748182, Val MSE:0.010354, Val CE:0.043511, Train ACC:1.000000, Val ACC:0.993750

Epoch 1867/4000: 100%|██████████| 1/1 [00:00<00:00, 24.04it/s]

epoch: 1866, beta = 0.000097, Train MSE: 0.006683, Train CE:0.011951, Train KL:8.748264, Val MSE:0.010358, Val CE:0.043582, Train ACC:1.000000, Val ACC:0.993750

Epoch 1868/4000: 100%|██████████| 1/1 [00:00<00:00, 24.30it/s]

epoch: 1867, beta = 0.000097, Train MSE: 0.006683, Train CE:0.011952, Train KL:8.748345, Val MSE:0.010357, Val CE:0.043556, Train ACC:1.000000, Val ACC:0.993750

Epoch 1869/4000: 100%|██████████| 1/1 [00:00<00:00, 23.98it/s]

epoch: 1868, beta = 0.000097, Train MSE: 0.006677, Train CE:0.011953, Train KL:8.748426, Val MSE:0.010371, Val CE:0.043534, Train ACC:1.000000, Val ACC:0.993750

Epoch 1870/4000: 100%|██████████| 1/1 [00:00<00:00, 24.14it/s]

epoch: 1869, beta = 0.000097, Train MSE: 0.006691, Train CE:0.011942, Train KL:8.748507, Val MSE:0.010366, Val CE:0.043616, Train ACC:1.000000, Val ACC:0.993750

Epoch 1871/4000: 100%|██████████| 1/1 [00:00<00:00, 23.76it/s]

epoch: 1870, beta = 0.000097, Train MSE: 0.006680, Train CE:0.011946, Train KL:8.748592, Val MSE:0.010381, Val CE:0.043615, Train ACC:1.000000, Val ACC:0.993750

Epoch 1872/4000: 100%|██████████| 1/1 [00:00<00:00, 23.90it/s]

Learning rate updated: 1.9262719795904432e-05
epoch: 1871, beta = 0.000097, Train MSE: 0.006682, Train CE:0.011943, Train KL:8.748681, Val MSE:0.010386, Val CE:0.043426, Train ACC:1.000000, Val ACC:0.993750

Epoch 1873/4000: 100%|██████████| 1/1 [00:00<00:00, 25.84it/s]

epoch: 1872, beta = 0.000097, Train MSE: 0.006687, Train CE:0.011940, Train KL:8.748775, Val MSE:0.010375, Val CE:0.043524, Train ACC:1.000000, Val ACC:0.993750

Epoch 1874/4000: 100%|██████████| 1/1 [00:00<00:00, 24.04it/s]

epoch: 1873, beta = 0.000097, Train MSE: 0.006679, Train CE:0.011947, Train KL:8.748861, Val MSE:0.010379, Val CE:0.043501, Train ACC:1.000000, Val ACC:0.993750

Epoch 1875/4000: 100%|██████████| 1/1 [00:00<00:00, 23.94it/s]

epoch: 1874, beta = 0.000097, Train MSE: 0.006687, Train CE:0.011940, Train KL:8.748950, Val MSE:0.010378, Val CE:0.043610, Train ACC:1.000000, Val ACC:0.993750

Epoch 1876/4000: 100%|██████████| 1/1 [00:00<00:00, 23.99it/s]

epoch: 1875, beta = 0.000097, Train MSE: 0.006689, Train CE:0.011941, Train KL:8.749038, Val MSE:0.010347, Val CE:0.043748, Train ACC:1.000000, Val ACC:0.993750

Epoch 1877/4000: 100%|██████████| 1/1 [00:00<00:00, 23.90it/s]

epoch: 1876, beta = 0.000097, Train MSE: 0.006683, Train CE:0.011943, Train KL:8.749119, Val MSE:0.010354, Val CE:0.043356, Train ACC:1.000000, Val ACC:0.993750

Epoch 1878/4000: 100%|██████████| 1/1 [00:00<00:00, 24.05it/s]

epoch: 1877, beta = 0.000097, Train MSE: 0.006679, Train CE:0.011933, Train KL:8.749200, Val MSE:0.010343, Val CE:0.043583, Train ACC:1.000000, Val ACC:0.993750

Epoch 1879/4000: 100%|██████████| 1/1 [00:00<00:00, 23.49it/s]

epoch: 1878, beta = 0.000097, Train MSE: 0.006678, Train CE:0.011934, Train KL:8.749280, Val MSE:0.010367, Val CE:0.043589, Train ACC:1.000000, Val ACC:0.993750

Epoch 1880/4000: 100%|██████████| 1/1 [00:00<00:00, 19.68it/s]

epoch: 1879, beta = 0.000097, Train MSE: 0.006677, Train CE:0.011937, Train KL:8.749366, Val MSE:0.010359, Val CE:0.043189, Train ACC:1.000000, Val ACC:0.993750

Epoch 1881/4000: 100%|██████████| 1/1 [00:00<00:00, 20.52it/s]

epoch: 1880, beta = 0.000097, Train MSE: 0.006686, Train CE:0.011934, Train KL:8.749456, Val MSE:0.010375, Val CE:0.043468, Train ACC:1.000000, Val ACC:0.993750

Epoch 1882/4000: 100%|██████████| 1/1 [00:00<00:00, 25.13it/s]

epoch: 1881, beta = 0.000097, Train MSE: 0.006675, Train CE:0.011931, Train KL:8.749546, Val MSE:0.010358, Val CE:0.043337, Train ACC:1.000000, Val ACC:0.993750

Epoch 1883/4000: 100%|██████████| 1/1 [00:00<00:00, 27.23it/s]

Learning rate updated: 1.829958380610921e-05
epoch: 1882, beta = 0.000097, Train MSE: 0.006682, Train CE:0.011932, Train KL:8.749640, Val MSE:0.010331, Val CE:0.043524, Train ACC:1.000000, Val ACC:0.993750

Epoch 1884/4000: 100%|██████████| 1/1 [00:00<00:00, 24.59it/s]

epoch: 1883, beta = 0.000097, Train MSE: 0.006678, Train CE:0.011926, Train KL:8.749734, Val MSE:0.010392, Val CE:0.043610, Train ACC:1.000000, Val ACC:0.993750

Epoch 1885/4000: 100%|██████████| 1/1 [00:00<00:00, 24.46it/s]

epoch: 1884, beta = 0.000097, Train MSE: 0.006683, Train CE:0.011930, Train KL:8.749823, Val MSE:0.010352, Val CE:0.043889, Train ACC:1.000000, Val ACC:0.993750

Epoch 1886/4000: 100%|██████████| 1/1 [00:00<00:00, 24.01it/s]

epoch: 1885, beta = 0.000097, Train MSE: 0.006688, Train CE:0.011927, Train KL:8.749907, Val MSE:0.010367, Val CE:0.043732, Train ACC:1.000000, Val ACC:0.993750

Epoch 1887/4000: 100%|██████████| 1/1 [00:00<00:00, 26.47it/s]

epoch: 1886, beta = 0.000097, Train MSE: 0.006675, Train CE:0.011925, Train KL:8.749988, Val MSE:0.010370, Val CE:0.043779, Train ACC:1.000000, Val ACC:0.993750

Epoch 1888/4000: 100%|██████████| 1/1 [00:00<00:00, 23.18it/s]

epoch: 1887, beta = 0.000097, Train MSE: 0.006675, Train CE:0.011927, Train KL:8.750063, Val MSE:0.010358, Val CE:0.043488, Train ACC:1.000000, Val ACC:0.993750

Epoch 1889/4000: 100%|██████████| 1/1 [00:00<00:00, 23.53it/s]

epoch: 1888, beta = 0.000097, Train MSE: 0.006677, Train CE:0.011920, Train KL:8.750138, Val MSE:0.010357, Val CE:0.043751, Train ACC:1.000000, Val ACC:0.993750

Epoch 1890/4000: 100%|██████████| 1/1 [00:00<00:00, 24.97it/s]

epoch: 1889, beta = 0.000097, Train MSE: 0.006670, Train CE:0.011918, Train KL:8.750211, Val MSE:0.010365, Val CE:0.043666, Train ACC:1.000000, Val ACC:0.993750

Epoch 1891/4000: 100%|██████████| 1/1 [00:00<00:00, 25.12it/s]

epoch: 1890, beta = 0.000097, Train MSE: 0.006686, Train CE:0.011917, Train KL:8.750283, Val MSE:0.010373, Val CE:0.043634, Train ACC:1.000000, Val ACC:0.993750

Epoch 1892/4000: 100%|██████████| 1/1 [00:00<00:00, 24.19it/s]

epoch: 1891, beta = 0.000097, Train MSE: 0.006683, Train CE:0.011921, Train KL:8.750361, Val MSE:0.010375, Val CE:0.043430, Train ACC:1.000000, Val ACC:0.993750

Epoch 1893/4000: 100%|██████████| 1/1 [00:00<00:00, 26.50it/s]

epoch: 1892, beta = 0.000097, Train MSE: 0.006675, Train CE:0.011914, Train KL:8.750447, Val MSE:0.010340, Val CE:0.043592, Train ACC:1.000000, Val ACC:0.993750

Epoch 1894/4000: 100%|██████████| 1/1 [00:00<00:00, 24.01it/s]

Learning rate updated: 1.738460461580375e-05
epoch: 1893, beta = 0.000097, Train MSE: 0.006680, Train CE:0.011916, Train KL:8.750538, Val MSE:0.010342, Val CE:0.043492, Train ACC:1.000000, Val ACC:0.993750

Epoch 1895/4000: 100%|██████████| 1/1 [00:00<00:00, 25.08it/s]

epoch: 1894, beta = 0.000097, Train MSE: 0.006684, Train CE:0.011915, Train KL:8.750634, Val MSE:0.010341, Val CE:0.043779, Train ACC:1.000000, Val ACC:0.993750

Epoch 1896/4000: 100%|██████████| 1/1 [00:00<00:00, 24.21it/s]

epoch: 1895, beta = 0.000097, Train MSE: 0.006678, Train CE:0.011914, Train KL:8.750728, Val MSE:0.010340, Val CE:0.043506, Train ACC:1.000000, Val ACC:0.993750

Epoch 1897/4000: 100%|██████████| 1/1 [00:00<00:00, 25.75it/s]

epoch: 1896, beta = 0.000097, Train MSE: 0.006680, Train CE:0.011909, Train KL:8.750815, Val MSE:0.010353, Val CE:0.043529, Train ACC:1.000000, Val ACC:0.993750

Epoch 1898/4000: 100%|██████████| 1/1 [00:00<00:00, 22.19it/s]

epoch: 1897, beta = 0.000097, Train MSE: 0.006670, Train CE:0.011915, Train KL:8.750896, Val MSE:0.010380, Val CE:0.043380, Train ACC:1.000000, Val ACC:0.993750

Epoch 1899/4000: 100%|██████████| 1/1 [00:00<00:00, 23.03it/s]

epoch: 1898, beta = 0.000097, Train MSE: 0.006680, Train CE:0.011905, Train KL:8.750971, Val MSE:0.010358, Val CE:0.043740, Train ACC:1.000000, Val ACC:0.993750

Epoch 1900/4000: 100%|██████████| 1/1 [00:00<00:00, 20.43it/s]

epoch: 1899, beta = 0.000097, Train MSE: 0.006668, Train CE:0.011914, Train KL:8.751037, Val MSE:0.010365, Val CE:0.043429, Train ACC:1.000000, Val ACC:0.993750

Epoch 1901/4000: 100%|██████████| 1/1 [00:00<00:00, 19.07it/s]

epoch: 1900, beta = 0.000097, Train MSE: 0.006674, Train CE:0.011904, Train KL:8.751103, Val MSE:0.010357, Val CE:0.043349, Train ACC:1.000000, Val ACC:0.993750

Epoch 1902/4000: 100%|██████████| 1/1 [00:00<00:00, 22.39it/s]

epoch: 1901, beta = 0.000097, Train MSE: 0.006663, Train CE:0.011908, Train KL:8.751172, Val MSE:0.010357, Val CE:0.043462, Train ACC:1.000000, Val ACC:0.993750

Epoch 1903/4000: 100%|██████████| 1/1 [00:00<00:00, 23.19it/s]

epoch: 1902, beta = 0.000097, Train MSE: 0.006676, Train CE:0.011905, Train KL:8.751245, Val MSE:0.010351, Val CE:0.043674, Train ACC:1.000000, Val ACC:0.993750

Epoch 1904/4000: 100%|██████████| 1/1 [00:00<00:00, 22.32it/s]

epoch: 1903, beta = 0.000097, Train MSE: 0.006673, Train CE:0.011907, Train KL:8.751323, Val MSE:0.010352, Val CE:0.043635, Train ACC:1.000000, Val ACC:0.993750

Epoch 1905/4000: 100%|██████████| 1/1 [00:00<00:00, 25.63it/s]

Learning rate updated: 1.6515374385013564e-05
epoch: 1904, beta = 0.000097, Train MSE: 0.006678, Train CE:0.011908, Train KL:8.751405, Val MSE:0.010344, Val CE:0.043657, Train ACC:1.000000, Val ACC:0.993750

Epoch 1906/4000: 100%|██████████| 1/1 [00:00<00:00, 20.77it/s]

epoch: 1905, beta = 0.000097, Train MSE: 0.006670, Train CE:0.011906, Train KL:8.751491, Val MSE:0.010348, Val CE:0.043431, Train ACC:1.000000, Val ACC:0.993750

Epoch 1907/4000: 100%|██████████| 1/1 [00:00<00:00, 22.93it/s]

epoch: 1906, beta = 0.000097, Train MSE: 0.006675, Train CE:0.011900, Train KL:8.751577, Val MSE:0.010375, Val CE:0.043856, Train ACC:1.000000, Val ACC:0.993750

Epoch 1908/4000: 100%|██████████| 1/1 [00:00<00:00, 24.22it/s]

epoch: 1907, beta = 0.000097, Train MSE: 0.006666, Train CE:0.011900, Train KL:8.751659, Val MSE:0.010359, Val CE:0.043697, Train ACC:1.000000, Val ACC:0.993750

Epoch 1909/4000: 100%|██████████| 1/1 [00:00<00:00, 24.56it/s]

epoch: 1908, beta = 0.000097, Train MSE: 0.006664, Train CE:0.011901, Train KL:8.751737, Val MSE:0.010333, Val CE:0.043606, Train ACC:1.000000, Val ACC:0.993750

Epoch 1910/4000: 100%|██████████| 1/1 [00:00<00:00, 22.60it/s]

epoch: 1909, beta = 0.000097, Train MSE: 0.006668, Train CE:0.011898, Train KL:8.751808, Val MSE:0.010329, Val CE:0.043670, Train ACC:1.000000, Val ACC:0.993750

Epoch 1911/4000: 100%|██████████| 1/1 [00:00<00:00, 23.99it/s]

epoch: 1910, beta = 0.000097, Train MSE: 0.006660, Train CE:0.011901, Train KL:8.751870, Val MSE:0.010356, Val CE:0.043791, Train ACC:1.000000, Val ACC:0.993229

Epoch 1912/4000: 100%|██████████| 1/1 [00:00<00:00, 21.71it/s]

epoch: 1911, beta = 0.000097, Train MSE: 0.006680, Train CE:0.011894, Train KL:8.751927, Val MSE:0.010349, Val CE:0.043523, Train ACC:1.000000, Val ACC:0.993750

Epoch 1913/4000: 100%|██████████| 1/1 [00:00<00:00, 24.10it/s]

epoch: 1912, beta = 0.000097, Train MSE: 0.006672, Train CE:0.011898, Train KL:8.751990, Val MSE:0.010339, Val CE:0.043653, Train ACC:1.000000, Val ACC:0.993750

Epoch 1914/4000: 100%|██████████| 1/1 [00:00<00:00, 23.02it/s]

epoch: 1913, beta = 0.000097, Train MSE: 0.006679, Train CE:0.011896, Train KL:8.752057, Val MSE:0.010376, Val CE:0.043412, Train ACC:1.000000, Val ACC:0.993750

Epoch 1915/4000: 100%|██████████| 1/1 [00:00<00:00, 23.56it/s]

epoch: 1914, beta = 0.000097, Train MSE: 0.006675, Train CE:0.011888, Train KL:8.752120, Val MSE:0.010358, Val CE:0.043520, Train ACC:1.000000, Val ACC:0.993750

Epoch 1916/4000: 100%|██████████| 1/1 [00:00<00:00, 24.27it/s]

Learning rate updated: 1.5689605665762886e-05
epoch: 1915, beta = 0.000097, Train MSE: 0.006668, Train CE:0.011891, Train KL:8.752188, Val MSE:0.010346, Val CE:0.043446, Train ACC:1.000000, Val ACC:0.993750

Epoch 1917/4000: 100%|██████████| 1/1 [00:00<00:00, 23.97it/s]

epoch: 1916, beta = 0.000097, Train MSE: 0.006673, Train CE:0.011887, Train KL:8.752262, Val MSE:0.010349, Val CE:0.043481, Train ACC:1.000000, Val ACC:0.993750

Epoch 1918/4000: 100%|██████████| 1/1 [00:00<00:00, 27.77it/s]

epoch: 1917, beta = 0.000097, Train MSE: 0.006657, Train CE:0.011888, Train KL:8.752337, Val MSE:0.010379, Val CE:0.043528, Train ACC:1.000000, Val ACC:0.993750

Epoch 1919/4000: 100%|██████████| 1/1 [00:00<00:00, 22.68it/s]

epoch: 1918, beta = 0.000097, Train MSE: 0.006665, Train CE:0.011888, Train KL:8.752415, Val MSE:0.010353, Val CE:0.043728, Train ACC:1.000000, Val ACC:0.993750

Epoch 1920/4000: 100%|██████████| 1/1 [00:00<00:00, 20.46it/s]

epoch: 1919, beta = 0.000097, Train MSE: 0.006671, Train CE:0.011891, Train KL:8.752491, Val MSE:0.010356, Val CE:0.043533, Train ACC:1.000000, Val ACC:0.993750

Epoch 1921/4000: 100%|██████████| 1/1 [00:00<00:00, 21.61it/s]

epoch: 1920, beta = 0.000097, Train MSE: 0.006667, Train CE:0.011888, Train KL:8.752571, Val MSE:0.010355, Val CE:0.043666, Train ACC:1.000000, Val ACC:0.993750

Epoch 1922/4000: 100%|██████████| 1/1 [00:00<00:00, 22.62it/s]

epoch: 1921, beta = 0.000097, Train MSE: 0.006667, Train CE:0.011881, Train KL:8.752649, Val MSE:0.010318, Val CE:0.043554, Train ACC:1.000000, Val ACC:0.993750

Epoch 1923/4000: 100%|██████████| 1/1 [00:00<00:00, 24.66it/s]

epoch: 1922, beta = 0.000097, Train MSE: 0.006671, Train CE:0.011887, Train KL:8.752731, Val MSE:0.010325, Val CE:0.043322, Train ACC:1.000000, Val ACC:0.993750

Epoch 1924/4000: 100%|██████████| 1/1 [00:00<00:00, 24.28it/s]

epoch: 1923, beta = 0.000097, Train MSE: 0.006664, Train CE:0.011882, Train KL:8.752808, Val MSE:0.010344, Val CE:0.043367, Train ACC:1.000000, Val ACC:0.993750

Epoch 1925/4000: 100%|██████████| 1/1 [00:00<00:00, 21.73it/s]

epoch: 1924, beta = 0.000097, Train MSE: 0.006659, Train CE:0.011879, Train KL:8.752881, Val MSE:0.010367, Val CE:0.043526, Train ACC:1.000000, Val ACC:0.993750

Epoch 1926/4000: 100%|██████████| 1/1 [00:00<00:00, 24.17it/s]

epoch: 1925, beta = 0.000097, Train MSE: 0.006664, Train CE:0.011883, Train KL:8.752952, Val MSE:0.010347, Val CE:0.043612, Train ACC:1.000000, Val ACC:0.993750

Epoch 1927/4000: 100%|██████████| 1/1 [00:00<00:00, 23.69it/s]

Learning rate updated: 1.490512538247474e-05
epoch: 1926, beta = 0.000097, Train MSE: 0.006673, Train CE:0.011877, Train KL:8.753024, Val MSE:0.010338, Val CE:0.043533, Train ACC:1.000000, Val ACC:0.993750

Epoch 1928/4000: 100%|██████████| 1/1 [00:00<00:00, 24.03it/s]

epoch: 1927, beta = 0.000097, Train MSE: 0.006666, Train CE:0.011876, Train KL:8.753099, Val MSE:0.010333, Val CE:0.043726, Train ACC:1.000000, Val ACC:0.993750

Epoch 1929/4000: 100%|██████████| 1/1 [00:00<00:00, 23.33it/s]

epoch: 1928, beta = 0.000097, Train MSE: 0.006675, Train CE:0.011872, Train KL:8.753168, Val MSE:0.010361, Val CE:0.043482, Train ACC:1.000000, Val ACC:0.993750

Epoch 1930/4000: 100%|██████████| 1/1 [00:00<00:00, 23.00it/s]

epoch: 1929, beta = 0.000097, Train MSE: 0.006669, Train CE:0.011879, Train KL:8.753242, Val MSE:0.010356, Val CE:0.043675, Train ACC:1.000000, Val ACC:0.993750

Epoch 1931/4000: 100%|██████████| 1/1 [00:00<00:00, 23.93it/s]

epoch: 1930, beta = 0.000097, Train MSE: 0.006662, Train CE:0.011875, Train KL:8.753317, Val MSE:0.010346, Val CE:0.043688, Train ACC:1.000000, Val ACC:0.993750

Epoch 1932/4000: 100%|██████████| 1/1 [00:00<00:00, 22.93it/s]

epoch: 1931, beta = 0.000097, Train MSE: 0.006666, Train CE:0.011874, Train KL:8.753384, Val MSE:0.010357, Val CE:0.043547, Train ACC:1.000000, Val ACC:0.993750

Epoch 1933/4000: 100%|██████████| 1/1 [00:00<00:00, 23.73it/s]

epoch: 1932, beta = 0.000097, Train MSE: 0.006665, Train CE:0.011871, Train KL:8.753448, Val MSE:0.010371, Val CE:0.043454, Train ACC:1.000000, Val ACC:0.993750

Epoch 1934/4000: 100%|██████████| 1/1 [00:00<00:00, 26.06it/s]

epoch: 1933, beta = 0.000097, Train MSE: 0.006665, Train CE:0.011876, Train KL:8.753505, Val MSE:0.010335, Val CE:0.043283, Train ACC:1.000000, Val ACC:0.993750

Epoch 1935/4000: 100%|██████████| 1/1 [00:00<00:00, 26.21it/s]

epoch: 1934, beta = 0.000097, Train MSE: 0.006667, Train CE:0.011867, Train KL:8.753565, Val MSE:0.010359, Val CE:0.043554, Train ACC:1.000000, Val ACC:0.993750

Epoch 1936/4000: 100%|██████████| 1/1 [00:00<00:00, 23.53it/s]

epoch: 1935, beta = 0.000097, Train MSE: 0.006657, Train CE:0.011870, Train KL:8.753622, Val MSE:0.010362, Val CE:0.043574, Train ACC:1.000000, Val ACC:0.993750

Epoch 1937/4000: 100%|██████████| 1/1 [00:00<00:00, 24.28it/s]

epoch: 1936, beta = 0.000097, Train MSE: 0.006655, Train CE:0.011871, Train KL:8.753681, Val MSE:0.010351, Val CE:0.043604, Train ACC:1.000000, Val ACC:0.993750

Epoch 1938/4000: 100%|██████████| 1/1 [00:00<00:00, 23.57it/s]

Learning rate updated: 1.4159869113351003e-05
epoch: 1937, beta = 0.000097, Train MSE: 0.006662, Train CE:0.011868, Train KL:8.753741, Val MSE:0.010365, Val CE:0.043531, Train ACC:1.000000, Val ACC:0.993750

Epoch 1939/4000: 100%|██████████| 1/1 [00:00<00:00, 19.36it/s]

epoch: 1938, beta = 0.000097, Train MSE: 0.006670, Train CE:0.011862, Train KL:8.753806, Val MSE:0.010358, Val CE:0.043729, Train ACC:1.000000, Val ACC:0.993750

Epoch 1940/4000: 100%|██████████| 1/1 [00:00<00:00,  5.44it/s]

epoch: 1939, beta = 0.000097, Train MSE: 0.006656, Train CE:0.011862, Train KL:8.753868, Val MSE:0.010352, Val CE:0.043489, Train ACC:1.000000, Val ACC:0.993750

Epoch 1941/4000: 100%|██████████| 1/1 [00:00<00:00, 23.34it/s]

epoch: 1940, beta = 0.000097, Train MSE: 0.006667, Train CE:0.011868, Train KL:8.753930, Val MSE:0.010334, Val CE:0.043620, Train ACC:1.000000, Val ACC:0.993750

Epoch 1942/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 1941, beta = 0.000097, Train MSE: 0.006661, Train CE:0.011866, Train KL:8.753991, Val MSE:0.010360, Val CE:0.043426, Train ACC:1.000000, Val ACC:0.993750

Epoch 1943/4000: 100%|██████████| 1/1 [00:00<00:00, 23.94it/s]

epoch: 1942, beta = 0.000097, Train MSE: 0.006665, Train CE:0.011864, Train KL:8.754052, Val MSE:0.010359, Val CE:0.043332, Train ACC:1.000000, Val ACC:0.993750

Epoch 1944/4000: 100%|██████████| 1/1 [00:00<00:00, 20.74it/s]

epoch: 1943, beta = 0.000097, Train MSE: 0.006664, Train CE:0.011865, Train KL:8.754112, Val MSE:0.010350, Val CE:0.043466, Train ACC:1.000000, Val ACC:0.993750

Epoch 1945/4000: 100%|██████████| 1/1 [00:00<00:00, 23.94it/s]

epoch: 1944, beta = 0.000097, Train MSE: 0.006660, Train CE:0.011862, Train KL:8.754171, Val MSE:0.010351, Val CE:0.043559, Train ACC:1.000000, Val ACC:0.993750

Epoch 1946/4000: 100%|██████████| 1/1 [00:00<00:00, 24.01it/s]

epoch: 1945, beta = 0.000097, Train MSE: 0.006663, Train CE:0.011870, Train KL:8.754231, Val MSE:0.010355, Val CE:0.043467, Train ACC:1.000000, Val ACC:0.993750

Epoch 1947/4000: 100%|██████████| 1/1 [00:00<00:00, 23.99it/s]

epoch: 1946, beta = 0.000097, Train MSE: 0.006662, Train CE:0.011857, Train KL:8.754295, Val MSE:0.010329, Val CE:0.043555, Train ACC:1.000000, Val ACC:0.993750

Epoch 1948/4000: 100%|██████████| 1/1 [00:00<00:00, 23.38it/s]

epoch: 1947, beta = 0.000097, Train MSE: 0.006664, Train CE:0.011854, Train KL:8.754356, Val MSE:0.010367, Val CE:0.043510, Train ACC:1.000000, Val ACC:0.993750

Epoch 1949/4000: 100%|██████████| 1/1 [00:00<00:00, 24.03it/s]

Learning rate updated: 1.3451875657683452e-05
epoch: 1948, beta = 0.000097, Train MSE: 0.006666, Train CE:0.011864, Train KL:8.754414, Val MSE:0.010347, Val CE:0.043550, Train ACC:1.000000, Val ACC:0.993750

Epoch 1950/4000: 100%|██████████| 1/1 [00:00<00:00, 23.58it/s]

epoch: 1949, beta = 0.000097, Train MSE: 0.006659, Train CE:0.011859, Train KL:8.754476, Val MSE:0.010331, Val CE:0.043584, Train ACC:1.000000, Val ACC:0.993750

Epoch 1951/4000: 100%|██████████| 1/1 [00:00<00:00, 23.84it/s]

epoch: 1950, beta = 0.000097, Train MSE: 0.006658, Train CE:0.011852, Train KL:8.754536, Val MSE:0.010347, Val CE:0.043720, Train ACC:1.000000, Val ACC:0.993750

Epoch 1952/4000: 100%|██████████| 1/1 [00:00<00:00, 24.04it/s]

epoch: 1951, beta = 0.000097, Train MSE: 0.006666, Train CE:0.011848, Train KL:8.754598, Val MSE:0.010327, Val CE:0.043516, Train ACC:1.000000, Val ACC:0.993750

Epoch 1953/4000: 100%|██████████| 1/1 [00:00<00:00, 26.80it/s]

epoch: 1952, beta = 0.000097, Train MSE: 0.006652, Train CE:0.011855, Train KL:8.754657, Val MSE:0.010340, Val CE:0.043412, Train ACC:1.000000, Val ACC:0.993750

Epoch 1954/4000: 100%|██████████| 1/1 [00:00<00:00, 23.55it/s]

epoch: 1953, beta = 0.000097, Train MSE: 0.006665, Train CE:0.011856, Train KL:8.754717, Val MSE:0.010346, Val CE:0.043553, Train ACC:1.000000, Val ACC:0.993750

Epoch 1955/4000: 100%|██████████| 1/1 [00:00<00:00, 24.01it/s]

epoch: 1954, beta = 0.000097, Train MSE: 0.006661, Train CE:0.011854, Train KL:8.754778, Val MSE:0.010343, Val CE:0.043734, Train ACC:1.000000, Val ACC:0.993750

Epoch 1956/4000: 100%|██████████| 1/1 [00:00<00:00, 23.88it/s]

epoch: 1955, beta = 0.000097, Train MSE: 0.006660, Train CE:0.011852, Train KL:8.754841, Val MSE:0.010333, Val CE:0.043349, Train ACC:1.000000, Val ACC:0.993750

Epoch 1957/4000: 100%|██████████| 1/1 [00:00<00:00, 24.10it/s]

epoch: 1956, beta = 0.000097, Train MSE: 0.006654, Train CE:0.011848, Train KL:8.754905, Val MSE:0.010314, Val CE:0.043491, Train ACC:1.000000, Val ACC:0.993750

Epoch 1958/4000: 100%|██████████| 1/1 [00:00<00:00, 22.04it/s]

epoch: 1957, beta = 0.000097, Train MSE: 0.006653, Train CE:0.011846, Train KL:8.754968, Val MSE:0.010358, Val CE:0.043514, Train ACC:1.000000, Val ACC:0.993750

Epoch 1959/4000: 100%|██████████| 1/1 [00:00<00:00, 24.80it/s]

epoch: 1958, beta = 0.000097, Train MSE: 0.006655, Train CE:0.011847, Train KL:8.755030, Val MSE:0.010331, Val CE:0.043437, Train ACC:1.000000, Val ACC:0.993750

Epoch 1960/4000: 100%|██████████| 1/1 [00:00<00:00, 22.90it/s]

Learning rate updated: 1.277928187479928e-05
epoch: 1959, beta = 0.000097, Train MSE: 0.006666, Train CE:0.011849, Train KL:8.755091, Val MSE:0.010325, Val CE:0.043423, Train ACC:1.000000, Val ACC:0.993750

Epoch 1961/4000: 100%|██████████| 1/1 [00:00<00:00, 19.03it/s]

epoch: 1960, beta = 0.000097, Train MSE: 0.006652, Train CE:0.011843, Train KL:8.755157, Val MSE:0.010340, Val CE:0.043468, Train ACC:1.000000, Val ACC:0.993750

Epoch 1962/4000: 100%|██████████| 1/1 [00:00<00:00, 20.10it/s]

epoch: 1961, beta = 0.000097, Train MSE: 0.006655, Train CE:0.011840, Train KL:8.755214, Val MSE:0.010346, Val CE:0.043152, Train ACC:1.000000, Val ACC:0.993750

Epoch 1963/4000: 100%|██████████| 1/1 [00:00<00:00, 22.03it/s]

epoch: 1962, beta = 0.000097, Train MSE: 0.006656, Train CE:0.011842, Train KL:8.755268, Val MSE:0.010351, Val CE:0.043161, Train ACC:1.000000, Val ACC:0.993750

Epoch 1964/4000: 100%|██████████| 1/1 [00:00<00:00, 24.02it/s]

epoch: 1963, beta = 0.000097, Train MSE: 0.006668, Train CE:0.011847, Train KL:8.755322, Val MSE:0.010341, Val CE:0.043254, Train ACC:1.000000, Val ACC:0.993750

Epoch 1965/4000: 100%|██████████| 1/1 [00:00<00:00, 23.10it/s]

epoch: 1964, beta = 0.000097, Train MSE: 0.006663, Train CE:0.011848, Train KL:8.755376, Val MSE:0.010327, Val CE:0.043380, Train ACC:1.000000, Val ACC:0.993750

Epoch 1966/4000: 100%|██████████| 1/1 [00:00<00:00, 23.58it/s]

epoch: 1965, beta = 0.000097, Train MSE: 0.006659, Train CE:0.011850, Train KL:8.755432, Val MSE:0.010341, Val CE:0.043242, Train ACC:1.000000, Val ACC:0.993750

Epoch 1967/4000: 100%|██████████| 1/1 [00:00<00:00, 23.73it/s]

epoch: 1966, beta = 0.000097, Train MSE: 0.006660, Train CE:0.011844, Train KL:8.755491, Val MSE:0.010370, Val CE:0.043405, Train ACC:1.000000, Val ACC:0.993750

Epoch 1968/4000: 100%|██████████| 1/1 [00:00<00:00, 25.30it/s]

epoch: 1967, beta = 0.000097, Train MSE: 0.006658, Train CE:0.011835, Train KL:8.755557, Val MSE:0.010345, Val CE:0.043463, Train ACC:1.000000, Val ACC:0.993750

Epoch 1969/4000: 100%|██████████| 1/1 [00:00<00:00, 24.30it/s]

epoch: 1968, beta = 0.000097, Train MSE: 0.006662, Train CE:0.011840, Train KL:8.755625, Val MSE:0.010363, Val CE:0.043442, Train ACC:1.000000, Val ACC:0.993750

Epoch 1970/4000: 100%|██████████| 1/1 [00:00<00:00, 22.01it/s]

epoch: 1969, beta = 0.000097, Train MSE: 0.006651, Train CE:0.011839, Train KL:8.755692, Val MSE:0.010324, Val CE:0.043533, Train ACC:1.000000, Val ACC:0.993750

Epoch 1971/4000: 100%|██████████| 1/1 [00:00<00:00, 24.21it/s]

Learning rate updated: 1.2140317781059316e-05
epoch: 1970, beta = 0.000097, Train MSE: 0.006658, Train CE:0.011835, Train KL:8.755759, Val MSE:0.010376, Val CE:0.043601, Train ACC:1.000000, Val ACC:0.993750

Epoch 1972/4000: 100%|██████████| 1/1 [00:00<00:00, 25.34it/s]

epoch: 1971, beta = 0.000097, Train MSE: 0.006658, Train CE:0.011837, Train KL:8.755823, Val MSE:0.010360, Val CE:0.043440, Train ACC:1.000000, Val ACC:0.993750

Epoch 1973/4000: 100%|██████████| 1/1 [00:00<00:00, 22.31it/s]

epoch: 1972, beta = 0.000097, Train MSE: 0.006657, Train CE:0.011835, Train KL:8.755884, Val MSE:0.010343, Val CE:0.043727, Train ACC:1.000000, Val ACC:0.993750

Epoch 1974/4000: 100%|██████████| 1/1 [00:00<00:00, 21.02it/s]

epoch: 1973, beta = 0.000097, Train MSE: 0.006655, Train CE:0.011836, Train KL:8.755938, Val MSE:0.010320, Val CE:0.043526, Train ACC:1.000000, Val ACC:0.993750

Epoch 1975/4000: 100%|██████████| 1/1 [00:00<00:00, 24.20it/s]

epoch: 1974, beta = 0.000097, Train MSE: 0.006645, Train CE:0.011836, Train KL:8.755994, Val MSE:0.010328, Val CE:0.043721, Train ACC:1.000000, Val ACC:0.993750

Epoch 1976/4000: 100%|██████████| 1/1 [00:00<00:00, 24.71it/s]

epoch: 1975, beta = 0.000097, Train MSE: 0.006646, Train CE:0.011833, Train KL:8.756049, Val MSE:0.010347, Val CE:0.043661, Train ACC:1.000000, Val ACC:0.993750

Epoch 1977/4000: 100%|██████████| 1/1 [00:00<00:00, 23.29it/s]

epoch: 1976, beta = 0.000097, Train MSE: 0.006652, Train CE:0.011836, Train KL:8.756102, Val MSE:0.010355, Val CE:0.043613, Train ACC:1.000000, Val ACC:0.993229

Epoch 1978/4000: 100%|██████████| 1/1 [00:00<00:00, 21.74it/s]

epoch: 1977, beta = 0.000097, Train MSE: 0.006658, Train CE:0.011826, Train KL:8.756155, Val MSE:0.010345, Val CE:0.043669, Train ACC:1.000000, Val ACC:0.993750

Epoch 1979/4000: 100%|██████████| 1/1 [00:00<00:00, 20.19it/s]

epoch: 1978, beta = 0.000097, Train MSE: 0.006650, Train CE:0.011830, Train KL:8.756210, Val MSE:0.010348, Val CE:0.043549, Train ACC:1.000000, Val ACC:0.993750

Epoch 1980/4000: 100%|██████████| 1/1 [00:00<00:00, 23.66it/s]

epoch: 1979, beta = 0.000097, Train MSE: 0.006653, Train CE:0.011825, Train KL:8.756264, Val MSE:0.010345, Val CE:0.043614, Train ACC:1.000000, Val ACC:0.993750

Epoch 1981/4000: 100%|██████████| 1/1 [00:00<00:00, 24.28it/s]

epoch: 1980, beta = 0.000097, Train MSE: 0.006660, Train CE:0.011828, Train KL:8.756318, Val MSE:0.010333, Val CE:0.043750, Train ACC:1.000000, Val ACC:0.993750

Epoch 1982/4000: 100%|██████████| 1/1 [00:00<00:00, 24.21it/s]

Learning rate updated: 1.153330189200635e-05
epoch: 1981, beta = 0.000097, Train MSE: 0.006642, Train CE:0.011829, Train KL:8.756375, Val MSE:0.010341, Val CE:0.043629, Train ACC:1.000000, Val ACC:0.993750

Epoch 1983/4000: 100%|██████████| 1/1 [00:00<00:00, 23.56it/s]

epoch: 1982, beta = 0.000097, Train MSE: 0.006651, Train CE:0.011823, Train KL:8.756429, Val MSE:0.010360, Val CE:0.043565, Train ACC:1.000000, Val ACC:0.993750

Epoch 1984/4000: 100%|██████████| 1/1 [00:00<00:00, 23.98it/s]

epoch: 1983, beta = 0.000097, Train MSE: 0.006653, Train CE:0.011826, Train KL:8.756482, Val MSE:0.010345, Val CE:0.043685, Train ACC:1.000000, Val ACC:0.993750

Epoch 1985/4000: 100%|██████████| 1/1 [00:00<00:00, 25.68it/s]

epoch: 1984, beta = 0.000097, Train MSE: 0.006667, Train CE:0.011827, Train KL:8.756534, Val MSE:0.010364, Val CE:0.043587, Train ACC:1.000000, Val ACC:0.993750

Epoch 1986/4000: 100%|██████████| 1/1 [00:00<00:00, 24.36it/s]

epoch: 1985, beta = 0.000097, Train MSE: 0.006647, Train CE:0.011825, Train KL:8.756587, Val MSE:0.010345, Val CE:0.043365, Train ACC:1.000000, Val ACC:0.993750

Epoch 1987/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 1986, beta = 0.000097, Train MSE: 0.006647, Train CE:0.011819, Train KL:8.756642, Val MSE:0.010362, Val CE:0.043835, Train ACC:1.000000, Val ACC:0.993750

Epoch 1988/4000: 100%|██████████| 1/1 [00:00<00:00, 24.52it/s]

epoch: 1987, beta = 0.000097, Train MSE: 0.006649, Train CE:0.011821, Train KL:8.756695, Val MSE:0.010340, Val CE:0.043544, Train ACC:1.000000, Val ACC:0.993750

Epoch 1989/4000: 100%|██████████| 1/1 [00:00<00:00, 23.96it/s]

epoch: 1988, beta = 0.000097, Train MSE: 0.006649, Train CE:0.011819, Train KL:8.756748, Val MSE:0.010344, Val CE:0.043668, Train ACC:1.000000, Val ACC:0.993750

Epoch 1990/4000: 100%|██████████| 1/1 [00:00<00:00, 24.02it/s]

epoch: 1989, beta = 0.000097, Train MSE: 0.006654, Train CE:0.011826, Train KL:8.756802, Val MSE:0.010349, Val CE:0.043654, Train ACC:1.000000, Val ACC:0.993750

Epoch 1991/4000: 100%|██████████| 1/1 [00:00<00:00, 25.16it/s]

epoch: 1990, beta = 0.000097, Train MSE: 0.006655, Train CE:0.011827, Train KL:8.756852, Val MSE:0.010326, Val CE:0.043743, Train ACC:1.000000, Val ACC:0.993750

Epoch 1992/4000: 100%|██████████| 1/1 [00:00<00:00, 24.14it/s]

epoch: 1991, beta = 0.000097, Train MSE: 0.006653, Train CE:0.011821, Train KL:8.756900, Val MSE:0.010346, Val CE:0.043667, Train ACC:1.000000, Val ACC:0.993750

Epoch 1993/4000: 100%|██████████| 1/1 [00:00<00:00, 23.36it/s]

Learning rate updated: 1.0956636797406032e-05
epoch: 1992, beta = 0.000097, Train MSE: 0.006646, Train CE:0.011819, Train KL:8.756944, Val MSE:0.010336, Val CE:0.043548, Train ACC:1.000000, Val ACC:0.993750

Epoch 1994/4000: 100%|██████████| 1/1 [00:00<00:00, 24.03it/s]

epoch: 1993, beta = 0.000097, Train MSE: 0.006648, Train CE:0.011818, Train KL:8.756987, Val MSE:0.010324, Val CE:0.043307, Train ACC:1.000000, Val ACC:0.993750

Epoch 1995/4000: 100%|██████████| 1/1 [00:00<00:00, 24.02it/s]

epoch: 1994, beta = 0.000097, Train MSE: 0.006647, Train CE:0.011814, Train KL:8.757030, Val MSE:0.010341, Val CE:0.043370, Train ACC:1.000000, Val ACC:0.993750

Epoch 1996/4000: 100%|██████████| 1/1 [00:00<00:00, 23.95it/s]

epoch: 1995, beta = 0.000097, Train MSE: 0.006648, Train CE:0.011816, Train KL:8.757071, Val MSE:0.010343, Val CE:0.043460, Train ACC:1.000000, Val ACC:0.993750

Epoch 1997/4000: 100%|██████████| 1/1 [00:00<00:00, 24.54it/s]

epoch: 1996, beta = 0.000097, Train MSE: 0.006643, Train CE:0.011815, Train KL:8.757113, Val MSE:0.010335, Val CE:0.043308, Train ACC:1.000000, Val ACC:0.993750

Epoch 1998/4000: 100%|██████████| 1/1 [00:00<00:00, 21.33it/s]

epoch: 1997, beta = 0.000097, Train MSE: 0.006650, Train CE:0.011812, Train KL:8.757155, Val MSE:0.010329, Val CE:0.043528, Train ACC:1.000000, Val ACC:0.993750

Epoch 1999/4000: 100%|██████████| 1/1 [00:00<00:00, 24.66it/s]

epoch: 1998, beta = 0.000097, Train MSE: 0.006655, Train CE:0.011815, Train KL:8.757198, Val MSE:0.010314, Val CE:0.043559, Train ACC:1.000000, Val ACC:0.993750

Epoch 2000/4000: 100%|██████████| 1/1 [00:00<00:00, 20.77it/s]

epoch: 1999, beta = 0.000097, Train MSE: 0.006645, Train CE:0.011807, Train KL:8.757246, Val MSE:0.010319, Val CE:0.043439, Train ACC:1.000000, Val ACC:0.993750

Epoch 2001/4000: 100%|██████████| 1/1 [00:00<00:00, 24.81it/s]

epoch: 2000, beta = 0.000097, Train MSE: 0.006655, Train CE:0.011809, Train KL:8.757297, Val MSE:0.010342, Val CE:0.043610, Train ACC:1.000000, Val ACC:0.993750

Epoch 2002/4000: 100%|██████████| 1/1 [00:00<00:00, 23.44it/s]

epoch: 2001, beta = 0.000097, Train MSE: 0.006659, Train CE:0.011808, Train KL:8.757347, Val MSE:0.010357, Val CE:0.043593, Train ACC:1.000000, Val ACC:0.993750

Epoch 2003/4000: 100%|██████████| 1/1 [00:00<00:00, 20.42it/s]

epoch: 2002, beta = 0.000097, Train MSE: 0.006657, Train CE:0.011813, Train KL:8.757397, Val MSE:0.010342, Val CE:0.043508, Train ACC:1.000000, Val ACC:0.993750

Epoch 2004/4000: 100%|██████████| 1/1 [00:00<00:00, 23.18it/s]

Learning rate updated: 1.0408804957535729e-05
epoch: 2003, beta = 0.000097, Train MSE: 0.006645, Train CE:0.011815, Train KL:8.757448, Val MSE:0.010334, Val CE:0.043512, Train ACC:1.000000, Val ACC:0.993750

Epoch 2005/4000: 100%|██████████| 1/1 [00:00<00:00, 22.90it/s]

epoch: 2004, beta = 0.000097, Train MSE: 0.006650, Train CE:0.011810, Train KL:8.757498, Val MSE:0.010327, Val CE:0.043490, Train ACC:1.000000, Val ACC:0.993750

Epoch 2006/4000: 100%|██████████| 1/1 [00:00<00:00, 22.43it/s]

epoch: 2005, beta = 0.000097, Train MSE: 0.006647, Train CE:0.011810, Train KL:8.757540, Val MSE:0.010313, Val CE:0.043465, Train ACC:1.000000, Val ACC:0.993750

Epoch 2007/4000: 100%|██████████| 1/1 [00:00<00:00, 22.28it/s]

epoch: 2006, beta = 0.000097, Train MSE: 0.006654, Train CE:0.011808, Train KL:8.757582, Val MSE:0.010350, Val CE:0.043369, Train ACC:1.000000, Val ACC:0.993750

Epoch 2008/4000: 100%|██████████| 1/1 [00:00<00:00, 22.63it/s]

epoch: 2007, beta = 0.000097, Train MSE: 0.006655, Train CE:0.011809, Train KL:8.757622, Val MSE:0.010329, Val CE:0.043245, Train ACC:1.000000, Val ACC:0.993750

Epoch 2009/4000: 100%|██████████| 1/1 [00:00<00:00, 25.01it/s]

epoch: 2008, beta = 0.000097, Train MSE: 0.006649, Train CE:0.011805, Train KL:8.757663, Val MSE:0.010335, Val CE:0.043474, Train ACC:1.000000, Val ACC:0.993750

Epoch 2010/4000: 100%|██████████| 1/1 [00:00<00:00, 24.27it/s]

epoch: 2009, beta = 0.000097, Train MSE: 0.006643, Train CE:0.011805, Train KL:8.757703, Val MSE:0.010344, Val CE:0.043277, Train ACC:1.000000, Val ACC:0.993750

Epoch 2011/4000: 100%|██████████| 1/1 [00:00<00:00, 23.48it/s]

epoch: 2010, beta = 0.000097, Train MSE: 0.006640, Train CE:0.011801, Train KL:8.757747, Val MSE:0.010332, Val CE:0.043355, Train ACC:1.000000, Val ACC:0.993750

Epoch 2012/4000: 100%|██████████| 1/1 [00:00<00:00, 23.05it/s]

epoch: 2011, beta = 0.000097, Train MSE: 0.006650, Train CE:0.011804, Train KL:8.757793, Val MSE:0.010345, Val CE:0.043388, Train ACC:1.000000, Val ACC:0.993750

Epoch 2013/4000: 100%|██████████| 1/1 [00:00<00:00, 24.03it/s]

epoch: 2012, beta = 0.000097, Train MSE: 0.006646, Train CE:0.011809, Train KL:8.757842, Val MSE:0.010373, Val CE:0.043278, Train ACC:1.000000, Val ACC:0.993750

Epoch 2014/4000: 100%|██████████| 1/1 [00:00<00:00, 23.92it/s]

epoch: 2013, beta = 0.000097, Train MSE: 0.006654, Train CE:0.011804, Train KL:8.757898, Val MSE:0.010329, Val CE:0.043422, Train ACC:1.000000, Val ACC:0.993750

Epoch 2015/4000: 100%|██████████| 1/1 [00:00<00:00, 23.35it/s]

Learning rate updated: 9.888364709658941e-06
epoch: 2014, beta = 0.000097, Train MSE: 0.006645, Train CE:0.011803, Train KL:8.757957, Val MSE:0.010303, Val CE:0.043339, Train ACC:1.000000, Val ACC:0.993750

Epoch 2016/4000: 100%|██████████| 1/1 [00:00<00:00, 21.66it/s]

epoch: 2015, beta = 0.000097, Train MSE: 0.006648, Train CE:0.011797, Train KL:8.758014, Val MSE:0.010292, Val CE:0.043202, Train ACC:1.000000, Val ACC:0.993750

Epoch 2017/4000: 100%|██████████| 1/1 [00:00<00:00, 22.60it/s]

epoch: 2016, beta = 0.000097, Train MSE: 0.006649, Train CE:0.011804, Train KL:8.758065, Val MSE:0.010338, Val CE:0.043403, Train ACC:1.000000, Val ACC:0.993750

Epoch 2018/4000: 100%|██████████| 1/1 [00:00<00:00, 22.00it/s]

epoch: 2017, beta = 0.000097, Train MSE: 0.006648, Train CE:0.011806, Train KL:8.758114, Val MSE:0.010308, Val CE:0.043404, Train ACC:1.000000, Val ACC:0.993750

Epoch 2019/4000: 100%|██████████| 1/1 [00:00<00:00, 22.70it/s]

epoch: 2018, beta = 0.000097, Train MSE: 0.006646, Train CE:0.011795, Train KL:8.758163, Val MSE:0.010344, Val CE:0.043346, Train ACC:1.000000, Val ACC:0.993750

Epoch 2020/4000: 100%|██████████| 1/1 [00:00<00:00, 23.86it/s]

epoch: 2019, beta = 0.000097, Train MSE: 0.006642, Train CE:0.011801, Train KL:8.758210, Val MSE:0.010335, Val CE:0.043439, Train ACC:1.000000, Val ACC:0.993750

Epoch 2021/4000: 100%|██████████| 1/1 [00:00<00:00, 23.61it/s]

epoch: 2020, beta = 0.000097, Train MSE: 0.006641, Train CE:0.011792, Train KL:8.758256, Val MSE:0.010332, Val CE:0.043577, Train ACC:1.000000, Val ACC:0.993750

Epoch 2022/4000: 100%|██████████| 1/1 [00:00<00:00, 24.06it/s]

epoch: 2021, beta = 0.000097, Train MSE: 0.006641, Train CE:0.011800, Train KL:8.758299, Val MSE:0.010313, Val CE:0.043591, Train ACC:1.000000, Val ACC:0.993750

Epoch 2023/4000: 100%|██████████| 1/1 [00:00<00:00, 26.40it/s]

epoch: 2022, beta = 0.000097, Train MSE: 0.006656, Train CE:0.011797, Train KL:8.758339, Val MSE:0.010331, Val CE:0.043316, Train ACC:1.000000, Val ACC:0.993750

Epoch 2024/4000: 100%|██████████| 1/1 [00:00<00:00, 26.94it/s]

epoch: 2023, beta = 0.000097, Train MSE: 0.006658, Train CE:0.011794, Train KL:8.758383, Val MSE:0.010340, Val CE:0.043348, Train ACC:1.000000, Val ACC:0.993750

Epoch 2025/4000: 100%|██████████| 1/1 [00:00<00:00, 19.64it/s]

epoch: 2024, beta = 0.000097, Train MSE: 0.006639, Train CE:0.011803, Train KL:8.758428, Val MSE:0.010318, Val CE:0.043478, Train ACC:1.000000, Val ACC:0.993750

Epoch 2026/4000: 100%|██████████| 1/1 [00:00<00:00, 21.38it/s]

Learning rate updated: 9.393946474175994e-06
epoch: 2025, beta = 0.000097, Train MSE: 0.006648, Train CE:0.011793, Train KL:8.758473, Val MSE:0.010339, Val CE:0.043596, Train ACC:1.000000, Val ACC:0.993750

Epoch 2027/4000: 100%|██████████| 1/1 [00:00<00:00, 21.55it/s]

epoch: 2026, beta = 0.000097, Train MSE: 0.006643, Train CE:0.011791, Train KL:8.758519, Val MSE:0.010294, Val CE:0.043486, Train ACC:1.000000, Val ACC:0.993750

Epoch 2028/4000: 100%|██████████| 1/1 [00:00<00:00, 24.46it/s]

epoch: 2027, beta = 0.000097, Train MSE: 0.006653, Train CE:0.011788, Train KL:8.758564, Val MSE:0.010329, Val CE:0.043574, Train ACC:1.000000, Val ACC:0.993750

Epoch 2029/4000: 100%|██████████| 1/1 [00:00<00:00, 24.20it/s]

epoch: 2028, beta = 0.000097, Train MSE: 0.006642, Train CE:0.011797, Train KL:8.758610, Val MSE:0.010358, Val CE:0.043526, Train ACC:1.000000, Val ACC:0.993750

Epoch 2030/4000: 100%|██████████| 1/1 [00:00<00:00, 24.01it/s]

epoch: 2029, beta = 0.000097, Train MSE: 0.006644, Train CE:0.011793, Train KL:8.758653, Val MSE:0.010337, Val CE:0.043334, Train ACC:1.000000, Val ACC:0.993750

Epoch 2031/4000: 100%|██████████| 1/1 [00:00<00:00, 23.98it/s]

epoch: 2030, beta = 0.000097, Train MSE: 0.006641, Train CE:0.011787, Train KL:8.758698, Val MSE:0.010321, Val CE:0.043426, Train ACC:1.000000, Val ACC:0.993750

Epoch 2032/4000: 100%|██████████| 1/1 [00:00<00:00, 23.93it/s]

epoch: 2031, beta = 0.000097, Train MSE: 0.006652, Train CE:0.011794, Train KL:8.758739, Val MSE:0.010333, Val CE:0.043441, Train ACC:1.000000, Val ACC:0.993750

Epoch 2033/4000: 100%|██████████| 1/1 [00:00<00:00, 24.59it/s]

epoch: 2032, beta = 0.000097, Train MSE: 0.006639, Train CE:0.011791, Train KL:8.758782, Val MSE:0.010324, Val CE:0.043389, Train ACC:1.000000, Val ACC:0.993750

Epoch 2034/4000: 100%|██████████| 1/1 [00:00<00:00, 23.99it/s]

epoch: 2033, beta = 0.000097, Train MSE: 0.006647, Train CE:0.011789, Train KL:8.758823, Val MSE:0.010327, Val CE:0.043567, Train ACC:1.000000, Val ACC:0.993750

Epoch 2035/4000: 100%|██████████| 1/1 [00:00<00:00, 24.03it/s]

epoch: 2034, beta = 0.000097, Train MSE: 0.006642, Train CE:0.011790, Train KL:8.758864, Val MSE:0.010340, Val CE:0.043322, Train ACC:1.000000, Val ACC:0.993750

Epoch 2036/4000: 100%|██████████| 1/1 [00:00<00:00, 26.72it/s]

epoch: 2035, beta = 0.000097, Train MSE: 0.006636, Train CE:0.011789, Train KL:8.758905, Val MSE:0.010331, Val CE:0.043430, Train ACC:1.000000, Val ACC:0.993750

Epoch 2037/4000: 100%|██████████| 1/1 [00:00<00:00, 18.91it/s]

Learning rate updated: 8.924249150467194e-06
epoch: 2036, beta = 0.000097, Train MSE: 0.006646, Train CE:0.011783, Train KL:8.758945, Val MSE:0.010317, Val CE:0.043328, Train ACC:1.000000, Val ACC:0.993750

Epoch 2038/4000: 100%|██████████| 1/1 [00:00<00:00, 23.76it/s]

epoch: 2037, beta = 0.000097, Train MSE: 0.006651, Train CE:0.011790, Train KL:8.758984, Val MSE:0.010322, Val CE:0.043440, Train ACC:1.000000, Val ACC:0.993750

Epoch 2039/4000: 100%|██████████| 1/1 [00:00<00:00, 25.28it/s]

epoch: 2038, beta = 0.000097, Train MSE: 0.006643, Train CE:0.011784, Train KL:8.759022, Val MSE:0.010294, Val CE:0.043574, Train ACC:1.000000, Val ACC:0.993750

Epoch 2040/4000: 100%|██████████| 1/1 [00:00<00:00, 24.84it/s]

epoch: 2039, beta = 0.000097, Train MSE: 0.006637, Train CE:0.011781, Train KL:8.759064, Val MSE:0.010339, Val CE:0.043373, Train ACC:1.000000, Val ACC:0.993750

Epoch 2041/4000: 100%|██████████| 1/1 [00:00<00:00, 24.14it/s]

epoch: 2040, beta = 0.000097, Train MSE: 0.006645, Train CE:0.011780, Train KL:8.759106, Val MSE:0.010340, Val CE:0.043633, Train ACC:1.000000, Val ACC:0.993750

Epoch 2042/4000: 100%|██████████| 1/1 [00:00<00:00, 24.69it/s]

epoch: 2041, beta = 0.000097, Train MSE: 0.006650, Train CE:0.011783, Train KL:8.759148, Val MSE:0.010310, Val CE:0.043263, Train ACC:1.000000, Val ACC:0.993750

Epoch 2043/4000: 100%|██████████| 1/1 [00:00<00:00, 22.36it/s]

epoch: 2042, beta = 0.000097, Train MSE: 0.006635, Train CE:0.011775, Train KL:8.759194, Val MSE:0.010331, Val CE:0.043379, Train ACC:1.000000, Val ACC:0.993750

Epoch 2044/4000: 100%|██████████| 1/1 [00:00<00:00, 23.93it/s]

epoch: 2043, beta = 0.000097, Train MSE: 0.006658, Train CE:0.011777, Train KL:8.759239, Val MSE:0.010329, Val CE:0.043237, Train ACC:1.000000, Val ACC:0.993750

Epoch 2045/4000: 100%|██████████| 1/1 [00:00<00:00, 21.31it/s]

epoch: 2044, beta = 0.000097, Train MSE: 0.006635, Train CE:0.011782, Train KL:8.759283, Val MSE:0.010338, Val CE:0.043411, Train ACC:1.000000, Val ACC:0.993750

Epoch 2046/4000: 100%|██████████| 1/1 [00:00<00:00, 21.42it/s]

epoch: 2045, beta = 0.000097, Train MSE: 0.006651, Train CE:0.011783, Train KL:8.759326, Val MSE:0.010316, Val CE:0.043513, Train ACC:1.000000, Val ACC:0.993750

Epoch 2047/4000: 100%|██████████| 1/1 [00:00<00:00, 19.11it/s]

epoch: 2046, beta = 0.000097, Train MSE: 0.006636, Train CE:0.011784, Train KL:8.759372, Val MSE:0.010328, Val CE:0.043567, Train ACC:1.000000, Val ACC:0.993750

Epoch 2048/4000: 100%|██████████| 1/1 [00:00<00:00, 22.20it/s]

Learning rate updated: 8.478036692943835e-06
epoch: 2047, beta = 0.000097, Train MSE: 0.006641, Train CE:0.011771, Train KL:8.759416, Val MSE:0.010335, Val CE:0.043711, Train ACC:1.000000, Val ACC:0.993750

Epoch 2049/4000: 100%|██████████| 1/1 [00:00<00:00, 23.17it/s]

epoch: 2048, beta = 0.000097, Train MSE: 0.006639, Train CE:0.011782, Train KL:8.759456, Val MSE:0.010314, Val CE:0.043421, Train ACC:1.000000, Val ACC:0.993750

Epoch 2050/4000: 100%|██████████| 1/1 [00:00<00:00, 25.72it/s]

epoch: 2049, beta = 0.000097, Train MSE: 0.006640, Train CE:0.011781, Train KL:8.759491, Val MSE:0.010328, Val CE:0.043338, Train ACC:1.000000, Val ACC:0.993750

Epoch 2051/4000: 100%|██████████| 1/1 [00:00<00:00, 25.73it/s]

epoch: 2050, beta = 0.000097, Train MSE: 0.006645, Train CE:0.011777, Train KL:8.759526, Val MSE:0.010326, Val CE:0.043470, Train ACC:1.000000, Val ACC:0.993750

Epoch 2052/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 2051, beta = 0.000097, Train MSE: 0.006643, Train CE:0.011774, Train KL:8.759563, Val MSE:0.010315, Val CE:0.043220, Train ACC:1.000000, Val ACC:0.993750

Epoch 2053/4000: 100%|██████████| 1/1 [00:00<00:00, 23.80it/s]

epoch: 2052, beta = 0.000097, Train MSE: 0.006633, Train CE:0.011776, Train KL:8.759599, Val MSE:0.010348, Val CE:0.043592, Train ACC:1.000000, Val ACC:0.993750

Epoch 2054/4000: 100%|██████████| 1/1 [00:00<00:00, 25.38it/s]

epoch: 2053, beta = 0.000097, Train MSE: 0.006642, Train CE:0.011778, Train KL:8.759635, Val MSE:0.010346, Val CE:0.043360, Train ACC:1.000000, Val ACC:0.993750

Epoch 2055/4000: 100%|██████████| 1/1 [00:00<00:00, 23.02it/s]

epoch: 2054, beta = 0.000097, Train MSE: 0.006642, Train CE:0.011778, Train KL:8.759677, Val MSE:0.010341, Val CE:0.043326, Train ACC:1.000000, Val ACC:0.993750

Epoch 2056/4000: 100%|██████████| 1/1 [00:00<00:00, 23.39it/s]

epoch: 2055, beta = 0.000097, Train MSE: 0.006635, Train CE:0.011778, Train KL:8.759720, Val MSE:0.010338, Val CE:0.043491, Train ACC:1.000000, Val ACC:0.993750

Epoch 2057/4000: 100%|██████████| 1/1 [00:00<00:00, 24.72it/s]

epoch: 2056, beta = 0.000097, Train MSE: 0.006640, Train CE:0.011774, Train KL:8.759766, Val MSE:0.010311, Val CE:0.043558, Train ACC:1.000000, Val ACC:0.993750

Epoch 2058/4000: 100%|██████████| 1/1 [00:00<00:00, 24.23it/s]

epoch: 2057, beta = 0.000097, Train MSE: 0.006643, Train CE:0.011770, Train KL:8.759810, Val MSE:0.010343, Val CE:0.043605, Train ACC:1.000000, Val ACC:0.993750

Epoch 2059/4000: 100%|██████████| 1/1 [00:00<00:00, 21.08it/s]

Learning rate updated: 8.054134858296643e-06
epoch: 2058, beta = 0.000097, Train MSE: 0.006628, Train CE:0.011773, Train KL:8.759852, Val MSE:0.010321, Val CE:0.043400, Train ACC:1.000000, Val ACC:0.993750

Epoch 2060/4000: 100%|██████████| 1/1 [00:00<00:00, 24.04it/s]

epoch: 2059, beta = 0.000097, Train MSE: 0.006636, Train CE:0.011772, Train KL:8.759893, Val MSE:0.010349, Val CE:0.043330, Train ACC:1.000000, Val ACC:0.993750

Epoch 2061/4000: 100%|██████████| 1/1 [00:00<00:00, 24.16it/s]

epoch: 2060, beta = 0.000097, Train MSE: 0.006634, Train CE:0.011767, Train KL:8.759932, Val MSE:0.010326, Val CE:0.043634, Train ACC:1.000000, Val ACC:0.993750

Epoch 2062/4000: 100%|██████████| 1/1 [00:00<00:00, 26.42it/s]

epoch: 2061, beta = 0.000097, Train MSE: 0.006640, Train CE:0.011769, Train KL:8.759968, Val MSE:0.010332, Val CE:0.043464, Train ACC:1.000000, Val ACC:0.993750

Epoch 2063/4000: 100%|██████████| 1/1 [00:00<00:00, 22.36it/s]

epoch: 2062, beta = 0.000097, Train MSE: 0.006648, Train CE:0.011765, Train KL:8.760005, Val MSE:0.010330, Val CE:0.043434, Train ACC:1.000000, Val ACC:0.993750

Epoch 2064/4000: 100%|██████████| 1/1 [00:00<00:00, 27.51it/s]

epoch: 2063, beta = 0.000097, Train MSE: 0.006639, Train CE:0.011766, Train KL:8.760041, Val MSE:0.010341, Val CE:0.043484, Train ACC:1.000000, Val ACC:0.993750

Epoch 2065/4000: 100%|██████████| 1/1 [00:00<00:00, 23.98it/s]

epoch: 2064, beta = 0.000097, Train MSE: 0.006647, Train CE:0.011768, Train KL:8.760076, Val MSE:0.010297, Val CE:0.043405, Train ACC:1.000000, Val ACC:0.993750

Epoch 2066/4000: 100%|██████████| 1/1 [00:00<00:00, 23.83it/s]

epoch: 2065, beta = 0.000097, Train MSE: 0.006639, Train CE:0.011764, Train KL:8.760109, Val MSE:0.010316, Val CE:0.043531, Train ACC:1.000000, Val ACC:0.993750

Epoch 2067/4000: 100%|██████████| 1/1 [00:00<00:00, 27.39it/s]

epoch: 2066, beta = 0.000097, Train MSE: 0.006641, Train CE:0.011769, Train KL:8.760142, Val MSE:0.010309, Val CE:0.043378, Train ACC:1.000000, Val ACC:0.993750

Epoch 2068/4000: 100%|██████████| 1/1 [00:00<00:00, 27.89it/s]

epoch: 2067, beta = 0.000097, Train MSE: 0.006637, Train CE:0.011762, Train KL:8.760176, Val MSE:0.010328, Val CE:0.043332, Train ACC:1.000000, Val ACC:0.993750

Epoch 2069/4000: 100%|██████████| 1/1 [00:00<00:00, 24.18it/s]

epoch: 2068, beta = 0.000097, Train MSE: 0.006640, Train CE:0.011767, Train KL:8.760210, Val MSE:0.010321, Val CE:0.043606, Train ACC:1.000000, Val ACC:0.993750

Epoch 2070/4000: 100%|██████████| 1/1 [00:00<00:00, 24.32it/s]

Learning rate updated: 7.65142811538181e-06
epoch: 2069, beta = 0.000097, Train MSE: 0.006640, Train CE:0.011769, Train KL:8.760243, Val MSE:0.010354, Val CE:0.043306, Train ACC:1.000000, Val ACC:0.993750

Epoch 2071/4000: 100%|██████████| 1/1 [00:00<00:00, 23.56it/s]

epoch: 2070, beta = 0.000097, Train MSE: 0.006631, Train CE:0.011763, Train KL:8.760282, Val MSE:0.010339, Val CE:0.043274, Train ACC:1.000000, Val ACC:0.993750

Epoch 2072/4000: 100%|██████████| 1/1 [00:00<00:00, 22.79it/s]

epoch: 2071, beta = 0.000097, Train MSE: 0.006638, Train CE:0.011764, Train KL:8.760320, Val MSE:0.010333, Val CE:0.043497, Train ACC:1.000000, Val ACC:0.993750

Epoch 2073/4000: 100%|██████████| 1/1 [00:00<00:00, 24.42it/s]

epoch: 2072, beta = 0.000097, Train MSE: 0.006638, Train CE:0.011765, Train KL:8.760361, Val MSE:0.010295, Val CE:0.043355, Train ACC:1.000000, Val ACC:0.993750

Epoch 2074/4000: 100%|██████████| 1/1 [00:00<00:00, 22.11it/s]

epoch: 2073, beta = 0.000097, Train MSE: 0.006639, Train CE:0.011769, Train KL:8.760401, Val MSE:0.010330, Val CE:0.043385, Train ACC:1.000000, Val ACC:0.993750

Epoch 2075/4000: 100%|██████████| 1/1 [00:00<00:00, 24.03it/s]

epoch: 2074, beta = 0.000097, Train MSE: 0.006644, Train CE:0.011758, Train KL:8.760441, Val MSE:0.010315, Val CE:0.043597, Train ACC:1.000000, Val ACC:0.993750

Epoch 2076/4000: 100%|██████████| 1/1 [00:00<00:00, 22.87it/s]

epoch: 2075, beta = 0.000097, Train MSE: 0.006640, Train CE:0.011762, Train KL:8.760480, Val MSE:0.010337, Val CE:0.043536, Train ACC:1.000000, Val ACC:0.993750

Epoch 2077/4000: 100%|██████████| 1/1 [00:00<00:00, 22.81it/s]

epoch: 2076, beta = 0.000097, Train MSE: 0.006641, Train CE:0.011763, Train KL:8.760515, Val MSE:0.010333, Val CE:0.043355, Train ACC:1.000000, Val ACC:0.993750

Epoch 2078/4000: 100%|██████████| 1/1 [00:00<00:00, 24.62it/s]

epoch: 2077, beta = 0.000097, Train MSE: 0.006630, Train CE:0.011765, Train KL:8.760550, Val MSE:0.010327, Val CE:0.043405, Train ACC:1.000000, Val ACC:0.993750

Epoch 2079/4000: 100%|██████████| 1/1 [00:00<00:00, 21.14it/s]

epoch: 2078, beta = 0.000097, Train MSE: 0.006627, Train CE:0.011761, Train KL:8.760585, Val MSE:0.010326, Val CE:0.043317, Train ACC:1.000000, Val ACC:0.993750

Epoch 2080/4000: 100%|██████████| 1/1 [00:00<00:00, 23.78it/s]

epoch: 2079, beta = 0.000097, Train MSE: 0.006640, Train CE:0.011763, Train KL:8.760617, Val MSE:0.010333, Val CE:0.043475, Train ACC:1.000000, Val ACC:0.993750

Epoch 2081/4000: 100%|██████████| 1/1 [00:00<00:00, 24.64it/s]

Learning rate updated: 7.26885670961272e-06
epoch: 2080, beta = 0.000097, Train MSE: 0.006632, Train CE:0.011765, Train KL:8.760652, Val MSE:0.010313, Val CE:0.043603, Train ACC:1.000000, Val ACC:0.993750

Epoch 2082/4000: 100%|██████████| 1/1 [00:00<00:00, 25.19it/s]

epoch: 2081, beta = 0.000097, Train MSE: 0.006639, Train CE:0.011763, Train KL:8.760682, Val MSE:0.010333, Val CE:0.043415, Train ACC:1.000000, Val ACC:0.993750

Epoch 2083/4000: 100%|██████████| 1/1 [00:00<00:00, 23.30it/s]

epoch: 2082, beta = 0.000097, Train MSE: 0.006641, Train CE:0.011760, Train KL:8.760714, Val MSE:0.010335, Val CE:0.043647, Train ACC:1.000000, Val ACC:0.993750

Epoch 2084/4000: 100%|██████████| 1/1 [00:00<00:00, 24.33it/s]

epoch: 2083, beta = 0.000097, Train MSE: 0.006642, Train CE:0.011760, Train KL:8.760748, Val MSE:0.010344, Val CE:0.043537, Train ACC:1.000000, Val ACC:0.993750

Epoch 2085/4000: 100%|██████████| 1/1 [00:00<00:00, 24.65it/s]

epoch: 2084, beta = 0.000097, Train MSE: 0.006630, Train CE:0.011763, Train KL:8.760780, Val MSE:0.010328, Val CE:0.043377, Train ACC:1.000000, Val ACC:0.993750

Epoch 2086/4000: 100%|██████████| 1/1 [00:00<00:00, 22.53it/s]

epoch: 2085, beta = 0.000097, Train MSE: 0.006642, Train CE:0.011760, Train KL:8.760815, Val MSE:0.010290, Val CE:0.043458, Train ACC:1.000000, Val ACC:0.993750

Epoch 2087/4000: 100%|██████████| 1/1 [00:00<00:00, 22.82it/s]

epoch: 2086, beta = 0.000097, Train MSE: 0.006642, Train CE:0.011750, Train KL:8.760852, Val MSE:0.010318, Val CE:0.043278, Train ACC:1.000000, Val ACC:0.993750

Epoch 2088/4000: 100%|██████████| 1/1 [00:00<00:00, 22.75it/s]

epoch: 2087, beta = 0.000097, Train MSE: 0.006636, Train CE:0.011756, Train KL:8.760890, Val MSE:0.010351, Val CE:0.043590, Train ACC:1.000000, Val ACC:0.993750

Epoch 2089/4000: 100%|██████████| 1/1 [00:00<00:00, 22.10it/s]

epoch: 2088, beta = 0.000097, Train MSE: 0.006631, Train CE:0.011761, Train KL:8.760925, Val MSE:0.010320, Val CE:0.043811, Train ACC:1.000000, Val ACC:0.993750

Epoch 2090/4000: 100%|██████████| 1/1 [00:00<00:00, 20.75it/s]

epoch: 2089, beta = 0.000097, Train MSE: 0.006634, Train CE:0.011757, Train KL:8.760963, Val MSE:0.010335, Val CE:0.043517, Train ACC:1.000000, Val ACC:0.993750

Epoch 2091/4000: 100%|██████████| 1/1 [00:00<00:00, 24.02it/s]

epoch: 2090, beta = 0.000097, Train MSE: 0.006636, Train CE:0.011753, Train KL:8.760998, Val MSE:0.010332, Val CE:0.043631, Train ACC:1.000000, Val ACC:0.993750

Epoch 2092/4000: 100%|██████████| 1/1 [00:00<00:00, 22.41it/s]

Learning rate updated: 6.905413874132084e-06
epoch: 2091, beta = 0.000097, Train MSE: 0.006638, Train CE:0.011752, Train KL:8.761037, Val MSE:0.010317, Val CE:0.043555, Train ACC:1.000000, Val ACC:0.993750

Epoch 2093/4000: 100%|██████████| 1/1 [00:00<00:00, 22.44it/s]

epoch: 2092, beta = 0.000097, Train MSE: 0.006631, Train CE:0.011756, Train KL:8.761073, Val MSE:0.010299, Val CE:0.043431, Train ACC:1.000000, Val ACC:0.993750

Epoch 2094/4000: 100%|██████████| 1/1 [00:00<00:00, 20.73it/s]

epoch: 2093, beta = 0.000097, Train MSE: 0.006636, Train CE:0.011752, Train KL:8.761106, Val MSE:0.010316, Val CE:0.043695, Train ACC:1.000000, Val ACC:0.993750

Epoch 2095/4000: 100%|██████████| 1/1 [00:00<00:00, 24.39it/s]

epoch: 2094, beta = 0.000097, Train MSE: 0.006630, Train CE:0.011751, Train KL:8.761140, Val MSE:0.010338, Val CE:0.043525, Train ACC:1.000000, Val ACC:0.993750

Epoch 2096/4000: 100%|██████████| 1/1 [00:00<00:00, 23.30it/s]

epoch: 2095, beta = 0.000097, Train MSE: 0.006628, Train CE:0.011754, Train KL:8.761172, Val MSE:0.010359, Val CE:0.043531, Train ACC:1.000000, Val ACC:0.993750

Epoch 2097/4000: 100%|██████████| 1/1 [00:00<00:00, 21.51it/s]

epoch: 2096, beta = 0.000097, Train MSE: 0.006631, Train CE:0.011756, Train KL:8.761203, Val MSE:0.010300, Val CE:0.043363, Train ACC:1.000000, Val ACC:0.993750

Epoch 2098/4000: 100%|██████████| 1/1 [00:00<00:00, 22.23it/s]

epoch: 2097, beta = 0.000097, Train MSE: 0.006633, Train CE:0.011756, Train KL:8.761234, Val MSE:0.010311, Val CE:0.043467, Train ACC:1.000000, Val ACC:0.993750

Epoch 2099/4000: 100%|██████████| 1/1 [00:00<00:00, 21.80it/s]

epoch: 2098, beta = 0.000097, Train MSE: 0.006642, Train CE:0.011753, Train KL:8.761267, Val MSE:0.010313, Val CE:0.043485, Train ACC:1.000000, Val ACC:0.993750

Epoch 2100/4000: 100%|██████████| 1/1 [00:00<00:00, 21.51it/s]

epoch: 2099, beta = 0.000097, Train MSE: 0.006626, Train CE:0.011748, Train KL:8.761301, Val MSE:0.010305, Val CE:0.043349, Train ACC:1.000000, Val ACC:0.993750

Epoch 2101/4000: 100%|██████████| 1/1 [00:00<00:00, 26.45it/s]

epoch: 2100, beta = 0.000097, Train MSE: 0.006632, Train CE:0.011756, Train KL:8.761333, Val MSE:0.010293, Val CE:0.043302, Train ACC:1.000000, Val ACC:0.993750

Epoch 2102/4000: 100%|██████████| 1/1 [00:00<00:00, 23.74it/s]

epoch: 2101, beta = 0.000097, Train MSE: 0.006633, Train CE:0.011754, Train KL:8.761364, Val MSE:0.010312, Val CE:0.043370, Train ACC:1.000000, Val ACC:0.993750

Epoch 2103/4000: 100%|██████████| 1/1 [00:00<00:00, 23.63it/s]

Learning rate updated: 6.5601431804254795e-06
epoch: 2102, beta = 0.000097, Train MSE: 0.006637, Train CE:0.011748, Train KL:8.761395, Val MSE:0.010302, Val CE:0.043696, Train ACC:1.000000, Val ACC:0.993750

Epoch 2104/4000: 100%|██████████| 1/1 [00:00<00:00, 23.03it/s]

epoch: 2103, beta = 0.000097, Train MSE: 0.006635, Train CE:0.011750, Train KL:8.761429, Val MSE:0.010314, Val CE:0.043346, Train ACC:1.000000, Val ACC:0.993750

Epoch 2105/4000: 100%|██████████| 1/1 [00:00<00:00, 23.36it/s]

epoch: 2104, beta = 0.000097, Train MSE: 0.006641, Train CE:0.011747, Train KL:8.761463, Val MSE:0.010349, Val CE:0.043451, Train ACC:1.000000, Val ACC:0.993750

Epoch 2106/4000: 100%|██████████| 1/1 [00:00<00:00, 20.94it/s]

epoch: 2105, beta = 0.000097, Train MSE: 0.006640, Train CE:0.011750, Train KL:8.761498, Val MSE:0.010342, Val CE:0.043235, Train ACC:1.000000, Val ACC:0.993750

Epoch 2107/4000: 100%|██████████| 1/1 [00:00<00:00, 23.57it/s]

epoch: 2106, beta = 0.000097, Train MSE: 0.006626, Train CE:0.011746, Train KL:8.761536, Val MSE:0.010313, Val CE:0.043421, Train ACC:1.000000, Val ACC:0.993750

Epoch 2108/4000: 100%|██████████| 1/1 [00:00<00:00, 23.99it/s]

epoch: 2107, beta = 0.000097, Train MSE: 0.006634, Train CE:0.011746, Train KL:8.761571, Val MSE:0.010325, Val CE:0.043388, Train ACC:1.000000, Val ACC:0.993750

Epoch 2109/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 2108, beta = 0.000097, Train MSE: 0.006640, Train CE:0.011745, Train KL:8.761605, Val MSE:0.010303, Val CE:0.043616, Train ACC:1.000000, Val ACC:0.993750

Epoch 2110/4000: 100%|██████████| 1/1 [00:00<00:00, 23.57it/s]

epoch: 2109, beta = 0.000097, Train MSE: 0.006627, Train CE:0.011742, Train KL:8.761642, Val MSE:0.010284, Val CE:0.043401, Train ACC:1.000000, Val ACC:0.993750

Epoch 2111/4000: 100%|██████████| 1/1 [00:00<00:00, 27.63it/s]

epoch: 2110, beta = 0.000097, Train MSE: 0.006627, Train CE:0.011742, Train KL:8.761680, Val MSE:0.010322, Val CE:0.043553, Train ACC:1.000000, Val ACC:0.993750

Epoch 2112/4000: 100%|██████████| 1/1 [00:00<00:00, 24.35it/s]

epoch: 2111, beta = 0.000097, Train MSE: 0.006621, Train CE:0.011749, Train KL:8.761713, Val MSE:0.010297, Val CE:0.043595, Train ACC:1.000000, Val ACC:0.993750

Epoch 2113/4000: 100%|██████████| 1/1 [00:00<00:00, 24.55it/s]

epoch: 2112, beta = 0.000097, Train MSE: 0.006640, Train CE:0.011747, Train KL:8.761744, Val MSE:0.010298, Val CE:0.043493, Train ACC:1.000000, Val ACC:0.993750

Epoch 2114/4000: 100%|██████████| 1/1 [00:00<00:00, 24.04it/s]

Learning rate updated: 6.232136021404205e-06
epoch: 2113, beta = 0.000097, Train MSE: 0.006638, Train CE:0.011749, Train KL:8.761775, Val MSE:0.010298, Val CE:0.043558, Train ACC:1.000000, Val ACC:0.993750

Epoch 2115/4000: 100%|██████████| 1/1 [00:00<00:00, 22.76it/s]

epoch: 2114, beta = 0.000097, Train MSE: 0.006636, Train CE:0.011746, Train KL:8.761806, Val MSE:0.010310, Val CE:0.043758, Train ACC:1.000000, Val ACC:0.993750

Epoch 2116/4000: 100%|██████████| 1/1 [00:00<00:00, 24.57it/s]

epoch: 2115, beta = 0.000097, Train MSE: 0.006629, Train CE:0.011742, Train KL:8.761832, Val MSE:0.010313, Val CE:0.043597, Train ACC:1.000000, Val ACC:0.993750

Epoch 2117/4000: 100%|██████████| 1/1 [00:00<00:00, 22.81it/s]

epoch: 2116, beta = 0.000097, Train MSE: 0.006625, Train CE:0.011746, Train KL:8.761860, Val MSE:0.010321, Val CE:0.043512, Train ACC:1.000000, Val ACC:0.993750

Epoch 2118/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 2117, beta = 0.000097, Train MSE: 0.006630, Train CE:0.011747, Train KL:8.761888, Val MSE:0.010316, Val CE:0.043477, Train ACC:1.000000, Val ACC:0.993750

Epoch 2119/4000: 100%|██████████| 1/1 [00:00<00:00, 24.11it/s]

epoch: 2118, beta = 0.000097, Train MSE: 0.006628, Train CE:0.011742, Train KL:8.761917, Val MSE:0.010316, Val CE:0.043429, Train ACC:1.000000, Val ACC:0.993750

Epoch 2120/4000: 100%|██████████| 1/1 [00:00<00:00, 23.94it/s]

epoch: 2119, beta = 0.000097, Train MSE: 0.006626, Train CE:0.011740, Train KL:8.761945, Val MSE:0.010342, Val CE:0.043485, Train ACC:1.000000, Val ACC:0.993750

Epoch 2121/4000: 100%|██████████| 1/1 [00:00<00:00, 23.99it/s]

epoch: 2120, beta = 0.000097, Train MSE: 0.006629, Train CE:0.011743, Train KL:8.761972, Val MSE:0.010289, Val CE:0.043347, Train ACC:1.000000, Val ACC:0.993750

Epoch 2122/4000: 100%|██████████| 1/1 [00:00<00:00, 24.63it/s]

epoch: 2121, beta = 0.000097, Train MSE: 0.006628, Train CE:0.011735, Train KL:8.762000, Val MSE:0.010303, Val CE:0.043256, Train ACC:1.000000, Val ACC:0.993750

Epoch 2123/4000: 100%|██████████| 1/1 [00:00<00:00, 23.98it/s]

epoch: 2122, beta = 0.000097, Train MSE: 0.006638, Train CE:0.011744, Train KL:8.762030, Val MSE:0.010272, Val CE:0.043564, Train ACC:1.000000, Val ACC:0.993750

Epoch 2124/4000: 100%|██████████| 1/1 [00:00<00:00, 24.65it/s]

epoch: 2123, beta = 0.000097, Train MSE: 0.006632, Train CE:0.011741, Train KL:8.762059, Val MSE:0.010314, Val CE:0.043412, Train ACC:1.000000, Val ACC:0.993750

Epoch 2125/4000: 100%|██████████| 1/1 [00:00<00:00, 24.80it/s]

Learning rate updated: 5.920529220333994e-06
epoch: 2124, beta = 0.000097, Train MSE: 0.006630, Train CE:0.011739, Train KL:8.762091, Val MSE:0.010302, Val CE:0.043362, Train ACC:1.000000, Val ACC:0.993750

Epoch 2126/4000: 100%|██████████| 1/1 [00:00<00:00, 23.84it/s]

epoch: 2125, beta = 0.000097, Train MSE: 0.006639, Train CE:0.011740, Train KL:8.762123, Val MSE:0.010328, Val CE:0.043659, Train ACC:1.000000, Val ACC:0.993750

Epoch 2127/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 2126, beta = 0.000097, Train MSE: 0.006625, Train CE:0.011742, Train KL:8.762154, Val MSE:0.010303, Val CE:0.043471, Train ACC:1.000000, Val ACC:0.993750

Epoch 2128/4000: 100%|██████████| 1/1 [00:00<00:00, 15.66it/s]

epoch: 2127, beta = 0.000097, Train MSE: 0.006634, Train CE:0.011746, Train KL:8.762186, Val MSE:0.010317, Val CE:0.043528, Train ACC:1.000000, Val ACC:0.993750

Epoch 2129/4000: 100%|██████████| 1/1 [00:00<00:00, 22.05it/s]

epoch: 2128, beta = 0.000097, Train MSE: 0.006647, Train CE:0.011731, Train KL:8.762219, Val MSE:0.010304, Val CE:0.043447, Train ACC:1.000000, Val ACC:0.993750

Epoch 2130/4000: 100%|██████████| 1/1 [00:00<00:00, 21.50it/s]

epoch: 2129, beta = 0.000097, Train MSE: 0.006628, Train CE:0.011734, Train KL:8.762252, Val MSE:0.010325, Val CE:0.043445, Train ACC:1.000000, Val ACC:0.993750

Epoch 2131/4000: 100%|██████████| 1/1 [00:00<00:00, 22.19it/s]

epoch: 2130, beta = 0.000097, Train MSE: 0.006635, Train CE:0.011737, Train KL:8.762285, Val MSE:0.010323, Val CE:0.043540, Train ACC:1.000000, Val ACC:0.993750

Epoch 2132/4000: 100%|██████████| 1/1 [00:00<00:00, 23.16it/s]

epoch: 2131, beta = 0.000097, Train MSE: 0.006627, Train CE:0.011736, Train KL:8.762316, Val MSE:0.010316, Val CE:0.043506, Train ACC:1.000000, Val ACC:0.993750

Epoch 2133/4000: 100%|██████████| 1/1 [00:00<00:00, 23.94it/s]

epoch: 2132, beta = 0.000097, Train MSE: 0.006627, Train CE:0.011730, Train KL:8.762344, Val MSE:0.010339, Val CE:0.043647, Train ACC:1.000000, Val ACC:0.993750

Epoch 2134/4000: 100%|██████████| 1/1 [00:00<00:00, 23.82it/s]

epoch: 2133, beta = 0.000097, Train MSE: 0.006632, Train CE:0.011728, Train KL:8.762376, Val MSE:0.010300, Val CE:0.043644, Train ACC:1.000000, Val ACC:0.993750

Epoch 2135/4000: 100%|██████████| 1/1 [00:00<00:00, 24.87it/s]

epoch: 2134, beta = 0.000097, Train MSE: 0.006625, Train CE:0.011733, Train KL:8.762407, Val MSE:0.010341, Val CE:0.043464, Train ACC:1.000000, Val ACC:0.993229

Epoch 2136/4000: 100%|██████████| 1/1 [00:00<00:00, 23.99it/s]

Learning rate updated: 5.624502759317295e-06
epoch: 2135, beta = 0.000097, Train MSE: 0.006623, Train CE:0.011728, Train KL:8.762436, Val MSE:0.010333, Val CE:0.043674, Train ACC:1.000000, Val ACC:0.993750

Epoch 2137/4000: 100%|██████████| 1/1 [00:00<00:00, 23.27it/s]

epoch: 2136, beta = 0.000097, Train MSE: 0.006626, Train CE:0.011736, Train KL:8.762464, Val MSE:0.010290, Val CE:0.043510, Train ACC:1.000000, Val ACC:0.993750

Epoch 2138/4000: 100%|██████████| 1/1 [00:00<00:00, 24.14it/s]

epoch: 2137, beta = 0.000097, Train MSE: 0.006637, Train CE:0.011727, Train KL:8.762487, Val MSE:0.010310, Val CE:0.043624, Train ACC:1.000000, Val ACC:0.993750

Epoch 2139/4000: 100%|██████████| 1/1 [00:00<00:00, 24.97it/s]

epoch: 2138, beta = 0.000097, Train MSE: 0.006626, Train CE:0.011732, Train KL:8.762513, Val MSE:0.010310, Val CE:0.043362, Train ACC:1.000000, Val ACC:0.993750

Epoch 2140/4000: 100%|██████████| 1/1 [00:00<00:00, 23.93it/s]

epoch: 2139, beta = 0.000097, Train MSE: 0.006634, Train CE:0.011733, Train KL:8.762537, Val MSE:0.010303, Val CE:0.043669, Train ACC:1.000000, Val ACC:0.993750

Epoch 2141/4000: 100%|██████████| 1/1 [00:00<00:00, 23.76it/s]

epoch: 2140, beta = 0.000097, Train MSE: 0.006630, Train CE:0.011735, Train KL:8.762564, Val MSE:0.010335, Val CE:0.043652, Train ACC:1.000000, Val ACC:0.993750

Epoch 2142/4000: 100%|██████████| 1/1 [00:00<00:00, 23.96it/s]

epoch: 2141, beta = 0.000097, Train MSE: 0.006626, Train CE:0.011738, Train KL:8.762590, Val MSE:0.010306, Val CE:0.043451, Train ACC:1.000000, Val ACC:0.993750

Epoch 2143/4000: 100%|██████████| 1/1 [00:00<00:00, 24.68it/s]

epoch: 2142, beta = 0.000097, Train MSE: 0.006629, Train CE:0.011731, Train KL:8.762618, Val MSE:0.010306, Val CE:0.043618, Train ACC:1.000000, Val ACC:0.993750

Epoch 2144/4000: 100%|██████████| 1/1 [00:00<00:00, 24.02it/s]

epoch: 2143, beta = 0.000097, Train MSE: 0.006627, Train CE:0.011727, Train KL:8.762648, Val MSE:0.010303, Val CE:0.043573, Train ACC:1.000000, Val ACC:0.993750

Epoch 2145/4000: 100%|██████████| 1/1 [00:00<00:00, 24.17it/s]

epoch: 2144, beta = 0.000097, Train MSE: 0.006629, Train CE:0.011734, Train KL:8.762677, Val MSE:0.010306, Val CE:0.043596, Train ACC:1.000000, Val ACC:0.993750

Epoch 2146/4000: 100%|██████████| 1/1 [00:00<00:00, 22.32it/s]

epoch: 2145, beta = 0.000097, Train MSE: 0.006625, Train CE:0.011730, Train KL:8.762708, Val MSE:0.010324, Val CE:0.043412, Train ACC:1.000000, Val ACC:0.993750

Epoch 2147/4000: 100%|██████████| 1/1 [00:00<00:00, 20.49it/s]

Learning rate updated: 5.34327762135143e-06
epoch: 2146, beta = 0.000097, Train MSE: 0.006629, Train CE:0.011729, Train KL:8.762736, Val MSE:0.010275, Val CE:0.043498, Train ACC:1.000000, Val ACC:0.993750

Epoch 2148/4000: 100%|██████████| 1/1 [00:00<00:00, 21.01it/s]

epoch: 2147, beta = 0.000097, Train MSE: 0.006627, Train CE:0.011726, Train KL:8.762766, Val MSE:0.010330, Val CE:0.043581, Train ACC:1.000000, Val ACC:0.993750

Epoch 2149/4000: 100%|██████████| 1/1 [00:00<00:00, 24.22it/s]

epoch: 2148, beta = 0.000097, Train MSE: 0.006636, Train CE:0.011731, Train KL:8.762794, Val MSE:0.010336, Val CE:0.043511, Train ACC:1.000000, Val ACC:0.993750

Epoch 2150/4000: 100%|██████████| 1/1 [00:00<00:00, 24.26it/s]

epoch: 2149, beta = 0.000097, Train MSE: 0.006624, Train CE:0.011727, Train KL:8.762825, Val MSE:0.010307, Val CE:0.043710, Train ACC:1.000000, Val ACC:0.993750

Epoch 2151/4000: 100%|██████████| 1/1 [00:00<00:00, 22.55it/s]

epoch: 2150, beta = 0.000097, Train MSE: 0.006623, Train CE:0.011722, Train KL:8.762854, Val MSE:0.010285, Val CE:0.043640, Train ACC:1.000000, Val ACC:0.993750

Epoch 2152/4000: 100%|██████████| 1/1 [00:00<00:00, 22.42it/s]

epoch: 2151, beta = 0.000097, Train MSE: 0.006628, Train CE:0.011721, Train KL:8.762881, Val MSE:0.010322, Val CE:0.043527, Train ACC:1.000000, Val ACC:0.993750

Epoch 2153/4000: 100%|██████████| 1/1 [00:00<00:00, 22.74it/s]

epoch: 2152, beta = 0.000097, Train MSE: 0.006633, Train CE:0.011728, Train KL:8.762909, Val MSE:0.010329, Val CE:0.043551, Train ACC:1.000000, Val ACC:0.993750

Epoch 2154/4000: 100%|██████████| 1/1 [00:00<00:00, 23.79it/s]

epoch: 2153, beta = 0.000097, Train MSE: 0.006625, Train CE:0.011722, Train KL:8.762935, Val MSE:0.010326, Val CE:0.043320, Train ACC:1.000000, Val ACC:0.993750

Epoch 2155/4000: 100%|██████████| 1/1 [00:00<00:00, 23.99it/s]

epoch: 2154, beta = 0.000097, Train MSE: 0.006629, Train CE:0.011720, Train KL:8.762961, Val MSE:0.010307, Val CE:0.043354, Train ACC:1.000000, Val ACC:0.993750

Epoch 2156/4000: 100%|██████████| 1/1 [00:00<00:00, 23.73it/s]

epoch: 2155, beta = 0.000097, Train MSE: 0.006631, Train CE:0.011721, Train KL:8.762986, Val MSE:0.010280, Val CE:0.043508, Train ACC:1.000000, Val ACC:0.993750

Epoch 2157/4000: 100%|██████████| 1/1 [00:00<00:00, 23.21it/s]

epoch: 2156, beta = 0.000097, Train MSE: 0.006623, Train CE:0.011726, Train KL:8.763013, Val MSE:0.010309, Val CE:0.043482, Train ACC:1.000000, Val ACC:0.993750

Epoch 2158/4000: 100%|██████████| 1/1 [00:00<00:00, 23.33it/s]

Learning rate updated: 5.076113740283858e-06
epoch: 2157, beta = 0.000097, Train MSE: 0.006625, Train CE:0.011728, Train KL:8.763039, Val MSE:0.010300, Val CE:0.043503, Train ACC:1.000000, Val ACC:0.993750

Epoch 2159/4000: 100%|██████████| 1/1 [00:00<00:00, 22.96it/s]

epoch: 2158, beta = 0.000097, Train MSE: 0.006620, Train CE:0.011723, Train KL:8.763064, Val MSE:0.010327, Val CE:0.043454, Train ACC:1.000000, Val ACC:0.993750

Epoch 2160/4000: 100%|██████████| 1/1 [00:00<00:00, 27.43it/s]

epoch: 2159, beta = 0.000097, Train MSE: 0.006636, Train CE:0.011722, Train KL:8.763090, Val MSE:0.010312, Val CE:0.043430, Train ACC:1.000000, Val ACC:0.993750

Epoch 2161/4000: 100%|██████████| 1/1 [00:00<00:00, 20.57it/s]

epoch: 2160, beta = 0.000097, Train MSE: 0.006625, Train CE:0.011721, Train KL:8.763117, Val MSE:0.010294, Val CE:0.043458, Train ACC:1.000000, Val ACC:0.993750

Epoch 2162/4000: 100%|██████████| 1/1 [00:00<00:00, 23.62it/s]

epoch: 2161, beta = 0.000097, Train MSE: 0.006630, Train CE:0.011717, Train KL:8.763144, Val MSE:0.010301, Val CE:0.043280, Train ACC:1.000000, Val ACC:0.993750

Epoch 2163/4000: 100%|██████████| 1/1 [00:00<00:00, 23.80it/s]

epoch: 2162, beta = 0.000097, Train MSE: 0.006629, Train CE:0.011720, Train KL:8.763167, Val MSE:0.010283, Val CE:0.043273, Train ACC:1.000000, Val ACC:0.993750

Epoch 2164/4000: 100%|██████████| 1/1 [00:00<00:00, 23.11it/s]

epoch: 2163, beta = 0.000097, Train MSE: 0.006627, Train CE:0.011721, Train KL:8.763191, Val MSE:0.010304, Val CE:0.043425, Train ACC:1.000000, Val ACC:0.993750

Epoch 2165/4000: 100%|██████████| 1/1 [00:00<00:00, 22.63it/s]

epoch: 2164, beta = 0.000097, Train MSE: 0.006623, Train CE:0.011722, Train KL:8.763214, Val MSE:0.010322, Val CE:0.043275, Train ACC:1.000000, Val ACC:0.993750

Epoch 2166/4000: 100%|██████████| 1/1 [00:00<00:00, 19.22it/s]

epoch: 2165, beta = 0.000097, Train MSE: 0.006632, Train CE:0.011721, Train KL:8.763240, Val MSE:0.010300, Val CE:0.043482, Train ACC:1.000000, Val ACC:0.993750

Epoch 2167/4000: 100%|██████████| 1/1 [00:00<00:00, 21.99it/s]

epoch: 2166, beta = 0.000097, Train MSE: 0.006631, Train CE:0.011726, Train KL:8.763263, Val MSE:0.010302, Val CE:0.043407, Train ACC:1.000000, Val ACC:0.993750

Epoch 2168/4000: 100%|██████████| 1/1 [00:00<00:00, 23.19it/s]

epoch: 2167, beta = 0.000097, Train MSE: 0.006632, Train CE:0.011715, Train KL:8.763290, Val MSE:0.010298, Val CE:0.043462, Train ACC:1.000000, Val ACC:0.993750

Epoch 2169/4000: 100%|██████████| 1/1 [00:00<00:00, 24.41it/s]

Learning rate updated: 4.8223080532696655e-06
epoch: 2168, beta = 0.000097, Train MSE: 0.006632, Train CE:0.011722, Train KL:8.763314, Val MSE:0.010300, Val CE:0.043504, Train ACC:1.000000, Val ACC:0.993750

Epoch 2170/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 2169, beta = 0.000097, Train MSE: 0.006621, Train CE:0.011722, Train KL:8.763338, Val MSE:0.010281, Val CE:0.043683, Train ACC:1.000000, Val ACC:0.993229

Epoch 2171/4000: 100%|██████████| 1/1 [00:00<00:00, 24.19it/s]

epoch: 2170, beta = 0.000097, Train MSE: 0.006625, Train CE:0.011715, Train KL:8.763361, Val MSE:0.010311, Val CE:0.043376, Train ACC:1.000000, Val ACC:0.993750

Epoch 2172/4000: 100%|██████████| 1/1 [00:00<00:00, 24.11it/s]

epoch: 2171, beta = 0.000097, Train MSE: 0.006632, Train CE:0.011721, Train KL:8.763382, Val MSE:0.010317, Val CE:0.043564, Train ACC:1.000000, Val ACC:0.993750

Epoch 2173/4000: 100%|██████████| 1/1 [00:00<00:00, 24.01it/s]

epoch: 2172, beta = 0.000097, Train MSE: 0.006620, Train CE:0.011725, Train KL:8.763405, Val MSE:0.010313, Val CE:0.043649, Train ACC:1.000000, Val ACC:0.993750

Epoch 2174/4000: 100%|██████████| 1/1 [00:00<00:00, 23.74it/s]

epoch: 2173, beta = 0.000097, Train MSE: 0.006629, Train CE:0.011715, Train KL:8.763429, Val MSE:0.010318, Val CE:0.043560, Train ACC:1.000000, Val ACC:0.993750

Epoch 2175/4000: 100%|██████████| 1/1 [00:00<00:00, 23.91it/s]

epoch: 2174, beta = 0.000097, Train MSE: 0.006623, Train CE:0.011714, Train KL:8.763450, Val MSE:0.010312, Val CE:0.043576, Train ACC:1.000000, Val ACC:0.993750

Epoch 2176/4000: 100%|██████████| 1/1 [00:00<00:00, 26.60it/s]

epoch: 2175, beta = 0.000097, Train MSE: 0.006632, Train CE:0.011722, Train KL:8.763473, Val MSE:0.010283, Val CE:0.043563, Train ACC:1.000000, Val ACC:0.993750

Epoch 2177/4000: 100%|██████████| 1/1 [00:00<00:00, 23.96it/s]

epoch: 2176, beta = 0.000097, Train MSE: 0.006630, Train CE:0.011719, Train KL:8.763495, Val MSE:0.010301, Val CE:0.043359, Train ACC:1.000000, Val ACC:0.993750

Epoch 2178/4000: 100%|██████████| 1/1 [00:00<00:00, 24.64it/s]

epoch: 2177, beta = 0.000097, Train MSE: 0.006635, Train CE:0.011713, Train KL:8.763518, Val MSE:0.010271, Val CE:0.043378, Train ACC:1.000000, Val ACC:0.993750

Epoch 2179/4000: 100%|██████████| 1/1 [00:00<00:00, 24.44it/s]

epoch: 2178, beta = 0.000097, Train MSE: 0.006624, Train CE:0.011716, Train KL:8.763543, Val MSE:0.010288, Val CE:0.043319, Train ACC:1.000000, Val ACC:0.993750

Epoch 2180/4000: 100%|██████████| 1/1 [00:00<00:00, 23.61it/s]

Learning rate updated: 4.581192650606182e-06
epoch: 2179, beta = 0.000097, Train MSE: 0.006632, Train CE:0.011716, Train KL:8.763568, Val MSE:0.010297, Val CE:0.043557, Train ACC:1.000000, Val ACC:0.993750

Epoch 2181/4000: 100%|██████████| 1/1 [00:00<00:00, 24.43it/s]

epoch: 2180, beta = 0.000097, Train MSE: 0.006628, Train CE:0.011712, Train KL:8.763594, Val MSE:0.010305, Val CE:0.043621, Train ACC:1.000000, Val ACC:0.993750

Epoch 2182/4000: 100%|██████████| 1/1 [00:00<00:00, 24.35it/s]

epoch: 2181, beta = 0.000097, Train MSE: 0.006620, Train CE:0.011713, Train KL:8.763617, Val MSE:0.010324, Val CE:0.043408, Train ACC:1.000000, Val ACC:0.993750

Epoch 2183/4000: 100%|██████████| 1/1 [00:00<00:00, 23.52it/s]

epoch: 2182, beta = 0.000097, Train MSE: 0.006620, Train CE:0.011710, Train KL:8.763639, Val MSE:0.010291, Val CE:0.043412, Train ACC:1.000000, Val ACC:0.993750

Epoch 2184/4000: 100%|██████████| 1/1 [00:00<00:00, 25.00it/s]

epoch: 2183, beta = 0.000097, Train MSE: 0.006624, Train CE:0.011709, Train KL:8.763663, Val MSE:0.010283, Val CE:0.043200, Train ACC:1.000000, Val ACC:0.993750

Epoch 2185/4000: 100%|██████████| 1/1 [00:00<00:00, 18.65it/s]

epoch: 2184, beta = 0.000097, Train MSE: 0.006633, Train CE:0.011716, Train KL:8.763687, Val MSE:0.010286, Val CE:0.043327, Train ACC:1.000000, Val ACC:0.993750

Epoch 2186/4000: 100%|██████████| 1/1 [00:00<00:00, 21.14it/s]

epoch: 2185, beta = 0.000097, Train MSE: 0.006616, Train CE:0.011723, Train KL:8.763711, Val MSE:0.010343, Val CE:0.043367, Train ACC:1.000000, Val ACC:0.993750

Epoch 2187/4000: 100%|██████████| 1/1 [00:00<00:00, 20.98it/s]

epoch: 2186, beta = 0.000097, Train MSE: 0.006620, Train CE:0.011713, Train KL:8.763736, Val MSE:0.010311, Val CE:0.043690, Train ACC:1.000000, Val ACC:0.993750

Epoch 2188/4000: 100%|██████████| 1/1 [00:00<00:00, 23.90it/s]

epoch: 2187, beta = 0.000097, Train MSE: 0.006631, Train CE:0.011709, Train KL:8.763761, Val MSE:0.010306, Val CE:0.043515, Train ACC:1.000000, Val ACC:0.993750

Epoch 2189/4000: 100%|██████████| 1/1 [00:00<00:00, 22.37it/s]

epoch: 2188, beta = 0.000097, Train MSE: 0.006631, Train CE:0.011711, Train KL:8.763786, Val MSE:0.010314, Val CE:0.043503, Train ACC:1.000000, Val ACC:0.993750

Epoch 2190/4000: 100%|██████████| 1/1 [00:00<00:00, 23.82it/s]

epoch: 2189, beta = 0.000097, Train MSE: 0.006629, Train CE:0.011718, Train KL:8.763810, Val MSE:0.010310, Val CE:0.043636, Train ACC:1.000000, Val ACC:0.993750

Epoch 2191/4000: 100%|██████████| 1/1 [00:00<00:00, 26.97it/s]

Learning rate updated: 4.3521330180758725e-06
epoch: 2190, beta = 0.000097, Train MSE: 0.006626, Train CE:0.011708, Train KL:8.763836, Val MSE:0.010303, Val CE:0.043346, Train ACC:1.000000, Val ACC:0.993750

Epoch 2192/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 2191, beta = 0.000097, Train MSE: 0.006627, Train CE:0.011709, Train KL:8.763863, Val MSE:0.010303, Val CE:0.043726, Train ACC:1.000000, Val ACC:0.993750

Epoch 2193/4000: 100%|██████████| 1/1 [00:00<00:00, 23.85it/s]

epoch: 2192, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011709, Train KL:8.763886, Val MSE:0.010309, Val CE:0.043472, Train ACC:1.000000, Val ACC:0.993750

Epoch 2194/4000: 100%|██████████| 1/1 [00:00<00:00, 24.05it/s]

epoch: 2193, beta = 0.000097, Train MSE: 0.006637, Train CE:0.011717, Train KL:8.763910, Val MSE:0.010319, Val CE:0.043236, Train ACC:1.000000, Val ACC:0.993750

Epoch 2195/4000: 100%|██████████| 1/1 [00:00<00:00, 25.70it/s]

epoch: 2194, beta = 0.000097, Train MSE: 0.006627, Train CE:0.011705, Train KL:8.763934, Val MSE:0.010296, Val CE:0.043409, Train ACC:1.000000, Val ACC:0.993750

Epoch 2196/4000: 100%|██████████| 1/1 [00:00<00:00, 23.59it/s]

epoch: 2195, beta = 0.000097, Train MSE: 0.006617, Train CE:0.011711, Train KL:8.763959, Val MSE:0.010337, Val CE:0.043422, Train ACC:1.000000, Val ACC:0.993750

Epoch 2197/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 2196, beta = 0.000097, Train MSE: 0.006627, Train CE:0.011707, Train KL:8.763983, Val MSE:0.010293, Val CE:0.043570, Train ACC:1.000000, Val ACC:0.993750

Epoch 2198/4000: 100%|██████████| 1/1 [00:00<00:00, 24.12it/s]

epoch: 2197, beta = 0.000097, Train MSE: 0.006621, Train CE:0.011716, Train KL:8.764007, Val MSE:0.010299, Val CE:0.043634, Train ACC:1.000000, Val ACC:0.993750

Epoch 2199/4000: 100%|██████████| 1/1 [00:00<00:00, 23.76it/s]

epoch: 2198, beta = 0.000097, Train MSE: 0.006630, Train CE:0.011708, Train KL:8.764032, Val MSE:0.010349, Val CE:0.043341, Train ACC:1.000000, Val ACC:0.993750

Epoch 2200/4000: 100%|██████████| 1/1 [00:00<00:00, 24.65it/s]

epoch: 2199, beta = 0.000097, Train MSE: 0.006618, Train CE:0.011709, Train KL:8.764055, Val MSE:0.010308, Val CE:0.043459, Train ACC:1.000000, Val ACC:0.993750

Epoch 2201/4000: 100%|██████████| 1/1 [00:00<00:00, 26.20it/s]

epoch: 2200, beta = 0.000097, Train MSE: 0.006622, Train CE:0.011708, Train KL:8.764079, Val MSE:0.010342, Val CE:0.043562, Train ACC:1.000000, Val ACC:0.993750

Epoch 2202/4000: 100%|██████████| 1/1 [00:00<00:00, 22.67it/s]

Learning rate updated: 4.1345263671720786e-06
epoch: 2201, beta = 0.000097, Train MSE: 0.006625, Train CE:0.011706, Train KL:8.764101, Val MSE:0.010286, Val CE:0.043418, Train ACC:1.000000, Val ACC:0.993750

Epoch 2203/4000: 100%|██████████| 1/1 [00:00<00:00, 17.35it/s]

epoch: 2202, beta = 0.000097, Train MSE: 0.006619, Train CE:0.011704, Train KL:8.764122, Val MSE:0.010308, Val CE:0.043431, Train ACC:1.000000, Val ACC:0.993750

Epoch 2204/4000: 100%|██████████| 1/1 [00:00<00:00, 23.05it/s]

epoch: 2203, beta = 0.000097, Train MSE: 0.006618, Train CE:0.011706, Train KL:8.764140, Val MSE:0.010308, Val CE:0.043349, Train ACC:1.000000, Val ACC:0.993750

Epoch 2205/4000: 100%|██████████| 1/1 [00:00<00:00, 23.35it/s]

epoch: 2204, beta = 0.000097, Train MSE: 0.006619, Train CE:0.011708, Train KL:8.764159, Val MSE:0.010285, Val CE:0.043472, Train ACC:1.000000, Val ACC:0.993750

Epoch 2206/4000: 100%|██████████| 1/1 [00:00<00:00, 22.38it/s]

epoch: 2205, beta = 0.000097, Train MSE: 0.006631, Train CE:0.011708, Train KL:8.764177, Val MSE:0.010285, Val CE:0.043612, Train ACC:1.000000, Val ACC:0.993750

Epoch 2207/4000: 100%|██████████| 1/1 [00:00<00:00, 20.82it/s]

epoch: 2206, beta = 0.000097, Train MSE: 0.006625, Train CE:0.011708, Train KL:8.764195, Val MSE:0.010306, Val CE:0.043473, Train ACC:1.000000, Val ACC:0.993750

Epoch 2208/4000: 100%|██████████| 1/1 [00:00<00:00, 23.64it/s]

epoch: 2207, beta = 0.000097, Train MSE: 0.006627, Train CE:0.011707, Train KL:8.764214, Val MSE:0.010284, Val CE:0.043331, Train ACC:1.000000, Val ACC:0.993750

Epoch 2209/4000: 100%|██████████| 1/1 [00:00<00:00, 23.91it/s]

epoch: 2208, beta = 0.000097, Train MSE: 0.006622, Train CE:0.011704, Train KL:8.764233, Val MSE:0.010262, Val CE:0.043605, Train ACC:1.000000, Val ACC:0.993750

Epoch 2210/4000: 100%|██████████| 1/1 [00:00<00:00, 23.02it/s]

epoch: 2209, beta = 0.000097, Train MSE: 0.006623, Train CE:0.011700, Train KL:8.764252, Val MSE:0.010319, Val CE:0.043513, Train ACC:1.000000, Val ACC:0.993750

Epoch 2211/4000: 100%|██████████| 1/1 [00:00<00:00, 23.93it/s]

epoch: 2210, beta = 0.000097, Train MSE: 0.006623, Train CE:0.011710, Train KL:8.764273, Val MSE:0.010278, Val CE:0.043398, Train ACC:1.000000, Val ACC:0.993750

Epoch 2212/4000: 100%|██████████| 1/1 [00:00<00:00, 21.85it/s]

epoch: 2211, beta = 0.000097, Train MSE: 0.006620, Train CE:0.011706, Train KL:8.764294, Val MSE:0.010292, Val CE:0.043347, Train ACC:1.000000, Val ACC:0.993750

Epoch 2213/4000: 100%|██████████| 1/1 [00:00<00:00, 25.29it/s]

Learning rate updated: 3.927800048813474e-06
epoch: 2212, beta = 0.000097, Train MSE: 0.006624, Train CE:0.011710, Train KL:8.764313, Val MSE:0.010318, Val CE:0.043422, Train ACC:1.000000, Val ACC:0.993750

Epoch 2214/4000: 100%|██████████| 1/1 [00:00<00:00, 23.96it/s]

epoch: 2213, beta = 0.000097, Train MSE: 0.006630, Train CE:0.011706, Train KL:8.764337, Val MSE:0.010282, Val CE:0.043485, Train ACC:1.000000, Val ACC:0.993750

Epoch 2215/4000: 100%|██████████| 1/1 [00:00<00:00, 23.52it/s]

epoch: 2214, beta = 0.000097, Train MSE: 0.006623, Train CE:0.011699, Train KL:8.764360, Val MSE:0.010303, Val CE:0.043401, Train ACC:1.000000, Val ACC:0.993750

Epoch 2216/4000: 100%|██████████| 1/1 [00:00<00:00, 23.04it/s]

epoch: 2215, beta = 0.000097, Train MSE: 0.006617, Train CE:0.011708, Train KL:8.764384, Val MSE:0.010296, Val CE:0.043226, Train ACC:1.000000, Val ACC:0.993750

Epoch 2217/4000: 100%|██████████| 1/1 [00:00<00:00, 22.16it/s]

epoch: 2216, beta = 0.000097, Train MSE: 0.006618, Train CE:0.011703, Train KL:8.764407, Val MSE:0.010288, Val CE:0.043346, Train ACC:1.000000, Val ACC:0.993750

Epoch 2218/4000: 100%|██████████| 1/1 [00:00<00:00, 21.76it/s]

epoch: 2217, beta = 0.000097, Train MSE: 0.006622, Train CE:0.011701, Train KL:8.764431, Val MSE:0.010309, Val CE:0.043432, Train ACC:1.000000, Val ACC:0.993750

Epoch 2219/4000: 100%|██████████| 1/1 [00:00<00:00, 22.74it/s]

epoch: 2218, beta = 0.000097, Train MSE: 0.006622, Train CE:0.011701, Train KL:8.764454, Val MSE:0.010307, Val CE:0.043535, Train ACC:1.000000, Val ACC:0.993750

Epoch 2220/4000: 100%|██████████| 1/1 [00:00<00:00, 24.09it/s]

epoch: 2219, beta = 0.000097, Train MSE: 0.006622, Train CE:0.011699, Train KL:8.764477, Val MSE:0.010303, Val CE:0.043461, Train ACC:1.000000, Val ACC:0.993750

Epoch 2221/4000: 100%|██████████| 1/1 [00:00<00:00, 24.47it/s]

epoch: 2220, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011702, Train KL:8.764500, Val MSE:0.010293, Val CE:0.043502, Train ACC:1.000000, Val ACC:0.993750

Epoch 2222/4000: 100%|██████████| 1/1 [00:00<00:00, 22.71it/s]

epoch: 2221, beta = 0.000097, Train MSE: 0.006625, Train CE:0.011699, Train KL:8.764521, Val MSE:0.010312, Val CE:0.043580, Train ACC:1.000000, Val ACC:0.993750

Epoch 2223/4000: 100%|██████████| 1/1 [00:00<00:00, 21.94it/s]

epoch: 2222, beta = 0.000097, Train MSE: 0.006621, Train CE:0.011707, Train KL:8.764541, Val MSE:0.010312, Val CE:0.043238, Train ACC:1.000000, Val ACC:0.993750

Epoch 2224/4000: 100%|██████████| 1/1 [00:00<00:00, 21.45it/s]

Learning rate updated: 3.7314100463728006e-06
epoch: 2223, beta = 0.000097, Train MSE: 0.006619, Train CE:0.011701, Train KL:8.764561, Val MSE:0.010289, Val CE:0.043405, Train ACC:1.000000, Val ACC:0.993750

Epoch 2225/4000: 100%|██████████| 1/1 [00:00<00:00, 20.98it/s]

epoch: 2224, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011696, Train KL:8.764579, Val MSE:0.010303, Val CE:0.043286, Train ACC:1.000000, Val ACC:0.993750

Epoch 2226/4000: 100%|██████████| 1/1 [00:00<00:00, 22.72it/s]

epoch: 2225, beta = 0.000097, Train MSE: 0.006623, Train CE:0.011698, Train KL:8.764594, Val MSE:0.010294, Val CE:0.043379, Train ACC:1.000000, Val ACC:0.993750

Epoch 2227/4000: 100%|██████████| 1/1 [00:00<00:00, 23.24it/s]

epoch: 2226, beta = 0.000097, Train MSE: 0.006613, Train CE:0.011699, Train KL:8.764609, Val MSE:0.010324, Val CE:0.043611, Train ACC:1.000000, Val ACC:0.993750

Epoch 2228/4000: 100%|██████████| 1/1 [00:00<00:00, 23.80it/s]

epoch: 2227, beta = 0.000097, Train MSE: 0.006621, Train CE:0.011705, Train KL:8.764624, Val MSE:0.010279, Val CE:0.043496, Train ACC:1.000000, Val ACC:0.993750

Epoch 2229/4000: 100%|██████████| 1/1 [00:00<00:00, 24.61it/s]

epoch: 2228, beta = 0.000097, Train MSE: 0.006631, Train CE:0.011699, Train KL:8.764638, Val MSE:0.010316, Val CE:0.043487, Train ACC:1.000000, Val ACC:0.993750

Epoch 2230/4000: 100%|██████████| 1/1 [00:00<00:00, 26.49it/s]

epoch: 2229, beta = 0.000097, Train MSE: 0.006624, Train CE:0.011702, Train KL:8.764652, Val MSE:0.010312, Val CE:0.043370, Train ACC:1.000000, Val ACC:0.993750

Epoch 2231/4000: 100%|██████████| 1/1 [00:00<00:00, 24.13it/s]

epoch: 2230, beta = 0.000097, Train MSE: 0.006635, Train CE:0.011701, Train KL:8.764669, Val MSE:0.010294, Val CE:0.043429, Train ACC:1.000000, Val ACC:0.993750

Epoch 2232/4000: 100%|██████████| 1/1 [00:00<00:00, 23.01it/s]

epoch: 2231, beta = 0.000097, Train MSE: 0.006619, Train CE:0.011698, Train KL:8.764688, Val MSE:0.010303, Val CE:0.043305, Train ACC:1.000000, Val ACC:0.993750

Epoch 2233/4000: 100%|██████████| 1/1 [00:00<00:00, 24.60it/s]

epoch: 2232, beta = 0.000097, Train MSE: 0.006620, Train CE:0.011695, Train KL:8.764706, Val MSE:0.010328, Val CE:0.043595, Train ACC:1.000000, Val ACC:0.993750

Epoch 2234/4000: 100%|██████████| 1/1 [00:00<00:00, 24.02it/s]

epoch: 2233, beta = 0.000097, Train MSE: 0.006626, Train CE:0.011699, Train KL:8.764725, Val MSE:0.010303, Val CE:0.043334, Train ACC:1.000000, Val ACC:0.993750

Epoch 2235/4000: 100%|██████████| 1/1 [00:00<00:00, 24.69it/s]

Learning rate updated: 3.5448395440541604e-06
epoch: 2234, beta = 0.000097, Train MSE: 0.006624, Train CE:0.011695, Train KL:8.764742, Val MSE:0.010307, Val CE:0.043370, Train ACC:1.000000, Val ACC:0.993750

Epoch 2236/4000: 100%|██████████| 1/1 [00:00<00:00, 23.51it/s]

epoch: 2235, beta = 0.000097, Train MSE: 0.006622, Train CE:0.011700, Train KL:8.764761, Val MSE:0.010280, Val CE:0.043572, Train ACC:1.000000, Val ACC:0.993750

Epoch 2237/4000: 100%|██████████| 1/1 [00:00<00:00, 23.49it/s]

epoch: 2236, beta = 0.000097, Train MSE: 0.006615, Train CE:0.011696, Train KL:8.764781, Val MSE:0.010320, Val CE:0.043622, Train ACC:1.000000, Val ACC:0.993750

Epoch 2238/4000: 100%|██████████| 1/1 [00:00<00:00, 24.92it/s]

epoch: 2237, beta = 0.000097, Train MSE: 0.006615, Train CE:0.011696, Train KL:8.764800, Val MSE:0.010311, Val CE:0.043403, Train ACC:1.000000, Val ACC:0.993750

Epoch 2239/4000: 100%|██████████| 1/1 [00:00<00:00, 23.98it/s]

epoch: 2238, beta = 0.000097, Train MSE: 0.006614, Train CE:0.011699, Train KL:8.764817, Val MSE:0.010258, Val CE:0.043464, Train ACC:1.000000, Val ACC:0.993750

Epoch 2240/4000: 100%|██████████| 1/1 [00:00<00:00, 23.35it/s]

epoch: 2239, beta = 0.000097, Train MSE: 0.006624, Train CE:0.011692, Train KL:8.764836, Val MSE:0.010298, Val CE:0.043569, Train ACC:1.000000, Val ACC:0.993750

Epoch 2241/4000: 100%|██████████| 1/1 [00:00<00:00, 22.90it/s]

epoch: 2240, beta = 0.000097, Train MSE: 0.006621, Train CE:0.011695, Train KL:8.764853, Val MSE:0.010313, Val CE:0.043764, Train ACC:1.000000, Val ACC:0.993750

Epoch 2242/4000: 100%|██████████| 1/1 [00:00<00:00, 23.40it/s]

epoch: 2241, beta = 0.000097, Train MSE: 0.006615, Train CE:0.011697, Train KL:8.764871, Val MSE:0.010302, Val CE:0.043410, Train ACC:1.000000, Val ACC:0.993750

Epoch 2243/4000: 100%|██████████| 1/1 [00:00<00:00, 24.35it/s]

epoch: 2242, beta = 0.000097, Train MSE: 0.006618, Train CE:0.011697, Train KL:8.764890, Val MSE:0.010303, Val CE:0.043373, Train ACC:1.000000, Val ACC:0.993750

Epoch 2244/4000: 100%|██████████| 1/1 [00:00<00:00, 24.10it/s]

epoch: 2243, beta = 0.000097, Train MSE: 0.006626, Train CE:0.011691, Train KL:8.764908, Val MSE:0.010288, Val CE:0.043434, Train ACC:1.000000, Val ACC:0.993750

Epoch 2245/4000: 100%|██████████| 1/1 [00:00<00:00, 23.23it/s]

epoch: 2244, beta = 0.000097, Train MSE: 0.006618, Train CE:0.011694, Train KL:8.764926, Val MSE:0.010276, Val CE:0.043363, Train ACC:1.000000, Val ACC:0.993750

Epoch 2246/4000: 100%|██████████| 1/1 [00:00<00:00, 19.24it/s]

Learning rate updated: 3.3675975668514524e-06
epoch: 2245, beta = 0.000097, Train MSE: 0.006618, Train CE:0.011694, Train KL:8.764946, Val MSE:0.010320, Val CE:0.043578, Train ACC:1.000000, Val ACC:0.993750

Epoch 2247/4000: 100%|██████████| 1/1 [00:00<00:00, 21.75it/s]

epoch: 2246, beta = 0.000097, Train MSE: 0.006618, Train CE:0.011695, Train KL:8.764963, Val MSE:0.010309, Val CE:0.043294, Train ACC:1.000000, Val ACC:0.993750

Epoch 2248/4000: 100%|██████████| 1/1 [00:00<00:00, 21.49it/s]

epoch: 2247, beta = 0.000097, Train MSE: 0.006619, Train CE:0.011694, Train KL:8.764981, Val MSE:0.010313, Val CE:0.043684, Train ACC:1.000000, Val ACC:0.993750

Epoch 2249/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 2248, beta = 0.000097, Train MSE: 0.006623, Train CE:0.011693, Train KL:8.764999, Val MSE:0.010292, Val CE:0.043338, Train ACC:1.000000, Val ACC:0.993750

Epoch 2250/4000: 100%|██████████| 1/1 [00:00<00:00, 24.28it/s]

epoch: 2249, beta = 0.000097, Train MSE: 0.006614, Train CE:0.011698, Train KL:8.765018, Val MSE:0.010325, Val CE:0.043233, Train ACC:1.000000, Val ACC:0.993750

Epoch 2251/4000: 100%|██████████| 1/1 [00:00<00:00, 24.01it/s]

epoch: 2250, beta = 0.000097, Train MSE: 0.006624, Train CE:0.011694, Train KL:8.765035, Val MSE:0.010286, Val CE:0.043547, Train ACC:1.000000, Val ACC:0.993750

Epoch 2252/4000: 100%|██████████| 1/1 [00:00<00:00, 26.59it/s]

epoch: 2251, beta = 0.000097, Train MSE: 0.006619, Train CE:0.011689, Train KL:8.765053, Val MSE:0.010280, Val CE:0.043404, Train ACC:1.000000, Val ACC:0.993750

Epoch 2253/4000: 100%|██████████| 1/1 [00:00<00:00, 21.44it/s]

epoch: 2252, beta = 0.000097, Train MSE: 0.006618, Train CE:0.011695, Train KL:8.765071, Val MSE:0.010323, Val CE:0.043463, Train ACC:1.000000, Val ACC:0.993750

Epoch 2254/4000: 100%|██████████| 1/1 [00:00<00:00, 24.01it/s]

epoch: 2253, beta = 0.000097, Train MSE: 0.006624, Train CE:0.011690, Train KL:8.765087, Val MSE:0.010325, Val CE:0.043287, Train ACC:1.000000, Val ACC:0.993750

Epoch 2255/4000: 100%|██████████| 1/1 [00:00<00:00, 24.69it/s]

epoch: 2254, beta = 0.000097, Train MSE: 0.006624, Train CE:0.011695, Train KL:8.765105, Val MSE:0.010293, Val CE:0.043537, Train ACC:1.000000, Val ACC:0.993750

Epoch 2256/4000: 100%|██████████| 1/1 [00:00<00:00, 25.70it/s]

epoch: 2255, beta = 0.000097, Train MSE: 0.006615, Train CE:0.011689, Train KL:8.765121, Val MSE:0.010325, Val CE:0.043513, Train ACC:1.000000, Val ACC:0.993750

Epoch 2257/4000: 100%|██████████| 1/1 [00:00<00:00, 24.11it/s]

Learning rate updated: 3.1992176885088796e-06
epoch: 2256, beta = 0.000097, Train MSE: 0.006621, Train CE:0.011689, Train KL:8.765139, Val MSE:0.010318, Val CE:0.043784, Train ACC:1.000000, Val ACC:0.993750

Epoch 2258/4000: 100%|██████████| 1/1 [00:00<00:00, 26.25it/s]

epoch: 2257, beta = 0.000097, Train MSE: 0.006624, Train CE:0.011688, Train KL:8.765155, Val MSE:0.010263, Val CE:0.043437, Train ACC:1.000000, Val ACC:0.993750

Epoch 2259/4000: 100%|██████████| 1/1 [00:00<00:00, 22.97it/s]

epoch: 2258, beta = 0.000097, Train MSE: 0.006620, Train CE:0.011692, Train KL:8.765171, Val MSE:0.010292, Val CE:0.043358, Train ACC:1.000000, Val ACC:0.993750

Epoch 2260/4000: 100%|██████████| 1/1 [00:00<00:00, 27.49it/s]

epoch: 2259, beta = 0.000097, Train MSE: 0.006616, Train CE:0.011692, Train KL:8.765185, Val MSE:0.010314, Val CE:0.043564, Train ACC:1.000000, Val ACC:0.993750

Epoch 2261/4000: 100%|██████████| 1/1 [00:00<00:00, 23.97it/s]

epoch: 2260, beta = 0.000097, Train MSE: 0.006622, Train CE:0.011694, Train KL:8.765200, Val MSE:0.010291, Val CE:0.043542, Train ACC:1.000000, Val ACC:0.993750

Epoch 2262/4000: 100%|██████████| 1/1 [00:00<00:00, 24.23it/s]

epoch: 2261, beta = 0.000097, Train MSE: 0.006622, Train CE:0.011687, Train KL:8.765214, Val MSE:0.010254, Val CE:0.043306, Train ACC:1.000000, Val ACC:0.993750

Epoch 2263/4000: 100%|██████████| 1/1 [00:00<00:00, 20.09it/s]

epoch: 2262, beta = 0.000097, Train MSE: 0.006614, Train CE:0.011689, Train KL:8.765228, Val MSE:0.010294, Val CE:0.043370, Train ACC:1.000000, Val ACC:0.993750

Epoch 2264/4000: 100%|██████████| 1/1 [00:00<00:00, 22.58it/s]

epoch: 2263, beta = 0.000097, Train MSE: 0.006615, Train CE:0.011687, Train KL:8.765245, Val MSE:0.010303, Val CE:0.043186, Train ACC:1.000000, Val ACC:0.993750

Epoch 2265/4000: 100%|██████████| 1/1 [00:00<00:00, 21.99it/s]

epoch: 2264, beta = 0.000097, Train MSE: 0.006618, Train CE:0.011693, Train KL:8.765262, Val MSE:0.010288, Val CE:0.043399, Train ACC:1.000000, Val ACC:0.993750

Epoch 2266/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 2265, beta = 0.000097, Train MSE: 0.006623, Train CE:0.011686, Train KL:8.765279, Val MSE:0.010306, Val CE:0.043439, Train ACC:1.000000, Val ACC:0.993750

Epoch 2267/4000: 100%|██████████| 1/1 [00:00<00:00, 23.93it/s]

epoch: 2266, beta = 0.000097, Train MSE: 0.006617, Train CE:0.011691, Train KL:8.765296, Val MSE:0.010303, Val CE:0.043433, Train ACC:1.000000, Val ACC:0.993750

Epoch 2268/4000: 100%|██████████| 1/1 [00:00<00:00, 23.86it/s]

Learning rate updated: 3.0392568040834356e-06
epoch: 2267, beta = 0.000097, Train MSE: 0.006611, Train CE:0.011688, Train KL:8.765313, Val MSE:0.010303, Val CE:0.043258, Train ACC:1.000000, Val ACC:0.993750

Epoch 2269/4000: 100%|██████████| 1/1 [00:00<00:00, 24.74it/s]

epoch: 2268, beta = 0.000097, Train MSE: 0.006623, Train CE:0.011688, Train KL:8.765331, Val MSE:0.010282, Val CE:0.043510, Train ACC:1.000000, Val ACC:0.993750

Epoch 2270/4000: 100%|██████████| 1/1 [00:00<00:00, 24.20it/s]

epoch: 2269, beta = 0.000097, Train MSE: 0.006626, Train CE:0.011688, Train KL:8.765347, Val MSE:0.010283, Val CE:0.043543, Train ACC:1.000000, Val ACC:0.993750

Epoch 2271/4000: 100%|██████████| 1/1 [00:00<00:00, 24.31it/s]

epoch: 2270, beta = 0.000097, Train MSE: 0.006616, Train CE:0.011687, Train KL:8.765365, Val MSE:0.010300, Val CE:0.043435, Train ACC:1.000000, Val ACC:0.993750

Epoch 2272/4000: 100%|██████████| 1/1 [00:00<00:00, 23.61it/s]

epoch: 2271, beta = 0.000097, Train MSE: 0.006624, Train CE:0.011689, Train KL:8.765382, Val MSE:0.010305, Val CE:0.043333, Train ACC:1.000000, Val ACC:0.993750

Epoch 2273/4000: 100%|██████████| 1/1 [00:00<00:00, 24.16it/s]

epoch: 2272, beta = 0.000097, Train MSE: 0.006614, Train CE:0.011684, Train KL:8.765398, Val MSE:0.010285, Val CE:0.043318, Train ACC:1.000000, Val ACC:0.993750

Epoch 2274/4000: 100%|██████████| 1/1 [00:00<00:00, 24.26it/s]

epoch: 2273, beta = 0.000097, Train MSE: 0.006617, Train CE:0.011689, Train KL:8.765414, Val MSE:0.010292, Val CE:0.043356, Train ACC:1.000000, Val ACC:0.993750

Epoch 2275/4000: 100%|██████████| 1/1 [00:00<00:00, 24.81it/s]

epoch: 2274, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011684, Train KL:8.765430, Val MSE:0.010290, Val CE:0.043399, Train ACC:1.000000, Val ACC:0.993750

Epoch 2276/4000: 100%|██████████| 1/1 [00:00<00:00, 24.02it/s]

epoch: 2275, beta = 0.000097, Train MSE: 0.006618, Train CE:0.011687, Train KL:8.765446, Val MSE:0.010302, Val CE:0.043498, Train ACC:1.000000, Val ACC:0.993750

Epoch 2277/4000: 100%|██████████| 1/1 [00:00<00:00, 23.93it/s]

epoch: 2276, beta = 0.000097, Train MSE: 0.006614, Train CE:0.011690, Train KL:8.765463, Val MSE:0.010284, Val CE:0.043356, Train ACC:1.000000, Val ACC:0.993750

Epoch 2278/4000: 100%|██████████| 1/1 [00:00<00:00, 24.05it/s]

epoch: 2277, beta = 0.000097, Train MSE: 0.006619, Train CE:0.011689, Train KL:8.765478, Val MSE:0.010299, Val CE:0.043293, Train ACC:1.000000, Val ACC:0.993750

Epoch 2279/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

Learning rate updated: 2.8872939638792635e-06
epoch: 2278, beta = 0.000097, Train MSE: 0.006627, Train CE:0.011684, Train KL:8.765496, Val MSE:0.010302, Val CE:0.043450, Train ACC:1.000000, Val ACC:0.993750

Epoch 2280/4000: 100%|██████████| 1/1 [00:00<00:00, 24.07it/s]

epoch: 2279, beta = 0.000097, Train MSE: 0.006614, Train CE:0.011688, Train KL:8.765512, Val MSE:0.010270, Val CE:0.043607, Train ACC:1.000000, Val ACC:0.993750

Epoch 2281/4000: 100%|██████████| 1/1 [00:00<00:00, 23.77it/s]

epoch: 2280, beta = 0.000097, Train MSE: 0.006616, Train CE:0.011687, Train KL:8.765525, Val MSE:0.010287, Val CE:0.043429, Train ACC:1.000000, Val ACC:0.993750

Epoch 2282/4000: 100%|██████████| 1/1 [00:00<00:00, 24.03it/s]

epoch: 2281, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011688, Train KL:8.765539, Val MSE:0.010319, Val CE:0.043519, Train ACC:1.000000, Val ACC:0.993750

Epoch 2283/4000: 100%|██████████| 1/1 [00:00<00:00, 20.88it/s]

epoch: 2282, beta = 0.000097, Train MSE: 0.006618, Train CE:0.011689, Train KL:8.765552, Val MSE:0.010324, Val CE:0.043619, Train ACC:1.000000, Val ACC:0.993750

Epoch 2284/4000: 100%|██████████| 1/1 [00:00<00:00, 17.43it/s]

epoch: 2283, beta = 0.000097, Train MSE: 0.006622, Train CE:0.011688, Train KL:8.765565, Val MSE:0.010295, Val CE:0.043655, Train ACC:1.000000, Val ACC:0.993750

Epoch 2285/4000: 100%|██████████| 1/1 [00:00<00:00, 22.76it/s]

epoch: 2284, beta = 0.000097, Train MSE: 0.006615, Train CE:0.011691, Train KL:8.765578, Val MSE:0.010287, Val CE:0.043440, Train ACC:1.000000, Val ACC:0.993750

Epoch 2286/4000: 100%|██████████| 1/1 [00:00<00:00, 23.17it/s]

epoch: 2285, beta = 0.000097, Train MSE: 0.006621, Train CE:0.011687, Train KL:8.765590, Val MSE:0.010320, Val CE:0.043596, Train ACC:1.000000, Val ACC:0.993750

Epoch 2287/4000: 100%|██████████| 1/1 [00:00<00:00, 23.98it/s]

epoch: 2286, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011684, Train KL:8.765604, Val MSE:0.010306, Val CE:0.043539, Train ACC:1.000000, Val ACC:0.993750

Epoch 2288/4000: 100%|██████████| 1/1 [00:00<00:00, 23.07it/s]

epoch: 2287, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011678, Train KL:8.765615, Val MSE:0.010315, Val CE:0.043508, Train ACC:1.000000, Val ACC:0.993750

Epoch 2289/4000: 100%|██████████| 1/1 [00:00<00:00, 23.66it/s]

epoch: 2288, beta = 0.000097, Train MSE: 0.006616, Train CE:0.011686, Train KL:8.765628, Val MSE:0.010278, Val CE:0.043435, Train ACC:1.000000, Val ACC:0.993750

Epoch 2290/4000: 100%|██████████| 1/1 [00:00<00:00, 22.31it/s]

Learning rate updated: 2.7429292656853003e-06
epoch: 2289, beta = 0.000097, Train MSE: 0.006619, Train CE:0.011679, Train KL:8.765641, Val MSE:0.010306, Val CE:0.043242, Train ACC:1.000000, Val ACC:0.993750

Epoch 2291/4000: 100%|██████████| 1/1 [00:00<00:00, 22.65it/s]

epoch: 2290, beta = 0.000097, Train MSE: 0.006615, Train CE:0.011687, Train KL:8.765656, Val MSE:0.010286, Val CE:0.043526, Train ACC:1.000000, Val ACC:0.993750

Epoch 2292/4000: 100%|██████████| 1/1 [00:00<00:00, 23.17it/s]

epoch: 2291, beta = 0.000097, Train MSE: 0.006611, Train CE:0.011684, Train KL:8.765669, Val MSE:0.010297, Val CE:0.043326, Train ACC:1.000000, Val ACC:0.993750

Epoch 2293/4000: 100%|██████████| 1/1 [00:00<00:00, 22.01it/s]

epoch: 2292, beta = 0.000097, Train MSE: 0.006615, Train CE:0.011684, Train KL:8.765682, Val MSE:0.010303, Val CE:0.043449, Train ACC:1.000000, Val ACC:0.993750

Epoch 2294/4000: 100%|██████████| 1/1 [00:00<00:00, 23.65it/s]

epoch: 2293, beta = 0.000097, Train MSE: 0.006615, Train CE:0.011680, Train KL:8.765697, Val MSE:0.010285, Val CE:0.043304, Train ACC:1.000000, Val ACC:0.993750

Epoch 2295/4000: 100%|██████████| 1/1 [00:00<00:00, 24.62it/s]

epoch: 2294, beta = 0.000097, Train MSE: 0.006613, Train CE:0.011681, Train KL:8.765713, Val MSE:0.010303, Val CE:0.043669, Train ACC:1.000000, Val ACC:0.993750

Epoch 2296/4000: 100%|██████████| 1/1 [00:00<00:00, 22.39it/s]

epoch: 2295, beta = 0.000097, Train MSE: 0.006621, Train CE:0.011682, Train KL:8.765727, Val MSE:0.010279, Val CE:0.043549, Train ACC:1.000000, Val ACC:0.993750

Epoch 2297/4000: 100%|██████████| 1/1 [00:00<00:00, 23.31it/s]

epoch: 2296, beta = 0.000097, Train MSE: 0.006613, Train CE:0.011681, Train KL:8.765742, Val MSE:0.010319, Val CE:0.043347, Train ACC:1.000000, Val ACC:0.993750

Epoch 2298/4000: 100%|██████████| 1/1 [00:00<00:00, 20.89it/s]

epoch: 2297, beta = 0.000097, Train MSE: 0.006621, Train CE:0.011679, Train KL:8.765757, Val MSE:0.010246, Val CE:0.043464, Train ACC:1.000000, Val ACC:0.993750

Epoch 2299/4000: 100%|██████████| 1/1 [00:00<00:00, 23.02it/s]

epoch: 2298, beta = 0.000097, Train MSE: 0.006617, Train CE:0.011683, Train KL:8.765771, Val MSE:0.010268, Val CE:0.043409, Train ACC:1.000000, Val ACC:0.993750

Epoch 2300/4000: 100%|██████████| 1/1 [00:00<00:00, 24.01it/s]

epoch: 2299, beta = 0.000097, Train MSE: 0.006618, Train CE:0.011686, Train KL:8.765786, Val MSE:0.010298, Val CE:0.043400, Train ACC:1.000000, Val ACC:0.993750

Epoch 2301/4000: 100%|██████████| 1/1 [00:00<00:00, 25.64it/s]

Learning rate updated: 2.605782802401035e-06
epoch: 2300, beta = 0.000097, Train MSE: 0.006618, Train CE:0.011686, Train KL:8.765800, Val MSE:0.010282, Val CE:0.043603, Train ACC:1.000000, Val ACC:0.993750

Epoch 2302/4000: 100%|██████████| 1/1 [00:00<00:00, 23.65it/s]

epoch: 2301, beta = 0.000097, Train MSE: 0.006616, Train CE:0.011680, Train KL:8.765817, Val MSE:0.010299, Val CE:0.043484, Train ACC:1.000000, Val ACC:0.993750

Epoch 2303/4000: 100%|██████████| 1/1 [00:00<00:00, 24.56it/s]

epoch: 2302, beta = 0.000097, Train MSE: 0.006615, Train CE:0.011681, Train KL:8.765832, Val MSE:0.010297, Val CE:0.043392, Train ACC:1.000000, Val ACC:0.993750

Epoch 2304/4000: 100%|██████████| 1/1 [00:00<00:00, 20.19it/s]

epoch: 2303, beta = 0.000097, Train MSE: 0.006620, Train CE:0.011682, Train KL:8.765847, Val MSE:0.010293, Val CE:0.043535, Train ACC:1.000000, Val ACC:0.993750

Epoch 2305/4000: 100%|██████████| 1/1 [00:00<00:00, 20.52it/s]

epoch: 2304, beta = 0.000097, Train MSE: 0.006614, Train CE:0.011682, Train KL:8.765862, Val MSE:0.010313, Val CE:0.043597, Train ACC:1.000000, Val ACC:0.993750

Epoch 2306/4000: 100%|██████████| 1/1 [00:00<00:00, 23.77it/s]

epoch: 2305, beta = 0.000097, Train MSE: 0.006613, Train CE:0.011679, Train KL:8.765878, Val MSE:0.010292, Val CE:0.043356, Train ACC:1.000000, Val ACC:0.993750

Epoch 2307/4000: 100%|██████████| 1/1 [00:00<00:00, 24.33it/s]

epoch: 2306, beta = 0.000097, Train MSE: 0.006621, Train CE:0.011679, Train KL:8.765893, Val MSE:0.010314, Val CE:0.043360, Train ACC:1.000000, Val ACC:0.993750

Epoch 2308/4000: 100%|██████████| 1/1 [00:00<00:00, 24.01it/s]

epoch: 2307, beta = 0.000097, Train MSE: 0.006611, Train CE:0.011679, Train KL:8.765908, Val MSE:0.010291, Val CE:0.043528, Train ACC:1.000000, Val ACC:0.993750

Epoch 2309/4000: 100%|██████████| 1/1 [00:00<00:00, 23.84it/s]

epoch: 2308, beta = 0.000097, Train MSE: 0.006619, Train CE:0.011685, Train KL:8.765924, Val MSE:0.010313, Val CE:0.043260, Train ACC:1.000000, Val ACC:0.993750

Epoch 2310/4000: 100%|██████████| 1/1 [00:00<00:00, 23.73it/s]

epoch: 2309, beta = 0.000097, Train MSE: 0.006616, Train CE:0.011680, Train KL:8.765940, Val MSE:0.010320, Val CE:0.043667, Train ACC:1.000000, Val ACC:0.993750

Epoch 2311/4000: 100%|██████████| 1/1 [00:00<00:00, 24.11it/s]

epoch: 2310, beta = 0.000097, Train MSE: 0.006614, Train CE:0.011680, Train KL:8.765955, Val MSE:0.010307, Val CE:0.043691, Train ACC:1.000000, Val ACC:0.993750

Epoch 2312/4000: 100%|██████████| 1/1 [00:00<00:00, 23.49it/s]

Learning rate updated: 2.475493662280983e-06
epoch: 2311, beta = 0.000097, Train MSE: 0.006620, Train CE:0.011682, Train KL:8.765969, Val MSE:0.010322, Val CE:0.043356, Train ACC:1.000000, Val ACC:0.993750

Epoch 2313/4000: 100%|██████████| 1/1 [00:00<00:00, 26.44it/s]

epoch: 2312, beta = 0.000097, Train MSE: 0.006615, Train CE:0.011682, Train KL:8.765984, Val MSE:0.010298, Val CE:0.043660, Train ACC:1.000000, Val ACC:0.993750

Epoch 2314/4000: 100%|██████████| 1/1 [00:00<00:00, 24.01it/s]

epoch: 2313, beta = 0.000097, Train MSE: 0.006611, Train CE:0.011670, Train KL:8.765997, Val MSE:0.010288, Val CE:0.043552, Train ACC:1.000000, Val ACC:0.993750

Epoch 2315/4000: 100%|██████████| 1/1 [00:00<00:00, 23.88it/s]

epoch: 2314, beta = 0.000097, Train MSE: 0.006613, Train CE:0.011675, Train KL:8.766008, Val MSE:0.010287, Val CE:0.043649, Train ACC:1.000000, Val ACC:0.993750

Epoch 2316/4000: 100%|██████████| 1/1 [00:00<00:00, 24.56it/s]

epoch: 2315, beta = 0.000097, Train MSE: 0.006616, Train CE:0.011674, Train KL:8.766019, Val MSE:0.010305, Val CE:0.043467, Train ACC:1.000000, Val ACC:0.993750

Epoch 2317/4000: 100%|██████████| 1/1 [00:00<00:00, 22.94it/s]

epoch: 2316, beta = 0.000097, Train MSE: 0.006621, Train CE:0.011679, Train KL:8.766028, Val MSE:0.010323, Val CE:0.043393, Train ACC:1.000000, Val ACC:0.993750

Epoch 2318/4000: 100%|██████████| 1/1 [00:00<00:00, 23.24it/s]

epoch: 2317, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011681, Train KL:8.766039, Val MSE:0.010266, Val CE:0.043434, Train ACC:1.000000, Val ACC:0.993750

Epoch 2319/4000: 100%|██████████| 1/1 [00:00<00:00, 24.16it/s]

epoch: 2318, beta = 0.000097, Train MSE: 0.006615, Train CE:0.011672, Train KL:8.766047, Val MSE:0.010286, Val CE:0.043342, Train ACC:1.000000, Val ACC:0.993750

Epoch 2320/4000: 100%|██████████| 1/1 [00:00<00:00, 23.82it/s]

epoch: 2319, beta = 0.000097, Train MSE: 0.006626, Train CE:0.011678, Train KL:8.766056, Val MSE:0.010290, Val CE:0.043379, Train ACC:1.000000, Val ACC:0.993750

Epoch 2321/4000: 100%|██████████| 1/1 [00:00<00:00, 24.19it/s]

epoch: 2320, beta = 0.000097, Train MSE: 0.006617, Train CE:0.011674, Train KL:8.766066, Val MSE:0.010293, Val CE:0.043382, Train ACC:1.000000, Val ACC:0.993750

Epoch 2322/4000: 100%|██████████| 1/1 [00:00<00:00, 20.33it/s]

epoch: 2321, beta = 0.000097, Train MSE: 0.006611, Train CE:0.011680, Train KL:8.766076, Val MSE:0.010272, Val CE:0.043479, Train ACC:1.000000, Val ACC:0.993750

Epoch 2323/4000: 100%|██████████| 1/1 [00:00<00:00, 20.81it/s]

Learning rate updated: 2.351718979166934e-06
epoch: 2322, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011671, Train KL:8.766087, Val MSE:0.010300, Val CE:0.043413, Train ACC:1.000000, Val ACC:0.993750

Epoch 2324/4000: 100%|██████████| 1/1 [00:00<00:00, 21.76it/s]

epoch: 2323, beta = 0.000097, Train MSE: 0.006621, Train CE:0.011680, Train KL:8.766097, Val MSE:0.010297, Val CE:0.043297, Train ACC:1.000000, Val ACC:0.993750

Epoch 2325/4000: 100%|██████████| 1/1 [00:00<00:00, 24.19it/s]

epoch: 2324, beta = 0.000097, Train MSE: 0.006616, Train CE:0.011677, Train KL:8.766109, Val MSE:0.010282, Val CE:0.043668, Train ACC:1.000000, Val ACC:0.993750

Epoch 2326/4000: 100%|██████████| 1/1 [00:00<00:00, 22.85it/s]

epoch: 2325, beta = 0.000097, Train MSE: 0.006615, Train CE:0.011676, Train KL:8.766121, Val MSE:0.010318, Val CE:0.043349, Train ACC:1.000000, Val ACC:0.993750

Epoch 2327/4000: 100%|██████████| 1/1 [00:00<00:00, 24.13it/s]

epoch: 2326, beta = 0.000097, Train MSE: 0.006613, Train CE:0.011679, Train KL:8.766132, Val MSE:0.010280, Val CE:0.043568, Train ACC:1.000000, Val ACC:0.993750

Epoch 2328/4000: 100%|██████████| 1/1 [00:00<00:00, 23.75it/s]

epoch: 2327, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011680, Train KL:8.766146, Val MSE:0.010297, Val CE:0.043451, Train ACC:1.000000, Val ACC:0.993750

Epoch 2329/4000: 100%|██████████| 1/1 [00:00<00:00, 23.67it/s]

epoch: 2328, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011681, Train KL:8.766158, Val MSE:0.010307, Val CE:0.043556, Train ACC:1.000000, Val ACC:0.993750

Epoch 2330/4000: 100%|██████████| 1/1 [00:00<00:00, 23.60it/s]

epoch: 2329, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011678, Train KL:8.766171, Val MSE:0.010320, Val CE:0.043391, Train ACC:1.000000, Val ACC:0.993750

Epoch 2331/4000: 100%|██████████| 1/1 [00:00<00:00, 24.20it/s]

epoch: 2330, beta = 0.000097, Train MSE: 0.006632, Train CE:0.011672, Train KL:8.766184, Val MSE:0.010302, Val CE:0.043395, Train ACC:1.000000, Val ACC:0.993750

Epoch 2332/4000: 100%|██████████| 1/1 [00:00<00:00, 22.07it/s]

epoch: 2331, beta = 0.000097, Train MSE: 0.006613, Train CE:0.011673, Train KL:8.766198, Val MSE:0.010294, Val CE:0.043531, Train ACC:1.000000, Val ACC:0.993750

Epoch 2333/4000: 100%|██████████| 1/1 [00:00<00:00, 23.43it/s]

epoch: 2332, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011674, Train KL:8.766212, Val MSE:0.010292, Val CE:0.043378, Train ACC:1.000000, Val ACC:0.993750

Epoch 2334/4000: 100%|██████████| 1/1 [00:00<00:00, 23.88it/s]

Learning rate updated: 2.234133030208587e-06
epoch: 2333, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011673, Train KL:8.766227, Val MSE:0.010282, Val CE:0.043322, Train ACC:1.000000, Val ACC:0.993750

Epoch 2335/4000: 100%|██████████| 1/1 [00:00<00:00, 23.58it/s]

epoch: 2334, beta = 0.000097, Train MSE: 0.006622, Train CE:0.011680, Train KL:8.766241, Val MSE:0.010276, Val CE:0.043364, Train ACC:1.000000, Val ACC:0.993750

Epoch 2336/4000: 100%|██████████| 1/1 [00:00<00:00, 23.68it/s]

epoch: 2335, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011672, Train KL:8.766255, Val MSE:0.010335, Val CE:0.043502, Train ACC:1.000000, Val ACC:0.993750

Epoch 2337/4000: 100%|██████████| 1/1 [00:00<00:00, 20.04it/s]

epoch: 2336, beta = 0.000097, Train MSE: 0.006620, Train CE:0.011678, Train KL:8.766271, Val MSE:0.010298, Val CE:0.043477, Train ACC:1.000000, Val ACC:0.993750

Epoch 2338/4000: 100%|██████████| 1/1 [00:00<00:00, 19.98it/s]

epoch: 2337, beta = 0.000097, Train MSE: 0.006618, Train CE:0.011675, Train KL:8.766286, Val MSE:0.010305, Val CE:0.043638, Train ACC:1.000000, Val ACC:0.993750

Epoch 2339/4000: 100%|██████████| 1/1 [00:00<00:00, 20.73it/s]

epoch: 2338, beta = 0.000097, Train MSE: 0.006613, Train CE:0.011672, Train KL:8.766300, Val MSE:0.010283, Val CE:0.043490, Train ACC:1.000000, Val ACC:0.993750

Epoch 2340/4000: 100%|██████████| 1/1 [00:00<00:00, 21.63it/s]

epoch: 2339, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011679, Train KL:8.766315, Val MSE:0.010307, Val CE:0.043402, Train ACC:1.000000, Val ACC:0.993750

Epoch 2341/4000: 100%|██████████| 1/1 [00:00<00:00, 22.04it/s]

epoch: 2340, beta = 0.000097, Train MSE: 0.006617, Train CE:0.011671, Train KL:8.766329, Val MSE:0.010289, Val CE:0.043254, Train ACC:1.000000, Val ACC:0.993750

Epoch 2342/4000: 100%|██████████| 1/1 [00:00<00:00, 23.42it/s]

epoch: 2341, beta = 0.000097, Train MSE: 0.006617, Train CE:0.011672, Train KL:8.766344, Val MSE:0.010324, Val CE:0.043417, Train ACC:1.000000, Val ACC:0.993750

Epoch 2343/4000: 100%|██████████| 1/1 [00:00<00:00, 22.77it/s]

epoch: 2342, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011676, Train KL:8.766359, Val MSE:0.010327, Val CE:0.043332, Train ACC:1.000000, Val ACC:0.993750

Epoch 2344/4000: 100%|██████████| 1/1 [00:00<00:00, 23.44it/s]

epoch: 2343, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011672, Train KL:8.766374, Val MSE:0.010288, Val CE:0.043451, Train ACC:1.000000, Val ACC:0.993750

Epoch 2345/4000: 100%|██████████| 1/1 [00:00<00:00, 22.08it/s]

Learning rate updated: 2.1224263786981576e-06
epoch: 2344, beta = 0.000097, Train MSE: 0.006614, Train CE:0.011672, Train KL:8.766387, Val MSE:0.010266, Val CE:0.043175, Train ACC:1.000000, Val ACC:0.993750

Epoch 2346/4000: 100%|██████████| 1/1 [00:00<00:00, 24.25it/s]

epoch: 2345, beta = 0.000097, Train MSE: 0.006618, Train CE:0.011672, Train KL:8.766399, Val MSE:0.010297, Val CE:0.043626, Train ACC:1.000000, Val ACC:0.993750

Epoch 2347/4000: 100%|██████████| 1/1 [00:00<00:00, 24.17it/s]

epoch: 2346, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011667, Train KL:8.766410, Val MSE:0.010316, Val CE:0.043536, Train ACC:1.000000, Val ACC:0.993750

Epoch 2348/4000: 100%|██████████| 1/1 [00:00<00:00, 24.20it/s]

epoch: 2347, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011670, Train KL:8.766422, Val MSE:0.010311, Val CE:0.043518, Train ACC:1.000000, Val ACC:0.993750

Epoch 2349/4000: 100%|██████████| 1/1 [00:00<00:00, 20.51it/s]

epoch: 2348, beta = 0.000097, Train MSE: 0.006619, Train CE:0.011675, Train KL:8.766432, Val MSE:0.010283, Val CE:0.043543, Train ACC:1.000000, Val ACC:0.993750

Epoch 2350/4000: 100%|██████████| 1/1 [00:00<00:00, 23.62it/s]

epoch: 2349, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011674, Train KL:8.766443, Val MSE:0.010287, Val CE:0.043724, Train ACC:1.000000, Val ACC:0.993750

Epoch 2351/4000: 100%|██████████| 1/1 [00:00<00:00, 22.26it/s]

epoch: 2350, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011669, Train KL:8.766453, Val MSE:0.010314, Val CE:0.043618, Train ACC:1.000000, Val ACC:0.993750

Epoch 2352/4000: 100%|██████████| 1/1 [00:00<00:00, 23.88it/s]

epoch: 2351, beta = 0.000097, Train MSE: 0.006613, Train CE:0.011674, Train KL:8.766462, Val MSE:0.010271, Val CE:0.043562, Train ACC:1.000000, Val ACC:0.993750

Epoch 2353/4000: 100%|██████████| 1/1 [00:00<00:00, 26.46it/s]

epoch: 2352, beta = 0.000097, Train MSE: 0.006626, Train CE:0.011673, Train KL:8.766473, Val MSE:0.010280, Val CE:0.043443, Train ACC:1.000000, Val ACC:0.993750

Epoch 2354/4000: 100%|██████████| 1/1 [00:00<00:00, 18.34it/s]

epoch: 2353, beta = 0.000097, Train MSE: 0.006613, Train CE:0.011676, Train KL:8.766483, Val MSE:0.010308, Val CE:0.043558, Train ACC:1.000000, Val ACC:0.993750

Epoch 2355/4000: 100%|██████████| 1/1 [00:00<00:00, 22.11it/s]

epoch: 2354, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011672, Train KL:8.766494, Val MSE:0.010301, Val CE:0.043304, Train ACC:1.000000, Val ACC:0.993750

Epoch 2356/4000: 100%|██████████| 1/1 [00:00<00:00, 24.48it/s]

Learning rate updated: 2.0163050597632494e-06
epoch: 2355, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011673, Train KL:8.766504, Val MSE:0.010288, Val CE:0.043391, Train ACC:1.000000, Val ACC:0.993750

Epoch 2357/4000: 100%|██████████| 1/1 [00:00<00:00, 23.58it/s]

epoch: 2356, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011664, Train KL:8.766514, Val MSE:0.010301, Val CE:0.043310, Train ACC:1.000000, Val ACC:0.993750

Epoch 2358/4000: 100%|██████████| 1/1 [00:00<00:00, 21.82it/s]

epoch: 2357, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011675, Train KL:8.766522, Val MSE:0.010291, Val CE:0.043332, Train ACC:1.000000, Val ACC:0.993750

Epoch 2359/4000: 100%|██████████| 1/1 [00:00<00:00, 23.69it/s]

epoch: 2358, beta = 0.000097, Train MSE: 0.006622, Train CE:0.011672, Train KL:8.766532, Val MSE:0.010275, Val CE:0.043282, Train ACC:1.000000, Val ACC:0.993750

Epoch 2360/4000: 100%|██████████| 1/1 [00:00<00:00, 24.18it/s]

epoch: 2359, beta = 0.000097, Train MSE: 0.006617, Train CE:0.011666, Train KL:8.766540, Val MSE:0.010307, Val CE:0.043653, Train ACC:1.000000, Val ACC:0.993750

Epoch 2361/4000: 100%|██████████| 1/1 [00:00<00:00, 24.09it/s]

epoch: 2360, beta = 0.000097, Train MSE: 0.006618, Train CE:0.011671, Train KL:8.766550, Val MSE:0.010267, Val CE:0.043443, Train ACC:1.000000, Val ACC:0.993750

Epoch 2362/4000: 100%|██████████| 1/1 [00:00<00:00, 24.70it/s]

epoch: 2361, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011673, Train KL:8.766560, Val MSE:0.010272, Val CE:0.043325, Train ACC:1.000000, Val ACC:0.993750

Epoch 2363/4000: 100%|██████████| 1/1 [00:00<00:00, 24.07it/s]

epoch: 2362, beta = 0.000097, Train MSE: 0.006615, Train CE:0.011669, Train KL:8.766569, Val MSE:0.010289, Val CE:0.043398, Train ACC:1.000000, Val ACC:0.993750

Epoch 2364/4000: 100%|██████████| 1/1 [00:00<00:00, 23.34it/s]

epoch: 2363, beta = 0.000097, Train MSE: 0.006619, Train CE:0.011672, Train KL:8.766578, Val MSE:0.010306, Val CE:0.043593, Train ACC:1.000000, Val ACC:0.993750

Epoch 2365/4000: 100%|██████████| 1/1 [00:00<00:00, 23.42it/s]

epoch: 2364, beta = 0.000097, Train MSE: 0.006621, Train CE:0.011669, Train KL:8.766589, Val MSE:0.010290, Val CE:0.043550, Train ACC:1.000000, Val ACC:0.993750

Epoch 2366/4000: 100%|██████████| 1/1 [00:00<00:00, 26.39it/s]

epoch: 2365, beta = 0.000097, Train MSE: 0.006617, Train CE:0.011673, Train KL:8.766599, Val MSE:0.010274, Val CE:0.043357, Train ACC:1.000000, Val ACC:0.993750

Epoch 2367/4000: 100%|██████████| 1/1 [00:00<00:00, 24.02it/s]

Learning rate updated: 1.915489806775087e-06
epoch: 2366, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011669, Train KL:8.766609, Val MSE:0.010300, Val CE:0.043346, Train ACC:1.000000, Val ACC:0.993750

Epoch 2368/4000: 100%|██████████| 1/1 [00:00<00:00, 20.89it/s]

epoch: 2367, beta = 0.000097, Train MSE: 0.006617, Train CE:0.011671, Train KL:8.766621, Val MSE:0.010314, Val CE:0.043363, Train ACC:1.000000, Val ACC:0.993750

Epoch 2369/4000: 100%|██████████| 1/1 [00:00<00:00, 24.17it/s]

epoch: 2368, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011659, Train KL:8.766631, Val MSE:0.010306, Val CE:0.043297, Train ACC:1.000000, Val ACC:0.993750

Epoch 2370/4000: 100%|██████████| 1/1 [00:00<00:00, 24.17it/s]

epoch: 2369, beta = 0.000097, Train MSE: 0.006613, Train CE:0.011671, Train KL:8.766642, Val MSE:0.010306, Val CE:0.043421, Train ACC:1.000000, Val ACC:0.993750

Epoch 2371/4000: 100%|██████████| 1/1 [00:00<00:00, 19.02it/s]

epoch: 2370, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011672, Train KL:8.766653, Val MSE:0.010289, Val CE:0.043347, Train ACC:1.000000, Val ACC:0.993750

Epoch 2372/4000: 100%|██████████| 1/1 [00:00<00:00, 21.88it/s]

epoch: 2371, beta = 0.000097, Train MSE: 0.006616, Train CE:0.011663, Train KL:8.766665, Val MSE:0.010290, Val CE:0.043685, Train ACC:1.000000, Val ACC:0.993750

Epoch 2373/4000: 100%|██████████| 1/1 [00:00<00:00, 21.35it/s]

epoch: 2372, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011664, Train KL:8.766676, Val MSE:0.010276, Val CE:0.043312, Train ACC:1.000000, Val ACC:0.993750

Epoch 2374/4000: 100%|██████████| 1/1 [00:00<00:00, 24.10it/s]

epoch: 2373, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011664, Train KL:8.766687, Val MSE:0.010307, Val CE:0.043434, Train ACC:1.000000, Val ACC:0.993750

Epoch 2375/4000: 100%|██████████| 1/1 [00:00<00:00, 24.17it/s]

epoch: 2374, beta = 0.000097, Train MSE: 0.006617, Train CE:0.011669, Train KL:8.766700, Val MSE:0.010260, Val CE:0.043500, Train ACC:1.000000, Val ACC:0.993750

Epoch 2376/4000: 100%|██████████| 1/1 [00:00<00:00, 24.53it/s]

epoch: 2375, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011670, Train KL:8.766712, Val MSE:0.010291, Val CE:0.043479, Train ACC:1.000000, Val ACC:0.993750

Epoch 2377/4000: 100%|██████████| 1/1 [00:00<00:00, 21.37it/s]

epoch: 2376, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011665, Train KL:8.766724, Val MSE:0.010284, Val CE:0.043529, Train ACC:1.000000, Val ACC:0.993750

Epoch 2378/4000: 100%|██████████| 1/1 [00:00<00:00, 23.78it/s]

Learning rate updated: 1.8197153164363325e-06
epoch: 2377, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011664, Train KL:8.766735, Val MSE:0.010280, Val CE:0.043681, Train ACC:1.000000, Val ACC:0.993750

Epoch 2379/4000: 100%|██████████| 1/1 [00:00<00:00, 24.56it/s]

epoch: 2378, beta = 0.000097, Train MSE: 0.006617, Train CE:0.011670, Train KL:8.766747, Val MSE:0.010298, Val CE:0.043512, Train ACC:1.000000, Val ACC:0.993750

Epoch 2380/4000: 100%|██████████| 1/1 [00:00<00:00, 26.78it/s]

epoch: 2379, beta = 0.000097, Train MSE: 0.006614, Train CE:0.011668, Train KL:8.766757, Val MSE:0.010312, Val CE:0.043513, Train ACC:1.000000, Val ACC:0.993750

Epoch 2381/4000: 100%|██████████| 1/1 [00:00<00:00, 23.98it/s]

epoch: 2380, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011666, Train KL:8.766768, Val MSE:0.010281, Val CE:0.043507, Train ACC:1.000000, Val ACC:0.993750

Epoch 2382/4000: 100%|██████████| 1/1 [00:00<00:00, 25.41it/s]

epoch: 2381, beta = 0.000097, Train MSE: 0.006623, Train CE:0.011665, Train KL:8.766777, Val MSE:0.010310, Val CE:0.043381, Train ACC:1.000000, Val ACC:0.993750

Epoch 2383/4000: 100%|██████████| 1/1 [00:00<00:00, 24.24it/s]

epoch: 2382, beta = 0.000097, Train MSE: 0.006615, Train CE:0.011671, Train KL:8.766788, Val MSE:0.010303, Val CE:0.043582, Train ACC:1.000000, Val ACC:0.993750

Epoch 2384/4000: 100%|██████████| 1/1 [00:00<00:00, 23.99it/s]

epoch: 2383, beta = 0.000097, Train MSE: 0.006625, Train CE:0.011662, Train KL:8.766797, Val MSE:0.010299, Val CE:0.043796, Train ACC:1.000000, Val ACC:0.993750

Epoch 2385/4000: 100%|██████████| 1/1 [00:00<00:00, 24.01it/s]

epoch: 2384, beta = 0.000097, Train MSE: 0.006615, Train CE:0.011670, Train KL:8.766808, Val MSE:0.010310, Val CE:0.043393, Train ACC:1.000000, Val ACC:0.993750

Epoch 2386/4000: 100%|██████████| 1/1 [00:00<00:00, 25.64it/s]

epoch: 2385, beta = 0.000097, Train MSE: 0.006619, Train CE:0.011664, Train KL:8.766817, Val MSE:0.010282, Val CE:0.043615, Train ACC:1.000000, Val ACC:0.993750

Epoch 2387/4000: 100%|██████████| 1/1 [00:00<00:00, 23.35it/s]

epoch: 2386, beta = 0.000097, Train MSE: 0.006618, Train CE:0.011668, Train KL:8.766829, Val MSE:0.010274, Val CE:0.043309, Train ACC:1.000000, Val ACC:0.993750

Epoch 2388/4000: 100%|██████████| 1/1 [00:00<00:00, 21.57it/s]

epoch: 2387, beta = 0.000097, Train MSE: 0.006619, Train CE:0.011664, Train KL:8.766838, Val MSE:0.010259, Val CE:0.043279, Train ACC:1.000000, Val ACC:0.993750

Epoch 2389/4000: 100%|██████████| 1/1 [00:00<00:00, 18.14it/s]

Learning rate updated: 1.7287295506145157e-06
epoch: 2388, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011665, Train KL:8.766849, Val MSE:0.010294, Val CE:0.043458, Train ACC:1.000000, Val ACC:0.993750

Epoch 2390/4000: 100%|██████████| 1/1 [00:00<00:00, 23.83it/s]

epoch: 2389, beta = 0.000097, Train MSE: 0.006613, Train CE:0.011666, Train KL:8.766859, Val MSE:0.010294, Val CE:0.043491, Train ACC:1.000000, Val ACC:0.993750

Epoch 2391/4000: 100%|██████████| 1/1 [00:00<00:00, 21.06it/s]

epoch: 2390, beta = 0.000097, Train MSE: 0.006615, Train CE:0.011663, Train KL:8.766870, Val MSE:0.010281, Val CE:0.043492, Train ACC:1.000000, Val ACC:0.993750

Epoch 2392/4000: 100%|██████████| 1/1 [00:00<00:00, 23.05it/s]

epoch: 2391, beta = 0.000097, Train MSE: 0.006615, Train CE:0.011667, Train KL:8.766879, Val MSE:0.010296, Val CE:0.043288, Train ACC:1.000000, Val ACC:0.993750

Epoch 2393/4000: 100%|██████████| 1/1 [00:00<00:00, 23.27it/s]

epoch: 2392, beta = 0.000097, Train MSE: 0.006621, Train CE:0.011664, Train KL:8.766890, Val MSE:0.010295, Val CE:0.043425, Train ACC:1.000000, Val ACC:0.993750

Epoch 2394/4000: 100%|██████████| 1/1 [00:00<00:00, 25.05it/s]

epoch: 2393, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011659, Train KL:8.766901, Val MSE:0.010293, Val CE:0.043405, Train ACC:1.000000, Val ACC:0.993750

Epoch 2395/4000: 100%|██████████| 1/1 [00:00<00:00, 23.91it/s]

epoch: 2394, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011658, Train KL:8.766912, Val MSE:0.010293, Val CE:0.043316, Train ACC:1.000000, Val ACC:0.993750

Epoch 2396/4000: 100%|██████████| 1/1 [00:00<00:00, 23.70it/s]

epoch: 2395, beta = 0.000097, Train MSE: 0.006617, Train CE:0.011658, Train KL:8.766920, Val MSE:0.010310, Val CE:0.043298, Train ACC:1.000000, Val ACC:0.993750

Epoch 2397/4000: 100%|██████████| 1/1 [00:00<00:00, 23.97it/s]

epoch: 2396, beta = 0.000097, Train MSE: 0.006615, Train CE:0.011668, Train KL:8.766931, Val MSE:0.010283, Val CE:0.043463, Train ACC:1.000000, Val ACC:0.993750

Epoch 2398/4000: 100%|██████████| 1/1 [00:00<00:00, 22.96it/s]

epoch: 2397, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011663, Train KL:8.766940, Val MSE:0.010311, Val CE:0.043457, Train ACC:1.000000, Val ACC:0.993750

Epoch 2399/4000: 100%|██████████| 1/1 [00:00<00:00, 23.39it/s]

epoch: 2398, beta = 0.000097, Train MSE: 0.006619, Train CE:0.011656, Train KL:8.766950, Val MSE:0.010301, Val CE:0.043505, Train ACC:1.000000, Val ACC:0.993750

Epoch 2400/4000: 100%|██████████| 1/1 [00:00<00:00, 23.58it/s]

Learning rate updated: 1.6422930730837899e-06
epoch: 2399, beta = 0.000097, Train MSE: 0.006615, Train CE:0.011661, Train KL:8.766959, Val MSE:0.010287, Val CE:0.043443, Train ACC:1.000000, Val ACC:0.993750

Epoch 2401/4000: 100%|██████████| 1/1 [00:00<00:00, 24.54it/s]

epoch: 2400, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011664, Train KL:8.766970, Val MSE:0.010283, Val CE:0.043457, Train ACC:1.000000, Val ACC:0.993750

Epoch 2402/4000: 100%|██████████| 1/1 [00:00<00:00, 22.72it/s]

epoch: 2401, beta = 0.000097, Train MSE: 0.006613, Train CE:0.011662, Train KL:8.766978, Val MSE:0.010306, Val CE:0.043569, Train ACC:1.000000, Val ACC:0.993750

Epoch 2403/4000: 100%|██████████| 1/1 [00:00<00:00, 23.95it/s]

epoch: 2402, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011663, Train KL:8.766988, Val MSE:0.010285, Val CE:0.043583, Train ACC:1.000000, Val ACC:0.993750

Epoch 2404/4000: 100%|██████████| 1/1 [00:00<00:00, 20.76it/s]

epoch: 2403, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011663, Train KL:8.766997, Val MSE:0.010292, Val CE:0.043494, Train ACC:1.000000, Val ACC:0.993750

Epoch 2405/4000: 100%|██████████| 1/1 [00:00<00:00, 21.95it/s]

epoch: 2404, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011665, Train KL:8.767005, Val MSE:0.010305, Val CE:0.043384, Train ACC:1.000000, Val ACC:0.993750

Epoch 2406/4000: 100%|██████████| 1/1 [00:00<00:00, 20.77it/s]

epoch: 2405, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011665, Train KL:8.767014, Val MSE:0.010302, Val CE:0.043316, Train ACC:1.000000, Val ACC:0.993750

Epoch 2407/4000: 100%|██████████| 1/1 [00:00<00:00, 21.62it/s]

epoch: 2406, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011658, Train KL:8.767022, Val MSE:0.010267, Val CE:0.043543, Train ACC:1.000000, Val ACC:0.993750

Epoch 2408/4000: 100%|██████████| 1/1 [00:00<00:00, 24.33it/s]

epoch: 2407, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011666, Train KL:8.767031, Val MSE:0.010307, Val CE:0.043440, Train ACC:1.000000, Val ACC:0.993750

Epoch 2409/4000: 100%|██████████| 1/1 [00:00<00:00, 24.13it/s]

epoch: 2408, beta = 0.000097, Train MSE: 0.006611, Train CE:0.011656, Train KL:8.767038, Val MSE:0.010310, Val CE:0.043318, Train ACC:1.000000, Val ACC:0.993750

Epoch 2410/4000: 100%|██████████| 1/1 [00:00<00:00, 22.15it/s]

epoch: 2409, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011655, Train KL:8.767046, Val MSE:0.010289, Val CE:0.043470, Train ACC:1.000000, Val ACC:0.993750

Epoch 2411/4000: 100%|██████████| 1/1 [00:00<00:00, 23.92it/s]

Learning rate updated: 1.5601784194296004e-06
epoch: 2410, beta = 0.000097, Train MSE: 0.006611, Train CE:0.011661, Train KL:8.767054, Val MSE:0.010288, Val CE:0.043275, Train ACC:1.000000, Val ACC:0.993750

Epoch 2412/4000: 100%|██████████| 1/1 [00:00<00:00, 24.65it/s]

epoch: 2411, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011660, Train KL:8.767061, Val MSE:0.010278, Val CE:0.043543, Train ACC:1.000000, Val ACC:0.993750

Epoch 2413/4000: 100%|██████████| 1/1 [00:00<00:00, 22.89it/s]

epoch: 2412, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011666, Train KL:8.767067, Val MSE:0.010299, Val CE:0.043467, Train ACC:1.000000, Val ACC:0.993750

Epoch 2414/4000: 100%|██████████| 1/1 [00:00<00:00, 24.01it/s]

epoch: 2413, beta = 0.000097, Train MSE: 0.006613, Train CE:0.011666, Train KL:8.767074, Val MSE:0.010282, Val CE:0.043443, Train ACC:1.000000, Val ACC:0.993750

Epoch 2415/4000: 100%|██████████| 1/1 [00:00<00:00, 21.43it/s]

epoch: 2414, beta = 0.000097, Train MSE: 0.006611, Train CE:0.011660, Train KL:8.767081, Val MSE:0.010293, Val CE:0.043462, Train ACC:1.000000, Val ACC:0.993750

Epoch 2416/4000: 100%|██████████| 1/1 [00:00<00:00, 24.46it/s]

epoch: 2415, beta = 0.000097, Train MSE: 0.006614, Train CE:0.011660, Train KL:8.767090, Val MSE:0.010325, Val CE:0.043373, Train ACC:1.000000, Val ACC:0.993750

Epoch 2417/4000: 100%|██████████| 1/1 [00:00<00:00, 23.78it/s]

epoch: 2416, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011660, Train KL:8.767097, Val MSE:0.010306, Val CE:0.043450, Train ACC:1.000000, Val ACC:0.993750

Epoch 2418/4000: 100%|██████████| 1/1 [00:00<00:00, 26.92it/s]

epoch: 2417, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011656, Train KL:8.767105, Val MSE:0.010318, Val CE:0.043709, Train ACC:1.000000, Val ACC:0.993750

Epoch 2419/4000: 100%|██████████| 1/1 [00:00<00:00, 28.87it/s]

epoch: 2418, beta = 0.000097, Train MSE: 0.006619, Train CE:0.011662, Train KL:8.767113, Val MSE:0.010299, Val CE:0.043525, Train ACC:1.000000, Val ACC:0.993750

Epoch 2420/4000: 100%|██████████| 1/1 [00:00<00:00, 24.52it/s]

epoch: 2419, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011661, Train KL:8.767120, Val MSE:0.010257, Val CE:0.043352, Train ACC:1.000000, Val ACC:0.993750

Epoch 2421/4000: 100%|██████████| 1/1 [00:00<00:00, 22.68it/s]

epoch: 2420, beta = 0.000097, Train MSE: 0.006616, Train CE:0.011659, Train KL:8.767129, Val MSE:0.010319, Val CE:0.043354, Train ACC:1.000000, Val ACC:0.993750

Epoch 2422/4000: 100%|██████████| 1/1 [00:00<00:00, 26.31it/s]

Learning rate updated: 1.4821694984581202e-06
epoch: 2421, beta = 0.000097, Train MSE: 0.006613, Train CE:0.011667, Train KL:8.767138, Val MSE:0.010288, Val CE:0.043602, Train ACC:1.000000, Val ACC:0.993750

Epoch 2423/4000: 100%|██████████| 1/1 [00:00<00:00, 24.03it/s]

epoch: 2422, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011660, Train KL:8.767147, Val MSE:0.010291, Val CE:0.043572, Train ACC:1.000000, Val ACC:0.993750

Epoch 2424/4000: 100%|██████████| 1/1 [00:00<00:00, 24.03it/s]

epoch: 2423, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011664, Train KL:8.767155, Val MSE:0.010315, Val CE:0.043482, Train ACC:1.000000, Val ACC:0.993750

Epoch 2425/4000: 100%|██████████| 1/1 [00:00<00:00, 24.05it/s]

epoch: 2424, beta = 0.000097, Train MSE: 0.006613, Train CE:0.011665, Train KL:8.767162, Val MSE:0.010307, Val CE:0.043233, Train ACC:1.000000, Val ACC:0.993750

Epoch 2426/4000: 100%|██████████| 1/1 [00:00<00:00, 19.92it/s]

epoch: 2425, beta = 0.000097, Train MSE: 0.006617, Train CE:0.011658, Train KL:8.767170, Val MSE:0.010284, Val CE:0.043561, Train ACC:1.000000, Val ACC:0.993750

Epoch 2427/4000: 100%|██████████| 1/1 [00:00<00:00, 21.05it/s]

epoch: 2426, beta = 0.000097, Train MSE: 0.006615, Train CE:0.011657, Train KL:8.767179, Val MSE:0.010278, Val CE:0.043498, Train ACC:1.000000, Val ACC:0.993750

Epoch 2428/4000: 100%|██████████| 1/1 [00:00<00:00, 22.33it/s]

epoch: 2427, beta = 0.000097, Train MSE: 0.006613, Train CE:0.011655, Train KL:8.767186, Val MSE:0.010293, Val CE:0.043372, Train ACC:1.000000, Val ACC:0.993750

Epoch 2429/4000: 100%|██████████| 1/1 [00:00<00:00, 23.74it/s]

epoch: 2428, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011666, Train KL:8.767194, Val MSE:0.010286, Val CE:0.043600, Train ACC:1.000000, Val ACC:0.993229

Epoch 2430/4000: 100%|██████████| 1/1 [00:00<00:00, 23.91it/s]

epoch: 2429, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011663, Train KL:8.767203, Val MSE:0.010287, Val CE:0.043436, Train ACC:1.000000, Val ACC:0.993750

Epoch 2431/4000: 100%|██████████| 1/1 [00:00<00:00, 24.21it/s]

epoch: 2430, beta = 0.000097, Train MSE: 0.006619, Train CE:0.011661, Train KL:8.767211, Val MSE:0.010281, Val CE:0.043553, Train ACC:1.000000, Val ACC:0.993750

Epoch 2432/4000: 100%|██████████| 1/1 [00:00<00:00, 24.12it/s]

epoch: 2431, beta = 0.000097, Train MSE: 0.006613, Train CE:0.011661, Train KL:8.767220, Val MSE:0.010261, Val CE:0.043581, Train ACC:1.000000, Val ACC:0.993750

Epoch 2433/4000: 100%|██████████| 1/1 [00:00<00:00, 24.16it/s]

Learning rate updated: 1.4080610235352142e-06
epoch: 2432, beta = 0.000097, Train MSE: 0.006623, Train CE:0.011657, Train KL:8.767228, Val MSE:0.010291, Val CE:0.043436, Train ACC:1.000000, Val ACC:0.993750

Epoch 2434/4000: 100%|██████████| 1/1 [00:00<00:00, 21.81it/s]

epoch: 2433, beta = 0.000097, Train MSE: 0.006617, Train CE:0.011657, Train KL:8.767237, Val MSE:0.010290, Val CE:0.043416, Train ACC:1.000000, Val ACC:0.993750

Epoch 2435/4000: 100%|██████████| 1/1 [00:00<00:00, 24.56it/s]

epoch: 2434, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011660, Train KL:8.767244, Val MSE:0.010302, Val CE:0.043473, Train ACC:1.000000, Val ACC:0.993750

Epoch 2436/4000: 100%|██████████| 1/1 [00:00<00:00, 22.67it/s]

epoch: 2435, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011661, Train KL:8.767253, Val MSE:0.010292, Val CE:0.043536, Train ACC:1.000000, Val ACC:0.993750

Epoch 2437/4000: 100%|██████████| 1/1 [00:00<00:00, 20.90it/s]

epoch: 2436, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011659, Train KL:8.767262, Val MSE:0.010288, Val CE:0.043525, Train ACC:1.000000, Val ACC:0.993750

Epoch 2438/4000: 100%|██████████| 1/1 [00:00<00:00, 24.68it/s]

epoch: 2437, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011656, Train KL:8.767270, Val MSE:0.010294, Val CE:0.043367, Train ACC:1.000000, Val ACC:0.993750

Epoch 2439/4000: 100%|██████████| 1/1 [00:00<00:00, 22.00it/s]

epoch: 2438, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011656, Train KL:8.767278, Val MSE:0.010278, Val CE:0.043430, Train ACC:1.000000, Val ACC:0.993750

Epoch 2440/4000: 100%|██████████| 1/1 [00:00<00:00, 24.85it/s]

epoch: 2439, beta = 0.000097, Train MSE: 0.006615, Train CE:0.011656, Train KL:8.767286, Val MSE:0.010306, Val CE:0.043618, Train ACC:1.000000, Val ACC:0.993750

Epoch 2441/4000: 100%|██████████| 1/1 [00:00<00:00, 23.81it/s]

epoch: 2440, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011660, Train KL:8.767294, Val MSE:0.010282, Val CE:0.043404, Train ACC:1.000000, Val ACC:0.993750

Epoch 2442/4000: 100%|██████████| 1/1 [00:00<00:00, 22.44it/s]

epoch: 2441, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011655, Train KL:8.767302, Val MSE:0.010288, Val CE:0.043549, Train ACC:1.000000, Val ACC:0.993750

Epoch 2443/4000: 100%|██████████| 1/1 [00:00<00:00, 19.48it/s]

epoch: 2442, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011656, Train KL:8.767309, Val MSE:0.010310, Val CE:0.043470, Train ACC:1.000000, Val ACC:0.993750

Epoch 2444/4000: 100%|██████████| 1/1 [00:00<00:00, 19.58it/s]

Learning rate updated: 1.3376579723584535e-06

epoch: 2443, beta = 0.000097, Train MSE: 0.006613, Train CE:0.011657, Train KL:8.767317, Val MSE:0.010285, Val CE:0.043616, Train ACC:1.000000, Val ACC:0.993750

Epoch 2445/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 2444, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011661, Train KL:8.767324, Val MSE:0.010285, Val CE:0.043461, Train ACC:1.000000, Val ACC:0.993750

Epoch 2446/4000: 100%|██████████| 1/1 [00:00<00:00, 23.96it/s]

epoch: 2445, beta = 0.000097, Train MSE: 0.006617, Train CE:0.011656, Train KL:8.767331, Val MSE:0.010291, Val CE:0.043165, Train ACC:1.000000, Val ACC:0.993750

Epoch 2447/4000: 100%|██████████| 1/1 [00:00<00:00, 21.52it/s]

epoch: 2446, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011656, Train KL:8.767338, Val MSE:0.010293, Val CE:0.043428, Train ACC:1.000000, Val ACC:0.993750

Epoch 2448/4000: 100%|██████████| 1/1 [00:00<00:00, 24.16it/s]

epoch: 2447, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011660, Train KL:8.767344, Val MSE:0.010292, Val CE:0.043389, Train ACC:1.000000, Val ACC:0.993750

Epoch 2449/4000: 100%|██████████| 1/1 [00:00<00:00, 23.29it/s]

epoch: 2448, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011658, Train KL:8.767351, Val MSE:0.010262, Val CE:0.043539, Train ACC:1.000000, Val ACC:0.993750

Epoch 2450/4000: 100%|██████████| 1/1 [00:00<00:00, 23.22it/s]

epoch: 2449, beta = 0.000097, Train MSE: 0.006624, Train CE:0.011656, Train KL:8.767357, Val MSE:0.010286, Val CE:0.043601, Train ACC:1.000000, Val ACC:0.993750

Epoch 2451/4000: 100%|██████████| 1/1 [00:00<00:00, 22.56it/s]

epoch: 2450, beta = 0.000097, Train MSE: 0.006613, Train CE:0.011655, Train KL:8.767363, Val MSE:0.010290, Val CE:0.043430, Train ACC:1.000000, Val ACC:0.993750

Epoch 2452/4000: 100%|██████████| 1/1 [00:00<00:00, 21.31it/s]

epoch: 2451, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011660, Train KL:8.767369, Val MSE:0.010286, Val CE:0.043470, Train ACC:1.000000, Val ACC:0.993750

Epoch 2453/4000: 100%|██████████| 1/1 [00:00<00:00, 24.41it/s]

epoch: 2452, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011659, Train KL:8.767376, Val MSE:0.010321, Val CE:0.043488, Train ACC:1.000000, Val ACC:0.993750

Epoch 2454/4000: 100%|██████████| 1/1 [00:00<00:00, 22.90it/s]

epoch: 2453, beta = 0.000097, Train MSE: 0.006616, Train CE:0.011653, Train KL:8.767383, Val MSE:0.010286, Val CE:0.043422, Train ACC:1.000000, Val ACC:0.993750

Epoch 2455/4000: 100%|██████████| 1/1 [00:00<00:00, 23.27it/s]

Learning rate updated: 1.2707750737405307e-06
epoch: 2454, beta = 0.000097, Train MSE: 0.006611, Train CE:0.011660, Train KL:8.767389, Val MSE:0.010274, Val CE:0.043529, Train ACC:1.000000, Val ACC:0.993750

Epoch 2456/4000: 100%|██████████| 1/1 [00:00<00:00, 24.08it/s]

epoch: 2455, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011657, Train KL:8.767396, Val MSE:0.010277, Val CE:0.043355, Train ACC:1.000000, Val ACC:0.993750

Epoch 2457/4000: 100%|██████████| 1/1 [00:00<00:00, 24.23it/s]

epoch: 2456, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011657, Train KL:8.767402, Val MSE:0.010276, Val CE:0.043476, Train ACC:1.000000, Val ACC:0.993750

Epoch 2458/4000: 100%|██████████| 1/1 [00:00<00:00, 24.11it/s]

epoch: 2457, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011656, Train KL:8.767408, Val MSE:0.010306, Val CE:0.043437, Train ACC:1.000000, Val ACC:0.993750

Epoch 2459/4000: 100%|██████████| 1/1 [00:00<00:00, 21.50it/s]

epoch: 2458, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011661, Train KL:8.767416, Val MSE:0.010275, Val CE:0.043375, Train ACC:1.000000, Val ACC:0.993750

Epoch 2460/4000: 100%|██████████| 1/1 [00:00<00:00, 24.42it/s]

epoch: 2459, beta = 0.000097, Train MSE: 0.006614, Train CE:0.011659, Train KL:8.767422, Val MSE:0.010294, Val CE:0.043389, Train ACC:1.000000, Val ACC:0.993750

Epoch 2461/4000: 100%|██████████| 1/1 [00:00<00:00, 22.97it/s]

epoch: 2460, beta = 0.000097, Train MSE: 0.006621, Train CE:0.011651, Train KL:8.767428, Val MSE:0.010293, Val CE:0.043448, Train ACC:1.000000, Val ACC:0.993750

Epoch 2462/4000: 100%|██████████| 1/1 [00:00<00:00, 25.64it/s]

epoch: 2461, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011654, Train KL:8.767435, Val MSE:0.010310, Val CE:0.043287, Train ACC:1.000000, Val ACC:0.993750

Epoch 2463/4000: 100%|██████████| 1/1 [00:00<00:00, 24.60it/s]

epoch: 2462, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011652, Train KL:8.767441, Val MSE:0.010283, Val CE:0.043336, Train ACC:1.000000, Val ACC:0.993750

Epoch 2464/4000: 100%|██████████| 1/1 [00:00<00:00, 21.91it/s]

epoch: 2463, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011659, Train KL:8.767447, Val MSE:0.010285, Val CE:0.043513, Train ACC:1.000000, Val ACC:0.993750

Epoch 2465/4000: 100%|██████████| 1/1 [00:00<00:00, 23.78it/s]

epoch: 2464, beta = 0.000097, Train MSE: 0.006618, Train CE:0.011648, Train KL:8.767454, Val MSE:0.010254, Val CE:0.043300, Train ACC:1.000000, Val ACC:0.993750

Epoch 2466/4000: 100%|██████████| 1/1 [00:00<00:00, 25.40it/s]

Learning rate updated: 1.2072363200535042e-06
epoch: 2465, beta = 0.000097, Train MSE: 0.006611, Train CE:0.011658, Train KL:8.767461, Val MSE:0.010305, Val CE:0.043275, Train ACC:1.000000, Val ACC:0.993750

Epoch 2467/4000: 100%|██████████| 1/1 [00:00<00:00, 24.70it/s]

epoch: 2466, beta = 0.000097, Train MSE: 0.006614, Train CE:0.011653, Train KL:8.767467, Val MSE:0.010300, Val CE:0.043229, Train ACC:1.000000, Val ACC:0.993750

Epoch 2468/4000: 100%|██████████| 1/1 [00:00<00:00, 26.49it/s]

epoch: 2467, beta = 0.000097, Train MSE: 0.006616, Train CE:0.011657, Train KL:8.767474, Val MSE:0.010263, Val CE:0.043443, Train ACC:1.000000, Val ACC:0.993750

Epoch 2469/4000: 100%|██████████| 1/1 [00:00<00:00, 23.58it/s]

epoch: 2468, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011657, Train KL:8.767482, Val MSE:0.010237, Val CE:0.043329, Train ACC:1.000000, Val ACC:0.993750

Epoch 2470/4000: 100%|██████████| 1/1 [00:00<00:00, 24.61it/s]

epoch: 2469, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011655, Train KL:8.767489, Val MSE:0.010256, Val CE:0.043504, Train ACC:1.000000, Val ACC:0.993750

Epoch 2471/4000: 100%|██████████| 1/1 [00:00<00:00, 24.58it/s]

epoch: 2470, beta = 0.000097, Train MSE: 0.006617, Train CE:0.011655, Train KL:8.767498, Val MSE:0.010281, Val CE:0.043455, Train ACC:1.000000, Val ACC:0.993750

Epoch 2472/4000: 100%|██████████| 1/1 [00:00<00:00, 23.95it/s]

epoch: 2471, beta = 0.000097, Train MSE: 0.006617, Train CE:0.011656, Train KL:8.767506, Val MSE:0.010279, Val CE:0.043550, Train ACC:1.000000, Val ACC:0.993750

Epoch 2473/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 2472, beta = 0.000097, Train MSE: 0.006617, Train CE:0.011651, Train KL:8.767513, Val MSE:0.010332, Val CE:0.043514, Train ACC:1.000000, Val ACC:0.993750

Epoch 2474/4000: 100%|██████████| 1/1 [00:00<00:00, 24.71it/s]

epoch: 2473, beta = 0.000097, Train MSE: 0.006614, Train CE:0.011656, Train KL:8.767520, Val MSE:0.010300, Val CE:0.043449, Train ACC:1.000000, Val ACC:0.993750

Epoch 2475/4000: 100%|██████████| 1/1 [00:00<00:00, 23.69it/s]

epoch: 2474, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011660, Train KL:8.767528, Val MSE:0.010273, Val CE:0.043407, Train ACC:1.000000, Val ACC:0.993750

Epoch 2476/4000: 100%|██████████| 1/1 [00:00<00:00, 26.38it/s]

epoch: 2475, beta = 0.000097, Train MSE: 0.006617, Train CE:0.011658, Train KL:8.767536, Val MSE:0.010281, Val CE:0.043441, Train ACC:1.000000, Val ACC:0.993750

Epoch 2477/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

Learning rate updated: 1.146874504050829e-06
epoch: 2476, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011651, Train KL:8.767544, Val MSE:0.010300, Val CE:0.043513, Train ACC:1.000000, Val ACC:0.993750

Epoch 2478/4000: 100%|██████████| 1/1 [00:00<00:00, 23.55it/s]

epoch: 2477, beta = 0.000097, Train MSE: 0.006616, Train CE:0.011658, Train KL:8.767551, Val MSE:0.010260, Val CE:0.043504, Train ACC:1.000000, Val ACC:0.993750

Epoch 2479/4000: 100%|██████████| 1/1 [00:00<00:00, 24.55it/s]

epoch: 2478, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011651, Train KL:8.767559, Val MSE:0.010290, Val CE:0.043526, Train ACC:1.000000, Val ACC:0.993750

Epoch 2480/4000: 100%|██████████| 1/1 [00:00<00:00, 25.83it/s]

epoch: 2479, beta = 0.000097, Train MSE: 0.006618, Train CE:0.011660, Train KL:8.767565, Val MSE:0.010286, Val CE:0.043458, Train ACC:1.000000, Val ACC:0.993750

Epoch 2481/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 2480, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011654, Train KL:8.767571, Val MSE:0.010278, Val CE:0.043451, Train ACC:1.000000, Val ACC:0.993750

Epoch 2482/4000: 100%|██████████| 1/1 [00:00<00:00, 24.94it/s]

epoch: 2481, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011656, Train KL:8.767579, Val MSE:0.010283, Val CE:0.043602, Train ACC:1.000000, Val ACC:0.993750

Epoch 2483/4000: 100%|██████████| 1/1 [00:00<00:00, 19.78it/s]

epoch: 2482, beta = 0.000097, Train MSE: 0.006611, Train CE:0.011657, Train KL:8.767586, Val MSE:0.010265, Val CE:0.043272, Train ACC:1.000000, Val ACC:0.993750

Epoch 2484/4000: 100%|██████████| 1/1 [00:00<00:00, 20.85it/s]

epoch: 2483, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011651, Train KL:8.767593, Val MSE:0.010273, Val CE:0.043307, Train ACC:1.000000, Val ACC:0.993750

Epoch 2485/4000: 100%|██████████| 1/1 [00:00<00:00, 21.02it/s]

epoch: 2484, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011657, Train KL:8.767599, Val MSE:0.010279, Val CE:0.043528, Train ACC:1.000000, Val ACC:0.993750

Epoch 2486/4000: 100%|██████████| 1/1 [00:00<00:00, 22.95it/s]

epoch: 2485, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011647, Train KL:8.767607, Val MSE:0.010289, Val CE:0.043458, Train ACC:1.000000, Val ACC:0.993750

Epoch 2487/4000: 100%|██████████| 1/1 [00:00<00:00, 23.40it/s]

epoch: 2486, beta = 0.000097, Train MSE: 0.006614, Train CE:0.011655, Train KL:8.767612, Val MSE:0.010267, Val CE:0.043244, Train ACC:1.000000, Val ACC:0.993750

Epoch 2488/4000: 100%|██████████| 1/1 [00:00<00:00, 22.46it/s]

Learning rate updated: 1.0895307788482876e-06
epoch: 2487, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011650, Train KL:8.767620, Val MSE:0.010321, Val CE:0.043591, Train ACC:1.000000, Val ACC:0.993750

Epoch 2489/4000: 100%|██████████| 1/1 [00:00<00:00, 21.57it/s]

epoch: 2488, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011650, Train KL:8.767627, Val MSE:0.010288, Val CE:0.043259, Train ACC:1.000000, Val ACC:0.993750

Epoch 2490/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 2489, beta = 0.000097, Train MSE: 0.006611, Train CE:0.011659, Train KL:8.767632, Val MSE:0.010288, Val CE:0.043518, Train ACC:1.000000, Val ACC:0.993750

Epoch 2491/4000: 100%|██████████| 1/1 [00:00<00:00, 24.71it/s]

epoch: 2490, beta = 0.000097, Train MSE: 0.006614, Train CE:0.011658, Train KL:8.767638, Val MSE:0.010299, Val CE:0.043391, Train ACC:1.000000, Val ACC:0.993750

Epoch 2492/4000: 100%|██████████| 1/1 [00:00<00:00, 25.61it/s]

epoch: 2491, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011659, Train KL:8.767643, Val MSE:0.010298, Val CE:0.043413, Train ACC:1.000000, Val ACC:0.993750

Epoch 2493/4000: 100%|██████████| 1/1 [00:00<00:00, 22.06it/s]

epoch: 2492, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011650, Train KL:8.767650, Val MSE:0.010261, Val CE:0.043565, Train ACC:1.000000, Val ACC:0.993750

Epoch 2494/4000: 100%|██████████| 1/1 [00:00<00:00, 24.42it/s]

epoch: 2493, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011652, Train KL:8.767655, Val MSE:0.010274, Val CE:0.043371, Train ACC:1.000000, Val ACC:0.993750

Epoch 2495/4000: 100%|██████████| 1/1 [00:00<00:00, 24.05it/s]

epoch: 2494, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011652, Train KL:8.767663, Val MSE:0.010283, Val CE:0.043419, Train ACC:1.000000, Val ACC:0.993750

Epoch 2496/4000: 100%|██████████| 1/1 [00:00<00:00, 24.03it/s]

epoch: 2495, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011654, Train KL:8.767668, Val MSE:0.010302, Val CE:0.043479, Train ACC:1.000000, Val ACC:0.993750

Epoch 2497/4000: 100%|██████████| 1/1 [00:00<00:00, 22.81it/s]

epoch: 2496, beta = 0.000097, Train MSE: 0.006616, Train CE:0.011651, Train KL:8.767674, Val MSE:0.010300, Val CE:0.043481, Train ACC:1.000000, Val ACC:0.993750

Epoch 2498/4000: 100%|██████████| 1/1 [00:00<00:00, 23.71it/s]

epoch: 2497, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011651, Train KL:8.767680, Val MSE:0.010282, Val CE:0.043517, Train ACC:1.000000, Val ACC:0.993750

Epoch 2499/4000: 100%|██████████| 1/1 [00:00<00:00, 23.88it/s]

Learning rate updated: 1.0350542399058731e-06
epoch: 2498, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011656, Train KL:8.767686, Val MSE:0.010258, Val CE:0.043427, Train ACC:1.000000, Val ACC:0.993750

Epoch 2500/4000: 100%|██████████| 1/1 [00:00<00:00, 20.82it/s]

epoch: 2499, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011650, Train KL:8.767693, Val MSE:0.010289, Val CE:0.043421, Train ACC:1.000000, Val ACC:0.993750

Epoch 2501/4000: 100%|██████████| 1/1 [00:00<00:00, 20.14it/s]

epoch: 2500, beta = 0.000097, Train MSE: 0.006616, Train CE:0.011654, Train KL:8.767698, Val MSE:0.010289, Val CE:0.043451, Train ACC:1.000000, Val ACC:0.993750

Epoch 2502/4000: 100%|██████████| 1/1 [00:00<00:00, 23.44it/s]

epoch: 2501, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011647, Train KL:8.767703, Val MSE:0.010269, Val CE:0.043537, Train ACC:1.000000, Val ACC:0.993750

Epoch 2503/4000: 100%|██████████| 1/1 [00:00<00:00, 24.57it/s]

epoch: 2502, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011653, Train KL:8.767709, Val MSE:0.010302, Val CE:0.043538, Train ACC:1.000000, Val ACC:0.993750

Epoch 2504/4000: 100%|██████████| 1/1 [00:00<00:00, 26.45it/s]

epoch: 2503, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011654, Train KL:8.767715, Val MSE:0.010307, Val CE:0.043581, Train ACC:1.000000, Val ACC:0.993750

Epoch 2505/4000: 100%|██████████| 1/1 [00:00<00:00, 24.21it/s]

epoch: 2504, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011646, Train KL:8.767720, Val MSE:0.010310, Val CE:0.043624, Train ACC:1.000000, Val ACC:0.993750

Epoch 2506/4000: 100%|██████████| 1/1 [00:00<00:00, 20.85it/s]

epoch: 2505, beta = 0.000097, Train MSE: 0.006614, Train CE:0.011656, Train KL:8.767726, Val MSE:0.010278, Val CE:0.043529, Train ACC:1.000000, Val ACC:0.993750

Epoch 2507/4000: 100%|██████████| 1/1 [00:00<00:00, 23.88it/s]

epoch: 2506, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011650, Train KL:8.767732, Val MSE:0.010267, Val CE:0.043462, Train ACC:1.000000, Val ACC:0.993750

Epoch 2508/4000: 100%|██████████| 1/1 [00:00<00:00, 23.92it/s]

epoch: 2507, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011655, Train KL:8.767738, Val MSE:0.010329, Val CE:0.043330, Train ACC:1.000000, Val ACC:0.993750

Epoch 2509/4000: 100%|██████████| 1/1 [00:00<00:00, 27.71it/s]

epoch: 2508, beta = 0.000097, Train MSE: 0.006611, Train CE:0.011653, Train KL:8.767744, Val MSE:0.010301, Val CE:0.043366, Train ACC:1.000000, Val ACC:0.993750

Epoch 2510/4000: 100%|██████████| 1/1 [00:00<00:00, 23.98it/s]

Learning rate updated: 9.833015279105794e-07
epoch: 2509, beta = 0.000097, Train MSE: 0.006611, Train CE:0.011648, Train KL:8.767751, Val MSE:0.010293, Val CE:0.043419, Train ACC:1.000000, Val ACC:0.993750

Epoch 2511/4000: 100%|██████████| 1/1 [00:00<00:00, 24.17it/s]

epoch: 2510, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011654, Train KL:8.767757, Val MSE:0.010286, Val CE:0.043475, Train ACC:1.000000, Val ACC:0.993750

Epoch 2512/4000: 100%|██████████| 1/1 [00:00<00:00, 23.32it/s]

epoch: 2511, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011656, Train KL:8.767763, Val MSE:0.010289, Val CE:0.043286, Train ACC:1.000000, Val ACC:0.993750

Epoch 2513/4000: 100%|██████████| 1/1 [00:00<00:00, 23.08it/s]

epoch: 2512, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011656, Train KL:8.767771, Val MSE:0.010296, Val CE:0.043361, Train ACC:1.000000, Val ACC:0.993750

Epoch 2514/4000: 100%|██████████| 1/1 [00:00<00:00, 23.94it/s]

epoch: 2513, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011652, Train KL:8.767776, Val MSE:0.010276, Val CE:0.043507, Train ACC:1.000000, Val ACC:0.993750

Epoch 2515/4000: 100%|██████████| 1/1 [00:00<00:00, 23.00it/s]

epoch: 2514, beta = 0.000097, Train MSE: 0.006615, Train CE:0.011651, Train KL:8.767782, Val MSE:0.010325, Val CE:0.043538, Train ACC:1.000000, Val ACC:0.993750

Epoch 2516/4000: 100%|██████████| 1/1 [00:00<00:00, 20.59it/s]

epoch: 2515, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011646, Train KL:8.767789, Val MSE:0.010280, Val CE:0.043397, Train ACC:1.000000, Val ACC:0.993750

Epoch 2517/4000: 100%|██████████| 1/1 [00:00<00:00, 18.91it/s]

epoch: 2516, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011653, Train KL:8.767795, Val MSE:0.010290, Val CE:0.043430, Train ACC:1.000000, Val ACC:0.993750

Epoch 2518/4000: 100%|██████████| 1/1 [00:00<00:00, 23.49it/s]

epoch: 2517, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011651, Train KL:8.767801, Val MSE:0.010317, Val CE:0.043434, Train ACC:1.000000, Val ACC:0.993750

Epoch 2519/4000: 100%|██████████| 1/1 [00:00<00:00, 24.42it/s]

epoch: 2518, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011645, Train KL:8.767807, Val MSE:0.010296, Val CE:0.043366, Train ACC:1.000000, Val ACC:0.993750

Epoch 2520/4000: 100%|██████████| 1/1 [00:00<00:00, 25.90it/s]

epoch: 2519, beta = 0.000097, Train MSE: 0.006614, Train CE:0.011654, Train KL:8.767813, Val MSE:0.010283, Val CE:0.043346, Train ACC:1.000000, Val ACC:0.993750

Epoch 2521/4000: 100%|██████████| 1/1 [00:00<00:00, 23.65it/s]

Learning rate updated: 9.341364515150503e-07
epoch: 2520, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011652, Train KL:8.767818, Val MSE:0.010331, Val CE:0.043430, Train ACC:1.000000, Val ACC:0.993750

Epoch 2522/4000: 100%|██████████| 1/1 [00:00<00:00, 24.87it/s]

epoch: 2521, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011655, Train KL:8.767824, Val MSE:0.010269, Val CE:0.043389, Train ACC:1.000000, Val ACC:0.993750

Epoch 2523/4000: 100%|██████████| 1/1 [00:00<00:00, 23.74it/s]

epoch: 2522, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011653, Train KL:8.767829, Val MSE:0.010283, Val CE:0.043400, Train ACC:1.000000, Val ACC:0.993750

Epoch 2524/4000: 100%|██████████| 1/1 [00:00<00:00, 23.20it/s]

epoch: 2523, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011649, Train KL:8.767835, Val MSE:0.010301, Val CE:0.043418, Train ACC:1.000000, Val ACC:0.993750

Epoch 2525/4000: 100%|██████████| 1/1 [00:00<00:00, 23.94it/s]

epoch: 2524, beta = 0.000097, Train MSE: 0.006619, Train CE:0.011651, Train KL:8.767840, Val MSE:0.010313, Val CE:0.043459, Train ACC:1.000000, Val ACC:0.993750

Epoch 2526/4000: 100%|██████████| 1/1 [00:00<00:00, 23.95it/s]

epoch: 2525, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011654, Train KL:8.767845, Val MSE:0.010307, Val CE:0.043338, Train ACC:1.000000, Val ACC:0.993750

Epoch 2527/4000: 100%|██████████| 1/1 [00:00<00:00, 24.73it/s]

epoch: 2526, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011655, Train KL:8.767851, Val MSE:0.010275, Val CE:0.043352, Train ACC:1.000000, Val ACC:0.993750

Epoch 2528/4000: 100%|██████████| 1/1 [00:00<00:00, 23.20it/s]

epoch: 2527, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011648, Train KL:8.767856, Val MSE:0.010283, Val CE:0.043473, Train ACC:1.000000, Val ACC:0.993750

Epoch 2529/4000: 100%|██████████| 1/1 [00:00<00:00, 24.09it/s]

epoch: 2528, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011653, Train KL:8.767860, Val MSE:0.010288, Val CE:0.043342, Train ACC:1.000000, Val ACC:0.993750

Epoch 2530/4000: 100%|██████████| 1/1 [00:00<00:00, 23.78it/s]

epoch: 2529, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011651, Train KL:8.767866, Val MSE:0.010278, Val CE:0.043552, Train ACC:1.000000, Val ACC:0.993750

Epoch 2531/4000: 100%|██████████| 1/1 [00:00<00:00, 24.01it/s]

epoch: 2530, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011652, Train KL:8.767872, Val MSE:0.010301, Val CE:0.043587, Train ACC:1.000000, Val ACC:0.993750

Epoch 2532/4000: 100%|██████████| 1/1 [00:00<00:00, 22.05it/s]

Learning rate updated: 8.874296289392978e-07
epoch: 2531, beta = 0.000097, Train MSE: 0.006618, Train CE:0.011648, Train KL:8.767878, Val MSE:0.010286, Val CE:0.043450, Train ACC:1.000000, Val ACC:0.993750

Epoch 2533/4000: 100%|██████████| 1/1 [00:00<00:00, 22.11it/s]

epoch: 2532, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011648, Train KL:8.767883, Val MSE:0.010306, Val CE:0.043573, Train ACC:1.000000, Val ACC:0.993750

Epoch 2534/4000: 100%|██████████| 1/1 [00:00<00:00, 23.73it/s]

epoch: 2533, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011651, Train KL:8.767888, Val MSE:0.010266, Val CE:0.043280, Train ACC:1.000000, Val ACC:0.993750

Epoch 2535/4000: 100%|██████████| 1/1 [00:00<00:00, 20.01it/s]

epoch: 2534, beta = 0.000097, Train MSE: 0.006617, Train CE:0.011652, Train KL:8.767893, Val MSE:0.010265, Val CE:0.043442, Train ACC:1.000000, Val ACC:0.993750

Epoch 2536/4000: 100%|██████████| 1/1 [00:00<00:00, 22.81it/s]

epoch: 2535, beta = 0.000097, Train MSE: 0.006611, Train CE:0.011651, Train KL:8.767898, Val MSE:0.010290, Val CE:0.043316, Train ACC:1.000000, Val ACC:0.993750

Epoch 2537/4000: 100%|██████████| 1/1 [00:00<00:00, 18.98it/s]

epoch: 2536, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011645, Train KL:8.767903, Val MSE:0.010293, Val CE:0.043523, Train ACC:1.000000, Val ACC:0.993750

Epoch 2538/4000: 100%|██████████| 1/1 [00:00<00:00, 19.85it/s]

epoch: 2537, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011646, Train KL:8.767908, Val MSE:0.010274, Val CE:0.043389, Train ACC:1.000000, Val ACC:0.993750

Epoch 2539/4000: 100%|██████████| 1/1 [00:00<00:00, 22.47it/s]

epoch: 2538, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011649, Train KL:8.767913, Val MSE:0.010296, Val CE:0.043380, Train ACC:1.000000, Val ACC:0.993750

Epoch 2540/4000: 100%|██████████| 1/1 [00:00<00:00, 23.95it/s]

epoch: 2539, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011648, Train KL:8.767919, Val MSE:0.010259, Val CE:0.043416, Train ACC:1.000000, Val ACC:0.993750

Epoch 2541/4000: 100%|██████████| 1/1 [00:00<00:00, 23.98it/s]

epoch: 2540, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011655, Train KL:8.767923, Val MSE:0.010259, Val CE:0.043449, Train ACC:1.000000, Val ACC:0.993750

Epoch 2542/4000: 100%|██████████| 1/1 [00:00<00:00, 23.06it/s]

epoch: 2541, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011645, Train KL:8.767928, Val MSE:0.010263, Val CE:0.043245, Train ACC:1.000000, Val ACC:0.993750

Epoch 2543/4000: 100%|██████████| 1/1 [00:00<00:00, 24.58it/s]

Learning rate updated: 8.430581474923329e-07
epoch: 2542, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011646, Train KL:8.767934, Val MSE:0.010287, Val CE:0.043391, Train ACC:1.000000, Val ACC:0.993750

Epoch 2544/4000: 100%|██████████| 1/1 [00:00<00:00, 23.59it/s]

epoch: 2543, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011652, Train KL:8.767940, Val MSE:0.010301, Val CE:0.043330, Train ACC:1.000000, Val ACC:0.993750

Epoch 2545/4000: 100%|██████████| 1/1 [00:00<00:00, 23.99it/s]

epoch: 2544, beta = 0.000097, Train MSE: 0.006615, Train CE:0.011649, Train KL:8.767943, Val MSE:0.010281, Val CE:0.043533, Train ACC:1.000000, Val ACC:0.993750

Epoch 2546/4000: 100%|██████████| 1/1 [00:00<00:00, 22.84it/s]

epoch: 2545, beta = 0.000097, Train MSE: 0.006614, Train CE:0.011644, Train KL:8.767949, Val MSE:0.010290, Val CE:0.043534, Train ACC:1.000000, Val ACC:0.993750

Epoch 2547/4000: 100%|██████████| 1/1 [00:00<00:00, 23.94it/s]

epoch: 2546, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011654, Train KL:8.767954, Val MSE:0.010302, Val CE:0.043423, Train ACC:1.000000, Val ACC:0.993750

Epoch 2548/4000: 100%|██████████| 1/1 [00:00<00:00, 23.82it/s]

epoch: 2547, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011651, Train KL:8.767960, Val MSE:0.010272, Val CE:0.043306, Train ACC:1.000000, Val ACC:0.993750

Epoch 2549/4000: 100%|██████████| 1/1 [00:00<00:00, 24.01it/s]

epoch: 2548, beta = 0.000097, Train MSE: 0.006616, Train CE:0.011649, Train KL:8.767964, Val MSE:0.010291, Val CE:0.043446, Train ACC:1.000000, Val ACC:0.993750

Epoch 2550/4000: 100%|██████████| 1/1 [00:00<00:00, 23.66it/s]

epoch: 2549, beta = 0.000097, Train MSE: 0.006616, Train CE:0.011646, Train KL:8.767970, Val MSE:0.010302, Val CE:0.043481, Train ACC:1.000000, Val ACC:0.993750

Epoch 2551/4000: 100%|██████████| 1/1 [00:00<00:00, 20.36it/s]

epoch: 2550, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011641, Train KL:8.767975, Val MSE:0.010292, Val CE:0.043549, Train ACC:1.000000, Val ACC:0.993750

Epoch 2552/4000: 100%|██████████| 1/1 [00:00<00:00, 22.96it/s]

epoch: 2551, beta = 0.000097, Train MSE: 0.006611, Train CE:0.011649, Train KL:8.767980, Val MSE:0.010278, Val CE:0.043558, Train ACC:1.000000, Val ACC:0.993750

Epoch 2553/4000: 100%|██████████| 1/1 [00:00<00:00, 26.62it/s]

epoch: 2552, beta = 0.000097, Train MSE: 0.006614, Train CE:0.011650, Train KL:8.767985, Val MSE:0.010263, Val CE:0.043331, Train ACC:1.000000, Val ACC:0.993750

Epoch 2554/4000: 100%|██████████| 1/1 [00:00<00:00, 24.04it/s]

Learning rate updated: 8.009052401177162e-07
epoch: 2553, beta = 0.000097, Train MSE: 0.006614, Train CE:0.011641, Train KL:8.767990, Val MSE:0.010285, Val CE:0.043396, Train ACC:1.000000, Val ACC:0.993750

Epoch 2555/4000: 100%|██████████| 1/1 [00:00<00:00, 19.57it/s]

epoch: 2554, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011647, Train KL:8.767997, Val MSE:0.010293, Val CE:0.043304, Train ACC:1.000000, Val ACC:0.993750

Epoch 2556/4000: 100%|██████████| 1/1 [00:00<00:00, 21.15it/s]

epoch: 2555, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011643, Train KL:8.768001, Val MSE:0.010291, Val CE:0.043237, Train ACC:1.000000, Val ACC:0.993750

Epoch 2557/4000: 100%|██████████| 1/1 [00:00<00:00, 21.72it/s]

epoch: 2556, beta = 0.000097, Train MSE: 0.006614, Train CE:0.011645, Train KL:8.768005, Val MSE:0.010278, Val CE:0.043132, Train ACC:1.000000, Val ACC:0.993750

Epoch 2558/4000: 100%|██████████| 1/1 [00:00<00:00, 24.03it/s]

epoch: 2557, beta = 0.000097, Train MSE: 0.006613, Train CE:0.011643, Train KL:8.768012, Val MSE:0.010285, Val CE:0.043527, Train ACC:1.000000, Val ACC:0.993750

Epoch 2559/4000: 100%|██████████| 1/1 [00:00<00:00, 23.88it/s]

epoch: 2558, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011650, Train KL:8.768017, Val MSE:0.010285, Val CE:0.043477, Train ACC:1.000000, Val ACC:0.993750

Epoch 2560/4000: 100%|██████████| 1/1 [00:00<00:00, 23.52it/s]

epoch: 2559, beta = 0.000097, Train MSE: 0.006617, Train CE:0.011647, Train KL:8.768021, Val MSE:0.010273, Val CE:0.043355, Train ACC:1.000000, Val ACC:0.993750

Epoch 2561/4000: 100%|██████████| 1/1 [00:00<00:00, 24.05it/s]

epoch: 2560, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011645, Train KL:8.768025, Val MSE:0.010287, Val CE:0.043495, Train ACC:1.000000, Val ACC:0.993750

Epoch 2562/4000: 100%|██████████| 1/1 [00:00<00:00, 26.19it/s]

epoch: 2561, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011649, Train KL:8.768031, Val MSE:0.010291, Val CE:0.043380, Train ACC:1.000000, Val ACC:0.993750

Epoch 2563/4000: 100%|██████████| 1/1 [00:00<00:00, 24.10it/s]

epoch: 2562, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011650, Train KL:8.768036, Val MSE:0.010266, Val CE:0.043432, Train ACC:1.000000, Val ACC:0.993750

Epoch 2564/4000: 100%|██████████| 1/1 [00:00<00:00, 22.71it/s]

epoch: 2563, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011651, Train KL:8.768041, Val MSE:0.010287, Val CE:0.043270, Train ACC:1.000000, Val ACC:0.993750

Epoch 2565/4000: 100%|██████████| 1/1 [00:00<00:00, 24.18it/s]

Learning rate updated: 7.608599781118303e-07
epoch: 2564, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011650, Train KL:8.768045, Val MSE:0.010291, Val CE:0.043568, Train ACC:1.000000, Val ACC:0.993750

Epoch 2566/4000: 100%|██████████| 1/1 [00:00<00:00, 24.17it/s]

epoch: 2565, beta = 0.000097, Train MSE: 0.006611, Train CE:0.011645, Train KL:8.768050, Val MSE:0.010295, Val CE:0.043316, Train ACC:1.000000, Val ACC:0.993750

Epoch 2567/4000: 100%|██████████| 1/1 [00:00<00:00, 24.54it/s]

epoch: 2566, beta = 0.000097, Train MSE: 0.006615, Train CE:0.011651, Train KL:8.768055, Val MSE:0.010303, Val CE:0.043466, Train ACC:1.000000, Val ACC:0.993750

Epoch 2568/4000: 100%|██████████| 1/1 [00:00<00:00, 27.09it/s]

epoch: 2567, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011646, Train KL:8.768059, Val MSE:0.010266, Val CE:0.043448, Train ACC:1.000000, Val ACC:0.993750

Epoch 2569/4000: 100%|██████████| 1/1 [00:00<00:00, 23.56it/s]

epoch: 2568, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011647, Train KL:8.768064, Val MSE:0.010295, Val CE:0.043270, Train ACC:1.000000, Val ACC:0.993750

Epoch 2570/4000: 100%|██████████| 1/1 [00:00<00:00, 22.43it/s]

epoch: 2569, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011648, Train KL:8.768068, Val MSE:0.010277, Val CE:0.043470, Train ACC:1.000000, Val ACC:0.993750

Epoch 2571/4000: 100%|██████████| 1/1 [00:00<00:00, 23.93it/s]

epoch: 2570, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011649, Train KL:8.768074, Val MSE:0.010275, Val CE:0.043348, Train ACC:1.000000, Val ACC:0.993750

Epoch 2572/4000: 100%|██████████| 1/1 [00:00<00:00, 22.18it/s]

epoch: 2571, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011641, Train KL:8.768078, Val MSE:0.010304, Val CE:0.043612, Train ACC:1.000000, Val ACC:0.993750

Epoch 2573/4000: 100%|██████████| 1/1 [00:00<00:00, 17.06it/s]

epoch: 2572, beta = 0.000097, Train MSE: 0.006617, Train CE:0.011648, Train KL:8.768083, Val MSE:0.010269, Val CE:0.043481, Train ACC:1.000000, Val ACC:0.993750

Epoch 2574/4000: 100%|██████████| 1/1 [00:00<00:00, 22.52it/s]

epoch: 2573, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011646, Train KL:8.768088, Val MSE:0.010260, Val CE:0.043495, Train ACC:1.000000, Val ACC:0.993750

Epoch 2575/4000: 100%|██████████| 1/1 [00:00<00:00, 21.95it/s]

epoch: 2574, beta = 0.000097, Train MSE: 0.006617, Train CE:0.011645, Train KL:8.768093, Val MSE:0.010285, Val CE:0.043567, Train ACC:1.000000, Val ACC:0.993750

Epoch 2576/4000: 100%|██████████| 1/1 [00:00<00:00, 27.43it/s]

Learning rate updated: 7.228169792062388e-07
epoch: 2575, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011645, Train KL:8.768097, Val MSE:0.010279, Val CE:0.043662, Train ACC:1.000000, Val ACC:0.993750

Epoch 2577/4000: 100%|██████████| 1/1 [00:00<00:00, 25.70it/s]

epoch: 2576, beta = 0.000097, Train MSE: 0.006616, Train CE:0.011647, Train KL:8.768104, Val MSE:0.010286, Val CE:0.043352, Train ACC:1.000000, Val ACC:0.993750

Epoch 2578/4000: 100%|██████████| 1/1 [00:00<00:00, 23.84it/s]

epoch: 2577, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011641, Train KL:8.768108, Val MSE:0.010293, Val CE:0.043364, Train ACC:1.000000, Val ACC:0.993750

Epoch 2579/4000: 100%|██████████| 1/1 [00:00<00:00, 24.60it/s]

epoch: 2578, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011650, Train KL:8.768113, Val MSE:0.010284, Val CE:0.043280, Train ACC:1.000000, Val ACC:0.993750

Epoch 2580/4000: 100%|██████████| 1/1 [00:00<00:00, 22.26it/s]

epoch: 2579, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011645, Train KL:8.768118, Val MSE:0.010277, Val CE:0.043330, Train ACC:1.000000, Val ACC:0.993750

Epoch 2581/4000: 100%|██████████| 1/1 [00:00<00:00, 23.96it/s]

epoch: 2580, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011647, Train KL:8.768123, Val MSE:0.010274, Val CE:0.043297, Train ACC:1.000000, Val ACC:0.993750

Epoch 2582/4000: 100%|██████████| 1/1 [00:00<00:00, 22.37it/s]

epoch: 2581, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011639, Train KL:8.768126, Val MSE:0.010299, Val CE:0.043370, Train ACC:1.000000, Val ACC:0.993750

Epoch 2583/4000: 100%|██████████| 1/1 [00:00<00:00, 24.36it/s]

epoch: 2582, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011644, Train KL:8.768131, Val MSE:0.010326, Val CE:0.043705, Train ACC:1.000000, Val ACC:0.993750

Epoch 2584/4000: 100%|██████████| 1/1 [00:00<00:00, 23.63it/s]

epoch: 2583, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011643, Train KL:8.768136, Val MSE:0.010300, Val CE:0.043507, Train ACC:1.000000, Val ACC:0.993750

Epoch 2585/4000: 100%|██████████| 1/1 [00:00<00:00, 21.96it/s]

epoch: 2584, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011645, Train KL:8.768140, Val MSE:0.010279, Val CE:0.043418, Train ACC:1.000000, Val ACC:0.993750

Epoch 2586/4000: 100%|██████████| 1/1 [00:00<00:00, 24.09it/s]

epoch: 2585, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011644, Train KL:8.768145, Val MSE:0.010292, Val CE:0.043469, Train ACC:1.000000, Val ACC:0.993750

Epoch 2587/4000: 100%|██████████| 1/1 [00:00<00:00, 24.16it/s]

Learning rate updated: 6.866761302459269e-07
epoch: 2586, beta = 0.000097, Train MSE: 0.006611, Train CE:0.011645, Train KL:8.768149, Val MSE:0.010291, Val CE:0.043519, Train ACC:1.000000, Val ACC:0.993750

Epoch 2588/4000: 100%|██████████| 1/1 [00:00<00:00, 23.27it/s]

epoch: 2587, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011644, Train KL:8.768155, Val MSE:0.010263, Val CE:0.043338, Train ACC:1.000000, Val ACC:0.993750

Epoch 2589/4000: 100%|██████████| 1/1 [00:00<00:00, 22.86it/s]

epoch: 2588, beta = 0.000097, Train MSE: 0.006621, Train CE:0.011640, Train KL:8.768159, Val MSE:0.010270, Val CE:0.043477, Train ACC:1.000000, Val ACC:0.993750

Epoch 2590/4000: 100%|██████████| 1/1 [00:00<00:00, 23.98it/s]

epoch: 2589, beta = 0.000097, Train MSE: 0.006615, Train CE:0.011642, Train KL:8.768163, Val MSE:0.010295, Val CE:0.043474, Train ACC:1.000000, Val ACC:0.993750

Epoch 2591/4000: 100%|██████████| 1/1 [00:00<00:00, 20.67it/s]

epoch: 2590, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011651, Train KL:8.768167, Val MSE:0.010297, Val CE:0.043281, Train ACC:1.000000, Val ACC:0.993750

Epoch 2592/4000: 100%|██████████| 1/1 [00:00<00:00, 21.14it/s]

epoch: 2591, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011645, Train KL:8.768172, Val MSE:0.010266, Val CE:0.043440, Train ACC:1.000000, Val ACC:0.993750

Epoch 2593/4000: 100%|██████████| 1/1 [00:00<00:00, 23.87it/s]

epoch: 2592, beta = 0.000097, Train MSE: 0.006611, Train CE:0.011645, Train KL:8.768176, Val MSE:0.010307, Val CE:0.043461, Train ACC:1.000000, Val ACC:0.993750

Epoch 2594/4000: 100%|██████████| 1/1 [00:00<00:00, 24.08it/s]

epoch: 2593, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011651, Train KL:8.768181, Val MSE:0.010297, Val CE:0.043425, Train ACC:1.000000, Val ACC:0.993750

Epoch 2595/4000: 100%|██████████| 1/1 [00:00<00:00, 25.78it/s]

epoch: 2594, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011646, Train KL:8.768185, Val MSE:0.010293, Val CE:0.043346, Train ACC:1.000000, Val ACC:0.993750

Epoch 2596/4000: 100%|██████████| 1/1 [00:00<00:00, 24.74it/s]

epoch: 2595, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011645, Train KL:8.768189, Val MSE:0.010284, Val CE:0.043544, Train ACC:1.000000, Val ACC:0.993750

Epoch 2597/4000: 100%|██████████| 1/1 [00:00<00:00, 23.58it/s]

epoch: 2596, beta = 0.000097, Train MSE: 0.006614, Train CE:0.011645, Train KL:8.768193, Val MSE:0.010290, Val CE:0.043431, Train ACC:1.000000, Val ACC:0.993750

Epoch 2598/4000: 100%|██████████| 1/1 [00:00<00:00, 24.26it/s]

Learning rate updated: 6.523423237336305e-07
epoch: 2597, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011647, Train KL:8.768197, Val MSE:0.010313, Val CE:0.043556, Train ACC:1.000000, Val ACC:0.993750

Epoch 2599/4000: 100%|██████████| 1/1 [00:00<00:00, 24.44it/s]

epoch: 2598, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011650, Train KL:8.768201, Val MSE:0.010305, Val CE:0.043504, Train ACC:1.000000, Val ACC:0.993750

Epoch 2600/4000: 100%|██████████| 1/1 [00:00<00:00, 24.07it/s]

epoch: 2599, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011646, Train KL:8.768205, Val MSE:0.010272, Val CE:0.043438, Train ACC:1.000000, Val ACC:0.993750

Epoch 2601/4000: 100%|██████████| 1/1 [00:00<00:00, 23.96it/s]

epoch: 2600, beta = 0.000097, Train MSE: 0.006614, Train CE:0.011642, Train KL:8.768209, Val MSE:0.010282, Val CE:0.043546, Train ACC:1.000000, Val ACC:0.993750

Epoch 2602/4000: 100%|██████████| 1/1 [00:00<00:00, 23.98it/s]

epoch: 2601, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011651, Train KL:8.768212, Val MSE:0.010271, Val CE:0.043612, Train ACC:1.000000, Val ACC:0.993750

Epoch 2603/4000: 100%|██████████| 1/1 [00:00<00:00, 24.23it/s]

epoch: 2602, beta = 0.000097, Train MSE: 0.006614, Train CE:0.011644, Train KL:8.768216, Val MSE:0.010259, Val CE:0.043481, Train ACC:1.000000, Val ACC:0.993750

Epoch 2604/4000: 100%|██████████| 1/1 [00:00<00:00, 24.59it/s]

epoch: 2603, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011641, Train KL:8.768220, Val MSE:0.010306, Val CE:0.043481, Train ACC:1.000000, Val ACC:0.993750

Epoch 2605/4000: 100%|██████████| 1/1 [00:00<00:00, 23.06it/s]

epoch: 2604, beta = 0.000097, Train MSE: 0.006617, Train CE:0.011644, Train KL:8.768226, Val MSE:0.010310, Val CE:0.043409, Train ACC:1.000000, Val ACC:0.993750

Epoch 2606/4000: 100%|██████████| 1/1 [00:00<00:00, 22.45it/s]

epoch: 2605, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011641, Train KL:8.768229, Val MSE:0.010306, Val CE:0.043465, Train ACC:1.000000, Val ACC:0.993750

Epoch 2607/4000: 100%|██████████| 1/1 [00:00<00:00, 21.48it/s]

epoch: 2606, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011641, Train KL:8.768233, Val MSE:0.010255, Val CE:0.043573, Train ACC:1.000000, Val ACC:0.993750

Epoch 2608/4000: 100%|██████████| 1/1 [00:00<00:00, 22.98it/s]

epoch: 2607, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011646, Train KL:8.768236, Val MSE:0.010304, Val CE:0.043327, Train ACC:1.000000, Val ACC:0.993750

Epoch 2609/4000: 100%|██████████| 1/1 [00:00<00:00, 24.02it/s]

Learning rate updated: 6.197252075469489e-07
epoch: 2608, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011641, Train KL:8.768240, Val MSE:0.010281, Val CE:0.043458, Train ACC:1.000000, Val ACC:0.993750

Epoch 2610/4000: 100%|██████████| 1/1 [00:00<00:00, 24.31it/s]

epoch: 2609, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011641, Train KL:8.768244, Val MSE:0.010308, Val CE:0.043279, Train ACC:1.000000, Val ACC:0.993750

Epoch 2611/4000: 100%|██████████| 1/1 [00:00<00:00, 22.50it/s]

epoch: 2610, beta = 0.000097, Train MSE: 0.006615, Train CE:0.011640, Train KL:8.768248, Val MSE:0.010295, Val CE:0.043291, Train ACC:1.000000, Val ACC:0.993750

Epoch 2612/4000: 100%|██████████| 1/1 [00:00<00:00, 24.80it/s]

epoch: 2611, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011645, Train KL:8.768251, Val MSE:0.010281, Val CE:0.043625, Train ACC:1.000000, Val ACC:0.993750

Epoch 2613/4000: 100%|██████████| 1/1 [00:00<00:00, 24.22it/s]

epoch: 2612, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011646, Train KL:8.768255, Val MSE:0.010268, Val CE:0.043391, Train ACC:1.000000, Val ACC:0.993750

Epoch 2614/4000: 100%|██████████| 1/1 [00:00<00:00, 24.01it/s]

epoch: 2613, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011642, Train KL:8.768259, Val MSE:0.010295, Val CE:0.043307, Train ACC:1.000000, Val ACC:0.993750

Epoch 2615/4000: 100%|██████████| 1/1 [00:00<00:00, 24.50it/s]

epoch: 2614, beta = 0.000097, Train MSE: 0.006619, Train CE:0.011647, Train KL:8.768263, Val MSE:0.010290, Val CE:0.043504, Train ACC:1.000000, Val ACC:0.993750

Epoch 2616/4000: 100%|██████████| 1/1 [00:00<00:00, 27.20it/s]

epoch: 2615, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011644, Train KL:8.768266, Val MSE:0.010283, Val CE:0.043452, Train ACC:1.000000, Val ACC:0.993750

Epoch 2617/4000: 100%|██████████| 1/1 [00:00<00:00, 24.18it/s]

epoch: 2616, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011644, Train KL:8.768270, Val MSE:0.010295, Val CE:0.043386, Train ACC:1.000000, Val ACC:0.993750

Epoch 2618/4000: 100%|██████████| 1/1 [00:00<00:00, 24.20it/s]

epoch: 2617, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011640, Train KL:8.768273, Val MSE:0.010273, Val CE:0.043437, Train ACC:1.000000, Val ACC:0.993750

Epoch 2619/4000: 100%|██████████| 1/1 [00:00<00:00, 24.68it/s]

epoch: 2618, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011642, Train KL:8.768278, Val MSE:0.010314, Val CE:0.043687, Train ACC:1.000000, Val ACC:0.993750

Epoch 2620/4000: 100%|██████████| 1/1 [00:00<00:00, 24.11it/s]

Learning rate updated: 5.887389471696014e-07
epoch: 2619, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011645, Train KL:8.768282, Val MSE:0.010287, Val CE:0.043273, Train ACC:1.000000, Val ACC:0.993750

Epoch 2621/4000: 100%|██████████| 1/1 [00:00<00:00, 23.89it/s]

epoch: 2620, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011643, Train KL:8.768286, Val MSE:0.010284, Val CE:0.043551, Train ACC:1.000000, Val ACC:0.993750

Epoch 2622/4000: 100%|██████████| 1/1 [00:00<00:00, 24.47it/s]

epoch: 2621, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011647, Train KL:8.768289, Val MSE:0.010279, Val CE:0.043370, Train ACC:1.000000, Val ACC:0.993750

Epoch 2623/4000: 100%|██████████| 1/1 [00:00<00:00, 23.21it/s]

epoch: 2622, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011649, Train KL:8.768292, Val MSE:0.010242, Val CE:0.043356, Train ACC:1.000000, Val ACC:0.993750

Epoch 2624/4000: 100%|██████████| 1/1 [00:00<00:00, 22.41it/s]

epoch: 2623, beta = 0.000097, Train MSE: 0.006611, Train CE:0.011648, Train KL:8.768296, Val MSE:0.010270, Val CE:0.043509, Train ACC:1.000000, Val ACC:0.993750

Epoch 2625/4000: 100%|██████████| 1/1 [00:00<00:00, 23.67it/s]

epoch: 2624, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011643, Train KL:8.768300, Val MSE:0.010291, Val CE:0.043499, Train ACC:1.000000, Val ACC:0.993750

Epoch 2626/4000: 100%|██████████| 1/1 [00:00<00:00, 22.42it/s]

epoch: 2625, beta = 0.000097, Train MSE: 0.006614, Train CE:0.011646, Train KL:8.768304, Val MSE:0.010285, Val CE:0.043429, Train ACC:1.000000, Val ACC:0.993750

Epoch 2627/4000: 100%|██████████| 1/1 [00:00<00:00, 19.52it/s]

epoch: 2626, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011640, Train KL:8.768307, Val MSE:0.010258, Val CE:0.043242, Train ACC:1.000000, Val ACC:0.993750

Epoch 2628/4000: 100%|██████████| 1/1 [00:00<00:00, 20.67it/s]

epoch: 2627, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011645, Train KL:8.768311, Val MSE:0.010294, Val CE:0.043363, Train ACC:1.000000, Val ACC:0.993750

Epoch 2629/4000: 100%|██████████| 1/1 [00:00<00:00, 19.50it/s]

epoch: 2628, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011645, Train KL:8.768314, Val MSE:0.010282, Val CE:0.043337, Train ACC:1.000000, Val ACC:0.993750

Epoch 2630/4000: 100%|██████████| 1/1 [00:00<00:00, 24.07it/s]

epoch: 2629, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011642, Train KL:8.768318, Val MSE:0.010283, Val CE:0.043231, Train ACC:1.000000, Val ACC:0.993750

Epoch 2631/4000: 100%|██████████| 1/1 [00:00<00:00, 24.09it/s]

Learning rate updated: 5.593019998111213e-07
epoch: 2630, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011642, Train KL:8.768321, Val MSE:0.010280, Val CE:0.043325, Train ACC:1.000000, Val ACC:0.993750

Epoch 2632/4000: 100%|██████████| 1/1 [00:00<00:00, 25.41it/s]

epoch: 2631, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011643, Train KL:8.768325, Val MSE:0.010304, Val CE:0.043393, Train ACC:1.000000, Val ACC:0.993750

Epoch 2633/4000: 100%|██████████| 1/1 [00:00<00:00, 23.95it/s]

epoch: 2632, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011645, Train KL:8.768328, Val MSE:0.010296, Val CE:0.043557, Train ACC:1.000000, Val ACC:0.993750

Epoch 2634/4000: 100%|██████████| 1/1 [00:00<00:00, 23.94it/s]

epoch: 2633, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011641, Train KL:8.768332, Val MSE:0.010283, Val CE:0.043284, Train ACC:1.000000, Val ACC:0.993750

Epoch 2635/4000: 100%|██████████| 1/1 [00:00<00:00, 24.26it/s]

epoch: 2634, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011644, Train KL:8.768335, Val MSE:0.010284, Val CE:0.043721, Train ACC:1.000000, Val ACC:0.993750

Epoch 2636/4000: 100%|██████████| 1/1 [00:00<00:00, 21.79it/s]

epoch: 2635, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011647, Train KL:8.768339, Val MSE:0.010295, Val CE:0.043067, Train ACC:1.000000, Val ACC:0.993750

Epoch 2637/4000: 100%|██████████| 1/1 [00:00<00:00, 24.21it/s]

epoch: 2636, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011641, Train KL:8.768343, Val MSE:0.010285, Val CE:0.043336, Train ACC:1.000000, Val ACC:0.993750

Epoch 2638/4000: 100%|██████████| 1/1 [00:00<00:00, 24.04it/s]

epoch: 2637, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011640, Train KL:8.768346, Val MSE:0.010314, Val CE:0.043316, Train ACC:1.000000, Val ACC:0.993750

Epoch 2639/4000: 100%|██████████| 1/1 [00:00<00:00, 24.26it/s]

epoch: 2638, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011640, Train KL:8.768350, Val MSE:0.010295, Val CE:0.043480, Train ACC:1.000000, Val ACC:0.993750

Epoch 2640/4000: 100%|██████████| 1/1 [00:00<00:00, 23.54it/s]

epoch: 2639, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011643, Train KL:8.768353, Val MSE:0.010292, Val CE:0.043477, Train ACC:1.000000, Val ACC:0.993750

Epoch 2641/4000: 100%|██████████| 1/1 [00:00<00:00, 22.74it/s]

epoch: 2640, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011640, Train KL:8.768357, Val MSE:0.010278, Val CE:0.043338, Train ACC:1.000000, Val ACC:0.993750

Epoch 2642/4000: 100%|██████████| 1/1 [00:00<00:00, 19.21it/s]

Learning rate updated: 5.313368998205652e-07
epoch: 2641, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011643, Train KL:8.768360, Val MSE:0.010318, Val CE:0.043263, Train ACC:1.000000, Val ACC:0.993750

Epoch 2643/4000: 100%|██████████| 1/1 [00:00<00:00, 21.44it/s]

epoch: 2642, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011645, Train KL:8.768363, Val MSE:0.010302, Val CE:0.043468, Train ACC:1.000000, Val ACC:0.993750

Epoch 2644/4000: 100%|██████████| 1/1 [00:00<00:00, 24.35it/s]

epoch: 2643, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011644, Train KL:8.768367, Val MSE:0.010256, Val CE:0.043425, Train ACC:1.000000, Val ACC:0.993750

Epoch 2645/4000: 100%|██████████| 1/1 [00:00<00:00, 23.91it/s]

epoch: 2644, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011639, Train KL:8.768370, Val MSE:0.010292, Val CE:0.043473, Train ACC:1.000000, Val ACC:0.993229

Epoch 2646/4000: 100%|██████████| 1/1 [00:00<00:00, 25.13it/s]

epoch: 2645, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011641, Train KL:8.768373, Val MSE:0.010293, Val CE:0.043398, Train ACC:1.000000, Val ACC:0.993750

Epoch 2647/4000: 100%|██████████| 1/1 [00:00<00:00, 24.09it/s]

epoch: 2646, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011638, Train KL:8.768377, Val MSE:0.010275, Val CE:0.043643, Train ACC:1.000000, Val ACC:0.993750

Epoch 2648/4000: 100%|██████████| 1/1 [00:00<00:00, 23.40it/s]

epoch: 2647, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011646, Train KL:8.768380, Val MSE:0.010263, Val CE:0.043443, Train ACC:1.000000, Val ACC:0.993750

Epoch 2649/4000: 100%|██████████| 1/1 [00:00<00:00, 24.35it/s]

epoch: 2648, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011639, Train KL:8.768383, Val MSE:0.010301, Val CE:0.043438, Train ACC:1.000000, Val ACC:0.993750

Epoch 2650/4000: 100%|██████████| 1/1 [00:00<00:00, 22.51it/s]

epoch: 2649, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011643, Train KL:8.768387, Val MSE:0.010286, Val CE:0.043657, Train ACC:1.000000, Val ACC:0.993750

Epoch 2651/4000: 100%|██████████| 1/1 [00:00<00:00, 23.99it/s]

epoch: 2650, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011641, Train KL:8.768391, Val MSE:0.010283, Val CE:0.043426, Train ACC:1.000000, Val ACC:0.993750

Epoch 2652/4000: 100%|██████████| 1/1 [00:00<00:00, 21.89it/s]

epoch: 2651, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011642, Train KL:8.768394, Val MSE:0.010257, Val CE:0.043470, Train ACC:1.000000, Val ACC:0.993750

Epoch 2653/4000: 100%|██████████| 1/1 [00:00<00:00, 23.97it/s]

Learning rate updated: 5.047700548295369e-07
epoch: 2652, beta = 0.000097, Train MSE: 0.006619, Train CE:0.011642, Train KL:8.768397, Val MSE:0.010284, Val CE:0.043403, Train ACC:1.000000, Val ACC:0.993750

Epoch 2654/4000: 100%|██████████| 1/1 [00:00<00:00, 23.41it/s]

epoch: 2653, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011642, Train KL:8.768400, Val MSE:0.010289, Val CE:0.043378, Train ACC:1.000000, Val ACC:0.993750

Epoch 2655/4000: 100%|██████████| 1/1 [00:00<00:00, 24.10it/s]

epoch: 2654, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011640, Train KL:8.768404, Val MSE:0.010288, Val CE:0.043544, Train ACC:1.000000, Val ACC:0.993750

Epoch 2656/4000: 100%|██████████| 1/1 [00:00<00:00, 22.09it/s]

epoch: 2655, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011644, Train KL:8.768407, Val MSE:0.010271, Val CE:0.043578, Train ACC:1.000000, Val ACC:0.993750

Epoch 2657/4000: 100%|██████████| 1/1 [00:00<00:00, 24.50it/s]

epoch: 2656, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011642, Train KL:8.768411, Val MSE:0.010276, Val CE:0.043254, Train ACC:1.000000, Val ACC:0.993750

Epoch 2658/4000: 100%|██████████| 1/1 [00:00<00:00, 23.41it/s]

epoch: 2657, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011642, Train KL:8.768414, Val MSE:0.010275, Val CE:0.043501, Train ACC:1.000000, Val ACC:0.993750

Epoch 2659/4000: 100%|██████████| 1/1 [00:00<00:00, 24.08it/s]

epoch: 2658, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011643, Train KL:8.768416, Val MSE:0.010311, Val CE:0.043455, Train ACC:1.000000, Val ACC:0.993750

Epoch 2660/4000: 100%|██████████| 1/1 [00:00<00:00, 23.24it/s]

epoch: 2659, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011644, Train KL:8.768420, Val MSE:0.010299, Val CE:0.043455, Train ACC:1.000000, Val ACC:0.993750

Epoch 2661/4000: 100%|██████████| 1/1 [00:00<00:00, 19.96it/s]

epoch: 2660, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011641, Train KL:8.768423, Val MSE:0.010312, Val CE:0.043569, Train ACC:1.000000, Val ACC:0.993750

Epoch 2662/4000: 100%|██████████| 1/1 [00:00<00:00, 23.72it/s]

epoch: 2661, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011644, Train KL:8.768426, Val MSE:0.010302, Val CE:0.043418, Train ACC:1.000000, Val ACC:0.993750

Epoch 2663/4000: 100%|██████████| 1/1 [00:00<00:00, 23.71it/s]

epoch: 2662, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011641, Train KL:8.768429, Val MSE:0.010268, Val CE:0.043592, Train ACC:1.000000, Val ACC:0.993750

Epoch 2664/4000: 100%|██████████| 1/1 [00:00<00:00, 24.27it/s]

Learning rate updated: 4.7953155208806e-07
epoch: 2663, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011636, Train KL:8.768432, Val MSE:0.010296, Val CE:0.043249, Train ACC:1.000000, Val ACC:0.993750

Epoch 2665/4000: 100%|██████████| 1/1 [00:00<00:00, 24.82it/s]

epoch: 2664, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011635, Train KL:8.768435, Val MSE:0.010300, Val CE:0.043502, Train ACC:1.000000, Val ACC:0.993750

Epoch 2666/4000: 100%|██████████| 1/1 [00:00<00:00, 24.12it/s]

epoch: 2665, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011641, Train KL:8.768437, Val MSE:0.010293, Val CE:0.043499, Train ACC:1.000000, Val ACC:0.993750

Epoch 2667/4000: 100%|██████████| 1/1 [00:00<00:00, 23.60it/s]

epoch: 2666, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011637, Train KL:8.768439, Val MSE:0.010307, Val CE:0.043378, Train ACC:1.000000, Val ACC:0.993750

Epoch 2668/4000: 100%|██████████| 1/1 [00:00<00:00, 20.74it/s]

epoch: 2667, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011641, Train KL:8.768443, Val MSE:0.010287, Val CE:0.043493, Train ACC:1.000000, Val ACC:0.993750

Epoch 2669/4000: 100%|██████████| 1/1 [00:00<00:00, 22.93it/s]

epoch: 2668, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011644, Train KL:8.768445, Val MSE:0.010282, Val CE:0.043338, Train ACC:1.000000, Val ACC:0.993750

Epoch 2670/4000: 100%|██████████| 1/1 [00:00<00:00, 22.45it/s]

epoch: 2669, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011641, Train KL:8.768448, Val MSE:0.010304, Val CE:0.043352, Train ACC:1.000000, Val ACC:0.993750

Epoch 2671/4000: 100%|██████████| 1/1 [00:00<00:00, 23.77it/s]

epoch: 2670, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011643, Train KL:8.768451, Val MSE:0.010284, Val CE:0.043507, Train ACC:1.000000, Val ACC:0.993750

Epoch 2672/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 2671, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011634, Train KL:8.768453, Val MSE:0.010282, Val CE:0.043352, Train ACC:1.000000, Val ACC:0.993750

Epoch 2673/4000: 100%|██████████| 1/1 [00:00<00:00, 23.41it/s]

epoch: 2672, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011641, Train KL:8.768455, Val MSE:0.010305, Val CE:0.043324, Train ACC:1.000000, Val ACC:0.993750

Epoch 2674/4000: 100%|██████████| 1/1 [00:00<00:00, 23.42it/s]

epoch: 2673, beta = 0.000097, Train MSE: 0.006615, Train CE:0.011640, Train KL:8.768457, Val MSE:0.010293, Val CE:0.043589, Train ACC:1.000000, Val ACC:0.993750

Epoch 2675/4000: 100%|██████████| 1/1 [00:00<00:00, 22.84it/s]

Learning rate updated: 4.55554974483657e-07
epoch: 2674, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011637, Train KL:8.768459, Val MSE:0.010289, Val CE:0.043563, Train ACC:1.000000, Val ACC:0.993750

Epoch 2676/4000: 100%|██████████| 1/1 [00:00<00:00, 24.04it/s]

epoch: 2675, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011641, Train KL:8.768462, Val MSE:0.010263, Val CE:0.043335, Train ACC:1.000000, Val ACC:0.993750

Epoch 2677/4000: 100%|██████████| 1/1 [00:00<00:00, 24.06it/s]

epoch: 2676, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011642, Train KL:8.768465, Val MSE:0.010255, Val CE:0.043483, Train ACC:1.000000, Val ACC:0.993750

Epoch 2678/4000: 100%|██████████| 1/1 [00:00<00:00, 23.64it/s]

epoch: 2677, beta = 0.000097, Train MSE: 0.006611, Train CE:0.011637, Train KL:8.768467, Val MSE:0.010270, Val CE:0.043504, Train ACC:1.000000, Val ACC:0.993750

Epoch 2679/4000: 100%|██████████| 1/1 [00:00<00:00, 24.62it/s]

epoch: 2678, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011640, Train KL:8.768470, Val MSE:0.010273, Val CE:0.043490, Train ACC:1.000000, Val ACC:0.993750

Epoch 2680/4000: 100%|██████████| 1/1 [00:00<00:00, 19.01it/s]

epoch: 2679, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011637, Train KL:8.768472, Val MSE:0.010289, Val CE:0.043212, Train ACC:1.000000, Val ACC:0.993750

Epoch 2681/4000: 100%|██████████| 1/1 [00:00<00:00, 21.26it/s]

epoch: 2680, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011636, Train KL:8.768475, Val MSE:0.010306, Val CE:0.043556, Train ACC:1.000000, Val ACC:0.993750

Epoch 2682/4000: 100%|██████████| 1/1 [00:00<00:00, 23.72it/s]

epoch: 2681, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011644, Train KL:8.768476, Val MSE:0.010304, Val CE:0.043454, Train ACC:1.000000, Val ACC:0.993750

Epoch 2683/4000: 100%|██████████| 1/1 [00:00<00:00, 22.75it/s]

epoch: 2682, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011639, Train KL:8.768478, Val MSE:0.010288, Val CE:0.043365, Train ACC:1.000000, Val ACC:0.993750

Epoch 2684/4000: 100%|██████████| 1/1 [00:00<00:00, 22.94it/s]

epoch: 2683, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011636, Train KL:8.768480, Val MSE:0.010279, Val CE:0.043645, Train ACC:1.000000, Val ACC:0.993750

Epoch 2685/4000: 100%|██████████| 1/1 [00:00<00:00, 22.95it/s]

epoch: 2684, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011641, Train KL:8.768482, Val MSE:0.010287, Val CE:0.043322, Train ACC:1.000000, Val ACC:0.993750

Epoch 2686/4000: 100%|██████████| 1/1 [00:00<00:00, 23.95it/s]

Learning rate updated: 4.327772257594741e-07
epoch: 2685, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011645, Train KL:8.768484, Val MSE:0.010305, Val CE:0.043542, Train ACC:1.000000, Val ACC:0.993750

Epoch 2687/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 2686, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011640, Train KL:8.768487, Val MSE:0.010300, Val CE:0.043457, Train ACC:1.000000, Val ACC:0.993750

Epoch 2688/4000: 100%|██████████| 1/1 [00:00<00:00, 26.39it/s]

epoch: 2687, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011638, Train KL:8.768489, Val MSE:0.010279, Val CE:0.043591, Train ACC:1.000000, Val ACC:0.993750

Epoch 2689/4000: 100%|██████████| 1/1 [00:00<00:00, 23.11it/s]

epoch: 2688, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011639, Train KL:8.768491, Val MSE:0.010281, Val CE:0.043301, Train ACC:1.000000, Val ACC:0.993750

Epoch 2690/4000: 100%|██████████| 1/1 [00:00<00:00, 26.73it/s]

epoch: 2689, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011638, Train KL:8.768494, Val MSE:0.010291, Val CE:0.043530, Train ACC:1.000000, Val ACC:0.993750

Epoch 2691/4000: 100%|██████████| 1/1 [00:00<00:00, 23.99it/s]

epoch: 2690, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011639, Train KL:8.768497, Val MSE:0.010260, Val CE:0.043367, Train ACC:1.000000, Val ACC:0.993750

Epoch 2692/4000: 100%|██████████| 1/1 [00:00<00:00, 23.62it/s]

epoch: 2691, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011640, Train KL:8.768498, Val MSE:0.010278, Val CE:0.043593, Train ACC:1.000000, Val ACC:0.993750

Epoch 2693/4000: 100%|██████████| 1/1 [00:00<00:00, 26.08it/s]

epoch: 2692, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011646, Train KL:8.768501, Val MSE:0.010273, Val CE:0.043623, Train ACC:1.000000, Val ACC:0.993750

Epoch 2694/4000: 100%|██████████| 1/1 [00:00<00:00, 24.27it/s]

epoch: 2693, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011641, Train KL:8.768504, Val MSE:0.010275, Val CE:0.043480, Train ACC:1.000000, Val ACC:0.993750

Epoch 2695/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 2694, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011638, Train KL:8.768507, Val MSE:0.010275, Val CE:0.043419, Train ACC:1.000000, Val ACC:0.993750

Epoch 2696/4000: 100%|██████████| 1/1 [00:00<00:00, 26.03it/s]

epoch: 2695, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011648, Train KL:8.768510, Val MSE:0.010259, Val CE:0.043414, Train ACC:1.000000, Val ACC:0.993750

Epoch 2697/4000: 100%|██████████| 1/1 [00:00<00:00, 25.85it/s]

Learning rate updated: 4.111383644715004e-07
epoch: 2696, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011636, Train KL:8.768513, Val MSE:0.010260, Val CE:0.043343, Train ACC:1.000000, Val ACC:0.993750

Epoch 2698/4000: 100%|██████████| 1/1 [00:00<00:00, 24.63it/s]

epoch: 2697, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011642, Train KL:8.768517, Val MSE:0.010315, Val CE:0.043508, Train ACC:1.000000, Val ACC:0.993750

Epoch 2699/4000: 100%|██████████| 1/1 [00:00<00:00, 20.75it/s]

epoch: 2698, beta = 0.000097, Train MSE: 0.006613, Train CE:0.011641, Train KL:8.768519, Val MSE:0.010266, Val CE:0.043676, Train ACC:1.000000, Val ACC:0.993750

Epoch 2700/4000: 100%|██████████| 1/1 [00:00<00:00, 18.41it/s]

epoch: 2699, beta = 0.000097, Train MSE: 0.006611, Train CE:0.011636, Train KL:8.768521, Val MSE:0.010275, Val CE:0.043502, Train ACC:1.000000, Val ACC:0.993750

Epoch 2701/4000: 100%|██████████| 1/1 [00:00<00:00, 21.57it/s]

epoch: 2700, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011642, Train KL:8.768524, Val MSE:0.010291, Val CE:0.043759, Train ACC:1.000000, Val ACC:0.993750

Epoch 2702/4000: 100%|██████████| 1/1 [00:00<00:00, 23.31it/s]

epoch: 2701, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011644, Train KL:8.768527, Val MSE:0.010301, Val CE:0.043475, Train ACC:1.000000, Val ACC:0.993750

Epoch 2703/4000: 100%|██████████| 1/1 [00:00<00:00, 22.57it/s]

epoch: 2702, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011638, Train KL:8.768530, Val MSE:0.010303, Val CE:0.043563, Train ACC:1.000000, Val ACC:0.993750

Epoch 2704/4000: 100%|██████████| 1/1 [00:00<00:00, 23.97it/s]

epoch: 2703, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011636, Train KL:8.768532, Val MSE:0.010301, Val CE:0.043531, Train ACC:1.000000, Val ACC:0.993750

Epoch 2705/4000: 100%|██████████| 1/1 [00:00<00:00, 26.76it/s]

epoch: 2704, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011636, Train KL:8.768535, Val MSE:0.010270, Val CE:0.043508, Train ACC:1.000000, Val ACC:0.993750

Epoch 2706/4000: 100%|██████████| 1/1 [00:00<00:00, 22.19it/s]

epoch: 2705, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011647, Train KL:8.768538, Val MSE:0.010286, Val CE:0.043442, Train ACC:1.000000, Val ACC:0.993750

Epoch 2707/4000: 100%|██████████| 1/1 [00:00<00:00, 23.71it/s]

epoch: 2706, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011642, Train KL:8.768540, Val MSE:0.010319, Val CE:0.043357, Train ACC:1.000000, Val ACC:0.993750

Epoch 2708/4000: 100%|██████████| 1/1 [00:00<00:00, 23.46it/s]

Learning rate updated: 3.905814462479254e-07
epoch: 2707, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011639, Train KL:8.768543, Val MSE:0.010275, Val CE:0.043569, Train ACC:1.000000, Val ACC:0.993750

Epoch 2709/4000: 100%|██████████| 1/1 [00:00<00:00, 24.33it/s]

epoch: 2708, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011637, Train KL:8.768545, Val MSE:0.010290, Val CE:0.043455, Train ACC:1.000000, Val ACC:0.993750

Epoch 2710/4000: 100%|██████████| 1/1 [00:00<00:00, 23.93it/s]

epoch: 2709, beta = 0.000097, Train MSE: 0.006614, Train CE:0.011638, Train KL:8.768548, Val MSE:0.010264, Val CE:0.043348, Train ACC:1.000000, Val ACC:0.993750

Epoch 2711/4000: 100%|██████████| 1/1 [00:00<00:00, 23.97it/s]

epoch: 2710, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011638, Train KL:8.768550, Val MSE:0.010274, Val CE:0.043353, Train ACC:1.000000, Val ACC:0.993750

Epoch 2712/4000: 100%|██████████| 1/1 [00:00<00:00, 21.98it/s]

epoch: 2711, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011639, Train KL:8.768553, Val MSE:0.010277, Val CE:0.043396, Train ACC:1.000000, Val ACC:0.993750

Epoch 2713/4000: 100%|██████████| 1/1 [00:00<00:00, 22.98it/s]

epoch: 2712, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011637, Train KL:8.768555, Val MSE:0.010287, Val CE:0.043508, Train ACC:1.000000, Val ACC:0.993750

Epoch 2714/4000: 100%|██████████| 1/1 [00:00<00:00, 23.01it/s]

epoch: 2713, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011639, Train KL:8.768558, Val MSE:0.010269, Val CE:0.043475, Train ACC:1.000000, Val ACC:0.993750

Epoch 2715/4000: 100%|██████████| 1/1 [00:00<00:00, 25.07it/s]

epoch: 2714, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011642, Train KL:8.768559, Val MSE:0.010313, Val CE:0.043377, Train ACC:1.000000, Val ACC:0.993750

Epoch 2716/4000: 100%|██████████| 1/1 [00:00<00:00, 22.93it/s]

epoch: 2715, beta = 0.000097, Train MSE: 0.006614, Train CE:0.011639, Train KL:8.768562, Val MSE:0.010297, Val CE:0.043605, Train ACC:1.000000, Val ACC:0.993750

Epoch 2717/4000: 100%|██████████| 1/1 [00:00<00:00, 24.42it/s]

epoch: 2716, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011640, Train KL:8.768565, Val MSE:0.010293, Val CE:0.043264, Train ACC:1.000000, Val ACC:0.993750

Epoch 2718/4000: 100%|██████████| 1/1 [00:00<00:00, 20.42it/s]

epoch: 2717, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011642, Train KL:8.768567, Val MSE:0.010268, Val CE:0.043263, Train ACC:1.000000, Val ACC:0.993750

Epoch 2719/4000: 100%|██████████| 1/1 [00:00<00:00, 21.03it/s]

Learning rate updated: 3.710523739355291e-07
epoch: 2718, beta = 0.000097, Train MSE: 0.006611, Train CE:0.011641, Train KL:8.768570, Val MSE:0.010294, Val CE:0.043581, Train ACC:1.000000, Val ACC:0.993750

Epoch 2720/4000: 100%|██████████| 1/1 [00:00<00:00, 18.39it/s]

epoch: 2719, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011635, Train KL:8.768572, Val MSE:0.010271, Val CE:0.043531, Train ACC:1.000000, Val ACC:0.993750

Epoch 2721/4000: 100%|██████████| 1/1 [00:00<00:00, 22.80it/s]

epoch: 2720, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011640, Train KL:8.768574, Val MSE:0.010315, Val CE:0.043440, Train ACC:1.000000, Val ACC:0.993750

Epoch 2722/4000: 100%|██████████| 1/1 [00:00<00:00, 22.08it/s]

epoch: 2721, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011643, Train KL:8.768576, Val MSE:0.010285, Val CE:0.043496, Train ACC:1.000000, Val ACC:0.993750

Epoch 2723/4000: 100%|██████████| 1/1 [00:00<00:00, 21.73it/s]

epoch: 2722, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011637, Train KL:8.768578, Val MSE:0.010305, Val CE:0.043433, Train ACC:1.000000, Val ACC:0.993750

Epoch 2724/4000: 100%|██████████| 1/1 [00:00<00:00, 24.57it/s]

epoch: 2723, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011643, Train KL:8.768580, Val MSE:0.010262, Val CE:0.043275, Train ACC:1.000000, Val ACC:0.993750

Epoch 2725/4000: 100%|██████████| 1/1 [00:00<00:00, 24.57it/s]

epoch: 2724, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011636, Train KL:8.768581, Val MSE:0.010307, Val CE:0.043479, Train ACC:1.000000, Val ACC:0.993750

Epoch 2726/4000: 100%|██████████| 1/1 [00:00<00:00, 24.03it/s]

epoch: 2725, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011642, Train KL:8.768585, Val MSE:0.010285, Val CE:0.043749, Train ACC:1.000000, Val ACC:0.993750

Epoch 2727/4000: 100%|██████████| 1/1 [00:00<00:00, 22.79it/s]

epoch: 2726, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011636, Train KL:8.768586, Val MSE:0.010314, Val CE:0.043521, Train ACC:1.000000, Val ACC:0.993750

Epoch 2728/4000: 100%|██████████| 1/1 [00:00<00:00, 24.20it/s]

epoch: 2727, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011635, Train KL:8.768588, Val MSE:0.010265, Val CE:0.043434, Train ACC:1.000000, Val ACC:0.993750

Epoch 2729/4000: 100%|██████████| 1/1 [00:00<00:00, 21.33it/s]

epoch: 2728, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011636, Train KL:8.768590, Val MSE:0.010311, Val CE:0.043515, Train ACC:1.000000, Val ACC:0.993750

Epoch 2730/4000: 100%|██████████| 1/1 [00:00<00:00, 24.46it/s]

Learning rate updated: 3.524997552387526e-07
epoch: 2729, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011642, Train KL:8.768593, Val MSE:0.010281, Val CE:0.043449, Train ACC:1.000000, Val ACC:0.993750

Epoch 2731/4000: 100%|██████████| 1/1 [00:00<00:00, 23.39it/s]

epoch: 2730, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011639, Train KL:8.768594, Val MSE:0.010307, Val CE:0.043255, Train ACC:1.000000, Val ACC:0.993750

Epoch 2732/4000: 100%|██████████| 1/1 [00:00<00:00, 24.09it/s]

epoch: 2731, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011634, Train KL:8.768598, Val MSE:0.010283, Val CE:0.043287, Train ACC:1.000000, Val ACC:0.993750

Epoch 2733/4000: 100%|██████████| 1/1 [00:00<00:00, 24.80it/s]

epoch: 2732, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011635, Train KL:8.768598, Val MSE:0.010270, Val CE:0.043573, Train ACC:1.000000, Val ACC:0.993750

Epoch 2734/4000: 100%|██████████| 1/1 [00:00<00:00, 24.04it/s]

epoch: 2733, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011643, Train KL:8.768600, Val MSE:0.010280, Val CE:0.043612, Train ACC:1.000000, Val ACC:0.993750

Epoch 2735/4000: 100%|██████████| 1/1 [00:00<00:00, 23.53it/s]

epoch: 2734, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011641, Train KL:8.768602, Val MSE:0.010280, Val CE:0.043410, Train ACC:1.000000, Val ACC:0.993750

Epoch 2736/4000: 100%|██████████| 1/1 [00:00<00:00, 22.19it/s]

epoch: 2735, beta = 0.000097, Train MSE: 0.006616, Train CE:0.011637, Train KL:8.768604, Val MSE:0.010264, Val CE:0.043343, Train ACC:1.000000, Val ACC:0.993750

Epoch 2737/4000: 100%|██████████| 1/1 [00:00<00:00, 18.40it/s]

epoch: 2736, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011642, Train KL:8.768606, Val MSE:0.010275, Val CE:0.043486, Train ACC:1.000000, Val ACC:0.993229

Epoch 2738/4000: 100%|██████████| 1/1 [00:00<00:00, 23.66it/s]

epoch: 2737, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011640, Train KL:8.768608, Val MSE:0.010303, Val CE:0.043399, Train ACC:1.000000, Val ACC:0.993750

Epoch 2739/4000: 100%|██████████| 1/1 [00:00<00:00, 24.21it/s]

epoch: 2738, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011636, Train KL:8.768611, Val MSE:0.010286, Val CE:0.043344, Train ACC:1.000000, Val ACC:0.993750

Epoch 2740/4000: 100%|██████████| 1/1 [00:00<00:00, 23.68it/s]

epoch: 2739, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011642, Train KL:8.768613, Val MSE:0.010268, Val CE:0.043539, Train ACC:1.000000, Val ACC:0.993750

Epoch 2741/4000: 100%|██████████| 1/1 [00:00<00:00, 23.96it/s]

Learning rate updated: 3.34874767476815e-07
epoch: 2740, beta = 0.000097, Train MSE: 0.006615, Train CE:0.011639, Train KL:8.768616, Val MSE:0.010281, Val CE:0.043513, Train ACC:1.000000, Val ACC:0.993750

Epoch 2742/4000: 100%|██████████| 1/1 [00:00<00:00, 26.38it/s]

epoch: 2741, beta = 0.000097, Train MSE: 0.006613, Train CE:0.011637, Train KL:8.768617, Val MSE:0.010310, Val CE:0.043386, Train ACC:1.000000, Val ACC:0.993750

Epoch 2743/4000: 100%|██████████| 1/1 [00:00<00:00, 24.35it/s]

epoch: 2742, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011635, Train KL:8.768620, Val MSE:0.010249, Val CE:0.043530, Train ACC:1.000000, Val ACC:0.993750

Epoch 2744/4000: 100%|██████████| 1/1 [00:00<00:00, 21.31it/s]

epoch: 2743, beta = 0.000097, Train MSE: 0.006617, Train CE:0.011649, Train KL:8.768621, Val MSE:0.010286, Val CE:0.043610, Train ACC:1.000000, Val ACC:0.993750

Epoch 2745/4000: 100%|██████████| 1/1 [00:00<00:00, 24.35it/s]

epoch: 2744, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011636, Train KL:8.768624, Val MSE:0.010311, Val CE:0.043317, Train ACC:1.000000, Val ACC:0.993750

Epoch 2746/4000: 100%|██████████| 1/1 [00:00<00:00, 22.80it/s]

epoch: 2745, beta = 0.000097, Train MSE: 0.006616, Train CE:0.011638, Train KL:8.768628, Val MSE:0.010296, Val CE:0.043463, Train ACC:1.000000, Val ACC:0.993750

Epoch 2747/4000: 100%|██████████| 1/1 [00:00<00:00, 24.06it/s]

epoch: 2746, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011638, Train KL:8.768629, Val MSE:0.010280, Val CE:0.043483, Train ACC:1.000000, Val ACC:0.993750

Epoch 2748/4000: 100%|██████████| 1/1 [00:00<00:00, 23.86it/s]

epoch: 2747, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011649, Train KL:8.768632, Val MSE:0.010274, Val CE:0.043457, Train ACC:1.000000, Val ACC:0.993750

Epoch 2749/4000: 100%|██████████| 1/1 [00:00<00:00, 24.66it/s]

epoch: 2748, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011639, Train KL:8.768635, Val MSE:0.010261, Val CE:0.043376, Train ACC:1.000000, Val ACC:0.993750

Epoch 2750/4000: 100%|██████████| 1/1 [00:00<00:00, 22.60it/s]

epoch: 2749, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011636, Train KL:8.768637, Val MSE:0.010279, Val CE:0.043450, Train ACC:1.000000, Val ACC:0.993750

Epoch 2751/4000: 100%|██████████| 1/1 [00:00<00:00, 22.90it/s]

epoch: 2750, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011638, Train KL:8.768640, Val MSE:0.010309, Val CE:0.043531, Train ACC:1.000000, Val ACC:0.993750

Epoch 2752/4000: 100%|██████████| 1/1 [00:00<00:00, 21.17it/s]

Learning rate updated: 3.181310291029742e-07
epoch: 2751, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011636, Train KL:8.768641, Val MSE:0.010295, Val CE:0.043334, Train ACC:1.000000, Val ACC:0.993750

Epoch 2753/4000: 100%|██████████| 1/1 [00:00<00:00, 21.12it/s]

epoch: 2752, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011640, Train KL:8.768644, Val MSE:0.010303, Val CE:0.043305, Train ACC:1.000000, Val ACC:0.993750

Epoch 2754/4000: 100%|██████████| 1/1 [00:00<00:00, 20.05it/s]

epoch: 2753, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011641, Train KL:8.768647, Val MSE:0.010291, Val CE:0.043601, Train ACC:1.000000, Val ACC:0.993750

Epoch 2755/4000: 100%|██████████| 1/1 [00:00<00:00, 22.47it/s]

epoch: 2754, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011638, Train KL:8.768648, Val MSE:0.010307, Val CE:0.043460, Train ACC:1.000000, Val ACC:0.993750

Epoch 2756/4000: 100%|██████████| 1/1 [00:00<00:00, 22.20it/s]

epoch: 2755, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011636, Train KL:8.768651, Val MSE:0.010297, Val CE:0.043314, Train ACC:1.000000, Val ACC:0.993750

Epoch 2757/4000: 100%|██████████| 1/1 [00:00<00:00, 24.21it/s]

epoch: 2756, beta = 0.000097, Train MSE: 0.006615, Train CE:0.011636, Train KL:8.768652, Val MSE:0.010275, Val CE:0.043526, Train ACC:1.000000, Val ACC:0.993750

Epoch 2758/4000: 100%|██████████| 1/1 [00:00<00:00, 22.96it/s]

epoch: 2757, beta = 0.000097, Train MSE: 0.006618, Train CE:0.011638, Train KL:8.768655, Val MSE:0.010270, Val CE:0.043621, Train ACC:1.000000, Val ACC:0.993750

Epoch 2759/4000: 100%|██████████| 1/1 [00:00<00:00, 24.08it/s]

epoch: 2758, beta = 0.000097, Train MSE: 0.006616, Train CE:0.011637, Train KL:8.768657, Val MSE:0.010292, Val CE:0.043307, Train ACC:1.000000, Val ACC:0.993750

Epoch 2760/4000: 100%|██████████| 1/1 [00:00<00:00, 23.66it/s]

epoch: 2759, beta = 0.000097, Train MSE: 0.006611, Train CE:0.011638, Train KL:8.768659, Val MSE:0.010281, Val CE:0.043476, Train ACC:1.000000, Val ACC:0.993750

Epoch 2761/4000: 100%|██████████| 1/1 [00:00<00:00, 23.09it/s]

epoch: 2760, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011631, Train KL:8.768661, Val MSE:0.010275, Val CE:0.043510, Train ACC:1.000000, Val ACC:0.993750

Epoch 2762/4000: 100%|██████████| 1/1 [00:00<00:00, 23.57it/s]

epoch: 2761, beta = 0.000097, Train MSE: 0.006617, Train CE:0.011642, Train KL:8.768662, Val MSE:0.010274, Val CE:0.043328, Train ACC:1.000000, Val ACC:0.993750

Epoch 2763/4000: 100%|██████████| 1/1 [00:00<00:00, 24.51it/s]

Learning rate updated: 3.0222447764782547e-07
epoch: 2762, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011641, Train KL:8.768666, Val MSE:0.010305, Val CE:0.043426, Train ACC:1.000000, Val ACC:0.993750

Epoch 2764/4000: 100%|██████████| 1/1 [00:00<00:00, 24.11it/s]

epoch: 2763, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011640, Train KL:8.768667, Val MSE:0.010291, Val CE:0.043532, Train ACC:1.000000, Val ACC:0.993750

Epoch 2765/4000: 100%|██████████| 1/1 [00:00<00:00, 27.13it/s]

epoch: 2764, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011639, Train KL:8.768669, Val MSE:0.010296, Val CE:0.043422, Train ACC:1.000000, Val ACC:0.993750

Epoch 2766/4000: 100%|██████████| 1/1 [00:00<00:00, 27.41it/s]

epoch: 2765, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011636, Train KL:8.768671, Val MSE:0.010282, Val CE:0.043414, Train ACC:1.000000, Val ACC:0.993750

Epoch 2767/4000: 100%|██████████| 1/1 [00:00<00:00, 24.31it/s]

epoch: 2766, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011638, Train KL:8.768674, Val MSE:0.010285, Val CE:0.043386, Train ACC:1.000000, Val ACC:0.993750

Epoch 2768/4000: 100%|██████████| 1/1 [00:00<00:00, 24.34it/s]

epoch: 2767, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011637, Train KL:8.768675, Val MSE:0.010271, Val CE:0.043222, Train ACC:1.000000, Val ACC:0.993750

Epoch 2769/4000: 100%|██████████| 1/1 [00:00<00:00, 18.75it/s]

epoch: 2768, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011633, Train KL:8.768677, Val MSE:0.010298, Val CE:0.043487, Train ACC:1.000000, Val ACC:0.993750

Epoch 2770/4000: 100%|██████████| 1/1 [00:00<00:00, 23.80it/s]

epoch: 2769, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011634, Train KL:8.768679, Val MSE:0.010295, Val CE:0.043450, Train ACC:1.000000, Val ACC:0.993750

Epoch 2771/4000: 100%|██████████| 1/1 [00:00<00:00, 23.17it/s]

epoch: 2770, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011634, Train KL:8.768681, Val MSE:0.010290, Val CE:0.043214, Train ACC:1.000000, Val ACC:0.993750

Epoch 2772/4000: 100%|██████████| 1/1 [00:00<00:00, 25.67it/s]

epoch: 2771, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011632, Train KL:8.768682, Val MSE:0.010281, Val CE:0.043487, Train ACC:1.000000, Val ACC:0.993750

Epoch 2773/4000: 100%|██████████| 1/1 [00:00<00:00, 23.82it/s]

epoch: 2772, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011634, Train KL:8.768684, Val MSE:0.010314, Val CE:0.043524, Train ACC:1.000000, Val ACC:0.993229

Epoch 2774/4000: 100%|██████████| 1/1 [00:00<00:00, 23.42it/s]

Learning rate updated: 2.8711325376543416e-07
epoch: 2773, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011634, Train KL:8.768685, Val MSE:0.010270, Val CE:0.043435, Train ACC:1.000000, Val ACC:0.993750

Epoch 2775/4000: 100%|██████████| 1/1 [00:00<00:00, 24.15it/s]

epoch: 2774, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011639, Train KL:8.768687, Val MSE:0.010286, Val CE:0.043322, Train ACC:1.000000, Val ACC:0.993750

Epoch 2776/4000: 100%|██████████| 1/1 [00:00<00:00, 24.51it/s]

epoch: 2775, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011640, Train KL:8.768689, Val MSE:0.010270, Val CE:0.043451, Train ACC:1.000000, Val ACC:0.993750

Epoch 2777/4000: 100%|██████████| 1/1 [00:00<00:00, 23.72it/s]

epoch: 2776, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011640, Train KL:8.768690, Val MSE:0.010282, Val CE:0.043586, Train ACC:1.000000, Val ACC:0.993750

Epoch 2778/4000: 100%|██████████| 1/1 [00:00<00:00, 23.57it/s]

epoch: 2777, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011636, Train KL:8.768692, Val MSE:0.010307, Val CE:0.043334, Train ACC:1.000000, Val ACC:0.993750

Epoch 2779/4000: 100%|██████████| 1/1 [00:00<00:00, 24.32it/s]

epoch: 2778, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011639, Train KL:8.768693, Val MSE:0.010297, Val CE:0.043302, Train ACC:1.000000, Val ACC:0.993750

Epoch 2780/4000: 100%|██████████| 1/1 [00:00<00:00, 21.76it/s]

epoch: 2779, beta = 0.000097, Train MSE: 0.006611, Train CE:0.011637, Train KL:8.768695, Val MSE:0.010291, Val CE:0.043636, Train ACC:1.000000, Val ACC:0.993750

Epoch 2781/4000: 100%|██████████| 1/1 [00:00<00:00, 23.47it/s]

epoch: 2780, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011637, Train KL:8.768697, Val MSE:0.010270, Val CE:0.043225, Train ACC:1.000000, Val ACC:0.993750

Epoch 2782/4000: 100%|██████████| 1/1 [00:00<00:00, 24.43it/s]

epoch: 2781, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011638, Train KL:8.768698, Val MSE:0.010257, Val CE:0.043597, Train ACC:1.000000, Val ACC:0.993750

Epoch 2783/4000: 100%|██████████| 1/1 [00:00<00:00, 22.58it/s]

epoch: 2782, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011639, Train KL:8.768700, Val MSE:0.010282, Val CE:0.043305, Train ACC:1.000000, Val ACC:0.993750

Epoch 2784/4000: 100%|██████████| 1/1 [00:00<00:00, 23.51it/s]

epoch: 2783, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011638, Train KL:8.768702, Val MSE:0.010298, Val CE:0.043525, Train ACC:1.000000, Val ACC:0.993750

Epoch 2785/4000: 100%|██████████| 1/1 [00:00<00:00, 24.10it/s]

Learning rate updated: 2.7275759107716244e-07
epoch: 2784, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011632, Train KL:8.768704, Val MSE:0.010258, Val CE:0.043360, Train ACC:1.000000, Val ACC:0.993750

Epoch 2786/4000: 100%|██████████| 1/1 [00:00<00:00, 20.44it/s]

epoch: 2785, beta = 0.000097, Train MSE: 0.006615, Train CE:0.011641, Train KL:8.768705, Val MSE:0.010261, Val CE:0.043423, Train ACC:1.000000, Val ACC:0.993750

Epoch 2787/4000: 100%|██████████| 1/1 [00:00<00:00, 22.06it/s]

epoch: 2786, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011638, Train KL:8.768707, Val MSE:0.010291, Val CE:0.043432, Train ACC:1.000000, Val ACC:0.993750

Epoch 2788/4000: 100%|██████████| 1/1 [00:00<00:00, 23.54it/s]

epoch: 2787, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011632, Train KL:8.768708, Val MSE:0.010303, Val CE:0.043385, Train ACC:1.000000, Val ACC:0.993750

Epoch 2789/4000: 100%|██████████| 1/1 [00:00<00:00, 23.93it/s]

epoch: 2788, beta = 0.000097, Train MSE: 0.006595, Train CE:0.011632, Train KL:8.768711, Val MSE:0.010303, Val CE:0.043522, Train ACC:1.000000, Val ACC:0.993750

Epoch 2790/4000: 100%|██████████| 1/1 [00:00<00:00, 24.17it/s]

epoch: 2789, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011637, Train KL:8.768713, Val MSE:0.010255, Val CE:0.043583, Train ACC:1.000000, Val ACC:0.993750

Epoch 2791/4000: 100%|██████████| 1/1 [00:00<00:00, 23.91it/s]

epoch: 2790, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011638, Train KL:8.768715, Val MSE:0.010300, Val CE:0.043356, Train ACC:1.000000, Val ACC:0.993750

Epoch 2792/4000: 100%|██████████| 1/1 [00:00<00:00, 24.14it/s]

epoch: 2791, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011637, Train KL:8.768717, Val MSE:0.010272, Val CE:0.043634, Train ACC:1.000000, Val ACC:0.993750

Epoch 2793/4000: 100%|██████████| 1/1 [00:00<00:00, 23.56it/s]

epoch: 2792, beta = 0.000097, Train MSE: 0.006613, Train CE:0.011636, Train KL:8.768717, Val MSE:0.010274, Val CE:0.043207, Train ACC:1.000000, Val ACC:0.993750

Epoch 2794/4000: 100%|██████████| 1/1 [00:00<00:00, 23.33it/s]

epoch: 2793, beta = 0.000097, Train MSE: 0.006619, Train CE:0.011635, Train KL:8.768719, Val MSE:0.010289, Val CE:0.043415, Train ACC:1.000000, Val ACC:0.993750

Epoch 2795/4000: 100%|██████████| 1/1 [00:00<00:00, 22.91it/s]

epoch: 2794, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011641, Train KL:8.768721, Val MSE:0.010302, Val CE:0.043669, Train ACC:1.000000, Val ACC:0.993750

Epoch 2796/4000: 100%|██████████| 1/1 [00:00<00:00, 24.21it/s]

Learning rate updated: 2.591197115233043e-07
epoch: 2795, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011636, Train KL:8.768723, Val MSE:0.010313, Val CE:0.043551, Train ACC:1.000000, Val ACC:0.993750

Epoch 2797/4000: 100%|██████████| 1/1 [00:00<00:00, 22.48it/s]

epoch: 2796, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011628, Train KL:8.768724, Val MSE:0.010285, Val CE:0.043361, Train ACC:1.000000, Val ACC:0.993750

Epoch 2798/4000: 100%|██████████| 1/1 [00:00<00:00, 21.84it/s]

epoch: 2797, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011636, Train KL:8.768725, Val MSE:0.010293, Val CE:0.043476, Train ACC:1.000000, Val ACC:0.993750

Epoch 2799/4000: 100%|██████████| 1/1 [00:00<00:00, 25.26it/s]

epoch: 2798, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011643, Train KL:8.768727, Val MSE:0.010285, Val CE:0.043503, Train ACC:1.000000, Val ACC:0.993750

Epoch 2800/4000: 100%|██████████| 1/1 [00:00<00:00, 23.75it/s]

epoch: 2799, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011637, Train KL:8.768728, Val MSE:0.010285, Val CE:0.043464, Train ACC:1.000000, Val ACC:0.993750

Epoch 2801/4000: 100%|██████████| 1/1 [00:00<00:00, 21.86it/s]

epoch: 2800, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011629, Train KL:8.768730, Val MSE:0.010293, Val CE:0.043475, Train ACC:1.000000, Val ACC:0.993750

Epoch 2802/4000: 100%|██████████| 1/1 [00:00<00:00, 18.63it/s]

epoch: 2801, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011633, Train KL:8.768732, Val MSE:0.010280, Val CE:0.043493, Train ACC:1.000000, Val ACC:0.993750

Epoch 2803/4000: 100%|██████████| 1/1 [00:00<00:00, 23.03it/s]

epoch: 2802, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011636, Train KL:8.768733, Val MSE:0.010277, Val CE:0.043627, Train ACC:1.000000, Val ACC:0.993750

Epoch 2804/4000: 100%|██████████| 1/1 [00:00<00:00, 23.36it/s]

epoch: 2803, beta = 0.000097, Train MSE: 0.006614, Train CE:0.011637, Train KL:8.768735, Val MSE:0.010275, Val CE:0.043545, Train ACC:1.000000, Val ACC:0.993750

Epoch 2805/4000: 100%|██████████| 1/1 [00:00<00:00, 24.09it/s]

epoch: 2804, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011637, Train KL:8.768736, Val MSE:0.010260, Val CE:0.043241, Train ACC:1.000000, Val ACC:0.993750

Epoch 2806/4000: 100%|██████████| 1/1 [00:00<00:00, 25.99it/s]

epoch: 2805, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011635, Train KL:8.768738, Val MSE:0.010260, Val CE:0.043530, Train ACC:1.000000, Val ACC:0.993750

Epoch 2807/4000: 100%|██████████| 1/1 [00:00<00:00, 24.18it/s]

Learning rate updated: 2.4616372594713905e-07
epoch: 2806, beta = 0.000097, Train MSE: 0.006616, Train CE:0.011637, Train KL:8.768740, Val MSE:0.010277, Val CE:0.043505, Train ACC:1.000000, Val ACC:0.993750

Epoch 2808/4000: 100%|██████████| 1/1 [00:00<00:00, 23.94it/s]

epoch: 2807, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011636, Train KL:8.768741, Val MSE:0.010291, Val CE:0.043215, Train ACC:1.000000, Val ACC:0.993750

Epoch 2809/4000: 100%|██████████| 1/1 [00:00<00:00, 24.14it/s]

epoch: 2808, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011634, Train KL:8.768744, Val MSE:0.010276, Val CE:0.043624, Train ACC:1.000000, Val ACC:0.993750

Epoch 2810/4000: 100%|██████████| 1/1 [00:00<00:00, 24.36it/s]

epoch: 2809, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011639, Train KL:8.768744, Val MSE:0.010274, Val CE:0.043323, Train ACC:1.000000, Val ACC:0.993750

Epoch 2811/4000: 100%|██████████| 1/1 [00:00<00:00, 24.63it/s]

epoch: 2810, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011635, Train KL:8.768745, Val MSE:0.010263, Val CE:0.043442, Train ACC:1.000000, Val ACC:0.993750

Epoch 2812/4000: 100%|██████████| 1/1 [00:00<00:00, 25.85it/s]

epoch: 2811, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011640, Train KL:8.768747, Val MSE:0.010261, Val CE:0.043059, Train ACC:1.000000, Val ACC:0.993750

Epoch 2813/4000: 100%|██████████| 1/1 [00:00<00:00, 24.03it/s]

epoch: 2812, beta = 0.000097, Train MSE: 0.006611, Train CE:0.011637, Train KL:8.768748, Val MSE:0.010289, Val CE:0.043457, Train ACC:1.000000, Val ACC:0.993750

Epoch 2814/4000: 100%|██████████| 1/1 [00:00<00:00, 22.98it/s]

epoch: 2813, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011636, Train KL:8.768751, Val MSE:0.010299, Val CE:0.043322, Train ACC:1.000000, Val ACC:0.993750

Epoch 2815/4000: 100%|██████████| 1/1 [00:00<00:00, 23.47it/s]

epoch: 2814, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011634, Train KL:8.768751, Val MSE:0.010278, Val CE:0.043513, Train ACC:1.000000, Val ACC:0.993750

Epoch 2816/4000: 100%|██████████| 1/1 [00:00<00:00, 21.01it/s]

epoch: 2815, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011631, Train KL:8.768753, Val MSE:0.010296, Val CE:0.043695, Train ACC:1.000000, Val ACC:0.993750

Epoch 2817/4000: 100%|██████████| 1/1 [00:00<00:00, 21.10it/s]

epoch: 2816, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011636, Train KL:8.768755, Val MSE:0.010275, Val CE:0.043420, Train ACC:1.000000, Val ACC:0.993750

Epoch 2818/4000: 100%|██████████| 1/1 [00:00<00:00, 22.77it/s]

Learning rate updated: 2.3385553964978208e-07
epoch: 2817, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011637, Train KL:8.768756, Val MSE:0.010289, Val CE:0.043576, Train ACC:1.000000, Val ACC:0.993750

Epoch 2819/4000: 100%|██████████| 1/1 [00:00<00:00, 24.37it/s]

epoch: 2818, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011630, Train KL:8.768758, Val MSE:0.010294, Val CE:0.043198, Train ACC:1.000000, Val ACC:0.993750

Epoch 2820/4000: 100%|██████████| 1/1 [00:00<00:00, 23.47it/s]

epoch: 2819, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011633, Train KL:8.768759, Val MSE:0.010300, Val CE:0.043404, Train ACC:1.000000, Val ACC:0.993750

Epoch 2821/4000: 100%|██████████| 1/1 [00:00<00:00, 23.53it/s]

epoch: 2820, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011637, Train KL:8.768760, Val MSE:0.010296, Val CE:0.043331, Train ACC:1.000000, Val ACC:0.993750

Epoch 2822/4000: 100%|██████████| 1/1 [00:00<00:00, 24.05it/s]

epoch: 2821, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011633, Train KL:8.768762, Val MSE:0.010295, Val CE:0.043348, Train ACC:1.000000, Val ACC:0.993750

Epoch 2823/4000: 100%|██████████| 1/1 [00:00<00:00, 24.06it/s]

epoch: 2822, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011634, Train KL:8.768763, Val MSE:0.010278, Val CE:0.043380, Train ACC:1.000000, Val ACC:0.993750

Epoch 2824/4000: 100%|██████████| 1/1 [00:00<00:00, 23.98it/s]

epoch: 2823, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011633, Train KL:8.768764, Val MSE:0.010262, Val CE:0.043407, Train ACC:1.000000, Val ACC:0.993750

Epoch 2825/4000: 100%|██████████| 1/1 [00:00<00:00, 24.46it/s]

epoch: 2824, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011632, Train KL:8.768765, Val MSE:0.010271, Val CE:0.043475, Train ACC:1.000000, Val ACC:0.993750

Epoch 2826/4000: 100%|██████████| 1/1 [00:00<00:00, 24.54it/s]

epoch: 2825, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011629, Train KL:8.768766, Val MSE:0.010315, Val CE:0.043623, Train ACC:1.000000, Val ACC:0.993750

Epoch 2827/4000: 100%|██████████| 1/1 [00:00<00:00, 23.76it/s]

epoch: 2826, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011632, Train KL:8.768766, Val MSE:0.010285, Val CE:0.043441, Train ACC:1.000000, Val ACC:0.993750

Epoch 2828/4000: 100%|██████████| 1/1 [00:00<00:00, 22.60it/s]

epoch: 2827, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011644, Train KL:8.768768, Val MSE:0.010286, Val CE:0.043400, Train ACC:1.000000, Val ACC:0.993750

Epoch 2829/4000: 100%|██████████| 1/1 [00:00<00:00, 24.31it/s]

Learning rate updated: 2.2216276266729297e-07
epoch: 2828, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011640, Train KL:8.768770, Val MSE:0.010279, Val CE:0.043327, Train ACC:1.000000, Val ACC:0.993750

Epoch 2830/4000: 100%|██████████| 1/1 [00:00<00:00, 25.13it/s]

epoch: 2829, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011636, Train KL:8.768770, Val MSE:0.010304, Val CE:0.043555, Train ACC:1.000000, Val ACC:0.993750

Epoch 2831/4000: 100%|██████████| 1/1 [00:00<00:00, 24.26it/s]

epoch: 2830, beta = 0.000097, Train MSE: 0.006611, Train CE:0.011636, Train KL:8.768773, Val MSE:0.010274, Val CE:0.043594, Train ACC:1.000000, Val ACC:0.993750

Epoch 2832/4000: 100%|██████████| 1/1 [00:00<00:00, 25.36it/s]

epoch: 2831, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011628, Train KL:8.768774, Val MSE:0.010275, Val CE:0.043557, Train ACC:1.000000, Val ACC:0.993750

Epoch 2833/4000: 100%|██████████| 1/1 [00:00<00:00, 23.08it/s]

epoch: 2832, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011635, Train KL:8.768774, Val MSE:0.010300, Val CE:0.043227, Train ACC:1.000000, Val ACC:0.993750

Epoch 2834/4000: 100%|██████████| 1/1 [00:00<00:00, 18.83it/s]

epoch: 2833, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011636, Train KL:8.768776, Val MSE:0.010289, Val CE:0.043281, Train ACC:1.000000, Val ACC:0.993750

Epoch 2835/4000: 100%|██████████| 1/1 [00:00<00:00, 22.02it/s]

epoch: 2834, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011634, Train KL:8.768778, Val MSE:0.010280, Val CE:0.043498, Train ACC:1.000000, Val ACC:0.993750

Epoch 2836/4000: 100%|██████████| 1/1 [00:00<00:00, 22.15it/s]

epoch: 2835, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011635, Train KL:8.768779, Val MSE:0.010278, Val CE:0.043558, Train ACC:1.000000, Val ACC:0.993750

Epoch 2837/4000: 100%|██████████| 1/1 [00:00<00:00, 20.92it/s]

epoch: 2836, beta = 0.000097, Train MSE: 0.006615, Train CE:0.011642, Train KL:8.768781, Val MSE:0.010272, Val CE:0.043492, Train ACC:1.000000, Val ACC:0.993750

Epoch 2838/4000: 100%|██████████| 1/1 [00:00<00:00, 23.09it/s]

epoch: 2837, beta = 0.000097, Train MSE: 0.006594, Train CE:0.011636, Train KL:8.768782, Val MSE:0.010287, Val CE:0.043607, Train ACC:1.000000, Val ACC:0.993750

Epoch 2839/4000: 100%|██████████| 1/1 [00:00<00:00, 24.05it/s]

epoch: 2838, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011637, Train KL:8.768783, Val MSE:0.010291, Val CE:0.043407, Train ACC:1.000000, Val ACC:0.993750

Epoch 2840/4000: 100%|██████████| 1/1 [00:00<00:00, 24.09it/s]

Learning rate updated: 2.110546245339283e-07
epoch: 2839, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011634, Train KL:8.768784, Val MSE:0.010272, Val CE:0.043499, Train ACC:1.000000, Val ACC:0.993750

Epoch 2841/4000: 100%|██████████| 1/1 [00:00<00:00, 23.80it/s]

epoch: 2840, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011639, Train KL:8.768785, Val MSE:0.010319, Val CE:0.043491, Train ACC:1.000000, Val ACC:0.993750

Epoch 2842/4000: 100%|██████████| 1/1 [00:00<00:00, 24.10it/s]

epoch: 2841, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011634, Train KL:8.768785, Val MSE:0.010297, Val CE:0.043691, Train ACC:1.000000, Val ACC:0.993750

Epoch 2843/4000: 100%|██████████| 1/1 [00:00<00:00, 23.94it/s]

epoch: 2842, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011635, Train KL:8.768787, Val MSE:0.010284, Val CE:0.043508, Train ACC:1.000000, Val ACC:0.993750

Epoch 2844/4000: 100%|██████████| 1/1 [00:00<00:00, 25.29it/s]

epoch: 2843, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011635, Train KL:8.768788, Val MSE:0.010302, Val CE:0.043204, Train ACC:1.000000, Val ACC:0.993750

Epoch 2845/4000: 100%|██████████| 1/1 [00:00<00:00, 23.87it/s]

epoch: 2844, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011638, Train KL:8.768789, Val MSE:0.010272, Val CE:0.043465, Train ACC:1.000000, Val ACC:0.993750

Epoch 2846/4000: 100%|██████████| 1/1 [00:00<00:00, 23.32it/s]

epoch: 2845, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011638, Train KL:8.768791, Val MSE:0.010282, Val CE:0.043557, Train ACC:1.000000, Val ACC:0.993750

Epoch 2847/4000: 100%|██████████| 1/1 [00:00<00:00, 24.25it/s]

epoch: 2846, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011637, Train KL:8.768792, Val MSE:0.010259, Val CE:0.043406, Train ACC:1.000000, Val ACC:0.993750

Epoch 2848/4000: 100%|██████████| 1/1 [00:00<00:00, 24.23it/s]

epoch: 2847, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011636, Train KL:8.768793, Val MSE:0.010294, Val CE:0.043502, Train ACC:1.000000, Val ACC:0.993750

Epoch 2849/4000: 100%|██████████| 1/1 [00:00<00:00, 23.56it/s]

epoch: 2848, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011634, Train KL:8.768794, Val MSE:0.010288, Val CE:0.043368, Train ACC:1.000000, Val ACC:0.993750

Epoch 2850/4000: 100%|██████████| 1/1 [00:00<00:00, 20.59it/s]

epoch: 2849, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011639, Train KL:8.768796, Val MSE:0.010251, Val CE:0.043581, Train ACC:1.000000, Val ACC:0.993750

Epoch 2851/4000: 100%|██████████| 1/1 [00:00<00:00, 22.94it/s]

Learning rate updated: 2.0050189330723186e-07
epoch: 2850, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011638, Train KL:8.768797, Val MSE:0.010281, Val CE:0.043444, Train ACC:1.000000, Val ACC:0.993750

Epoch 2852/4000: 100%|██████████| 1/1 [00:00<00:00, 23.97it/s]

epoch: 2851, beta = 0.000097, Train MSE: 0.006611, Train CE:0.011638, Train KL:8.768797, Val MSE:0.010280, Val CE:0.043559, Train ACC:1.000000, Val ACC:0.993750

Epoch 2853/4000: 100%|██████████| 1/1 [00:00<00:00, 25.15it/s]

epoch: 2852, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011635, Train KL:8.768799, Val MSE:0.010277, Val CE:0.043415, Train ACC:1.000000, Val ACC:0.993750

Epoch 2854/4000: 100%|██████████| 1/1 [00:00<00:00, 24.11it/s]

epoch: 2853, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011633, Train KL:8.768801, Val MSE:0.010311, Val CE:0.043491, Train ACC:1.000000, Val ACC:0.993750

Epoch 2855/4000: 100%|██████████| 1/1 [00:00<00:00, 24.04it/s]

epoch: 2854, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011629, Train KL:8.768801, Val MSE:0.010280, Val CE:0.043514, Train ACC:1.000000, Val ACC:0.993750

Epoch 2856/4000: 100%|██████████| 1/1 [00:00<00:00, 24.23it/s]

epoch: 2855, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011635, Train KL:8.768804, Val MSE:0.010298, Val CE:0.043368, Train ACC:1.000000, Val ACC:0.993750

Epoch 2857/4000: 100%|██████████| 1/1 [00:00<00:00, 25.93it/s]

epoch: 2856, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011639, Train KL:8.768804, Val MSE:0.010304, Val CE:0.043502, Train ACC:1.000000, Val ACC:0.993750

Epoch 2858/4000: 100%|██████████| 1/1 [00:00<00:00, 27.22it/s]

epoch: 2857, beta = 0.000097, Train MSE: 0.006594, Train CE:0.011627, Train KL:8.768805, Val MSE:0.010277, Val CE:0.043323, Train ACC:1.000000, Val ACC:0.993750

Epoch 2859/4000: 100%|██████████| 1/1 [00:00<00:00, 23.93it/s]

epoch: 2858, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011634, Train KL:8.768806, Val MSE:0.010280, Val CE:0.043531, Train ACC:1.000000, Val ACC:0.993750

Epoch 2860/4000: 100%|██████████| 1/1 [00:00<00:00, 24.85it/s]

epoch: 2859, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011635, Train KL:8.768808, Val MSE:0.010267, Val CE:0.043488, Train ACC:1.000000, Val ACC:0.993750

Epoch 2861/4000: 100%|██████████| 1/1 [00:00<00:00, 22.60it/s]

epoch: 2860, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011637, Train KL:8.768808, Val MSE:0.010285, Val CE:0.043672, Train ACC:1.000000, Val ACC:0.993750

Epoch 2862/4000: 100%|██████████| 1/1 [00:00<00:00, 26.75it/s]

Learning rate updated: 1.9047679864187027e-07
epoch: 2861, beta = 0.000097, Train MSE: 0.006590, Train CE:0.011635, Train KL:8.768809, Val MSE:0.010276, Val CE:0.043202, Train ACC:1.000000, Val ACC:0.993750

Epoch 2863/4000: 100%|██████████| 1/1 [00:00<00:00, 24.25it/s]

epoch: 2862, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011639, Train KL:8.768811, Val MSE:0.010301, Val CE:0.043334, Train ACC:1.000000, Val ACC:0.993750

Epoch 2864/4000: 100%|██████████| 1/1 [00:00<00:00, 25.43it/s]

epoch: 2863, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011636, Train KL:8.768812, Val MSE:0.010313, Val CE:0.043432, Train ACC:1.000000, Val ACC:0.993750

Epoch 2865/4000: 100%|██████████| 1/1 [00:00<00:00, 24.33it/s]

epoch: 2864, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011636, Train KL:8.768812, Val MSE:0.010262, Val CE:0.043325, Train ACC:1.000000, Val ACC:0.993750

Epoch 2866/4000: 100%|██████████| 1/1 [00:00<00:00, 23.98it/s]

epoch: 2865, beta = 0.000097, Train MSE: 0.006614, Train CE:0.011638, Train KL:8.768814, Val MSE:0.010277, Val CE:0.043538, Train ACC:1.000000, Val ACC:0.993750

Epoch 2867/4000: 100%|██████████| 1/1 [00:00<00:00, 17.07it/s]

epoch: 2866, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011637, Train KL:8.768815, Val MSE:0.010292, Val CE:0.043513, Train ACC:1.000000, Val ACC:0.993750

Epoch 2868/4000: 100%|██████████| 1/1 [00:00<00:00, 22.31it/s]

epoch: 2867, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011633, Train KL:8.768816, Val MSE:0.010264, Val CE:0.043489, Train ACC:1.000000, Val ACC:0.993750

Epoch 2869/4000: 100%|██████████| 1/1 [00:00<00:00, 24.09it/s]

epoch: 2868, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011632, Train KL:8.768817, Val MSE:0.010287, Val CE:0.043547, Train ACC:1.000000, Val ACC:0.993750

Epoch 2870/4000: 100%|██████████| 1/1 [00:00<00:00, 23.70it/s]

epoch: 2869, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011638, Train KL:8.768819, Val MSE:0.010279, Val CE:0.043595, Train ACC:1.000000, Val ACC:0.993750

Epoch 2871/4000: 100%|██████████| 1/1 [00:00<00:00, 23.32it/s]

epoch: 2870, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011637, Train KL:8.768820, Val MSE:0.010294, Val CE:0.043455, Train ACC:1.000000, Val ACC:0.993750

Epoch 2872/4000: 100%|██████████| 1/1 [00:00<00:00, 22.96it/s]

epoch: 2871, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011636, Train KL:8.768822, Val MSE:0.010270, Val CE:0.043404, Train ACC:1.000000, Val ACC:0.993750

Epoch 2873/4000: 100%|██████████| 1/1 [00:00<00:00, 23.30it/s]

epoch: 2872, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011635, Train KL:8.768822, Val MSE:0.010276, Val CE:0.043506, Train ACC:1.000000, Val ACC:0.993750

Epoch 2874/4000: 100%|██████████| 1/1 [00:00<00:00, 23.28it/s]

epoch: 2873, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011632, Train KL:8.768824, Val MSE:0.010274, Val CE:0.043532, Train ACC:1.000000, Val ACC:0.993750

Epoch 2875/4000: 100%|██████████| 1/1 [00:00<00:00, 21.94it/s]

epoch: 2874, beta = 0.000097, Train MSE: 0.006592, Train CE:0.011634, Train KL:8.768825, Val MSE:0.010291, Val CE:0.043207, Train ACC:1.000000, Val ACC:0.993750

Epoch 2876/4000: 100%|██████████| 1/1 [00:00<00:00, 21.38it/s]

epoch: 2875, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011634, Train KL:8.768826, Val MSE:0.010272, Val CE:0.043237, Train ACC:1.000000, Val ACC:0.993750

Epoch 2877/4000: 100%|██████████| 1/1 [00:00<00:00, 22.12it/s]

epoch: 2876, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011636, Train KL:8.768826, Val MSE:0.010283, Val CE:0.043292, Train ACC:1.000000, Val ACC:0.993750

Epoch 2878/4000: 100%|██████████| 1/1 [00:00<00:00, 22.00it/s]

epoch: 2877, beta = 0.000097, Train MSE: 0.006593, Train CE:0.011638, Train KL:8.768827, Val MSE:0.010291, Val CE:0.043392, Train ACC:1.000000, Val ACC:0.993750

Epoch 2879/4000: 100%|██████████| 1/1 [00:00<00:00, 20.71it/s]

epoch: 2878, beta = 0.000097, Train MSE: 0.006613, Train CE:0.011635, Train KL:8.768827, Val MSE:0.010273, Val CE:0.043481, Train ACC:1.000000, Val ACC:0.993750

Epoch 2880/4000: 100%|██████████| 1/1 [00:00<00:00, 23.54it/s]

epoch: 2879, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011641, Train KL:8.768829, Val MSE:0.010277, Val CE:0.043506, Train ACC:1.000000, Val ACC:0.993750

Epoch 2881/4000: 100%|██████████| 1/1 [00:00<00:00, 19.40it/s]

epoch: 2880, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011634, Train KL:8.768831, Val MSE:0.010272, Val CE:0.043520, Train ACC:1.000000, Val ACC:0.993750

Epoch 2882/4000: 100%|██████████| 1/1 [00:00<00:00, 23.41it/s]

epoch: 2881, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011638, Train KL:8.768832, Val MSE:0.010285, Val CE:0.043234, Train ACC:1.000000, Val ACC:0.993750

Epoch 2883/4000: 100%|██████████| 1/1 [00:00<00:00, 22.99it/s]

epoch: 2882, beta = 0.000097, Train MSE: 0.006611, Train CE:0.011632, Train KL:8.768832, Val MSE:0.010295, Val CE:0.043278, Train ACC:1.000000, Val ACC:0.993750

Epoch 2884/4000: 100%|██████████| 1/1 [00:00<00:00, 25.07it/s]

epoch: 2883, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011637, Train KL:8.768834, Val MSE:0.010266, Val CE:0.043546, Train ACC:1.000000, Val ACC:0.993750

Epoch 2885/4000: 100%|██████████| 1/1 [00:00<00:00, 24.12it/s]

epoch: 2884, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011639, Train KL:8.768835, Val MSE:0.010279, Val CE:0.043495, Train ACC:1.000000, Val ACC:0.993750

Epoch 2886/4000: 100%|██████████| 1/1 [00:00<00:00, 23.75it/s]

epoch: 2885, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011638, Train KL:8.768836, Val MSE:0.010272, Val CE:0.043572, Train ACC:1.000000, Val ACC:0.993750

Epoch 2887/4000: 100%|██████████| 1/1 [00:00<00:00, 23.10it/s]

epoch: 2886, beta = 0.000097, Train MSE: 0.006614, Train CE:0.011634, Train KL:8.768837, Val MSE:0.010266, Val CE:0.043596, Train ACC:1.000000, Val ACC:0.993750

Epoch 2888/4000: 100%|██████████| 1/1 [00:00<00:00, 23.02it/s]

epoch: 2887, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011641, Train KL:8.768839, Val MSE:0.010285, Val CE:0.043539, Train ACC:1.000000, Val ACC:0.993750

Epoch 2889/4000: 100%|██████████| 1/1 [00:00<00:00, 24.03it/s]

epoch: 2888, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011633, Train KL:8.768840, Val MSE:0.010273, Val CE:0.043349, Train ACC:1.000000, Val ACC:0.993750

Epoch 2890/4000: 100%|██████████| 1/1 [00:00<00:00, 22.15it/s]

epoch: 2889, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011631, Train KL:8.768841, Val MSE:0.010278, Val CE:0.043607, Train ACC:1.000000, Val ACC:0.993750

Epoch 2891/4000: 100%|██████████| 1/1 [00:00<00:00, 23.42it/s]

epoch: 2890, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011638, Train KL:8.768842, Val MSE:0.010261, Val CE:0.043633, Train ACC:1.000000, Val ACC:0.993750

Epoch 2892/4000: 100%|██████████| 1/1 [00:00<00:00, 23.54it/s]

epoch: 2891, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011636, Train KL:8.768844, Val MSE:0.010290, Val CE:0.043343, Train ACC:1.000000, Val ACC:0.993750

Epoch 2893/4000: 100%|██████████| 1/1 [00:00<00:00, 23.50it/s]

epoch: 2892, beta = 0.000097, Train MSE: 0.006594, Train CE:0.011636, Train KL:8.768845, Val MSE:0.010279, Val CE:0.043522, Train ACC:1.000000, Val ACC:0.993750

Epoch 2894/4000: 100%|██████████| 1/1 [00:00<00:00, 19.16it/s]

epoch: 2893, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011635, Train KL:8.768846, Val MSE:0.010275, Val CE:0.043459, Train ACC:1.000000, Val ACC:0.993750

Epoch 2895/4000: 100%|██████████| 1/1 [00:00<00:00, 19.24it/s]

epoch: 2894, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011633, Train KL:8.768847, Val MSE:0.010299, Val CE:0.043364, Train ACC:1.000000, Val ACC:0.993750

Epoch 2896/4000: 100%|██████████| 1/1 [00:00<00:00, 25.22it/s]

epoch: 2895, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011629, Train KL:8.768847, Val MSE:0.010269, Val CE:0.043292, Train ACC:1.000000, Val ACC:0.993750

Epoch 2897/4000: 100%|██████████| 1/1 [00:00<00:00, 24.04it/s]

epoch: 2896, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011634, Train KL:8.768849, Val MSE:0.010265, Val CE:0.043275, Train ACC:1.000000, Val ACC:0.993750

Epoch 2898/4000: 100%|██████████| 1/1 [00:00<00:00, 24.01it/s]

epoch: 2897, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011631, Train KL:8.768851, Val MSE:0.010264, Val CE:0.043468, Train ACC:1.000000, Val ACC:0.993750

Epoch 2899/4000: 100%|██████████| 1/1 [00:00<00:00, 23.82it/s]

epoch: 2898, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011633, Train KL:8.768851, Val MSE:0.010261, Val CE:0.043403, Train ACC:1.000000, Val ACC:0.993750

Epoch 2900/4000: 100%|██████████| 1/1 [00:00<00:00, 21.52it/s]

epoch: 2899, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011637, Train KL:8.768853, Val MSE:0.010280, Val CE:0.043421, Train ACC:1.000000, Val ACC:0.993750

Epoch 2901/4000: 100%|██████████| 1/1 [00:00<00:00, 24.03it/s]

epoch: 2900, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011628, Train KL:8.768853, Val MSE:0.010262, Val CE:0.043277, Train ACC:1.000000, Val ACC:0.993750

Epoch 2902/4000: 100%|██████████| 1/1 [00:00<00:00, 23.87it/s]

epoch: 2901, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011633, Train KL:8.768854, Val MSE:0.010288, Val CE:0.043677, Train ACC:1.000000, Val ACC:0.993750

Epoch 2903/4000: 100%|██████████| 1/1 [00:00<00:00, 23.58it/s]

epoch: 2902, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011633, Train KL:8.768855, Val MSE:0.010264, Val CE:0.043384, Train ACC:1.000000, Val ACC:0.993750

Epoch 2904/4000: 100%|██████████| 1/1 [00:00<00:00, 22.45it/s]

epoch: 2903, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011636, Train KL:8.768857, Val MSE:0.010293, Val CE:0.043420, Train ACC:1.000000, Val ACC:0.993750

Epoch 2905/4000: 100%|██████████| 1/1 [00:00<00:00, 24.88it/s]

epoch: 2904, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011632, Train KL:8.768858, Val MSE:0.010279, Val CE:0.043483, Train ACC:1.000000, Val ACC:0.993750

Epoch 2906/4000: 100%|██████████| 1/1 [00:00<00:00, 24.02it/s]

epoch: 2905, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011635, Train KL:8.768859, Val MSE:0.010267, Val CE:0.043562, Train ACC:1.000000, Val ACC:0.993750

Epoch 2907/4000: 100%|██████████| 1/1 [00:00<00:00, 24.54it/s]

epoch: 2906, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011632, Train KL:8.768860, Val MSE:0.010281, Val CE:0.043425, Train ACC:1.000000, Val ACC:0.993750

Epoch 2908/4000: 100%|██████████| 1/1 [00:00<00:00, 22.82it/s]

epoch: 2907, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011637, Train KL:8.768862, Val MSE:0.010286, Val CE:0.043520, Train ACC:1.000000, Val ACC:0.993750

Epoch 2909/4000: 100%|██████████| 1/1 [00:00<00:00, 17.04it/s]

epoch: 2908, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011632, Train KL:8.768863, Val MSE:0.010270, Val CE:0.043582, Train ACC:1.000000, Val ACC:0.993750

Epoch 2910/4000: 100%|██████████| 1/1 [00:00<00:00, 22.89it/s]

epoch: 2909, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011638, Train KL:8.768863, Val MSE:0.010268, Val CE:0.043534, Train ACC:1.000000, Val ACC:0.993750

Epoch 2911/4000: 100%|██████████| 1/1 [00:00<00:00, 23.83it/s]

epoch: 2910, beta = 0.000097, Train MSE: 0.006614, Train CE:0.011630, Train KL:8.768865, Val MSE:0.010282, Val CE:0.043435, Train ACC:1.000000, Val ACC:0.993750

Epoch 2912/4000: 100%|██████████| 1/1 [00:00<00:00, 23.23it/s]

epoch: 2911, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011633, Train KL:8.768867, Val MSE:0.010289, Val CE:0.043634, Train ACC:1.000000, Val ACC:0.993750

Epoch 2913/4000: 100%|██████████| 1/1 [00:00<00:00, 23.07it/s]

epoch: 2912, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011632, Train KL:8.768867, Val MSE:0.010292, Val CE:0.043469, Train ACC:1.000000, Val ACC:0.993750

Epoch 2914/4000: 100%|██████████| 1/1 [00:00<00:00, 23.74it/s]

epoch: 2913, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011631, Train KL:8.768867, Val MSE:0.010285, Val CE:0.043371, Train ACC:1.000000, Val ACC:0.993750

Epoch 2915/4000: 100%|██████████| 1/1 [00:00<00:00, 23.55it/s]

epoch: 2914, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011631, Train KL:8.768868, Val MSE:0.010277, Val CE:0.043460, Train ACC:1.000000, Val ACC:0.993750

Epoch 2916/4000: 100%|██████████| 1/1 [00:00<00:00, 22.91it/s]

epoch: 2915, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011633, Train KL:8.768870, Val MSE:0.010290, Val CE:0.043690, Train ACC:1.000000, Val ACC:0.993750

Epoch 2917/4000: 100%|██████████| 1/1 [00:00<00:00, 22.53it/s]

epoch: 2916, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011637, Train KL:8.768870, Val MSE:0.010279, Val CE:0.043561, Train ACC:1.000000, Val ACC:0.993750

Epoch 2918/4000: 100%|██████████| 1/1 [00:00<00:00, 21.83it/s]

epoch: 2917, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011632, Train KL:8.768872, Val MSE:0.010293, Val CE:0.043524, Train ACC:1.000000, Val ACC:0.993750

Epoch 2919/4000: 100%|██████████| 1/1 [00:00<00:00, 24.01it/s]

epoch: 2918, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011636, Train KL:8.768874, Val MSE:0.010280, Val CE:0.043455, Train ACC:1.000000, Val ACC:0.993750

Epoch 2920/4000: 100%|██████████| 1/1 [00:00<00:00, 23.65it/s]

epoch: 2919, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011633, Train KL:8.768874, Val MSE:0.010293, Val CE:0.043432, Train ACC:1.000000, Val ACC:0.993750

Epoch 2921/4000: 100%|██████████| 1/1 [00:00<00:00, 22.32it/s]

epoch: 2920, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011636, Train KL:8.768875, Val MSE:0.010291, Val CE:0.043308, Train ACC:1.000000, Val ACC:0.993750

Epoch 2922/4000: 100%|██████████| 1/1 [00:00<00:00, 23.93it/s]

epoch: 2921, beta = 0.000097, Train MSE: 0.006595, Train CE:0.011638, Train KL:8.768877, Val MSE:0.010297, Val CE:0.043512, Train ACC:1.000000, Val ACC:0.993750

Epoch 2923/4000: 100%|██████████| 1/1 [00:00<00:00, 21.88it/s]

epoch: 2922, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011636, Train KL:8.768878, Val MSE:0.010275, Val CE:0.043480, Train ACC:1.000000, Val ACC:0.993750

Epoch 2924/4000: 100%|██████████| 1/1 [00:00<00:00, 23.95it/s]

epoch: 2923, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011634, Train KL:8.768878, Val MSE:0.010278, Val CE:0.043395, Train ACC:1.000000, Val ACC:0.993750

Epoch 2925/4000: 100%|██████████| 1/1 [00:00<00:00, 24.02it/s]

epoch: 2924, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011636, Train KL:8.768880, Val MSE:0.010278, Val CE:0.043374, Train ACC:1.000000, Val ACC:0.993750

Epoch 2926/4000: 100%|██████████| 1/1 [00:00<00:00, 22.97it/s]

epoch: 2925, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011631, Train KL:8.768881, Val MSE:0.010273, Val CE:0.043290, Train ACC:1.000000, Val ACC:0.993750

Epoch 2927/4000: 100%|██████████| 1/1 [00:00<00:00, 19.93it/s]

epoch: 2926, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011636, Train KL:8.768882, Val MSE:0.010288, Val CE:0.043487, Train ACC:1.000000, Val ACC:0.993750

Epoch 2928/4000: 100%|██████████| 1/1 [00:00<00:00, 23.85it/s]

epoch: 2927, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011632, Train KL:8.768883, Val MSE:0.010276, Val CE:0.043365, Train ACC:1.000000, Val ACC:0.993750

Epoch 2929/4000: 100%|██████████| 1/1 [00:00<00:00, 19.64it/s]

epoch: 2928, beta = 0.000097, Train MSE: 0.006595, Train CE:0.011633, Train KL:8.768884, Val MSE:0.010290, Val CE:0.043556, Train ACC:1.000000, Val ACC:0.993750

Epoch 2930/4000: 100%|██████████| 1/1 [00:00<00:00, 25.84it/s]

epoch: 2929, beta = 0.000097, Train MSE: 0.006594, Train CE:0.011636, Train KL:8.768885, Val MSE:0.010295, Val CE:0.043385, Train ACC:1.000000, Val ACC:0.993750

Epoch 2931/4000: 100%|██████████| 1/1 [00:00<00:00, 24.18it/s]

epoch: 2930, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011631, Train KL:8.768886, Val MSE:0.010269, Val CE:0.043445, Train ACC:1.000000, Val ACC:0.993750

Epoch 2932/4000: 100%|██████████| 1/1 [00:00<00:00, 23.43it/s]

epoch: 2931, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011632, Train KL:8.768887, Val MSE:0.010289, Val CE:0.043472, Train ACC:1.000000, Val ACC:0.993750

Epoch 2933/4000: 100%|██████████| 1/1 [00:00<00:00, 23.35it/s]

epoch: 2932, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011630, Train KL:8.768888, Val MSE:0.010292, Val CE:0.043498, Train ACC:1.000000, Val ACC:0.993750

Epoch 2934/4000: 100%|██████████| 1/1 [00:00<00:00, 21.83it/s]

epoch: 2933, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011633, Train KL:8.768889, Val MSE:0.010293, Val CE:0.043290, Train ACC:1.000000, Val ACC:0.993750

Epoch 2935/4000: 100%|██████████| 1/1 [00:00<00:00, 24.10it/s]

epoch: 2934, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011627, Train KL:8.768889, Val MSE:0.010277, Val CE:0.043570, Train ACC:1.000000, Val ACC:0.993750

Epoch 2936/4000: 100%|██████████| 1/1 [00:00<00:00, 23.62it/s]

epoch: 2935, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011634, Train KL:8.768890, Val MSE:0.010296, Val CE:0.043386, Train ACC:1.000000, Val ACC:0.993750

Epoch 2937/4000: 100%|██████████| 1/1 [00:00<00:00, 24.04it/s]

epoch: 2936, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011633, Train KL:8.768892, Val MSE:0.010280, Val CE:0.043391, Train ACC:1.000000, Val ACC:0.993750

Epoch 2938/4000: 100%|██████████| 1/1 [00:00<00:00, 22.68it/s]

epoch: 2937, beta = 0.000097, Train MSE: 0.006594, Train CE:0.011632, Train KL:8.768893, Val MSE:0.010271, Val CE:0.043466, Train ACC:1.000000, Val ACC:0.993750

Epoch 2939/4000: 100%|██████████| 1/1 [00:00<00:00, 24.11it/s]

epoch: 2938, beta = 0.000097, Train MSE: 0.006588, Train CE:0.011630, Train KL:8.768894, Val MSE:0.010286, Val CE:0.043542, Train ACC:1.000000, Val ACC:0.993750

Epoch 2940/4000: 100%|██████████| 1/1 [00:00<00:00, 23.65it/s]

epoch: 2939, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011634, Train KL:8.768896, Val MSE:0.010304, Val CE:0.043603, Train ACC:1.000000, Val ACC:0.993750

Epoch 2941/4000: 100%|██████████| 1/1 [00:00<00:00, 19.81it/s]

epoch: 2940, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011632, Train KL:8.768897, Val MSE:0.010271, Val CE:0.043303, Train ACC:1.000000, Val ACC:0.993750

Epoch 2942/4000: 100%|██████████| 1/1 [00:00<00:00, 21.98it/s]

epoch: 2941, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011631, Train KL:8.768898, Val MSE:0.010276, Val CE:0.043480, Train ACC:1.000000, Val ACC:0.993750

Epoch 2943/4000: 100%|██████████| 1/1 [00:00<00:00, 22.37it/s]

epoch: 2942, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011628, Train KL:8.768898, Val MSE:0.010302, Val CE:0.043317, Train ACC:1.000000, Val ACC:0.993750

Epoch 2944/4000: 100%|██████████| 1/1 [00:00<00:00, 22.56it/s]

epoch: 2943, beta = 0.000097, Train MSE: 0.006611, Train CE:0.011630, Train KL:8.768900, Val MSE:0.010267, Val CE:0.043556, Train ACC:1.000000, Val ACC:0.993750

Epoch 2945/4000: 100%|██████████| 1/1 [00:00<00:00, 24.05it/s]

epoch: 2944, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011632, Train KL:8.768901, Val MSE:0.010285, Val CE:0.043357, Train ACC:1.000000, Val ACC:0.993750

Epoch 2946/4000: 100%|██████████| 1/1 [00:00<00:00, 24.05it/s]

epoch: 2945, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011634, Train KL:8.768901, Val MSE:0.010296, Val CE:0.043416, Train ACC:1.000000, Val ACC:0.993750

Epoch 2947/4000: 100%|██████████| 1/1 [00:00<00:00, 24.03it/s]

epoch: 2946, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011633, Train KL:8.768903, Val MSE:0.010296, Val CE:0.043573, Train ACC:1.000000, Val ACC:0.993750

Epoch 2948/4000: 100%|██████████| 1/1 [00:00<00:00, 25.41it/s]

epoch: 2947, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011632, Train KL:8.768904, Val MSE:0.010283, Val CE:0.043412, Train ACC:1.000000, Val ACC:0.993750

Epoch 2949/4000: 100%|██████████| 1/1 [00:00<00:00, 25.71it/s]

epoch: 2948, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011631, Train KL:8.768905, Val MSE:0.010257, Val CE:0.043487, Train ACC:1.000000, Val ACC:0.993750

Epoch 2950/4000: 100%|██████████| 1/1 [00:00<00:00, 24.04it/s]

epoch: 2949, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011630, Train KL:8.768906, Val MSE:0.010274, Val CE:0.043450, Train ACC:1.000000, Val ACC:0.993750

Epoch 2951/4000: 100%|██████████| 1/1 [00:00<00:00, 21.46it/s]

epoch: 2950, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011628, Train KL:8.768906, Val MSE:0.010275, Val CE:0.043459, Train ACC:1.000000, Val ACC:0.993750

Epoch 2952/4000: 100%|██████████| 1/1 [00:00<00:00, 23.25it/s]

epoch: 2951, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011638, Train KL:8.768908, Val MSE:0.010279, Val CE:0.043487, Train ACC:1.000000, Val ACC:0.993750

Epoch 2953/4000: 100%|██████████| 1/1 [00:00<00:00, 27.14it/s]

epoch: 2952, beta = 0.000097, Train MSE: 0.006594, Train CE:0.011636, Train KL:8.768909, Val MSE:0.010271, Val CE:0.043479, Train ACC:1.000000, Val ACC:0.993750

Epoch 2954/4000: 100%|██████████| 1/1 [00:00<00:00, 23.73it/s]

epoch: 2953, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011635, Train KL:8.768909, Val MSE:0.010286, Val CE:0.043664, Train ACC:1.000000, Val ACC:0.993750

Epoch 2955/4000: 100%|██████████| 1/1 [00:00<00:00, 23.73it/s]

epoch: 2954, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011632, Train KL:8.768910, Val MSE:0.010280, Val CE:0.043371, Train ACC:1.000000, Val ACC:0.993750

Epoch 2956/4000: 100%|██████████| 1/1 [00:00<00:00, 23.48it/s]

epoch: 2955, beta = 0.000097, Train MSE: 0.006611, Train CE:0.011628, Train KL:8.768911, Val MSE:0.010283, Val CE:0.043453, Train ACC:1.000000, Val ACC:0.993750

Epoch 2957/4000: 100%|██████████| 1/1 [00:00<00:00, 18.05it/s]

epoch: 2956, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011633, Train KL:8.768912, Val MSE:0.010296, Val CE:0.043439, Train ACC:1.000000, Val ACC:0.993750

Epoch 2958/4000: 100%|██████████| 1/1 [00:00<00:00, 21.17it/s]

epoch: 2957, beta = 0.000097, Train MSE: 0.006611, Train CE:0.011637, Train KL:8.768912, Val MSE:0.010281, Val CE:0.043371, Train ACC:1.000000, Val ACC:0.993750

Epoch 2959/4000: 100%|██████████| 1/1 [00:00<00:00, 22.46it/s]

epoch: 2958, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011630, Train KL:8.768914, Val MSE:0.010281, Val CE:0.043419, Train ACC:1.000000, Val ACC:0.993750

Epoch 2960/4000: 100%|██████████| 1/1 [00:00<00:00, 24.22it/s]

epoch: 2959, beta = 0.000097, Train MSE: 0.006617, Train CE:0.011633, Train KL:8.768915, Val MSE:0.010276, Val CE:0.043518, Train ACC:1.000000, Val ACC:0.993750

Epoch 2961/4000: 100%|██████████| 1/1 [00:00<00:00, 23.28it/s]

epoch: 2960, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011631, Train KL:8.768916, Val MSE:0.010309, Val CE:0.043422, Train ACC:1.000000, Val ACC:0.993750

Epoch 2962/4000: 100%|██████████| 1/1 [00:00<00:00, 23.65it/s]

epoch: 2961, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011631, Train KL:8.768918, Val MSE:0.010268, Val CE:0.043439, Train ACC:1.000000, Val ACC:0.993750

Epoch 2963/4000: 100%|██████████| 1/1 [00:00<00:00, 23.85it/s]

epoch: 2962, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011638, Train KL:8.768919, Val MSE:0.010282, Val CE:0.043310, Train ACC:1.000000, Val ACC:0.993750

Epoch 2964/4000: 100%|██████████| 1/1 [00:00<00:00, 23.12it/s]

epoch: 2963, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011635, Train KL:8.768920, Val MSE:0.010242, Val CE:0.043367, Train ACC:1.000000, Val ACC:0.993750

Epoch 2965/4000: 100%|██████████| 1/1 [00:00<00:00, 24.14it/s]

epoch: 2964, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011631, Train KL:8.768921, Val MSE:0.010274, Val CE:0.043486, Train ACC:1.000000, Val ACC:0.993750

Epoch 2966/4000: 100%|██████████| 1/1 [00:00<00:00, 23.73it/s]

epoch: 2965, beta = 0.000097, Train MSE: 0.006590, Train CE:0.011631, Train KL:8.768923, Val MSE:0.010274, Val CE:0.043375, Train ACC:1.000000, Val ACC:0.993750

Epoch 2967/4000: 100%|██████████| 1/1 [00:00<00:00, 24.35it/s]

epoch: 2966, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011630, Train KL:8.768924, Val MSE:0.010277, Val CE:0.043443, Train ACC:1.000000, Val ACC:0.993750

Epoch 2968/4000: 100%|██████████| 1/1 [00:00<00:00, 23.82it/s]

epoch: 2967, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011635, Train KL:8.768924, Val MSE:0.010294, Val CE:0.043568, Train ACC:1.000000, Val ACC:0.993750

Epoch 2969/4000: 100%|██████████| 1/1 [00:00<00:00, 24.38it/s]

epoch: 2968, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011628, Train KL:8.768926, Val MSE:0.010302, Val CE:0.043568, Train ACC:1.000000, Val ACC:0.993750

Epoch 2970/4000: 100%|██████████| 1/1 [00:00<00:00, 24.01it/s]

epoch: 2969, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011627, Train KL:8.768927, Val MSE:0.010288, Val CE:0.043665, Train ACC:1.000000, Val ACC:0.993750

Epoch 2971/4000: 100%|██████████| 1/1 [00:00<00:00, 22.89it/s]

epoch: 2970, beta = 0.000097, Train MSE: 0.006621, Train CE:0.011636, Train KL:8.768928, Val MSE:0.010264, Val CE:0.043453, Train ACC:1.000000, Val ACC:0.993750

Epoch 2972/4000: 100%|██████████| 1/1 [00:00<00:00, 24.26it/s]

epoch: 2971, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011629, Train KL:8.768929, Val MSE:0.010245, Val CE:0.043458, Train ACC:1.000000, Val ACC:0.993750

Epoch 2973/4000: 100%|██████████| 1/1 [00:00<00:00, 23.78it/s]

epoch: 2972, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011633, Train KL:8.768930, Val MSE:0.010269, Val CE:0.043426, Train ACC:1.000000, Val ACC:0.993750

Epoch 2974/4000: 100%|██████████| 1/1 [00:00<00:00, 21.82it/s]

epoch: 2973, beta = 0.000097, Train MSE: 0.006616, Train CE:0.011632, Train KL:8.768930, Val MSE:0.010299, Val CE:0.043621, Train ACC:1.000000, Val ACC:0.993750

Epoch 2975/4000: 100%|██████████| 1/1 [00:00<00:00, 21.86it/s]

epoch: 2974, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011629, Train KL:8.768931, Val MSE:0.010272, Val CE:0.043349, Train ACC:1.000000, Val ACC:0.993750

Epoch 2976/4000: 100%|██████████| 1/1 [00:00<00:00, 24.45it/s]

epoch: 2975, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011635, Train KL:8.768931, Val MSE:0.010250, Val CE:0.043615, Train ACC:1.000000, Val ACC:0.993750

Epoch 2977/4000: 100%|██████████| 1/1 [00:00<00:00, 24.40it/s]

epoch: 2976, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011634, Train KL:8.768935, Val MSE:0.010283, Val CE:0.043392, Train ACC:1.000000, Val ACC:0.993750

Epoch 2978/4000: 100%|██████████| 1/1 [00:00<00:00, 24.24it/s]

epoch: 2977, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011631, Train KL:8.768935, Val MSE:0.010294, Val CE:0.043439, Train ACC:1.000000, Val ACC:0.993750

Epoch 2979/4000: 100%|██████████| 1/1 [00:00<00:00, 24.42it/s]

epoch: 2978, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011635, Train KL:8.768936, Val MSE:0.010274, Val CE:0.043524, Train ACC:1.000000, Val ACC:0.993750

Epoch 2980/4000: 100%|██████████| 1/1 [00:00<00:00, 24.02it/s]

epoch: 2979, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011639, Train KL:8.768938, Val MSE:0.010273, Val CE:0.043383, Train ACC:1.000000, Val ACC:0.993750

Epoch 2981/4000: 100%|██████████| 1/1 [00:00<00:00, 24.30it/s]

epoch: 2980, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011636, Train KL:8.768939, Val MSE:0.010265, Val CE:0.043488, Train ACC:1.000000, Val ACC:0.993750

Epoch 2982/4000: 100%|██████████| 1/1 [00:00<00:00, 24.28it/s]

epoch: 2981, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011634, Train KL:8.768941, Val MSE:0.010278, Val CE:0.043560, Train ACC:1.000000, Val ACC:0.993750

Epoch 2983/4000: 100%|██████████| 1/1 [00:00<00:00, 24.62it/s]

epoch: 2982, beta = 0.000097, Train MSE: 0.006617, Train CE:0.011631, Train KL:8.768943, Val MSE:0.010277, Val CE:0.043533, Train ACC:1.000000, Val ACC:0.993750

Epoch 2984/4000: 100%|██████████| 1/1 [00:00<00:00, 23.79it/s]

epoch: 2983, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011632, Train KL:8.768944, Val MSE:0.010279, Val CE:0.043498, Train ACC:1.000000, Val ACC:0.993750

Epoch 2985/4000: 100%|██████████| 1/1 [00:00<00:00, 24.78it/s]

epoch: 2984, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011625, Train KL:8.768946, Val MSE:0.010289, Val CE:0.043582, Train ACC:1.000000, Val ACC:0.993750

Epoch 2986/4000: 100%|██████████| 1/1 [00:00<00:00, 22.07it/s]

epoch: 2985, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011632, Train KL:8.768947, Val MSE:0.010259, Val CE:0.043405, Train ACC:1.000000, Val ACC:0.993750

Epoch 2987/4000: 100%|██████████| 1/1 [00:00<00:00, 24.43it/s]

epoch: 2986, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011636, Train KL:8.768948, Val MSE:0.010307, Val CE:0.043478, Train ACC:1.000000, Val ACC:0.993750

Epoch 2988/4000: 100%|██████████| 1/1 [00:00<00:00, 18.90it/s]

epoch: 2987, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011634, Train KL:8.768949, Val MSE:0.010278, Val CE:0.043549, Train ACC:1.000000, Val ACC:0.993750

Epoch 2989/4000: 100%|██████████| 1/1 [00:00<00:00, 21.51it/s]

epoch: 2988, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011639, Train KL:8.768950, Val MSE:0.010267, Val CE:0.043301, Train ACC:1.000000, Val ACC:0.993750

Epoch 2990/4000: 100%|██████████| 1/1 [00:00<00:00, 23.47it/s]

epoch: 2989, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011631, Train KL:8.768951, Val MSE:0.010300, Val CE:0.043427, Train ACC:1.000000, Val ACC:0.993750

Epoch 2991/4000: 100%|██████████| 1/1 [00:00<00:00, 23.11it/s]

epoch: 2990, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011631, Train KL:8.768953, Val MSE:0.010268, Val CE:0.043502, Train ACC:1.000000, Val ACC:0.993750

Epoch 2992/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 2991, beta = 0.000097, Train MSE: 0.006613, Train CE:0.011630, Train KL:8.768954, Val MSE:0.010298, Val CE:0.043436, Train ACC:1.000000, Val ACC:0.993750

Epoch 2993/4000: 100%|██████████| 1/1 [00:00<00:00, 22.75it/s]

epoch: 2992, beta = 0.000097, Train MSE: 0.006595, Train CE:0.011633, Train KL:8.768955, Val MSE:0.010302, Val CE:0.043588, Train ACC:1.000000, Val ACC:0.993750

Epoch 2994/4000: 100%|██████████| 1/1 [00:00<00:00, 23.55it/s]

epoch: 2993, beta = 0.000097, Train MSE: 0.006614, Train CE:0.011637, Train KL:8.768956, Val MSE:0.010256, Val CE:0.043658, Train ACC:1.000000, Val ACC:0.993750

Epoch 2995/4000: 100%|██████████| 1/1 [00:00<00:00, 25.27it/s]

epoch: 2994, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011629, Train KL:8.768958, Val MSE:0.010282, Val CE:0.043294, Train ACC:1.000000, Val ACC:0.993750

Epoch 2996/4000: 100%|██████████| 1/1 [00:00<00:00, 23.40it/s]

epoch: 2995, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011630, Train KL:8.768959, Val MSE:0.010270, Val CE:0.043375, Train ACC:1.000000, Val ACC:0.993750

Epoch 2997/4000: 100%|██████████| 1/1 [00:00<00:00, 25.24it/s]

epoch: 2996, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011629, Train KL:8.768961, Val MSE:0.010297, Val CE:0.043416, Train ACC:1.000000, Val ACC:0.993750

Epoch 2998/4000: 100%|██████████| 1/1 [00:00<00:00, 25.12it/s]

epoch: 2997, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011631, Train KL:8.768962, Val MSE:0.010272, Val CE:0.043471, Train ACC:1.000000, Val ACC:0.993750

Epoch 2999/4000: 100%|██████████| 1/1 [00:00<00:00, 24.62it/s]

epoch: 2998, beta = 0.000097, Train MSE: 0.006611, Train CE:0.011630, Train KL:8.768963, Val MSE:0.010299, Val CE:0.043553, Train ACC:1.000000, Val ACC:0.993750

Epoch 3000/4000: 100%|██████████| 1/1 [00:00<00:00, 22.08it/s]

epoch: 2999, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011633, Train KL:8.768963, Val MSE:0.010301, Val CE:0.043511, Train ACC:1.000000, Val ACC:0.993750

Epoch 3001/4000: 100%|██████████| 1/1 [00:00<00:00, 23.42it/s]

epoch: 3000, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011634, Train KL:8.768964, Val MSE:0.010279, Val CE:0.043368, Train ACC:1.000000, Val ACC:0.993750

Epoch 3002/4000: 100%|██████████| 1/1 [00:00<00:00, 22.14it/s]

epoch: 3001, beta = 0.000097, Train MSE: 0.006615, Train CE:0.011637, Train KL:8.768966, Val MSE:0.010272, Val CE:0.043502, Train ACC:1.000000, Val ACC:0.993750

Epoch 3003/4000: 100%|██████████| 1/1 [00:00<00:00, 24.12it/s]

epoch: 3002, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011631, Train KL:8.768967, Val MSE:0.010298, Val CE:0.043602, Train ACC:1.000000, Val ACC:0.993750

Epoch 3004/4000: 100%|██████████| 1/1 [00:00<00:00, 23.34it/s]

epoch: 3003, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011629, Train KL:8.768968, Val MSE:0.010301, Val CE:0.043324, Train ACC:1.000000, Val ACC:0.993750

Epoch 3005/4000: 100%|██████████| 1/1 [00:00<00:00, 23.17it/s]

epoch: 3004, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011631, Train KL:8.768970, Val MSE:0.010297, Val CE:0.043384, Train ACC:1.000000, Val ACC:0.993750

Epoch 3006/4000: 100%|██████████| 1/1 [00:00<00:00, 20.59it/s]

epoch: 3005, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011633, Train KL:8.768970, Val MSE:0.010269, Val CE:0.043491, Train ACC:1.000000, Val ACC:0.993750

Epoch 3007/4000: 100%|██████████| 1/1 [00:00<00:00, 21.33it/s]

epoch: 3006, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011633, Train KL:8.768971, Val MSE:0.010304, Val CE:0.043491, Train ACC:1.000000, Val ACC:0.993750

Epoch 3008/4000: 100%|██████████| 1/1 [00:00<00:00, 21.66it/s]

epoch: 3007, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011632, Train KL:8.768973, Val MSE:0.010293, Val CE:0.043551, Train ACC:1.000000, Val ACC:0.993750

Epoch 3009/4000: 100%|██████████| 1/1 [00:00<00:00, 24.01it/s]

epoch: 3008, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011636, Train KL:8.768974, Val MSE:0.010272, Val CE:0.043262, Train ACC:1.000000, Val ACC:0.993750

Epoch 3010/4000: 100%|██████████| 1/1 [00:00<00:00, 24.63it/s]

epoch: 3009, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011637, Train KL:8.768974, Val MSE:0.010291, Val CE:0.043369, Train ACC:1.000000, Val ACC:0.993750

Epoch 3011/4000: 100%|██████████| 1/1 [00:00<00:00, 25.18it/s]

epoch: 3010, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011629, Train KL:8.768977, Val MSE:0.010290, Val CE:0.043542, Train ACC:1.000000, Val ACC:0.993750

Epoch 3012/4000: 100%|██████████| 1/1 [00:00<00:00, 24.13it/s]

epoch: 3011, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011630, Train KL:8.768978, Val MSE:0.010294, Val CE:0.043187, Train ACC:1.000000, Val ACC:0.993750

Epoch 3013/4000: 100%|██████████| 1/1 [00:00<00:00, 21.76it/s]

epoch: 3012, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011632, Train KL:8.768978, Val MSE:0.010274, Val CE:0.043325, Train ACC:1.000000, Val ACC:0.993750

Epoch 3014/4000: 100%|██████████| 1/1 [00:00<00:00, 21.01it/s]

epoch: 3013, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011625, Train KL:8.768980, Val MSE:0.010255, Val CE:0.043473, Train ACC:1.000000, Val ACC:0.993750

Epoch 3015/4000: 100%|██████████| 1/1 [00:00<00:00, 24.37it/s]

epoch: 3014, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011633, Train KL:8.768981, Val MSE:0.010320, Val CE:0.043378, Train ACC:1.000000, Val ACC:0.993750

Epoch 3016/4000: 100%|██████████| 1/1 [00:00<00:00, 24.63it/s]

epoch: 3015, beta = 0.000097, Train MSE: 0.006614, Train CE:0.011636, Train KL:8.768982, Val MSE:0.010257, Val CE:0.043641, Train ACC:1.000000, Val ACC:0.993750

Epoch 3017/4000: 100%|██████████| 1/1 [00:00<00:00, 23.93it/s]

epoch: 3016, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011633, Train KL:8.768984, Val MSE:0.010302, Val CE:0.043596, Train ACC:1.000000, Val ACC:0.993750

Epoch 3018/4000: 100%|██████████| 1/1 [00:00<00:00, 27.01it/s]

epoch: 3017, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011628, Train KL:8.768985, Val MSE:0.010304, Val CE:0.043372, Train ACC:1.000000, Val ACC:0.993750

Epoch 3019/4000: 100%|██████████| 1/1 [00:00<00:00, 22.47it/s]

epoch: 3018, beta = 0.000097, Train MSE: 0.006590, Train CE:0.011629, Train KL:8.768986, Val MSE:0.010299, Val CE:0.043520, Train ACC:1.000000, Val ACC:0.993750

Epoch 3020/4000: 100%|██████████| 1/1 [00:00<00:00, 22.56it/s]

epoch: 3019, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011623, Train KL:8.768987, Val MSE:0.010266, Val CE:0.043331, Train ACC:1.000000, Val ACC:0.993750

Epoch 3021/4000: 100%|██████████| 1/1 [00:00<00:00, 23.07it/s]

epoch: 3020, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011632, Train KL:8.768988, Val MSE:0.010258, Val CE:0.043523, Train ACC:1.000000, Val ACC:0.993750

Epoch 3022/4000: 100%|██████████| 1/1 [00:00<00:00, 22.89it/s]

epoch: 3021, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011635, Train KL:8.768989, Val MSE:0.010285, Val CE:0.043655, Train ACC:1.000000, Val ACC:0.993750

Epoch 3023/4000: 100%|██████████| 1/1 [00:00<00:00, 24.25it/s]

epoch: 3022, beta = 0.000097, Train MSE: 0.006594, Train CE:0.011631, Train KL:8.768991, Val MSE:0.010254, Val CE:0.043420, Train ACC:1.000000, Val ACC:0.993750

Epoch 3024/4000: 100%|██████████| 1/1 [00:00<00:00, 23.23it/s]

epoch: 3023, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011628, Train KL:8.768991, Val MSE:0.010285, Val CE:0.043373, Train ACC:1.000000, Val ACC:0.993750

Epoch 3025/4000: 100%|██████████| 1/1 [00:00<00:00, 23.31it/s]

epoch: 3024, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011625, Train KL:8.768993, Val MSE:0.010271, Val CE:0.043298, Train ACC:1.000000, Val ACC:0.993750

Epoch 3026/4000: 100%|██████████| 1/1 [00:00<00:00, 24.73it/s]

epoch: 3025, beta = 0.000097, Train MSE: 0.006613, Train CE:0.011628, Train KL:8.768994, Val MSE:0.010273, Val CE:0.043475, Train ACC:1.000000, Val ACC:0.993750

Epoch 3027/4000: 100%|██████████| 1/1 [00:00<00:00, 23.67it/s]

epoch: 3026, beta = 0.000097, Train MSE: 0.006594, Train CE:0.011632, Train KL:8.768996, Val MSE:0.010270, Val CE:0.043502, Train ACC:1.000000, Val ACC:0.993750

Epoch 3028/4000: 100%|██████████| 1/1 [00:00<00:00, 24.51it/s]

epoch: 3027, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011631, Train KL:8.768997, Val MSE:0.010296, Val CE:0.043497, Train ACC:1.000000, Val ACC:0.993750

Epoch 3029/4000: 100%|██████████| 1/1 [00:00<00:00, 23.88it/s]

epoch: 3028, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011635, Train KL:8.768997, Val MSE:0.010322, Val CE:0.043604, Train ACC:1.000000, Val ACC:0.993750

Epoch 3030/4000: 100%|██████████| 1/1 [00:00<00:00, 24.09it/s]

epoch: 3029, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011632, Train KL:8.768998, Val MSE:0.010291, Val CE:0.043432, Train ACC:1.000000, Val ACC:0.993750

Epoch 3031/4000: 100%|██████████| 1/1 [00:00<00:00, 22.73it/s]

epoch: 3030, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011629, Train KL:8.769001, Val MSE:0.010289, Val CE:0.043437, Train ACC:1.000000, Val ACC:0.993750

Epoch 3032/4000: 100%|██████████| 1/1 [00:00<00:00, 23.33it/s]

epoch: 3031, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011627, Train KL:8.769002, Val MSE:0.010295, Val CE:0.043445, Train ACC:1.000000, Val ACC:0.993750

Epoch 3033/4000: 100%|██████████| 1/1 [00:00<00:00, 22.97it/s]

epoch: 3032, beta = 0.000097, Train MSE: 0.006621, Train CE:0.011631, Train KL:8.769003, Val MSE:0.010301, Val CE:0.043301, Train ACC:1.000000, Val ACC:0.993750

Epoch 3034/4000: 100%|██████████| 1/1 [00:00<00:00, 18.93it/s]

epoch: 3033, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011628, Train KL:8.769005, Val MSE:0.010287, Val CE:0.043626, Train ACC:1.000000, Val ACC:0.993750

Epoch 3035/4000: 100%|██████████| 1/1 [00:00<00:00, 21.01it/s]

epoch: 3034, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011631, Train KL:8.769005, Val MSE:0.010290, Val CE:0.043596, Train ACC:1.000000, Val ACC:0.993750

Epoch 3036/4000: 100%|██████████| 1/1 [00:00<00:00, 21.36it/s]

epoch: 3035, beta = 0.000097, Train MSE: 0.006594, Train CE:0.011631, Train KL:8.769007, Val MSE:0.010291, Val CE:0.043571, Train ACC:1.000000, Val ACC:0.993750

Epoch 3037/4000: 100%|██████████| 1/1 [00:00<00:00, 21.48it/s]

epoch: 3036, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011629, Train KL:8.769009, Val MSE:0.010294, Val CE:0.043591, Train ACC:1.000000, Val ACC:0.993750

Epoch 3038/4000: 100%|██████████| 1/1 [00:00<00:00, 24.02it/s]

epoch: 3037, beta = 0.000097, Train MSE: 0.006615, Train CE:0.011632, Train KL:8.769010, Val MSE:0.010263, Val CE:0.043334, Train ACC:1.000000, Val ACC:0.993750

Epoch 3039/4000: 100%|██████████| 1/1 [00:00<00:00, 23.79it/s]

epoch: 3038, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011636, Train KL:8.769011, Val MSE:0.010272, Val CE:0.043625, Train ACC:1.000000, Val ACC:0.993750

Epoch 3040/4000: 100%|██████████| 1/1 [00:00<00:00, 24.42it/s]

epoch: 3039, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011631, Train KL:8.769012, Val MSE:0.010272, Val CE:0.043520, Train ACC:1.000000, Val ACC:0.993750

Epoch 3041/4000: 100%|██████████| 1/1 [00:00<00:00, 23.32it/s]

epoch: 3040, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011629, Train KL:8.769014, Val MSE:0.010295, Val CE:0.043635, Train ACC:1.000000, Val ACC:0.993750

Epoch 3042/4000: 100%|██████████| 1/1 [00:00<00:00, 22.87it/s]

epoch: 3041, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011629, Train KL:8.769015, Val MSE:0.010283, Val CE:0.043583, Train ACC:1.000000, Val ACC:0.993750

Epoch 3043/4000: 100%|██████████| 1/1 [00:00<00:00, 23.78it/s]

epoch: 3042, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011628, Train KL:8.769016, Val MSE:0.010296, Val CE:0.043535, Train ACC:1.000000, Val ACC:0.993750

Epoch 3044/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 3043, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011633, Train KL:8.769017, Val MSE:0.010287, Val CE:0.043531, Train ACC:1.000000, Val ACC:0.993750

Epoch 3045/4000: 100%|██████████| 1/1 [00:00<00:00, 23.50it/s]

epoch: 3044, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011632, Train KL:8.769019, Val MSE:0.010309, Val CE:0.043581, Train ACC:1.000000, Val ACC:0.993750

Epoch 3046/4000: 100%|██████████| 1/1 [00:00<00:00, 21.74it/s]

epoch: 3045, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011633, Train KL:8.769020, Val MSE:0.010285, Val CE:0.043644, Train ACC:1.000000, Val ACC:0.993750

Epoch 3047/4000: 100%|██████████| 1/1 [00:00<00:00, 23.94it/s]

epoch: 3046, beta = 0.000097, Train MSE: 0.006592, Train CE:0.011632, Train KL:8.769023, Val MSE:0.010280, Val CE:0.043385, Train ACC:1.000000, Val ACC:0.993750

Epoch 3048/4000: 100%|██████████| 1/1 [00:00<00:00, 23.92it/s]

epoch: 3047, beta = 0.000097, Train MSE: 0.006594, Train CE:0.011633, Train KL:8.769024, Val MSE:0.010324, Val CE:0.043608, Train ACC:1.000000, Val ACC:0.993750

Epoch 3049/4000: 100%|██████████| 1/1 [00:00<00:00, 24.15it/s]

epoch: 3048, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011636, Train KL:8.769025, Val MSE:0.010269, Val CE:0.043336, Train ACC:1.000000, Val ACC:0.993750

Epoch 3050/4000: 100%|██████████| 1/1 [00:00<00:00, 21.93it/s]

epoch: 3049, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011631, Train KL:8.769027, Val MSE:0.010291, Val CE:0.043559, Train ACC:1.000000, Val ACC:0.993750

Epoch 3051/4000: 100%|██████████| 1/1 [00:00<00:00, 21.83it/s]

epoch: 3050, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011632, Train KL:8.769028, Val MSE:0.010296, Val CE:0.043669, Train ACC:1.000000, Val ACC:0.993750

Epoch 3052/4000: 100%|██████████| 1/1 [00:00<00:00, 23.12it/s]

epoch: 3051, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011635, Train KL:8.769028, Val MSE:0.010276, Val CE:0.043300, Train ACC:1.000000, Val ACC:0.993750

Epoch 3053/4000: 100%|██████████| 1/1 [00:00<00:00, 23.91it/s]

epoch: 3052, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011635, Train KL:8.769031, Val MSE:0.010278, Val CE:0.043568, Train ACC:1.000000, Val ACC:0.993750

Epoch 3054/4000: 100%|██████████| 1/1 [00:00<00:00, 24.69it/s]

epoch: 3053, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011632, Train KL:8.769032, Val MSE:0.010283, Val CE:0.043614, Train ACC:1.000000, Val ACC:0.993750

Epoch 3055/4000: 100%|██████████| 1/1 [00:00<00:00, 23.97it/s]

epoch: 3054, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011628, Train KL:8.769032, Val MSE:0.010264, Val CE:0.043462, Train ACC:1.000000, Val ACC:0.993750

Epoch 3056/4000: 100%|██████████| 1/1 [00:00<00:00, 22.94it/s]

epoch: 3055, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011633, Train KL:8.769034, Val MSE:0.010286, Val CE:0.043300, Train ACC:1.000000, Val ACC:0.993750

Epoch 3057/4000: 100%|██████████| 1/1 [00:00<00:00,  6.77it/s]

epoch: 3056, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011632, Train KL:8.769035, Val MSE:0.010269, Val CE:0.043541, Train ACC:1.000000, Val ACC:0.993750

Epoch 3058/4000: 100%|██████████| 1/1 [00:00<00:00, 23.16it/s]

epoch: 3057, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011628, Train KL:8.769036, Val MSE:0.010282, Val CE:0.043336, Train ACC:1.000000, Val ACC:0.993750

Epoch 3059/4000: 100%|██████████| 1/1 [00:00<00:00, 23.46it/s]

epoch: 3058, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011631, Train KL:8.769037, Val MSE:0.010242, Val CE:0.043534, Train ACC:1.000000, Val ACC:0.993750

Epoch 3060/4000: 100%|██████████| 1/1 [00:00<00:00, 20.82it/s]

epoch: 3059, beta = 0.000097, Train MSE: 0.006594, Train CE:0.011631, Train KL:8.769039, Val MSE:0.010275, Val CE:0.043460, Train ACC:1.000000, Val ACC:0.993750

Epoch 3061/4000: 100%|██████████| 1/1 [00:00<00:00, 28.50it/s]

epoch: 3060, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011624, Train KL:8.769040, Val MSE:0.010298, Val CE:0.043534, Train ACC:1.000000, Val ACC:0.993750

Epoch 3062/4000: 100%|██████████| 1/1 [00:00<00:00, 23.39it/s]

epoch: 3061, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011631, Train KL:8.769041, Val MSE:0.010294, Val CE:0.043610, Train ACC:1.000000, Val ACC:0.993750

Epoch 3063/4000: 100%|██████████| 1/1 [00:00<00:00, 20.69it/s]

epoch: 3062, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011627, Train KL:8.769042, Val MSE:0.010287, Val CE:0.043313, Train ACC:1.000000, Val ACC:0.993750

Epoch 3064/4000: 100%|██████████| 1/1 [00:00<00:00, 21.60it/s]

epoch: 3063, beta = 0.000097, Train MSE: 0.006592, Train CE:0.011627, Train KL:8.769043, Val MSE:0.010286, Val CE:0.043314, Train ACC:1.000000, Val ACC:0.993750

Epoch 3065/4000: 100%|██████████| 1/1 [00:00<00:00, 20.76it/s]

epoch: 3064, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011624, Train KL:8.769044, Val MSE:0.010280, Val CE:0.043511, Train ACC:1.000000, Val ACC:0.993750

Epoch 3066/4000: 100%|██████████| 1/1 [00:00<00:00, 22.77it/s]

epoch: 3065, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011630, Train KL:8.769045, Val MSE:0.010273, Val CE:0.043358, Train ACC:1.000000, Val ACC:0.993750

Epoch 3067/4000: 100%|██████████| 1/1 [00:00<00:00, 24.16it/s]

epoch: 3066, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011633, Train KL:8.769047, Val MSE:0.010293, Val CE:0.043719, Train ACC:1.000000, Val ACC:0.993750

Epoch 3068/4000: 100%|██████████| 1/1 [00:00<00:00, 23.56it/s]

epoch: 3067, beta = 0.000097, Train MSE: 0.006611, Train CE:0.011629, Train KL:8.769047, Val MSE:0.010290, Val CE:0.043408, Train ACC:1.000000, Val ACC:0.993750

Epoch 3069/4000: 100%|██████████| 1/1 [00:00<00:00, 22.05it/s]

epoch: 3068, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011636, Train KL:8.769049, Val MSE:0.010260, Val CE:0.043376, Train ACC:1.000000, Val ACC:0.993750

Epoch 3070/4000: 100%|██████████| 1/1 [00:00<00:00, 22.60it/s]

epoch: 3069, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011624, Train KL:8.769050, Val MSE:0.010274, Val CE:0.043636, Train ACC:1.000000, Val ACC:0.993750

Epoch 3071/4000: 100%|██████████| 1/1 [00:00<00:00, 24.04it/s]

epoch: 3070, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011631, Train KL:8.769051, Val MSE:0.010282, Val CE:0.043529, Train ACC:1.000000, Val ACC:0.993750

Epoch 3072/4000: 100%|██████████| 1/1 [00:00<00:00, 24.05it/s]

epoch: 3071, beta = 0.000097, Train MSE: 0.006611, Train CE:0.011630, Train KL:8.769053, Val MSE:0.010295, Val CE:0.043362, Train ACC:1.000000, Val ACC:0.993750

Epoch 3073/4000: 100%|██████████| 1/1 [00:00<00:00, 23.80it/s]

epoch: 3072, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011628, Train KL:8.769054, Val MSE:0.010283, Val CE:0.043340, Train ACC:1.000000, Val ACC:0.993750

Epoch 3074/4000: 100%|██████████| 1/1 [00:00<00:00, 21.52it/s]

epoch: 3073, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011630, Train KL:8.769055, Val MSE:0.010282, Val CE:0.043387, Train ACC:1.000000, Val ACC:0.993750

Epoch 3075/4000: 100%|██████████| 1/1 [00:00<00:00, 23.79it/s]

epoch: 3074, beta = 0.000097, Train MSE: 0.006595, Train CE:0.011632, Train KL:8.769055, Val MSE:0.010299, Val CE:0.043507, Train ACC:1.000000, Val ACC:0.993750

Epoch 3076/4000: 100%|██████████| 1/1 [00:00<00:00, 25.35it/s]

epoch: 3075, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011629, Train KL:8.769057, Val MSE:0.010255, Val CE:0.043310, Train ACC:1.000000, Val ACC:0.993750

Epoch 3077/4000: 100%|██████████| 1/1 [00:00<00:00, 24.30it/s]

epoch: 3076, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011632, Train KL:8.769058, Val MSE:0.010280, Val CE:0.043454, Train ACC:1.000000, Val ACC:0.993750

Epoch 3078/4000: 100%|██████████| 1/1 [00:00<00:00, 25.31it/s]

epoch: 3077, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011628, Train KL:8.769060, Val MSE:0.010262, Val CE:0.043415, Train ACC:1.000000, Val ACC:0.993750

Epoch 3079/4000: 100%|██████████| 1/1 [00:00<00:00, 18.53it/s]

epoch: 3078, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011631, Train KL:8.769062, Val MSE:0.010281, Val CE:0.043383, Train ACC:1.000000, Val ACC:0.993750

Epoch 3080/4000: 100%|██████████| 1/1 [00:00<00:00, 21.56it/s]

epoch: 3079, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011628, Train KL:8.769063, Val MSE:0.010269, Val CE:0.043357, Train ACC:1.000000, Val ACC:0.993750

Epoch 3081/4000: 100%|██████████| 1/1 [00:00<00:00, 23.65it/s]

epoch: 3080, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011629, Train KL:8.769064, Val MSE:0.010294, Val CE:0.043206, Train ACC:1.000000, Val ACC:0.993750

Epoch 3082/4000: 100%|██████████| 1/1 [00:00<00:00, 21.13it/s]

epoch: 3081, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011631, Train KL:8.769065, Val MSE:0.010284, Val CE:0.043654, Train ACC:1.000000, Val ACC:0.993750

Epoch 3083/4000: 100%|██████████| 1/1 [00:00<00:00, 24.08it/s]

epoch: 3082, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011623, Train KL:8.769066, Val MSE:0.010293, Val CE:0.043383, Train ACC:1.000000, Val ACC:0.993750

Epoch 3084/4000: 100%|██████████| 1/1 [00:00<00:00, 24.26it/s]

epoch: 3083, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011630, Train KL:8.769067, Val MSE:0.010259, Val CE:0.043367, Train ACC:1.000000, Val ACC:0.993750

Epoch 3085/4000: 100%|██████████| 1/1 [00:00<00:00, 23.80it/s]

epoch: 3084, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011632, Train KL:8.769068, Val MSE:0.010283, Val CE:0.043340, Train ACC:1.000000, Val ACC:0.993750

Epoch 3086/4000: 100%|██████████| 1/1 [00:00<00:00, 23.93it/s]

epoch: 3085, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011627, Train KL:8.769070, Val MSE:0.010268, Val CE:0.043631, Train ACC:1.000000, Val ACC:0.993750

Epoch 3087/4000: 100%|██████████| 1/1 [00:00<00:00, 24.07it/s]

epoch: 3086, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011631, Train KL:8.769071, Val MSE:0.010280, Val CE:0.043446, Train ACC:1.000000, Val ACC:0.993750

Epoch 3088/4000: 100%|██████████| 1/1 [00:00<00:00, 24.17it/s]

epoch: 3087, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011630, Train KL:8.769071, Val MSE:0.010279, Val CE:0.043527, Train ACC:1.000000, Val ACC:0.993750

Epoch 3089/4000: 100%|██████████| 1/1 [00:00<00:00, 24.13it/s]

epoch: 3088, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011632, Train KL:8.769073, Val MSE:0.010278, Val CE:0.043409, Train ACC:1.000000, Val ACC:0.993750

Epoch 3090/4000: 100%|██████████| 1/1 [00:00<00:00, 23.95it/s]

epoch: 3089, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011628, Train KL:8.769074, Val MSE:0.010260, Val CE:0.043417, Train ACC:1.000000, Val ACC:0.993750

Epoch 3091/4000: 100%|██████████| 1/1 [00:00<00:00, 23.47it/s]

epoch: 3090, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011625, Train KL:8.769075, Val MSE:0.010297, Val CE:0.043545, Train ACC:1.000000, Val ACC:0.993750

Epoch 3092/4000: 100%|██████████| 1/1 [00:00<00:00, 23.38it/s]

epoch: 3091, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011632, Train KL:8.769077, Val MSE:0.010281, Val CE:0.043380, Train ACC:1.000000, Val ACC:0.993750

Epoch 3093/4000: 100%|██████████| 1/1 [00:00<00:00, 24.05it/s]

epoch: 3092, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011631, Train KL:8.769078, Val MSE:0.010281, Val CE:0.043340, Train ACC:1.000000, Val ACC:0.993750

Epoch 3094/4000: 100%|██████████| 1/1 [00:00<00:00, 20.16it/s]

epoch: 3093, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011629, Train KL:8.769080, Val MSE:0.010295, Val CE:0.043522, Train ACC:1.000000, Val ACC:0.993229

Epoch 3095/4000: 100%|██████████| 1/1 [00:00<00:00, 21.67it/s]

epoch: 3094, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011629, Train KL:8.769081, Val MSE:0.010266, Val CE:0.043618, Train ACC:1.000000, Val ACC:0.993750

Epoch 3096/4000: 100%|██████████| 1/1 [00:00<00:00, 23.49it/s]

epoch: 3095, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011635, Train KL:8.769082, Val MSE:0.010305, Val CE:0.043546, Train ACC:1.000000, Val ACC:0.993750

Epoch 3097/4000: 100%|██████████| 1/1 [00:00<00:00, 21.89it/s]

epoch: 3096, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011628, Train KL:8.769083, Val MSE:0.010291, Val CE:0.043597, Train ACC:1.000000, Val ACC:0.993750

Epoch 3098/4000: 100%|██████████| 1/1 [00:00<00:00, 24.01it/s]

epoch: 3097, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011624, Train KL:8.769086, Val MSE:0.010281, Val CE:0.043567, Train ACC:1.000000, Val ACC:0.993750

Epoch 3099/4000: 100%|██████████| 1/1 [00:00<00:00, 23.89it/s]

epoch: 3098, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011624, Train KL:8.769086, Val MSE:0.010278, Val CE:0.043531, Train ACC:1.000000, Val ACC:0.993750

Epoch 3100/4000: 100%|██████████| 1/1 [00:00<00:00, 23.99it/s]

epoch: 3099, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011629, Train KL:8.769088, Val MSE:0.010297, Val CE:0.043206, Train ACC:1.000000, Val ACC:0.993750

Epoch 3101/4000: 100%|██████████| 1/1 [00:00<00:00, 20.83it/s]

epoch: 3100, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011627, Train KL:8.769090, Val MSE:0.010264, Val CE:0.043439, Train ACC:1.000000, Val ACC:0.993750

Epoch 3102/4000: 100%|██████████| 1/1 [00:00<00:00, 22.12it/s]

epoch: 3101, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011632, Train KL:8.769090, Val MSE:0.010273, Val CE:0.043274, Train ACC:1.000000, Val ACC:0.993750

Epoch 3103/4000: 100%|██████████| 1/1 [00:00<00:00, 23.90it/s]

epoch: 3102, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011629, Train KL:8.769091, Val MSE:0.010248, Val CE:0.043574, Train ACC:1.000000, Val ACC:0.993750

Epoch 3104/4000: 100%|██████████| 1/1 [00:00<00:00, 23.92it/s]

epoch: 3103, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011631, Train KL:8.769093, Val MSE:0.010294, Val CE:0.043450, Train ACC:1.000000, Val ACC:0.993750

Epoch 3105/4000: 100%|██████████| 1/1 [00:00<00:00, 23.62it/s]

epoch: 3104, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011627, Train KL:8.769094, Val MSE:0.010267, Val CE:0.043367, Train ACC:1.000000, Val ACC:0.993750

Epoch 3106/4000: 100%|██████████| 1/1 [00:00<00:00, 23.98it/s]

epoch: 3105, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011628, Train KL:8.769094, Val MSE:0.010285, Val CE:0.043467, Train ACC:1.000000, Val ACC:0.993750

Epoch 3107/4000: 100%|██████████| 1/1 [00:00<00:00, 20.63it/s]

epoch: 3106, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011628, Train KL:8.769095, Val MSE:0.010257, Val CE:0.043463, Train ACC:1.000000, Val ACC:0.993750

Epoch 3108/4000: 100%|██████████| 1/1 [00:00<00:00, 19.89it/s]

epoch: 3107, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011621, Train KL:8.769097, Val MSE:0.010291, Val CE:0.043474, Train ACC:1.000000, Val ACC:0.993750

Epoch 3109/4000: 100%|██████████| 1/1 [00:00<00:00, 21.95it/s]

epoch: 3108, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011628, Train KL:8.769098, Val MSE:0.010279, Val CE:0.043565, Train ACC:1.000000, Val ACC:0.993750

Epoch 3110/4000: 100%|██████████| 1/1 [00:00<00:00, 22.95it/s]

epoch: 3109, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011630, Train KL:8.769098, Val MSE:0.010274, Val CE:0.043550, Train ACC:1.000000, Val ACC:0.993750

Epoch 3111/4000: 100%|██████████| 1/1 [00:00<00:00, 22.99it/s]

epoch: 3110, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011630, Train KL:8.769100, Val MSE:0.010264, Val CE:0.043506, Train ACC:1.000000, Val ACC:0.993750

Epoch 3112/4000: 100%|██████████| 1/1 [00:00<00:00, 23.32it/s]

epoch: 3111, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011631, Train KL:8.769101, Val MSE:0.010309, Val CE:0.043501, Train ACC:1.000000, Val ACC:0.993750

Epoch 3113/4000: 100%|██████████| 1/1 [00:00<00:00, 23.58it/s]

epoch: 3112, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011629, Train KL:8.769101, Val MSE:0.010279, Val CE:0.043363, Train ACC:1.000000, Val ACC:0.993750

Epoch 3114/4000: 100%|██████████| 1/1 [00:00<00:00, 23.54it/s]

epoch: 3113, beta = 0.000097, Train MSE: 0.006593, Train CE:0.011633, Train KL:8.769103, Val MSE:0.010261, Val CE:0.043461, Train ACC:1.000000, Val ACC:0.993750

Epoch 3115/4000: 100%|██████████| 1/1 [00:00<00:00, 24.21it/s]

epoch: 3114, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011633, Train KL:8.769105, Val MSE:0.010277, Val CE:0.043268, Train ACC:1.000000, Val ACC:0.993750

Epoch 3116/4000: 100%|██████████| 1/1 [00:00<00:00, 23.97it/s]

epoch: 3115, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011627, Train KL:8.769106, Val MSE:0.010272, Val CE:0.043476, Train ACC:1.000000, Val ACC:0.993750

Epoch 3117/4000: 100%|██████████| 1/1 [00:00<00:00, 22.99it/s]

epoch: 3116, beta = 0.000097, Train MSE: 0.006615, Train CE:0.011630, Train KL:8.769108, Val MSE:0.010264, Val CE:0.043421, Train ACC:1.000000, Val ACC:0.993750

Epoch 3118/4000: 100%|██████████| 1/1 [00:00<00:00, 23.45it/s]

epoch: 3117, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011634, Train KL:8.769109, Val MSE:0.010311, Val CE:0.043421, Train ACC:1.000000, Val ACC:0.993750

Epoch 3119/4000: 100%|██████████| 1/1 [00:00<00:00, 23.19it/s]

epoch: 3118, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011632, Train KL:8.769110, Val MSE:0.010317, Val CE:0.043286, Train ACC:1.000000, Val ACC:0.993750

Epoch 3120/4000: 100%|██████████| 1/1 [00:00<00:00, 24.02it/s]

epoch: 3119, beta = 0.000097, Train MSE: 0.006595, Train CE:0.011629, Train KL:8.769112, Val MSE:0.010258, Val CE:0.043393, Train ACC:1.000000, Val ACC:0.993750

Epoch 3121/4000: 100%|██████████| 1/1 [00:00<00:00, 23.66it/s]

epoch: 3120, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011626, Train KL:8.769113, Val MSE:0.010265, Val CE:0.043449, Train ACC:1.000000, Val ACC:0.993750

Epoch 3122/4000: 100%|██████████| 1/1 [00:00<00:00, 23.95it/s]

epoch: 3121, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011626, Train KL:8.769114, Val MSE:0.010257, Val CE:0.043503, Train ACC:1.000000, Val ACC:0.993750

Epoch 3123/4000: 100%|██████████| 1/1 [00:00<00:00, 21.37it/s]

epoch: 3122, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011626, Train KL:8.769114, Val MSE:0.010281, Val CE:0.043345, Train ACC:1.000000, Val ACC:0.993750

Epoch 3124/4000: 100%|██████████| 1/1 [00:00<00:00, 22.86it/s]

epoch: 3123, beta = 0.000097, Train MSE: 0.006590, Train CE:0.011628, Train KL:8.769116, Val MSE:0.010252, Val CE:0.043217, Train ACC:1.000000, Val ACC:0.993750

Epoch 3125/4000: 100%|██████████| 1/1 [00:00<00:00, 16.86it/s]

epoch: 3124, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011630, Train KL:8.769117, Val MSE:0.010304, Val CE:0.043472, Train ACC:1.000000, Val ACC:0.993750

Epoch 3126/4000: 100%|██████████| 1/1 [00:00<00:00, 23.79it/s]

epoch: 3125, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011630, Train KL:8.769118, Val MSE:0.010284, Val CE:0.043517, Train ACC:1.000000, Val ACC:0.993750

Epoch 3127/4000: 100%|██████████| 1/1 [00:00<00:00, 21.44it/s]

epoch: 3126, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011631, Train KL:8.769120, Val MSE:0.010260, Val CE:0.043382, Train ACC:1.000000, Val ACC:0.993750

Epoch 3128/4000: 100%|██████████| 1/1 [00:00<00:00, 22.60it/s]

epoch: 3127, beta = 0.000097, Train MSE: 0.006613, Train CE:0.011625, Train KL:8.769121, Val MSE:0.010297, Val CE:0.043393, Train ACC:1.000000, Val ACC:0.993750

Epoch 3129/4000: 100%|██████████| 1/1 [00:00<00:00, 23.85it/s]

epoch: 3128, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011625, Train KL:8.769122, Val MSE:0.010285, Val CE:0.043411, Train ACC:1.000000, Val ACC:0.993750

Epoch 3130/4000: 100%|██████████| 1/1 [00:00<00:00, 23.84it/s]

epoch: 3129, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011627, Train KL:8.769124, Val MSE:0.010280, Val CE:0.043249, Train ACC:1.000000, Val ACC:0.993750

Epoch 3131/4000: 100%|██████████| 1/1 [00:00<00:00, 23.98it/s]

epoch: 3130, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011627, Train KL:8.769124, Val MSE:0.010266, Val CE:0.043337, Train ACC:1.000000, Val ACC:0.993750

Epoch 3132/4000: 100%|██████████| 1/1 [00:00<00:00, 23.87it/s]

epoch: 3131, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011634, Train KL:8.769126, Val MSE:0.010312, Val CE:0.043398, Train ACC:1.000000, Val ACC:0.993750

Epoch 3133/4000: 100%|██████████| 1/1 [00:00<00:00, 24.55it/s]

epoch: 3132, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011629, Train KL:8.769128, Val MSE:0.010266, Val CE:0.043443, Train ACC:1.000000, Val ACC:0.993750

Epoch 3134/4000: 100%|██████████| 1/1 [00:00<00:00, 23.49it/s]

epoch: 3133, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011631, Train KL:8.769128, Val MSE:0.010250, Val CE:0.043441, Train ACC:1.000000, Val ACC:0.993750

Epoch 3135/4000: 100%|██████████| 1/1 [00:00<00:00, 23.29it/s]

epoch: 3134, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011629, Train KL:8.769129, Val MSE:0.010287, Val CE:0.043250, Train ACC:1.000000, Val ACC:0.993750

Epoch 3136/4000: 100%|██████████| 1/1 [00:00<00:00, 24.28it/s]

epoch: 3135, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011626, Train KL:8.769131, Val MSE:0.010272, Val CE:0.043358, Train ACC:1.000000, Val ACC:0.993750

Epoch 3137/4000: 100%|██████████| 1/1 [00:00<00:00, 24.56it/s]

epoch: 3136, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011627, Train KL:8.769132, Val MSE:0.010283, Val CE:0.043264, Train ACC:1.000000, Val ACC:0.993750

Epoch 3138/4000: 100%|██████████| 1/1 [00:00<00:00, 23.21it/s]

epoch: 3137, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011633, Train KL:8.769132, Val MSE:0.010271, Val CE:0.043435, Train ACC:1.000000, Val ACC:0.993750

Epoch 3139/4000: 100%|██████████| 1/1 [00:00<00:00, 18.87it/s]

epoch: 3138, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011630, Train KL:8.769134, Val MSE:0.010273, Val CE:0.043462, Train ACC:1.000000, Val ACC:0.993750

Epoch 3140/4000: 100%|██████████| 1/1 [00:00<00:00, 22.98it/s]

epoch: 3139, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011629, Train KL:8.769135, Val MSE:0.010282, Val CE:0.043468, Train ACC:1.000000, Val ACC:0.993750

Epoch 3141/4000: 100%|██████████| 1/1 [00:00<00:00, 21.19it/s]

epoch: 3140, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011632, Train KL:8.769136, Val MSE:0.010273, Val CE:0.043463, Train ACC:1.000000, Val ACC:0.993750

Epoch 3142/4000: 100%|██████████| 1/1 [00:00<00:00, 24.02it/s]

epoch: 3141, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011631, Train KL:8.769138, Val MSE:0.010260, Val CE:0.043330, Train ACC:1.000000, Val ACC:0.993750

Epoch 3143/4000: 100%|██████████| 1/1 [00:00<00:00, 27.35it/s]

epoch: 3142, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011627, Train KL:8.769139, Val MSE:0.010281, Val CE:0.043588, Train ACC:1.000000, Val ACC:0.993750

Epoch 3144/4000: 100%|██████████| 1/1 [00:00<00:00, 23.49it/s]

epoch: 3143, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011632, Train KL:8.769141, Val MSE:0.010268, Val CE:0.043361, Train ACC:1.000000, Val ACC:0.993750

Epoch 3145/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 3144, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011628, Train KL:8.769143, Val MSE:0.010283, Val CE:0.043378, Train ACC:1.000000, Val ACC:0.993750

Epoch 3146/4000: 100%|██████████| 1/1 [00:00<00:00, 22.72it/s]

epoch: 3145, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011629, Train KL:8.769144, Val MSE:0.010279, Val CE:0.043658, Train ACC:1.000000, Val ACC:0.993750

Epoch 3147/4000: 100%|██████████| 1/1 [00:00<00:00, 24.84it/s]

epoch: 3146, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011628, Train KL:8.769146, Val MSE:0.010261, Val CE:0.043441, Train ACC:1.000000, Val ACC:0.993750

Epoch 3148/4000: 100%|██████████| 1/1 [00:00<00:00, 23.07it/s]

epoch: 3147, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011630, Train KL:8.769147, Val MSE:0.010293, Val CE:0.043566, Train ACC:1.000000, Val ACC:0.993750

Epoch 3149/4000: 100%|██████████| 1/1 [00:00<00:00, 23.59it/s]

epoch: 3148, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011620, Train KL:8.769149, Val MSE:0.010295, Val CE:0.043491, Train ACC:1.000000, Val ACC:0.993750

Epoch 3150/4000: 100%|██████████| 1/1 [00:00<00:00, 23.63it/s]

epoch: 3149, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011630, Train KL:8.769151, Val MSE:0.010266, Val CE:0.043353, Train ACC:1.000000, Val ACC:0.993750

Epoch 3151/4000: 100%|██████████| 1/1 [00:00<00:00, 23.12it/s]

epoch: 3150, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011625, Train KL:8.769152, Val MSE:0.010266, Val CE:0.043258, Train ACC:1.000000, Val ACC:0.993750

Epoch 3152/4000: 100%|██████████| 1/1 [00:00<00:00, 25.52it/s]

epoch: 3151, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011628, Train KL:8.769154, Val MSE:0.010254, Val CE:0.043812, Train ACC:1.000000, Val ACC:0.993750

Epoch 3153/4000: 100%|██████████| 1/1 [00:00<00:00, 23.28it/s]

epoch: 3152, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011633, Train KL:8.769155, Val MSE:0.010296, Val CE:0.043371, Train ACC:1.000000, Val ACC:0.993750

Epoch 3154/4000: 100%|██████████| 1/1 [00:00<00:00, 24.11it/s]

epoch: 3153, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011630, Train KL:8.769156, Val MSE:0.010277, Val CE:0.043309, Train ACC:1.000000, Val ACC:0.993750

Epoch 3155/4000: 100%|██████████| 1/1 [00:00<00:00, 22.24it/s]

epoch: 3154, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011633, Train KL:8.769158, Val MSE:0.010286, Val CE:0.043541, Train ACC:1.000000, Val ACC:0.993750

Epoch 3156/4000: 100%|██████████| 1/1 [00:00<00:00, 21.49it/s]

epoch: 3155, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011629, Train KL:8.769159, Val MSE:0.010286, Val CE:0.043485, Train ACC:1.000000, Val ACC:0.993750

Epoch 3157/4000: 100%|██████████| 1/1 [00:00<00:00, 15.68it/s]

epoch: 3156, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011629, Train KL:8.769160, Val MSE:0.010263, Val CE:0.043412, Train ACC:1.000000, Val ACC:0.993750

Epoch 3158/4000: 100%|██████████| 1/1 [00:00<00:00, 22.59it/s]

epoch: 3157, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011628, Train KL:8.769162, Val MSE:0.010269, Val CE:0.043406, Train ACC:1.000000, Val ACC:0.993750

Epoch 3159/4000: 100%|██████████| 1/1 [00:00<00:00, 23.94it/s]

epoch: 3158, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011626, Train KL:8.769163, Val MSE:0.010294, Val CE:0.043280, Train ACC:1.000000, Val ACC:0.993750

Epoch 3160/4000: 100%|██████████| 1/1 [00:00<00:00, 23.89it/s]

epoch: 3159, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011626, Train KL:8.769165, Val MSE:0.010267, Val CE:0.043518, Train ACC:1.000000, Val ACC:0.993750

Epoch 3161/4000: 100%|██████████| 1/1 [00:00<00:00, 23.87it/s]

epoch: 3160, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011627, Train KL:8.769166, Val MSE:0.010297, Val CE:0.043465, Train ACC:1.000000, Val ACC:0.993750

Epoch 3162/4000: 100%|██████████| 1/1 [00:00<00:00, 25.98it/s]

epoch: 3161, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011631, Train KL:8.769167, Val MSE:0.010267, Val CE:0.043465, Train ACC:1.000000, Val ACC:0.993750

Epoch 3163/4000: 100%|██████████| 1/1 [00:00<00:00, 24.25it/s]

epoch: 3162, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011635, Train KL:8.769169, Val MSE:0.010267, Val CE:0.043482, Train ACC:1.000000, Val ACC:0.993750

Epoch 3164/4000: 100%|██████████| 1/1 [00:00<00:00, 24.18it/s]

epoch: 3163, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011625, Train KL:8.769170, Val MSE:0.010241, Val CE:0.043592, Train ACC:1.000000, Val ACC:0.993750

Epoch 3165/4000: 100%|██████████| 1/1 [00:00<00:00, 24.06it/s]

epoch: 3164, beta = 0.000097, Train MSE: 0.006595, Train CE:0.011624, Train KL:8.769172, Val MSE:0.010297, Val CE:0.043587, Train ACC:1.000000, Val ACC:0.993750

Epoch 3166/4000: 100%|██████████| 1/1 [00:00<00:00, 24.04it/s]

epoch: 3165, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011629, Train KL:8.769174, Val MSE:0.010279, Val CE:0.043578, Train ACC:1.000000, Val ACC:0.993750

Epoch 3167/4000: 100%|██████████| 1/1 [00:00<00:00, 24.49it/s]

epoch: 3166, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011626, Train KL:8.769175, Val MSE:0.010304, Val CE:0.043386, Train ACC:1.000000, Val ACC:0.993750

Epoch 3168/4000: 100%|██████████| 1/1 [00:00<00:00, 24.72it/s]

epoch: 3167, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011625, Train KL:8.769175, Val MSE:0.010269, Val CE:0.043550, Train ACC:1.000000, Val ACC:0.993750

Epoch 3169/4000: 100%|██████████| 1/1 [00:00<00:00, 23.43it/s]

epoch: 3168, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011627, Train KL:8.769177, Val MSE:0.010299, Val CE:0.043395, Train ACC:1.000000, Val ACC:0.993750

Epoch 3170/4000: 100%|██████████| 1/1 [00:00<00:00, 22.78it/s]

epoch: 3169, beta = 0.000097, Train MSE: 0.006617, Train CE:0.011630, Train KL:8.769177, Val MSE:0.010263, Val CE:0.043592, Train ACC:1.000000, Val ACC:0.993750

Epoch 3171/4000: 100%|██████████| 1/1 [00:00<00:00, 23.35it/s]

epoch: 3170, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011633, Train KL:8.769179, Val MSE:0.010283, Val CE:0.043546, Train ACC:1.000000, Val ACC:0.993229

Epoch 3172/4000: 100%|██████████| 1/1 [00:00<00:00, 23.88it/s]

epoch: 3171, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011628, Train KL:8.769181, Val MSE:0.010296, Val CE:0.043690, Train ACC:1.000000, Val ACC:0.993750

Epoch 3173/4000: 100%|██████████| 1/1 [00:00<00:00, 23.49it/s]

epoch: 3172, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011632, Train KL:8.769182, Val MSE:0.010240, Val CE:0.043475, Train ACC:1.000000, Val ACC:0.993750

Epoch 3174/4000: 100%|██████████| 1/1 [00:00<00:00, 21.67it/s]

epoch: 3173, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011625, Train KL:8.769183, Val MSE:0.010284, Val CE:0.043639, Train ACC:1.000000, Val ACC:0.993750

Epoch 3175/4000: 100%|██████████| 1/1 [00:00<00:00, 23.40it/s]

epoch: 3174, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011629, Train KL:8.769185, Val MSE:0.010293, Val CE:0.043330, Train ACC:1.000000, Val ACC:0.993750

Epoch 3176/4000: 100%|██████████| 1/1 [00:00<00:00, 22.43it/s]

epoch: 3175, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011626, Train KL:8.769185, Val MSE:0.010313, Val CE:0.043652, Train ACC:1.000000, Val ACC:0.993750

Epoch 3177/4000: 100%|██████████| 1/1 [00:00<00:00, 21.96it/s]

epoch: 3176, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011626, Train KL:8.769187, Val MSE:0.010288, Val CE:0.043489, Train ACC:1.000000, Val ACC:0.993750

Epoch 3178/4000: 100%|██████████| 1/1 [00:00<00:00, 22.68it/s]

epoch: 3177, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011624, Train KL:8.769189, Val MSE:0.010276, Val CE:0.043418, Train ACC:1.000000, Val ACC:0.993750

Epoch 3179/4000: 100%|██████████| 1/1 [00:00<00:00, 23.18it/s]

epoch: 3178, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011623, Train KL:8.769190, Val MSE:0.010264, Val CE:0.043674, Train ACC:1.000000, Val ACC:0.993750

Epoch 3180/4000: 100%|██████████| 1/1 [00:00<00:00, 22.84it/s]

epoch: 3179, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011625, Train KL:8.769191, Val MSE:0.010303, Val CE:0.043491, Train ACC:1.000000, Val ACC:0.993750

Epoch 3181/4000: 100%|██████████| 1/1 [00:00<00:00, 22.80it/s]

epoch: 3180, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011632, Train KL:8.769193, Val MSE:0.010315, Val CE:0.043387, Train ACC:1.000000, Val ACC:0.993750

Epoch 3182/4000: 100%|██████████| 1/1 [00:00<00:00, 23.79it/s]

epoch: 3181, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011627, Train KL:8.769195, Val MSE:0.010294, Val CE:0.043386, Train ACC:1.000000, Val ACC:0.993750

Epoch 3183/4000: 100%|██████████| 1/1 [00:00<00:00, 22.83it/s]

epoch: 3182, beta = 0.000097, Train MSE: 0.006623, Train CE:0.011629, Train KL:8.769195, Val MSE:0.010286, Val CE:0.043410, Train ACC:1.000000, Val ACC:0.993750

Epoch 3184/4000: 100%|██████████| 1/1 [00:00<00:00, 22.54it/s]

epoch: 3183, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011623, Train KL:8.769197, Val MSE:0.010289, Val CE:0.043377, Train ACC:1.000000, Val ACC:0.993750

Epoch 3185/4000: 100%|██████████| 1/1 [00:00<00:00, 22.41it/s]

epoch: 3184, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011631, Train KL:8.769198, Val MSE:0.010286, Val CE:0.043289, Train ACC:1.000000, Val ACC:0.993750

Epoch 3186/4000: 100%|██████████| 1/1 [00:00<00:00, 21.80it/s]

epoch: 3185, beta = 0.000097, Train MSE: 0.006593, Train CE:0.011625, Train KL:8.769201, Val MSE:0.010256, Val CE:0.043527, Train ACC:1.000000, Val ACC:0.993750

Epoch 3187/4000: 100%|██████████| 1/1 [00:00<00:00, 22.36it/s]

epoch: 3186, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011633, Train KL:8.769202, Val MSE:0.010282, Val CE:0.043442, Train ACC:1.000000, Val ACC:0.993750

Epoch 3188/4000: 100%|██████████| 1/1 [00:00<00:00, 24.11it/s]

epoch: 3187, beta = 0.000097, Train MSE: 0.006595, Train CE:0.011626, Train KL:8.769204, Val MSE:0.010277, Val CE:0.043490, Train ACC:1.000000, Val ACC:0.993750

Epoch 3189/4000: 100%|██████████| 1/1 [00:00<00:00, 23.44it/s]

epoch: 3188, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011629, Train KL:8.769205, Val MSE:0.010290, Val CE:0.043444, Train ACC:1.000000, Val ACC:0.993750

Epoch 3190/4000: 100%|██████████| 1/1 [00:00<00:00, 24.08it/s]

epoch: 3189, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011627, Train KL:8.769206, Val MSE:0.010284, Val CE:0.043429, Train ACC:1.000000, Val ACC:0.993750

Epoch 3191/4000: 100%|██████████| 1/1 [00:00<00:00, 22.39it/s]

epoch: 3190, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011630, Train KL:8.769207, Val MSE:0.010266, Val CE:0.043458, Train ACC:1.000000, Val ACC:0.993750

Epoch 3192/4000: 100%|██████████| 1/1 [00:00<00:00, 22.90it/s]

epoch: 3191, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011628, Train KL:8.769209, Val MSE:0.010286, Val CE:0.043642, Train ACC:1.000000, Val ACC:0.993750

Epoch 3193/4000: 100%|██████████| 1/1 [00:00<00:00, 20.55it/s]

epoch: 3192, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011634, Train KL:8.769210, Val MSE:0.010274, Val CE:0.043649, Train ACC:1.000000, Val ACC:0.993750

Epoch 3194/4000: 100%|██████████| 1/1 [00:00<00:00, 22.90it/s]

epoch: 3193, beta = 0.000097, Train MSE: 0.006595, Train CE:0.011627, Train KL:8.769212, Val MSE:0.010299, Val CE:0.043390, Train ACC:1.000000, Val ACC:0.993750

Epoch 3195/4000: 100%|██████████| 1/1 [00:00<00:00, 20.06it/s]

epoch: 3194, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011626, Train KL:8.769213, Val MSE:0.010295, Val CE:0.043447, Train ACC:1.000000, Val ACC:0.993750

Epoch 3196/4000: 100%|██████████| 1/1 [00:00<00:00, 23.54it/s]

epoch: 3195, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011627, Train KL:8.769215, Val MSE:0.010272, Val CE:0.043248, Train ACC:1.000000, Val ACC:0.993750

Epoch 3197/4000: 100%|██████████| 1/1 [00:00<00:00, 24.12it/s]

epoch: 3196, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011630, Train KL:8.769216, Val MSE:0.010270, Val CE:0.043253, Train ACC:1.000000, Val ACC:0.993750

Epoch 3198/4000: 100%|██████████| 1/1 [00:00<00:00, 23.85it/s]

epoch: 3197, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011627, Train KL:8.769217, Val MSE:0.010269, Val CE:0.043360, Train ACC:1.000000, Val ACC:0.993750

Epoch 3199/4000: 100%|██████████| 1/1 [00:00<00:00, 23.15it/s]

epoch: 3198, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011628, Train KL:8.769218, Val MSE:0.010279, Val CE:0.043360, Train ACC:1.000000, Val ACC:0.993750

Epoch 3200/4000: 100%|██████████| 1/1 [00:00<00:00, 25.08it/s]

epoch: 3199, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011632, Train KL:8.769219, Val MSE:0.010252, Val CE:0.043464, Train ACC:1.000000, Val ACC:0.993750

Epoch 3201/4000: 100%|██████████| 1/1 [00:00<00:00, 24.05it/s]

epoch: 3200, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011628, Train KL:8.769220, Val MSE:0.010280, Val CE:0.043454, Train ACC:1.000000, Val ACC:0.993750

Epoch 3202/4000: 100%|██████████| 1/1 [00:00<00:00, 27.57it/s]

epoch: 3201, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011632, Train KL:8.769222, Val MSE:0.010277, Val CE:0.043472, Train ACC:1.000000, Val ACC:0.993750

Epoch 3203/4000: 100%|██████████| 1/1 [00:00<00:00, 23.67it/s]

epoch: 3202, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011621, Train KL:8.769223, Val MSE:0.010271, Val CE:0.043655, Train ACC:1.000000, Val ACC:0.993750

Epoch 3204/4000: 100%|██████████| 1/1 [00:00<00:00, 22.79it/s]

epoch: 3203, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011632, Train KL:8.769224, Val MSE:0.010246, Val CE:0.043572, Train ACC:1.000000, Val ACC:0.993750

Epoch 3205/4000: 100%|██████████| 1/1 [00:00<00:00, 19.35it/s]

epoch: 3204, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011628, Train KL:8.769225, Val MSE:0.010284, Val CE:0.043469, Train ACC:1.000000, Val ACC:0.993750

Epoch 3206/4000: 100%|██████████| 1/1 [00:00<00:00, 21.59it/s]

epoch: 3205, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011627, Train KL:8.769228, Val MSE:0.010283, Val CE:0.043664, Train ACC:1.000000, Val ACC:0.993750

Epoch 3207/4000: 100%|██████████| 1/1 [00:00<00:00, 23.57it/s]

epoch: 3206, beta = 0.000097, Train MSE: 0.006590, Train CE:0.011626, Train KL:8.769228, Val MSE:0.010237, Val CE:0.043357, Train ACC:1.000000, Val ACC:0.993750

Epoch 3208/4000: 100%|██████████| 1/1 [00:00<00:00, 21.56it/s]

epoch: 3207, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011632, Train KL:8.769230, Val MSE:0.010263, Val CE:0.043413, Train ACC:1.000000, Val ACC:0.993750

Epoch 3209/4000: 100%|██████████| 1/1 [00:00<00:00, 23.99it/s]

epoch: 3208, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011629, Train KL:8.769232, Val MSE:0.010298, Val CE:0.043461, Train ACC:1.000000, Val ACC:0.993750

Epoch 3210/4000: 100%|██████████| 1/1 [00:00<00:00, 23.90it/s]

epoch: 3209, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011630, Train KL:8.769234, Val MSE:0.010254, Val CE:0.043395, Train ACC:1.000000, Val ACC:0.993750

Epoch 3211/4000: 100%|██████████| 1/1 [00:00<00:00, 25.52it/s]

epoch: 3210, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011625, Train KL:8.769235, Val MSE:0.010273, Val CE:0.043440, Train ACC:1.000000, Val ACC:0.993750

Epoch 3212/4000: 100%|██████████| 1/1 [00:00<00:00, 23.56it/s]

epoch: 3211, beta = 0.000097, Train MSE: 0.006611, Train CE:0.011622, Train KL:8.769237, Val MSE:0.010291, Val CE:0.043385, Train ACC:1.000000, Val ACC:0.993750

Epoch 3213/4000: 100%|██████████| 1/1 [00:00<00:00, 23.93it/s]

epoch: 3212, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011629, Train KL:8.769238, Val MSE:0.010277, Val CE:0.043659, Train ACC:1.000000, Val ACC:0.993750

Epoch 3214/4000: 100%|██████████| 1/1 [00:00<00:00, 24.06it/s]

epoch: 3213, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011626, Train KL:8.769239, Val MSE:0.010276, Val CE:0.043623, Train ACC:1.000000, Val ACC:0.993750

Epoch 3215/4000: 100%|██████████| 1/1 [00:00<00:00, 22.71it/s]

epoch: 3214, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011620, Train KL:8.769242, Val MSE:0.010259, Val CE:0.043694, Train ACC:1.000000, Val ACC:0.993750

Epoch 3216/4000: 100%|██████████| 1/1 [00:00<00:00, 23.04it/s]

epoch: 3215, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011639, Train KL:8.769243, Val MSE:0.010285, Val CE:0.043477, Train ACC:1.000000, Val ACC:0.993229

Epoch 3217/4000: 100%|██████████| 1/1 [00:00<00:00, 23.90it/s]

epoch: 3216, beta = 0.000097, Train MSE: 0.006595, Train CE:0.011626, Train KL:8.769245, Val MSE:0.010272, Val CE:0.043749, Train ACC:1.000000, Val ACC:0.993750

Epoch 3218/4000: 100%|██████████| 1/1 [00:00<00:00, 23.65it/s]

epoch: 3217, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011632, Train KL:8.769247, Val MSE:0.010284, Val CE:0.043577, Train ACC:1.000000, Val ACC:0.993750

Epoch 3219/4000: 100%|██████████| 1/1 [00:00<00:00, 21.85it/s]

epoch: 3218, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011628, Train KL:8.769249, Val MSE:0.010289, Val CE:0.043448, Train ACC:1.000000, Val ACC:0.993750

Epoch 3220/4000: 100%|██████████| 1/1 [00:00<00:00, 23.51it/s]

epoch: 3219, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011628, Train KL:8.769250, Val MSE:0.010287, Val CE:0.043427, Train ACC:1.000000, Val ACC:0.993750

Epoch 3221/4000: 100%|██████████| 1/1 [00:00<00:00, 20.40it/s]

epoch: 3220, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011631, Train KL:8.769251, Val MSE:0.010254, Val CE:0.043587, Train ACC:1.000000, Val ACC:0.993750

Epoch 3222/4000: 100%|██████████| 1/1 [00:00<00:00, 17.80it/s]

epoch: 3221, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011621, Train KL:8.769253, Val MSE:0.010289, Val CE:0.043447, Train ACC:1.000000, Val ACC:0.993750

Epoch 3223/4000: 100%|██████████| 1/1 [00:00<00:00, 21.72it/s]

epoch: 3222, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011626, Train KL:8.769255, Val MSE:0.010273, Val CE:0.043377, Train ACC:1.000000, Val ACC:0.993750

Epoch 3224/4000: 100%|██████████| 1/1 [00:00<00:00, 23.29it/s]

epoch: 3223, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011630, Train KL:8.769256, Val MSE:0.010302, Val CE:0.043300, Train ACC:1.000000, Val ACC:0.993750

Epoch 3225/4000: 100%|██████████| 1/1 [00:00<00:00, 23.03it/s]

epoch: 3224, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011625, Train KL:8.769258, Val MSE:0.010262, Val CE:0.043387, Train ACC:1.000000, Val ACC:0.993750

Epoch 3226/4000: 100%|██████████| 1/1 [00:00<00:00, 23.91it/s]

epoch: 3225, beta = 0.000097, Train MSE: 0.006614, Train CE:0.011624, Train KL:8.769258, Val MSE:0.010289, Val CE:0.043410, Train ACC:1.000000, Val ACC:0.993750

Epoch 3227/4000: 100%|██████████| 1/1 [00:00<00:00, 23.87it/s]

epoch: 3226, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011627, Train KL:8.769260, Val MSE:0.010306, Val CE:0.043341, Train ACC:1.000000, Val ACC:0.993750

Epoch 3228/4000: 100%|██████████| 1/1 [00:00<00:00, 23.40it/s]

epoch: 3227, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011628, Train KL:8.769262, Val MSE:0.010292, Val CE:0.043297, Train ACC:1.000000, Val ACC:0.993750

Epoch 3229/4000: 100%|██████████| 1/1 [00:00<00:00, 23.20it/s]

epoch: 3228, beta = 0.000097, Train MSE: 0.006614, Train CE:0.011623, Train KL:8.769263, Val MSE:0.010293, Val CE:0.043425, Train ACC:1.000000, Val ACC:0.993750

Epoch 3230/4000: 100%|██████████| 1/1 [00:00<00:00, 21.13it/s]

epoch: 3229, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011629, Train KL:8.769265, Val MSE:0.010256, Val CE:0.043484, Train ACC:1.000000, Val ACC:0.993750

Epoch 3231/4000: 100%|██████████| 1/1 [00:00<00:00, 23.53it/s]

epoch: 3230, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011625, Train KL:8.769266, Val MSE:0.010279, Val CE:0.043730, Train ACC:1.000000, Val ACC:0.993750

Epoch 3232/4000: 100%|██████████| 1/1 [00:00<00:00, 24.67it/s]

epoch: 3231, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011626, Train KL:8.769268, Val MSE:0.010273, Val CE:0.043447, Train ACC:1.000000, Val ACC:0.993750

Epoch 3233/4000: 100%|██████████| 1/1 [00:00<00:00, 24.16it/s]

epoch: 3232, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011628, Train KL:8.769270, Val MSE:0.010281, Val CE:0.043434, Train ACC:1.000000, Val ACC:0.993750

Epoch 3234/4000: 100%|██████████| 1/1 [00:00<00:00, 20.05it/s]

epoch: 3233, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011631, Train KL:8.769271, Val MSE:0.010270, Val CE:0.043335, Train ACC:1.000000, Val ACC:0.993750

Epoch 3235/4000: 100%|██████████| 1/1 [00:00<00:00, 21.24it/s]

epoch: 3234, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011622, Train KL:8.769273, Val MSE:0.010265, Val CE:0.043590, Train ACC:1.000000, Val ACC:0.993750

Epoch 3236/4000: 100%|██████████| 1/1 [00:00<00:00, 21.51it/s]

epoch: 3235, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011625, Train KL:8.769274, Val MSE:0.010258, Val CE:0.043508, Train ACC:1.000000, Val ACC:0.993750

Epoch 3237/4000: 100%|██████████| 1/1 [00:00<00:00, 25.61it/s]

epoch: 3236, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011625, Train KL:8.769276, Val MSE:0.010272, Val CE:0.043291, Train ACC:1.000000, Val ACC:0.993750

Epoch 3238/4000: 100%|██████████| 1/1 [00:00<00:00, 23.87it/s]

epoch: 3237, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011630, Train KL:8.769278, Val MSE:0.010283, Val CE:0.043457, Train ACC:1.000000, Val ACC:0.993750

Epoch 3239/4000: 100%|██████████| 1/1 [00:00<00:00, 22.09it/s]

epoch: 3238, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011632, Train KL:8.769279, Val MSE:0.010280, Val CE:0.043468, Train ACC:1.000000, Val ACC:0.993750

Epoch 3240/4000: 100%|██████████| 1/1 [00:00<00:00, 25.49it/s]

epoch: 3239, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011632, Train KL:8.769280, Val MSE:0.010263, Val CE:0.043256, Train ACC:1.000000, Val ACC:0.993750

Epoch 3241/4000: 100%|██████████| 1/1 [00:00<00:00, 24.65it/s]

epoch: 3240, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011623, Train KL:8.769281, Val MSE:0.010296, Val CE:0.043502, Train ACC:1.000000, Val ACC:0.993750

Epoch 3242/4000: 100%|██████████| 1/1 [00:00<00:00, 23.99it/s]

epoch: 3241, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011632, Train KL:8.769283, Val MSE:0.010274, Val CE:0.043562, Train ACC:1.000000, Val ACC:0.993750

Epoch 3243/4000: 100%|██████████| 1/1 [00:00<00:00, 23.00it/s]

epoch: 3242, beta = 0.000097, Train MSE: 0.006589, Train CE:0.011625, Train KL:8.769285, Val MSE:0.010297, Val CE:0.043285, Train ACC:1.000000, Val ACC:0.993750

Epoch 3244/4000: 100%|██████████| 1/1 [00:00<00:00, 23.43it/s]

epoch: 3243, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011627, Train KL:8.769286, Val MSE:0.010302, Val CE:0.043459, Train ACC:1.000000, Val ACC:0.993750

Epoch 3245/4000: 100%|██████████| 1/1 [00:00<00:00, 23.71it/s]

epoch: 3244, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011627, Train KL:8.769288, Val MSE:0.010299, Val CE:0.043274, Train ACC:1.000000, Val ACC:0.993750

Epoch 3246/4000: 100%|██████████| 1/1 [00:00<00:00, 23.79it/s]

epoch: 3245, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011627, Train KL:8.769289, Val MSE:0.010279, Val CE:0.043455, Train ACC:1.000000, Val ACC:0.993750

Epoch 3247/4000: 100%|██████████| 1/1 [00:00<00:00, 22.48it/s]

epoch: 3246, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011625, Train KL:8.769291, Val MSE:0.010271, Val CE:0.043349, Train ACC:1.000000, Val ACC:0.993750

Epoch 3248/4000: 100%|██████████| 1/1 [00:00<00:00, 23.55it/s]

epoch: 3247, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011625, Train KL:8.769293, Val MSE:0.010282, Val CE:0.043425, Train ACC:1.000000, Val ACC:0.993750

Epoch 3249/4000: 100%|██████████| 1/1 [00:00<00:00, 20.81it/s]

epoch: 3248, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011626, Train KL:8.769294, Val MSE:0.010289, Val CE:0.043554, Train ACC:1.000000, Val ACC:0.993750

Epoch 3250/4000: 100%|██████████| 1/1 [00:00<00:00, 22.60it/s]

epoch: 3249, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011627, Train KL:8.769296, Val MSE:0.010274, Val CE:0.043504, Train ACC:1.000000, Val ACC:0.993750

Epoch 3251/4000: 100%|██████████| 1/1 [00:00<00:00, 22.40it/s]

epoch: 3250, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011626, Train KL:8.769298, Val MSE:0.010293, Val CE:0.043315, Train ACC:1.000000, Val ACC:0.993750

Epoch 3252/4000: 100%|██████████| 1/1 [00:00<00:00, 23.03it/s]

epoch: 3251, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011624, Train KL:8.769299, Val MSE:0.010291, Val CE:0.043445, Train ACC:1.000000, Val ACC:0.993750

Epoch 3253/4000: 100%|██████████| 1/1 [00:00<00:00, 23.82it/s]

epoch: 3252, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011629, Train KL:8.769300, Val MSE:0.010305, Val CE:0.043574, Train ACC:1.000000, Val ACC:0.993750

Epoch 3254/4000: 100%|██████████| 1/1 [00:00<00:00, 24.43it/s]

epoch: 3253, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011629, Train KL:8.769301, Val MSE:0.010272, Val CE:0.043337, Train ACC:1.000000, Val ACC:0.993750

Epoch 3255/4000: 100%|██████████| 1/1 [00:00<00:00, 23.70it/s]

epoch: 3254, beta = 0.000097, Train MSE: 0.006595, Train CE:0.011628, Train KL:8.769303, Val MSE:0.010294, Val CE:0.043504, Train ACC:1.000000, Val ACC:0.993750

Epoch 3256/4000: 100%|██████████| 1/1 [00:00<00:00, 22.91it/s]

epoch: 3255, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011631, Train KL:8.769305, Val MSE:0.010302, Val CE:0.043440, Train ACC:1.000000, Val ACC:0.993750

Epoch 3257/4000: 100%|██████████| 1/1 [00:00<00:00, 23.80it/s]

epoch: 3256, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011624, Train KL:8.769306, Val MSE:0.010291, Val CE:0.043456, Train ACC:1.000000, Val ACC:0.993750

Epoch 3258/4000: 100%|██████████| 1/1 [00:00<00:00, 23.76it/s]

epoch: 3257, beta = 0.000097, Train MSE: 0.006614, Train CE:0.011629, Train KL:8.769308, Val MSE:0.010274, Val CE:0.043506, Train ACC:1.000000, Val ACC:0.993750

Epoch 3259/4000: 100%|██████████| 1/1 [00:00<00:00, 21.46it/s]

epoch: 3258, beta = 0.000097, Train MSE: 0.006594, Train CE:0.011633, Train KL:8.769310, Val MSE:0.010252, Val CE:0.043574, Train ACC:1.000000, Val ACC:0.993750

Epoch 3260/4000: 100%|██████████| 1/1 [00:00<00:00, 23.87it/s]

epoch: 3259, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011622, Train KL:8.769311, Val MSE:0.010291, Val CE:0.043446, Train ACC:1.000000, Val ACC:0.993750

Epoch 3261/4000: 100%|██████████| 1/1 [00:00<00:00, 22.33it/s]

epoch: 3260, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011627, Train KL:8.769313, Val MSE:0.010301, Val CE:0.043228, Train ACC:1.000000, Val ACC:0.993750

Epoch 3262/4000: 100%|██████████| 1/1 [00:00<00:00, 24.46it/s]

epoch: 3261, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011624, Train KL:8.769316, Val MSE:0.010293, Val CE:0.043548, Train ACC:1.000000, Val ACC:0.993750

Epoch 3263/4000: 100%|██████████| 1/1 [00:00<00:00, 24.17it/s]

epoch: 3262, beta = 0.000097, Train MSE: 0.006594, Train CE:0.011623, Train KL:8.769317, Val MSE:0.010246, Val CE:0.043398, Train ACC:1.000000, Val ACC:0.993750

Epoch 3264/4000: 100%|██████████| 1/1 [00:00<00:00, 23.32it/s]

epoch: 3263, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011626, Train KL:8.769317, Val MSE:0.010283, Val CE:0.043478, Train ACC:1.000000, Val ACC:0.993750

Epoch 3265/4000: 100%|██████████| 1/1 [00:00<00:00, 21.34it/s]

epoch: 3264, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011628, Train KL:8.769319, Val MSE:0.010308, Val CE:0.043477, Train ACC:1.000000, Val ACC:0.993750

Epoch 3266/4000: 100%|██████████| 1/1 [00:00<00:00, 22.86it/s]

epoch: 3265, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011627, Train KL:8.769320, Val MSE:0.010259, Val CE:0.043344, Train ACC:1.000000, Val ACC:0.993750

Epoch 3267/4000: 100%|██████████| 1/1 [00:00<00:00, 22.64it/s]

epoch: 3266, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011628, Train KL:8.769322, Val MSE:0.010290, Val CE:0.043533, Train ACC:1.000000, Val ACC:0.993750

Epoch 3268/4000: 100%|██████████| 1/1 [00:00<00:00, 19.59it/s]

epoch: 3267, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011626, Train KL:8.769323, Val MSE:0.010270, Val CE:0.043439, Train ACC:1.000000, Val ACC:0.993750

Epoch 3269/4000: 100%|██████████| 1/1 [00:00<00:00, 22.78it/s]

epoch: 3268, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011625, Train KL:8.769324, Val MSE:0.010243, Val CE:0.043603, Train ACC:1.000000, Val ACC:0.993750

Epoch 3270/4000: 100%|██████████| 1/1 [00:00<00:00, 24.22it/s]

epoch: 3269, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011625, Train KL:8.769326, Val MSE:0.010240, Val CE:0.043605, Train ACC:1.000000, Val ACC:0.993750

Epoch 3271/4000: 100%|██████████| 1/1 [00:00<00:00, 24.01it/s]

epoch: 3270, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011622, Train KL:8.769328, Val MSE:0.010290, Val CE:0.043426, Train ACC:1.000000, Val ACC:0.993750

Epoch 3272/4000: 100%|██████████| 1/1 [00:00<00:00, 20.12it/s]

epoch: 3271, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011631, Train KL:8.769329, Val MSE:0.010287, Val CE:0.043402, Train ACC:1.000000, Val ACC:0.993750

Epoch 3273/4000: 100%|██████████| 1/1 [00:00<00:00, 24.15it/s]

epoch: 3272, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011628, Train KL:8.769331, Val MSE:0.010281, Val CE:0.043619, Train ACC:1.000000, Val ACC:0.993750

Epoch 3274/4000: 100%|██████████| 1/1 [00:00<00:00, 22.90it/s]

epoch: 3273, beta = 0.000097, Train MSE: 0.006615, Train CE:0.011629, Train KL:8.769332, Val MSE:0.010300, Val CE:0.043503, Train ACC:1.000000, Val ACC:0.993750

Epoch 3275/4000: 100%|██████████| 1/1 [00:00<00:00, 23.23it/s]

epoch: 3274, beta = 0.000097, Train MSE: 0.006613, Train CE:0.011630, Train KL:8.769334, Val MSE:0.010269, Val CE:0.043365, Train ACC:1.000000, Val ACC:0.993750

Epoch 3276/4000: 100%|██████████| 1/1 [00:00<00:00, 22.42it/s]

epoch: 3275, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011625, Train KL:8.769336, Val MSE:0.010278, Val CE:0.043403, Train ACC:1.000000, Val ACC:0.993750

Epoch 3277/4000: 100%|██████████| 1/1 [00:00<00:00, 26.43it/s]

epoch: 3276, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011627, Train KL:8.769338, Val MSE:0.010267, Val CE:0.043372, Train ACC:1.000000, Val ACC:0.993750

Epoch 3278/4000: 100%|██████████| 1/1 [00:00<00:00, 23.57it/s]

epoch: 3277, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011624, Train KL:8.769339, Val MSE:0.010281, Val CE:0.043352, Train ACC:1.000000, Val ACC:0.993750

Epoch 3279/4000: 100%|██████████| 1/1 [00:00<00:00, 24.22it/s]

epoch: 3278, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011626, Train KL:8.769341, Val MSE:0.010279, Val CE:0.043598, Train ACC:1.000000, Val ACC:0.993750

Epoch 3280/4000: 100%|██████████| 1/1 [00:00<00:00, 24.12it/s]

epoch: 3279, beta = 0.000097, Train MSE: 0.006594, Train CE:0.011621, Train KL:8.769343, Val MSE:0.010297, Val CE:0.043618, Train ACC:1.000000, Val ACC:0.993750

Epoch 3281/4000: 100%|██████████| 1/1 [00:00<00:00, 22.00it/s]

epoch: 3280, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011623, Train KL:8.769343, Val MSE:0.010275, Val CE:0.043228, Train ACC:1.000000, Val ACC:0.993750

Epoch 3282/4000: 100%|██████████| 1/1 [00:00<00:00, 20.65it/s]

epoch: 3281, beta = 0.000097, Train MSE: 0.006613, Train CE:0.011626, Train KL:8.769345, Val MSE:0.010255, Val CE:0.043420, Train ACC:1.000000, Val ACC:0.993750

Epoch 3283/4000: 100%|██████████| 1/1 [00:00<00:00, 22.04it/s]

epoch: 3282, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011627, Train KL:8.769346, Val MSE:0.010247, Val CE:0.043338, Train ACC:1.000000, Val ACC:0.993750

Epoch 3284/4000: 100%|██████████| 1/1 [00:00<00:00, 23.19it/s]

epoch: 3283, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011631, Train KL:8.769348, Val MSE:0.010308, Val CE:0.043421, Train ACC:1.000000, Val ACC:0.993750

Epoch 3285/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 3284, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011627, Train KL:8.769350, Val MSE:0.010284, Val CE:0.043375, Train ACC:1.000000, Val ACC:0.993750

Epoch 3286/4000: 100%|██████████| 1/1 [00:00<00:00, 23.49it/s]

epoch: 3285, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011624, Train KL:8.769351, Val MSE:0.010264, Val CE:0.043288, Train ACC:1.000000, Val ACC:0.993750

Epoch 3287/4000: 100%|██████████| 1/1 [00:00<00:00, 24.29it/s]

epoch: 3286, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011627, Train KL:8.769353, Val MSE:0.010263, Val CE:0.043339, Train ACC:1.000000, Val ACC:0.993750

Epoch 3288/4000: 100%|██████████| 1/1 [00:00<00:00, 23.40it/s]

epoch: 3287, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011628, Train KL:8.769355, Val MSE:0.010283, Val CE:0.043498, Train ACC:1.000000, Val ACC:0.993750

Epoch 3289/4000: 100%|██████████| 1/1 [00:00<00:00, 23.98it/s]

epoch: 3288, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011623, Train KL:8.769357, Val MSE:0.010270, Val CE:0.043323, Train ACC:1.000000, Val ACC:0.993750

Epoch 3290/4000: 100%|██████████| 1/1 [00:00<00:00, 23.43it/s]

epoch: 3289, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011625, Train KL:8.769359, Val MSE:0.010247, Val CE:0.043491, Train ACC:1.000000, Val ACC:0.993750

Epoch 3291/4000: 100%|██████████| 1/1 [00:00<00:00, 22.65it/s]

epoch: 3290, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011627, Train KL:8.769360, Val MSE:0.010270, Val CE:0.043299, Train ACC:1.000000, Val ACC:0.993750

Epoch 3292/4000: 100%|██████████| 1/1 [00:00<00:00, 24.05it/s]

epoch: 3291, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011628, Train KL:8.769362, Val MSE:0.010286, Val CE:0.043298, Train ACC:1.000000, Val ACC:0.993750

Epoch 3293/4000: 100%|██████████| 1/1 [00:00<00:00, 23.50it/s]

epoch: 3292, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011629, Train KL:8.769364, Val MSE:0.010263, Val CE:0.043325, Train ACC:1.000000, Val ACC:0.993750

Epoch 3294/4000: 100%|██████████| 1/1 [00:00<00:00, 23.29it/s]

epoch: 3293, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011625, Train KL:8.769365, Val MSE:0.010297, Val CE:0.043371, Train ACC:1.000000, Val ACC:0.993750

Epoch 3295/4000: 100%|██████████| 1/1 [00:00<00:00, 23.10it/s]

epoch: 3294, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011620, Train KL:8.769366, Val MSE:0.010275, Val CE:0.043547, Train ACC:1.000000, Val ACC:0.993750

Epoch 3296/4000: 100%|██████████| 1/1 [00:00<00:00, 24.04it/s]

epoch: 3295, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011618, Train KL:8.769369, Val MSE:0.010277, Val CE:0.043539, Train ACC:1.000000, Val ACC:0.993750

Epoch 3297/4000: 100%|██████████| 1/1 [00:00<00:00, 21.94it/s]

epoch: 3296, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011623, Train KL:8.769370, Val MSE:0.010258, Val CE:0.043357, Train ACC:1.000000, Val ACC:0.993750

Epoch 3298/4000: 100%|██████████| 1/1 [00:00<00:00, 24.11it/s]

epoch: 3297, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011625, Train KL:8.769372, Val MSE:0.010253, Val CE:0.043440, Train ACC:1.000000, Val ACC:0.993750

Epoch 3299/4000: 100%|██████████| 1/1 [00:00<00:00, 23.97it/s]

epoch: 3298, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011623, Train KL:8.769373, Val MSE:0.010260, Val CE:0.043375, Train ACC:1.000000, Val ACC:0.993750

Epoch 3300/4000: 100%|██████████| 1/1 [00:00<00:00, 22.87it/s]

epoch: 3299, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011625, Train KL:8.769375, Val MSE:0.010272, Val CE:0.043473, Train ACC:1.000000, Val ACC:0.993750

Epoch 3301/4000: 100%|██████████| 1/1 [00:00<00:00, 21.57it/s]

epoch: 3300, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011623, Train KL:8.769376, Val MSE:0.010308, Val CE:0.043453, Train ACC:1.000000, Val ACC:0.993750

Epoch 3302/4000: 100%|██████████| 1/1 [00:00<00:00, 18.72it/s]

epoch: 3301, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011624, Train KL:8.769378, Val MSE:0.010277, Val CE:0.043499, Train ACC:1.000000, Val ACC:0.993750

Epoch 3303/4000: 100%|██████████| 1/1 [00:00<00:00, 23.47it/s]

epoch: 3302, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011627, Train KL:8.769380, Val MSE:0.010267, Val CE:0.043571, Train ACC:1.000000, Val ACC:0.993750

Epoch 3304/4000: 100%|██████████| 1/1 [00:00<00:00, 24.06it/s]

epoch: 3303, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011626, Train KL:8.769382, Val MSE:0.010273, Val CE:0.043605, Train ACC:1.000000, Val ACC:0.993750

Epoch 3305/4000: 100%|██████████| 1/1 [00:00<00:00, 24.07it/s]

epoch: 3304, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011628, Train KL:8.769382, Val MSE:0.010277, Val CE:0.043402, Train ACC:1.000000, Val ACC:0.993750

Epoch 3306/4000: 100%|██████████| 1/1 [00:00<00:00, 22.86it/s]

epoch: 3305, beta = 0.000097, Train MSE: 0.006592, Train CE:0.011624, Train KL:8.769384, Val MSE:0.010294, Val CE:0.043526, Train ACC:1.000000, Val ACC:0.993750

Epoch 3307/4000: 100%|██████████| 1/1 [00:00<00:00, 24.12it/s]

epoch: 3306, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011627, Train KL:8.769385, Val MSE:0.010270, Val CE:0.043631, Train ACC:1.000000, Val ACC:0.993750

Epoch 3308/4000: 100%|██████████| 1/1 [00:00<00:00, 23.51it/s]

epoch: 3307, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011622, Train KL:8.769387, Val MSE:0.010294, Val CE:0.043411, Train ACC:1.000000, Val ACC:0.993750

Epoch 3309/4000: 100%|██████████| 1/1 [00:00<00:00, 23.92it/s]

epoch: 3308, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011626, Train KL:8.769388, Val MSE:0.010288, Val CE:0.043450, Train ACC:1.000000, Val ACC:0.993750

Epoch 3310/4000: 100%|██████████| 1/1 [00:00<00:00, 23.44it/s]

epoch: 3309, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011625, Train KL:8.769389, Val MSE:0.010295, Val CE:0.043509, Train ACC:1.000000, Val ACC:0.993750

Epoch 3311/4000: 100%|██████████| 1/1 [00:00<00:00, 26.02it/s]

epoch: 3310, beta = 0.000097, Train MSE: 0.006594, Train CE:0.011624, Train KL:8.769391, Val MSE:0.010273, Val CE:0.043531, Train ACC:1.000000, Val ACC:0.993750

Epoch 3312/4000: 100%|██████████| 1/1 [00:00<00:00, 23.85it/s]

epoch: 3311, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011631, Train KL:8.769392, Val MSE:0.010270, Val CE:0.043452, Train ACC:1.000000, Val ACC:0.993750

Epoch 3313/4000: 100%|██████████| 1/1 [00:00<00:00, 24.01it/s]

epoch: 3312, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011627, Train KL:8.769393, Val MSE:0.010278, Val CE:0.043618, Train ACC:1.000000, Val ACC:0.993750

Epoch 3314/4000: 100%|██████████| 1/1 [00:00<00:00, 23.50it/s]

epoch: 3313, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011626, Train KL:8.769395, Val MSE:0.010289, Val CE:0.043508, Train ACC:1.000000, Val ACC:0.993750

Epoch 3315/4000: 100%|██████████| 1/1 [00:00<00:00, 23.11it/s]

epoch: 3314, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011624, Train KL:8.769397, Val MSE:0.010291, Val CE:0.043557, Train ACC:1.000000, Val ACC:0.993750

Epoch 3316/4000: 100%|██████████| 1/1 [00:00<00:00, 19.50it/s]

epoch: 3315, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011622, Train KL:8.769398, Val MSE:0.010257, Val CE:0.043498, Train ACC:1.000000, Val ACC:0.993750

Epoch 3317/4000: 100%|██████████| 1/1 [00:00<00:00, 20.95it/s]

epoch: 3316, beta = 0.000097, Train MSE: 0.006611, Train CE:0.011621, Train KL:8.769399, Val MSE:0.010301, Val CE:0.043550, Train ACC:1.000000, Val ACC:0.993750

Epoch 3318/4000: 100%|██████████| 1/1 [00:00<00:00, 22.87it/s]

epoch: 3317, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011621, Train KL:8.769401, Val MSE:0.010295, Val CE:0.043534, Train ACC:1.000000, Val ACC:0.993750

Epoch 3319/4000: 100%|██████████| 1/1 [00:00<00:00, 24.02it/s]

epoch: 3318, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011632, Train KL:8.769403, Val MSE:0.010281, Val CE:0.043555, Train ACC:1.000000, Val ACC:0.993750

Epoch 3320/4000: 100%|██████████| 1/1 [00:00<00:00, 21.62it/s]

epoch: 3319, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011622, Train KL:8.769403, Val MSE:0.010250, Val CE:0.043296, Train ACC:1.000000, Val ACC:0.993750

Epoch 3321/4000: 100%|██████████| 1/1 [00:00<00:00, 23.33it/s]

epoch: 3320, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011625, Train KL:8.769404, Val MSE:0.010287, Val CE:0.043386, Train ACC:1.000000, Val ACC:0.993750

Epoch 3322/4000: 100%|██████████| 1/1 [00:00<00:00, 24.07it/s]

epoch: 3321, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011622, Train KL:8.769405, Val MSE:0.010273, Val CE:0.043707, Train ACC:1.000000, Val ACC:0.993750

Epoch 3323/4000: 100%|██████████| 1/1 [00:00<00:00, 24.08it/s]

epoch: 3322, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011629, Train KL:8.769407, Val MSE:0.010269, Val CE:0.043441, Train ACC:1.000000, Val ACC:0.993750

Epoch 3324/4000: 100%|██████████| 1/1 [00:00<00:00, 23.32it/s]

epoch: 3323, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011624, Train KL:8.769408, Val MSE:0.010277, Val CE:0.043609, Train ACC:1.000000, Val ACC:0.993750

Epoch 3325/4000: 100%|██████████| 1/1 [00:00<00:00, 24.15it/s]

epoch: 3324, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011628, Train KL:8.769410, Val MSE:0.010299, Val CE:0.043302, Train ACC:1.000000, Val ACC:0.993750

Epoch 3326/4000: 100%|██████████| 1/1 [00:00<00:00, 23.52it/s]

epoch: 3325, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011625, Train KL:8.769412, Val MSE:0.010295, Val CE:0.043527, Train ACC:1.000000, Val ACC:0.993750

Epoch 3327/4000: 100%|██████████| 1/1 [00:00<00:00, 22.66it/s]

epoch: 3326, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011621, Train KL:8.769413, Val MSE:0.010274, Val CE:0.043399, Train ACC:1.000000, Val ACC:0.993750

Epoch 3328/4000: 100%|██████████| 1/1 [00:00<00:00, 22.20it/s]

epoch: 3327, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011627, Train KL:8.769415, Val MSE:0.010296, Val CE:0.043403, Train ACC:1.000000, Val ACC:0.993750

Epoch 3329/4000: 100%|██████████| 1/1 [00:00<00:00, 22.33it/s]

epoch: 3328, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011628, Train KL:8.769416, Val MSE:0.010269, Val CE:0.043538, Train ACC:1.000000, Val ACC:0.993750

Epoch 3330/4000: 100%|██████████| 1/1 [00:00<00:00, 23.89it/s]

epoch: 3329, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011625, Train KL:8.769418, Val MSE:0.010271, Val CE:0.043563, Train ACC:1.000000, Val ACC:0.993750

Epoch 3331/4000: 100%|██████████| 1/1 [00:00<00:00, 23.43it/s]

epoch: 3330, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011625, Train KL:8.769419, Val MSE:0.010298, Val CE:0.043474, Train ACC:1.000000, Val ACC:0.993750

Epoch 3332/4000: 100%|██████████| 1/1 [00:00<00:00, 23.02it/s]

epoch: 3331, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011623, Train KL:8.769421, Val MSE:0.010282, Val CE:0.043495, Train ACC:1.000000, Val ACC:0.993750

Epoch 3333/4000: 100%|██████████| 1/1 [00:00<00:00, 23.81it/s]

epoch: 3332, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011629, Train KL:8.769422, Val MSE:0.010265, Val CE:0.043376, Train ACC:1.000000, Val ACC:0.993750

Epoch 3334/4000: 100%|██████████| 1/1 [00:00<00:00, 24.16it/s]

epoch: 3333, beta = 0.000097, Train MSE: 0.006591, Train CE:0.011627, Train KL:8.769423, Val MSE:0.010314, Val CE:0.043384, Train ACC:1.000000, Val ACC:0.993750

Epoch 3335/4000: 100%|██████████| 1/1 [00:00<00:00, 22.74it/s]

epoch: 3334, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011622, Train KL:8.769424, Val MSE:0.010251, Val CE:0.043416, Train ACC:1.000000, Val ACC:0.993750

Epoch 3336/4000: 100%|██████████| 1/1 [00:00<00:00, 18.25it/s]

epoch: 3335, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011623, Train KL:8.769425, Val MSE:0.010281, Val CE:0.043347, Train ACC:1.000000, Val ACC:0.993750

Epoch 3337/4000: 100%|██████████| 1/1 [00:00<00:00, 22.35it/s]

epoch: 3336, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011617, Train KL:8.769427, Val MSE:0.010252, Val CE:0.043503, Train ACC:1.000000, Val ACC:0.993750

Epoch 3338/4000: 100%|██████████| 1/1 [00:00<00:00, 23.47it/s]

epoch: 3337, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011624, Train KL:8.769428, Val MSE:0.010289, Val CE:0.043562, Train ACC:1.000000, Val ACC:0.993750

Epoch 3339/4000: 100%|██████████| 1/1 [00:00<00:00, 24.12it/s]

epoch: 3338, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011625, Train KL:8.769429, Val MSE:0.010272, Val CE:0.043258, Train ACC:1.000000, Val ACC:0.993750

Epoch 3340/4000: 100%|██████████| 1/1 [00:00<00:00, 23.82it/s]

epoch: 3339, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011630, Train KL:8.769430, Val MSE:0.010263, Val CE:0.043431, Train ACC:1.000000, Val ACC:0.993750

Epoch 3341/4000: 100%|██████████| 1/1 [00:00<00:00, 23.66it/s]

epoch: 3340, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011625, Train KL:8.769433, Val MSE:0.010257, Val CE:0.043412, Train ACC:1.000000, Val ACC:0.993750

Epoch 3342/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 3341, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011623, Train KL:8.769435, Val MSE:0.010278, Val CE:0.043519, Train ACC:1.000000, Val ACC:0.993750

Epoch 3343/4000: 100%|██████████| 1/1 [00:00<00:00, 24.19it/s]

epoch: 3342, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011623, Train KL:8.769436, Val MSE:0.010290, Val CE:0.043281, Train ACC:1.000000, Val ACC:0.993750

Epoch 3344/4000: 100%|██████████| 1/1 [00:00<00:00, 21.34it/s]

epoch: 3343, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011623, Train KL:8.769437, Val MSE:0.010279, Val CE:0.043322, Train ACC:1.000000, Val ACC:0.993750

Epoch 3345/4000: 100%|██████████| 1/1 [00:00<00:00, 23.98it/s]

epoch: 3344, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011618, Train KL:8.769440, Val MSE:0.010268, Val CE:0.043483, Train ACC:1.000000, Val ACC:0.993750

Epoch 3346/4000: 100%|██████████| 1/1 [00:00<00:00, 24.07it/s]

epoch: 3345, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011623, Train KL:8.769441, Val MSE:0.010288, Val CE:0.043396, Train ACC:1.000000, Val ACC:0.993750

Epoch 3347/4000: 100%|██████████| 1/1 [00:00<00:00, 22.22it/s]

epoch: 3346, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011627, Train KL:8.769443, Val MSE:0.010296, Val CE:0.043366, Train ACC:1.000000, Val ACC:0.993750

Epoch 3348/4000: 100%|██████████| 1/1 [00:00<00:00, 23.28it/s]

epoch: 3347, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011626, Train KL:8.769444, Val MSE:0.010271, Val CE:0.043592, Train ACC:1.000000, Val ACC:0.993750

Epoch 3349/4000: 100%|██████████| 1/1 [00:00<00:00, 23.43it/s]

epoch: 3348, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011626, Train KL:8.769445, Val MSE:0.010283, Val CE:0.043559, Train ACC:1.000000, Val ACC:0.993750

Epoch 3350/4000: 100%|██████████| 1/1 [00:00<00:00, 22.46it/s]

epoch: 3349, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011627, Train KL:8.769447, Val MSE:0.010288, Val CE:0.043350, Train ACC:1.000000, Val ACC:0.993750

Epoch 3351/4000: 100%|██████████| 1/1 [00:00<00:00, 20.39it/s]

epoch: 3350, beta = 0.000097, Train MSE: 0.006593, Train CE:0.011624, Train KL:8.769448, Val MSE:0.010267, Val CE:0.043291, Train ACC:1.000000, Val ACC:0.993750

Epoch 3352/4000: 100%|██████████| 1/1 [00:00<00:00, 22.48it/s]

epoch: 3351, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011627, Train KL:8.769450, Val MSE:0.010275, Val CE:0.043441, Train ACC:1.000000, Val ACC:0.993750

Epoch 3353/4000: 100%|██████████| 1/1 [00:00<00:00, 23.97it/s]

epoch: 3352, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011628, Train KL:8.769451, Val MSE:0.010272, Val CE:0.043445, Train ACC:1.000000, Val ACC:0.993750

Epoch 3354/4000: 100%|██████████| 1/1 [00:00<00:00, 21.07it/s]

epoch: 3353, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011632, Train KL:8.769453, Val MSE:0.010266, Val CE:0.043560, Train ACC:1.000000, Val ACC:0.993750

Epoch 3355/4000: 100%|██████████| 1/1 [00:00<00:00, 24.02it/s]

epoch: 3354, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011622, Train KL:8.769455, Val MSE:0.010283, Val CE:0.043392, Train ACC:1.000000, Val ACC:0.993750

Epoch 3356/4000: 100%|██████████| 1/1 [00:00<00:00, 21.71it/s]

epoch: 3355, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011625, Train KL:8.769456, Val MSE:0.010266, Val CE:0.043362, Train ACC:1.000000, Val ACC:0.993750

Epoch 3357/4000: 100%|██████████| 1/1 [00:00<00:00, 23.41it/s]

epoch: 3356, beta = 0.000097, Train MSE: 0.006595, Train CE:0.011622, Train KL:8.769458, Val MSE:0.010297, Val CE:0.043505, Train ACC:1.000000, Val ACC:0.993750

Epoch 3358/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 3357, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011625, Train KL:8.769459, Val MSE:0.010259, Val CE:0.043505, Train ACC:1.000000, Val ACC:0.993750

Epoch 3359/4000: 100%|██████████| 1/1 [00:00<00:00, 24.01it/s]

epoch: 3358, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011632, Train KL:8.769461, Val MSE:0.010262, Val CE:0.043290, Train ACC:1.000000, Val ACC:0.993750

Epoch 3360/4000: 100%|██████████| 1/1 [00:00<00:00, 23.52it/s]

epoch: 3359, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011623, Train KL:8.769463, Val MSE:0.010275, Val CE:0.043525, Train ACC:1.000000, Val ACC:0.993750

Epoch 3361/4000: 100%|██████████| 1/1 [00:00<00:00, 21.90it/s]

epoch: 3360, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011627, Train KL:8.769464, Val MSE:0.010283, Val CE:0.043645, Train ACC:1.000000, Val ACC:0.993750

Epoch 3362/4000: 100%|██████████| 1/1 [00:00<00:00, 23.10it/s]

epoch: 3361, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011626, Train KL:8.769465, Val MSE:0.010301, Val CE:0.043518, Train ACC:1.000000, Val ACC:0.993750

Epoch 3363/4000: 100%|██████████| 1/1 [00:00<00:00, 23.30it/s]

epoch: 3362, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011624, Train KL:8.769466, Val MSE:0.010292, Val CE:0.043406, Train ACC:1.000000, Val ACC:0.993750

Epoch 3364/4000: 100%|██████████| 1/1 [00:00<00:00, 24.14it/s]

epoch: 3363, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011620, Train KL:8.769468, Val MSE:0.010287, Val CE:0.043547, Train ACC:1.000000, Val ACC:0.993750

Epoch 3365/4000: 100%|██████████| 1/1 [00:00<00:00, 25.48it/s]

epoch: 3364, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011620, Train KL:8.769470, Val MSE:0.010280, Val CE:0.043590, Train ACC:1.000000, Val ACC:0.993750

Epoch 3366/4000: 100%|██████████| 1/1 [00:00<00:00, 22.34it/s]

epoch: 3365, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011627, Train KL:8.769471, Val MSE:0.010257, Val CE:0.043347, Train ACC:1.000000, Val ACC:0.993750

Epoch 3367/4000: 100%|██████████| 1/1 [00:00<00:00, 20.13it/s]

epoch: 3366, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011627, Train KL:8.769473, Val MSE:0.010272, Val CE:0.043538, Train ACC:1.000000, Val ACC:0.993750

Epoch 3368/4000: 100%|██████████| 1/1 [00:00<00:00, 18.95it/s]

epoch: 3367, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011622, Train KL:8.769474, Val MSE:0.010301, Val CE:0.043356, Train ACC:1.000000, Val ACC:0.993750

Epoch 3369/4000: 100%|██████████| 1/1 [00:00<00:00, 23.34it/s]

epoch: 3368, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011624, Train KL:8.769476, Val MSE:0.010280, Val CE:0.043250, Train ACC:1.000000, Val ACC:0.993750

Epoch 3370/4000: 100%|██████████| 1/1 [00:00<00:00, 23.67it/s]

epoch: 3369, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011623, Train KL:8.769478, Val MSE:0.010266, Val CE:0.043274, Train ACC:1.000000, Val ACC:0.993750

Epoch 3371/4000: 100%|██████████| 1/1 [00:00<00:00, 22.95it/s]

epoch: 3370, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011620, Train KL:8.769481, Val MSE:0.010268, Val CE:0.043552, Train ACC:1.000000, Val ACC:0.993750

Epoch 3372/4000: 100%|██████████| 1/1 [00:00<00:00, 23.81it/s]

epoch: 3371, beta = 0.000097, Train MSE: 0.006595, Train CE:0.011622, Train KL:8.769482, Val MSE:0.010303, Val CE:0.043585, Train ACC:1.000000, Val ACC:0.993750

Epoch 3373/4000: 100%|██████████| 1/1 [00:00<00:00, 23.40it/s]

epoch: 3372, beta = 0.000097, Train MSE: 0.006594, Train CE:0.011627, Train KL:8.769484, Val MSE:0.010285, Val CE:0.043454, Train ACC:1.000000, Val ACC:0.993750

Epoch 3374/4000: 100%|██████████| 1/1 [00:00<00:00, 23.71it/s]

epoch: 3373, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011621, Train KL:8.769485, Val MSE:0.010280, Val CE:0.043557, Train ACC:1.000000, Val ACC:0.993750

Epoch 3375/4000: 100%|██████████| 1/1 [00:00<00:00, 23.13it/s]

epoch: 3374, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011619, Train KL:8.769486, Val MSE:0.010313, Val CE:0.043567, Train ACC:1.000000, Val ACC:0.993750

Epoch 3376/4000: 100%|██████████| 1/1 [00:00<00:00, 24.05it/s]

epoch: 3375, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011622, Train KL:8.769488, Val MSE:0.010292, Val CE:0.043346, Train ACC:1.000000, Val ACC:0.993750

Epoch 3377/4000: 100%|██████████| 1/1 [00:00<00:00, 23.59it/s]

epoch: 3376, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011621, Train KL:8.769489, Val MSE:0.010256, Val CE:0.043298, Train ACC:1.000000, Val ACC:0.993750

Epoch 3378/4000: 100%|██████████| 1/1 [00:00<00:00, 23.48it/s]

epoch: 3377, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011624, Train KL:8.769492, Val MSE:0.010267, Val CE:0.043535, Train ACC:1.000000, Val ACC:0.993750

Epoch 3379/4000: 100%|██████████| 1/1 [00:00<00:00, 23.46it/s]

epoch: 3378, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011625, Train KL:8.769493, Val MSE:0.010265, Val CE:0.043404, Train ACC:1.000000, Val ACC:0.993750

Epoch 3380/4000: 100%|██████████| 1/1 [00:00<00:00, 26.97it/s]

epoch: 3379, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011629, Train KL:8.769496, Val MSE:0.010270, Val CE:0.043518, Train ACC:1.000000, Val ACC:0.993750

Epoch 3381/4000: 100%|██████████| 1/1 [00:00<00:00, 24.37it/s]

epoch: 3380, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011628, Train KL:8.769497, Val MSE:0.010285, Val CE:0.043555, Train ACC:1.000000, Val ACC:0.993750

Epoch 3382/4000: 100%|██████████| 1/1 [00:00<00:00, 20.55it/s]

epoch: 3381, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011625, Train KL:8.769499, Val MSE:0.010288, Val CE:0.043400, Train ACC:1.000000, Val ACC:0.993750

Epoch 3383/4000: 100%|██████████| 1/1 [00:00<00:00, 21.74it/s]

epoch: 3382, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011622, Train KL:8.769501, Val MSE:0.010247, Val CE:0.043512, Train ACC:1.000000, Val ACC:0.993750

Epoch 3384/4000: 100%|██████████| 1/1 [00:00<00:00, 24.08it/s]

epoch: 3383, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011626, Train KL:8.769503, Val MSE:0.010254, Val CE:0.043585, Train ACC:1.000000, Val ACC:0.993750

Epoch 3385/4000: 100%|██████████| 1/1 [00:00<00:00, 24.08it/s]

epoch: 3384, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011621, Train KL:8.769505, Val MSE:0.010252, Val CE:0.043419, Train ACC:1.000000, Val ACC:0.993750

Epoch 3386/4000: 100%|██████████| 1/1 [00:00<00:00, 23.38it/s]

epoch: 3385, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011625, Train KL:8.769506, Val MSE:0.010308, Val CE:0.043598, Train ACC:1.000000, Val ACC:0.993750

Epoch 3387/4000: 100%|██████████| 1/1 [00:00<00:00, 24.11it/s]

epoch: 3386, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011628, Train KL:8.769508, Val MSE:0.010296, Val CE:0.043393, Train ACC:1.000000, Val ACC:0.993750

Epoch 3388/4000: 100%|██████████| 1/1 [00:00<00:00, 25.32it/s]

epoch: 3387, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011629, Train KL:8.769509, Val MSE:0.010263, Val CE:0.043402, Train ACC:1.000000, Val ACC:0.993750

Epoch 3389/4000: 100%|██████████| 1/1 [00:00<00:00, 23.87it/s]

epoch: 3388, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011626, Train KL:8.769511, Val MSE:0.010285, Val CE:0.043296, Train ACC:1.000000, Val ACC:0.993750

Epoch 3390/4000: 100%|██████████| 1/1 [00:00<00:00, 23.64it/s]

epoch: 3389, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011625, Train KL:8.769512, Val MSE:0.010258, Val CE:0.043367, Train ACC:1.000000, Val ACC:0.993750

Epoch 3391/4000: 100%|██████████| 1/1 [00:00<00:00, 23.97it/s]

epoch: 3390, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011621, Train KL:8.769514, Val MSE:0.010270, Val CE:0.043338, Train ACC:1.000000, Val ACC:0.993750

Epoch 3392/4000: 100%|██████████| 1/1 [00:00<00:00, 23.47it/s]

epoch: 3391, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011624, Train KL:8.769516, Val MSE:0.010269, Val CE:0.043601, Train ACC:1.000000, Val ACC:0.993750

Epoch 3393/4000: 100%|██████████| 1/1 [00:00<00:00, 23.72it/s]

epoch: 3392, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011622, Train KL:8.769517, Val MSE:0.010252, Val CE:0.043405, Train ACC:1.000000, Val ACC:0.993750

Epoch 3394/4000: 100%|██████████| 1/1 [00:00<00:00, 23.89it/s]

epoch: 3393, beta = 0.000097, Train MSE: 0.006590, Train CE:0.011626, Train KL:8.769520, Val MSE:0.010255, Val CE:0.043502, Train ACC:1.000000, Val ACC:0.993750

Epoch 3395/4000: 100%|██████████| 1/1 [00:00<00:00, 22.04it/s]

epoch: 3394, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011628, Train KL:8.769521, Val MSE:0.010263, Val CE:0.043459, Train ACC:1.000000, Val ACC:0.993750

Epoch 3396/4000: 100%|██████████| 1/1 [00:00<00:00, 20.64it/s]

epoch: 3395, beta = 0.000097, Train MSE: 0.006614, Train CE:0.011628, Train KL:8.769524, Val MSE:0.010291, Val CE:0.043464, Train ACC:1.000000, Val ACC:0.993750

Epoch 3397/4000: 100%|██████████| 1/1 [00:00<00:00, 24.09it/s]

epoch: 3396, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011622, Train KL:8.769525, Val MSE:0.010286, Val CE:0.043476, Train ACC:1.000000, Val ACC:0.993750

Epoch 3398/4000: 100%|██████████| 1/1 [00:00<00:00, 23.16it/s]

epoch: 3397, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011616, Train KL:8.769526, Val MSE:0.010307, Val CE:0.043512, Train ACC:1.000000, Val ACC:0.993750

Epoch 3399/4000: 100%|██████████| 1/1 [00:00<00:00, 23.37it/s]

epoch: 3398, beta = 0.000097, Train MSE: 0.006616, Train CE:0.011620, Train KL:8.769527, Val MSE:0.010268, Val CE:0.043425, Train ACC:1.000000, Val ACC:0.993750

Epoch 3400/4000: 100%|██████████| 1/1 [00:00<00:00, 22.66it/s]

epoch: 3399, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011624, Train KL:8.769530, Val MSE:0.010269, Val CE:0.043439, Train ACC:1.000000, Val ACC:0.993750

Epoch 3401/4000: 100%|██████████| 1/1 [00:00<00:00, 23.00it/s]

epoch: 3400, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011623, Train KL:8.769531, Val MSE:0.010294, Val CE:0.043626, Train ACC:1.000000, Val ACC:0.993750

Epoch 3402/4000: 100%|██████████| 1/1 [00:00<00:00, 23.62it/s]

epoch: 3401, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011620, Train KL:8.769533, Val MSE:0.010271, Val CE:0.043650, Train ACC:1.000000, Val ACC:0.993750

Epoch 3403/4000: 100%|██████████| 1/1 [00:00<00:00, 24.23it/s]

epoch: 3402, beta = 0.000097, Train MSE: 0.006595, Train CE:0.011624, Train KL:8.769535, Val MSE:0.010298, Val CE:0.043549, Train ACC:1.000000, Val ACC:0.993750

Epoch 3404/4000: 100%|██████████| 1/1 [00:00<00:00, 23.91it/s]

epoch: 3403, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011617, Train KL:8.769536, Val MSE:0.010270, Val CE:0.043416, Train ACC:1.000000, Val ACC:0.993750

Epoch 3405/4000: 100%|██████████| 1/1 [00:00<00:00, 22.89it/s]

epoch: 3404, beta = 0.000097, Train MSE: 0.006611, Train CE:0.011623, Train KL:8.769538, Val MSE:0.010266, Val CE:0.043560, Train ACC:1.000000, Val ACC:0.993750

Epoch 3406/4000: 100%|██████████| 1/1 [00:00<00:00, 24.36it/s]

epoch: 3405, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011624, Train KL:8.769540, Val MSE:0.010285, Val CE:0.043401, Train ACC:1.000000, Val ACC:0.993750

Epoch 3407/4000: 100%|██████████| 1/1 [00:00<00:00, 23.00it/s]

epoch: 3406, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011623, Train KL:8.769542, Val MSE:0.010293, Val CE:0.043563, Train ACC:1.000000, Val ACC:0.993750

Epoch 3408/4000: 100%|██████████| 1/1 [00:00<00:00, 24.86it/s]

epoch: 3407, beta = 0.000097, Train MSE: 0.006594, Train CE:0.011622, Train KL:8.769544, Val MSE:0.010292, Val CE:0.043520, Train ACC:1.000000, Val ACC:0.993750

Epoch 3409/4000: 100%|██████████| 1/1 [00:00<00:00, 24.10it/s]

epoch: 3408, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011622, Train KL:8.769545, Val MSE:0.010276, Val CE:0.043351, Train ACC:1.000000, Val ACC:0.993750

Epoch 3410/4000: 100%|██████████| 1/1 [00:00<00:00, 24.02it/s]

epoch: 3409, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011622, Train KL:8.769547, Val MSE:0.010301, Val CE:0.043534, Train ACC:1.000000, Val ACC:0.993750

Epoch 3411/4000: 100%|██████████| 1/1 [00:00<00:00, 19.09it/s]

epoch: 3410, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011623, Train KL:8.769547, Val MSE:0.010260, Val CE:0.043385, Train ACC:1.000000, Val ACC:0.993750

Epoch 3412/4000: 100%|██████████| 1/1 [00:00<00:00, 20.64it/s]

epoch: 3411, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011628, Train KL:8.769549, Val MSE:0.010283, Val CE:0.043444, Train ACC:1.000000, Val ACC:0.993750

Epoch 3413/4000: 100%|██████████| 1/1 [00:00<00:00, 24.56it/s]

epoch: 3412, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011620, Train KL:8.769551, Val MSE:0.010276, Val CE:0.043428, Train ACC:1.000000, Val ACC:0.993750

Epoch 3414/4000: 100%|██████████| 1/1 [00:00<00:00, 24.22it/s]

epoch: 3413, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011625, Train KL:8.769552, Val MSE:0.010264, Val CE:0.043525, Train ACC:1.000000, Val ACC:0.993750

Epoch 3415/4000: 100%|██████████| 1/1 [00:00<00:00, 24.01it/s]

epoch: 3414, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011621, Train KL:8.769554, Val MSE:0.010250, Val CE:0.043291, Train ACC:1.000000, Val ACC:0.993750

Epoch 3416/4000: 100%|██████████| 1/1 [00:00<00:00, 22.84it/s]

epoch: 3415, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011618, Train KL:8.769556, Val MSE:0.010274, Val CE:0.043492, Train ACC:1.000000, Val ACC:0.993750

Epoch 3417/4000: 100%|██████████| 1/1 [00:00<00:00, 23.00it/s]

epoch: 3416, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011617, Train KL:8.769558, Val MSE:0.010293, Val CE:0.043523, Train ACC:1.000000, Val ACC:0.993750

Epoch 3418/4000: 100%|██████████| 1/1 [00:00<00:00, 25.97it/s]

epoch: 3417, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011621, Train KL:8.769560, Val MSE:0.010288, Val CE:0.043511, Train ACC:1.000000, Val ACC:0.993750

Epoch 3419/4000: 100%|██████████| 1/1 [00:00<00:00, 24.07it/s]

epoch: 3418, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011629, Train KL:8.769561, Val MSE:0.010279, Val CE:0.043357, Train ACC:1.000000, Val ACC:0.993750

Epoch 3420/4000: 100%|██████████| 1/1 [00:00<00:00, 23.82it/s]

epoch: 3419, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011621, Train KL:8.769563, Val MSE:0.010274, Val CE:0.043515, Train ACC:1.000000, Val ACC:0.993750

Epoch 3421/4000: 100%|██████████| 1/1 [00:00<00:00, 24.25it/s]

epoch: 3420, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011626, Train KL:8.769563, Val MSE:0.010300, Val CE:0.043272, Train ACC:1.000000, Val ACC:0.993750

Epoch 3422/4000: 100%|██████████| 1/1 [00:00<00:00, 23.98it/s]

epoch: 3421, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011621, Train KL:8.769567, Val MSE:0.010294, Val CE:0.043626, Train ACC:1.000000, Val ACC:0.993750

Epoch 3423/4000: 100%|██████████| 1/1 [00:00<00:00, 23.66it/s]

epoch: 3422, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011621, Train KL:8.769567, Val MSE:0.010306, Val CE:0.043366, Train ACC:1.000000, Val ACC:0.993750

Epoch 3424/4000: 100%|██████████| 1/1 [00:00<00:00, 23.66it/s]

epoch: 3423, beta = 0.000097, Train MSE: 0.006588, Train CE:0.011620, Train KL:8.769569, Val MSE:0.010276, Val CE:0.043398, Train ACC:1.000000, Val ACC:0.993750

Epoch 3425/4000: 100%|██████████| 1/1 [00:00<00:00, 23.56it/s]

epoch: 3424, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011617, Train KL:8.769570, Val MSE:0.010261, Val CE:0.043572, Train ACC:1.000000, Val ACC:0.993750

Epoch 3426/4000: 100%|██████████| 1/1 [00:00<00:00, 24.30it/s]

epoch: 3425, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011623, Train KL:8.769572, Val MSE:0.010289, Val CE:0.043222, Train ACC:1.000000, Val ACC:0.993750

Epoch 3427/4000: 100%|██████████| 1/1 [00:00<00:00, 21.39it/s]

epoch: 3426, beta = 0.000097, Train MSE: 0.006595, Train CE:0.011621, Train KL:8.769574, Val MSE:0.010282, Val CE:0.043226, Train ACC:1.000000, Val ACC:0.993750

Epoch 3428/4000: 100%|██████████| 1/1 [00:00<00:00, 21.93it/s]

epoch: 3427, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011617, Train KL:8.769575, Val MSE:0.010278, Val CE:0.043457, Train ACC:1.000000, Val ACC:0.993750

Epoch 3429/4000: 100%|██████████| 1/1 [00:00<00:00, 21.41it/s]

epoch: 3428, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011621, Train KL:8.769577, Val MSE:0.010279, Val CE:0.043411, Train ACC:1.000000, Val ACC:0.993750

Epoch 3430/4000: 100%|██████████| 1/1 [00:00<00:00, 24.80it/s]

epoch: 3429, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011623, Train KL:8.769578, Val MSE:0.010258, Val CE:0.043518, Train ACC:1.000000, Val ACC:0.993750

Epoch 3431/4000: 100%|██████████| 1/1 [00:00<00:00, 24.06it/s]

epoch: 3430, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011622, Train KL:8.769580, Val MSE:0.010291, Val CE:0.043497, Train ACC:1.000000, Val ACC:0.993750

Epoch 3432/4000: 100%|██████████| 1/1 [00:00<00:00, 22.65it/s]

epoch: 3431, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011612, Train KL:8.769582, Val MSE:0.010276, Val CE:0.043296, Train ACC:1.000000, Val ACC:0.993750

Epoch 3433/4000: 100%|██████████| 1/1 [00:00<00:00, 22.56it/s]

epoch: 3432, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011619, Train KL:8.769583, Val MSE:0.010279, Val CE:0.043516, Train ACC:1.000000, Val ACC:0.993750

Epoch 3434/4000: 100%|██████████| 1/1 [00:00<00:00, 23.15it/s]

epoch: 3433, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011626, Train KL:8.769586, Val MSE:0.010275, Val CE:0.043426, Train ACC:1.000000, Val ACC:0.993750

Epoch 3435/4000: 100%|██████████| 1/1 [00:00<00:00, 23.19it/s]

epoch: 3434, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011618, Train KL:8.769587, Val MSE:0.010274, Val CE:0.043514, Train ACC:1.000000, Val ACC:0.993750

Epoch 3436/4000: 100%|██████████| 1/1 [00:00<00:00, 23.00it/s]

epoch: 3435, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011621, Train KL:8.769588, Val MSE:0.010277, Val CE:0.043549, Train ACC:1.000000, Val ACC:0.993750

Epoch 3437/4000: 100%|██████████| 1/1 [00:00<00:00, 22.78it/s]

epoch: 3436, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011617, Train KL:8.769589, Val MSE:0.010274, Val CE:0.043406, Train ACC:1.000000, Val ACC:0.993750

Epoch 3438/4000: 100%|██████████| 1/1 [00:00<00:00, 22.14it/s]

epoch: 3437, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011621, Train KL:8.769591, Val MSE:0.010283, Val CE:0.043448, Train ACC:1.000000, Val ACC:0.993750

Epoch 3439/4000: 100%|██████████| 1/1 [00:00<00:00, 23.88it/s]

epoch: 3438, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011623, Train KL:8.769593, Val MSE:0.010271, Val CE:0.043513, Train ACC:1.000000, Val ACC:0.993750

Epoch 3440/4000: 100%|██████████| 1/1 [00:00<00:00, 22.16it/s]

epoch: 3439, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011617, Train KL:8.769594, Val MSE:0.010284, Val CE:0.043431, Train ACC:1.000000, Val ACC:0.993750

Epoch 3441/4000: 100%|██████████| 1/1 [00:00<00:00, 20.77it/s]

epoch: 3440, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011622, Train KL:8.769595, Val MSE:0.010264, Val CE:0.043321, Train ACC:1.000000, Val ACC:0.993750

Epoch 3442/4000: 100%|██████████| 1/1 [00:00<00:00, 20.99it/s]

epoch: 3441, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011622, Train KL:8.769597, Val MSE:0.010317, Val CE:0.043487, Train ACC:1.000000, Val ACC:0.993750

Epoch 3443/4000: 100%|██████████| 1/1 [00:00<00:00, 17.99it/s]

epoch: 3442, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011619, Train KL:8.769599, Val MSE:0.010288, Val CE:0.043358, Train ACC:1.000000, Val ACC:0.993750

Epoch 3444/4000: 100%|██████████| 1/1 [00:00<00:00, 23.02it/s]

epoch: 3443, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011622, Train KL:8.769600, Val MSE:0.010273, Val CE:0.043568, Train ACC:1.000000, Val ACC:0.993750

Epoch 3445/4000: 100%|██████████| 1/1 [00:00<00:00, 23.65it/s]

epoch: 3444, beta = 0.000097, Train MSE: 0.006595, Train CE:0.011622, Train KL:8.769601, Val MSE:0.010256, Val CE:0.043535, Train ACC:1.000000, Val ACC:0.993750

Epoch 3446/4000: 100%|██████████| 1/1 [00:00<00:00, 23.30it/s]

epoch: 3445, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011624, Train KL:8.769603, Val MSE:0.010286, Val CE:0.043592, Train ACC:1.000000, Val ACC:0.993750

Epoch 3447/4000: 100%|██████████| 1/1 [00:00<00:00, 24.12it/s]

epoch: 3446, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011621, Train KL:8.769605, Val MSE:0.010242, Val CE:0.043478, Train ACC:1.000000, Val ACC:0.993750

Epoch 3448/4000: 100%|██████████| 1/1 [00:00<00:00, 23.40it/s]

epoch: 3447, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011621, Train KL:8.769606, Val MSE:0.010272, Val CE:0.043574, Train ACC:1.000000, Val ACC:0.993750

Epoch 3449/4000: 100%|██████████| 1/1 [00:00<00:00, 24.04it/s]

epoch: 3448, beta = 0.000097, Train MSE: 0.006590, Train CE:0.011619, Train KL:8.769607, Val MSE:0.010285, Val CE:0.043452, Train ACC:1.000000, Val ACC:0.993750

Epoch 3450/4000: 100%|██████████| 1/1 [00:00<00:00, 23.43it/s]

epoch: 3449, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011621, Train KL:8.769608, Val MSE:0.010269, Val CE:0.043316, Train ACC:1.000000, Val ACC:0.993750

Epoch 3451/4000: 100%|██████████| 1/1 [00:00<00:00, 23.94it/s]

epoch: 3450, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011621, Train KL:8.769608, Val MSE:0.010267, Val CE:0.043365, Train ACC:1.000000, Val ACC:0.993750

Epoch 3452/4000: 100%|██████████| 1/1 [00:00<00:00, 23.81it/s]

epoch: 3451, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011619, Train KL:8.769610, Val MSE:0.010257, Val CE:0.043365, Train ACC:1.000000, Val ACC:0.993750

Epoch 3453/4000: 100%|██████████| 1/1 [00:00<00:00, 25.02it/s]

epoch: 3452, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011618, Train KL:8.769612, Val MSE:0.010279, Val CE:0.043501, Train ACC:1.000000, Val ACC:0.993750

Epoch 3454/4000: 100%|██████████| 1/1 [00:00<00:00, 24.34it/s]

epoch: 3453, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011622, Train KL:8.769613, Val MSE:0.010283, Val CE:0.043378, Train ACC:1.000000, Val ACC:0.993750

Epoch 3455/4000: 100%|██████████| 1/1 [00:00<00:00, 24.06it/s]

epoch: 3454, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011620, Train KL:8.769615, Val MSE:0.010283, Val CE:0.043288, Train ACC:1.000000, Val ACC:0.993750

Epoch 3456/4000: 100%|██████████| 1/1 [00:00<00:00, 24.01it/s]

epoch: 3455, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011622, Train KL:8.769616, Val MSE:0.010306, Val CE:0.043509, Train ACC:1.000000, Val ACC:0.993750

Epoch 3457/4000: 100%|██████████| 1/1 [00:00<00:00, 23.56it/s]

epoch: 3456, beta = 0.000097, Train MSE: 0.006594, Train CE:0.011621, Train KL:8.769617, Val MSE:0.010278, Val CE:0.043394, Train ACC:1.000000, Val ACC:0.993750

Epoch 3458/4000: 100%|██████████| 1/1 [00:00<00:00, 19.64it/s]

epoch: 3457, beta = 0.000097, Train MSE: 0.006595, Train CE:0.011625, Train KL:8.769619, Val MSE:0.010294, Val CE:0.043426, Train ACC:1.000000, Val ACC:0.993750

Epoch 3459/4000: 100%|██████████| 1/1 [00:00<00:00, 21.83it/s]

epoch: 3458, beta = 0.000097, Train MSE: 0.006594, Train CE:0.011617, Train KL:8.769621, Val MSE:0.010289, Val CE:0.043546, Train ACC:1.000000, Val ACC:0.993750

Epoch 3460/4000: 100%|██████████| 1/1 [00:00<00:00, 23.27it/s]

epoch: 3459, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011622, Train KL:8.769622, Val MSE:0.010299, Val CE:0.043435, Train ACC:1.000000, Val ACC:0.993750

Epoch 3461/4000: 100%|██████████| 1/1 [00:00<00:00, 22.27it/s]

epoch: 3460, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011622, Train KL:8.769624, Val MSE:0.010305, Val CE:0.043451, Train ACC:1.000000, Val ACC:0.993750

Epoch 3462/4000: 100%|██████████| 1/1 [00:00<00:00, 25.78it/s]

epoch: 3461, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011616, Train KL:8.769625, Val MSE:0.010277, Val CE:0.043400, Train ACC:1.000000, Val ACC:0.993750

Epoch 3463/4000: 100%|██████████| 1/1 [00:00<00:00, 24.04it/s]

epoch: 3462, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011619, Train KL:8.769628, Val MSE:0.010298, Val CE:0.043312, Train ACC:1.000000, Val ACC:0.993750

Epoch 3464/4000: 100%|██████████| 1/1 [00:00<00:00, 24.27it/s]

epoch: 3463, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011631, Train KL:8.769628, Val MSE:0.010293, Val CE:0.043367, Train ACC:1.000000, Val ACC:0.993750

Epoch 3465/4000: 100%|██████████| 1/1 [00:00<00:00, 23.61it/s]

epoch: 3464, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011621, Train KL:8.769630, Val MSE:0.010250, Val CE:0.043454, Train ACC:1.000000, Val ACC:0.993750

Epoch 3466/4000: 100%|██████████| 1/1 [00:00<00:00, 25.74it/s]

epoch: 3465, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011619, Train KL:8.769631, Val MSE:0.010305, Val CE:0.043550, Train ACC:1.000000, Val ACC:0.993750

Epoch 3467/4000: 100%|██████████| 1/1 [00:00<00:00, 23.67it/s]

epoch: 3466, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011619, Train KL:8.769632, Val MSE:0.010242, Val CE:0.043558, Train ACC:1.000000, Val ACC:0.993750

Epoch 3468/4000: 100%|██████████| 1/1 [00:00<00:00, 25.15it/s]

epoch: 3467, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011622, Train KL:8.769635, Val MSE:0.010269, Val CE:0.043628, Train ACC:1.000000, Val ACC:0.993750

Epoch 3469/4000: 100%|██████████| 1/1 [00:00<00:00, 23.06it/s]

epoch: 3468, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011618, Train KL:8.769636, Val MSE:0.010275, Val CE:0.043510, Train ACC:1.000000, Val ACC:0.993750

Epoch 3470/4000: 100%|██████████| 1/1 [00:00<00:00, 22.29it/s]

epoch: 3469, beta = 0.000097, Train MSE: 0.006595, Train CE:0.011621, Train KL:8.769638, Val MSE:0.010290, Val CE:0.043492, Train ACC:1.000000, Val ACC:0.993750

Epoch 3471/4000: 100%|██████████| 1/1 [00:00<00:00, 25.26it/s]

epoch: 3470, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011620, Train KL:8.769639, Val MSE:0.010275, Val CE:0.043481, Train ACC:1.000000, Val ACC:0.993750

Epoch 3472/4000: 100%|██████████| 1/1 [00:00<00:00, 22.91it/s]

epoch: 3471, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011626, Train KL:8.769641, Val MSE:0.010277, Val CE:0.043517, Train ACC:1.000000, Val ACC:0.993750

Epoch 3473/4000: 100%|██████████| 1/1 [00:00<00:00, 22.41it/s]

epoch: 3472, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011625, Train KL:8.769643, Val MSE:0.010265, Val CE:0.043584, Train ACC:1.000000, Val ACC:0.993750

Epoch 3474/4000: 100%|██████████| 1/1 [00:00<00:00, 23.83it/s]

epoch: 3473, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011623, Train KL:8.769645, Val MSE:0.010261, Val CE:0.043602, Train ACC:1.000000, Val ACC:0.993750

Epoch 3475/4000: 100%|██████████| 1/1 [00:00<00:00, 21.16it/s]

epoch: 3474, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011625, Train KL:8.769646, Val MSE:0.010273, Val CE:0.043474, Train ACC:1.000000, Val ACC:0.993750

Epoch 3476/4000: 100%|██████████| 1/1 [00:00<00:00, 22.53it/s]

epoch: 3475, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011626, Train KL:8.769648, Val MSE:0.010299, Val CE:0.043473, Train ACC:1.000000, Val ACC:0.993750

Epoch 3477/4000: 100%|██████████| 1/1 [00:00<00:00, 22.86it/s]

epoch: 3476, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011622, Train KL:8.769650, Val MSE:0.010256, Val CE:0.043606, Train ACC:1.000000, Val ACC:0.993750

Epoch 3478/4000: 100%|██████████| 1/1 [00:00<00:00, 23.32it/s]

epoch: 3477, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011621, Train KL:8.769651, Val MSE:0.010270, Val CE:0.043455, Train ACC:1.000000, Val ACC:0.993750

Epoch 3479/4000: 100%|██████████| 1/1 [00:00<00:00, 24.11it/s]

epoch: 3478, beta = 0.000097, Train MSE: 0.006592, Train CE:0.011624, Train KL:8.769653, Val MSE:0.010276, Val CE:0.043495, Train ACC:1.000000, Val ACC:0.993750

Epoch 3480/4000: 100%|██████████| 1/1 [00:00<00:00, 23.70it/s]

epoch: 3479, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011625, Train KL:8.769654, Val MSE:0.010257, Val CE:0.043441, Train ACC:1.000000, Val ACC:0.993750

Epoch 3481/4000: 100%|██████████| 1/1 [00:00<00:00, 23.35it/s]

epoch: 3480, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011619, Train KL:8.769656, Val MSE:0.010283, Val CE:0.043353, Train ACC:1.000000, Val ACC:0.993750

Epoch 3482/4000: 100%|██████████| 1/1 [00:00<00:00, 23.99it/s]

epoch: 3481, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011614, Train KL:8.769659, Val MSE:0.010265, Val CE:0.043440, Train ACC:1.000000, Val ACC:0.993750

Epoch 3483/4000: 100%|██████████| 1/1 [00:00<00:00, 24.93it/s]

epoch: 3482, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011618, Train KL:8.769661, Val MSE:0.010271, Val CE:0.043414, Train ACC:1.000000, Val ACC:0.993750

Epoch 3484/4000: 100%|██████████| 1/1 [00:00<00:00, 23.95it/s]

epoch: 3483, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011624, Train KL:8.769663, Val MSE:0.010261, Val CE:0.043552, Train ACC:1.000000, Val ACC:0.993750

Epoch 3485/4000: 100%|██████████| 1/1 [00:00<00:00, 24.70it/s]

epoch: 3484, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011626, Train KL:8.769664, Val MSE:0.010266, Val CE:0.043278, Train ACC:1.000000, Val ACC:0.993750

Epoch 3486/4000: 100%|██████████| 1/1 [00:00<00:00, 20.10it/s]

epoch: 3485, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011619, Train KL:8.769666, Val MSE:0.010257, Val CE:0.043599, Train ACC:1.000000, Val ACC:0.993750

Epoch 3487/4000: 100%|██████████| 1/1 [00:00<00:00, 21.04it/s]

epoch: 3486, beta = 0.000097, Train MSE: 0.006590, Train CE:0.011617, Train KL:8.769669, Val MSE:0.010309, Val CE:0.043508, Train ACC:1.000000, Val ACC:0.993750

Epoch 3488/4000: 100%|██████████| 1/1 [00:00<00:00, 23.36it/s]

epoch: 3487, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011617, Train KL:8.769670, Val MSE:0.010281, Val CE:0.043581, Train ACC:1.000000, Val ACC:0.993750

Epoch 3489/4000: 100%|██████████| 1/1 [00:00<00:00, 23.40it/s]

epoch: 3488, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011621, Train KL:8.769670, Val MSE:0.010274, Val CE:0.043679, Train ACC:1.000000, Val ACC:0.993750

Epoch 3490/4000: 100%|██████████| 1/1 [00:00<00:00, 23.41it/s]

epoch: 3489, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011621, Train KL:8.769672, Val MSE:0.010270, Val CE:0.043490, Train ACC:1.000000, Val ACC:0.993750

Epoch 3491/4000: 100%|██████████| 1/1 [00:00<00:00, 20.92it/s]

epoch: 3490, beta = 0.000097, Train MSE: 0.006590, Train CE:0.011622, Train KL:8.769674, Val MSE:0.010278, Val CE:0.043220, Train ACC:1.000000, Val ACC:0.993750

Epoch 3492/4000: 100%|██████████| 1/1 [00:00<00:00, 24.35it/s]

epoch: 3491, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011618, Train KL:8.769676, Val MSE:0.010257, Val CE:0.043302, Train ACC:1.000000, Val ACC:0.993750

Epoch 3493/4000: 100%|██████████| 1/1 [00:00<00:00, 24.13it/s]

epoch: 3492, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011619, Train KL:8.769678, Val MSE:0.010257, Val CE:0.043575, Train ACC:1.000000, Val ACC:0.993750

Epoch 3494/4000: 100%|██████████| 1/1 [00:00<00:00, 23.87it/s]

epoch: 3493, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011625, Train KL:8.769679, Val MSE:0.010249, Val CE:0.043461, Train ACC:1.000000, Val ACC:0.993750

Epoch 3495/4000: 100%|██████████| 1/1 [00:00<00:00, 23.11it/s]

epoch: 3494, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011613, Train KL:8.769681, Val MSE:0.010317, Val CE:0.043331, Train ACC:1.000000, Val ACC:0.993750

Epoch 3496/4000: 100%|██████████| 1/1 [00:00<00:00, 23.35it/s]

epoch: 3495, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011618, Train KL:8.769682, Val MSE:0.010270, Val CE:0.043469, Train ACC:1.000000, Val ACC:0.993750

Epoch 3497/4000: 100%|██████████| 1/1 [00:00<00:00, 23.86it/s]

epoch: 3496, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011621, Train KL:8.769683, Val MSE:0.010251, Val CE:0.043320, Train ACC:1.000000, Val ACC:0.993750

Epoch 3498/4000: 100%|██████████| 1/1 [00:00<00:00, 23.63it/s]

epoch: 3497, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011620, Train KL:8.769686, Val MSE:0.010298, Val CE:0.043479, Train ACC:1.000000, Val ACC:0.993750

Epoch 3499/4000: 100%|██████████| 1/1 [00:00<00:00, 21.99it/s]

epoch: 3498, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011619, Train KL:8.769687, Val MSE:0.010274, Val CE:0.043443, Train ACC:1.000000, Val ACC:0.993750

Epoch 3500/4000: 100%|██████████| 1/1 [00:00<00:00, 19.41it/s]

epoch: 3499, beta = 0.000097, Train MSE: 0.006595, Train CE:0.011621, Train KL:8.769688, Val MSE:0.010253, Val CE:0.043371, Train ACC:1.000000, Val ACC:0.993750

Epoch 3501/4000: 100%|██████████| 1/1 [00:00<00:00, 22.85it/s]

epoch: 3500, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011623, Train KL:8.769690, Val MSE:0.010310, Val CE:0.043471, Train ACC:1.000000, Val ACC:0.993750

Epoch 3502/4000: 100%|██████████| 1/1 [00:00<00:00, 23.00it/s]

epoch: 3501, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011620, Train KL:8.769691, Val MSE:0.010258, Val CE:0.043612, Train ACC:1.000000, Val ACC:0.993750

Epoch 3503/4000: 100%|██████████| 1/1 [00:00<00:00, 21.73it/s]

epoch: 3502, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011618, Train KL:8.769692, Val MSE:0.010286, Val CE:0.043497, Train ACC:1.000000, Val ACC:0.993750

Epoch 3504/4000: 100%|██████████| 1/1 [00:00<00:00, 23.66it/s]

epoch: 3503, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011621, Train KL:8.769693, Val MSE:0.010256, Val CE:0.043291, Train ACC:1.000000, Val ACC:0.993750

Epoch 3505/4000: 100%|██████████| 1/1 [00:00<00:00, 23.86it/s]

epoch: 3504, beta = 0.000097, Train MSE: 0.006614, Train CE:0.011618, Train KL:8.769695, Val MSE:0.010266, Val CE:0.043599, Train ACC:1.000000, Val ACC:0.993750

Epoch 3506/4000: 100%|██████████| 1/1 [00:00<00:00, 22.95it/s]

epoch: 3505, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011620, Train KL:8.769697, Val MSE:0.010291, Val CE:0.043521, Train ACC:1.000000, Val ACC:0.993750

Epoch 3507/4000: 100%|██████████| 1/1 [00:00<00:00, 22.04it/s]

epoch: 3506, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011617, Train KL:8.769699, Val MSE:0.010280, Val CE:0.043550, Train ACC:1.000000, Val ACC:0.993750

Epoch 3508/4000: 100%|██████████| 1/1 [00:00<00:00, 23.57it/s]

epoch: 3507, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011629, Train KL:8.769701, Val MSE:0.010273, Val CE:0.043769, Train ACC:1.000000, Val ACC:0.993750

Epoch 3509/4000: 100%|██████████| 1/1 [00:00<00:00, 22.35it/s]

epoch: 3508, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011617, Train KL:8.769702, Val MSE:0.010283, Val CE:0.043478, Train ACC:1.000000, Val ACC:0.993750

Epoch 3510/4000: 100%|██████████| 1/1 [00:00<00:00, 23.42it/s]

epoch: 3509, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011623, Train KL:8.769704, Val MSE:0.010297, Val CE:0.043591, Train ACC:1.000000, Val ACC:0.993750

Epoch 3511/4000: 100%|██████████| 1/1 [00:00<00:00, 23.40it/s]

epoch: 3510, beta = 0.000097, Train MSE: 0.006613, Train CE:0.011617, Train KL:8.769705, Val MSE:0.010297, Val CE:0.043445, Train ACC:1.000000, Val ACC:0.993750

Epoch 3512/4000: 100%|██████████| 1/1 [00:00<00:00, 24.35it/s]

epoch: 3511, beta = 0.000097, Train MSE: 0.006593, Train CE:0.011620, Train KL:8.769707, Val MSE:0.010287, Val CE:0.043428, Train ACC:1.000000, Val ACC:0.993750

Epoch 3513/4000: 100%|██████████| 1/1 [00:00<00:00, 24.15it/s]

epoch: 3512, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011619, Train KL:8.769709, Val MSE:0.010261, Val CE:0.043552, Train ACC:1.000000, Val ACC:0.993750

Epoch 3514/4000: 100%|██████████| 1/1 [00:00<00:00, 22.86it/s]

epoch: 3513, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011616, Train KL:8.769710, Val MSE:0.010281, Val CE:0.043473, Train ACC:1.000000, Val ACC:0.993750

Epoch 3515/4000: 100%|██████████| 1/1 [00:00<00:00, 23.69it/s]

epoch: 3514, beta = 0.000097, Train MSE: 0.006592, Train CE:0.011615, Train KL:8.769712, Val MSE:0.010272, Val CE:0.043469, Train ACC:1.000000, Val ACC:0.993750

Epoch 3516/4000: 100%|██████████| 1/1 [00:00<00:00, 19.38it/s]

epoch: 3515, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011624, Train KL:8.769713, Val MSE:0.010287, Val CE:0.043717, Train ACC:1.000000, Val ACC:0.993750

Epoch 3517/4000: 100%|██████████| 1/1 [00:00<00:00, 20.06it/s]

epoch: 3516, beta = 0.000097, Train MSE: 0.006593, Train CE:0.011620, Train KL:8.769715, Val MSE:0.010269, Val CE:0.043515, Train ACC:1.000000, Val ACC:0.993750

Epoch 3518/4000: 100%|██████████| 1/1 [00:00<00:00, 25.24it/s]

epoch: 3517, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011618, Train KL:8.769716, Val MSE:0.010272, Val CE:0.043582, Train ACC:1.000000, Val ACC:0.993750

Epoch 3519/4000: 100%|██████████| 1/1 [00:00<00:00, 27.42it/s]

epoch: 3518, beta = 0.000097, Train MSE: 0.006591, Train CE:0.011618, Train KL:8.769718, Val MSE:0.010290, Val CE:0.043414, Train ACC:1.000000, Val ACC:0.993750

Epoch 3520/4000: 100%|██████████| 1/1 [00:00<00:00, 24.27it/s]

epoch: 3519, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011619, Train KL:8.769720, Val MSE:0.010292, Val CE:0.043345, Train ACC:1.000000, Val ACC:0.993750

Epoch 3521/4000: 100%|██████████| 1/1 [00:00<00:00, 23.86it/s]

epoch: 3520, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011615, Train KL:8.769722, Val MSE:0.010285, Val CE:0.043559, Train ACC:1.000000, Val ACC:0.993750

Epoch 3522/4000: 100%|██████████| 1/1 [00:00<00:00, 24.19it/s]

epoch: 3521, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011621, Train KL:8.769724, Val MSE:0.010300, Val CE:0.043465, Train ACC:1.000000, Val ACC:0.993750

Epoch 3523/4000: 100%|██████████| 1/1 [00:00<00:00, 23.91it/s]

epoch: 3522, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011621, Train KL:8.769725, Val MSE:0.010274, Val CE:0.043379, Train ACC:1.000000, Val ACC:0.993750

Epoch 3524/4000: 100%|██████████| 1/1 [00:00<00:00, 24.05it/s]

epoch: 3523, beta = 0.000097, Train MSE: 0.006593, Train CE:0.011619, Train KL:8.769727, Val MSE:0.010275, Val CE:0.043389, Train ACC:1.000000, Val ACC:0.993750

Epoch 3525/4000: 100%|██████████| 1/1 [00:00<00:00, 24.20it/s]

epoch: 3524, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011625, Train KL:8.769728, Val MSE:0.010289, Val CE:0.043613, Train ACC:1.000000, Val ACC:0.993750

Epoch 3526/4000: 100%|██████████| 1/1 [00:00<00:00, 23.46it/s]

epoch: 3525, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011621, Train KL:8.769730, Val MSE:0.010277, Val CE:0.043730, Train ACC:1.000000, Val ACC:0.993750

Epoch 3527/4000: 100%|██████████| 1/1 [00:00<00:00, 21.32it/s]

epoch: 3526, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011622, Train KL:8.769732, Val MSE:0.010300, Val CE:0.043550, Train ACC:1.000000, Val ACC:0.993750

Epoch 3528/4000: 100%|██████████| 1/1 [00:00<00:00, 24.25it/s]

epoch: 3527, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011616, Train KL:8.769732, Val MSE:0.010263, Val CE:0.043590, Train ACC:1.000000, Val ACC:0.993750

Epoch 3529/4000: 100%|██████████| 1/1 [00:00<00:00, 22.92it/s]

epoch: 3528, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011615, Train KL:8.769735, Val MSE:0.010264, Val CE:0.043548, Train ACC:1.000000, Val ACC:0.993750

Epoch 3530/4000: 100%|██████████| 1/1 [00:00<00:00, 18.21it/s]

epoch: 3529, beta = 0.000097, Train MSE: 0.006590, Train CE:0.011615, Train KL:8.769737, Val MSE:0.010253, Val CE:0.043396, Train ACC:1.000000, Val ACC:0.993750

Epoch 3531/4000: 100%|██████████| 1/1 [00:00<00:00, 21.90it/s]

epoch: 3530, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011618, Train KL:8.769739, Val MSE:0.010305, Val CE:0.043603, Train ACC:1.000000, Val ACC:0.993750

Epoch 3532/4000: 100%|██████████| 1/1 [00:00<00:00, 23.15it/s]

epoch: 3531, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011619, Train KL:8.769740, Val MSE:0.010261, Val CE:0.043276, Train ACC:1.000000, Val ACC:0.993750

Epoch 3533/4000: 100%|██████████| 1/1 [00:00<00:00, 24.16it/s]

epoch: 3532, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011617, Train KL:8.769742, Val MSE:0.010282, Val CE:0.043426, Train ACC:1.000000, Val ACC:0.993750

Epoch 3534/4000: 100%|██████████| 1/1 [00:00<00:00, 25.12it/s]

epoch: 3533, beta = 0.000097, Train MSE: 0.006590, Train CE:0.011619, Train KL:8.769743, Val MSE:0.010267, Val CE:0.043318, Train ACC:1.000000, Val ACC:0.993750

Epoch 3535/4000: 100%|██████████| 1/1 [00:00<00:00, 24.18it/s]

epoch: 3534, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011619, Train KL:8.769745, Val MSE:0.010279, Val CE:0.043666, Train ACC:1.000000, Val ACC:0.993750

Epoch 3536/4000: 100%|██████████| 1/1 [00:00<00:00, 24.60it/s]

epoch: 3535, beta = 0.000097, Train MSE: 0.006590, Train CE:0.011616, Train KL:8.769747, Val MSE:0.010263, Val CE:0.043461, Train ACC:1.000000, Val ACC:0.993750

Epoch 3537/4000: 100%|██████████| 1/1 [00:00<00:00, 21.75it/s]

epoch: 3536, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011617, Train KL:8.769747, Val MSE:0.010280, Val CE:0.043790, Train ACC:1.000000, Val ACC:0.993750

Epoch 3538/4000: 100%|██████████| 1/1 [00:00<00:00, 23.59it/s]

epoch: 3537, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011615, Train KL:8.769748, Val MSE:0.010291, Val CE:0.043359, Train ACC:1.000000, Val ACC:0.993750

Epoch 3539/4000: 100%|██████████| 1/1 [00:00<00:00, 22.53it/s]

epoch: 3538, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011617, Train KL:8.769750, Val MSE:0.010288, Val CE:0.043327, Train ACC:1.000000, Val ACC:0.993750

Epoch 3540/4000: 100%|██████████| 1/1 [00:00<00:00, 23.99it/s]

epoch: 3539, beta = 0.000097, Train MSE: 0.006594, Train CE:0.011618, Train KL:8.769751, Val MSE:0.010291, Val CE:0.043596, Train ACC:1.000000, Val ACC:0.993750

Epoch 3541/4000: 100%|██████████| 1/1 [00:00<00:00, 25.40it/s]

epoch: 3540, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011624, Train KL:8.769753, Val MSE:0.010267, Val CE:0.043405, Train ACC:1.000000, Val ACC:0.993750

Epoch 3542/4000: 100%|██████████| 1/1 [00:00<00:00, 20.57it/s]

epoch: 3541, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011621, Train KL:8.769754, Val MSE:0.010273, Val CE:0.043376, Train ACC:1.000000, Val ACC:0.993750

Epoch 3543/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 3542, beta = 0.000097, Train MSE: 0.006595, Train CE:0.011619, Train KL:8.769756, Val MSE:0.010296, Val CE:0.043621, Train ACC:1.000000, Val ACC:0.993750

Epoch 3544/4000: 100%|██████████| 1/1 [00:00<00:00, 22.85it/s]

epoch: 3543, beta = 0.000097, Train MSE: 0.006595, Train CE:0.011616, Train KL:8.769757, Val MSE:0.010251, Val CE:0.043357, Train ACC:1.000000, Val ACC:0.993750

Epoch 3545/4000: 100%|██████████| 1/1 [00:00<00:00, 22.47it/s]

epoch: 3544, beta = 0.000097, Train MSE: 0.006595, Train CE:0.011617, Train KL:8.769760, Val MSE:0.010283, Val CE:0.043500, Train ACC:1.000000, Val ACC:0.993750

Epoch 3546/4000: 100%|██████████| 1/1 [00:00<00:00, 25.17it/s]

epoch: 3545, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011618, Train KL:8.769760, Val MSE:0.010284, Val CE:0.043426, Train ACC:1.000000, Val ACC:0.993750

Epoch 3547/4000: 100%|██████████| 1/1 [00:00<00:00, 23.92it/s]

epoch: 3546, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011618, Train KL:8.769762, Val MSE:0.010271, Val CE:0.043483, Train ACC:1.000000, Val ACC:0.993750

Epoch 3548/4000: 100%|██████████| 1/1 [00:00<00:00, 24.15it/s]

epoch: 3547, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011612, Train KL:8.769765, Val MSE:0.010307, Val CE:0.043391, Train ACC:1.000000, Val ACC:0.993750

Epoch 3549/4000: 100%|██████████| 1/1 [00:00<00:00, 22.78it/s]

epoch: 3548, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011614, Train KL:8.769766, Val MSE:0.010304, Val CE:0.043672, Train ACC:1.000000, Val ACC:0.993750

Epoch 3550/4000: 100%|██████████| 1/1 [00:00<00:00, 17.96it/s]

epoch: 3549, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011615, Train KL:8.769768, Val MSE:0.010247, Val CE:0.043301, Train ACC:1.000000, Val ACC:0.993750

Epoch 3551/4000: 100%|██████████| 1/1 [00:00<00:00, 21.48it/s]

epoch: 3550, beta = 0.000097, Train MSE: 0.006591, Train CE:0.011614, Train KL:8.769770, Val MSE:0.010282, Val CE:0.043736, Train ACC:1.000000, Val ACC:0.993750

Epoch 3552/4000: 100%|██████████| 1/1 [00:00<00:00, 23.93it/s]

epoch: 3551, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011617, Train KL:8.769772, Val MSE:0.010274, Val CE:0.043378, Train ACC:1.000000, Val ACC:0.993750

Epoch 3553/4000: 100%|██████████| 1/1 [00:00<00:00, 24.06it/s]

epoch: 3552, beta = 0.000097, Train MSE: 0.006590, Train CE:0.011615, Train KL:8.769773, Val MSE:0.010248, Val CE:0.043462, Train ACC:1.000000, Val ACC:0.993750

Epoch 3554/4000: 100%|██████████| 1/1 [00:00<00:00, 23.91it/s]

epoch: 3553, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011625, Train KL:8.769773, Val MSE:0.010274, Val CE:0.043303, Train ACC:1.000000, Val ACC:0.993750

Epoch 3555/4000: 100%|██████████| 1/1 [00:00<00:00, 23.33it/s]

epoch: 3554, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011616, Train KL:8.769775, Val MSE:0.010285, Val CE:0.043676, Train ACC:1.000000, Val ACC:0.993750

Epoch 3556/4000: 100%|██████████| 1/1 [00:00<00:00, 22.98it/s]

epoch: 3555, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011618, Train KL:8.769777, Val MSE:0.010269, Val CE:0.043397, Train ACC:1.000000, Val ACC:0.993750

Epoch 3557/4000: 100%|██████████| 1/1 [00:00<00:00, 23.39it/s]

epoch: 3556, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011623, Train KL:8.769778, Val MSE:0.010260, Val CE:0.043397, Train ACC:1.000000, Val ACC:0.993750

Epoch 3558/4000: 100%|██████████| 1/1 [00:00<00:00, 23.92it/s]

epoch: 3557, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011620, Train KL:8.769780, Val MSE:0.010277, Val CE:0.043322, Train ACC:1.000000, Val ACC:0.993750

Epoch 3559/4000: 100%|██████████| 1/1 [00:00<00:00, 24.32it/s]

epoch: 3558, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011621, Train KL:8.769782, Val MSE:0.010279, Val CE:0.043536, Train ACC:1.000000, Val ACC:0.993750

Epoch 3560/4000: 100%|██████████| 1/1 [00:00<00:00, 23.06it/s]

epoch: 3559, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011612, Train KL:8.769785, Val MSE:0.010274, Val CE:0.043317, Train ACC:1.000000, Val ACC:0.993750

Epoch 3561/4000: 100%|██████████| 1/1 [00:00<00:00, 18.00it/s]

epoch: 3560, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011614, Train KL:8.769786, Val MSE:0.010263, Val CE:0.043538, Train ACC:1.000000, Val ACC:0.993750

Epoch 3562/4000: 100%|██████████| 1/1 [00:00<00:00, 23.03it/s]

epoch: 3561, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011620, Train KL:8.769788, Val MSE:0.010279, Val CE:0.043306, Train ACC:1.000000, Val ACC:0.993750

Epoch 3563/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 3562, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011622, Train KL:8.769790, Val MSE:0.010281, Val CE:0.043566, Train ACC:1.000000, Val ACC:0.993750

Epoch 3564/4000: 100%|██████████| 1/1 [00:00<00:00, 23.02it/s]

epoch: 3563, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011625, Train KL:8.769792, Val MSE:0.010296, Val CE:0.043568, Train ACC:1.000000, Val ACC:0.993750

Epoch 3565/4000: 100%|██████████| 1/1 [00:00<00:00, 24.12it/s]

epoch: 3564, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011619, Train KL:8.769794, Val MSE:0.010273, Val CE:0.043295, Train ACC:1.000000, Val ACC:0.993750

Epoch 3566/4000: 100%|██████████| 1/1 [00:00<00:00, 24.82it/s]

epoch: 3565, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011617, Train KL:8.769795, Val MSE:0.010309, Val CE:0.043708, Train ACC:1.000000, Val ACC:0.993750

Epoch 3567/4000: 100%|██████████| 1/1 [00:00<00:00, 24.60it/s]

epoch: 3566, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011618, Train KL:8.769797, Val MSE:0.010270, Val CE:0.043529, Train ACC:1.000000, Val ACC:0.993750

Epoch 3568/4000: 100%|██████████| 1/1 [00:00<00:00, 23.20it/s]

epoch: 3567, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011621, Train KL:8.769798, Val MSE:0.010269, Val CE:0.043621, Train ACC:1.000000, Val ACC:0.993750

Epoch 3569/4000: 100%|██████████| 1/1 [00:00<00:00, 24.51it/s]

epoch: 3568, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011617, Train KL:8.769800, Val MSE:0.010295, Val CE:0.043540, Train ACC:1.000000, Val ACC:0.993750

Epoch 3570/4000: 100%|██████████| 1/1 [00:00<00:00, 22.71it/s]

epoch: 3569, beta = 0.000097, Train MSE: 0.006591, Train CE:0.011626, Train KL:8.769802, Val MSE:0.010277, Val CE:0.043589, Train ACC:1.000000, Val ACC:0.993750

Epoch 3571/4000: 100%|██████████| 1/1 [00:00<00:00, 22.92it/s]

epoch: 3570, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011625, Train KL:8.769804, Val MSE:0.010273, Val CE:0.043519, Train ACC:1.000000, Val ACC:0.993750

Epoch 3572/4000: 100%|██████████| 1/1 [00:00<00:00, 23.49it/s]

epoch: 3571, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011622, Train KL:8.769806, Val MSE:0.010287, Val CE:0.043334, Train ACC:1.000000, Val ACC:0.993750

Epoch 3573/4000: 100%|██████████| 1/1 [00:00<00:00, 22.74it/s]

epoch: 3572, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011615, Train KL:8.769808, Val MSE:0.010308, Val CE:0.043426, Train ACC:1.000000, Val ACC:0.993750

Epoch 3574/4000: 100%|██████████| 1/1 [00:00<00:00, 18.76it/s]

epoch: 3573, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011617, Train KL:8.769809, Val MSE:0.010283, Val CE:0.043392, Train ACC:1.000000, Val ACC:0.993750

Epoch 3575/4000: 100%|██████████| 1/1 [00:00<00:00, 18.76it/s]

epoch: 3574, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011612, Train KL:8.769811, Val MSE:0.010294, Val CE:0.043438, Train ACC:1.000000, Val ACC:0.993750

Epoch 3576/4000: 100%|██████████| 1/1 [00:00<00:00, 22.97it/s]

epoch: 3575, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011616, Train KL:8.769813, Val MSE:0.010273, Val CE:0.043517, Train ACC:1.000000, Val ACC:0.993750

Epoch 3577/4000: 100%|██████████| 1/1 [00:00<00:00, 22.29it/s]

epoch: 3576, beta = 0.000097, Train MSE: 0.006592, Train CE:0.011616, Train KL:8.769814, Val MSE:0.010273, Val CE:0.043306, Train ACC:1.000000, Val ACC:0.993750

Epoch 3578/4000: 100%|██████████| 1/1 [00:00<00:00, 24.36it/s]

epoch: 3577, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011617, Train KL:8.769816, Val MSE:0.010299, Val CE:0.043601, Train ACC:1.000000, Val ACC:0.993750

Epoch 3579/4000: 100%|██████████| 1/1 [00:00<00:00, 24.67it/s]

epoch: 3578, beta = 0.000097, Train MSE: 0.006591, Train CE:0.011620, Train KL:8.769817, Val MSE:0.010266, Val CE:0.043478, Train ACC:1.000000, Val ACC:0.993750

Epoch 3580/4000: 100%|██████████| 1/1 [00:00<00:00, 24.17it/s]

epoch: 3579, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011617, Train KL:8.769819, Val MSE:0.010265, Val CE:0.043553, Train ACC:1.000000, Val ACC:0.993750

Epoch 3581/4000: 100%|██████████| 1/1 [00:00<00:00, 23.73it/s]

epoch: 3580, beta = 0.000097, Train MSE: 0.006611, Train CE:0.011619, Train KL:8.769821, Val MSE:0.010296, Val CE:0.043551, Train ACC:1.000000, Val ACC:0.993750

Epoch 3582/4000: 100%|██████████| 1/1 [00:00<00:00, 25.24it/s]

epoch: 3581, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011616, Train KL:8.769822, Val MSE:0.010274, Val CE:0.043569, Train ACC:1.000000, Val ACC:0.993750

Epoch 3583/4000: 100%|██████████| 1/1 [00:00<00:00, 24.12it/s]

epoch: 3582, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011615, Train KL:8.769824, Val MSE:0.010294, Val CE:0.043378, Train ACC:1.000000, Val ACC:0.993750

Epoch 3584/4000: 100%|██████████| 1/1 [00:00<00:00, 26.86it/s]

epoch: 3583, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011618, Train KL:8.769826, Val MSE:0.010271, Val CE:0.043463, Train ACC:1.000000, Val ACC:0.993750

Epoch 3585/4000: 100%|██████████| 1/1 [00:00<00:00, 23.92it/s]

epoch: 3584, beta = 0.000097, Train MSE: 0.006590, Train CE:0.011616, Train KL:8.769828, Val MSE:0.010300, Val CE:0.043479, Train ACC:1.000000, Val ACC:0.993750

Epoch 3586/4000: 100%|██████████| 1/1 [00:00<00:00, 27.15it/s]

epoch: 3585, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011618, Train KL:8.769829, Val MSE:0.010292, Val CE:0.043542, Train ACC:1.000000, Val ACC:0.993750

Epoch 3587/4000: 100%|██████████| 1/1 [00:00<00:00, 24.59it/s]

epoch: 3586, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011620, Train KL:8.769831, Val MSE:0.010299, Val CE:0.043386, Train ACC:1.000000, Val ACC:0.993750

Epoch 3588/4000: 100%|██████████| 1/1 [00:00<00:00, 23.12it/s]

epoch: 3587, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011621, Train KL:8.769832, Val MSE:0.010257, Val CE:0.043371, Train ACC:1.000000, Val ACC:0.993750

Epoch 3589/4000: 100%|██████████| 1/1 [00:00<00:00, 23.36it/s]

epoch: 3588, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011617, Train KL:8.769834, Val MSE:0.010267, Val CE:0.043319, Train ACC:1.000000, Val ACC:0.993750

Epoch 3590/4000: 100%|██████████| 1/1 [00:00<00:00, 22.81it/s]

epoch: 3589, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011613, Train KL:8.769835, Val MSE:0.010275, Val CE:0.043558, Train ACC:1.000000, Val ACC:0.993750

Epoch 3591/4000: 100%|██████████| 1/1 [00:00<00:00, 24.44it/s]

epoch: 3590, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011619, Train KL:8.769835, Val MSE:0.010259, Val CE:0.043305, Train ACC:1.000000, Val ACC:0.993750

Epoch 3592/4000: 100%|██████████| 1/1 [00:00<00:00, 18.12it/s]

epoch: 3591, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011616, Train KL:8.769838, Val MSE:0.010258, Val CE:0.043414, Train ACC:1.000000, Val ACC:0.993750

Epoch 3593/4000: 100%|██████████| 1/1 [00:00<00:00, 20.29it/s]

epoch: 3592, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011624, Train KL:8.769839, Val MSE:0.010256, Val CE:0.043521, Train ACC:1.000000, Val ACC:0.993750

Epoch 3594/4000: 100%|██████████| 1/1 [00:00<00:00, 21.91it/s]

epoch: 3593, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011618, Train KL:8.769841, Val MSE:0.010277, Val CE:0.043512, Train ACC:1.000000, Val ACC:0.993750

Epoch 3595/4000: 100%|██████████| 1/1 [00:00<00:00, 23.76it/s]

epoch: 3594, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011617, Train KL:8.769843, Val MSE:0.010302, Val CE:0.043534, Train ACC:1.000000, Val ACC:0.993750

Epoch 3596/4000: 100%|██████████| 1/1 [00:00<00:00, 24.13it/s]

epoch: 3595, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011618, Train KL:8.769844, Val MSE:0.010291, Val CE:0.043364, Train ACC:1.000000, Val ACC:0.993750

Epoch 3597/4000: 100%|██████████| 1/1 [00:00<00:00, 23.53it/s]

epoch: 3596, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011627, Train KL:8.769847, Val MSE:0.010267, Val CE:0.043355, Train ACC:1.000000, Val ACC:0.993750

Epoch 3598/4000: 100%|██████████| 1/1 [00:00<00:00, 23.56it/s]

epoch: 3597, beta = 0.000097, Train MSE: 0.006595, Train CE:0.011614, Train KL:8.769849, Val MSE:0.010262, Val CE:0.043467, Train ACC:1.000000, Val ACC:0.993750

Epoch 3599/4000: 100%|██████████| 1/1 [00:00<00:00, 23.53it/s]

epoch: 3598, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011616, Train KL:8.769851, Val MSE:0.010279, Val CE:0.043714, Train ACC:1.000000, Val ACC:0.993750

Epoch 3600/4000: 100%|██████████| 1/1 [00:00<00:00, 21.98it/s]

epoch: 3599, beta = 0.000097, Train MSE: 0.006593, Train CE:0.011616, Train KL:8.769853, Val MSE:0.010266, Val CE:0.043566, Train ACC:1.000000, Val ACC:0.993750

Epoch 3601/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 3600, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011618, Train KL:8.769854, Val MSE:0.010265, Val CE:0.043417, Train ACC:1.000000, Val ACC:0.993750

Epoch 3602/4000: 100%|██████████| 1/1 [00:00<00:00, 24.50it/s]

epoch: 3601, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011616, Train KL:8.769856, Val MSE:0.010282, Val CE:0.043520, Train ACC:1.000000, Val ACC:0.993750

Epoch 3603/4000: 100%|██████████| 1/1 [00:00<00:00, 24.15it/s]

epoch: 3602, beta = 0.000097, Train MSE: 0.006594, Train CE:0.011610, Train KL:8.769857, Val MSE:0.010283, Val CE:0.043585, Train ACC:1.000000, Val ACC:0.993750

Epoch 3604/4000: 100%|██████████| 1/1 [00:00<00:00, 24.48it/s]

epoch: 3603, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011617, Train KL:8.769858, Val MSE:0.010278, Val CE:0.043645, Train ACC:1.000000, Val ACC:0.993750

Epoch 3605/4000: 100%|██████████| 1/1 [00:00<00:00, 23.49it/s]

epoch: 3604, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011621, Train KL:8.769861, Val MSE:0.010279, Val CE:0.043490, Train ACC:1.000000, Val ACC:0.993750

Epoch 3606/4000: 100%|██████████| 1/1 [00:00<00:00, 20.11it/s]

epoch: 3605, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011618, Train KL:8.769862, Val MSE:0.010276, Val CE:0.043363, Train ACC:1.000000, Val ACC:0.993750

Epoch 3607/4000: 100%|██████████| 1/1 [00:00<00:00, 22.76it/s]

epoch: 3606, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011626, Train KL:8.769864, Val MSE:0.010282, Val CE:0.043439, Train ACC:1.000000, Val ACC:0.993750

Epoch 3608/4000: 100%|██████████| 1/1 [00:00<00:00, 23.13it/s]

epoch: 3607, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011614, Train KL:8.769866, Val MSE:0.010273, Val CE:0.043289, Train ACC:1.000000, Val ACC:0.993750

Epoch 3609/4000: 100%|██████████| 1/1 [00:00<00:00, 24.02it/s]

epoch: 3608, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011617, Train KL:8.769868, Val MSE:0.010261, Val CE:0.043464, Train ACC:1.000000, Val ACC:0.993750

Epoch 3610/4000: 100%|██████████| 1/1 [00:00<00:00, 22.81it/s]

epoch: 3609, beta = 0.000097, Train MSE: 0.006591, Train CE:0.011615, Train KL:8.769870, Val MSE:0.010308, Val CE:0.043534, Train ACC:1.000000, Val ACC:0.993750

Epoch 3611/4000: 100%|██████████| 1/1 [00:00<00:00, 24.09it/s]

epoch: 3610, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011619, Train KL:8.769871, Val MSE:0.010270, Val CE:0.043411, Train ACC:1.000000, Val ACC:0.993750

Epoch 3612/4000: 100%|██████████| 1/1 [00:00<00:00, 23.61it/s]

epoch: 3611, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011618, Train KL:8.769874, Val MSE:0.010272, Val CE:0.043523, Train ACC:1.000000, Val ACC:0.993750

Epoch 3613/4000: 100%|██████████| 1/1 [00:00<00:00, 22.70it/s]

epoch: 3612, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011618, Train KL:8.769875, Val MSE:0.010305, Val CE:0.043453, Train ACC:1.000000, Val ACC:0.993750

Epoch 3614/4000: 100%|██████████| 1/1 [00:00<00:00, 23.67it/s]

epoch: 3613, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011614, Train KL:8.769876, Val MSE:0.010294, Val CE:0.043683, Train ACC:1.000000, Val ACC:0.993750

Epoch 3615/4000: 100%|██████████| 1/1 [00:00<00:00, 24.99it/s]

epoch: 3614, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011616, Train KL:8.769877, Val MSE:0.010291, Val CE:0.043407, Train ACC:1.000000, Val ACC:0.993750

Epoch 3616/4000: 100%|██████████| 1/1 [00:00<00:00, 23.40it/s]

epoch: 3615, beta = 0.000097, Train MSE: 0.006595, Train CE:0.011619, Train KL:8.769879, Val MSE:0.010272, Val CE:0.043421, Train ACC:1.000000, Val ACC:0.993750

Epoch 3617/4000: 100%|██████████| 1/1 [00:00<00:00, 23.35it/s]

epoch: 3616, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011621, Train KL:8.769881, Val MSE:0.010264, Val CE:0.043524, Train ACC:1.000000, Val ACC:0.993750

Epoch 3618/4000: 100%|██████████| 1/1 [00:00<00:00, 20.04it/s]

epoch: 3617, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011617, Train KL:8.769882, Val MSE:0.010278, Val CE:0.043379, Train ACC:1.000000, Val ACC:0.993750

Epoch 3619/4000: 100%|██████████| 1/1 [00:00<00:00, 19.92it/s]

epoch: 3618, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011620, Train KL:8.769885, Val MSE:0.010258, Val CE:0.043519, Train ACC:1.000000, Val ACC:0.993750

Epoch 3620/4000: 100%|██████████| 1/1 [00:00<00:00, 21.93it/s]

epoch: 3619, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011617, Train KL:8.769886, Val MSE:0.010277, Val CE:0.043358, Train ACC:1.000000, Val ACC:0.993750

Epoch 3621/4000: 100%|██████████| 1/1 [00:00<00:00, 23.99it/s]

epoch: 3620, beta = 0.000097, Train MSE: 0.006595, Train CE:0.011619, Train KL:8.769888, Val MSE:0.010274, Val CE:0.043621, Train ACC:1.000000, Val ACC:0.993750

Epoch 3622/4000: 100%|██████████| 1/1 [00:00<00:00, 23.94it/s]

epoch: 3621, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011613, Train KL:8.769890, Val MSE:0.010285, Val CE:0.043486, Train ACC:1.000000, Val ACC:0.993750

Epoch 3623/4000: 100%|██████████| 1/1 [00:00<00:00, 24.02it/s]

epoch: 3622, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011614, Train KL:8.769892, Val MSE:0.010277, Val CE:0.043380, Train ACC:1.000000, Val ACC:0.993750

Epoch 3624/4000: 100%|██████████| 1/1 [00:00<00:00, 25.26it/s]

epoch: 3623, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011622, Train KL:8.769893, Val MSE:0.010271, Val CE:0.043476, Train ACC:1.000000, Val ACC:0.993750

Epoch 3625/4000: 100%|██████████| 1/1 [00:00<00:00, 23.00it/s]

epoch: 3624, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011619, Train KL:8.769896, Val MSE:0.010295, Val CE:0.043497, Train ACC:1.000000, Val ACC:0.993750

Epoch 3626/4000: 100%|██████████| 1/1 [00:00<00:00, 23.07it/s]

epoch: 3625, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011616, Train KL:8.769897, Val MSE:0.010291, Val CE:0.043646, Train ACC:1.000000, Val ACC:0.993750

Epoch 3627/4000: 100%|██████████| 1/1 [00:00<00:00, 24.21it/s]

epoch: 3626, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011616, Train KL:8.769899, Val MSE:0.010244, Val CE:0.043427, Train ACC:1.000000, Val ACC:0.993750

Epoch 3628/4000: 100%|██████████| 1/1 [00:00<00:00, 22.58it/s]

epoch: 3627, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011618, Train KL:8.769900, Val MSE:0.010261, Val CE:0.043358, Train ACC:1.000000, Val ACC:0.993750

Epoch 3629/4000: 100%|██████████| 1/1 [00:00<00:00, 23.54it/s]

epoch: 3628, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011621, Train KL:8.769902, Val MSE:0.010288, Val CE:0.043301, Train ACC:1.000000, Val ACC:0.993750

Epoch 3630/4000: 100%|██████████| 1/1 [00:00<00:00, 23.93it/s]

epoch: 3629, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011620, Train KL:8.769904, Val MSE:0.010263, Val CE:0.043309, Train ACC:1.000000, Val ACC:0.993750

Epoch 3631/4000: 100%|██████████| 1/1 [00:00<00:00, 20.60it/s]

epoch: 3630, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011622, Train KL:8.769906, Val MSE:0.010273, Val CE:0.043560, Train ACC:1.000000, Val ACC:0.993750

Epoch 3632/4000: 100%|██████████| 1/1 [00:00<00:00, 23.41it/s]

epoch: 3631, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011613, Train KL:8.769909, Val MSE:0.010271, Val CE:0.043570, Train ACC:1.000000, Val ACC:0.993750

Epoch 3633/4000: 100%|██████████| 1/1 [00:00<00:00, 24.63it/s]

epoch: 3632, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011618, Train KL:8.769910, Val MSE:0.010278, Val CE:0.043322, Train ACC:1.000000, Val ACC:0.993750

Epoch 3634/4000: 100%|██████████| 1/1 [00:00<00:00, 23.84it/s]

epoch: 3633, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011617, Train KL:8.769912, Val MSE:0.010282, Val CE:0.043234, Train ACC:1.000000, Val ACC:0.993750

Epoch 3635/4000: 100%|██████████| 1/1 [00:00<00:00, 27.02it/s]

epoch: 3634, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011617, Train KL:8.769914, Val MSE:0.010263, Val CE:0.043355, Train ACC:1.000000, Val ACC:0.993750

Epoch 3636/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 3635, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011619, Train KL:8.769916, Val MSE:0.010316, Val CE:0.043344, Train ACC:1.000000, Val ACC:0.993750

Epoch 3637/4000: 100%|██████████| 1/1 [00:00<00:00, 23.33it/s]

epoch: 3636, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011611, Train KL:8.769917, Val MSE:0.010290, Val CE:0.043423, Train ACC:1.000000, Val ACC:0.993750

Epoch 3638/4000: 100%|██████████| 1/1 [00:00<00:00, 23.94it/s]

epoch: 3637, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011617, Train KL:8.769919, Val MSE:0.010238, Val CE:0.043529, Train ACC:1.000000, Val ACC:0.993750

Epoch 3639/4000: 100%|██████████| 1/1 [00:00<00:00, 23.25it/s]

epoch: 3638, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011616, Train KL:8.769920, Val MSE:0.010246, Val CE:0.043382, Train ACC:1.000000, Val ACC:0.993750

Epoch 3640/4000: 100%|██████████| 1/1 [00:00<00:00, 22.52it/s]

epoch: 3639, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011615, Train KL:8.769923, Val MSE:0.010270, Val CE:0.043362, Train ACC:1.000000, Val ACC:0.993750

Epoch 3641/4000: 100%|██████████| 1/1 [00:00<00:00, 24.21it/s]

epoch: 3640, beta = 0.000097, Train MSE: 0.006595, Train CE:0.011621, Train KL:8.769925, Val MSE:0.010249, Val CE:0.043524, Train ACC:1.000000, Val ACC:0.993750

Epoch 3642/4000: 100%|██████████| 1/1 [00:00<00:00, 23.81it/s]

epoch: 3641, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011618, Train KL:8.769927, Val MSE:0.010288, Val CE:0.043684, Train ACC:1.000000, Val ACC:0.993750

Epoch 3643/4000: 100%|██████████| 1/1 [00:00<00:00, 22.84it/s]

epoch: 3642, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011614, Train KL:8.769928, Val MSE:0.010255, Val CE:0.043558, Train ACC:1.000000, Val ACC:0.993750

Epoch 3644/4000: 100%|██████████| 1/1 [00:00<00:00, 24.97it/s]

epoch: 3643, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011619, Train KL:8.769930, Val MSE:0.010286, Val CE:0.043471, Train ACC:1.000000, Val ACC:0.993750

Epoch 3645/4000: 100%|██████████| 1/1 [00:00<00:00, 21.87it/s]

epoch: 3644, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011617, Train KL:8.769932, Val MSE:0.010296, Val CE:0.043508, Train ACC:1.000000, Val ACC:0.993750

Epoch 3646/4000: 100%|██████████| 1/1 [00:00<00:00, 23.48it/s]

epoch: 3645, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011616, Train KL:8.769935, Val MSE:0.010278, Val CE:0.043423, Train ACC:1.000000, Val ACC:0.993750

Epoch 3647/4000: 100%|██████████| 1/1 [00:00<00:00, 18.86it/s]

epoch: 3646, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011619, Train KL:8.769936, Val MSE:0.010274, Val CE:0.043421, Train ACC:1.000000, Val ACC:0.993750

Epoch 3648/4000: 100%|██████████| 1/1 [00:00<00:00, 21.68it/s]

epoch: 3647, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011610, Train KL:8.769938, Val MSE:0.010270, Val CE:0.043662, Train ACC:1.000000, Val ACC:0.993750

Epoch 3649/4000: 100%|██████████| 1/1 [00:00<00:00, 22.75it/s]

epoch: 3648, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011616, Train KL:8.769939, Val MSE:0.010264, Val CE:0.043607, Train ACC:1.000000, Val ACC:0.993750

Epoch 3650/4000: 100%|██████████| 1/1 [00:00<00:00, 23.54it/s]

epoch: 3649, beta = 0.000097, Train MSE: 0.006591, Train CE:0.011621, Train KL:8.769941, Val MSE:0.010272, Val CE:0.043342, Train ACC:1.000000, Val ACC:0.993750

Epoch 3651/4000: 100%|██████████| 1/1 [00:00<00:00, 23.73it/s]

epoch: 3650, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011620, Train KL:8.769943, Val MSE:0.010309, Val CE:0.043358, Train ACC:1.000000, Val ACC:0.993750

Epoch 3652/4000: 100%|██████████| 1/1 [00:00<00:00, 23.76it/s]

epoch: 3651, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011623, Train KL:8.769945, Val MSE:0.010241, Val CE:0.043450, Train ACC:1.000000, Val ACC:0.993750

Epoch 3653/4000: 100%|██████████| 1/1 [00:00<00:00, 23.98it/s]

epoch: 3652, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011621, Train KL:8.769947, Val MSE:0.010283, Val CE:0.043440, Train ACC:1.000000, Val ACC:0.993750

Epoch 3654/4000: 100%|██████████| 1/1 [00:00<00:00, 23.37it/s]

epoch: 3653, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011616, Train KL:8.769948, Val MSE:0.010270, Val CE:0.043498, Train ACC:1.000000, Val ACC:0.993750

Epoch 3655/4000: 100%|██████████| 1/1 [00:00<00:00, 23.96it/s]

epoch: 3654, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011615, Train KL:8.769951, Val MSE:0.010262, Val CE:0.043445, Train ACC:1.000000, Val ACC:0.993750

Epoch 3656/4000: 100%|██████████| 1/1 [00:00<00:00, 24.08it/s]

epoch: 3655, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011613, Train KL:8.769952, Val MSE:0.010263, Val CE:0.043505, Train ACC:1.000000, Val ACC:0.993750

Epoch 3657/4000: 100%|██████████| 1/1 [00:00<00:00, 23.69it/s]

epoch: 3656, beta = 0.000097, Train MSE: 0.006593, Train CE:0.011611, Train KL:8.769955, Val MSE:0.010288, Val CE:0.043465, Train ACC:1.000000, Val ACC:0.993750

Epoch 3658/4000: 100%|██████████| 1/1 [00:00<00:00, 24.54it/s]

epoch: 3657, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011616, Train KL:8.769957, Val MSE:0.010283, Val CE:0.043491, Train ACC:1.000000, Val ACC:0.993750

Epoch 3659/4000: 100%|██████████| 1/1 [00:00<00:00, 21.63it/s]

epoch: 3658, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011616, Train KL:8.769958, Val MSE:0.010262, Val CE:0.043388, Train ACC:1.000000, Val ACC:0.993750

Epoch 3660/4000: 100%|██████████| 1/1 [00:00<00:00, 23.50it/s]

epoch: 3659, beta = 0.000097, Train MSE: 0.006588, Train CE:0.011614, Train KL:8.769958, Val MSE:0.010269, Val CE:0.043514, Train ACC:1.000000, Val ACC:0.993750

Epoch 3661/4000: 100%|██████████| 1/1 [00:00<00:00, 29.00it/s]

epoch: 3660, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011619, Train KL:8.769960, Val MSE:0.010265, Val CE:0.043342, Train ACC:1.000000, Val ACC:0.993750

Epoch 3662/4000: 100%|██████████| 1/1 [00:00<00:00, 24.51it/s]

epoch: 3661, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011617, Train KL:8.769962, Val MSE:0.010297, Val CE:0.043543, Train ACC:1.000000, Val ACC:0.993750

Epoch 3663/4000: 100%|██████████| 1/1 [00:00<00:00, 24.11it/s]

epoch: 3662, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011623, Train KL:8.769964, Val MSE:0.010288, Val CE:0.043523, Train ACC:1.000000, Val ACC:0.993750

Epoch 3664/4000: 100%|██████████| 1/1 [00:00<00:00, 23.62it/s]

epoch: 3663, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011609, Train KL:8.769966, Val MSE:0.010253, Val CE:0.043507, Train ACC:1.000000, Val ACC:0.993750

Epoch 3665/4000: 100%|██████████| 1/1 [00:00<00:00, 19.06it/s]

epoch: 3664, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011612, Train KL:8.769967, Val MSE:0.010234, Val CE:0.043650, Train ACC:1.000000, Val ACC:0.993750

Epoch 3666/4000: 100%|██████████| 1/1 [00:00<00:00, 23.96it/s]

epoch: 3665, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011616, Train KL:8.769970, Val MSE:0.010246, Val CE:0.043345, Train ACC:1.000000, Val ACC:0.993750

Epoch 3667/4000: 100%|██████████| 1/1 [00:00<00:00, 24.03it/s]

epoch: 3666, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011617, Train KL:8.769971, Val MSE:0.010262, Val CE:0.043500, Train ACC:1.000000, Val ACC:0.993750

Epoch 3668/4000: 100%|██████████| 1/1 [00:00<00:00, 24.03it/s]

epoch: 3667, beta = 0.000097, Train MSE: 0.006595, Train CE:0.011623, Train KL:8.769973, Val MSE:0.010287, Val CE:0.043775, Train ACC:1.000000, Val ACC:0.993750

Epoch 3669/4000: 100%|██████████| 1/1 [00:00<00:00, 23.38it/s]

epoch: 3668, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011614, Train KL:8.769974, Val MSE:0.010272, Val CE:0.043646, Train ACC:1.000000, Val ACC:0.993750

Epoch 3670/4000: 100%|██████████| 1/1 [00:00<00:00, 24.85it/s]

epoch: 3669, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011616, Train KL:8.769976, Val MSE:0.010295, Val CE:0.043353, Train ACC:1.000000, Val ACC:0.993750

Epoch 3671/4000: 100%|██████████| 1/1 [00:00<00:00, 24.33it/s]

epoch: 3670, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011615, Train KL:8.769978, Val MSE:0.010287, Val CE:0.043580, Train ACC:1.000000, Val ACC:0.993750

Epoch 3672/4000: 100%|██████████| 1/1 [00:00<00:00, 22.38it/s]

epoch: 3671, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011610, Train KL:8.769979, Val MSE:0.010267, Val CE:0.043465, Train ACC:1.000000, Val ACC:0.993750

Epoch 3673/4000: 100%|██████████| 1/1 [00:00<00:00, 25.67it/s]

epoch: 3672, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011616, Train KL:8.769981, Val MSE:0.010290, Val CE:0.043449, Train ACC:1.000000, Val ACC:0.993750

Epoch 3674/4000: 100%|██████████| 1/1 [00:00<00:00, 23.32it/s]

epoch: 3673, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011621, Train KL:8.769983, Val MSE:0.010294, Val CE:0.043506, Train ACC:1.000000, Val ACC:0.993750

Epoch 3675/4000: 100%|██████████| 1/1 [00:00<00:00, 23.36it/s]

epoch: 3674, beta = 0.000097, Train MSE: 0.006589, Train CE:0.011618, Train KL:8.769985, Val MSE:0.010279, Val CE:0.043532, Train ACC:1.000000, Val ACC:0.993750

Epoch 3676/4000: 100%|██████████| 1/1 [00:00<00:00, 23.52it/s]

epoch: 3675, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011610, Train KL:8.769987, Val MSE:0.010262, Val CE:0.043523, Train ACC:1.000000, Val ACC:0.993750

Epoch 3677/4000: 100%|██████████| 1/1 [00:00<00:00, 23.37it/s]

epoch: 3676, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011614, Train KL:8.769989, Val MSE:0.010273, Val CE:0.043646, Train ACC:1.000000, Val ACC:0.993750

Epoch 3678/4000: 100%|██████████| 1/1 [00:00<00:00, 23.59it/s]

epoch: 3677, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011611, Train KL:8.769991, Val MSE:0.010258, Val CE:0.043521, Train ACC:1.000000, Val ACC:0.993750

Epoch 3679/4000: 100%|██████████| 1/1 [00:00<00:00, 22.85it/s]

epoch: 3678, beta = 0.000097, Train MSE: 0.006612, Train CE:0.011621, Train KL:8.769992, Val MSE:0.010288, Val CE:0.043467, Train ACC:1.000000, Val ACC:0.993750

Epoch 3680/4000: 100%|██████████| 1/1 [00:00<00:00, 20.40it/s]

epoch: 3679, beta = 0.000097, Train MSE: 0.006592, Train CE:0.011611, Train KL:8.769993, Val MSE:0.010241, Val CE:0.043589, Train ACC:1.000000, Val ACC:0.993750

Epoch 3681/4000: 100%|██████████| 1/1 [00:00<00:00, 23.28it/s]

epoch: 3680, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011613, Train KL:8.769996, Val MSE:0.010280, Val CE:0.043381, Train ACC:1.000000, Val ACC:0.993750

Epoch 3682/4000: 100%|██████████| 1/1 [00:00<00:00, 19.78it/s]

epoch: 3681, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011615, Train KL:8.769997, Val MSE:0.010302, Val CE:0.043399, Train ACC:1.000000, Val ACC:0.993750

Epoch 3683/4000: 100%|██████████| 1/1 [00:00<00:00, 27.94it/s]

epoch: 3682, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011615, Train KL:8.769999, Val MSE:0.010272, Val CE:0.043420, Train ACC:1.000000, Val ACC:0.993750

Epoch 3684/4000: 100%|██████████| 1/1 [00:00<00:00, 23.82it/s]

epoch: 3683, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011621, Train KL:8.770000, Val MSE:0.010253, Val CE:0.043622, Train ACC:1.000000, Val ACC:0.993750

Epoch 3685/4000: 100%|██████████| 1/1 [00:00<00:00, 24.17it/s]

epoch: 3684, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011616, Train KL:8.770003, Val MSE:0.010264, Val CE:0.043456, Train ACC:1.000000, Val ACC:0.993750

Epoch 3686/4000: 100%|██████████| 1/1 [00:00<00:00, 23.90it/s]

epoch: 3685, beta = 0.000097, Train MSE: 0.006593, Train CE:0.011611, Train KL:8.770004, Val MSE:0.010249, Val CE:0.043470, Train ACC:1.000000, Val ACC:0.993750

Epoch 3687/4000: 100%|██████████| 1/1 [00:00<00:00, 24.11it/s]

epoch: 3686, beta = 0.000097, Train MSE: 0.006592, Train CE:0.011621, Train KL:8.770006, Val MSE:0.010268, Val CE:0.043431, Train ACC:1.000000, Val ACC:0.993750

Epoch 3688/4000: 100%|██████████| 1/1 [00:00<00:00, 22.26it/s]

epoch: 3687, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011615, Train KL:8.770008, Val MSE:0.010269, Val CE:0.043478, Train ACC:1.000000, Val ACC:0.993750

Epoch 3689/4000: 100%|██████████| 1/1 [00:00<00:00, 23.97it/s]

epoch: 3688, beta = 0.000097, Train MSE: 0.006595, Train CE:0.011611, Train KL:8.770010, Val MSE:0.010298, Val CE:0.043379, Train ACC:1.000000, Val ACC:0.993750

Epoch 3690/4000: 100%|██████████| 1/1 [00:00<00:00, 24.69it/s]

epoch: 3689, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011615, Train KL:8.770012, Val MSE:0.010268, Val CE:0.043370, Train ACC:1.000000, Val ACC:0.993750

Epoch 3691/4000: 100%|██████████| 1/1 [00:00<00:00, 23.20it/s]

epoch: 3690, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011618, Train KL:8.770014, Val MSE:0.010287, Val CE:0.043577, Train ACC:1.000000, Val ACC:0.993750

Epoch 3692/4000: 100%|██████████| 1/1 [00:00<00:00, 17.99it/s]

epoch: 3691, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011618, Train KL:8.770016, Val MSE:0.010283, Val CE:0.043538, Train ACC:1.000000, Val ACC:0.993750

Epoch 3693/4000: 100%|██████████| 1/1 [00:00<00:00, 21.81it/s]

epoch: 3692, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011619, Train KL:8.770017, Val MSE:0.010286, Val CE:0.043570, Train ACC:1.000000, Val ACC:0.993750

Epoch 3694/4000: 100%|██████████| 1/1 [00:00<00:00, 24.48it/s]

epoch: 3693, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011614, Train KL:8.770019, Val MSE:0.010268, Val CE:0.043439, Train ACC:1.000000, Val ACC:0.993750

Epoch 3695/4000: 100%|██████████| 1/1 [00:00<00:00, 21.86it/s]

epoch: 3694, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011616, Train KL:8.770020, Val MSE:0.010280, Val CE:0.043491, Train ACC:1.000000, Val ACC:0.993750

Epoch 3696/4000: 100%|██████████| 1/1 [00:00<00:00, 23.96it/s]

epoch: 3695, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011610, Train KL:8.770021, Val MSE:0.010286, Val CE:0.043449, Train ACC:1.000000, Val ACC:0.993750

Epoch 3697/4000: 100%|██████████| 1/1 [00:00<00:00, 25.38it/s]

epoch: 3696, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011614, Train KL:8.770024, Val MSE:0.010285, Val CE:0.043656, Train ACC:1.000000, Val ACC:0.993750

Epoch 3698/4000: 100%|██████████| 1/1 [00:00<00:00, 25.75it/s]

epoch: 3697, beta = 0.000097, Train MSE: 0.006595, Train CE:0.011615, Train KL:8.770026, Val MSE:0.010287, Val CE:0.043446, Train ACC:1.000000, Val ACC:0.993750

Epoch 3699/4000: 100%|██████████| 1/1 [00:00<00:00, 23.67it/s]

epoch: 3698, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011620, Train KL:8.770028, Val MSE:0.010282, Val CE:0.043366, Train ACC:1.000000, Val ACC:0.993750

Epoch 3700/4000: 100%|██████████| 1/1 [00:00<00:00, 27.47it/s]

epoch: 3699, beta = 0.000097, Train MSE: 0.006595, Train CE:0.011618, Train KL:8.770030, Val MSE:0.010282, Val CE:0.043484, Train ACC:1.000000, Val ACC:0.993750

Epoch 3701/4000: 100%|██████████| 1/1 [00:00<00:00, 24.13it/s]

epoch: 3700, beta = 0.000097, Train MSE: 0.006593, Train CE:0.011620, Train KL:8.770032, Val MSE:0.010276, Val CE:0.043408, Train ACC:1.000000, Val ACC:0.993750

Epoch 3702/4000: 100%|██████████| 1/1 [00:00<00:00, 24.21it/s]

epoch: 3701, beta = 0.000097, Train MSE: 0.006594, Train CE:0.011615, Train KL:8.770034, Val MSE:0.010285, Val CE:0.043387, Train ACC:1.000000, Val ACC:0.993750

Epoch 3703/4000: 100%|██████████| 1/1 [00:00<00:00, 26.06it/s]

epoch: 3702, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011617, Train KL:8.770036, Val MSE:0.010288, Val CE:0.043626, Train ACC:1.000000, Val ACC:0.993750

Epoch 3704/4000: 100%|██████████| 1/1 [00:00<00:00, 23.71it/s]

epoch: 3703, beta = 0.000097, Train MSE: 0.006591, Train CE:0.011614, Train KL:8.770038, Val MSE:0.010284, Val CE:0.043408, Train ACC:1.000000, Val ACC:0.993750

Epoch 3705/4000: 100%|██████████| 1/1 [00:00<00:00, 23.69it/s]

epoch: 3704, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011622, Train KL:8.770040, Val MSE:0.010298, Val CE:0.043481, Train ACC:1.000000, Val ACC:0.993750

Epoch 3706/4000: 100%|██████████| 1/1 [00:00<00:00, 22.96it/s]

epoch: 3705, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011617, Train KL:8.770041, Val MSE:0.010291, Val CE:0.043433, Train ACC:1.000000, Val ACC:0.993750

Epoch 3707/4000: 100%|██████████| 1/1 [00:00<00:00, 17.81it/s]

epoch: 3706, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011618, Train KL:8.770043, Val MSE:0.010269, Val CE:0.043513, Train ACC:1.000000, Val ACC:0.993750

Epoch 3708/4000: 100%|██████████| 1/1 [00:00<00:00, 18.71it/s]

epoch: 3707, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011615, Train KL:8.770045, Val MSE:0.010265, Val CE:0.043591, Train ACC:1.000000, Val ACC:0.993750

Epoch 3709/4000: 100%|██████████| 1/1 [00:00<00:00, 26.89it/s]

epoch: 3708, beta = 0.000097, Train MSE: 0.006587, Train CE:0.011618, Train KL:8.770047, Val MSE:0.010316, Val CE:0.043452, Train ACC:1.000000, Val ACC:0.993750

Epoch 3710/4000: 100%|██████████| 1/1 [00:00<00:00, 27.98it/s]

epoch: 3709, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011615, Train KL:8.770047, Val MSE:0.010275, Val CE:0.043517, Train ACC:1.000000, Val ACC:0.993750

Epoch 3711/4000: 100%|██████████| 1/1 [00:00<00:00, 23.85it/s]

epoch: 3710, beta = 0.000097, Train MSE: 0.006593, Train CE:0.011616, Train KL:8.770049, Val MSE:0.010241, Val CE:0.043421, Train ACC:1.000000, Val ACC:0.993750

Epoch 3712/4000: 100%|██████████| 1/1 [00:00<00:00, 24.37it/s]

epoch: 3711, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011617, Train KL:8.770052, Val MSE:0.010266, Val CE:0.043582, Train ACC:1.000000, Val ACC:0.993750

Epoch 3713/4000: 100%|██████████| 1/1 [00:00<00:00, 23.06it/s]

epoch: 3712, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011615, Train KL:8.770054, Val MSE:0.010243, Val CE:0.043568, Train ACC:1.000000, Val ACC:0.993750

Epoch 3714/4000: 100%|██████████| 1/1 [00:00<00:00, 24.61it/s]

epoch: 3713, beta = 0.000097, Train MSE: 0.006594, Train CE:0.011621, Train KL:8.770055, Val MSE:0.010275, Val CE:0.043449, Train ACC:1.000000, Val ACC:0.993750

Epoch 3715/4000: 100%|██████████| 1/1 [00:00<00:00, 27.78it/s]

epoch: 3714, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011614, Train KL:8.770057, Val MSE:0.010278, Val CE:0.043542, Train ACC:1.000000, Val ACC:0.993750

Epoch 3716/4000: 100%|██████████| 1/1 [00:00<00:00, 23.99it/s]

epoch: 3715, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011612, Train KL:8.770059, Val MSE:0.010291, Val CE:0.043446, Train ACC:1.000000, Val ACC:0.993750

Epoch 3717/4000: 100%|██████████| 1/1 [00:00<00:00, 23.26it/s]

epoch: 3716, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011620, Train KL:8.770060, Val MSE:0.010271, Val CE:0.043242, Train ACC:1.000000, Val ACC:0.993750

Epoch 3718/4000: 100%|██████████| 1/1 [00:00<00:00, 26.10it/s]

epoch: 3717, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011615, Train KL:8.770062, Val MSE:0.010277, Val CE:0.043716, Train ACC:1.000000, Val ACC:0.993750

Epoch 3719/4000: 100%|██████████| 1/1 [00:00<00:00, 23.43it/s]

epoch: 3718, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011617, Train KL:8.770064, Val MSE:0.010285, Val CE:0.043535, Train ACC:1.000000, Val ACC:0.993750

Epoch 3720/4000: 100%|██████████| 1/1 [00:00<00:00, 24.04it/s]

epoch: 3719, beta = 0.000097, Train MSE: 0.006593, Train CE:0.011610, Train KL:8.770066, Val MSE:0.010283, Val CE:0.043277, Train ACC:1.000000, Val ACC:0.993750

Epoch 3721/4000: 100%|██████████| 1/1 [00:00<00:00, 22.90it/s]

epoch: 3720, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011621, Train KL:8.770068, Val MSE:0.010275, Val CE:0.043603, Train ACC:1.000000, Val ACC:0.993750

Epoch 3722/4000: 100%|██████████| 1/1 [00:00<00:00, 24.59it/s]

epoch: 3721, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011614, Train KL:8.770070, Val MSE:0.010282, Val CE:0.043454, Train ACC:1.000000, Val ACC:0.993750

Epoch 3723/4000: 100%|██████████| 1/1 [00:00<00:00, 24.04it/s]

epoch: 3722, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011610, Train KL:8.770072, Val MSE:0.010270, Val CE:0.043582, Train ACC:1.000000, Val ACC:0.993750

Epoch 3724/4000: 100%|██████████| 1/1 [00:00<00:00, 21.94it/s]

epoch: 3723, beta = 0.000097, Train MSE: 0.006589, Train CE:0.011612, Train KL:8.770074, Val MSE:0.010262, Val CE:0.043548, Train ACC:1.000000, Val ACC:0.993750

Epoch 3725/4000: 100%|██████████| 1/1 [00:00<00:00, 20.94it/s]

epoch: 3724, beta = 0.000097, Train MSE: 0.006592, Train CE:0.011608, Train KL:8.770075, Val MSE:0.010267, Val CE:0.043345, Train ACC:1.000000, Val ACC:0.993750

Epoch 3726/4000: 100%|██████████| 1/1 [00:00<00:00, 21.54it/s]

epoch: 3725, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011609, Train KL:8.770078, Val MSE:0.010296, Val CE:0.043401, Train ACC:1.000000, Val ACC:0.993750

Epoch 3727/4000: 100%|██████████| 1/1 [00:00<00:00, 24.37it/s]

epoch: 3726, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011613, Train KL:8.770079, Val MSE:0.010279, Val CE:0.043539, Train ACC:1.000000, Val ACC:0.993750

Epoch 3728/4000: 100%|██████████| 1/1 [00:00<00:00, 26.42it/s]

epoch: 3727, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011617, Train KL:8.770082, Val MSE:0.010262, Val CE:0.043492, Train ACC:1.000000, Val ACC:0.993750

Epoch 3729/4000: 100%|██████████| 1/1 [00:00<00:00, 23.61it/s]

epoch: 3728, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011611, Train KL:8.770082, Val MSE:0.010249, Val CE:0.043594, Train ACC:1.000000, Val ACC:0.993750

Epoch 3730/4000: 100%|██████████| 1/1 [00:00<00:00, 23.80it/s]

epoch: 3729, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011612, Train KL:8.770085, Val MSE:0.010269, Val CE:0.043548, Train ACC:1.000000, Val ACC:0.993750

Epoch 3731/4000: 100%|██████████| 1/1 [00:00<00:00, 24.36it/s]

epoch: 3730, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011611, Train KL:8.770086, Val MSE:0.010279, Val CE:0.043374, Train ACC:1.000000, Val ACC:0.993750

Epoch 3732/4000: 100%|██████████| 1/1 [00:00<00:00, 24.57it/s]

epoch: 3731, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011614, Train KL:8.770088, Val MSE:0.010266, Val CE:0.043643, Train ACC:1.000000, Val ACC:0.993750

Epoch 3733/4000: 100%|██████████| 1/1 [00:00<00:00, 24.22it/s]

epoch: 3732, beta = 0.000097, Train MSE: 0.006591, Train CE:0.011617, Train KL:8.770089, Val MSE:0.010270, Val CE:0.043498, Train ACC:1.000000, Val ACC:0.993750

Epoch 3734/4000: 100%|██████████| 1/1 [00:00<00:00, 24.44it/s]

epoch: 3733, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011611, Train KL:8.770092, Val MSE:0.010275, Val CE:0.043421, Train ACC:1.000000, Val ACC:0.993750

Epoch 3735/4000: 100%|██████████| 1/1 [00:00<00:00, 25.79it/s]

epoch: 3734, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011614, Train KL:8.770093, Val MSE:0.010277, Val CE:0.043180, Train ACC:1.000000, Val ACC:0.993750

Epoch 3736/4000: 100%|██████████| 1/1 [00:00<00:00, 23.28it/s]

epoch: 3735, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011617, Train KL:8.770095, Val MSE:0.010278, Val CE:0.043360, Train ACC:1.000000, Val ACC:0.993750

Epoch 3737/4000: 100%|██████████| 1/1 [00:00<00:00, 24.05it/s]

epoch: 3736, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011618, Train KL:8.770097, Val MSE:0.010285, Val CE:0.043320, Train ACC:1.000000, Val ACC:0.993750

Epoch 3738/4000: 100%|██████████| 1/1 [00:00<00:00, 22.97it/s]

epoch: 3737, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011617, Train KL:8.770100, Val MSE:0.010280, Val CE:0.043525, Train ACC:1.000000, Val ACC:0.993750

Epoch 3739/4000: 100%|██████████| 1/1 [00:00<00:00, 24.78it/s]

epoch: 3738, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011616, Train KL:8.770101, Val MSE:0.010254, Val CE:0.043548, Train ACC:1.000000, Val ACC:0.993750

Epoch 3740/4000: 100%|██████████| 1/1 [00:00<00:00, 17.54it/s]

epoch: 3739, beta = 0.000097, Train MSE: 0.006595, Train CE:0.011617, Train KL:8.770103, Val MSE:0.010258, Val CE:0.043549, Train ACC:1.000000, Val ACC:0.993750

Epoch 3741/4000: 100%|██████████| 1/1 [00:00<00:00, 21.89it/s]

epoch: 3740, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011614, Train KL:8.770104, Val MSE:0.010301, Val CE:0.043484, Train ACC:1.000000, Val ACC:0.993750

Epoch 3742/4000: 100%|██████████| 1/1 [00:00<00:00, 20.74it/s]

epoch: 3741, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011618, Train KL:8.770106, Val MSE:0.010287, Val CE:0.043452, Train ACC:1.000000, Val ACC:0.993750

Epoch 3743/4000: 100%|██████████| 1/1 [00:00<00:00, 23.08it/s]

epoch: 3742, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011614, Train KL:8.770108, Val MSE:0.010264, Val CE:0.043700, Train ACC:1.000000, Val ACC:0.993750

Epoch 3744/4000: 100%|██████████| 1/1 [00:00<00:00, 21.98it/s]

epoch: 3743, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011618, Train KL:8.770110, Val MSE:0.010257, Val CE:0.043385, Train ACC:1.000000, Val ACC:0.993750

Epoch 3745/4000: 100%|██████████| 1/1 [00:00<00:00, 24.19it/s]

epoch: 3744, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011612, Train KL:8.770112, Val MSE:0.010266, Val CE:0.043532, Train ACC:1.000000, Val ACC:0.993750

Epoch 3746/4000: 100%|██████████| 1/1 [00:00<00:00, 24.02it/s]

epoch: 3745, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011614, Train KL:8.770115, Val MSE:0.010267, Val CE:0.043335, Train ACC:1.000000, Val ACC:0.993750

Epoch 3747/4000: 100%|██████████| 1/1 [00:00<00:00, 22.76it/s]

epoch: 3746, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011609, Train KL:8.770116, Val MSE:0.010294, Val CE:0.043759, Train ACC:1.000000, Val ACC:0.993750

Epoch 3748/4000: 100%|██████████| 1/1 [00:00<00:00, 23.61it/s]

epoch: 3747, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011607, Train KL:8.770118, Val MSE:0.010258, Val CE:0.043274, Train ACC:1.000000, Val ACC:0.993750

Epoch 3749/4000: 100%|██████████| 1/1 [00:00<00:00, 24.04it/s]

epoch: 3748, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011617, Train KL:8.770120, Val MSE:0.010243, Val CE:0.043778, Train ACC:1.000000, Val ACC:0.993750

Epoch 3750/4000: 100%|██████████| 1/1 [00:00<00:00, 27.02it/s]

epoch: 3749, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011613, Train KL:8.770121, Val MSE:0.010260, Val CE:0.043651, Train ACC:1.000000, Val ACC:0.993750

Epoch 3751/4000: 100%|██████████| 1/1 [00:00<00:00, 23.75it/s]

epoch: 3750, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011612, Train KL:8.770123, Val MSE:0.010295, Val CE:0.043480, Train ACC:1.000000, Val ACC:0.993750

Epoch 3752/4000: 100%|██████████| 1/1 [00:00<00:00, 24.11it/s]

epoch: 3751, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011608, Train KL:8.770125, Val MSE:0.010267, Val CE:0.043786, Train ACC:1.000000, Val ACC:0.993750

Epoch 3753/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 3752, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011618, Train KL:8.770127, Val MSE:0.010257, Val CE:0.043472, Train ACC:1.000000, Val ACC:0.993750

Epoch 3754/4000: 100%|██████████| 1/1 [00:00<00:00, 23.69it/s]

epoch: 3753, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011608, Train KL:8.770128, Val MSE:0.010294, Val CE:0.043590, Train ACC:1.000000, Val ACC:0.993750

Epoch 3755/4000: 100%|██████████| 1/1 [00:00<00:00, 24.15it/s]

epoch: 3754, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011615, Train KL:8.770131, Val MSE:0.010292, Val CE:0.043325, Train ACC:1.000000, Val ACC:0.993750

Epoch 3756/4000: 100%|██████████| 1/1 [00:00<00:00, 19.58it/s]

epoch: 3755, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011616, Train KL:8.770132, Val MSE:0.010283, Val CE:0.043593, Train ACC:1.000000, Val ACC:0.993750

Epoch 3757/4000: 100%|██████████| 1/1 [00:00<00:00, 17.96it/s]

epoch: 3756, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011610, Train KL:8.770135, Val MSE:0.010308, Val CE:0.043456, Train ACC:1.000000, Val ACC:0.993750

Epoch 3758/4000: 100%|██████████| 1/1 [00:00<00:00, 22.75it/s]

epoch: 3757, beta = 0.000097, Train MSE: 0.006592, Train CE:0.011622, Train KL:8.770136, Val MSE:0.010287, Val CE:0.043581, Train ACC:1.000000, Val ACC:0.993750

Epoch 3759/4000: 100%|██████████| 1/1 [00:00<00:00, 23.97it/s]

epoch: 3758, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011610, Train KL:8.770138, Val MSE:0.010280, Val CE:0.043435, Train ACC:1.000000, Val ACC:0.993750

Epoch 3760/4000: 100%|██████████| 1/1 [00:00<00:00, 22.82it/s]

epoch: 3759, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011616, Train KL:8.770140, Val MSE:0.010270, Val CE:0.043542, Train ACC:1.000000, Val ACC:0.993750

Epoch 3761/4000: 100%|██████████| 1/1 [00:00<00:00, 23.99it/s]

epoch: 3760, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011617, Train KL:8.770142, Val MSE:0.010281, Val CE:0.043712, Train ACC:1.000000, Val ACC:0.993750

Epoch 3762/4000: 100%|██████████| 1/1 [00:00<00:00, 22.76it/s]

epoch: 3761, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011614, Train KL:8.770144, Val MSE:0.010271, Val CE:0.043508, Train ACC:1.000000, Val ACC:0.993750

Epoch 3763/4000: 100%|██████████| 1/1 [00:00<00:00, 23.02it/s]

epoch: 3762, beta = 0.000097, Train MSE: 0.006592, Train CE:0.011613, Train KL:8.770146, Val MSE:0.010251, Val CE:0.043645, Train ACC:1.000000, Val ACC:0.993750

Epoch 3764/4000: 100%|██████████| 1/1 [00:00<00:00, 23.59it/s]

epoch: 3763, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011608, Train KL:8.770148, Val MSE:0.010306, Val CE:0.043644, Train ACC:1.000000, Val ACC:0.993229

Epoch 3765/4000: 100%|██████████| 1/1 [00:00<00:00, 23.91it/s]

epoch: 3764, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011610, Train KL:8.770150, Val MSE:0.010263, Val CE:0.043376, Train ACC:1.000000, Val ACC:0.993750

Epoch 3766/4000: 100%|██████████| 1/1 [00:00<00:00, 24.03it/s]

epoch: 3765, beta = 0.000097, Train MSE: 0.006590, Train CE:0.011619, Train KL:8.770152, Val MSE:0.010263, Val CE:0.043167, Train ACC:1.000000, Val ACC:0.993750

Epoch 3767/4000: 100%|██████████| 1/1 [00:00<00:00, 21.00it/s]

epoch: 3766, beta = 0.000097, Train MSE: 0.006587, Train CE:0.011612, Train KL:8.770154, Val MSE:0.010298, Val CE:0.043299, Train ACC:1.000000, Val ACC:0.993750

Epoch 3768/4000: 100%|██████████| 1/1 [00:00<00:00, 16.63it/s]

epoch: 3767, beta = 0.000097, Train MSE: 0.006593, Train CE:0.011612, Train KL:8.770156, Val MSE:0.010266, Val CE:0.043236, Train ACC:1.000000, Val ACC:0.993750

Epoch 3769/4000: 100%|██████████| 1/1 [00:00<00:00, 22.95it/s]

epoch: 3768, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011614, Train KL:8.770158, Val MSE:0.010292, Val CE:0.043700, Train ACC:1.000000, Val ACC:0.993750

Epoch 3770/4000: 100%|██████████| 1/1 [00:00<00:00, 22.89it/s]

epoch: 3769, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011616, Train KL:8.770159, Val MSE:0.010250, Val CE:0.043541, Train ACC:1.000000, Val ACC:0.993750

Epoch 3771/4000: 100%|██████████| 1/1 [00:00<00:00, 22.79it/s]

epoch: 3770, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011612, Train KL:8.770163, Val MSE:0.010267, Val CE:0.043399, Train ACC:1.000000, Val ACC:0.993750

Epoch 3772/4000: 100%|██████████| 1/1 [00:00<00:00, 24.10it/s]

epoch: 3771, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011614, Train KL:8.770164, Val MSE:0.010266, Val CE:0.043581, Train ACC:1.000000, Val ACC:0.993750

Epoch 3773/4000: 100%|██████████| 1/1 [00:00<00:00, 22.87it/s]

epoch: 3772, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011618, Train KL:8.770165, Val MSE:0.010280, Val CE:0.043506, Train ACC:1.000000, Val ACC:0.993750

Epoch 3774/4000: 100%|██████████| 1/1 [00:00<00:00, 24.52it/s]

epoch: 3773, beta = 0.000097, Train MSE: 0.006594, Train CE:0.011617, Train KL:8.770167, Val MSE:0.010311, Val CE:0.043383, Train ACC:1.000000, Val ACC:0.993750

Epoch 3775/4000: 100%|██████████| 1/1 [00:00<00:00, 23.99it/s]

epoch: 3774, beta = 0.000097, Train MSE: 0.006592, Train CE:0.011614, Train KL:8.770170, Val MSE:0.010278, Val CE:0.043295, Train ACC:1.000000, Val ACC:0.993750

Epoch 3776/4000: 100%|██████████| 1/1 [00:00<00:00, 23.84it/s]

epoch: 3775, beta = 0.000097, Train MSE: 0.006589, Train CE:0.011613, Train KL:8.770172, Val MSE:0.010268, Val CE:0.043271, Train ACC:1.000000, Val ACC:0.993750

Epoch 3777/4000: 100%|██████████| 1/1 [00:00<00:00, 23.96it/s]

epoch: 3776, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011612, Train KL:8.770174, Val MSE:0.010265, Val CE:0.043693, Train ACC:1.000000, Val ACC:0.993750

Epoch 3778/4000: 100%|██████████| 1/1 [00:00<00:00, 21.81it/s]

epoch: 3777, beta = 0.000097, Train MSE: 0.006593, Train CE:0.011617, Train KL:8.770176, Val MSE:0.010258, Val CE:0.043561, Train ACC:1.000000, Val ACC:0.993750

Epoch 3779/4000: 100%|██████████| 1/1 [00:00<00:00, 20.46it/s]

epoch: 3778, beta = 0.000097, Train MSE: 0.006595, Train CE:0.011616, Train KL:8.770178, Val MSE:0.010283, Val CE:0.043504, Train ACC:1.000000, Val ACC:0.993750

Epoch 3780/4000: 100%|██████████| 1/1 [00:00<00:00, 22.07it/s]

epoch: 3779, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011611, Train KL:8.770179, Val MSE:0.010281, Val CE:0.043252, Train ACC:1.000000, Val ACC:0.993750

Epoch 3781/4000: 100%|██████████| 1/1 [00:00<00:00, 23.79it/s]

epoch: 3780, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011613, Train KL:8.770181, Val MSE:0.010259, Val CE:0.043194, Train ACC:1.000000, Val ACC:0.993750

Epoch 3782/4000: 100%|██████████| 1/1 [00:00<00:00, 24.54it/s]

epoch: 3781, beta = 0.000097, Train MSE: 0.006589, Train CE:0.011610, Train KL:8.770183, Val MSE:0.010285, Val CE:0.043380, Train ACC:1.000000, Val ACC:0.993750

Epoch 3783/4000: 100%|██████████| 1/1 [00:00<00:00, 24.27it/s]

epoch: 3782, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011610, Train KL:8.770185, Val MSE:0.010282, Val CE:0.043644, Train ACC:1.000000, Val ACC:0.993750

Epoch 3784/4000: 100%|██████████| 1/1 [00:00<00:00, 25.07it/s]

epoch: 3783, beta = 0.000097, Train MSE: 0.006593, Train CE:0.011613, Train KL:8.770186, Val MSE:0.010275, Val CE:0.043563, Train ACC:1.000000, Val ACC:0.993750

Epoch 3785/4000: 100%|██████████| 1/1 [00:00<00:00, 24.07it/s]

epoch: 3784, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011615, Train KL:8.770188, Val MSE:0.010270, Val CE:0.043568, Train ACC:1.000000, Val ACC:0.993750

Epoch 3786/4000: 100%|██████████| 1/1 [00:00<00:00, 23.94it/s]

epoch: 3785, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011616, Train KL:8.770189, Val MSE:0.010248, Val CE:0.043524, Train ACC:1.000000, Val ACC:0.993750

Epoch 3787/4000: 100%|██████████| 1/1 [00:00<00:00, 23.70it/s]

epoch: 3786, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011614, Train KL:8.770192, Val MSE:0.010260, Val CE:0.043510, Train ACC:1.000000, Val ACC:0.993750

Epoch 3788/4000: 100%|██████████| 1/1 [00:00<00:00, 23.32it/s]

epoch: 3787, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011614, Train KL:8.770193, Val MSE:0.010316, Val CE:0.043470, Train ACC:1.000000, Val ACC:0.993750

Epoch 3789/4000: 100%|██████████| 1/1 [00:00<00:00, 25.68it/s]

epoch: 3788, beta = 0.000097, Train MSE: 0.006592, Train CE:0.011616, Train KL:8.770195, Val MSE:0.010281, Val CE:0.043566, Train ACC:1.000000, Val ACC:0.993750

Epoch 3790/4000: 100%|██████████| 1/1 [00:00<00:00, 24.21it/s]

epoch: 3789, beta = 0.000097, Train MSE: 0.006589, Train CE:0.011611, Train KL:8.770197, Val MSE:0.010280, Val CE:0.043354, Train ACC:1.000000, Val ACC:0.993750

Epoch 3791/4000: 100%|██████████| 1/1 [00:00<00:00, 27.73it/s]

epoch: 3790, beta = 0.000097, Train MSE: 0.006592, Train CE:0.011610, Train KL:8.770200, Val MSE:0.010268, Val CE:0.043419, Train ACC:1.000000, Val ACC:0.993750

Epoch 3792/4000: 100%|██████████| 1/1 [00:00<00:00, 24.24it/s]

epoch: 3791, beta = 0.000097, Train MSE: 0.006594, Train CE:0.011612, Train KL:8.770202, Val MSE:0.010278, Val CE:0.043539, Train ACC:1.000000, Val ACC:0.993750

Epoch 3793/4000: 100%|██████████| 1/1 [00:00<00:00, 23.74it/s]

epoch: 3792, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011610, Train KL:8.770204, Val MSE:0.010274, Val CE:0.043430, Train ACC:1.000000, Val ACC:0.993750

Epoch 3794/4000: 100%|██████████| 1/1 [00:00<00:00, 26.15it/s]

epoch: 3793, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011612, Train KL:8.770205, Val MSE:0.010246, Val CE:0.043408, Train ACC:1.000000, Val ACC:0.993750

Epoch 3795/4000: 100%|██████████| 1/1 [00:00<00:00, 21.06it/s]

epoch: 3794, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011615, Train KL:8.770206, Val MSE:0.010295, Val CE:0.043458, Train ACC:1.000000, Val ACC:0.993750

Epoch 3796/4000: 100%|██████████| 1/1 [00:00<00:00, 21.57it/s]

epoch: 3795, beta = 0.000097, Train MSE: 0.006592, Train CE:0.011613, Train KL:8.770208, Val MSE:0.010283, Val CE:0.043548, Train ACC:1.000000, Val ACC:0.993750

Epoch 3797/4000: 100%|██████████| 1/1 [00:00<00:00, 23.84it/s]

epoch: 3796, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011613, Train KL:8.770210, Val MSE:0.010284, Val CE:0.043687, Train ACC:1.000000, Val ACC:0.993750

Epoch 3798/4000: 100%|██████████| 1/1 [00:00<00:00, 23.91it/s]

epoch: 3797, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011611, Train KL:8.770211, Val MSE:0.010283, Val CE:0.043520, Train ACC:1.000000, Val ACC:0.993750

Epoch 3799/4000: 100%|██████████| 1/1 [00:00<00:00, 22.31it/s]

epoch: 3798, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011609, Train KL:8.770213, Val MSE:0.010280, Val CE:0.043627, Train ACC:1.000000, Val ACC:0.993750

Epoch 3800/4000: 100%|██████████| 1/1 [00:00<00:00, 21.43it/s]

epoch: 3799, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011616, Train KL:8.770215, Val MSE:0.010284, Val CE:0.043430, Train ACC:1.000000, Val ACC:0.993750

Epoch 3801/4000: 100%|██████████| 1/1 [00:00<00:00, 22.87it/s]

epoch: 3800, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011613, Train KL:8.770217, Val MSE:0.010288, Val CE:0.043727, Train ACC:1.000000, Val ACC:0.993750

Epoch 3802/4000: 100%|██████████| 1/1 [00:00<00:00, 22.69it/s]

epoch: 3801, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011611, Train KL:8.770219, Val MSE:0.010276, Val CE:0.043539, Train ACC:1.000000, Val ACC:0.993750

Epoch 3803/4000: 100%|██████████| 1/1 [00:00<00:00, 22.70it/s]

epoch: 3802, beta = 0.000097, Train MSE: 0.006588, Train CE:0.011613, Train KL:8.770220, Val MSE:0.010257, Val CE:0.043454, Train ACC:1.000000, Val ACC:0.993750

Epoch 3804/4000: 100%|██████████| 1/1 [00:00<00:00, 23.51it/s]

epoch: 3803, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011609, Train KL:8.770222, Val MSE:0.010284, Val CE:0.043419, Train ACC:1.000000, Val ACC:0.993750

Epoch 3805/4000: 100%|██████████| 1/1 [00:00<00:00, 22.12it/s]

epoch: 3804, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011613, Train KL:8.770224, Val MSE:0.010304, Val CE:0.043272, Train ACC:1.000000, Val ACC:0.993750

Epoch 3806/4000: 100%|██████████| 1/1 [00:00<00:00, 24.38it/s]

epoch: 3805, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011617, Train KL:8.770226, Val MSE:0.010279, Val CE:0.043426, Train ACC:1.000000, Val ACC:0.993750

Epoch 3807/4000: 100%|██████████| 1/1 [00:00<00:00, 24.09it/s]

epoch: 3806, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011613, Train KL:8.770227, Val MSE:0.010273, Val CE:0.043318, Train ACC:1.000000, Val ACC:0.993750

Epoch 3808/4000: 100%|██████████| 1/1 [00:00<00:00, 22.86it/s]

epoch: 3807, beta = 0.000097, Train MSE: 0.006589, Train CE:0.011616, Train KL:8.770229, Val MSE:0.010273, Val CE:0.043406, Train ACC:1.000000, Val ACC:0.993750

Epoch 3809/4000: 100%|██████████| 1/1 [00:00<00:00, 23.53it/s]

epoch: 3808, beta = 0.000097, Train MSE: 0.006595, Train CE:0.011613, Train KL:8.770231, Val MSE:0.010260, Val CE:0.043561, Train ACC:1.000000, Val ACC:0.993750

Epoch 3810/4000: 100%|██████████| 1/1 [00:00<00:00, 24.08it/s]

epoch: 3809, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011607, Train KL:8.770232, Val MSE:0.010286, Val CE:0.043516, Train ACC:1.000000, Val ACC:0.993750

Epoch 3811/4000: 100%|██████████| 1/1 [00:00<00:00, 23.58it/s]

epoch: 3810, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011611, Train KL:8.770235, Val MSE:0.010302, Val CE:0.043657, Train ACC:1.000000, Val ACC:0.993750

Epoch 3812/4000: 100%|██████████| 1/1 [00:00<00:00, 23.49it/s]

epoch: 3811, beta = 0.000097, Train MSE: 0.006588, Train CE:0.011614, Train KL:8.770237, Val MSE:0.010245, Val CE:0.043505, Train ACC:1.000000, Val ACC:0.993750

Epoch 3813/4000: 100%|██████████| 1/1 [00:00<00:00, 19.79it/s]

epoch: 3812, beta = 0.000097, Train MSE: 0.006589, Train CE:0.011612, Train KL:8.770239, Val MSE:0.010298, Val CE:0.043730, Train ACC:1.000000, Val ACC:0.993750

Epoch 3814/4000: 100%|██████████| 1/1 [00:00<00:00, 21.91it/s]

epoch: 3813, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011610, Train KL:8.770240, Val MSE:0.010265, Val CE:0.043602, Train ACC:1.000000, Val ACC:0.993750

Epoch 3815/4000: 100%|██████████| 1/1 [00:00<00:00, 27.10it/s]

epoch: 3814, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011608, Train KL:8.770243, Val MSE:0.010269, Val CE:0.043578, Train ACC:1.000000, Val ACC:0.993750

Epoch 3816/4000: 100%|██████████| 1/1 [00:00<00:00, 24.03it/s]

epoch: 3815, beta = 0.000097, Train MSE: 0.006586, Train CE:0.011607, Train KL:8.770245, Val MSE:0.010269, Val CE:0.043566, Train ACC:1.000000, Val ACC:0.993750

Epoch 3817/4000: 100%|██████████| 1/1 [00:00<00:00, 23.61it/s]

epoch: 3816, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011615, Train KL:8.770247, Val MSE:0.010299, Val CE:0.043541, Train ACC:1.000000, Val ACC:0.993750

Epoch 3818/4000: 100%|██████████| 1/1 [00:00<00:00, 23.69it/s]

epoch: 3817, beta = 0.000097, Train MSE: 0.006594, Train CE:0.011613, Train KL:8.770247, Val MSE:0.010282, Val CE:0.043775, Train ACC:1.000000, Val ACC:0.993750

Epoch 3819/4000: 100%|██████████| 1/1 [00:00<00:00, 23.27it/s]

epoch: 3818, beta = 0.000097, Train MSE: 0.006595, Train CE:0.011610, Train KL:8.770250, Val MSE:0.010252, Val CE:0.043617, Train ACC:1.000000, Val ACC:0.993750

Epoch 3820/4000: 100%|██████████| 1/1 [00:00<00:00, 26.09it/s]

epoch: 3819, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011608, Train KL:8.770251, Val MSE:0.010252, Val CE:0.043564, Train ACC:1.000000, Val ACC:0.993750

Epoch 3821/4000: 100%|██████████| 1/1 [00:00<00:00, 23.99it/s]

epoch: 3820, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011614, Train KL:8.770253, Val MSE:0.010275, Val CE:0.043395, Train ACC:1.000000, Val ACC:0.993750

Epoch 3822/4000: 100%|██████████| 1/1 [00:00<00:00, 22.51it/s]

epoch: 3821, beta = 0.000097, Train MSE: 0.006588, Train CE:0.011609, Train KL:8.770255, Val MSE:0.010282, Val CE:0.043654, Train ACC:1.000000, Val ACC:0.993750

Epoch 3823/4000: 100%|██████████| 1/1 [00:00<00:00, 23.67it/s]

epoch: 3822, beta = 0.000097, Train MSE: 0.006594, Train CE:0.011610, Train KL:8.770257, Val MSE:0.010271, Val CE:0.043407, Train ACC:1.000000, Val ACC:0.993750

Epoch 3824/4000: 100%|██████████| 1/1 [00:00<00:00, 27.79it/s]

epoch: 3823, beta = 0.000097, Train MSE: 0.006594, Train CE:0.011611, Train KL:8.770259, Val MSE:0.010272, Val CE:0.043594, Train ACC:1.000000, Val ACC:0.993750

Epoch 3825/4000: 100%|██████████| 1/1 [00:00<00:00, 23.30it/s]

epoch: 3824, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011619, Train KL:8.770260, Val MSE:0.010289, Val CE:0.043641, Train ACC:1.000000, Val ACC:0.993750

Epoch 3826/4000: 100%|██████████| 1/1 [00:00<00:00, 23.19it/s]

epoch: 3825, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011612, Train KL:8.770262, Val MSE:0.010261, Val CE:0.043556, Train ACC:1.000000, Val ACC:0.993750

Epoch 3827/4000: 100%|██████████| 1/1 [00:00<00:00, 24.10it/s]

epoch: 3826, beta = 0.000097, Train MSE: 0.006594, Train CE:0.011614, Train KL:8.770263, Val MSE:0.010261, Val CE:0.043347, Train ACC:1.000000, Val ACC:0.993750

Epoch 3828/4000: 100%|██████████| 1/1 [00:00<00:00, 24.40it/s]

epoch: 3827, beta = 0.000097, Train MSE: 0.006588, Train CE:0.011611, Train KL:8.770265, Val MSE:0.010269, Val CE:0.043393, Train ACC:1.000000, Val ACC:0.993750

Epoch 3829/4000: 100%|██████████| 1/1 [00:00<00:00, 23.73it/s]

epoch: 3828, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011615, Train KL:8.770267, Val MSE:0.010286, Val CE:0.043544, Train ACC:1.000000, Val ACC:0.993750

Epoch 3830/4000: 100%|██████████| 1/1 [00:00<00:00, 21.93it/s]

epoch: 3829, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011607, Train KL:8.770267, Val MSE:0.010274, Val CE:0.043461, Train ACC:1.000000, Val ACC:0.993750

Epoch 3831/4000: 100%|██████████| 1/1 [00:00<00:00, 19.07it/s]

epoch: 3830, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011617, Train KL:8.770269, Val MSE:0.010273, Val CE:0.043580, Train ACC:1.000000, Val ACC:0.993750

Epoch 3832/4000: 100%|██████████| 1/1 [00:00<00:00, 22.10it/s]

epoch: 3831, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011607, Train KL:8.770270, Val MSE:0.010272, Val CE:0.043429, Train ACC:1.000000, Val ACC:0.993750

Epoch 3833/4000: 100%|██████████| 1/1 [00:00<00:00, 21.97it/s]

epoch: 3832, beta = 0.000097, Train MSE: 0.006595, Train CE:0.011608, Train KL:8.770272, Val MSE:0.010264, Val CE:0.043397, Train ACC:1.000000, Val ACC:0.993750

Epoch 3834/4000: 100%|██████████| 1/1 [00:00<00:00, 22.74it/s]

epoch: 3833, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011613, Train KL:8.770274, Val MSE:0.010277, Val CE:0.043469, Train ACC:1.000000, Val ACC:0.993750

Epoch 3835/4000: 100%|██████████| 1/1 [00:00<00:00, 24.70it/s]

epoch: 3834, beta = 0.000097, Train MSE: 0.006594, Train CE:0.011615, Train KL:8.770274, Val MSE:0.010261, Val CE:0.043721, Train ACC:1.000000, Val ACC:0.993750

Epoch 3836/4000: 100%|██████████| 1/1 [00:00<00:00, 23.18it/s]

epoch: 3835, beta = 0.000097, Train MSE: 0.006609, Train CE:0.011612, Train KL:8.770275, Val MSE:0.010304, Val CE:0.043464, Train ACC:1.000000, Val ACC:0.993750

Epoch 3837/4000: 100%|██████████| 1/1 [00:00<00:00, 24.50it/s]

epoch: 3836, beta = 0.000097, Train MSE: 0.006593, Train CE:0.011612, Train KL:8.770277, Val MSE:0.010289, Val CE:0.043616, Train ACC:1.000000, Val ACC:0.993750

Epoch 3838/4000: 100%|██████████| 1/1 [00:00<00:00, 21.31it/s]

epoch: 3837, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011607, Train KL:8.770278, Val MSE:0.010244, Val CE:0.043515, Train ACC:1.000000, Val ACC:0.993750

Epoch 3839/4000: 100%|██████████| 1/1 [00:00<00:00, 25.65it/s]

epoch: 3838, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011612, Train KL:8.770280, Val MSE:0.010245, Val CE:0.043396, Train ACC:1.000000, Val ACC:0.993750

Epoch 3840/4000: 100%|██████████| 1/1 [00:00<00:00, 24.65it/s]

epoch: 3839, beta = 0.000097, Train MSE: 0.006589, Train CE:0.011612, Train KL:8.770282, Val MSE:0.010271, Val CE:0.043447, Train ACC:1.000000, Val ACC:0.993750

Epoch 3841/4000: 100%|██████████| 1/1 [00:00<00:00, 23.66it/s]

epoch: 3840, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011608, Train KL:8.770283, Val MSE:0.010293, Val CE:0.043510, Train ACC:1.000000, Val ACC:0.993750

Epoch 3842/4000: 100%|██████████| 1/1 [00:00<00:00, 24.06it/s]

epoch: 3841, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011607, Train KL:8.770285, Val MSE:0.010297, Val CE:0.043430, Train ACC:1.000000, Val ACC:0.993750

Epoch 3843/4000: 100%|██████████| 1/1 [00:00<00:00, 22.95it/s]

epoch: 3842, beta = 0.000097, Train MSE: 0.006585, Train CE:0.011614, Train KL:8.770286, Val MSE:0.010305, Val CE:0.043403, Train ACC:1.000000, Val ACC:0.993750

Epoch 3844/4000: 100%|██████████| 1/1 [00:00<00:00, 22.59it/s]

epoch: 3843, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011609, Train KL:8.770288, Val MSE:0.010276, Val CE:0.043541, Train ACC:1.000000, Val ACC:0.993750

Epoch 3845/4000: 100%|██████████| 1/1 [00:00<00:00, 18.36it/s]

epoch: 3844, beta = 0.000097, Train MSE: 0.006592, Train CE:0.011602, Train KL:8.770289, Val MSE:0.010293, Val CE:0.043284, Train ACC:1.000000, Val ACC:0.993750

Epoch 3846/4000: 100%|██████████| 1/1 [00:00<00:00, 21.10it/s]

epoch: 3845, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011611, Train KL:8.770292, Val MSE:0.010281, Val CE:0.043503, Train ACC:1.000000, Val ACC:0.993750

Epoch 3847/4000: 100%|██████████| 1/1 [00:00<00:00, 20.64it/s]

epoch: 3846, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011609, Train KL:8.770292, Val MSE:0.010268, Val CE:0.043432, Train ACC:1.000000, Val ACC:0.993750

Epoch 3848/4000: 100%|██████████| 1/1 [00:00<00:00, 25.06it/s]

epoch: 3847, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011609, Train KL:8.770295, Val MSE:0.010266, Val CE:0.043539, Train ACC:1.000000, Val ACC:0.993750

Epoch 3849/4000: 100%|██████████| 1/1 [00:00<00:00, 21.94it/s]

epoch: 3848, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011607, Train KL:8.770297, Val MSE:0.010283, Val CE:0.043457, Train ACC:1.000000, Val ACC:0.993750

Epoch 3850/4000: 100%|██████████| 1/1 [00:00<00:00, 23.88it/s]

epoch: 3849, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011616, Train KL:8.770298, Val MSE:0.010254, Val CE:0.043476, Train ACC:1.000000, Val ACC:0.993750

Epoch 3851/4000: 100%|██████████| 1/1 [00:00<00:00, 24.03it/s]

epoch: 3850, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011612, Train KL:8.770301, Val MSE:0.010278, Val CE:0.043307, Train ACC:1.000000, Val ACC:0.993750

Epoch 3852/4000: 100%|██████████| 1/1 [00:00<00:00, 27.13it/s]

epoch: 3851, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011605, Train KL:8.770303, Val MSE:0.010276, Val CE:0.043660, Train ACC:1.000000, Val ACC:0.993750

Epoch 3853/4000: 100%|██████████| 1/1 [00:00<00:00, 22.32it/s]

epoch: 3852, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011615, Train KL:8.770305, Val MSE:0.010289, Val CE:0.043326, Train ACC:1.000000, Val ACC:0.993750

Epoch 3854/4000: 100%|██████████| 1/1 [00:00<00:00, 24.28it/s]

epoch: 3853, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011610, Train KL:8.770308, Val MSE:0.010266, Val CE:0.043597, Train ACC:1.000000, Val ACC:0.993750

Epoch 3855/4000: 100%|██████████| 1/1 [00:00<00:00, 24.15it/s]

epoch: 3854, beta = 0.000097, Train MSE: 0.006593, Train CE:0.011607, Train KL:8.770308, Val MSE:0.010289, Val CE:0.043307, Train ACC:1.000000, Val ACC:0.993750

Epoch 3856/4000: 100%|██████████| 1/1 [00:00<00:00, 23.62it/s]

epoch: 3855, beta = 0.000097, Train MSE: 0.006591, Train CE:0.011605, Train KL:8.770310, Val MSE:0.010280, Val CE:0.043440, Train ACC:1.000000, Val ACC:0.993750

Epoch 3857/4000: 100%|██████████| 1/1 [00:00<00:00, 22.49it/s]

epoch: 3856, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011609, Train KL:8.770312, Val MSE:0.010269, Val CE:0.043707, Train ACC:1.000000, Val ACC:0.993750

Epoch 3858/4000: 100%|██████████| 1/1 [00:00<00:00, 21.30it/s]

epoch: 3857, beta = 0.000097, Train MSE: 0.006590, Train CE:0.011612, Train KL:8.770315, Val MSE:0.010290, Val CE:0.043381, Train ACC:1.000000, Val ACC:0.993750

Epoch 3859/4000: 100%|██████████| 1/1 [00:00<00:00, 20.26it/s]

epoch: 3858, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011606, Train KL:8.770317, Val MSE:0.010285, Val CE:0.043551, Train ACC:1.000000, Val ACC:0.993750

Epoch 3860/4000: 100%|██████████| 1/1 [00:00<00:00, 21.38it/s]

epoch: 3859, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011612, Train KL:8.770320, Val MSE:0.010276, Val CE:0.043550, Train ACC:1.000000, Val ACC:0.993750

Epoch 3861/4000: 100%|██████████| 1/1 [00:00<00:00, 22.92it/s]

epoch: 3860, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011611, Train KL:8.770321, Val MSE:0.010257, Val CE:0.043579, Train ACC:1.000000, Val ACC:0.993750

Epoch 3862/4000: 100%|██████████| 1/1 [00:00<00:00, 22.84it/s]

epoch: 3861, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011616, Train KL:8.770323, Val MSE:0.010289, Val CE:0.043606, Train ACC:1.000000, Val ACC:0.993750

Epoch 3863/4000: 100%|██████████| 1/1 [00:00<00:00, 23.72it/s]

epoch: 3862, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011608, Train KL:8.770326, Val MSE:0.010272, Val CE:0.043379, Train ACC:1.000000, Val ACC:0.993750

Epoch 3864/4000: 100%|██████████| 1/1 [00:00<00:00, 24.49it/s]

epoch: 3863, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011611, Train KL:8.770328, Val MSE:0.010272, Val CE:0.043602, Train ACC:1.000000, Val ACC:0.993750

Epoch 3865/4000: 100%|██████████| 1/1 [00:00<00:00, 22.76it/s]

epoch: 3864, beta = 0.000097, Train MSE: 0.006595, Train CE:0.011611, Train KL:8.770329, Val MSE:0.010280, Val CE:0.043409, Train ACC:1.000000, Val ACC:0.993750

Epoch 3866/4000: 100%|██████████| 1/1 [00:00<00:00, 23.98it/s]

epoch: 3865, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011610, Train KL:8.770330, Val MSE:0.010253, Val CE:0.043544, Train ACC:1.000000, Val ACC:0.993750

Epoch 3867/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 3866, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011606, Train KL:8.770331, Val MSE:0.010283, Val CE:0.043292, Train ACC:1.000000, Val ACC:0.993750

Epoch 3868/4000: 100%|██████████| 1/1 [00:00<00:00, 23.09it/s]

epoch: 3867, beta = 0.000097, Train MSE: 0.006595, Train CE:0.011606, Train KL:8.770333, Val MSE:0.010295, Val CE:0.043618, Train ACC:1.000000, Val ACC:0.993750

Epoch 3869/4000: 100%|██████████| 1/1 [00:00<00:00, 23.45it/s]

epoch: 3868, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011608, Train KL:8.770335, Val MSE:0.010269, Val CE:0.043628, Train ACC:1.000000, Val ACC:0.993750

Epoch 3870/4000: 100%|██████████| 1/1 [00:00<00:00, 24.07it/s]

epoch: 3869, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011609, Train KL:8.770337, Val MSE:0.010281, Val CE:0.043471, Train ACC:1.000000, Val ACC:0.993750

Epoch 3871/4000: 100%|██████████| 1/1 [00:00<00:00, 19.77it/s]

epoch: 3870, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011610, Train KL:8.770339, Val MSE:0.010299, Val CE:0.043396, Train ACC:1.000000, Val ACC:0.993750

Epoch 3872/4000: 100%|██████████| 1/1 [00:00<00:00, 20.47it/s]

epoch: 3871, beta = 0.000097, Train MSE: 0.006592, Train CE:0.011610, Train KL:8.770340, Val MSE:0.010280, Val CE:0.043517, Train ACC:1.000000, Val ACC:0.993750

Epoch 3873/4000: 100%|██████████| 1/1 [00:00<00:00, 23.23it/s]

epoch: 3872, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011612, Train KL:8.770343, Val MSE:0.010269, Val CE:0.043386, Train ACC:1.000000, Val ACC:0.993750

Epoch 3874/4000: 100%|██████████| 1/1 [00:00<00:00, 25.41it/s]

epoch: 3873, beta = 0.000097, Train MSE: 0.006593, Train CE:0.011610, Train KL:8.770346, Val MSE:0.010301, Val CE:0.043465, Train ACC:1.000000, Val ACC:0.993750

Epoch 3875/4000: 100%|██████████| 1/1 [00:00<00:00, 22.13it/s]

epoch: 3874, beta = 0.000097, Train MSE: 0.006594, Train CE:0.011609, Train KL:8.770347, Val MSE:0.010263, Val CE:0.043494, Train ACC:1.000000, Val ACC:0.993750

Epoch 3876/4000: 100%|██████████| 1/1 [00:00<00:00, 22.82it/s]

epoch: 3875, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011613, Train KL:8.770349, Val MSE:0.010266, Val CE:0.043456, Train ACC:1.000000, Val ACC:0.993750

Epoch 3877/4000: 100%|██████████| 1/1 [00:00<00:00, 23.78it/s]

epoch: 3876, beta = 0.000097, Train MSE: 0.006593, Train CE:0.011609, Train KL:8.770351, Val MSE:0.010271, Val CE:0.043514, Train ACC:1.000000, Val ACC:0.993750

Epoch 3878/4000: 100%|██████████| 1/1 [00:00<00:00, 26.55it/s]

epoch: 3877, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011606, Train KL:8.770353, Val MSE:0.010266, Val CE:0.043493, Train ACC:1.000000, Val ACC:0.993750

Epoch 3879/4000: 100%|██████████| 1/1 [00:00<00:00, 24.04it/s]

epoch: 3878, beta = 0.000097, Train MSE: 0.006588, Train CE:0.011614, Train KL:8.770354, Val MSE:0.010286, Val CE:0.043547, Train ACC:1.000000, Val ACC:0.993750

Epoch 3880/4000: 100%|██████████| 1/1 [00:00<00:00, 27.11it/s]

epoch: 3879, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011614, Train KL:8.770358, Val MSE:0.010279, Val CE:0.043255, Train ACC:1.000000, Val ACC:0.993750

Epoch 3881/4000: 100%|██████████| 1/1 [00:00<00:00, 21.16it/s]

epoch: 3880, beta = 0.000097, Train MSE: 0.006593, Train CE:0.011610, Train KL:8.770359, Val MSE:0.010294, Val CE:0.043403, Train ACC:1.000000, Val ACC:0.993750

Epoch 3882/4000: 100%|██████████| 1/1 [00:00<00:00, 23.29it/s]

epoch: 3881, beta = 0.000097, Train MSE: 0.006592, Train CE:0.011614, Train KL:8.770362, Val MSE:0.010284, Val CE:0.043386, Train ACC:1.000000, Val ACC:0.993750

Epoch 3883/4000: 100%|██████████| 1/1 [00:00<00:00, 23.47it/s]

epoch: 3882, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011611, Train KL:8.770364, Val MSE:0.010270, Val CE:0.043540, Train ACC:1.000000, Val ACC:0.993750

Epoch 3884/4000: 100%|██████████| 1/1 [00:00<00:00, 22.82it/s]

epoch: 3883, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011612, Train KL:8.770366, Val MSE:0.010298, Val CE:0.043578, Train ACC:1.000000, Val ACC:0.993750

Epoch 3885/4000: 100%|██████████| 1/1 [00:00<00:00, 22.85it/s]

epoch: 3884, beta = 0.000097, Train MSE: 0.006594, Train CE:0.011609, Train KL:8.770368, Val MSE:0.010254, Val CE:0.043498, Train ACC:1.000000, Val ACC:0.993750

Epoch 3886/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 3885, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011610, Train KL:8.770370, Val MSE:0.010284, Val CE:0.043444, Train ACC:1.000000, Val ACC:0.993750

Epoch 3887/4000: 100%|██████████| 1/1 [00:00<00:00, 23.80it/s]

epoch: 3886, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011613, Train KL:8.770371, Val MSE:0.010290, Val CE:0.043378, Train ACC:1.000000, Val ACC:0.993750

Epoch 3888/4000: 100%|██████████| 1/1 [00:00<00:00, 25.19it/s]

epoch: 3887, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011611, Train KL:8.770374, Val MSE:0.010242, Val CE:0.043493, Train ACC:1.000000, Val ACC:0.993750

Epoch 3889/4000: 100%|██████████| 1/1 [00:00<00:00, 23.83it/s]

epoch: 3888, beta = 0.000097, Train MSE: 0.006593, Train CE:0.011610, Train KL:8.770378, Val MSE:0.010266, Val CE:0.043368, Train ACC:1.000000, Val ACC:0.993750

Epoch 3890/4000: 100%|██████████| 1/1 [00:00<00:00, 25.40it/s]

epoch: 3889, beta = 0.000097, Train MSE: 0.006608, Train CE:0.011612, Train KL:8.770379, Val MSE:0.010287, Val CE:0.043685, Train ACC:1.000000, Val ACC:0.993750

Epoch 3891/4000: 100%|██████████| 1/1 [00:00<00:00, 24.34it/s]

epoch: 3890, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011605, Train KL:8.770382, Val MSE:0.010253, Val CE:0.043575, Train ACC:1.000000, Val ACC:0.993750

Epoch 3892/4000: 100%|██████████| 1/1 [00:00<00:00, 24.01it/s]

epoch: 3891, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011605, Train KL:8.770384, Val MSE:0.010261, Val CE:0.043455, Train ACC:1.000000, Val ACC:0.993750

Epoch 3893/4000: 100%|██████████| 1/1 [00:00<00:00, 22.09it/s]

epoch: 3892, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011612, Train KL:8.770386, Val MSE:0.010278, Val CE:0.043333, Train ACC:1.000000, Val ACC:0.993750

Epoch 3894/4000: 100%|██████████| 1/1 [00:00<00:00, 24.00it/s]

epoch: 3893, beta = 0.000097, Train MSE: 0.006595, Train CE:0.011609, Train KL:8.770388, Val MSE:0.010254, Val CE:0.043517, Train ACC:1.000000, Val ACC:0.993750

Epoch 3895/4000: 100%|██████████| 1/1 [00:00<00:00, 22.72it/s]

epoch: 3894, beta = 0.000097, Train MSE: 0.006594, Train CE:0.011607, Train KL:8.770390, Val MSE:0.010289, Val CE:0.043536, Train ACC:1.000000, Val ACC:0.993750

Epoch 3896/4000: 100%|██████████| 1/1 [00:00<00:00, 22.55it/s]

epoch: 3895, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011613, Train KL:8.770392, Val MSE:0.010265, Val CE:0.043578, Train ACC:1.000000, Val ACC:0.993750

Epoch 3897/4000: 100%|██████████| 1/1 [00:00<00:00, 21.18it/s]

epoch: 3896, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011608, Train KL:8.770393, Val MSE:0.010286, Val CE:0.043541, Train ACC:1.000000, Val ACC:0.993750

Epoch 3898/4000: 100%|██████████| 1/1 [00:00<00:00, 21.49it/s]

epoch: 3897, beta = 0.000097, Train MSE: 0.006593, Train CE:0.011612, Train KL:8.770395, Val MSE:0.010292, Val CE:0.043623, Train ACC:1.000000, Val ACC:0.993750

Epoch 3899/4000: 100%|██████████| 1/1 [00:00<00:00, 23.64it/s]

epoch: 3898, beta = 0.000097, Train MSE: 0.006591, Train CE:0.011610, Train KL:8.770397, Val MSE:0.010242, Val CE:0.043276, Train ACC:1.000000, Val ACC:0.993750

Epoch 3900/4000: 100%|██████████| 1/1 [00:00<00:00, 22.12it/s]

epoch: 3899, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011610, Train KL:8.770400, Val MSE:0.010258, Val CE:0.043586, Train ACC:1.000000, Val ACC:0.993750

Epoch 3901/4000: 100%|██████████| 1/1 [00:00<00:00, 23.59it/s]

epoch: 3900, beta = 0.000097, Train MSE: 0.006591, Train CE:0.011609, Train KL:8.770401, Val MSE:0.010279, Val CE:0.043806, Train ACC:1.000000, Val ACC:0.993750

Epoch 3902/4000: 100%|██████████| 1/1 [00:00<00:00, 23.55it/s]

epoch: 3901, beta = 0.000097, Train MSE: 0.006592, Train CE:0.011611, Train KL:8.770403, Val MSE:0.010266, Val CE:0.043506, Train ACC:1.000000, Val ACC:0.993750

Epoch 3903/4000: 100%|██████████| 1/1 [00:00<00:00, 21.01it/s]

epoch: 3902, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011607, Train KL:8.770405, Val MSE:0.010270, Val CE:0.043546, Train ACC:1.000000, Val ACC:0.993750

Epoch 3904/4000: 100%|██████████| 1/1 [00:00<00:00, 20.91it/s]

epoch: 3903, beta = 0.000097, Train MSE: 0.006594, Train CE:0.011612, Train KL:8.770407, Val MSE:0.010285, Val CE:0.043615, Train ACC:1.000000, Val ACC:0.993750

Epoch 3905/4000: 100%|██████████| 1/1 [00:00<00:00, 22.89it/s]

epoch: 3904, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011609, Train KL:8.770409, Val MSE:0.010249, Val CE:0.043469, Train ACC:1.000000, Val ACC:0.993750

Epoch 3906/4000: 100%|██████████| 1/1 [00:00<00:00, 22.38it/s]

epoch: 3905, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011611, Train KL:8.770411, Val MSE:0.010268, Val CE:0.043698, Train ACC:1.000000, Val ACC:0.993750

Epoch 3907/4000: 100%|██████████| 1/1 [00:00<00:00, 23.69it/s]

epoch: 3906, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011611, Train KL:8.770412, Val MSE:0.010263, Val CE:0.043602, Train ACC:1.000000, Val ACC:0.993750

Epoch 3908/4000: 100%|██████████| 1/1 [00:00<00:00, 21.88it/s]

epoch: 3907, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011612, Train KL:8.770413, Val MSE:0.010278, Val CE:0.043563, Train ACC:1.000000, Val ACC:0.993750

Epoch 3909/4000: 100%|██████████| 1/1 [00:00<00:00, 24.06it/s]

epoch: 3908, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011609, Train KL:8.770416, Val MSE:0.010265, Val CE:0.043413, Train ACC:1.000000, Val ACC:0.993750

Epoch 3910/4000: 100%|██████████| 1/1 [00:00<00:00, 24.19it/s]

epoch: 3909, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011608, Train KL:8.770417, Val MSE:0.010267, Val CE:0.043490, Train ACC:1.000000, Val ACC:0.993750

Epoch 3911/4000: 100%|██████████| 1/1 [00:00<00:00, 21.67it/s]

epoch: 3910, beta = 0.000097, Train MSE: 0.006595, Train CE:0.011613, Train KL:8.770419, Val MSE:0.010281, Val CE:0.043571, Train ACC:1.000000, Val ACC:0.993750

Epoch 3912/4000: 100%|██████████| 1/1 [00:00<00:00, 23.96it/s]

epoch: 3911, beta = 0.000097, Train MSE: 0.006587, Train CE:0.011608, Train KL:8.770420, Val MSE:0.010292, Val CE:0.043502, Train ACC:1.000000, Val ACC:0.993750

Epoch 3913/4000: 100%|██████████| 1/1 [00:00<00:00, 21.91it/s]

epoch: 3912, beta = 0.000097, Train MSE: 0.006595, Train CE:0.011608, Train KL:8.770422, Val MSE:0.010305, Val CE:0.043421, Train ACC:1.000000, Val ACC:0.993750

Epoch 3914/4000: 100%|██████████| 1/1 [00:00<00:00, 23.88it/s]

epoch: 3913, beta = 0.000097, Train MSE: 0.006594, Train CE:0.011608, Train KL:8.770424, Val MSE:0.010254, Val CE:0.043545, Train ACC:1.000000, Val ACC:0.993750

Epoch 3915/4000: 100%|██████████| 1/1 [00:00<00:00, 22.21it/s]

epoch: 3914, beta = 0.000097, Train MSE: 0.006593, Train CE:0.011607, Train KL:8.770426, Val MSE:0.010265, Val CE:0.043583, Train ACC:1.000000, Val ACC:0.993750

Epoch 3916/4000: 100%|██████████| 1/1 [00:00<00:00, 23.25it/s]

epoch: 3915, beta = 0.000097, Train MSE: 0.006610, Train CE:0.011608, Train KL:8.770428, Val MSE:0.010265, Val CE:0.043756, Train ACC:1.000000, Val ACC:0.993750

Epoch 3917/4000: 100%|██████████| 1/1 [00:00<00:00, 21.53it/s]

epoch: 3916, beta = 0.000097, Train MSE: 0.006592, Train CE:0.011611, Train KL:8.770430, Val MSE:0.010286, Val CE:0.043305, Train ACC:1.000000, Val ACC:0.993750

Epoch 3918/4000: 100%|██████████| 1/1 [00:00<00:00, 20.83it/s]

epoch: 3917, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011604, Train KL:8.770432, Val MSE:0.010293, Val CE:0.043581, Train ACC:1.000000, Val ACC:0.993750

Epoch 3919/4000: 100%|██████████| 1/1 [00:00<00:00, 24.19it/s]

epoch: 3918, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011605, Train KL:8.770433, Val MSE:0.010275, Val CE:0.043564, Train ACC:1.000000, Val ACC:0.993750

Epoch 3920/4000: 100%|██████████| 1/1 [00:00<00:00, 24.15it/s]

epoch: 3919, beta = 0.000097, Train MSE: 0.006594, Train CE:0.011609, Train KL:8.770435, Val MSE:0.010289, Val CE:0.043509, Train ACC:1.000000, Val ACC:0.993750

Epoch 3921/4000: 100%|██████████| 1/1 [00:00<00:00, 23.88it/s]

epoch: 3920, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011606, Train KL:8.770437, Val MSE:0.010263, Val CE:0.043420, Train ACC:1.000000, Val ACC:0.993750

Epoch 3922/4000: 100%|██████████| 1/1 [00:00<00:00, 23.55it/s]

epoch: 3921, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011608, Train KL:8.770439, Val MSE:0.010286, Val CE:0.043432, Train ACC:1.000000, Val ACC:0.993750

Epoch 3923/4000: 100%|██████████| 1/1 [00:00<00:00, 23.70it/s]

epoch: 3922, beta = 0.000097, Train MSE: 0.006589, Train CE:0.011609, Train KL:8.770440, Val MSE:0.010303, Val CE:0.043388, Train ACC:1.000000, Val ACC:0.993750

Epoch 3924/4000: 100%|██████████| 1/1 [00:00<00:00, 23.47it/s]

epoch: 3923, beta = 0.000097, Train MSE: 0.006587, Train CE:0.011610, Train KL:8.770442, Val MSE:0.010293, Val CE:0.043424, Train ACC:1.000000, Val ACC:0.993750

Epoch 3925/4000: 100%|██████████| 1/1 [00:00<00:00, 24.02it/s]

epoch: 3924, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011604, Train KL:8.770445, Val MSE:0.010254, Val CE:0.043524, Train ACC:1.000000, Val ACC:0.993750

Epoch 3926/4000: 100%|██████████| 1/1 [00:00<00:00, 22.13it/s]

epoch: 3925, beta = 0.000097, Train MSE: 0.006594, Train CE:0.011604, Train KL:8.770447, Val MSE:0.010279, Val CE:0.043283, Train ACC:1.000000, Val ACC:0.993750

Epoch 3927/4000: 100%|██████████| 1/1 [00:00<00:00, 22.18it/s]

epoch: 3926, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011613, Train KL:8.770448, Val MSE:0.010266, Val CE:0.043555, Train ACC:1.000000, Val ACC:0.993750

Epoch 3928/4000: 100%|██████████| 1/1 [00:00<00:00, 16.72it/s]

epoch: 3927, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011607, Train KL:8.770451, Val MSE:0.010266, Val CE:0.043580, Train ACC:1.000000, Val ACC:0.993750

Epoch 3929/4000: 100%|██████████| 1/1 [00:00<00:00, 21.55it/s]

epoch: 3928, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011610, Train KL:8.770452, Val MSE:0.010271, Val CE:0.043668, Train ACC:1.000000, Val ACC:0.993750

Epoch 3930/4000: 100%|██████████| 1/1 [00:00<00:00, 25.21it/s]

epoch: 3929, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011611, Train KL:8.770454, Val MSE:0.010281, Val CE:0.043415, Train ACC:1.000000, Val ACC:0.993750

Epoch 3931/4000: 100%|██████████| 1/1 [00:00<00:00, 24.04it/s]

epoch: 3930, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011606, Train KL:8.770455, Val MSE:0.010279, Val CE:0.043603, Train ACC:1.000000, Val ACC:0.993750

Epoch 3932/4000: 100%|██████████| 1/1 [00:00<00:00, 22.71it/s]

epoch: 3931, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011607, Train KL:8.770458, Val MSE:0.010256, Val CE:0.043384, Train ACC:1.000000, Val ACC:0.993750

Epoch 3933/4000: 100%|██████████| 1/1 [00:00<00:00, 23.56it/s]

epoch: 3932, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011610, Train KL:8.770460, Val MSE:0.010283, Val CE:0.043718, Train ACC:1.000000, Val ACC:0.993750

Epoch 3934/4000: 100%|██████████| 1/1 [00:00<00:00, 24.09it/s]

epoch: 3933, beta = 0.000097, Train MSE: 0.006593, Train CE:0.011604, Train KL:8.770462, Val MSE:0.010304, Val CE:0.043595, Train ACC:1.000000, Val ACC:0.993750

Epoch 3935/4000: 100%|██████████| 1/1 [00:00<00:00, 24.09it/s]

epoch: 3934, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011607, Train KL:8.770463, Val MSE:0.010266, Val CE:0.043282, Train ACC:1.000000, Val ACC:0.993750

Epoch 3936/4000: 100%|██████████| 1/1 [00:00<00:00, 23.99it/s]

epoch: 3935, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011606, Train KL:8.770466, Val MSE:0.010274, Val CE:0.043517, Train ACC:1.000000, Val ACC:0.993750

Epoch 3937/4000: 100%|██████████| 1/1 [00:00<00:00, 24.08it/s]

epoch: 3936, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011612, Train KL:8.770468, Val MSE:0.010259, Val CE:0.043611, Train ACC:1.000000, Val ACC:0.993750

Epoch 3938/4000: 100%|██████████| 1/1 [00:00<00:00, 24.39it/s]

epoch: 3937, beta = 0.000097, Train MSE: 0.006603, Train CE:0.011607, Train KL:8.770470, Val MSE:0.010274, Val CE:0.043480, Train ACC:1.000000, Val ACC:0.993750

Epoch 3939/4000: 100%|██████████| 1/1 [00:00<00:00, 23.31it/s]

epoch: 3938, beta = 0.000097, Train MSE: 0.006594, Train CE:0.011607, Train KL:8.770472, Val MSE:0.010267, Val CE:0.043282, Train ACC:1.000000, Val ACC:0.993750

Epoch 3940/4000: 100%|██████████| 1/1 [00:00<00:00, 24.01it/s]

epoch: 3939, beta = 0.000097, Train MSE: 0.006595, Train CE:0.011607, Train KL:8.770473, Val MSE:0.010282, Val CE:0.043415, Train ACC:1.000000, Val ACC:0.993750

Epoch 3941/4000: 100%|██████████| 1/1 [00:00<00:00, 23.30it/s]

epoch: 3940, beta = 0.000097, Train MSE: 0.006611, Train CE:0.011605, Train KL:8.770475, Val MSE:0.010263, Val CE:0.043520, Train ACC:1.000000, Val ACC:0.993750

Epoch 3942/4000: 100%|██████████| 1/1 [00:00<00:00, 22.52it/s]

epoch: 3941, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011607, Train KL:8.770477, Val MSE:0.010286, Val CE:0.043503, Train ACC:1.000000, Val ACC:0.993750

Epoch 3943/4000: 100%|██████████| 1/1 [00:00<00:00, 18.97it/s]

epoch: 3942, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011614, Train KL:8.770479, Val MSE:0.010269, Val CE:0.043573, Train ACC:1.000000, Val ACC:0.993750

Epoch 3944/4000: 100%|██████████| 1/1 [00:00<00:00, 21.24it/s]

epoch: 3943, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011602, Train KL:8.770481, Val MSE:0.010272, Val CE:0.043663, Train ACC:1.000000, Val ACC:0.993750

Epoch 3945/4000: 100%|██████████| 1/1 [00:00<00:00, 24.05it/s]

epoch: 3944, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011604, Train KL:8.770483, Val MSE:0.010308, Val CE:0.043459, Train ACC:1.000000, Val ACC:0.993750

Epoch 3946/4000: 100%|██████████| 1/1 [00:00<00:00, 23.60it/s]

epoch: 3945, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011611, Train KL:8.770485, Val MSE:0.010279, Val CE:0.043643, Train ACC:1.000000, Val ACC:0.993750

Epoch 3947/4000: 100%|██████████| 1/1 [00:00<00:00, 23.96it/s]

epoch: 3946, beta = 0.000097, Train MSE: 0.006593, Train CE:0.011608, Train KL:8.770488, Val MSE:0.010278, Val CE:0.043533, Train ACC:1.000000, Val ACC:0.993750

Epoch 3948/4000: 100%|██████████| 1/1 [00:00<00:00, 23.60it/s]

epoch: 3947, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011610, Train KL:8.770491, Val MSE:0.010298, Val CE:0.043476, Train ACC:1.000000, Val ACC:0.993750

Epoch 3949/4000: 100%|██████████| 1/1 [00:00<00:00, 24.10it/s]

epoch: 3948, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011606, Train KL:8.770493, Val MSE:0.010257, Val CE:0.043542, Train ACC:1.000000, Val ACC:0.993750

Epoch 3950/4000: 100%|██████████| 1/1 [00:00<00:00, 24.64it/s]

epoch: 3949, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011609, Train KL:8.770494, Val MSE:0.010293, Val CE:0.043398, Train ACC:1.000000, Val ACC:0.993750

Epoch 3951/4000: 100%|██████████| 1/1 [00:00<00:00, 23.76it/s]

epoch: 3950, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011606, Train KL:8.770497, Val MSE:0.010245, Val CE:0.043366, Train ACC:1.000000, Val ACC:0.993750

Epoch 3952/4000: 100%|██████████| 1/1 [00:00<00:00, 25.14it/s]

epoch: 3951, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011608, Train KL:8.770499, Val MSE:0.010294, Val CE:0.043617, Train ACC:1.000000, Val ACC:0.993750

Epoch 3953/4000: 100%|██████████| 1/1 [00:00<00:00, 23.25it/s]

epoch: 3952, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011604, Train KL:8.770501, Val MSE:0.010267, Val CE:0.043433, Train ACC:1.000000, Val ACC:0.993750

Epoch 3954/4000: 100%|██████████| 1/1 [00:00<00:00, 22.99it/s]

epoch: 3953, beta = 0.000097, Train MSE: 0.006591, Train CE:0.011602, Train KL:8.770505, Val MSE:0.010267, Val CE:0.043516, Train ACC:1.000000, Val ACC:0.993750

Epoch 3955/4000: 100%|██████████| 1/1 [00:00<00:00, 24.31it/s]

epoch: 3954, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011608, Train KL:8.770506, Val MSE:0.010248, Val CE:0.043612, Train ACC:1.000000, Val ACC:0.993750

Epoch 3956/4000: 100%|██████████| 1/1 [00:00<00:00, 21.56it/s]

epoch: 3955, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011607, Train KL:8.770509, Val MSE:0.010307, Val CE:0.043302, Train ACC:1.000000, Val ACC:0.993750

Epoch 3957/4000: 100%|██████████| 1/1 [00:00<00:00, 22.50it/s]

epoch: 3956, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011611, Train KL:8.770512, Val MSE:0.010270, Val CE:0.043461, Train ACC:1.000000, Val ACC:0.993750

Epoch 3958/4000: 100%|██████████| 1/1 [00:00<00:00, 22.44it/s]

epoch: 3957, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011612, Train KL:8.770514, Val MSE:0.010302, Val CE:0.043444, Train ACC:1.000000, Val ACC:0.993750

Epoch 3959/4000: 100%|██████████| 1/1 [00:00<00:00, 26.78it/s]

epoch: 3958, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011614, Train KL:8.770515, Val MSE:0.010294, Val CE:0.043433, Train ACC:1.000000, Val ACC:0.993750

Epoch 3960/4000: 100%|██████████| 1/1 [00:00<00:00, 22.37it/s]

epoch: 3959, beta = 0.000097, Train MSE: 0.006595, Train CE:0.011609, Train KL:8.770517, Val MSE:0.010288, Val CE:0.043274, Train ACC:1.000000, Val ACC:0.993750

Epoch 3961/4000: 100%|██████████| 1/1 [00:00<00:00, 23.00it/s]

epoch: 3960, beta = 0.000097, Train MSE: 0.006591, Train CE:0.011604, Train KL:8.770520, Val MSE:0.010271, Val CE:0.043568, Train ACC:1.000000, Val ACC:0.993750

Epoch 3962/4000: 100%|██████████| 1/1 [00:00<00:00, 20.86it/s]

epoch: 3961, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011613, Train KL:8.770522, Val MSE:0.010283, Val CE:0.043573, Train ACC:1.000000, Val ACC:0.993750

Epoch 3963/4000: 100%|██████████| 1/1 [00:00<00:00, 23.94it/s]

epoch: 3962, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011604, Train KL:8.770524, Val MSE:0.010246, Val CE:0.043928, Train ACC:1.000000, Val ACC:0.993750

Epoch 3964/4000: 100%|██████████| 1/1 [00:00<00:00, 24.65it/s]

epoch: 3963, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011608, Train KL:8.770526, Val MSE:0.010309, Val CE:0.043421, Train ACC:1.000000, Val ACC:0.993750

Epoch 3965/4000: 100%|██████████| 1/1 [00:00<00:00, 23.75it/s]

epoch: 3964, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011608, Train KL:8.770528, Val MSE:0.010260, Val CE:0.043501, Train ACC:1.000000, Val ACC:0.993750

Epoch 3966/4000: 100%|██████████| 1/1 [00:00<00:00, 23.45it/s]

epoch: 3965, beta = 0.000097, Train MSE: 0.006602, Train CE:0.011606, Train KL:8.770531, Val MSE:0.010271, Val CE:0.043573, Train ACC:1.000000, Val ACC:0.993750

Epoch 3967/4000: 100%|██████████| 1/1 [00:00<00:00, 24.05it/s]

epoch: 3966, beta = 0.000097, Train MSE: 0.006606, Train CE:0.011612, Train KL:8.770532, Val MSE:0.010263, Val CE:0.043569, Train ACC:1.000000, Val ACC:0.993750

Epoch 3968/4000: 100%|██████████| 1/1 [00:00<00:00, 24.49it/s]

epoch: 3967, beta = 0.000097, Train MSE: 0.006592, Train CE:0.011605, Train KL:8.770535, Val MSE:0.010289, Val CE:0.043481, Train ACC:1.000000, Val ACC:0.993750

Epoch 3969/4000: 100%|██████████| 1/1 [00:00<00:00, 23.12it/s]

epoch: 3968, beta = 0.000097, Train MSE: 0.006592, Train CE:0.011602, Train KL:8.770536, Val MSE:0.010293, Val CE:0.043571, Train ACC:1.000000, Val ACC:0.993750

Epoch 3970/4000: 100%|██████████| 1/1 [00:00<00:00, 25.79it/s]

epoch: 3969, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011611, Train KL:8.770538, Val MSE:0.010252, Val CE:0.043472, Train ACC:1.000000, Val ACC:0.993750

Epoch 3971/4000: 100%|██████████| 1/1 [00:00<00:00, 24.18it/s]

epoch: 3970, beta = 0.000097, Train MSE: 0.006594, Train CE:0.011609, Train KL:8.770541, Val MSE:0.010279, Val CE:0.043626, Train ACC:1.000000, Val ACC:0.993750

Epoch 3972/4000: 100%|██████████| 1/1 [00:00<00:00, 23.49it/s]

epoch: 3971, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011604, Train KL:8.770543, Val MSE:0.010271, Val CE:0.043666, Train ACC:1.000000, Val ACC:0.993750

Epoch 3973/4000: 100%|██████████| 1/1 [00:00<00:00, 23.16it/s]

epoch: 3972, beta = 0.000097, Train MSE: 0.006601, Train CE:0.011604, Train KL:8.770544, Val MSE:0.010247, Val CE:0.043628, Train ACC:1.000000, Val ACC:0.993750

Epoch 3974/4000: 100%|██████████| 1/1 [00:00<00:00, 20.94it/s]

epoch: 3973, beta = 0.000097, Train MSE: 0.006594, Train CE:0.011608, Train KL:8.770546, Val MSE:0.010269, Val CE:0.043520, Train ACC:1.000000, Val ACC:0.993750

Epoch 3975/4000: 100%|██████████| 1/1 [00:00<00:00, 23.24it/s]

epoch: 3974, beta = 0.000097, Train MSE: 0.006590, Train CE:0.011604, Train KL:8.770549, Val MSE:0.010290, Val CE:0.043183, Train ACC:1.000000, Val ACC:0.993750

Epoch 3976/4000: 100%|██████████| 1/1 [00:00<00:00, 23.41it/s]

epoch: 3975, beta = 0.000097, Train MSE: 0.006607, Train CE:0.011608, Train KL:8.770550, Val MSE:0.010291, Val CE:0.043639, Train ACC:1.000000, Val ACC:0.993750

Epoch 3977/4000: 100%|██████████| 1/1 [00:00<00:00, 24.10it/s]

epoch: 3976, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011603, Train KL:8.770551, Val MSE:0.010259, Val CE:0.043528, Train ACC:1.000000, Val ACC:0.993750

Epoch 3978/4000: 100%|██████████| 1/1 [00:00<00:00, 25.41it/s]

epoch: 3977, beta = 0.000097, Train MSE: 0.006594, Train CE:0.011603, Train KL:8.770554, Val MSE:0.010272, Val CE:0.043435, Train ACC:1.000000, Val ACC:0.993750

Epoch 3979/4000: 100%|██████████| 1/1 [00:00<00:00, 23.03it/s]

epoch: 3978, beta = 0.000097, Train MSE: 0.006592, Train CE:0.011608, Train KL:8.770555, Val MSE:0.010267, Val CE:0.043443, Train ACC:1.000000, Val ACC:0.993750

Epoch 3980/4000: 100%|██████████| 1/1 [00:00<00:00, 23.96it/s]

epoch: 3979, beta = 0.000097, Train MSE: 0.006593, Train CE:0.011608, Train KL:8.770556, Val MSE:0.010246, Val CE:0.043471, Train ACC:1.000000, Val ACC:0.993750

Epoch 3981/4000: 100%|██████████| 1/1 [00:00<00:00, 23.96it/s]

epoch: 3980, beta = 0.000097, Train MSE: 0.006604, Train CE:0.011606, Train KL:8.770559, Val MSE:0.010270, Val CE:0.043382, Train ACC:1.000000, Val ACC:0.993750

Epoch 3982/4000: 100%|██████████| 1/1 [00:00<00:00, 21.96it/s]

epoch: 3981, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011602, Train KL:8.770561, Val MSE:0.010256, Val CE:0.043469, Train ACC:1.000000, Val ACC:0.993750

Epoch 3983/4000: 100%|██████████| 1/1 [00:00<00:00, 23.70it/s]

epoch: 3982, beta = 0.000097, Train MSE: 0.006600, Train CE:0.011601, Train KL:8.770562, Val MSE:0.010282, Val CE:0.043597, Train ACC:1.000000, Val ACC:0.993750

Epoch 3984/4000: 100%|██████████| 1/1 [00:00<00:00, 23.29it/s]

epoch: 3983, beta = 0.000097, Train MSE: 0.006586, Train CE:0.011605, Train KL:8.770564, Val MSE:0.010257, Val CE:0.043612, Train ACC:1.000000, Val ACC:0.993750

Epoch 3985/4000: 100%|██████████| 1/1 [00:00<00:00, 22.75it/s]

epoch: 3984, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011602, Train KL:8.770567, Val MSE:0.010256, Val CE:0.043359, Train ACC:1.000000, Val ACC:0.993750

Epoch 3986/4000: 100%|██████████| 1/1 [00:00<00:00, 20.61it/s]

epoch: 3985, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011606, Train KL:8.770570, Val MSE:0.010256, Val CE:0.043232, Train ACC:1.000000, Val ACC:0.993750

Epoch 3987/4000: 100%|██████████| 1/1 [00:00<00:00, 23.20it/s]

epoch: 3986, beta = 0.000097, Train MSE: 0.006598, Train CE:0.011608, Train KL:8.770572, Val MSE:0.010282, Val CE:0.043472, Train ACC:1.000000, Val ACC:0.993750

Epoch 3988/4000: 100%|██████████| 1/1 [00:00<00:00, 23.66it/s]

epoch: 3987, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011609, Train KL:8.770575, Val MSE:0.010287, Val CE:0.043637, Train ACC:1.000000, Val ACC:0.993750

Epoch 3989/4000: 100%|██████████| 1/1 [00:00<00:00, 22.32it/s]

epoch: 3988, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011607, Train KL:8.770576, Val MSE:0.010260, Val CE:0.043546, Train ACC:1.000000, Val ACC:0.993750

Epoch 3990/4000: 100%|██████████| 1/1 [00:00<00:00, 22.15it/s]

epoch: 3989, beta = 0.000097, Train MSE: 0.006596, Train CE:0.011611, Train KL:8.770578, Val MSE:0.010296, Val CE:0.043433, Train ACC:1.000000, Val ACC:0.993750

Epoch 3991/4000: 100%|██████████| 1/1 [00:00<00:00, 24.62it/s]

epoch: 3990, beta = 0.000097, Train MSE: 0.006589, Train CE:0.011604, Train KL:8.770581, Val MSE:0.010238, Val CE:0.043368, Train ACC:1.000000, Val ACC:0.993750

Epoch 3992/4000: 100%|██████████| 1/1 [00:00<00:00, 25.91it/s]

epoch: 3991, beta = 0.000097, Train MSE: 0.006591, Train CE:0.011605, Train KL:8.770584, Val MSE:0.010280, Val CE:0.043739, Train ACC:1.000000, Val ACC:0.993750

Epoch 3993/4000: 100%|██████████| 1/1 [00:00<00:00, 23.44it/s]

epoch: 3992, beta = 0.000097, Train MSE: 0.006590, Train CE:0.011609, Train KL:8.770585, Val MSE:0.010283, Val CE:0.043401, Train ACC:1.000000, Val ACC:0.993750

Epoch 3994/4000: 100%|██████████| 1/1 [00:00<00:00, 19.64it/s]

epoch: 3993, beta = 0.000097, Train MSE: 0.006593, Train CE:0.011606, Train KL:8.770588, Val MSE:0.010280, Val CE:0.043651, Train ACC:1.000000, Val ACC:0.993750

Epoch 3995/4000: 100%|██████████| 1/1 [00:00<00:00, 20.98it/s]

epoch: 3994, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011610, Train KL:8.770590, Val MSE:0.010278, Val CE:0.043709, Train ACC:1.000000, Val ACC:0.993750

Epoch 3996/4000: 100%|██████████| 1/1 [00:00<00:00, 22.64it/s]

epoch: 3995, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011608, Train KL:8.770593, Val MSE:0.010237, Val CE:0.043472, Train ACC:1.000000, Val ACC:0.993750

Epoch 3997/4000: 100%|██████████| 1/1 [00:00<00:00, 21.86it/s]

epoch: 3996, beta = 0.000097, Train MSE: 0.006592, Train CE:0.011606, Train KL:8.770595, Val MSE:0.010281, Val CE:0.043536, Train ACC:1.000000, Val ACC:0.993750

Epoch 3998/4000: 100%|██████████| 1/1 [00:00<00:00, 23.67it/s]

epoch: 3997, beta = 0.000097, Train MSE: 0.006599, Train CE:0.011606, Train KL:8.770597, Val MSE:0.010272, Val CE:0.043518, Train ACC:1.000000, Val ACC:0.993750

Epoch 3999/4000: 100%|██████████| 1/1 [00:00<00:00, 23.61it/s]

epoch: 3998, beta = 0.000097, Train MSE: 0.006597, Train CE:0.011611, Train KL:8.770599, Val MSE:0.010248, Val CE:0.043354, Train ACC:1.000000, Val ACC:0.993750

Epoch 4000/4000: 100%|██████████| 1/1 [00:00<00:00, 23.57it/s]

epoch: 3999, beta = 0.000097, Train MSE: 0.006605, Train CE:0.011609, Train KL:8.770600, Val MSE:0.010328, Val CE:0.043549, Train ACC:1.000000, Val ACC:0.993750
Training time: 3.5954 mins
Successfully load and save the model!
Successfully save pretrained embeddings in disk!

In [16]:
%run main.py --method tabsyn --dataname etri_syn

Using device: cuda:0
C:\Users\lhj56\ws\etri\lhj\tabsyn\tabsyn/ckpt/etri_syn/
MLPDiffusion(
  (proj): Linear(in_features=1012, out_features=1024, bias=True)
  (mlp): Sequential(
    (0): Linear(in_features=1024, out_features=2048, bias=True)
    (1): SiLU()
    (2): Linear(in_features=2048, out_features=2048, bias=True)
    (3): SiLU()
    (4): Linear(in_features=2048, out_features=1024, bias=True)
    (5): SiLU()
    (6): Linear(in_features=1024, out_features=1012, bias=True)
  )
  (map_noise): PositionalEmbedding()
  (time_embed): Sequential(
    (0): Linear(in_features=1024, out_features=1024, bias=True)
    (1): SiLU()
    (2): Linear(in_features=1024, out_features=1024, bias=True)
  )
)
the number of parameters 12567540

Epoch 1/10001: 100%|██████████| 1/1 [00:02<00:00,  2.30s/it, Loss=1.56]
Epoch 2/10001: 100%|██████████| 1/1 [00:02<00:00,  2.07s/it, Loss=1.58]
Epoch 3/10001: 100%|██████████| 1/1 [00:02<00:00,  2.01s/it, Loss=1.53]
Epoch 4/10001: 100%|██████████| 1/1 [00:02<00:00,  2.12s/it, Loss=1.54]
Epoch 5/10001: 100%|██████████| 1/1 [00:02<00:00,  2.03s/it, Loss=1.47]
Epoch 6/10001: 100%|██████████| 1/1 [00:02<00:00,  2.15s/it, Loss=1.49]
Epoch 7/10001: 100%|██████████| 1/1 [00:02<00:00,  2.13s/it, Loss=1.43]
Epoch 8/10001: 100%|██████████| 1/1 [00:02<00:00,  2.05s/it, Loss=1.42]
Epoch 9/10001: 100%|██████████| 1/1 [00:02<00:00,  2.03s/it, Loss=1.36]
Epoch 10/10001: 100%|██████████| 1/1 [00:01<00:00,  1.97s/it, Loss=1.37]
Epoch 11/10001: 100%|██████████| 1/1 [00:02<00:00,  2.17s/it, Loss=1.29]
Epoch 12/10001: 100%|██████████| 1/1 [00:01<00:00,  1.95s/it, Loss=1.28]
Epoch 13/10001: 100%|██████████| 1/1 [00:02<00:00,  2.05s/it, Loss=1.28]
Epoch 14/10001: 100%|██████████| 1/1 [00:02<00:00,  2.02s/it, Loss=1.28]
Epoch 15/10001: 100%|██████████| 1/1 [00:02<00:00,  2.01s/it, Loss=1.22]
Epoch 16/10001: 100%|██████████| 1/1 [00:02<00:00,  2.12s/it, Loss=1.19]
Epoch 17/10001: 100%|██████████| 1/1 [00:02<00:00,  2.01s/it, Loss=1.2]
Epoch 18/10001: 100%|██████████| 1/1 [00:01<00:00,  1.95s/it, Loss=1.19]
Epoch 19/10001: 100%|██████████| 1/1 [00:02<00:00,  2.10s/it, Loss=1.22]
Epoch 20/10001: 100%|██████████| 1/1 [00:01<00:00,  1.92s/it, Loss=1.15]
Epoch 21/10001: 100%|██████████| 1/1 [00:02<00:00,  2.20s/it, Loss=1.15]
Epoch 22/10001: 100%|██████████| 1/1 [00:02<00:00,  2.00s/it, Loss=1.13]
Epoch 23/10001: 100%|██████████| 1/1 [00:02<00:00,  2.03s/it, Loss=1.13]
Epoch 24/10001: 100%|██████████| 1/1 [00:02<00:00,  2.05s/it, Loss=1.13]
Epoch 25/10001: 100%|██████████| 1/1 [00:02<00:00,  2.09s/it, Loss=1.1]
Epoch 26/10001: 100%|██████████| 1/1 [00:02<00:00,  2.12s/it, Loss=1.08]
Epoch 27/10001: 100%|██████████| 1/1 [00:02<00:00,  2.06s/it, Loss=1.1]
Epoch 28/10001: 100%|██████████| 1/1 [00:01<00:00,  1.96s/it, Loss=1.07]
Epoch 29/10001: 100%|██████████| 1/1 [00:02<00:00,  2.06s/it, Loss=1.06]
Epoch 30/10001: 100%|██████████| 1/1 [00:01<00:00,  1.99s/it, Loss=1.07]
Epoch 31/10001: 100%|██████████| 1/1 [00:02<00:00,  2.20s/it, Loss=1.07]
Epoch 32/10001: 100%|██████████| 1/1 [00:01<00:00,  1.98s/it, Loss=1.07]
Epoch 33/10001: 100%|██████████| 1/1 [00:02<00:00,  2.23s/it, Loss=1.03]
Epoch 34/10001: 100%|██████████| 1/1 [00:02<00:00,  2.09s/it, Loss=1.05]
Epoch 35/10001: 100%|██████████| 1/1 [00:02<00:00,  2.09s/it, Loss=1.01]
Epoch 36/10001: 100%|██████████| 1/1 [00:02<00:00,  2.07s/it, Loss=1.02]
Epoch 37/10001: 100%|██████████| 1/1 [00:02<00:00,  2.14s/it, Loss=0.999]
Epoch 38/10001: 100%|██████████| 1/1 [00:02<00:00,  2.04s/it, Loss=0.994]
Epoch 39/10001: 100%|██████████| 1/1 [00:02<00:00,  2.13s/it, Loss=0.965]
Epoch 40/10001: 100%|██████████| 1/1 [00:02<00:00,  2.05s/it, Loss=0.978]
Epoch 41/10001: 100%|██████████| 1/1 [00:02<00:00,  2.01s/it, Loss=0.983]
Epoch 42/10001: 100%|██████████| 1/1 [00:02<00:00,  2.05s/it, Loss=0.978]
Epoch 43/10001: 100%|██████████| 1/1 [00:01<00:00,  1.96s/it, Loss=0.986]
Epoch 44/10001: 100%|██████████| 1/1 [00:01<00:00,  1.99s/it, Loss=0.97]
Epoch 45/10001: 100%|██████████| 1/1 [00:01<00:00,  1.96s/it, Loss=0.973]
Epoch 46/10001: 100%|██████████| 1/1 [00:02<00:00,  2.10s/it, Loss=0.957]
Epoch 47/10001: 100%|██████████| 1/1 [00:02<00:00,  2.03s/it, Loss=0.97]
Epoch 48/10001: 100%|██████████| 1/1 [00:02<00:00,  2.05s/it, Loss=0.933]
Epoch 49/10001: 100%|██████████| 1/1 [00:01<00:00,  1.98s/it, Loss=0.942]
Epoch 50/10001: 100%|██████████| 1/1 [00:02<00:00,  2.09s/it, Loss=0.928]
Epoch 51/10001: 100%|██████████| 1/1 [00:02<00:00,  2.04s/it, Loss=0.93]
Epoch 52/10001: 100%|██████████| 1/1 [00:02<00:00,  2.11s/it, Loss=0.924]
Epoch 53/10001: 100%|██████████| 1/1 [00:01<00:00,  2.00s/it, Loss=0.913]
Epoch 54/10001: 100%|██████████| 1/1 [00:02<00:00,  2.09s/it, Loss=0.919]
Epoch 55/10001: 100%|██████████| 1/1 [00:02<00:00,  2.06s/it, Loss=0.897]
Epoch 56/10001: 100%|██████████| 1/1 [00:02<00:00,  2.12s/it, Loss=0.906]
Epoch 57/10001: 100%|██████████| 1/1 [00:02<00:00,  2.01s/it, Loss=0.908]
Epoch 58/10001: 100%|██████████| 1/1 [00:02<00:00,  2.09s/it, Loss=0.895]
Epoch 59/10001: 100%|██████████| 1/1 [00:01<00:00,  1.98s/it, Loss=0.882]
Epoch 60/10001: 100%|██████████| 1/1 [00:02<00:00,  2.08s/it, Loss=0.874]
Epoch 61/10001: 100%|██████████| 1/1 [00:02<00:00,  2.09s/it, Loss=0.885]
Epoch 62/10001: 100%|██████████| 1/1 [00:02<00:00,  2.09s/it, Loss=0.909]
Epoch 63/10001: 100%|██████████| 1/1 [00:01<00:00,  1.95s/it, Loss=0.878]
Epoch 64/10001: 100%|██████████| 1/1 [00:02<00:00,  2.07s/it, Loss=0.863]
Epoch 65/10001: 100%|██████████| 1/1 [00:02<00:00,  2.06s/it, Loss=0.863]
Epoch 66/10001: 100%|██████████| 1/1 [00:02<00:00,  2.07s/it, Loss=0.869]
Epoch 67/10001: 100%|██████████| 1/1 [00:01<00:00,  1.97s/it, Loss=0.857]
Epoch 68/10001: 100%|██████████| 1/1 [00:02<00:00,  2.09s/it, Loss=0.846]
Epoch 69/10001: 100%|██████████| 1/1 [00:01<00:00,  1.96s/it, Loss=0.849]
Epoch 70/10001: 100%|██████████| 1/1 [00:01<00:00,  2.00s/it, Loss=0.866]
Epoch 71/10001: 100%|██████████| 1/1 [00:02<00:00,  2.09s/it, Loss=0.851]
Epoch 72/10001: 100%|██████████| 1/1 [00:02<00:00,  2.05s/it, Loss=0.856]
Epoch 73/10001: 100%|██████████| 1/1 [00:01<00:00,  1.97s/it, Loss=0.837]
Epoch 74/10001: 100%|██████████| 1/1 [00:02<00:00,  2.08s/it, Loss=0.842]
Epoch 75/10001: 100%|██████████| 1/1 [00:01<00:00,  1.96s/it, Loss=0.853]
Epoch 76/10001: 100%|██████████| 1/1 [00:02<00:00,  2.11s/it, Loss=0.834]
Epoch 77/10001: 100%|██████████| 1/1 [00:02<00:00,  2.03s/it, Loss=0.829]
Epoch 78/10001: 100%|██████████| 1/1 [00:02<00:00,  2.05s/it, Loss=0.854]
Epoch 79/10001: 100%|██████████| 1/1 [00:01<00:00,  1.99s/it, Loss=0.838]
Epoch 80/10001: 100%|██████████| 1/1 [00:02<00:00,  2.10s/it, Loss=0.832]
Epoch 81/10001: 100%|██████████| 1/1 [00:02<00:00,  2.02s/it, Loss=0.855]
Epoch 82/10001: 100%|██████████| 1/1 [00:02<00:00,  2.04s/it, Loss=0.829]
Epoch 83/10001: 100%|██████████| 1/1 [00:01<00:00,  1.92s/it, Loss=0.806]
Epoch 84/10001: 100%|██████████| 1/1 [00:02<00:00,  2.10s/it, Loss=0.836]
Epoch 85/10001: 100%|██████████| 1/1 [00:01<00:00,  1.94s/it, Loss=0.829]
Epoch 86/10001: 100%|██████████| 1/1 [00:02<00:00,  2.07s/it, Loss=0.818]
Epoch 87/10001: 100%|██████████| 1/1 [00:01<00:00,  1.97s/it, Loss=0.812]
Epoch 88/10001: 100%|██████████| 1/1 [00:02<00:00,  2.06s/it, Loss=0.813]
Epoch 89/10001: 100%|██████████| 1/1 [00:01<00:00,  1.98s/it, Loss=0.83]
Epoch 90/10001: 100%|██████████| 1/1 [00:02<00:00,  2.04s/it, Loss=0.842]
Epoch 91/10001: 100%|██████████| 1/1 [00:02<00:00,  2.08s/it, Loss=0.808]
Epoch 92/10001: 100%|██████████| 1/1 [00:02<00:00,  2.04s/it, Loss=0.828]
Epoch 93/10001: 100%|██████████| 1/1 [00:01<00:00,  1.93s/it, Loss=0.799]
Epoch 94/10001: 100%|██████████| 1/1 [00:02<00:00,  2.08s/it, Loss=0.818]
Epoch 95/10001: 100%|██████████| 1/1 [00:02<00:00,  2.06s/it, Loss=0.785]
Epoch 96/10001: 100%|██████████| 1/1 [00:02<00:00,  2.13s/it, Loss=0.791]
Epoch 97/10001: 100%|██████████| 1/1 [00:01<00:00,  1.99s/it, Loss=0.788]
Epoch 98/10001: 100%|██████████| 1/1 [00:02<00:00,  2.04s/it, Loss=0.794]
Epoch 99/10001: 100%|██████████| 1/1 [00:01<00:00,  1.96s/it, Loss=0.772]
Epoch 100/10001: 100%|██████████| 1/1 [00:02<00:00,  2.09s/it, Loss=0.793]
Epoch 101/10001: 100%|██████████| 1/1 [00:02<00:00,  2.07s/it, Loss=0.772]
Epoch 102/10001: 100%|██████████| 1/1 [00:02<00:00,  2.06s/it, Loss=0.81]
Epoch 103/10001: 100%|██████████| 1/1 [00:02<00:00,  2.02s/it, Loss=0.802]
Epoch 104/10001: 100%|██████████| 1/1 [00:02<00:00,  2.00s/it, Loss=0.808]
Epoch 105/10001: 100%|██████████| 1/1 [00:01<00:00,  1.97s/it, Loss=0.805]
Epoch 106/10001: 100%|██████████| 1/1 [00:02<00:00,  2.11s/it, Loss=0.795]
Epoch 107/10001: 100%|██████████| 1/1 [00:01<00:00,  1.94s/it, Loss=0.778]
Epoch 108/10001: 100%|██████████| 1/1 [00:02<00:00,  2.02s/it, Loss=0.797]
Epoch 109/10001: 100%|██████████| 1/1 [00:01<00:00,  1.99s/it, Loss=0.777]
Epoch 110/10001: 100%|██████████| 1/1 [00:02<00:00,  2.03s/it, Loss=0.792]
Epoch 111/10001: 100%|██████████| 1/1 [00:02<00:00,  2.03s/it, Loss=0.768]
Epoch 112/10001: 100%|██████████| 1/1 [00:02<00:00,  2.12s/it, Loss=0.791]
Epoch 113/10001: 100%|██████████| 1/1 [00:02<00:00,  2.04s/it, Loss=0.786]
Epoch 114/10001: 100%|██████████| 1/1 [00:01<00:00,  1.99s/it, Loss=0.769]
Epoch 115/10001: 100%|██████████| 1/1 [00:02<00:00,  2.01s/it, Loss=0.76]
Epoch 116/10001: 100%|██████████| 1/1 [00:02<00:00,  2.17s/it, Loss=0.789]
Epoch 117/10001: 100%|██████████| 1/1 [00:01<00:00,  1.99s/it, Loss=0.768]
Epoch 118/10001: 100%|██████████| 1/1 [00:01<00:00,  1.98s/it, Loss=0.738]
Epoch 119/10001: 100%|██████████| 1/1 [00:02<00:00,  2.11s/it, Loss=0.777]
Epoch 120/10001: 100%|██████████| 1/1 [00:01<00:00,  1.97s/it, Loss=0.77]
Epoch 121/10001: 100%|██████████| 1/1 [00:02<00:00,  2.11s/it, Loss=0.772]
Epoch 122/10001: 100%|██████████| 1/1 [00:01<00:00,  1.97s/it, Loss=0.774]
Epoch 123/10001: 100%|██████████| 1/1 [00:02<00:00,  2.03s/it, Loss=0.747]
Epoch 124/10001: 100%|██████████| 1/1 [00:01<00:00,  1.98s/it, Loss=0.787]
Epoch 125/10001: 100%|██████████| 1/1 [00:01<00:00,  1.99s/it, Loss=0.754]
Epoch 126/10001: 100%|██████████| 1/1 [00:02<00:00,  2.06s/it, Loss=0.774]
Epoch 127/10001: 100%|██████████| 1/1 [00:02<00:00,  2.06s/it, Loss=0.761]
Epoch 128/10001: 100%|██████████| 1/1 [00:01<00:00,  1.93s/it, Loss=0.774]
Epoch 129/10001: 100%|██████████| 1/1 [00:02<00:00,  2.01s/it, Loss=0.758]
Epoch 130/10001: 100%|██████████| 1/1 [00:01<00:00,  1.92s/it, Loss=0.76]
Epoch 131/10001: 100%|██████████| 1/1 [00:02<00:00,  2.09s/it, Loss=0.758]
Epoch 132/10001: 100%|██████████| 1/1 [00:01<00:00,  1.99s/it, Loss=0.767]
Epoch 133/10001: 100%|██████████| 1/1 [00:02<00:00,  2.06s/it, Loss=0.759]
Epoch 134/10001: 100%|██████████| 1/1 [00:01<00:00,  1.98s/it, Loss=0.744]
Epoch 135/10001: 100%|██████████| 1/1 [00:02<00:00,  2.03s/it, Loss=0.757]
Epoch 136/10001: 100%|██████████| 1/1 [00:02<00:00,  2.02s/it, Loss=0.729]
Epoch 137/10001: 100%|██████████| 1/1 [00:02<00:00,  2.12s/it, Loss=0.78]
Epoch 138/10001: 100%|██████████| 1/1 [00:02<00:00,  2.00s/it, Loss=0.762]
Epoch 139/10001: 100%|██████████| 1/1 [00:01<00:00,  1.96s/it, Loss=0.74]
Epoch 140/10001: 100%|██████████| 1/1 [00:02<00:00,  2.05s/it, Loss=0.715]
Epoch 141/10001: 100%|██████████| 1/1 [00:02<00:00,  2.16s/it, Loss=0.751]
Epoch 142/10001: 100%|██████████| 1/1 [00:02<00:00,  2.07s/it, Loss=0.734]
Epoch 143/10001: 100%|██████████| 1/1 [00:01<00:00,  1.98s/it, Loss=0.741]
Epoch 144/10001: 100%|██████████| 1/1 [00:02<00:00,  2.05s/it, Loss=0.734]
Epoch 145/10001: 100%|██████████| 1/1 [00:01<00:00,  1.99s/it, Loss=0.802]
Epoch 146/10001: 100%|██████████| 1/1 [00:02<00:00,  2.14s/it, Loss=0.744]
Epoch 147/10001: 100%|██████████| 1/1 [00:01<00:00,  1.99s/it, Loss=0.754]
Epoch 148/10001: 100%|██████████| 1/1 [00:02<00:00,  2.05s/it, Loss=0.771]
Epoch 149/10001: 100%|██████████| 1/1 [00:01<00:00,  2.00s/it, Loss=0.733]
Epoch 150/10001: 100%|██████████| 1/1 [00:02<00:00,  2.05s/it, Loss=0.743]
Epoch 151/10001: 100%|██████████| 1/1 [00:02<00:00,  2.06s/it, Loss=0.747]
Epoch 152/10001: 100%|██████████| 1/1 [00:02<00:00,  2.06s/it, Loss=0.74]
Epoch 153/10001: 100%|██████████| 1/1 [00:01<00:00,  1.96s/it, Loss=0.77]
Epoch 154/10001: 100%|██████████| 1/1 [00:02<00:00,  2.03s/it, Loss=0.743]
Epoch 155/10001: 100%|██████████| 1/1 [00:01<00:00,  1.95s/it, Loss=0.753]
Epoch 156/10001: 100%|██████████| 1/1 [00:02<00:00,  2.05s/it, Loss=0.76]
Epoch 157/10001: 100%|██████████| 1/1 [00:01<00:00,  1.92s/it, Loss=0.751]
Epoch 158/10001: 100%|██████████| 1/1 [00:02<00:00,  2.02s/it, Loss=0.783]
Epoch 159/10001: 100%|██████████| 1/1 [00:01<00:00,  1.97s/it, Loss=0.735]
Epoch 160/10001: 100%|██████████| 1/1 [00:02<00:00,  2.00s/it, Loss=0.769]
Epoch 161/10001: 100%|██████████| 1/1 [00:02<00:00,  2.04s/it, Loss=0.769]
Epoch 162/10001: 100%|██████████| 1/1 [00:02<00:00,  2.05s/it, Loss=0.765]
Epoch 163/10001: 100%|██████████| 1/1 [00:01<00:00,  1.99s/it, Loss=0.757]
Epoch 164/10001: 100%|██████████| 1/1 [00:01<00:00,  1.99s/it, Loss=0.775]
Epoch 165/10001: 100%|██████████| 1/1 [00:01<00:00,  1.95s/it, Loss=0.754]
Epoch 166/10001: 100%|██████████| 1/1 [00:02<00:00,  2.11s/it, Loss=0.723]
Epoch 167/10001: 100%|██████████| 1/1 [00:01<00:00,  1.97s/it, Loss=0.763]
Epoch 168/10001: 100%|██████████| 1/1 [00:02<00:00,  2.02s/it, Loss=0.752]
Epoch 169/10001: 100%|██████████| 1/1 [00:01<00:00,  1.92s/it, Loss=0.735]
Epoch 170/10001: 100%|██████████| 1/1 [00:02<00:00,  2.04s/it, Loss=0.754]
Epoch 171/10001: 100%|██████████| 1/1 [00:02<00:00,  2.04s/it, Loss=0.739]
Epoch 172/10001: 100%|██████████| 1/1 [00:02<00:00,  2.06s/it, Loss=0.729]
Epoch 173/10001: 100%|██████████| 1/1 [00:01<00:00,  1.96s/it, Loss=0.738]
Epoch 174/10001: 100%|██████████| 1/1 [00:02<00:00,  2.06s/it, Loss=0.73]
Epoch 175/10001: 100%|██████████| 1/1 [00:02<00:00,  2.02s/it, Loss=0.725]
Epoch 176/10001: 100%|██████████| 1/1 [00:02<00:00,  2.16s/it, Loss=0.759]
Epoch 177/10001: 100%|██████████| 1/1 [00:01<00:00,  1.96s/it, Loss=0.76]
Epoch 178/10001: 100%|██████████| 1/1 [00:02<00:00,  2.12s/it, Loss=0.755]
Epoch 179/10001: 100%|██████████| 1/1 [00:02<00:00,  2.01s/it, Loss=0.744]
Epoch 180/10001: 100%|██████████| 1/1 [00:02<00:00,  2.17s/it, Loss=0.717]
Epoch 181/10001: 100%|██████████| 1/1 [00:02<00:00,  2.10s/it, Loss=0.749]
Epoch 182/10001: 100%|██████████| 1/1 [00:02<00:00,  2.07s/it, Loss=0.751]
Epoch 183/10001: 100%|██████████| 1/1 [00:01<00:00,  1.98s/it, Loss=0.768]
Epoch 184/10001: 100%|██████████| 1/1 [00:02<00:00,  2.13s/it, Loss=0.751]
Epoch 185/10001: 100%|██████████| 1/1 [00:02<00:00,  2.04s/it, Loss=0.714]
Epoch 186/10001: 100%|██████████| 1/1 [00:02<00:00,  2.24s/it, Loss=0.728]
Epoch 187/10001: 100%|██████████| 1/1 [00:01<00:00,  1.99s/it, Loss=0.742]
Epoch 188/10001: 100%|██████████| 1/1 [00:02<00:00,  2.13s/it, Loss=0.734]
Epoch 189/10001: 100%|██████████| 1/1 [00:01<00:00,  1.95s/it, Loss=0.711]
Epoch 190/10001: 100%|██████████| 1/1 [00:02<00:00,  2.17s/it, Loss=0.726]
Epoch 191/10001: 100%|██████████| 1/1 [00:02<00:00,  2.12s/it, Loss=0.741]
Epoch 192/10001: 100%|██████████| 1/1 [00:02<00:00,  2.00s/it, Loss=0.738]
Epoch 193/10001: 100%|██████████| 1/1 [00:02<00:00,  2.04s/it, Loss=0.734]
Epoch 194/10001: 100%|██████████| 1/1 [00:01<00:00,  1.98s/it, Loss=0.746]
Epoch 195/10001: 100%|██████████| 1/1 [00:02<00:00,  2.02s/it, Loss=0.713]
Epoch 196/10001: 100%|██████████| 1/1 [00:02<00:00,  2.03s/it, Loss=0.718]
Epoch 197/10001: 100%|██████████| 1/1 [00:02<00:00,  2.04s/it, Loss=0.734]
Epoch 198/10001: 100%|██████████| 1/1 [00:01<00:00,  1.98s/it, Loss=0.737]
Epoch 199/10001: 100%|██████████| 1/1 [00:02<00:00,  2.05s/it, Loss=0.73]
Epoch 200/10001: 100%|██████████| 1/1 [00:01<00:00,  1.97s/it, Loss=0.771]
Epoch 201/10001: 100%|██████████| 1/1 [00:02<00:00,  2.09s/it, Loss=0.741]
Epoch 202/10001: 100%|██████████| 1/1 [00:02<00:00,  2.03s/it, Loss=0.728]
Epoch 203/10001: 100%|██████████| 1/1 [00:02<00:00,  2.03s/it, Loss=0.691]
Epoch 204/10001: 100%|██████████| 1/1 [00:02<00:00,  2.05s/it, Loss=0.689]
Epoch 205/10001: 100%|██████████| 1/1 [00:02<00:00,  2.06s/it, Loss=0.75]
Epoch 206/10001: 100%|██████████| 1/1 [00:02<00:00,  2.04s/it, Loss=0.721]
Epoch 207/10001: 100%|██████████| 1/1 [00:02<00:00,  2.07s/it, Loss=0.732]
Epoch 208/10001: 100%|██████████| 1/1 [00:01<00:00,  1.97s/it, Loss=0.745]
Epoch 209/10001: 100%|██████████| 1/1 [00:02<00:00,  2.03s/it, Loss=0.72]
Epoch 210/10001: 100%|██████████| 1/1 [00:01<00:00,  1.99s/it, Loss=0.706]
Epoch 211/10001: 100%|██████████| 1/1 [00:02<00:00,  2.10s/it, Loss=0.721]
Epoch 212/10001: 100%|██████████| 1/1 [00:01<00:00,  1.99s/it, Loss=0.717]
Epoch 213/10001: 100%|██████████| 1/1 [00:02<00:00,  2.06s/it, Loss=0.698]
Epoch 214/10001: 100%|██████████| 1/1 [00:01<00:00,  1.93s/it, Loss=0.72]
Epoch 215/10001: 100%|██████████| 1/1 [00:01<00:00,  2.00s/it, Loss=0.707]
Epoch 216/10001: 100%|██████████| 1/1 [00:02<00:00,  2.01s/it, Loss=0.702]
Epoch 217/10001: 100%|██████████| 1/1 [00:02<00:00,  2.01s/it, Loss=0.704]
Epoch 218/10001: 100%|██████████| 1/1 [00:01<00:00,  1.96s/it, Loss=0.749]
Epoch 219/10001: 100%|██████████| 1/1 [00:02<00:00,  2.05s/it, Loss=0.714]
Epoch 220/10001: 100%|██████████| 1/1 [00:01<00:00,  1.93s/it, Loss=0.764]
Epoch 221/10001: 100%|██████████| 1/1 [00:02<00:00,  2.12s/it, Loss=0.732]
Epoch 222/10001: 100%|██████████| 1/1 [00:01<00:00,  1.98s/it, Loss=0.704]
Epoch 223/10001: 100%|██████████| 1/1 [00:02<00:00,  2.04s/it, Loss=0.728]
Epoch 224/10001: 100%|██████████| 1/1 [00:01<00:00,  1.94s/it, Loss=0.727]
Epoch 225/10001: 100%|██████████| 1/1 [00:02<00:00,  2.05s/it, Loss=0.745]
Epoch 226/10001: 100%|██████████| 1/1 [00:01<00:00,  2.00s/it, Loss=0.731]
Epoch 227/10001: 100%|██████████| 1/1 [00:01<00:00,  1.99s/it, Loss=0.719]
Epoch 228/10001: 100%|██████████| 1/1 [00:01<00:00,  2.00s/it, Loss=0.702]
Epoch 229/10001: 100%|██████████| 1/1 [00:02<00:00,  2.05s/it, Loss=0.723]
Epoch 230/10001: 100%|██████████| 1/1 [00:01<00:00,  1.95s/it, Loss=0.728]
Epoch 231/10001: 100%|██████████| 1/1 [00:02<00:00,  2.10s/it, Loss=0.699]
Epoch 232/10001: 100%|██████████| 1/1 [00:02<00:00,  2.00s/it, Loss=0.71]
Epoch 233/10001: 100%|██████████| 1/1 [00:02<00:00,  2.06s/it, Loss=0.707]
Epoch 234/10001: 100%|██████████| 1/1 [00:01<00:00,  1.94s/it, Loss=0.701]
Epoch 235/10001: 100%|██████████| 1/1 [00:02<00:00,  2.04s/it, Loss=0.745]
Epoch 236/10001: 100%|██████████| 1/1 [00:02<00:00,  2.05s/it, Loss=0.722]
Epoch 237/10001: 100%|██████████| 1/1 [00:02<00:00,  2.04s/it, Loss=0.712]
Epoch 238/10001: 100%|██████████| 1/1 [00:01<00:00,  1.98s/it, Loss=0.76]
Epoch 239/10001: 100%|██████████| 1/1 [00:02<00:00,  2.04s/it, Loss=0.699]
Epoch 240/10001: 100%|██████████| 1/1 [00:02<00:00,  2.01s/it, Loss=0.741]
Epoch 241/10001: 100%|██████████| 1/1 [00:02<00:00,  2.13s/it, Loss=0.725]
Epoch 242/10001: 100%|██████████| 1/1 [00:01<00:00,  1.97s/it, Loss=0.765]
Epoch 243/10001: 100%|██████████| 1/1 [00:02<00:00,  2.02s/it, Loss=0.696]
Epoch 244/10001: 100%|██████████| 1/1 [00:01<00:00,  1.98s/it, Loss=0.741]
Epoch 245/10001: 100%|██████████| 1/1 [00:02<00:00,  2.04s/it, Loss=0.719]
Epoch 246/10001: 100%|██████████| 1/1 [00:02<00:00,  2.04s/it, Loss=0.731]
Epoch 247/10001: 100%|██████████| 1/1 [00:02<00:00,  2.02s/it, Loss=0.715]
Epoch 248/10001: 100%|██████████| 1/1 [00:01<00:00,  1.93s/it, Loss=0.714]
Epoch 249/10001: 100%|██████████| 1/1 [00:01<00:00,  1.98s/it, Loss=0.709]
Epoch 250/10001: 100%|██████████| 1/1 [00:01<00:00,  2.00s/it, Loss=0.707]
Epoch 251/10001: 100%|██████████| 1/1 [00:02<00:00,  2.12s/it, Loss=0.712]
Epoch 252/10001: 100%|██████████| 1/1 [00:01<00:00,  1.98s/it, Loss=0.698]
Epoch 253/10001: 100%|██████████| 1/1 [00:02<00:00,  2.01s/it, Loss=0.699]
Epoch 254/10001: 100%|██████████| 1/1 [00:02<00:00,  2.00s/it, Loss=0.717]
Epoch 255/10001: 100%|██████████| 1/1 [00:02<00:00,  2.02s/it, Loss=0.72]
Epoch 256/10001: 100%|██████████| 1/1 [00:02<00:00,  2.05s/it, Loss=0.707]
Epoch 257/10001: 100%|██████████| 1/1 [00:02<00:00,  2.07s/it, Loss=0.72]
Epoch 258/10001: 100%|██████████| 1/1 [00:01<00:00,  1.92s/it, Loss=0.686]
Epoch 259/10001: 100%|██████████| 1/1 [00:02<00:00,  2.09s/it, Loss=0.741]
Epoch 260/10001: 100%|██████████| 1/1 [00:01<00:00,  1.99s/it, Loss=0.706]
Epoch 261/10001: 100%|██████████| 1/1 [00:02<00:00,  2.11s/it, Loss=0.691]
Epoch 262/10001: 100%|██████████| 1/1 [00:01<00:00,  1.99s/it, Loss=0.693]
Epoch 263/10001: 100%|██████████| 1/1 [00:02<00:00,  2.05s/it, Loss=0.706]
Epoch 264/10001: 100%|██████████| 1/1 [00:02<00:00,  2.00s/it, Loss=0.676]
Epoch 265/10001: 100%|██████████| 1/1 [00:02<00:00,  2.10s/it, Loss=0.692]
Epoch 266/10001: 100%|██████████| 1/1 [00:02<00:00,  2.06s/it, Loss=0.703]
Epoch 267/10001: 100%|██████████| 1/1 [00:02<00:00,  2.02s/it, Loss=0.702]
Epoch 268/10001: 100%|██████████| 1/1 [00:01<00:00,  1.96s/it, Loss=0.7]

Early stopping
Time:  3050.0711629390717

In [17]:
!mkdir -p ./etri/synthetic/
%run main.py --method tabsyn --dataname etri_syn --mode sample --save_path ./synthetic/etri_syn.csv --num_samples 1000

���� ������ �ùٸ��� �ʽ��ϴ�.

Using device: cuda:0
Generating 1000 samples...
(1000, 15)
Time: 1.314455509185791
Saving sampled data to ./synthetic/etri_syn.csv

In [18]:
train = train2.copy()
test = test2.copy()

In [19]:
train.shape, train.dtypes

((450, 252),
 subject_id                               object
 sleep_date                               object
 lifelog_date                             object
 Q1                                        int64
 Q2                                        int64
 Q3                                        int64
 S1                                        int64
 S2                                        int64
 S3                                        int64
 charging_ratio                          float64
 charging_sum                            float64
 charging_transitions                    float64
 avg_charging_duration                   float64
 max_charging_duration                   float64
 sleep_charging_ratio                    float64
 sleep_charging_sum                      float64
 sleep_charging_transitions              float64
 sleep_avg_charging_duration             float64
 sleep_max_charging_duration             float64
 walking_minutes                         float64
 vehicle_minutes                         float64
 activity_minutes                        float64
 sleep_walking_minutes                   float64
 sleep_vehicle_minutes                   float64
 sleep_activity_minutes                  float64
 m_activity@240min@std@00h00m            float64
 m_activity@240min@std@04h00m            float64
 m_activity@240min@std@08h00m            float64
 m_activity@240min@std@12h00m            float64
 m_activity@240min@std@16h00m            float64
 m_activity@240min@std@20h00m            float64
 m_activity_met@240min@std@00h00m        float64
 m_activity_met@240min@std@04h00m        float64
 m_activity_met@240min@std@08h00m        float64
 m_activity_met@240min@std@12h00m        float64
 m_activity_met@240min@std@16h00m        float64
 m_activity_met@240min@std@20h00m        float64
 m_activity_met@240min@sum@00h00m        float64
 m_activity_met@240min@sum@04h00m        float64
 m_activity_met@240min@sum@08h00m        float64
 m_activity_met@240min@sum@12h00m        float64
 m_activity_met@240min@sum@16h00m        float64
 m_activity_met@240min@sum@20h00m        float64
 m_activity_0@240min@std@00h00m          float64
 m_activity_0@240min@std@04h00m          float64
 m_activity_0@240min@std@08h00m          float64
 m_activity_0@240min@std@12h00m          float64
 m_activity_0@240min@std@16h00m          float64
 m_activity_0@240min@std@20h00m          float64
 m_activity_0@240min@sum@00h00m          float64
 m_activity_0@240min@sum@04h00m          float64
 m_activity_0@240min@sum@08h00m          float64
 m_activity_0@240min@sum@12h00m          float64
 m_activity_0@240min@sum@16h00m          float64
 m_activity_0@240min@sum@20h00m          float64
 active_hour_unique_label_count          float64
 active_hour_snor_count                  float64
 sleep_hour_unique_label_count           float64
 sleep_hour_snor_count                   float64
 work_hour_rssi_mean                     float64
 work_hour_rssi_min                      float64
 work_hour_rssi_max                      float64
 work_hour_others_ratio                  float64
 work_hour_unknown_ratio                 float64
 free_hour_rssi_mean                     float64
 free_hour_rssi_min                      float64
 free_hour_rssi_max                      float64
 free_hour_others_ratio                  float64
 free_hour_unknown_ratio                 float64
 sleep_hour_rssi_mean                    float64
 sleep_hour_rssi_min                     float64
 sleep_hour_rssi_max                     float64
 sleep_hour_others_ratio                 float64
 sleep_hour_unknown_ratio                float64
 active_hour_walk_minutes                float64
 active_hour_jog_minutes                 float64
 active_hour_vehicle_minutes             float64
 active_hour_mean_speed                  float64
 active_hour_max_speed                   float64
 active_hour_min_speed                   float64
 active_hour_distance_x                  float64
 exercise_flag                           float64
 sleep_hour_walk_minutes                 float64
 sleep_hour_jog_minutes                  float64
 sleep_hour_vehicle_minutes              float64
 sleep_hour_mean_speed                   float64
 sleep_hour_max_speed                    float64
 sleep_hour_min_speed                    float64
 sleep_hour_distance_x                   float64
 mgps_first_wakeup_minutes               float64
 light_mean                              float64
 light_std                               float64
 light_max                               float64
 light_min                               float64
 light_night_mean                        float64
 light_day_mean                          float64
 light_night_ratio                       float64
 sleep_duration_min_mLight               float64
 sleep_time_min_mLight                   float64
 wake_time_min_mLight                    float64
 hour_slept_mLight                       float64
 hour_woke_up_mLight                     float64
 sleep_duration_interp_mLight            float64
 sleep_duration_hour_mLight              float64
 sleep_duration_interp_hour_mLight       float64
 light_sleep_time                        float64
 light_wake_time                         float64
 light_sleep_duration_min                float64
 light_weekday                           float64
 light_month                             float64
 light_avg_sleep_time                    float64
 light_avg_wake_time                     float64
 light_avg_sleep_duration                float64
 light_sleep_time_diff                   float64
 light_wake_time_diff                    float64
 light_sleep_duration_diff               float64
 light_sleep_time_ratio                  float64
 light_wake_time_ratio                   float64
 light_sleep_duration_ratio              float64
 light_sleep_time_lag1                   float64
 light_sleep_duration_lag1               float64
 light_sleep_time_diff_lag1              float64
 light_wake_time_diff_lag1               float64
 light_sleep_duration_diff_lag1          float64
 light_sleep_time_lag2                   float64
 light_wake_time_lag2                    float64
 light_sleep_duration_lag2               float64
 light_sleep_time_diff_lag2              float64
 light_wake_time_diff_lag2               float64
 light_sleep_duration_diff_lag2          float64
 light_week_type_lag1                     object
 light_rolling_sleep_time_2d             float64
 light_rolling_wake_time_2d              float64
 light_rolling_sleep_duration_2d         float64
 light_rolling_sleep_time_3d             float64
 light_rolling_wake_time_3d              float64
 light_rolling_sleep_duration_3d         float64
 light_weekday_avg_sleep                 float64
 light_sleep_duration_vs_weekday_avg     float64
 light_is_sleep_duration_change_large    float64
 lights_off_time                         float64
 sleep_time                              float64
 wake_time                               float64
 sleep_duration_min                      float64
 weekday                                 float64
 week_type                                object
 month                                   float64
 avg_sleep_time                          float64
 avg_wake_time                           float64
 avg_sleep_duration                      float64
 sleep_time_diff                         float64
 wake_time_diff                          float64
 sleep_duration_diff                     float64
 sleep_time_ratio                        float64
 wake_time_ratio                         float64
 sleep_duration_ratio                    float64
 sleep_time_lag1                         float64
 wake_time_lag1                          float64
 sleep_duration_lag1                     float64
 sleep_time_diff_lag1                    float64
 wake_time_diff_lag1                     float64
 sleep_duration_diff_lag1                float64
 sleep_time_lag2                         float64
 wake_time_lag2                          float64
 sleep_duration_lag2                     float64
 sleep_time_diff_lag2                    float64
 wake_time_diff_lag2                     float64
 sleep_duration_diff_lag2                float64
 week_type_lag1                           object
 rolling_sleep_time_2d                   float64
 rolling_wake_time_2d                    float64
 rolling_sleep_duration_2d               float64
 rolling_sleep_time_3d                   float64
 rolling_wake_time_3d                    float64
 rolling_sleep_duration_3d               float64
 weekday_avg_sleep                       float64
 sleep_duration_vs_weekday_avg           float64
 is_sleep_duration_change_large          float64
 activehour_통화_time                      float64
 beforebed_통화_time                       float64
 activehour_전화_time                      float64
 beforebed_전화_time                       float64
 activehour_YouTube_time                 float64
 beforebed_YouTube_time                  float64
 activehour_메신저_time                     float64
 beforebed_메신저_time                      float64
 activehour_NAVER_time                   float64
 beforebed_NAVER_time                    float64
 activehour_캐시워크_time                    float64
 beforebed_캐시워크_time                     float64
 activehour_성경일독Q_time                   float64
 beforebed_성경일독Q_time                    float64
 activehour_OneUI홈_time                  float64
 beforebed_OneUI홈_time                   float64
 activehour_unique_app_count             float64
 beforebed_unique_app_count              float64
 activehour_total_screen_time            float64
 beforebed_total_screen_time             float64
 activehour_screen_time_vs_avg_pct       float64
 beforebed_screen_time_vs_avg_pct        float64
 activehour_scan_count                   float64
 beforebed_scan_count                    float64
 activehour_unique_bssid_count           float64
 beforebed_unique_bssid_count            float64
 activehour_avg_rssi                     float64
 beforebed_avg_rssi                      float64
 activehour_max_rssi                     float64
 beforebed_max_rssi                      float64
 activehour_min_rssi                     float64
 beforebed_min_rssi                      float64
 activehour_strong_signal_ratio          float64
 beforebed_strong_signal_ratio           float64
 activehour_empty_scan_count             float64
 beforebed_empty_scan_count              float64
 activehour_top_bssid                     object
 beforebed_top_bssid                      object
 activehour_top_bssid_count              float64
 beforebed_top_bssid_count               float64
 activehour_hour_span_minutes            float64
 beforebed_hour_span_minutes             float64
 active_hour_mean_hr                     float64
 active_hour_min_hr                      float64
 active_hour_max_hr                      float64
 active_hour_std_hr                      float64
 active_hour_high_hr                     float64
 sleep_hour_mean_hr                      float64
 sleep_hour_min_hr                       float64
 sleep_hour_max_hr                       float64
 sleep_hour_std_hr                       float64
 sleep_hour_high_hr                      float64
 active_hour_mean_light                  float64
 active_hour_min_light                   float64
 active_hour_max_light                   float64
 active_hour_std_light                   float64
 sleep_hour_mean_light                   float64
 sleep_hour_min_light                    float64
 sleep_hour_max_light                    float64
 sleep_hour_std_light                    float64
 mlight_first_sleep_minutes              float64
 mlight_first_wakeup_minutes             float64
 active_hour_steps                       float64
 active_hour_distance_y                  float64
 active_hour_burned_calories             float64
 sleep_hour_steps                        float64
 sleep_hour_distance_y                   float64
 sleep_hour_burned_calories              float64
 m_light_awake_minutes                   float64
 m_light_awake_blocks                    float64
 w_light_awake_minutes                   float64
 w_light_awake_blocks                    float64
 light_awake_minutes                     float64
 light_awake_blocks                      float64
 dtype: object)

In [20]:
ori_syn_df = pd.read_csv("./synthetic/etri_syn.csv")

In [21]:
def sync_df(df, dtypes: dict):
    df = df.copy()
    for col, dtype in dtypes.items():
        if col in df.columns:
            df[col] = df[col].astype(dtype)
        else:
            print(f"Warning: Column {col} not found in DataFrame.")
            df[col] = pd.Series(
                data=0 if dtype in [np.int64, np.float64] else '',
                dtype=dtype,
            )  # Add missing column with correct dtype
    
    dummy = set(df.columns) - set(dtypes.keys())
    if dummy:
        print(f"Warning: Extra columns {dummy} found in DataFrame. They will be dropped.")
        df = df.drop(columns=dummy)

    return df

In [22]:
syn_df = sync_df(ori_syn_df, train.dtypes.to_dict())

Warning: Extra columns {'etri_syn'} found in DataFrame. They will be dropped.

In [23]:
syn_df.shape[1] == train.shape[1], syn_df.dtypes.equals(train.dtypes)

(True, True)

In [75]:
def vis_df(df):
    # 수치형 컬럼만 선택
    num_cols = df.select_dtypes(include=[np.number]).columns

    # 상관계수 행렬 계산
    corr_matrix = df[num_cols].corr()

    # 시각화
    plt.figure(figsize=(12, 10))
    sns.heatmap(corr_matrix, annot=True, fmt=".2f", cmap="coolwarm", square=True)
    plt.title("Correlation Matrix of Numerical Columns in df")
    plt.show()

### 🔥 추정수면효율
- 추정수면효율 (S2) : (불끈 시간 - 핸드폰 이용한 마지막 시간) / 추정수면시간

In [40]:
train = pd.read_parquet(f"../data/train_0524_v1.parquet")
test = pd.read_parquet(f"../data/test_0524_v1.parquet")
syn = syn_df.copy()

In [29]:
def calculate_sleep_duration_min(sleep_time, wake_time):
    """
    취침 시각(sleep_time)과 기상 시각(wake_time)을 입력받아 수면 시간(분) 반환
    단위는 float 시간 (예: 23.5, 6.25)
    """
    if pd.isna(sleep_time) or pd.isna(wake_time):
        return None
    if wake_time < sleep_time:
        wake_time += 24  # 자정 넘긴 경우 보정
    duration = (wake_time - sleep_time) * 60
    return round(duration)

In [41]:
train['불끈시간부터기상시간'] = train.apply(lambda x: calculate_sleep_duration_min(x['lights_off_time'],x['wake_time']),axis=1)
test['불끈시간부터기상시간'] = test.apply(lambda x: calculate_sleep_duration_min(x['lights_off_time'],x['wake_time']),axis=1)
syn['불끈시간부터기상시간'] = syn.apply(lambda x: calculate_sleep_duration_min(x['lights_off_time'],x['wake_time']),axis=1)

In [42]:
train['추정수면효율'] = train['불끈시간부터기상시간']/train['sleep_duration_min']
test['추정수면효율'] = test['불끈시간부터기상시간']/test['sleep_duration_min']
syn['추정수면효율'] = syn['불끈시간부터기상시간']/syn['sleep_duration_min']

# 이상값 제거
train['추정수면효율'] = np.where(train['추정수면효율']<-5,np.nan,train['추정수면효율'])
test['추정수면효율'] = np.where(test['추정수면효율']<-5,np.nan,test['추정수면효율'])
syn['추정수면효율'] = np.where(syn['추정수면효율']<-5,np.nan,syn['추정수면효율'])
train['추정수면효율'] = np.where(train['추정수면효율']>5,np.nan,train['추정수면효율'])
test['추정수면효율'] = np.where(test['추정수면효율']>55,np.nan,test['추정수면효율'])
syn['추정수면효율'] = np.where(syn['추정수면효율']>5,np.nan,syn['추정수면효율'])

In [43]:
# sleep duration

train['sleep_time_m_light_sleep_time'] = train['sleep_time'] - train['light_sleep_time']
test['sleep_time_m_light_sleep_time'] = test['sleep_time'] - test['light_sleep_time']
syn['sleep_time_m_light_sleep_time'] = syn['sleep_time'] - syn['light_sleep_time']

train['wake__time_m_light_wake__time'] = train['wake_time'] - train['light_wake_time']
test['wake__time_m_light_wake__time'] = test['wake_time'] - test['light_wake_time']
syn['wake__time_m_light_wake__time'] = syn['wake_time'] - syn['light_wake_time']

train['sleep_duration_min_m_light_sleep_duration_min'] = train['sleep_duration_min'] - train['light_sleep_duration_min']
test['sleep_duration_min_m_light_sleep_duration_min'] = test['sleep_duration_min'] - test['light_sleep_duration_min']
syn['sleep_duration_min_m_light_sleep_duration_min'] = syn['sleep_duration_min'] - syn['light_sleep_duration_min']

train['sleep_time_d_light_sleep_time'] = train['sleep_time'] / train['light_sleep_time']
test['sleep_time_d_light_sleep_time'] = test['sleep_time'] / test['light_sleep_time']
syn['sleep_time_d_light_sleep_time'] = syn['sleep_time'] / syn['light_sleep_time']

train['wake__time_d_light_wake__time'] = train['wake_time'] / train['light_wake_time']
test['wake__time_d_light_wake__time'] = test['wake_time'] / test['light_wake_time']
syn['wake__time_d_light_wake__time'] = syn['wake_time'] / syn['light_wake_time']

train['sleep_duration_min_d_light_sleep_duration_min'] = train['sleep_duration_min'] / train['light_sleep_duration_min']
test['sleep_duration_min_d_light_sleep_duration_min'] = test['sleep_duration_min'] / test['light_sleep_duration_min']
syn['sleep_duration_min_d_light_sleep_duration_min'] = syn['sleep_duration_min'] / syn['light_sleep_duration_min']

train['sleep_time_min'] = train[['sleep_time','light_sleep_time']].min(axis=1)
train['sleep_time_max'] = train[['sleep_time','light_sleep_time']].max(axis=1)

train['wake_time_min'] = train[['wake_time','light_wake_time']].min(axis=1)
train['wake_time_max'] = train[['wake_time','light_wake_time']].max(axis=1)

train['sleep_duration_min_min'] = train[['sleep_duration_min','light_sleep_duration_min']].min(axis=1)
train['sleep_duration_min_max'] = train[['sleep_duration_min','light_sleep_duration_min']].max(axis=1)

test['sleep_time_min'] = test[['sleep_time','light_sleep_time']].min(axis=1)
test['sleep_time_max'] = test[['sleep_time','light_sleep_time']].max(axis=1)

test['wake_time_min'] = test[['wake_time','light_wake_time']].min(axis=1)
test['wake_time_max'] = test[['wake_time','light_wake_time']].max(axis=1)

test['sleep_duration_min_min'] = test[['sleep_duration_min','light_sleep_duration_min']].min(axis=1)
test['sleep_duration_min_max'] = test[['sleep_duration_min','light_sleep_duration_min']].max(axis=1)

syn['sleep_time_min'] = syn[['sleep_time','light_sleep_time']].min(axis=1)
syn['sleep_time_max'] = syn[['sleep_time','light_sleep_time']].max(axis=1)

syn['wake_time_min'] = syn[['wake_time','light_wake_time']].min(axis=1)
syn['wake_time_max'] = syn[['wake_time','light_wake_time']].max(axis=1)

syn['sleep_duration_min_min'] = syn[['sleep_duration_min','light_sleep_duration_min']].min(axis=1)
syn['sleep_duration_min_max'] = syn[['sleep_duration_min','light_sleep_duration_min']].max(axis=1)

In [44]:
# 요일 컬럼 추가 (예: 월요일, 화요일, ...)
train['lifelog_date'] = pd.to_datetime(train['lifelog_date'])
test['lifelog_date'] = pd.to_datetime(test['lifelog_date'])
syn['lifelog_date'] = pd.to_datetime(syn['lifelog_date'])

# 요일
weekday_map = {
    0: '월요일', 1: '화요일', 2: '수요일', 3: '목요일',
    4: '금요일', 5: '토요일', 6: '일요일'
}
train['weekday'] = train['lifelog_date'].dt.dayofweek.map(weekday_map)
test['weekday'] = test['lifelog_date'].dt.dayofweek.map(weekday_map)
syn['weekday'] = syn['lifelog_date'].dt.dayofweek.map(weekday_map)

# 월
train['month'] = train['lifelog_date'].dt.month
test['month'] = test['lifelog_date'].dt.month
syn['month'] = syn['lifelog_date'].dt.month

# weekend
train['weekend'] = np.where(train['weekday'].isin(['토요일','일요일']),1,0)
test['weekend'] = np.where(test['weekday'].isin(['토요일','일요일']),1,0)
syn['weekend'] = np.where(syn['weekday'].isin(['토요일','일요일']),1,0)

# 공휴일
공휴일 = [
     '2024-08-15'
    ,'2024-09-16'
    ,'2024-09-17'
    ,'2024-09-18'
    ,'2024-10-03'
    ,'2024-10-09'
]
train['공휴일'] = np.where(train['lifelog_date'].isin(공휴일),1,0)
test['공휴일'] = np.where(test['lifelog_date'].isin(공휴일),1,0)
syn['공휴일'] = np.where(syn['lifelog_date'].isin(공휴일),1,0)

# 주말 + 공휴일 묶어주기
train['weekend_holilday'] = np.where( ((train['weekend']==0) & (train['공휴일']==1)), 1, train['weekend'])
test['weekend_holilday'] = np.where( ((test['weekend']==0) & (test['공휴일']==1)), 1, test['weekend'])
syn['weekend_holilday'] = np.where( ((syn['weekend']==0) & (syn['공휴일']==1)), 1, syn['weekend'])

In [45]:
def add_prev_day_flag(df):
    df = df.copy()
    df['lifelog_date'] = pd.to_datetime(df['lifelog_date'])

    # 각 subject_id별로 전날 날짜 만들기
    df['prev_day'] = df['lifelog_date'] - pd.Timedelta(days=1)

    # subject_id + 날짜 기준으로 원본 키 구성
    key_set = set(zip(df['subject_id'], df['lifelog_date']))

    # 전날 데이터가 존재하면 1, 없으면 0
    df['has_prev_day_data'] = df[['subject_id', 'prev_day']].apply(
        lambda row: 1 if (row['subject_id'], row['prev_day']) in key_set else 0, axis=1
    )

    return df.drop(columns=['prev_day'])

train = add_prev_day_flag(train)
test = add_prev_day_flag(test)
syn = add_prev_day_flag(syn)

In [46]:
# 추정휴가
def rule_based_sum(x):
    rules = (
        # (x['sleep_duration_min'] > (x['avg_sleep_duration']+30))
          (x['sleep_duration_min'] > (x['avg_sleep_duration']+60))
        & (x['week_type'] == 'weekday')
        # & (x['month'].isin([7,8]))
    )
    return rules

train['vacation'] = train.groupby('subject_id').apply(rule_based_sum).reset_index(level=0, drop=True).astype(int)
test['vacation'] = test.groupby('subject_id').apply(rule_based_sum).reset_index(level=0, drop=True).astype(int)
syn['vacation'] = syn.groupby('subject_id').apply(rule_based_sum).reset_index(level=0, drop=True).astype(int)

# check
test.groupby(['subject_id'])['vacation'].sum().head()

subject_id
id01    2
id02    3
id03    4
id04    9
id05    4
Name: vacation, dtype: int64

In [47]:
# 숫자형 컬럼만 선택해서 결측값 -1로 채우기
train[train.select_dtypes(include='number').columns] = train.select_dtypes(include='number').fillna(-1)
test[test.select_dtypes(include='number').columns] = test.select_dtypes(include='number').fillna(-1)
syn[syn.select_dtypes(include='number').columns] = syn.select_dtypes(include='number').fillna(-1)

In [48]:
def get_oof_predictions(X, y, params, n_splits=5, is_multiclass=False, num_class=None, early_stop=False):

    oof_preds = np.zeros(len(X))  # 1차원으로 변경
    skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)

    for train_idx, valid_idx in skf.split(X, y):
        X_train, X_valid = X.iloc[train_idx], X.iloc[valid_idx]
        y_train, y_valid = y.iloc[train_idx], y.iloc[valid_idx]

        if is_multiclass:
            model = LGBMClassifier(**params, objective='multiclass', num_class=num_class)
        else:
            model = LGBMClassifier(**params)

        if early_stop:
            model.fit(
                X_train, y_train,
                eval_set=[(X_train, y_train), (X_valid, y_valid)],
                callbacks=[early_stopping(stopping_rounds=100, verbose=False)]
            )
        else:
            model.fit(X_train, y_train)

        preds = model.predict(X_valid)  # returns 1D array
        oof_preds[valid_idx] = preds  # 1D -> 1D 저장

    return oof_preds

In [49]:
def focal_loss_lgb(y_pred, dtrain, alpha=0.25, gamma=2.0):
    y_true = dtrain.get_label()
    p = 1 / (1 + np.exp(-y_pred))  # sigmoid

    grad = alpha * (y_true * (1 - p) ** gamma * (gamma * p * np.log(np.clip(p, 1e-9, 1)) + p - 1) +
                    (1 - y_true) * p ** gamma * (gamma * (1 - p) * np.log(np.clip(1 - p, 1e-9, 1)) - p))

    hess = alpha * (y_true * (1 - p) ** gamma *
                    ((gamma * (1 - p) * (1 - 2 * p) - p * (1 - p)) * np.log(np.clip(p, 1e-9, 1)) +
                     2 * p - 1) +
                    (1 - y_true) * p ** gamma *
                    ((gamma * p * (1 - 2 * p) - (1 - p) * p) * np.log(np.clip(1 - p, 1e-9, 1)) +
                     1 - 2 * p))

    return grad, hess

def f1_eval(y_pred, dtrain):
    y_true = dtrain.get_label()
    y_pred_binary = (y_pred > 0.5).astype(int)
    return 'f1', f1_score(y_true, y_pred_binary), True  # ✅ 반환값: (이름, 점수, 높을수록 좋은지 여부)

In [72]:
def run_basemodel(train, test, valid_ids, best_param_dict, topn, n_splits=5, random_state=42, focal_loss=False, log_level=0, get_oof=False, submit=False, syn=None):
    import lightgbm as lgb

    train_df = train.copy()
    test_df = test.copy()
    syn_df = syn.copy() if syn is not None else None
    oof_result = pd.DataFrame()

    submission_final = test_df[['subject_id', 'sleep_date', 'lifelog_date']].copy()
    submission_final['lifelog_date'] = pd.to_datetime(submission_final['lifelog_date']).dt.date

    # 타겟
    targets_binary = ['Q1', 'Q2', 'Q3', 'S2', 'S3']
    targets_binary_name = ['기상직후수면질','취침전신체적피로','취침전스트레스','수면효율','수면잠들기시간']
    target_multiclass = 'S1'
    all_targets = targets_binary + [target_multiclass]

    def add_noise(series, noise_level, seed=3):
        rng = np.random.default_rng(seed)
        return series * (1 + noise_level * rng.standard_normal(len(series)))

    noise_level = 0.015

    for tgt in all_targets:
        encoder_feats = ['subject_id','month','weekend']
        subject_mean = train_df.groupby(encoder_feats)[tgt].mean().rename(f'{tgt}_te')
        train_df = train_df.merge(subject_mean, on=encoder_feats, how='left')
        test_df = test_df.merge(subject_mean, on=encoder_feats, how='left')
        if syn_df is not None:
          syn_df = syn_df.merge(subject_mean, on=encoder_feats, how='left')
        global_mean = train_df[tgt].mean()
        test_df[f'{tgt}_te'] = test_df[f'{tgt}_te'].fillna(global_mean)
        if syn_df is not None:
          syn_df[f'{tgt}_te'] = syn_df[f'{tgt}_te'].fillna(global_mean)

        train_df[f'{tgt}_te'] = add_noise(train_df[f'{tgt}_te'], noise_level)
        test_df[f'{tgt}_te'] = add_noise(test_df[f'{tgt}_te'], noise_level)
        if syn_df is not None:
          syn_df[f'{tgt}_te'] = add_noise(syn_df[f'{tgt}_te'], noise_level)

        train_df['TMP'] = train_df[encoder_feats].applymap(str).agg(''.join, axis=1)
        test_df['TMP'] = test_df[encoder_feats].applymap(str).agg(''.join, axis=1)
        if syn_df is not None:
          syn_df['TMP'] = syn_df[encoder_feats].applymap(str).agg(''.join, axis=1)

        encoder = TargetEncoder(cols=['TMP'], smoothing=300)
        encoder.fit(train_df[['TMP']], train_df[tgt])

        train_df[f'{tgt}_te2'] = add_noise(encoder.transform(train_df[['TMP']]).iloc[:, 0], noise_level)
        test_df[f'{tgt}_te2'] = add_noise(encoder.transform(test_df[['TMP']]).iloc[:, 0], noise_level)
        if syn_df is not None:
          syn_df[f'{tgt}_te2'] = add_noise(encoder.transform(syn_df[['TMP']]).iloc[:, 0], noise_level)

        train_df.drop(columns=['TMP'], inplace=True)
        test_df.drop(columns=['TMP'], inplace=True)
        if syn_df is not None:
          syn_df.drop(columns=['TMP'], inplace=True)

    PK = ['sleep_date', 'lifelog_date', 'subject_id']
    encoder = LabelEncoder()
    categorical_features = [i for i in train_df.select_dtypes(include=['object', 'category']).columns if i not in PK+['pk']]
    # print(f"# 카테고리변수: {categorical_features}")
    for col in categorical_features:
        train_df[col] = encoder.fit_transform(train_df[col])
        test_df[col] = encoder.fit_transform(test_df[col])
        if syn_df is not None:
            syn_df[col] = encoder.fit_transform(syn_df[col])


    # ============================================= train / valid 모델 학습 =============================================

    X = train_df.drop(columns=PK + all_targets)
    test_X = test_df.drop(columns=PK + all_targets)

    total_avg_f1s = []
    best_iteration_temp = {k: [] for k in all_targets}
    val_f1 = []
    top_features_dict = {}
    for col in targets_binary:

        # 상관관계기반 변수선택
        # ==============================================================
        y = train_df[col]
        corr_series = X.corrwith(y).abs()
        if isinstance(topn,int)==True:
          top_features = corr_series.sort_values(ascending=False).head(topn).index.tolist()
        else:
          top_features = corr_series.sort_values(ascending=False).head(topn[col]).index.tolist()
        top_features_dict[col] = top_features
        # ==============================================================

        # valid_ids['pk'] = valid_ids['subject_id'] + valid_ids['sleep_date']
        train_df['pk'] = train_df['subject_id'] + train_df['sleep_date']
        if syn_df is not None:
          syn_df['pk'] = syn_df['subject_id'] + syn_df['sleep_date']

        X_valid = train_df.loc[train_df['pk'].isin(valid_ids), top_features].reset_index(drop=True)
        X_train = train_df.loc[~train_df['pk'].isin(valid_ids), top_features].reset_index(drop=True)
        if syn_df is not None:
          X_syn = syn_df.loc[~syn_df['pk'].isin(valid_ids), top_features].reset_index(drop=True)

        y_valid = train_df.loc[train_df['pk'].isin(valid_ids), col].reset_index(drop=True)
        y_train = train_df.loc[~train_df['pk'].isin(valid_ids), col].reset_index(drop=True)
        if syn_df is not None:
          y_syn = syn_df.loc[~syn_df['pk'].isin(valid_ids), col].reset_index(drop=True)

        model = LGBMClassifier(**best_param_dict[col], random_state=random_state)

        # focal loss 학습 (**not working)
        # ==============================================================
        if syn_df is not None:
          X_train = pd.concat([X_train, X_syn], axis=0).reset_index(drop=True)
          y_train = pd.concat([y_train, y_syn], axis=0).reset_index(drop=True)
        if focal_loss:
            dtrain = lgb.Dataset(X_train, label=y_train)
            dvalid = lgb.Dataset(X_valid, label=y_valid)
            model = lgb.train(
                params={k: v for k, v in best_param_dict[col].items() if k != 'objective'},  # learning_rate는 아래에서 설정
                train_set=dtrain,
                valid_sets=dvalid,
                fobj=focal_loss_lgb,
                feval=f1_eval,
                num_boost_round=1000
            )
        # ==============================================================
        else:
            model.fit(X_train, y_train)

        pred_valid = model.predict(X_valid)
        f1 = f1_score(y_valid, pred_valid, average='macro')
        val_f1.append(f1)

    # 상관관계기반 변수선택
    # ==============================================================
    y = train_df['S1']
    corr_series = X.corrwith(y).abs()
    if isinstance(topn,int)==True:
      top_features = corr_series.sort_values(ascending=False).head(topn).index.tolist()
    else:
      top_features = corr_series.sort_values(ascending=False).head(topn['S1']).index.tolist()
    top_features_dict['S1'] = top_features
    # ==============================================================

    X_valid = train_df.loc[train_df['pk'].isin(valid_ids), top_features].reset_index(drop=True)
    X_train = train_df.loc[~train_df['pk'].isin(valid_ids), top_features].reset_index(drop=True)
    if syn_df is not None:
        X_syn = syn_df.loc[~syn_df['pk'].isin(valid_ids), top_features].reset_index(drop=True)

    y_valid = train_df.loc[train_df['pk'].isin(valid_ids), 'S1'].reset_index(drop=True)
    y_train = train_df.loc[~train_df['pk'].isin(valid_ids), 'S1'].reset_index(drop=True)
    if syn_df is not None:
        y_syn = syn_df.loc[~syn_df['pk'].isin(valid_ids), 'S1'].reset_index(drop=True)


    model = LGBMClassifier(**best_param_dict['S1'], objective='multiclass', num_class=3, random_state=random_state)

    # focal loss 학습 (**not working)
    # ==============================================================

    if syn_df is not None:
        X_train = pd.concat([X_train, X_syn], axis=0).reset_index(drop=True)
        y_train = pd.concat([y_train, y_syn], axis=0).reset_index(drop=True)

    if focal_loss:
        dtrain = lgb.Dataset(X_train, label=y_train)
        dvalid = lgb.Dataset(X_valid, label=y_valid)
        model = lgb.train(
            params={k: v for k, v in best_param_dict[col].items() if k != 'objective'},  # learning_rate는 아래에서 설정
            train_set=dtrain,
            valid_sets=dvalid,
            fobj=focal_loss_lgb,
            feval=f1_eval,
            num_boost_round=1000
        )
    # ==============================================================
    else:
        model.fit(X_train, y_train)

    pred_valid = model.predict(X_valid)
    f1 = f1_score(y_valid, pred_valid, average='macro')
    val_f1.append(f1)
    avg_f1 = np.mean(val_f1)
    detail = " ".join([f"{name}({tname}):{score:.4f}" for name, tname, score in zip(targets_binary + ['S1'], targets_binary_name + ['수면시간'], val_f1)])
    print(f"# 평균 F1: {avg_f1:.4f} / [상세] {detail}")


    # ============================================= 전체 재학습 및 예측 =============================================
    if submit==True:
      for col in targets_binary:
          model = LGBMClassifier(**best_param_dict[col], random_state=random_state)

          X_train = train_df[top_features_dict[col]].copy()
          y_train = train_df[col].copy()

          if syn_df is not None:
            X_syn = syn_df[top_features_dict[col]].copy()
            y_syn = syn_df[col].copy()
            X_train = pd.concat([X_train, X_syn], axis=0).reset_index(drop=True)
            y_train = pd.concat([y_train, y_syn], axis=0).reset_index(drop=True)

          model.fit(X_train, y_train)

          submission_final[col] = model.predict(test_X[top_features_dict[col]])

          if log_level==1:
            # vi[1]
            fi_df = pd.DataFrame({'feature': top_features_dict[col], 'importance': model.feature_importances_})
            top10 = fi_df.sort_values(by='importance', ascending=False).head(10)
            feat_str = ", ".join([f"{row['feature']}({int(row['importance'])})" for _, row in top10.iterrows()])
            print(f"[{col}] {feat_str}")

      # S1 예측
      model = LGBMClassifier(**best_param_dict['S1'], objective='multiclass', num_class=3, random_state=random_state)

      X_train = train_df[top_features_dict['S1']].copy()
      y_train = train_df['S1'].copy()

      if syn_df is not None:
        X_syn = syn_df[top_features_dict['S1']].copy()
        y_syn = syn_df['S1'].copy()
        X_train = pd.concat([X_train, X_syn], axis=0).reset_index(drop=True)
        y_train = pd.concat([y_train, y_syn], axis=0).reset_index(drop=True)

      model.fit(X_train, y_train)

      submission_final['S1'] = model.predict(test_X[top_features_dict['S1']])

      if log_level==1:
        # vi[2]
        fi_df = pd.DataFrame({'feature': top_features_dict['S1'], 'importance': model.feature_importances_})
        top10 = fi_df.sort_values(by='importance', ascending=False).head(10)
        feat_str = ", ".join([f"{row['feature']}({int(row['importance'])})" for _, row in top10.iterrows()])
        print(f"[S1] {feat_str}")

      # 예측 저장
      submission_final = submission_final[['subject_id', 'sleep_date', 'lifelog_date', 'Q1', 'Q2', 'Q3', 'S1', 'S2', 'S3']]
      fname = f"./submission_{avg_f1}.csv"
      submission_final.to_csv(fname, index=False)
      print(f"# {fname} 저장 완료")

      # 모델별 예측결과 비율 비교
      a11 = train_df[['Q1', 'Q2', 'Q3', 'S1', 'S2', 'S3']].sum()
      a13 = train_df[['Q1', 'Q2', 'Q3', 'S1', 'S2', 'S3']].apply(len)
      a12 = train_df[['Q1', 'Q2', 'Q3', 'S1', 'S2', 'S3']].mean()
      a21 = submission_final[['Q1', 'Q2', 'Q3', 'S1', 'S2', 'S3']].sum()
      a23 = submission_final[['Q1', 'Q2', 'Q3', 'S1', 'S2', 'S3']].apply(len)
      a22 = submission_final[['Q1', 'Q2', 'Q3', 'S1', 'S2', 'S3']].mean()
      result = pd.concat([a11, a13, a12, a21, a23, a22], axis=1)
      result.columns = ['학습sum','학습len','학습mean','테스트sum','테스트len','테스트mean']

      if log_level==1:
        print('# 예측결과 비교표')
        display(result)

      # 정규화된 빈도 계산
      a1 = train['S1'].value_counts(normalize=True).rename('train_distribution')
      a2 = submission_final['S1'].value_counts(normalize=True).rename('submission_distribution')
      combined = pd.concat([a1, a2], axis=1).fillna(0)
      display(combined.sort_index())

    # ============================================= OOF 예측 생성 ===================================================

    if get_oof==True:
      oof_result = train_df[['subject_id', 'sleep_date', 'lifelog_date']].copy()
      oof_f1 = []

      # binary
      for col in targets_binary:
          y = train_df[col]
          model = LGBMClassifier(**best_param_dict[col], random_state=random_state)
          oof_preds = np.zeros_like(y)
          kf = KFold(n_splits=n_splits, shuffle=True, random_state=random_state)
          for train_index, valid_index in kf.split(X):
              X_train = X.iloc[train_index][top_features_dict[col]]
              y_train = y.iloc[train_index]

              if syn_df is not None:
                X_syn = syn_df[top_features_dict[col]].copy()
                y_syn = syn_df[col].copy()
                X_train = pd.concat([X_train, X_syn], axis=0).reset_index(drop=True)
                y_train = pd.concat([y_train, y_syn], axis=0).reset_index(drop=True)

              model.fit(X_train, y_train)
              oof_preds[valid_index] = model.predict(X.iloc[valid_index][top_features_dict[col]])

          oof_result[col] = oof_preds
          f1 = f1_score(y, oof_preds, average='macro')
          oof_f1.append(f1)

      # S1
      y = train_df['S1']
      model = LGBMClassifier(**best_param_dict['S1'], objective='multiclass', num_class=3, random_state=random_state)
      oof_preds = np.zeros_like(y)
      for train_index, valid_index in kf.split(X):
          X_train = X.iloc[train_index][top_features_dict['S1']]
          y_train = y.iloc[train_index]
          if syn_df is not None:
                X_syn = syn_df[top_features_dict[col]].copy()
                y_syn = syn_df[col].copy()
                X_train = pd.concat([X_train, X_syn], axis=0).reset_index(drop=True)
                y_train = pd.concat([y_train, y_syn], axis=0).reset_index(drop=True)
          model.fit(X_train, y_train)
          oof_preds[valid_index] = model.predict(X.iloc[valid_index][top_features_dict['S1']])

      oof_result[col] = oof_preds
      f1 = f1_score(y, oof_preds, average='macro')
      oof_f1.append(f1)
      oof_avg_f1 = np.mean(oof_f1)
      detail = " ".join([f"{name}({tname}):{score:.4f}" for name, tname, score in zip(targets_binary + ['S1'], targets_binary_name + ['S1'], oof_f1)])
      print(f"#  oof F1: {oof_avg_f1:.4f} / [상세] {detail}")

    return submission_final, oof_result, avg_f1, val_f1

In [60]:
trn = train.copy()
tst = test.copy()
sy = syn.copy()

In [61]:
# 인코딩1
trn['weekday'] = trn['weekday'].map(dict([(j,i) for i,j in weekday_map.items()]))
tst['weekday'] = tst['weekday'].map(dict([(j,i) for i,j in weekday_map.items()]))
sy['weekday'] = sy['weekday'].map(dict([(j,i) for i,j in weekday_map.items()]))

# 인코딩2
a1_map = {'weekday': 1, 'weekend':2}
trn['week_type'] = trn['week_type'].map(a1_map)
tst['week_type'] = tst['week_type'].map(a1_map)
sy['week_type'] = sy['week_type'].map(a1_map)

# 인코딩3
a1_map = {'weekday': 1, 'weekend':2}
trn['week_type_lag1'] = trn['week_type_lag1'].map(a1_map)
tst['week_type_lag1'] = tst['week_type_lag1'].map(a1_map)
sy['week_type_lag1'] = sy['week_type_lag1'].map(a1_map)

In [62]:
drop_features2 = [
  'light_week_type_lag1',
  'activehour_top_bssid',
  'beforebed_top_bssid'
]

In [63]:
# 검증데이터셋 PK모음
valid_ids1 = ['id012024-07-24', 'id012024-07-27', 'id012024-08-18', 'id012024-08-19', 'id012024-08-20', 'id012024-08-21', 'id012024-08-22', 'id012024-08-24', 'id012024-08-25', 'id012024-08-26', 'id012024-08-27', 'id012024-08-28', 'id012024-08-29', 'id012024-08-30', 'id022024-08-23', 'id022024-08-24', 'id022024-09-16', 'id022024-09-17', 'id022024-09-19', 'id022024-09-20', 'id022024-09-21', 'id022024-09-22', 'id022024-09-23', 'id022024-09-24', 'id022024-09-25', 'id022024-09-26', 'id022024-09-27', 'id022024-09-28', 'id032024-08-30', 'id032024-09-01', 'id032024-09-02', 'id032024-09-03', 'id032024-09-05', 'id032024-09-06', 'id032024-09-07', 'id042024-09-03', 'id042024-09-04', 'id042024-09-05', 'id042024-09-06', 'id042024-09-07', 'id042024-09-08', 'id042024-09-09', 'id042024-10-08', 'id042024-10-09', 'id042024-10-10', 'id042024-10-11', 'id042024-10-12', 'id042024-10-13', 'id042024-10-14', 'id052024-10-19', 'id052024-10-23', 'id052024-10-24', 'id052024-10-25', 'id052024-10-26', 'id052024-10-27', 'id052024-10-28', 'id062024-07-25', 'id062024-07-26', 'id062024-07-27', 'id062024-07-28', 'id062024-07-29', 'id062024-07-30', 'id062024-07-31', 'id072024-07-07', 'id072024-07-08', 'id072024-07-09', 'id072024-07-10', 'id072024-07-11', 'id072024-07-12', 'id072024-07-13', 'id072024-07-30', 'id072024-08-01', 'id072024-08-02', 'id072024-08-03', 'id072024-08-04', 'id072024-08-05', 'id072024-08-06', 'id082024-08-28', 'id082024-08-29', 'id082024-08-30', 'id082024-08-31', 'id082024-09-01', 'id082024-09-02', 'id082024-09-04', 'id092024-08-02', 'id092024-08-22', 'id092024-08-23', 'id092024-08-24', 'id092024-08-25', 'id092024-08-27', 'id092024-08-28', 'id092024-08-29', 'id092024-08-30', 'id092024-08-31', 'id092024-09-01', 'id092024-09-02', 'id092024-09-03', 'id092024-09-04', 'id102024-08-28', 'id102024-08-30', 'id102024-08-31', 'id102024-09-01', 'id102024-09-02', 'id102024-09-03', 'id102024-09-06']
valid_ids2 = ['id012024-07-24', 'id012024-07-27', 'id012024-08-19', 'id012024-08-20', 'id012024-08-21', 'id012024-08-22', 'id012024-08-24', 'id012024-08-25', 'id012024-08-26', 'id012024-08-27', 'id012024-08-28', 'id012024-08-29', 'id012024-08-30', 'id012024-09-01', 'id022024-08-23', 'id022024-08-24', 'id022024-09-13', 'id022024-09-14', 'id022024-09-16', 'id022024-09-17', 'id022024-09-19', 'id022024-09-20', 'id022024-09-21', 'id022024-09-22', 'id022024-09-23', 'id022024-09-24', 'id022024-09-25', 'id022024-09-26', 'id032024-09-02', 'id032024-09-03', 'id032024-09-05', 'id032024-09-06', 'id032024-09-07', 'id032024-09-08', 'id042024-09-07', 'id042024-09-08', 'id042024-09-09', 'id042024-09-11', 'id042024-09-17', 'id042024-09-18', 'id042024-09-28', 'id042024-09-29', 'id042024-10-21', 'id042024-10-23', 'id042024-10-27', 'id052024-08-29', 'id052024-08-30', 'id052024-08-31', 'id052024-09-01', 'id052024-10-10', 'id052024-11-05', 'id052024-11-06', 'id052024-11-10', 'id052024-11-11', 'id052024-11-12', 'id052024-11-15', 'id062024-08-03', 'id062024-08-04', 'id062024-08-05', 'id062024-08-06', 'id062024-08-11', 'id062024-08-16', 'id062024-08-19', 'id072024-07-02', 'id072024-07-03', 'id072024-07-04', 'id072024-07-06', 'id072024-07-07', 'id072024-07-08', 'id072024-07-09', 'id072024-08-02', 'id072024-08-03', 'id072024-08-04', 'id072024-08-05', 'id072024-08-06', 'id072024-08-07', 'id072024-08-08', 'id082024-09-01', 'id082024-09-02', 'id082024-09-04', 'id082024-09-06', 'id082024-09-12', 'id082024-09-16', 'id082024-09-17', 'id092024-07-27', 'id092024-07-28', 'id092024-07-30', 'id092024-07-31', 'id092024-08-02', 'id092024-08-04', 'id092024-08-05', 'id092024-08-22', 'id092024-08-23', 'id092024-08-24', 'id092024-08-25', 'id092024-08-27', 'id092024-08-28', 'id092024-08-29', 'id102024-08-30', 'id102024-08-31', 'id102024-09-01', 'id102024-09-02', 'id102024-09-03', 'id102024-09-06', 'id102024-09-08']
valid_ids3 = ['id012024-07-20', 'id012024-07-23', 'id012024-08-19', 'id012024-08-20', 'id012024-08-21', 'id012024-08-22', 'id012024-08-24', 'id012024-08-25', 'id012024-08-26', 'id012024-08-27', 'id012024-08-28', 'id012024-08-29', 'id012024-08-30', 'id012024-09-01', 'id022024-08-21', 'id022024-08-22', 'id022024-09-11', 'id022024-09-12', 'id022024-09-13', 'id022024-09-14', 'id022024-09-16', 'id022024-09-17', 'id022024-09-19', 'id022024-09-20', 'id022024-09-21', 'id022024-09-22', 'id022024-09-23', 'id022024-09-24', 'id032024-09-05', 'id032024-09-06', 'id032024-09-07', 'id032024-09-08', 'id032024-09-10', 'id032024-09-12', 'id032024-09-13', 'id042024-08-27', 'id042024-08-28', 'id042024-08-29', 'id042024-08-30', 'id042024-08-31', 'id042024-09-01', 'id042024-09-02', 'id042024-10-01', 'id042024-10-02', 'id042024-10-03', 'id042024-10-04', 'id042024-10-05', 'id042024-10-06', 'id042024-10-07', 'id052024-10-28', 'id052024-10-29', 'id052024-10-30', 'id052024-10-31', 'id052024-11-03', 'id052024-11-05', 'id052024-11-06', 'id062024-07-31', 'id062024-08-01', 'id062024-08-02', 'id062024-08-03', 'id062024-08-04', 'id062024-08-05', 'id062024-08-06', 'id072024-06-29', 'id072024-06-30', 'id072024-07-01', 'id072024-07-02', 'id072024-07-03', 'id072024-07-04', 'id072024-07-06', 'id072024-08-07', 'id072024-08-08', 'id072024-08-09', 'id072024-08-10', 'id072024-08-11', 'id072024-08-12', 'id072024-08-13', 'id082024-08-19', 'id082024-08-20', 'id082024-08-22', 'id082024-08-23', 'id082024-08-24', 'id082024-08-25', 'id082024-08-26', 'id092024-08-04', 'id092024-08-22', 'id092024-08-23', 'id092024-08-24', 'id092024-08-25', 'id092024-08-27', 'id092024-08-28', 'id092024-08-29', 'id092024-08-30', 'id092024-08-31', 'id092024-09-01', 'id092024-09-02', 'id092024-09-03', 'id092024-09-04', 'id102024-09-02', 'id102024-09-03', 'id102024-09-06', 'id102024-09-08', 'id102024-09-09', 'id102024-09-12', 'id102024-09-15']
valid_ids4 = ['id012024-07-24', 'id012024-07-27', 'id012024-08-18', 'id012024-08-19', 'id012024-08-20', 'id012024-08-21', 'id012024-08-22', 'id012024-08-24', 'id012024-08-25', 'id012024-08-26', 'id012024-08-27', 'id012024-08-28', 'id012024-08-29', 'id012024-08-30', 'id022024-08-23', 'id022024-08-24', 'id022024-09-12', 'id022024-09-13', 'id022024-09-14', 'id022024-09-16', 'id022024-09-17', 'id022024-09-22', 'id022024-09-23', 'id022024-09-24', 'id022024-09-25', 'id022024-09-26', 'id022024-09-27', 'id022024-09-28', 'id032024-08-30', 'id032024-09-01', 'id032024-09-02', 'id032024-09-07', 'id032024-09-08', 'id032024-09-10', 'id042024-09-03', 'id042024-09-04', 'id042024-09-05', 'id042024-09-11', 'id042024-09-17', 'id042024-09-18', 'id042024-09-28', 'id042024-09-29', 'id042024-10-21', 'id042024-10-23', 'id042024-10-27', 'id052024-08-29', 'id052024-08-30', 'id052024-08-31', 'id052024-09-01', 'id052024-10-10', 'id052024-11-03', 'id052024-11-05', 'id052024-11-10', 'id052024-11-11', 'id052024-11-12', 'id052024-11-15', 'id062024-07-27', 'id062024-07-28', 'id062024-07-29', 'id062024-07-30', 'id062024-08-11', 'id062024-08-16', 'id062024-08-19', 'id072024-07-03', 'id072024-07-04', 'id072024-07-06', 'id072024-07-10', 'id072024-07-11', 'id072024-07-12', 'id072024-07-13', 'id072024-07-29', 'id072024-07-30', 'id072024-08-01', 'id072024-08-02', 'id072024-08-03', 'id072024-08-04', 'id072024-08-05', 'id082024-09-01', 'id082024-09-02', 'id082024-09-04', 'id082024-09-06', 'id082024-09-12', 'id082024-09-16', 'id082024-09-17', 'id092024-07-02', 'id092024-07-04', 'id092024-07-05', 'id092024-07-06', 'id092024-08-02', 'id092024-08-04', 'id092024-08-05', 'id092024-08-22', 'id092024-08-23', 'id092024-08-24', 'id092024-08-25', 'id092024-08-27', 'id092024-08-28', 'id092024-08-29', 'id102024-07-27', 'id102024-07-28', 'id102024-07-29', 'id102024-07-30', 'id102024-08-01', 'id102024-08-02', 'id102024-08-03']

In [ ]:
# 공통 하이퍼파라미터
common_params = {
    'boosting_type': 'dart',
    'learning_rate': 0.01,
    'n_estimators': 2000,
    'feature_fraction': 0.6,
    'bagging_fraction': 0.8,
    'bagging_freq': 1,
    'lambda_l1': 5,
    'lambda_l2': 1,
    'drop_rate': 0.1,
    'skip_drop': 0.5,
    'max_drop': 50,
    'uniform_drop': False,
    'verbosity': -1,
    'n_jobs': -1
}

# 모델별 세부 하이퍼파라미터
best_param_dict = {}

# 공통 하이퍼파라미터 대체 (이상한 모델의 경우)
best_param_dict['Q3'] = common_params
best_param_dict['S1'] = common_params
best_param_dict['S2'] = common_params
best_param_dict['S3'] = common_params
best_param_dict['Q1'] = common_params
best_param_dict['Q2'] = common_params

"""
# 평균 F1: 0.6402 / [상세] Q1(기상직후수면질):0.6945 Q2(취침전신체적피로):0.7679 Q3(취침전스트레스):0.6196 S2(수면효율):0.5726 S3(수면잠들기시간):0.6907 S1(S1):0.4962
# [OOF - Q1] F1 score: 0.7067
# [OOF - Q2] F1 score: 0.6989
# [OOF - Q3] F1 score: 0.6731
# [OOF - S2] F1 score: 0.6996
# [OOF - S3] F1 score: 0.7242
# [OOF - S1] F1 score: 0.5523
# [OOF] 평균 F1 score: 0.6758
"""

rst = {}
selected_features = [i for i in trn.columns if i not in drop_features2]
for topn in tqdm(range(5, len(selected_features) // 2, 5), desc="TOPN Loop"):
    print(f"\n# topn: {topn}")
    submission_final, oof_result, avg_f1, val_f1 = run_basemodel(
        trn[selected_features], tst[selected_features], valid_ids1,
        best_param_dict,
        topn=topn,
        n_splits=5,
        random_state=41,
        focal_loss=False,
        log_level=0,
        submit=False,
        get_oof=False,
        syn=sy[selected_features] if len(sy) > 0 else None
    )
    rst[topn] = (avg_f1, val_f1)

TOPN Loop:   0%|          | 0/9 [00:00<?, ?it/s]

# topn: 5

TOPN Loop:   0%|          | 0/9 [00:14<?, ?it/s]

KeyboardInterrupt:

In [ ]:
score_df = pd.DataFrame([
    {
        "topn": k,
        "avg_f1": v[0],
        "Q1": v[1][0],
        "Q2": v[1][1],
        "Q3": v[1][2],
        "S2": v[1][3],
        "S3": v[1][4],
        "S1": v[1][5],
    } for k, v in rst.items()
])
fname = 'score_df.xlsx'
score_df.to_excel(fname)
# files.download(fname)
score_df.head()

   topn  avg_f1     Q1     Q2     Q3     S2     S3     S1
0     5  0.6172 0.7038 0.6905 0.5956 0.5331 0.6617 0.5186
1    10  0.6187 0.6546 0.7524 0.6514 0.5495 0.6489 0.4555
2    15  0.6190 0.6919 0.7333 0.6578 0.5333 0.7260 0.3717
3    20  0.6451 0.6839 0.7331 0.6535 0.6324 0.7041 0.4636
4    25  0.6423 0.6945 0.7333 0.6411 0.6063 0.7348 0.4433

In [ ]:
best_rows = []
for col in ["Q1", "Q2", "Q3", "S2", "S3", "S1"]:
    row = score_df.loc[score_df[col].idxmax()]
    best_rows.append({
        "Target": col,
        "Best_Topn": int(row["topn"])
    })
best_topn = pd.DataFrame(best_rows)
best_topn = best_topn.set_index(['Target']).to_dict()['Best_Topn']
# best_topn: {'Q1': 95, 'Q2': 140, 'Q3': 45, 'S2': 175, 'S3': 15, 'S1': 5}
print(f'# best_topn: {best_topn}')

# best_topn: {'Q1': 55, 'Q2': 45, 'Q3': 35, 'S2': 45, 'S3': 30, 'S1': 5}

In [ ]:
"""
# 평균 F1: 0.6755 / [상세] Q1(기상직후수면질):0.7222 Q2(취침전신체적피로):0.7982 Q3(취침전스트레스):0.6830 S2(수면효율):0.6033 S3(수면잠들기시간):0.6992 S1(수면시간)):0.5471
[Q1]기상직후수면질 Q1_te2(1284), wake_time_diff(1144), Q1_te(802), beforebed_통화_time(600), wake_time(574), light_night_mean(572), wake_time_diff_lag1(425), img9(404), img4(399), img1(343)
[Q2]취침전신체적피로 Q2_te2(1544), Q2_te(757), activehour_total_screen_time(492), activehour_screen_time_vs_avg_pct(441), light_sleep_time_diff(392), beforebed_unique_bssid_count(349), img7(346), wake_time_lag1(301), rolling_wake_time_3d(292), activity_minutes(283)
[Q3]취침전스트레스 Q3_te2(1516), Q3_te(806), beforebed_top_bssid_count(800), free_hour_others_ratio(677), light_mean(596), light_sleep_time_lag2(582), beforebed_scan_count(569), work_hour_rssi_mean(555), sleep_duration_min_m_light_sleep_duration_min(548), beforebed_strong_signal_ratio(461)
[S2]수면효율 S2_te(1075), S2_te2(1049), wake_time_min(389), work_hour_unknown_ratio(359), img1(331), activehour_전화_time(321), mlight_first_wakeup_minutes(295), m_activity@240min@std@12h00m(276), work_hour_rssi_mean(269), activehour_screen_time_vs_avg_pct(260)
[S3]수면잠들기시간 S3_te(1893), S3_te2(1702), activehour_max_rssi(999), work_hour_rssi_max(819), S2_te2(459), beforebed_max_rssi(436), S2_te(365), beforebed_통화_time(309), Q1_te2(306), Q1_te(193)
[S1]수면시간 wake_time_diff(6404), S1_te(5855), S1_te2(4932), S2_te(3343), S2_te2(2331)
# /content/drive/MyDrive/data/submission_0.6754966856141595.csv 저장 완료
# 예측결과 비교표
학습sum	학습len	학습mean	테스트sum	테스트len	테스트mean
Q1	223	450	0.4956	136	250	0.5440
Q2	253	450	0.5622	152	250	0.6080
Q3	270	450	0.6000	166	250	0.6640
S1	390	450	0.8667	188	250	0.7520
S2	293	450	0.6511	154	250	0.6160
S3	298	450	0.6622	172	250	0.6880

train_distribution	submission_distribution
S1
0	0.3178	0.3240
1	0.4978	0.6000
2	0.1844	0.0760

# oof F1: 0.6870 / [상세] Q1(기상직후수면질):0.7222 Q2(취침전신체적피로):0.7111 Q3(취침전스트레스):0.6948 S2(수면효율):0.7211 S3(수면잠들기시간):0.7110 S1(S1):0.5619
"""
submission_final, oof_result, avg_f1, val_f1 = run_basemodel(
    trn[selected_features], tst[selected_features], valid_ids1,
    best_param_dict,
    topn=best_topn,
    n_splits=5,
    random_state= 41, # 41,
    focal_loss=False,
    log_level=1,
    submit=True,
    get_oof=True,
    syn=sy[selected_features] if len(sy) > 0 else None
)

# 평균 F1: 0.6864 / [상세] Q1(기상직후수면질):0.7122 Q2(취침전신체적피로):0.8000 Q3(취침전스트레스):0.6941 S2(수면효율):0.6546 S3(수면잠들기시간):0.7390 S1(수면시간):0.5186
[Q1] wake_time_diff(2089), light_rolling_wake_time_2d(1774), activehour_avg_rssi(1657), activehour_메신저_time(1625), wake_time_diff_lag1(1617), light_night_mean(1609), light_rolling_wake_time_3d(1581), Q1_te2(1547), work_hour_rssi_min(1507), work_hour_others_ratio(1459)
[Q2] charging_ratio(1999), m_activity_met@240min@sum@08h00m(1868), activehour_scan_count(1847), activehour_screen_time_vs_avg_pct(1768), m_activity_met@240min@sum@12h00m(1744), free_hour_unknown_ratio(1720), beforebed_max_rssi(1660), activehour_unique_bssid_count(1655), activehour_메신저_time(1648), light_day_mean(1616)
[Q3] light_sleep_duration_lag2(2172), free_hour_others_ratio(2117), light_sleep_duration_lag1(2117), beforebed_strong_signal_ratio(2061), work_hour_rssi_mean(2010), work_hour_rssi_min(1998), light_avg_sleep_duration(1981), light_mean(1972), light_rolling_sleep_time_3d(1959), light_rolling_sleep_duration_3d(1849)
[S2] activehour_unique_app_count(2202), light_sleep_time_lag1(1901), activehour_scan_count(1829), S2_te(1762), sleep_time_d_light_sleep_time(1732), light_sleep_time_lag2(1630), work_hour_unknown_ratio(1557), activehour_max_rssi(1553), beforebed_max_rssi(1513), activehour_top_bssid_count(1488)
[S3] activehour_max_rssi(3587), active_hour_max_speed(3280), active_hour_high_hr(3262), work_hour_rssi_max(3216), activehour_통화_time(3195), beforebed_max_rssi(2865), activehour_unique_app_count(2863), active_hour_walk_minutes(2283), activehour_전화_time(2165), light_month(2004)
[S1] wake_time_diff(16814), S2_te2(11377), S1_te(10617), S1_te2(9951), S2_te(9546)
# ./submission_0.6864098774576562.csv 저장 완료
# 예측결과 비교표

    학습sum  학습len  학습mean  테스트sum  테스트len  테스트mean
Q1    223    450  0.4956     140     250   0.5600
Q2    253    450  0.5622     137     250   0.5480
Q3    270    450  0.6000     164     250   0.6560
S1    390    450  0.8667     191     250   0.7640
S2    293    450  0.6511     167     250   0.6680
S3    298    450  0.6622     170     250   0.6800

    train_distribution  submission_distribution
S1
0               0.3178                   0.2800
1               0.4978                   0.6760
2               0.1844                   0.0440

LightGBMError: The number of features in data (5) is not the same as it was in training data (31).
You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.